만국박람회 [STEP1] 허황, 제리, 앨리
yagom-academy/ios-exposition-universelle pull request #108
Opened 2021-12-06 12:42 UTC by wooyani77

안녕하세요, 도미닉(@AppleCEO)

만국박람회 1모둠 허황, 제리, 앨리입니다! 🍎

STEP 1 요구사항 구현하여 고민했던 점과 질문 드리고 싶은 부분 정리해 PR 드립니다.

부족한 점이 많지만, 리뷰 잘 부탁드려요! 

---

## ❓고민했던 점

- enum func
    
    Parser 타입을 구현할 때 구조체나 클래스를 사용할 수도 있지만, 구조체나 클래스를 사용하면 다른 개발자가 구현을 찾아가서 확인하지 않는이상, 객체를 생성해버릴 수도 있다고 생각되어 enum 타입으로 구현하였습니다. 
    
- 접근제어
    
    타입을 구현할 때 프로퍼티에 직접 접근해서 사용하는것 보다 은닉화로 프로퍼티들을 숨기고 메서드로 프로퍼티에 접근할 수 있는 창구를 만들어주는 것이 적절하다고 생각했습니다. 그래서 접근제어를 설정하려고 하다보니 아래와같이 할 수 있을 것 같은데, 접근제어를 하려고 상수를 변수로 변경해주는 것이 상수의 이점을 사용하지 못하는 것 같다는 생각이 들었습니다. 지금은 접근제어가 필요하다고 생각되지 않아 설정을 해주지 않았습니다.
    
    ```swift
    // 현재 코드
    struct ExpoInformation {
        let title: String
        let visitors: Int
        let location: String
        let duration: String
        let description: String
    }
    
    // 시도해본 코드
    struct ExpoInformation {
        private(set) var title: String
        private(set) var visitors: Int
        private(set) var location: String
        private(set) var duration: String
        private(set) var description: String
    }
    ```
    
- decodable  프로토콜 채택
    
    `ExpoInformation`와 `ExpoEntry` 타입을 구현할 때, Codable protocol을 채택할지 `Decodable`만 채택할지 고민이 되었습니다. 해당 타입들이 JSON으로 encoding될 필요가 없다고 생각되어 Decodable protocol을 채택했습니다.
    
- `decode()` 메서드 테스트
    
    `decode()` 메서드를 구현하고나서 test case를 작성하는 과정에서 오류를 발견했습니다. 처음엔 아래와 같이 generic 타입의 배열을 반환하도록 구현했었는데요, test를 진행하다보니 `ExpoInformation`은 단일 요소이고 `ExpoEntry`는 배열이라서 기존의 방식으로는 test를 진행하는데 문제가 있었습니다. 해당 메서드의 반환타입을 아래와같이 수정해주는 방식으로 해결해보았습니다!
    
    ```swift
    // before
    static func decode(from jsonName: String) -> [Element]? { } 
    /* ... */
    let result = Parser<ExpoEntry>.decode(from: jsonName)
    
    // after
    static func decode(from jsonName: String) -> Element? { }
    /* ... */
    let result = Parser<[ExpoEntry]>.decode(from: jsonName)
    ```
    

---

## ❗️조언을 얻고 싶은 부분

- 그룹을 나누는 기준
    
    `Parser 열거형`은 데이터를 가진게 아닌 데이터를 가공하는 역할을 가진 열거형입니다.
    
    모델에 가까운 거 같아 모델 그룹에 넣어주긴 했지만 모델이라고 하기엔 뭔가 애매한거 같습니다.
    
    이전 계산기 프로젝트를 진행할 땐 계산 역할을 하는 클래스의 경우 Service라는 그룹을 만들어서 넣었습니다. 
    
    그룹을 분리하는 기준이 MVC로 나누기엔 조금 애매한 것 같은데 도미닉의 생각이 궁금합니다!🤔
    
    또 주로 사용하는 그룹명(Service, Error 등)이 있으신가요??😊
    

---

2021-12-06 14:42 UTC, AppleCEO requested changes
안녕하세요 도미닉입니다
허황, 제리, 앨리 고생하셨습니다!
PR 속도가 빨랐습니다~

- 그룹을 나누는 기준
그룹을 분리하는 기준이 MVC로 나누기엔 조금 애매한 것 같은데 도미닉의 생각이 궁금합니다!🤔
또 주로 사용하는 그룹명(Service, Error 등)이 있으신가요??😊

저는 모델에 넣습니다.
JSON 으로 받아오는 데이터들은 모델의 역할을 하기 때문입니다. 레이웬더리치의 예제 코드에서도 모델 객체에서 네트워크에서 받아오는 코드를 메소드로 작성하는 경우를 본 적이 있습니다. 참고해보시면 좋겠습니다!

2021-12-06 14:42 UTC, AppleCEO commented on Expo1900/Expo1900/Model/ExpoEntry.swift
> +}
Decodable 과 CodingKeys 를 사용해보셨군요! 👍 
저는 CodingKeys 는 Decodable 과 연관이 있다고 생각하는데요.
이렇게 다른 extension 으로 빼낸 이유가 있을까요?

2021-12-06 14:42 UTC, AppleCEO commented on Expo1900/Expo1900/Model/ExpoInformation.swift
> +extension ExpoInformation: Decodable { }
모델 역할을 하는 구조체에는 Decodable 혹은 Codable 을 바로 채택하는 경우가 많은 것 같습니다.
이 구조체의 역할은 Decodable 만 하는 것이기 때문인데요.
이렇게 extension 으로 빼내면 이 구조체가 단지 프로퍼티들을 가지는 것인지 Decodable 을 위한 프로퍼티들인지 아래 11번째 줄까지 확인해야 할 것 같습니다.
그리고 extension 이 한 줄로 줄어져있어서 만약 11번째 줄을 실수로 읽지 않는다면 이 구조체가 Decodable을 채택했는지도 헷갈릴 수 있을 것 같네요 🔢

2021-12-06 14:42 UTC, AppleCEO commented on Expo1900/Expo1900/Model/Parser.swift
> +    }
코드들이 명료하고 어떤 역할을 하는지 정확합니다 💯

2021-12-06 14:42 UTC, AppleCEO commented on Expo1900/Expo1900/Model/Parser.swift
> +    }
추가로 decoder 라는 상수명은 어떤 것을 해독하는지 불명확한 것 같습니다.
JSON 을 디코딩하는 역할이 이름에 드러나면 좋겠습니다!
저는 이 변수가 한번만 쓰일 때는 상수에 넣지 않고 아래처럼 한 줄로 표현하기도 하는데 이 부분 고민해보면 좋겠습니다~
let products = try? JSONDecoder().decode(Element.self, from: data.data)

2021-12-06 14:42 UTC, AppleCEO commented on Expo1900/Expo1900Tests/ParserTests.swift
> +class ParserTests: XCTestCase {
테스트 코드를 작성한 것 좋습니다~ 🥇

2021-12-07 01:21 UTC, llghdud921 commented on Expo1900/Expo1900/Model/ExpoInformation.swift
> +extension ExpoInformation: Decodable { }
가독성을 고려해서 분리를 해보았는데요! 
실수를 방지하는 것이 더 중요하다 생각해서 수정하였습니다 :)

2021-12-07 01:23 UTC, hwangjeha commented on Expo1900/Expo1900/Model/ExpoEntry.swift
> +}
따로 빼서 작성한 이유는 코드를 깔끔하게 작성하려고 따로 빼줬습니다😭
도미닉께서 현재 코멘트와 아래 코멘트에서 설명해주신 대로 연관있는 코드는 같이 작성하는게 가독성을 고려했을 때 더 좋은 방법인 것 같습니다😊

2021-12-07 01:37 UTC, wooyani77 commented on Expo1900/Expo1900/Model/Parser.swift
> +    }
말씀해주신대로 한줄로 작성해도 좋을 것 같습니다ㅎㅎ! `let products = try? JSONDecoder().decode(Element.self, from: data.data)` 해당방법으로 수정했습니다~

2021-12-07 01:53 UTC, llghdud921 commented
안녕하세요 도미닉
코멘트 정말 감사합니다 :)

추가로 구현한 부분이 있어서 간략하게 말씀드립니다.

- NSDataAssetName 확장
   하드코딩 하지 않고 실수를 방지하기 위해서 NSDataAssetName을 확장하여 Assets내 파일의 이름을 정의하였습니다. 
```
extension NSDataAssetName {
    static let expositionUniverselle1900: NSDataAssetName = "exposition_universelle_1900"
    static let items: NSDataAssetName = "items"
}
```

2021-12-07 02:49 UTC, merged