만국박람회 [STEP2] 요한, 조이
yagom-academy/ios-exposition-universelle pull request #116
Opened 2021-12-09 07:16 UTC by na-young-kwon

안녕하세요 쿠마 @leejun6694 🍠
만국박람회 9조 요한과 조이 입니다
STEP2도 예상보다 빨리 완성하게 되어서 pr보냅니다~!

## 📝 STEP2 목표
STEP2는 STEP1에서 매칭했던 모델들로 UI를 구성하는 것이 목표입니다 
***(오토레이아웃은 STEP3에서 적용됩니다)***

총 3개의 화면으로 구성됩니다

### 1. 시작 화면 (박람회 소개)
박람회 정보를 저장하는 `Exposition`의 정보를 읽어와 **스크롤뷰** 형태로 보여주고 스크롤 최하단에는 **다음 화면으로 이동하는 버튼**이 존재합니다

### 2. 출품작 소개 화면
출품작 정보를 저장하는 `Entry`를 읽어와 **Table View**로 보여줍니다
각 cell은 출품작의 **사진/이름/간단설명**을 포함하며 클릭하면 해당 출품작의 상세 정보 화면으로 이동합니다

### 3. 출품작 상세 정보 화면
'시작 화면'과 유사하게 **스크롤뷰** 형태로 선택된 출품작의 **사진/상세설명**을 보여줍니다

<br>

## 🧐 신경쓴 점
### 1. 구체적인 모델링
뷰컨트롤러가 너무 많은 역할을 하지 않도록 방문객 / 개최지 / 개최기간을 모델인 `Exposition` 에서 가공했습니다. 뷰컨트롤러에서는 모델에 있는 데이터를 바로 쓸 수 있도록 모델링을 하여 뷰컨트롤러의 역할을 나눠주었습니다.

- 변경 전
```swift
private func setLabels(from exposition: Exposition) {
        titleLabel.text = expostion.title
        visitorsLabel.text = "방문객 : \(expostion.visitors)"
        locationLabel.text = "개최지 : \(expostion.location)"
        durationLabel.text = "개최 기간 : \(expostion.duration)"
        descriptionLabel.text = expostion.description
    }

```

- 변경 후
```swift
private func setLabels(from exposition: Exposition) {
        titleLabel.text = exposition.title
        visitorsLabel.text = exposition.visitorsDescription
        locationLabel.text = exposition.locationDescription
        durationLabel.text = exposition.durationDescription
        descriptionLabel.text = exposition.description
    }
```

<br>

### 2. 에러타입 정의
JSON 파싱중에 나올 수 있는 에러를 처리하기 위해 에러타입을 정의하고 associated value로 filename을 받습니다. 에러발생시 filename을 알려서 구체적으로 어떤 파일 때문에 발생한 에러 인지 알 수 있도록 구현했습니다.

<br>

### 3. 기획서에 맞게 화면 구성하기
**✔️ 문제**
기획서를 보면 네비게이션 상단이 반투명한 회색이고, 화면을 스크롤할 때 네비게이션바 뒤로 사진이 비치는 모습을 볼 수 있습니다. 
하지만 저희가 만든 App에서는 **네비게이션 바 뒤로 사진이 비치지 않는 문제가 있었습니다.**

**✔️ 해결**
네비게이션 바의 투명도 문제가 아닌, 애초에 스크롤뷰의 크기를 화면에 꽉차게 구성하지 않았던 점이 문제였습니다.
구체적으로는 제약을 걸 때 `constraint to margins` 이 항목을 체크해서 스크롤뷰의 top attribute를 superview에 맞추더라도 margin이 생겨버렸기 때문이었습니다.
`constraint to margins` 항목을 체크해제 해서 문제를 해결했습니다.

<br>

## 😵‍💫 궁금한 점

### Q1. cellForRowAt 안에서 너무 많은 작업을 하고 있는 것 같아요

**✔️ 직면했던 문제**
cellForRowAt 메서드는 빈번히 호출되기에 최대한 가볍게 설계하려고 목표했는데 현재 코드에서는 너무 많은 작업을 하고 있는 것 같다고 느꼈습니다

```swift
override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "entryCell", for: indexPath)
    
    // 너무 많은 작업을 하고있다고 생각하는 부분
        var content = cell.defaultContentConfiguration()    
        let entry = entries[indexPath.row]
        content.text = entry.name
        content.secondaryText = entry.shortDescription
        content.image = UIImage(named: entry.imageName)
        cell.contentConfiguration = content
        
        return cell
    }
```

**✔️ 생각해본 해결 방법**
지금은 테이블뷰에서 기본 제공하는 셀을 사용하고 있는데, 스텝3에서 오토레이아웃을 위해 커스텀 셀 타입을 정의하게 될 것 같습니다. 커스텀 셀을 만들면 해당 클래스 `awakeFromNib()` 에서 해당 작업을 해줄수도 있는 것 같습니다. 

**✔️ 궁금한 점**
커스텀 셀 클래스에서 해당 작업을 해주는 것이  `cellForRowAt()` 에서 해주는 것 보다 성능상으로 더 이점이 있는지 궁금합니다.
혹은 저희가 생각하지 못한 다른 방법이 있는지 궁금합니다.

<br>

### Q2. 뷰컨 인스턴스 생성 시점과 IBOutlet이 채워지는 시점은 어떻게 차이가 있나요?

#### ✔️ 직면했던 문제
'출품작 Table 화면' 뷰컨에서 '출품작 상세정보 화면' 뷰컨으로 출품작 정보를 넘겨주기 위해 스토리보드로 segue를 만들고 `performSegue()` 메서드 호출과 함께 아래와 같이`prepare` 메서드를 활용하였습니다

하지만 `prepare`가 호출되는 시점에는 아래와 같이 
segue의 다음화면에 대한 뷰컨 인스턴스(`entryDetailViewController`)는 만들어졌으나 
IBOutlet 프로퍼티(`entryDescription`)는 채워지지 않고 nil인 상태였습니다
```swift
override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    guard let entryDetailViewController = segue.destination as? EntryDetailViewController,
          let entryDescription = sender as? UILabel else { return }

    //runtime Error!
    entryDetailViewController.entryDescription = entryDescription
}
```

#### ✔️ 임시 문제 해결

IBOutlet 프로퍼티가 아닌 별도의 프로퍼티(`entry`)를 만들어 전달해줌으로써 해결하였습니다

```swift
override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    guard let entryDetailViewController = segue.destination as? EntryDetailViewController,
          let entry = sender as? Entry else { return }

    entryDetailViewController.entry = entry
}
```

#### ✔️ 궁금한 점
위로 미루어보아 뷰컨인스턴스의 생성시점과 IBOutlet 프로퍼티가 채워지는 시점이 다름을 알 수 있었습니다 
*(prepare() 메서드는 그 사이에 호출됨)*

**`performSegue()`가 호출되었을 때, 뷰컨 인스턴스가 언제 생성되고, IBOutlet 프로퍼티는 언제 초기화되는지, 그리고 prepare() 메서드는 언제 호출되는지 알아보려면 어떤 키워드로 찾아보면 될까요?**

2021-12-09 13:36 UTC, leejun6694 requested changes
요한, 조이 안녕하세요 : )
step 2 를 구현하느라 고생 많으셨습니다.
몇가지 리뷰를 남겼는데, 코드 작성 스타일(?) 관련해서는 회의실에서 같이 얘기해봐요~~!

2021-12-09 13:36 UTC, leejun6694 commented on Expo1900/Expo1900/EntryTableViewController.swift
> +    private func parseEntriesFromAsset() {
코드 작성 순서가 정리되면 좋을 것 같습니다.
현재는 property 가 맨 위에 작성되는 것 외엔, 규칙이나 구분이 없네요.
여러 방법이 있겠지만, 시간될 때 같이 회의실에서 얘기해봐요 : )

2021-12-09 13:36 UTC, leejun6694 commented on Expo1900/Expo1900/EntryTableViewController.swift
> +        navigationController?.setNavigationBarHidden(false, animated: true)
빠진 코드가 있습니다.
빠져도 상관 없는데, 왜 필요한 걸까요?

2021-12-09 13:36 UTC, leejun6694 commented on Expo1900/Expo1900/EntryTableViewController.swift
> +        let entry = entries[indexPath.row]
index 안전할까요...?

2021-12-09 13:36 UTC, leejun6694 commented on Expo1900/Expo1900/EntryTableViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "entryCell", for: indexPath)
string 값들을 직접 입력하는 것은 때론 위험할 수도 있습니다.
어느 한 곳에서 정리해주는 것이 도움될 수도 있겠네요~~!

2021-12-09 13:36 UTC, leejun6694 commented on Expo1900/Expo1900/Expo1900Error.swift
> +enum Expo1900Error: Error, CustomStringConvertible {
👍👍

2021-12-09 13:36 UTC, leejun6694 commented on Expo1900/Expo1900/Model/Exposition.swift
> +        self = try JSONDecoder.shared.decode(Exposition.self, from: data.data)
`data.data` 는 조금 어색하네요...ㅎㅎ

2021-12-09 13:36 UTC, leejun6694 commented on Expo1900/Expo1900/Model/Entry.swift
> +import UIKit
`UIKit` 을 import 해준 이유가 있을까요?

2021-12-09 13:36 UTC, leejun6694 commented on Expo1900/Expo1900/Extension_Int.swift
> +import Foundation
file 명도 같이 얘기해봐요ㅎㅎ

2021-12-09 13:36 UTC, leejun6694 commented on Expo1900/Expo1900/EntryDetailViewController.swift
> +        self.navigationItem.title = entry?.name
생략 가능한 코드를 통일성 있게 작성하면 좋을 것 같습니다 : )

2021-12-09 13:36 UTC, leejun6694 commented on Expo1900/Expo1900/EntryDetailViewController.swift
> +    @IBOutlet private weak var entryDescription: UILabel!
UI component naming 도 통일성이 있으면 좋겠네요~!

2021-12-10 06:22 UTC, YohanBlessYou commented on Expo1900/Expo1900/EntryDetailViewController.swift
> +    @IBOutlet private weak var entryDescription: UILabel!
suffix로 타입을 적어주는 컨벤션을 알고 있었는데 깜빡했네요 😅 
두 IBOutlet 프로퍼티에 `ImageView` / `Label`를 붙혀주었습니다!

2021-12-10 06:31 UTC, na-young-kwon commented on Expo1900/Expo1900/EntryTableViewController.swift
> +    private func parseEntriesFromAsset() {
코드 순서를 전체적으로 재배치 했어요.
`IBOutlet - 프로퍼티 - 라이프사이클 메서드` 순으로 배치했고, 주석도 추가해주었습니다.
테이블뷰 관련 메서드들도  extension으로 빼서 구분해주었습니다.
이전보다 좀 더 깔끔해지고 읽기도 수월한 것 같아요😀

2021-12-10 06:32 UTC, YohanBlessYou commented on Expo1900/Expo1900/EntryDetailViewController.swift
> +        self.navigationItem.title = entry?.name
저희 나름대로 스타일을 정하고 근거를 생각해보았습니다!

**우선, 저희도 self를 생략하는 방향으로 선택하였습니다**
첫 번째 이유는, 말씀해주셨던 것처럼 self를 반드시 써주어야 하는 부분과 구분이 되도록 하기 위함이고
두 번째 이유는, 생략가능한 self를 전부 붙혀주는건 기본적으로 비효율적이므로 굳이 써야할 이유가 없다면 생략하는게 맞다고 판단했습니다

2021-12-10 06:33 UTC, YohanBlessYou commented on Expo1900/Expo1900/Extension_Int.swift
> +import Foundation
말씀해주신대로 "타입명+Extension" 포맷으로 통일하였습니다!

2021-12-10 06:34 UTC, YohanBlessYou commented on Expo1900/Expo1900/Model/Entry.swift
> +import UIKit
해당 파일에서 필요한 경우에만 import를 해주도록 모든 파일에서 통일하였습니다

경우에 따라 Model에서도 UIKit의 일부 모듈이 필요한 경우가 있는데 `import UIKit.NSDataAsset` 이런식으로 필요한 모듈만 가져오도록 변경하였습니다

2021-12-10 06:36 UTC, YohanBlessYou commented on Expo1900/Expo1900/Model/Exposition.swift
> +        self = try JSONDecoder.shared.decode(Exposition.self, from: data.data)
저희도 아차 싶었습니다ㅎㅎ...

위 코드는 Exposition 인스턴스의 소스가 될 JSON이므로 역할을 명시해주기 위해 `expositionJSON`으로 변경하였습니다

2021-12-10 06:37 UTC, YohanBlessYou commented on Expo1900/Expo1900/EntryTableViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "entryCell", for: indexPath)
JSONAsset 파일이름의 경우, 별도의 열거형으로 정리해주었었는데요~

cell과 segue의 경우 특정 뷰컨에서만 사용하므로 뷰컨의 상수 프로퍼티로 정의해주었습니다!

2021-12-10 06:45 UTC, na-young-kwon commented on Expo1900/Expo1900/EntryTableViewController.swift
> +        navigationController?.setNavigationBarHidden(false, animated: true)
```swift
override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
}
```
이렇게 수정 했습니다.

super는 부모클래스를 의미합니다. 따라서 오버라이딩 할 때 부모의 작업을 실행하지말지 선택하는 것이기 때문에 코드가 없어도 컴파일 에러를 유발하진 않습니다. 
super.viewWillAppear는 빈 메서드 이지만 애플이 나중에 뷰에 필요한 코드를 추가할 수도 있으므로 일단 적어주는게 좋습니다.


<img width="554" alt="스크린샷 2021-12-10 오후 3 43 53" src="https://user-images.githubusercontent.com/74536728/145529500-24bc54da-5cd4-435c-bfa0-e7b6fe9b4ad8.png">
(공식문서를 보면 반드시 호출하라고 적혀있기도 합니다!)

2021-12-10 06:50 UTC, na-young-kwon commented on Expo1900/Expo1900/EntryTableViewController.swift
> +        let entry = entries[indexPath.row]
말씀해주신 키워드로(`Swift array safe index`) 검색해봤어요
여러 방법 중 subscript를 추가해서 배열에 접근하도록 수정했습니다.
```swift
extension Array {
    subscript(index index: Int) -> Element? {
        return indices.contains(index) ? self[index] : nil
    }
}
```
index를 포함하는지 확인한 후 요소를 옵셔널 타입으로 리턴하도록 코드를 작성했보았습니다😀

2021-12-13 07:43 UTC, leejun6694 approved these changes
LGTM

2021-12-13 07:44 UTC, leejun6694 commented
피드백 내용도 잘 반영해주셨네요. 감사합니다 : )
step 2 구현 고생하셨습니다~!

2021-12-13 07:44 UTC, merged