만국박람회 [STEP 2] 앨리, 허황, 제리
yagom-academy/ios-exposition-universelle pull request #119
Opened 2021-12-10 09:40 UTC by llghdud921

안녕하세요, 도미닉(@AppleCEO)

만국박람회 1모둠 허황, 제리, 앨리입니다! 🍎

STEP 2 구현완료하여 PR 드립니다.

autoLayout을 조금 구현하긴 했지만 step3에서 완성할 예정입니다.
부족한 점이 많지만, 리뷰 잘 부탁드려요!

<br/>

## 💡 구현 내용

- 구현하기전 UML을 그리고 UML을 토대로 구현해 봤습니다.
    
![%EB%A7%8C%EA%B5%AD%EB%B0%95%EB%9E%8C%ED%9A%8C%20SETP2%20UML](https://user-images.githubusercontent.com/40068674/145551645-a5f77ae2-9a96-462d-a41f-56a567a9bc39.png)

 
## ❓고민했던 점

- UIButton의 title이 변경되는 문제
    
    기존 방식으로 했을 때는 클릭을 했을 때 버튼의 타이틀이 바뀌는 것을 확인했습니다. `setTitle()` 메소드를 적용하여 바뀌지 않도록 바꿔주었습니다.
    
    ```swift
    // 기존방식 - 버튼을 클릭하면 텍스트가 바뀜
    button.titleLabel?.text = "한국의 출품작 보러가기"
    
    // 변경 후 - 클릭했을 때 텍스트가 변하지 않음
    button.setTitle("한국의 출품작 보러가기", for: .normal)
    ```
    
    `setTitle` 메소드를 처음 사용해봐서 버튼 상태에 따른 타이틀 변경에 대한 테스트를 해보았는데 `hightlighted`만 적용이 되는 것 같습니다. 어떤 경우에 UIState를 적용하는지, 또 자주 사용되는 state가 있는지 궁금합니다!
    
    ```swift
    button.setTitle("한국의 출품작 보러가기", for: .normal)
    button.setTitle("selected", for: .selected)
    button.setTitle("highlighted", for: .highlighted)
    button.setTitle("application", for: .application)
    button.setTitle("disabled", for: .disabled)
    button.setTitle("focused", for: .focused)
    button.setTitle("reserved", for: .reserved)
    ```
    
![Simulator%20Screen%20Recording%20-%20iPhone%2012%20Pro%20-%202021-12-09%20at%2015 24 01](https://user-images.githubusercontent.com/40068674/145551842-cf8a8b1d-aae8-4cb0-812c-a016d19efa0c.gif)

<br/>

- `awakeFromNib()`
    
    CustomView를 만들어서 그 안에 IBOutlet으로 View와 연결해 해당 뷰들을 지정해주는 방식을 사용했습니다.
    
    `awakeFromNib()`을 사용하기전 CustomView 내부 `init()`에서 `setUp()` 메소드를 사용하여 초기설정을 하려 했으나 
    
    오류가 발생해 원인을 찾아봤습니다.
    
    뷰 컨트롤러 `loadView()`메소드가 호출되기 전 CustomView 내부 `init()`이 먼저 호출되어
    
    메모리 올라가지 않은 뷰에 접근하려 해서 생긴 문제였습니다.
    
    `awakeFromNib()` 에 대해 찾아보니 뷰가 인스턴스화 된 직후 호출되는 메소드 였습니다.
    
    커스텀 뷰 초기설정 `awakeFromNib()`내부에서 호출해 줬습니다.
    
    ```swift
    override func awakeFromNib() {
        super.awakeFromNib()
        setUp() // 커스텀 뷰 초기 설정하는 메소드
    }
    ```
    <br/>

- ViewController에서 View의 속성들을 설정을 해주어야할지 고민이 되었습니다.
    
    아래와같이 초기 데이터를 설정 해주는 `setUp()` 내부에서 `setUpStyle()`을 호출하는게 적절한 것인지 도미닉의 생각이 궁금합니다.
    
    ```swift
    func setUp(data: ExpoInformation) {
    		setUpStyle() 
    		// setUp(data:) 메소드는 초기 데이터를 설정해 주는 곳인데 setUpStyle() 함수가 여기서 호출되는게 맞나
    		// 뷰컨에서 호출해 주는게 맞나
    
        titleLabel.text = data.title
        posterImageView.image = UIImage(named: "poster")
        visitorsLabel.text = "방문객 : " + DecimalNumberFormatter.string(for: data.visitors) + " 명"
        locationLabel.text = "개최지 : " + data.location
        durationLabel.text = "개최 기간 : " + data.duration
        descriptionLabel.text = data.description
    }
        
    func setUpStyle() {
        self.spacing = 10
          
        titleLabel.textAlignment = .center
        visitorsLabel.textAlignment = .center
        locationLabel.textAlignment = .center
        durationLabel.textAlignment = .center
            
        titleLabel.numberOfLines = 2
        descriptionLabel.numberOfLines = 0
            
        titleLabel.font = .preferredFont(forTextStyle: .title1)
    }
    ```

<br/>
    
- 네비게이션 컨트롤러 활성화/비활성화 호출 위치
    
    첫번째 main 화면에서는 navigation Bar Item을 나타내지 않기 위해서 ViewLifeCycle 메소드를 이용해 `isNavigationBarButton` 속성을 이용하였습니다.
    
    - ViewWillAppear : 화면이 나타나기 전에 navigationBarButton을 숨김
    - viewWillDisappear : 화면이 사라지고 나서 navigationBarButton를 나타냄
    
    ```swift
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.navigationController?.isNavigationBarHidden = true
    }
        
    override func viewWillDisappear(_ animated: Bool) {
        viewWillDisappear(animated)
        self.navigationController?.isNavigationBarHidden = false
    }
    ```
    <br/>

## 💢 해결이 되지 않은 점

- xib 파일에 연결된 클래스 내부 @IBAction 동작하지 않는 이유
    
    커스텀 뷰를 만들 때 xib 파일로 만들려고 했습니다.
    
    xib 파일을 만들어 본 캠퍼가 없어 같이 학습하던 중 아래와 같은 에러가 발생했습니다.
    
    에러 메세지 :`unrecognized selector sent to instance`
    
    xib 파일에 클래스도 잘 등록되어 있는 것을 확인했습니다.
    
    원인에 대해서 감이 오지 않는데 저희가 학습해야 할 키워드가 있을까요?
    
<img width="500" alt="%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202021-12-09%20%EC%98%A4%ED%9B%84%203 58 46" src="https://user-images.githubusercontent.com/40068674/145552031-b72fe45f-5a69-4ef3-a8bd-4b04ca24ed01.png">
  

## ❗️조언을 얻고 싶은 부분

- `awakeFromNib()`
    
    `awakeFromNib()` 메소드를 xib파일로 커스텀 뷰를 구성할 때 알게 됐습니다.
    
    메소드 명에 `Nib`라는 키워드가 있어서 xib, nib 파일에서만 사용이 가능한 줄 알았는데 커스텀 뷰 클래스 내부에서 사용이 가능하더라구요. 
    
    혹시 커스텀 뷰가 인스턴스화 될 때 xib, nib 형태로 변환이 되는지 궁금합니다.

<br/>    

- 셀 구성 방법
    1. defaultContentConfiguration(iOS 14 이상)
    2. `커스텀 셀`
    
    셀을 구성할 때 iOS 14이상에서는 `defaultContentConfiguration`를 사용해서 셀을 구성해야하는건지
    
    `커스텀 셀`을 만들어서 구성해야 할 지 고민이 됐습니다.
    
    `defaultContentConfiguration`를 사용해서 구성했을 때 원하는 모양의 뷰를 만들기가 어려워 `커스텀 셀`을 만들어 작업했습니다.
    
    `defaultContentConfiguration`를 사용해서 원하는 모양의 뷰를 만들 수 있다면 `defaultContentConfiguration`를 사용해도 괜찮은걸까요?
    
<img width="800" alt="%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202021-12-10%20%EC%98%A4%ED%9B%84%203 17 14" src="https://user-images.githubusercontent.com/40068674/145552249-c1b8bba3-8045-41a6-a796-7b01f461a256.png">

---

2021-12-12 11:17 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
고생 많으셨습니다.
코멘트들보고 개선해보면 좋겠습니다.

- xib 파일에 연결된 클래스 내부 @IBAction 동작하지 않는 이유

비슷한 내용인 것 같은데 이 글 확인해보셨을까요? https://worldseawater.tistory.com/101
<unrecognized selector sent to instance swift> 이라고 검색했는데 한글 자료들도 많이 나오네요~
제가 아래 링크의 프로젝트에서 xib 를 사용해봤었는데 참고해보시고 더 구체적으로 질문해주시면 좋겠습니다!
https://github.com/AppleCEO/yogiyo

- 혹시 커스텀 뷰가 인스턴스화 될 때 xib, nib 형태로 변환이 되는지 궁금합니다.

아래 링크들 참고해서 직접 정리를 해보면 좋겠습니다. 조금 더 의견을 정리해서 이게 맞나요? 라고 물어보는 것이 더 좋은 방식일 것 같습니다. <커스텀 뷰 awakeFromNib()> 이라고만 검색해도 많은 글들이 나오네요!
http://codershigh.dscloud.biz:30004/t/awakefromnib/107/3
https://zeddios.tistory.com/298?category=682195

- defaultContentConfiguration를 사용해서 원하는 모양의 뷰를 만들 수 있다면 defaultContentConfiguration를 사용해도 괜찮은걸까요?

defaultContentConfiguration 을 사용해보지 않아서 정확하게 답변은 못드리겠지만 같은 역할을 하는 것이라면 사용해도 괜찮을 것 같습니다. 다만 iOS 13 이하를 지원한다면 분기 처리를 해서 둘 다 구현을 한다던지 대비가 필요할 것 같습니다!
아래 글에 잘 설명되어 있는 것 같은데 참고해보시면 좋겠습니다.
https://unnnyong.me/2020/07/05/wwdc-2020-modern-cell-configuration/

2021-12-13 05:46 UTC, llghdud921 commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    @IBOutlet private weak var detailStackView: EntryDetailStackView!
네 조언 감사드립니다. entryDetailStackView 로 변수명 변경했습니다!

2021-12-13 05:58 UTC, hwangjeha commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +        detailStackView.setUp(data: data)
setUpView(from data: ExpoEntry)로 변경했습니다😊
아래 남겨주신 같은 내용 코멘트도 반영하겠습니다.

2021-12-13 06:00 UTC, wooyani77 commented on Expo1900/Expo1900/View/EntryDetailStackView.swift
> +    func setUp(data: ExpoEntry) {
위에 말씀해주신 것과 동일하게 수정했습니다! :)

2021-12-13 06:06 UTC, wooyani77 commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +        self.title = data.name
self 키워드로 자신을 명시하도록해서 명확성을 보장해주려는 의도였습니다. 그런데 일관성 없게 키워드를 붙여준 것 같다는 생각이 들어서 꼭 필요한 부분이 아니면 붙이지 않는 것으로 의견을 모았습니다!

2021-12-13 06:09 UTC, llghdud921 commented on Expo1900/Expo1900/View/EntryDetailStackView.swift
> +        entryDescriptionLabel.numberOfLines = 0
위에서 답변드린것처럼 명확성을 위해 self를 붙였지만 꼭 필요한 부분에만 self를 붙이는 것으로 정하였습니다! 
감사합니다:)

2021-12-13 06:30 UTC, wooyani77 commented on Expo1900/Expo1900/View/CustomButtonStackView.swift
> +    @IBOutlet private weak var button: UIButton!
button의 네이밍은 역할을 명확히 해줄 수 있는 변수명인 `entryListButton` 으로 수정해주었습니다! 추가적으로 `CustomButtonStackView`라는 클래스 네이밍도 `EntryListButtonStackView` 로 수정했습니다.

2021-12-13 07:58 UTC, llghdud921 commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        expoEntries = Parser<[ExpoEntry]>.decode(from: .items) ?? []
네 이부분 코드를 개선해보았습니다!

- EntryListViewController 내부에 expoEntries property를 제거하고 외부에 ExpoEntries model type을 생성하였습니다.
- EntryListViewController 내부에서 ExpoEntries.list 타입 프로퍼티에 직접 접근해서 데이터를 활용하는 로직으로 개선하였습니다.

2021-12-13 07:59 UTC, wooyani77 commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +}
좀 깔끔하게 보이려고 extension으로 분리해줬습니다! 그런데 도미닉이 말씀해주신 것처럼 중요하지 않은 메소드 착각할 수 도 있겠다는 생각이 들어요! extension 삭제하고 다시 합쳐주었습니다 :)

2021-12-13 08:00 UTC, wooyani77 commented on Expo1900/Expo1900/Controller/ViewController.swift
>  }
이부분도 바로 위의 코멘트처럼 extension 삭제해주었고 ViewController의 네이밍도 `ExpoInformationViewController`로 좀 더 명확히 해주었습니다!

2021-12-13 08:01 UTC, hwangjeha commented on Expo1900/Expo1900/View/InformationStackView.swift
> +        titleLabel.font = .preferredFont(forTextStyle: .title1)
관련있는 기능을 개행으로 나눴습니다.
```swift
// 커스텀 스택 뷰의 자식 뷰들 간격 조정
spacing = 10
// Label 정렬 
titleLabel.textAlignment = .center
visitorsLabel.textAlignment = .center
locationLabel.textAlignment = .center
durationLabel.textAlignment = .center
// Label 라인 수 지정
titleLabel.numberOfLines = 2
descriptionLabel.numberOfLines = 0
// Label 폰트 지정
titleLabel.font = .preferredFont(forTextStyle: .title1)
```
주석으로 나눈 기준 적어봤습니다😊

2021-12-13 08:13 UTC, wooyani77 commented on Expo1900/Expo1900/View/InformationStackView.swift
> +class InformationStackView: UIStackView {
`ExpoInformationStackView`로 수정해주었습니다~

2021-12-13 08:13 UTC, llghdud921 commented on Expo1900/Expo1900/Model/DecimalNumberFormatter.swift
> +        return formatter.string(for: obj) ?? String()
네! 
DecimalNumberFormatter 내부에서 옵셔널을 처리하는 것 보다는 해당 메소드를 사용할 때 옵셔널 변수를 바인딩하는 것이 명확할 것 같아서 아래와 같이 코드 개선하였습니다.
```swift
if let visitors = DecimalNumberFormatter.string(for: data.visitors) {
            visitorsLabel.text = "방문객 : " + visitors + " 명"
        }
```

2021-12-13 08:56 UTC, hwangjeha commented
> 1. xib 파일에 연결된 클래스 내부 @IBAction 동작하지 않는 이유
> 
> 
> 
> 2. 혹시 커스텀 뷰가 인스턴스화 될 때 xib, nib 형태로 변환이 되는지 궁금합니다.
> 
>

1. 질문에 적진 않았지만 addTarget을 사용해서 버튼 이벤트를 연결시켜 동작하는건 확인해봤습니다. 
IBAction으로 이벤트를 연결하는 부분은 여전히 되지 않고 있습니다.
아직 xib파일에 대해서 이해가 부족한 것 같습니다.
도미닉 깃헙에 있는 예제와 링크를 토대로 xib에 대해 공부해보도록 하겠습니다😭

2. 첨부해주신 아래 링크랑 다른 자료 참고해서 정리해보고 추가적인 질문사항이 생기면 다시 질문 드리겠습니다.
링크 감사합니다😊

2021-12-13 13:41 UTC, AppleCEO commented on Expo1900/Expo1900/View/InformationStackView.swift
> +        titleLabel.font = .preferredFont(forTextStyle: .title1)
저는 특별한 경우가 아니라면 주석을 사용하지 않습니다.
만약 코드를 수정해야하면 그에 따라서 주석도 같이 수정해줘야하기 때문입니다.
주석이나 코드 둘 중 하나만 수정하게 되면 코드를 이해하기 힘들어질 것입니다.
이 내용은 <클린 코드> 라는 책에서 읽은 내용입니다 ㅎㅎ
제가 의도한 것은 이렇게 빈칸을 중간에 주는 것은 주석에서 적으신 것처럼 조금씩 다른 동작(역할)을 수행하는 것으로 생각이 들어서 입니다.
한 메소드에서 하나의 동작만을 수행하는  것이 좋습니다.
어떻게 개선해 볼 수 있을까요?

2021-12-13 13:43 UTC, AppleCEO commented on Expo1900/Expo1900/View/EntryDetailStackView.swift
> +        entryDescriptionLabel.numberOfLines = 0
참고로 https://github.com/StyleShare/swift-style-guide 스타일쉐어 라는 회사의 스위프트 스타일 가이드입니다.
이 글을 보시고 어떤 때 self 를 붙이는게 좋을지 고민해보면 좋겠습니다~

2021-12-13 13:54 UTC, AppleCEO commented
개선해보셨군요! 고생하셨습니다~ 머지 드리면 될까요? ㅎㅎ

2021-12-13 14:04 UTC, merged