만국박람회 [STEP2] 릴리, 니콜라스, 아카페라커피
yagom-academy/ios-exposition-universelle pull request #121
Opened 2021-12-10 10:36 UTC by yeahg-dev

안녕하세요 그린! @GREENOVER 
릴리, 니콜라스, 아카페라 커피입니다~
@Kim-EunsooSilver @aCafela-coffee

바쁘신 와중에도 정성스럽고 디테일한 리뷰 감사드려요!😀
스텝2 구현 완료하여 PR보내드립니다.
이번 스텝도 잘부탁드립니다!

<br>

## 고민한 점
### 1. UITableViewDataSource를 채택하는 객체를 별도로 생성할지에 대한 고민

- `UITableViewDataSource`를 채택하는 객체를 만들면 ViewController가 커지는 것을 방지할 수 있습니다. 예를 들어, 데이터를 업데이트하거나 페칭하는 코드를 별도의 정의된 클래스에서 구현해줌으로 뷰컨트롤러의 코드를 줄이고, 뷰에 관한 일만 하도록 집중시킬 수 있습니다.
- 이러한 장점에 따라 DataSource객체를 별도의 파일에 만들어 줄지 고민했습니다.
- 그런데 저희의 프로젝트 요구사항에서 데이터를 업데이트하고, 페칭하는 코드의 양이 많지 않을거라 판단해 TableViewController로 DataSource에 대한 처리를 구현해주었습니다.
    
[참고 문서](https://developer.apple.com/tutorials/app-dev-training/configuring-table-view-cells)
 > **Extract Data Source Methods**
    As your app grows, view controllers can become large and serve many purposes. In this section, pull the code related to fetching and updating data out of the view controller. Extracting the data source logic into its own class separates the concerns of these classes and focuses the view controller on view management.
    
<br>

### 2. UITableView vs UITableViewController
- 한국 출품작의 리스트를 보여줄 때 UIViewController 위에 UITableView를 올릴지
- UITableViewController를 이용하여 table를 보여줄지
 에 대한 고민을 했습니다.
    
**UITableViewController의 장점**
- UITableViewController는 루트 뷰가 UITableView이고 다른 뷰(스택뷰 등...)를 추가할 수 없습니다. 
- 따라서 UIViewController에서 TableView를 얹어주는 것보다 더 적은 view가 필요하므로 메모리가 적게 사용됩니다. 
- 그리고 TableView에 오토레이아웃이 자동으로 적용되는 이점이 있습니다.
    
    이번 프로젝트의 두번째 화면의 경우 TableView만 보여질 것이고, 따로 view가 추가될 확장성이 없다고 판단하여 TableViewController를 사용해서 tableView를 만들어주었습니다.

<br>

### 3. EntryViewController에서 보여질 객체(`ExpositionEntry`)를 어떻게 가공해서 View에 적용시킬지에 대한 고민
- EntryDetailViewController에 name, image, description 프로퍼티를 만들고, 여기 전달하기
- `ExpositionEntry` 를 Struct에서 Class로 변경하여 참조 전달하기

<Br>

## 질문드리고 싶은 점

- 외부 뷰컨트롤러에서 접근할 가능성이 없는 @IBOutlet은 `private` 으로 설정해주어도 괜찮을까요?

<br>

## 해결하지 못한 부분

### 마지막 뷰의 네비게이션 바의 투명도 문제

해결법을 못찾은 부분입니다. 나중에 오토레이아웃 설정하고 다시 해결하려고 합니다.
![스크린샷 2021-12-10 오후 7 28 53 Large](https://user-images.githubusercontent.com/81469717/145560517-138d9c32-d1f1-4f0a-b306-a1124b9cd83e.jpeg)

2021-12-10 13:38 UTC, GREENOVER reviewed
@yeahg-dev @Kim-EunsooSilver @aCafela-coffee 
세분 모두 스텝2도 고생많으셨습니다🥳🥳
생각보다 아주 빠르게 진행해주셨고 오토레이아웃을 제외한다면 대체적으로 잘 구현해주셨습니다!
테이블뷰도 적절히 잘 활용하신것도 잘 봤습니다ㅎㅎ
***
### 칭찬드리고 싶은 부분
- 파일명과 그룹화가 아주 잘 이뤄졌습니다 💯
- 짧은 시간에 코드상으론 테이블 뷰 등 필수적인것들 학습한것 같아요 💯
- 전체적으로 네이밍이 좋습니다 💯
***
### 고민하신점에 대한 저의 의견
1. UITableViewDataSource를 채택하는 객체를 별도로 생성할지에 대한 고민
- 지금 구현 좋습니다..!
여러분이 잘 고민하셨고 답도 도출해내신것 같네요 ㅎㅎ
추후에 말씀대로 뷰컨에서 할 수 있는 일이 많아지면 별도 분리하는것이 좋겠습니다👍
2. UIViewControlle vs UITableViewController
- 현재 구조에서는 UITableVC로 사용하신 지금이 가장 딱 좋습니다.
왜냐면 테이블VC외에 커스텀한 구현이 없기에 UIVC으로 할 이유가 없다고 판단됩니다.
3. EntryViewController에서 보여질 객체(ExpositionEntry)를 어떻게 가공해서 View에 적용시킬지에 대한 고민
- 현재 MVC 구조에서 지금같이 프로퍼티를 만들고 넘겨주어 setData를 통해 세팅해주는 방법 좋네요!
혹시 다른 방법들은 어떤것들이 있는지 학습해보신게 있을까요?🤔
***
### 질문사항에 대한 저의 의견
1. 외부 뷰컨트롤러에서 접근할 가능성이 없는 @IBOutlet은 private 으로 설정해주어도 괜찮을까요?
- 네 그럼요. private은 그럴때 사용하라고 있는거니까요..!
***
### 해결하지 못한 부분에 대한 저의 의견
- 해당 이슈는 네비게이션 바의 투명도 때문에 저 이미지가 safeArea를 침범하고 네비게이션 바 부분을 차지하는걸로는 보이지 않습니다.
완전한 오토레이아웃 이슈이기에 스텝3에서 해결해보실 수 있을것 같네요..!
***
스텝2에서 오토레이아웃이 빠졌기에 그 부분을 제외하고선 문제될 부분이 전혀 없습니다..!
다만 마이너하게 보완되거나 추가되었으면 좋겠다? 싶은 부분들은 리뷰 코멘트로 달아봤어요ㅎㅎ
확인하시고 여느때와 같이 수정이 필요하면 수정 후 요청을..! 머지를 원하시면 말씀해주세요!
고생하셨습니다👍

2021-12-10 13:38 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/ExpositionInformationViewController.swift
> +        self.navigationItem.backButtonTitle = "메인"
요것도 어떻게 보면 메서드로 뺄 수 있을것 같아요..!
지금이야 당연히 간단한 한줄 코드라 넣어도 뭐 무방하지만
이후 네비게이션을 세팅해주는 설정이 많아진다면 viewDidLoad에서 너무 많은 역할을 하게 됩니다!
최대한 메서드 별로 쪼개보는 습관화를 해보면 좋겠네요👍

2021-12-10 13:38 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/ExpositionInformationViewController.swift
> +        transitionToEntriesListButton.setTitle("한국의 출품작 보러가기", for: .normal)
여기도 줄바꿈이.. 필요.. 합..니..다..!!🚨

2021-12-10 23:58 UTC, GREENOVER commented
앗..! 제가 하나 리뷰중 놓친게 있습니다🥲
![스크린샷 2021-12-11 오전 8 57 57](https://user-images.githubusercontent.com/72292617/145655309-b8769a84-65ec-4a67-896f-861c8d41c460.png)
첫 메인 화면에서는 네비게이션바가 노출되지 않는것이 기획입니다🙋🏻
이에 맞춰 수정이 필요해보입니다!

2021-12-11 00:19 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/EntriesTableViewController.swift
> +        guard let entryDetailViewController = storyboard?.instantiateViewController(withIdentifier: "entryDetailView") as? EntryDetailViewController else {
entryDetailView와 같은것들은 name space로 관리한다면 더 안전할것 같아요🙋🏻

2021-12-11 00:19 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    private func prepare() {
조금 더 명확한 네이밍은 어떨까요🤔

2021-12-11 00:19 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    func setData(image: UIImage?, description: String?) {
여기도 조금 더 명확한 네이밍은 어떨까요🤔

2021-12-13 01:18 UTC, GREENOVER requested changes
필수 수정사항이 있기에 Request changes로 리뷰 상태 변경해두겠습니다!

2021-12-13 05:40 UTC, aCafela-coffee commented on Expo1900/Expo1900/Controller/EntriesTableViewController.swift
> +        return entries
반환값은 차이가 없습니다.
'Entry의 배열이 반환된다'고 읽히게 하려고 변수를 만들었습니다.

```swift
private let expositionEntries: [ExpositionEntry]? = {
    guard let entriesData = NSDataAsset(name: "items") else {
        return nil
    }
    let entries = try? JSONDecoder().decode([ExpositionEntry].self, from: entriesData.data)
    return entries
}()
```
그런데 지금 보니 변수 이름이 `expositionEntries`라서 `return try? JSONDecoder().decode([ExpositionEntry].self, from: entriesData.data)` 이렇게 써도 문제없을듯 합니다.

수정합니다.

2021-12-13 06:48 UTC, aCafela-coffee commented on Expo1900/Expo1900/Controller/EntriesTableViewController.swift
> +        return cell
`cellConfiguration(from:cellForRowAt:)` 만들었습니다.

2021-12-13 06:54 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/EntriesTableViewController.swift
> +        return cell
cellConfiguration이라는 메서드 명은 동사형보다는 명사형에 가깝다고 보이는데 어떻게 생각하시나요?
어떤 메서드명이 적절할까요?🤔

2021-12-13 07:01 UTC, yeahg-dev commented on Expo1900/Expo1900/Controller/EntriesTableViewController.swift
> +        let description = expositionEntries?[indexPath.row].description
저희가 생각해 본 차이점은 아래와 같습니다!

상수를 만들어서 넣어주는 방법
1. 상수로 따로 빼줌으로써 가독성이 향상됩니다.

매개변수에 바로 해당 값을 넣어주는 방법
1. 코드의 양이 줄어듭니다.
2. 매개변수의 출처가 명확해집니다.
 
추가적으로 두 방법은 메모리 사용량의 차이가 없을 것이라 생각했습니다.
근거는 스위프트의 String은 Copy On Write에 따라서 값이 변경되지 않는 이상 참조로 전달되고,
 UIImage도 클래스이므로 참조로 전달됩니다. 따라서 각 상수가 참조로 사용되므로 복사 시 메모리 낭비의 문제는 없을 것입니다.

2021-12-13 07:04 UTC, yeahg-dev commented on Expo1900/Expo1900/Controller/EntriesTableViewController.swift
> +        navigationController?.pushViewController(entryDetailViewController, animated: true)
네 수정해보았습니다!

2021-12-13 08:18 UTC, aCafela-coffee commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    @IBOutlet private weak var descriptionTextView: UITextView!
### strong일 경우
[참고 자료](http://monibu1548.github.io/2018/05/03/iboutlet-strong-weak/)
> 메모리가 부족하면 ViewController의 didReceiveMemoryWarning가 호출됩니다.
보통 didReceiveMemoryWarning 에서 main view를 nil 처리함으로써 main view를 포함한 subview들 까지 모두 dealloc 하여 메모리를 확보하는 동작을 구현합니다.

이때 @IBOutlet 프로퍼티(subView)가 강한 참조라면, didReceiveMemoryWarning 메서드가 호출될 때 해제되지 않습니다.

2021-12-13 08:20 UTC, aCafela-coffee commented on Expo1900/Expo1900/Controller/ExpositionInformationViewController.swift
> +//
이 과제는 yagom academy가 만든 것이라서 남겨뒀습니다.

2021-12-13 08:29 UTC, Kim-EunsooSilver commented on Expo1900/Expo1900/Controller/ExpositionInformationViewController.swift
> +    @IBOutlet private weak var desciptionTextView: UITextView!
저희는 HIG문서를 보면서 채택을 했습니다!! 아래는 간략한 설명입니다!

REF: Human Interface Guidelines
* label: A label describes an onscreen interface element or provides a short message. 
* textField: A text field is a single-line, fixed-height field that automatically brings up a keyboard when people tap it.
* textView: A text view displays multiline, styled text content. Text views can be any height and enable scrolling when the content extends outside of the view.

🤔혹시 짚어주신 코드부분이... HIG가 제시해준 가이드라인대로 하면은 안되는 케이스일까요...?

2021-12-13 08:43 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/ExpositionInformationViewController.swift
> +    @IBOutlet private weak var desciptionTextView: UITextView!
@Kim-EunsooSilver 아뇨! 궁금해서 여쭤봤어요..!
정말 단순히 궁금해서😀
다만 textView로 하셨다면 현재는 해당 텍스트뷰 영역을 클릭하면 커서가 나타나고 무언가 편집할 수 있다는 느낌을 주는데
요구사항과 프로젝트 설명에는 해당 관련하여 자세한 지침이 없지만 저는 이 부분이 수정 편집이 가능한 부분은 아니라 생각합니다.
(단순 정보 전달이기에)
그렇기에 사용자에게 이런 혼돈을 줄여주는 방법이 필요할것 같아요🤔

2021-12-13 09:06 UTC, aCafela-coffee commented on Expo1900/Expo1900/Controller/ExpositionInformationViewController.swift
> +        transitionToEntriesListButton.setTitle("한국의 출품작 보러가기", for: .normal)
수정합니다.

2021-12-13 09:41 UTC, yeahg-dev commented
> 앗..! 제가 하나 리뷰중 놓친게 있습니다🥲 ![스크린샷 2021-12-11 오전 8 57 57](https://user-images.githubusercontent.com/72292617/145655309-b8769a84-65ec-4a67-896f-861c8d41c460.png) 첫 메인 화면에서는 네비게이션바가 노출되지 않는것이 기획입니다🙋🏻 이에 맞춰 수정이 필요해보입니다!🚨

---
```swift
 override func viewDidLoad() {
        super.viewDidLoad()
        setExpositionInformation()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(true, animated: animated)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        navigationController?.setNavigationBarHidden(false, animated: animated)
        setNavigationItem()
    }
```
위 코드와 같이 수정하여 첫번째 화면에서는 네비게이션 바가 보여지지 않도록 수정했습니다.

그런데! 하나 궁금한 점이 있습니다.

아래의 코드 처럼 `setNavigationItem()`을 `viewDidLoad()` 안에서나 ` navigationController?.setNavigationBarHidden(false, animated: animated)`전에 호출하면 두번째 화면의 뒤로가기의 `메인`이 적용이 되지 않는 것을 발견했습니다.
`setNavigationBarHidden(true, animated: animated)`는 네비게이션바가 보여지고 안보여지고만 관장하는 메서드인것 같은데 
이런 현상이 일어나는 이유가 뭔지 혹시 알고계실까요??

```swift
override func viewDidLoad() {
        super.viewDidLoad()
        setExpositionInformation()
        setNavigationItem()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(true, animated: animated)
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        navigationController?.setNavigationBarHidden(false, animated: animated)
    }
```

2021-12-13 10:07 UTC, Kim-EunsooSilver commented on Expo1900/Expo1900/Controller/EntriesTableViewController.swift
> +        guard let entryDetailViewController = storyboard?.instantiateViewController(withIdentifier: "entryDetailView") as? EntryDetailViewController else {
name space 구현해 봤습니다!!!

2021-12-13 10:18 UTC, yeahg-dev commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    func setData(image: UIImage?, description: String?) {
어떤 부분에서의 모호함때문에 명확한 네이밍을 추천해주신건지 알 수 있을까요..?
저희가 작성한 코드라 그런지,,, `setData()`가 명확하게 보여서요...😭

2021-12-13 10:18 UTC, yeahg-dev commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    private func prepare() {
`prepareView()`로 수정해주었습니다!

2021-12-13 10:20 UTC, aCafela-coffee commented on Expo1900/Expo1900/Controller/EntriesTableViewController.swift
> +        let entries = try? JSONDecoder().decode([ExpositionEntry].self, from: entriesData.data)
어디로 빼면 좋을까요? `ExpositionEntry`에 넣어야 할까요?

2021-12-13 10:28 UTC, GREENOVER commented
> > 앗..! 제가 하나 리뷰중 놓친게 있습니다🥲 ![스크린샷 2021-12-11 오전 8 57 57](https://user-images.githubusercontent.com/72292617/145655309-b8769a84-65ec-4a67-896f-861c8d41c460.png) 첫 메인 화면에서는 네비게이션바가 노출되지 않는것이 기획입니다🙋🏻 이에 맞춰 수정이 필요해보입니다!🚨
> 
> ```swift
>  override func viewDidLoad() {
>         super.viewDidLoad()
>         setExpositionInformation()
>     }
>     
>     override func viewWillAppear(_ animated: Bool) {
>         super.viewWillAppear(animated)
>         navigationController?.setNavigationBarHidden(true, animated: animated)
>     }
>     
>     override func viewWillDisappear(_ animated: Bool) {
>         super.viewWillDisappear(animated)
>         navigationController?.setNavigationBarHidden(false, animated: animated)
>         setNavigationItem()
>     }
> ```
> 
> 위 코드와 같이 수정하여 첫번째 화면에서는 네비게이션 바가 보여지지 않도록 수정했습니다.
> 
> 그런데! 하나 궁금한 점이 있습니다.
> 
> 아래의 코드 처럼 `setNavigationItem()`을 `viewDidLoad()` 안에서나 ` navigationController?.setNavigationBarHidden(false, animated: animated)`전에 호출하면 두번째 화면의 뒤로가기의 `메인`이 적용이 되지 않는 것을 발견했습니다. `setNavigationBarHidden(true, animated: animated)`는 네비게이션바가 보여지고 안보여지고만 관장하는 메서드인것 같은데 이런 현상이 일어나는 이유가 뭔지 혹시 알고계실까요??
> 
> ```swift
> override func viewDidLoad() {
>         super.viewDidLoad()
>         setExpositionInformation()
>         setNavigationItem()
>     }
>     
>     override func viewWillAppear(_ animated: Bool) {
>         super.viewWillAppear(animated)
>         navigationController?.setNavigationBarHidden(true, animated: animated)
>     }
>     
>     override func viewWillDisappear(_ animated: Bool) {
>         super.viewWillDisappear(animated)
>         navigationController?.setNavigationBarHidden(false, animated: animated)
>     }
> ```

@yeahg-dev 
혹시 저는 코드상 문제가 없는것 같아 pull 받아 돌려보았는데 말씀하신 두 상황 모두 정상적으로 메인 텍스트가 적용됩니다.
즉 해당 메서드가 잘 호출되고 있습니다.
아마 제 생각으로는 캐쉬가 남아있는것 같은데 클린빌드를 해보실 수 있을까요?

2021-12-13 10:30 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    func setData(image: UIImage?, description: String?) {
아하 제가 생각한것은 만약 이 뷰컨이 나중에 커지게 되어 다른 데이터를 세팅해주는 메서드도 필요하다면
두 메서드의 네이밍만으로는 어떤 데이터를 세팅해줄지 모호해지게 됩니다.
이에 조금 더 구체적으로 어떤 데이터를 셋해주는건지 명확하면 어떨까라는 의도에서 말씀드렸습니다🙋🏻

2021-12-13 10:38 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/EntriesTableViewController.swift
> +        let entries = try? JSONDecoder().decode([ExpositionEntry].self, from: entriesData.data)
JSONParser라는 별도 타입을 만들어 구현해주면 어떨까라는 의도였습니다😀
이유는 해당 디코딩되는 과정의 코드들은 항상 중복적인데 만약 그 행위를 하는 메서드를 호출만 하면되기에
Enum 타입으로 static 메서드를 만들어 인자만 전달해준다면 공통적인 기능을 할 수 있을겁니다..!
음 대략 코드로 적어본다면
```swift
enum JSONParser<Element: Decodable> {
  static func decode(from jsonFileName: String) -> Element? {
     // 디코딩 구현부
      guard let entriesData = NSDataAsset(name: jsonFileName) else {
          return nil
      }
      let data = try? JSONDecoder().decode(Element.self, from: entriesData)
      return data
   }
}
```
변수명이나 그런건 신경쓰지 마시고 흐름을 봐주시면 좋을것 같습니다!
이렇게 하나의 공통 타입으로 뺀다면
호출부에서는 간략히
```swift
JSONParser<[ExpositionEntry]>.decode(from: xxx)
```
이런식으로 쓸 수 있을것 같아요.

2021-12-13 10:50 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/ExpositionInformationViewController.swift
> +        navigationController?.setNavigationBarHidden(true, animated: animated)
isNavigationBarHidden과 어떤 차이가 있나요?🤔

2021-12-13 13:05 UTC, aCafela-coffee commented on Expo1900/Expo1900/Controller/EntriesTableViewController.swift
> +        return cell
전에 [ryon의 코멘트](https://github.com/yagom-academy/ios-number-baseball/pull/47#discussion_r723696376)에서 get을 생략하는 경우도 있다고 해서 그랬어요.
> 예외 상황으로는, 조직에 따라 다르지만 함수나 메서드 이름에 get을 넣는 것을 지양하는 경우도 있습니다. 아래와 같은 경우에 get이 있다고 생각하고 함수의 의미를 파악하는 것이죠.
>
> randomInteger(between:) // 일정 범위 의 정수(between)를 전달받아 무작위 정수를 반환하는 메서드인가 보다.

그리고 `UITableViewCell.defaultContentConfiguration()` 여기서도 get을 생략한 네이밍이라고 생각했어요. 이 네이밍에 맞추려고 get이 생략된 `cellConfiguration`을 사용했어요.

2021-12-13 14:30 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/EntriesTableViewController.swift
> +        return cell
제 생각에는 해당 메서드는 get의 역할과 다릅니다. 왜냐면 해당 메서드를 호출하고 반환받아 변수에 입혀주는 부분이 get의 역할이지 메서드만 따로 분리해서 본다면 set의 기능에 가깝습니다!
다른 부분에 종속되지말고 메서드들을 독립적으로 보고 알맞은 기능에 맞는 네이밍을 지어주는편이 좋습니다🙌🏼

2021-12-14 01:54 UTC, aCafela-coffee commented on Expo1900/Expo1900/Controller/EntriesTableViewController.swift
> +        return cell
그렇군요. `setCellConfiguration` 변경했어요.

2021-12-14 01:56 UTC, yeahg-dev commented on Expo1900/Expo1900/Controller/ExpositionInformationViewController.swift
> +    @IBOutlet private weak var desciptionTextView: UITextView!
selectable 체크를 해제해주어 혼돈을 줄여주었습니다.

2021-12-14 02:33 UTC, aCafela-coffee commented on Expo1900/Expo1900/Controller/EntriesTableViewController.swift
> +        let entries = try? JSONDecoder().decode([ExpositionEntry].self, from: entriesData.data)
JSONParser 타입 만들었습니다.

그런데 지금은 따로 만들지 않아도 괜찮을것 같아요.
저 부분의 코드도 짧고, keyDecodingStrategy를 사용하도록 변경되는 모델이 생기면 분리해야 할거에요.

2021-12-14 02:37 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/EntriesTableViewController.swift
> +        let entries = try? JSONDecoder().decode([ExpositionEntry].self, from: entriesData.data)
네 맞아요!
현재 구현 스코프 정도에서는 따로 만들지 않아도 충분하긴 합니다.
다만 최대한 타입들과 기능들을 잘게 쪼개어 가져다 쓸 수 있도록 객체지향적으로 항상 바라보는 습관이 중요할것 같아 언지드렸습니다!
이 프로젝트 외에 현업에 가시면 모든걸 언제 확장되거나 쓰일지 몰라도 모듈화를 시키는 작업이 좋은 프로그래밍이라 생각합니다👍

2021-12-14 02:39 UTC, yeahg-dev commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    func setData(image: UIImage?, description: String?) {
아하~! 그런 상황에서는 모호할 수 있겠군요
`setEntryData`로 리네임 해주어 모호함을 제거해보았습니다!

2021-12-14 02:46 UTC, aCafela-coffee commented on Expo1900/Expo1900/Controller/ExpositionInformationViewController.swift
> +        navigationController?.setNavigationBarHidden(true, animated: animated)
isNavigationBarHidden은 애니메이션이 없어요. 화면이 완전히 전환되기 전에 네비게이션 바가 나타나요.

2021-12-14 02:54 UTC, GREENOVER approved these changes
모두 수고하셨습니다!
기능 및 코드 동작에 이상없습니다👍👍
혹시 추가적으로 보완할 사항들이 생기면 스텝3 오토레이아웃을 하면서 같이 진행해보시면 될것 같아요☺️
그럼 머지하겠습니다!
스텝3도 화이팅입니다🙌

2021-12-14 02:55 UTC, merged