만국박람회 [STEP 2] 아샌, yeha, 알라딘
yagom-academy/ios-exposition-universelle pull request #122
Opened 2021-12-13 09:23 UTC by ICS-Asan

안녕하세요. 델마 @delmaSong!!

아샌(@ICS-Asan), 예하(@ye-ha), 알라딘(@junbangg) 입니다. 

스텝2 PR 요청 보냅니다. 잘 부탁드려요!

# 💻  주요 구현 내용

### < View >

- ExpoMainView Storyboard 구성요소 배치
- ExpoItems 스토리보드 생성 및 구성 요소 배치
- JSON파일 디코딩 및 Custom TableViewCell 구현
- TableView 연결 및 CustomTableViewCell 속성 설정
- ExpoItemDetailViewController 생성 및 연결

### < View Controller >

- ExpoMainInformation JSON 디코딩
- ExpoMainInformation JSON 디코딩 관련 에러 타입 생성
- ExpoMainInformation Label 속성 설정
- ExpoItems JSON 디코딩
- ExpoItems JSON 디코딩 관련 에러 타입 생성
- ExpoItemsLabel 속성 설정

# 💡  조언 받고 싶은 내용

## < 메인화면 레이블 분리 VS 일부 문자 폰트 수정 >

- 프로젝트 예시 화면을 보니 메인 화면에서 title부분은 글자 크기가 다르게 되어있었습니다.
이 부분을 처리하기 위해 두가지 방법중에 일부 문자 폰트를 수정하는 방법을 선택했습니다.
- 레이블을 분리하게 되면 각 항목마다 Label이 2개인 StackView를  생성하고 autoLayout을 각각 설정해주어야하기 때문에 비효율적이라 판단되어 코드를 통해 일부 문자의 폰트만 수정하는 방법으로 진행했습니다. 
이게 괜찮은 방법인지, 개선할 수 있는 방법은 없는지 조언을 듣고 싶습니다.

```swift
// 구현 코드
private func increaseFontSize(of subtext: String, in text: String) -> NSMutableAttributedString {
        let attributeString = NSMutableAttributedString(string: text)
        let font = UIFont.systemFont(ofSize: 25)
        attributeString.addAttribute(.font, value: font, range: (text as NSString).range(of: subtext))
        return attributeString
    }

// 호출되는 부분
private func setupTitleLabel(with expoMainInformation: ExpoMainInformation) {
        let title = expoMainInformation.title.replacingOccurrences(of: Symbol.openingParenthesis, with: Symbol.linebreak + Symbol.openingParenthesis)
        titleLabel.text = title
        titleLabel.font = UIFont.systemFont(ofSize: 28)
        titleLabel.textAlignment = .center
    }
```

## < Stack View 관련 >

- 현재 Stack View 내에 Image View 와 Text View 가 있습니다. 
Stack View 와 관련하여 두 가지 현상에 대해 조언을 받고 싶습니다.
    - (원한 것) Stack View 가 Text View 에 텍스트가 남아 있는 만큼만 스크롤되기를 원했습니다. 
    (현재 상황) Stack View 가 아래로 무한 스크롤됩니다.
    - (원한 것) 이미지의 크기에 따라 Image View 의 크기를 변화시키고 싶었습니다. 
    (현재 상황) 이미지가 작을 때에도 Image View 의 크기가 고정되어 위아래로 공백이 있습니다.

## < 파일 분리 및 타입 관련 >

- 지난 스텝 1 리뷰를 받고, 저희는 `각 타입 별로 파일을 나누는 방법` 을 사용해보기로 했습니다. 저희가 수행한 부분에 대해서 어떻게 생각하시는지 궁금합니다.

![https://user-images.githubusercontent.com/91048487/145784722-950b1013-5a8e-4fb6-ab45-8042e550e1e2.png](https://user-images.githubusercontent.com/91048487/145784722-950b1013-5a8e-4fb6-ab45-8042e550e1e2.png)
- 각 View Controller 내에 코드를 파일이나 타입으로 분리할 수 있는 여지가 있을까요?

# ❓  질문할 내용

## <  tableView 메서드 내부 강제 언래핑 사용>

- 타입캐스팅 과정에서 옵셔널 바인딩이 필요했는데 프로토콜의 메서드는 리턴타입을 수정하거나 에러를 `throws`하도록 변경할 수 없었습니다.
그래서 현재 강제 언래핑(`!`)을 사용하였는데, 이러한 경우 어떻게 안전하게 옵셔널을 처리할 수 있는지 궁금합니다.

```swift
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "expoItemCell", for: indexPath) as! ExpoItemTableViewCell
        let expoItem = expoItems[indexPath.row]
        cell.configure(with: expoItem)
        return cell
    }
```

## **<UI를 구현하는 방법: Storyboard vs 코드>**

- 저희가 UI를 구현하면서 어떤 요소들은 **Storyboard** 로 하고 어떤 것들은 **코드**로 구현하는 일이 생겼었습니다. 
두 방법을 병행할때 고려할 수 있는 기준이 있는지 궁금합니다.
- 델마는 UI를 구현할때 **Storyboard** 와 **코드** 중 어떤 기준으로 무엇을 선택하는지 궁금합니다.

저희의 코드를 다듬을 시간이 조금 부족하여 미흡한 점이 많을 것 같습니다.
부족하지만 코멘트 주시면 열심히 고민해보고 리팩토링하는 시간을 갖도록 하겠습니다.
잘 부탁드립니다! 감사합니다!

2021-12-13 14:52 UTC, delmaSong requested changes
안녕하세요!
아샌, yeha, 알라딘 모두 수고 많으셨습니다! 😃

## 미구현된 사항
<img width=40% src="https://user-images.githubusercontent.com/40784518/145830854-a8b4224a-4411-4ca2-90ba-8e2f1aeab287.png">
1. 위의 이미지처럼 스크롤했을 때 네비게이션 영역이 표시됩니다. 
요구사항 문서에는 해당 기능에 대한 요구사항이 없어서, 스크롤 했을 때 네비게이션이 보이지 않도록 처리해주세요.

<img width=30% src="https://user-images.githubusercontent.com/40784518/145831150-7af97c1d-7b61-4c3e-b138-a3d147f139b0.png">

2. 위의 이미지를 보면 네이게이션 바의 상태가 스크롤하기 전에는 색상과 디바이더 부분이 보이지 않아 본문과의 구분이 없습니다. 
3. 위의 이미지에는 뒤로가기 버튼이 Back으로 표시되어있습니다. 요구사항 문서처럼 `메인`, `한국의 출품작` 이 표시되도록 수정해주세요.

## 조언받고 싶다고 하신 점
### < 메인화면 레이블 분리 VS 일부 문자 폰트 수정 >
지금도 괜찮은 방법이라고 생각해요. 다만 메서드 하나에 구체적인 레이블이 들어있으니까 메서드 하나랑 레이블 하나가 1:1로 대응되어 재사용측면에 좀 불리한 면이 있는 것 같아서 이 부분이 개선되면 좋을 것 같아요.
그리고 라벨이 두개 있는 스택뷰를 생성해서 내부의 텍스트만 다르게 해 재사용하는 방법도 괜찮을 것 같은데요? 여력이 된다면 한번 시도해보세요!

### 스택뷰 관련
해당 뷰의 계층구조를 보니 스크롤뷰 > 스택뷰 > 이미지뷰, 텍스트뷰 로 되어있더라구요.
스크롤뷰만으로는 원하는 뷰를 표현할 수 없었나요?

### 파일 분리 및 타입 관련
- 제가 어떻게 생각하는지도 중요(?) 하겠지만 그것보다는 함께 쓰는 분들이 파일이 어디있는지 찾기 쉽고, 새로 파일을 만들 때 어디에 생성해야할지도 명확하다면 충분히 잘 분리하셨을 것 같은데요? 어떠셨나요?

## 질문주신 사항
### tableView 내 강제 언래핑
해당 메서드에서는 반드시 `UITableViewCell`을 리턴해야해서 강제 언래핑을 하거나 실패한 경우 `UITableViewCell()`을 리턴하도록 할 수 있을 것 같아요

### UI 구현 방법
어떤것은 Storyboard로 구현하고 어떤 건 코드로 구현하셨는데, 그렇게 결정한 기준은 무엇인가요?
두개 다 사용하시면서 각각 어떤 장단점이 있었나요?

2021-12-13 14:52 UTC, delmaSong commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +
final 키워드에 대해 알아보세요 😃

2021-12-13 14:52 UTC, delmaSong commented on Expo1900/Expo1900/Controller/ExpoItemTableViewCell.swift
> +        super.awakeFromNib()
`awakeFromNib()`은 무슨 기능을 하는 메서드인가요?

2021-12-13 14:52 UTC, delmaSong commented on Expo1900/Expo1900/Controller/ExpoItemsTableViewController.swift
> +    }
`setupExpoItemsTableView()` 메서드 이름만 보면 dataSource를 지정해주는 작업도 할 것 같은데,  `viewDidLoad()`와 `setupExpoItemsTableView()`의 동작은 어떤 기준으로 분리한건가요?

2021-12-13 14:52 UTC, delmaSong commented on Expo1900/Expo1900/Errors/JSONDataError.swift
> +            return "\(fileName)이 없습니다"
`.fileConversionFailed` 는 파일 변환에 실패했다는 내용이고 `description`은 파일이 없다는 내용이어서 설명 혹은 케이스명이 적절하지 매치되지 않는 것 같아요.

2021-12-13 14:52 UTC, delmaSong commented on Expo1900/Expo1900/Namespaces/JSONFile.swift
> +}
이름이 `JSONFile`이라 꽤 제너럴하게 사용될 것 같은데 내부에는 expo와 관련된 것만 있네요 🤔

2021-12-13 14:52 UTC, delmaSong commented on Expo1900/Expo1900/Namespaces/LabelTitle.swift
> +}
`ExpoMainViewController` 내부에서만 사용되는데, 이렇게 전역적으로 있지 않아도 될 것 같네요

2021-12-13 14:52 UTC, delmaSong commented on Expo1900/Expo1900/Namespaces/Symbol.swift
> +}
`Symbol`도 마찬가지로 `ExpoMainViewController` 내에서만 사용되고있네요

2021-12-13 14:52 UTC, delmaSong commented on Expo1900/Expo1900/Controller/ExpoMainViewController.swift
> +}
전체 `String`과 관련한 `extension`이라 별도의 파일로 분리하는 게 나중에 찾기가 더 쉬울 것 같아요~
혹은 `ExpoMainViewController` 한정해서만 쓸거라면 별도의 접근제어자를 지정해주는 방법도 있구요.

2021-12-13 14:52 UTC, delmaSong commented on Expo1900/Expo1900/Controller/ExpoItemsTableViewController.swift
> +        } catch JSONDataError.fileConversionFailed(let fileName) {
내부에 `expoItemArray`를 또 선언해서 `ExpoItems`를 리턴할 것 없이
디코딩한 데이터를 외부의 `expoItems`로 바로 넣어주면 조금 더 간결해질 것 같네요

2021-12-15 05:16 UTC, ICS-Asan commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +
final 키워드에 대해 간단히 알아보았습니다!
final 키워드는 class의 재정의 및 상속을 방지하고 이를 보여줄 수 있는 키워드라고 생각했습니다.
그리고 깊이 이해하지는 못했지만 final 키워드를 붙여줌으로써 성능상의 이점도 있다는 것을 알게 되었습니다.
ExpoItemDetailVeiwController가 현재 가장 마지막 뷰컨트롤러이므로 위의 목적에 따라 final키워드를 붙여주는 것이 좋다고 생각합니다!!

2021-12-15 05:40 UTC, ICS-Asan commented on Expo1900/Expo1900/Controller/ExpoItemTableViewCell.swift
> +        super.awakeFromNib()
더 자세하게 개념을 이해하고자 공식문서를 통해 확인을 하고 직접 breakpoint를 통해 확인을 해봤습니다.
awakeFromNib()은 Interface Builder 아카이브나 nib파일에서 로드되고 객체가 초기화 된 후 호출되는 것이라고 확인했습니다.
- 현재 프로젝트의 코드에서의 호출 순서
   - viewDidLoad()->tableView()->dequeueReusableCell()->ExpoItemTableViewCell의 awakeFromNib()

2021-12-15 06:09 UTC, ICS-Asan commented on Expo1900/Expo1900/Controller/ExpoItemsTableViewController.swift
> +    }
저희는 tableView의 속성을 세팅하는 역할과 뷰컨트롤러의 프로퍼티를 세팅하는 역할을 구분하고자 따로 분리를 하였습니다.
하지만 코멘트를 보고 다시 생각해보니 네이밍이 모호하다는 생각이 들었습니다.
그래서 조금 더 명확한 네이밍으로 수정을 해보았습니다.
```swift
override func viewDidLoad() {
    super.viewDidLoad()
    setExpoItems()
    setUpExpoItemTableView()
}

private func setUpExpoItemTableView() {
    expoItemTableView.dataSource = self
}

private func setExpoItems() {
    expoItems = decodeExpoItemsJsonData()
}
```

2021-12-15 06:18 UTC, junbangg commented on Expo1900/Expo1900/Errors/JSONDataError.swift
> +            return "\(fileName)이 없습니다"
조금 더 명확한 네이밍을 위해 에러명을 'fileNotFound` 로 수정했습니다!

2021-12-15 06:27 UTC, ye-ha commented on Expo1900/Expo1900/Namespaces/JSONFile.swift
> +}
저희는 제너럴한 이름을 붙이는게 낫다고 생각해서 이렇게 이름을 붙였는데요..!  
expo와 관련된 JSON file만 들어오는 상황이라면 enem 이름도 expo를 넣어주는게 더 나을까요?

2021-12-15 06:28 UTC, ye-ha commented on Expo1900/Expo1900/Namespaces/JSONFile.swift
> +}
바꾼다면 `JSONFileName` 이나 `ExpoJSONFileName` 으로 바꾸면 좋겠다고 생각했습니다.

2021-12-15 06:44 UTC, ye-ha commented on Expo1900/Expo1900/Namespaces/LabelTitle.swift
> +}
이 부분과 아래 기호 부분을 추후에 여러 군데에서 쓰일 수도 있지 않을까 판단해서 지역으로 넣지 않고 `Namespaces`라는 폴더를 두고 분리를 했었습니다.
우선 쓰이는 곳에서 생성해두고 사용하다가 후에 여러 군데에서 쓰일 때 전역으로 빼서 쓰는 방식으로 진행하는 것이 나을까요?
현업에서 (이렇게 처음부터 만드는 경우는 많지 않겠지만..) 이런 상황이 생긴다면 어떻게 진행되는지 궁금합니다!

2021-12-15 06:44 UTC, ye-ha commented on Expo1900/Expo1900/Namespaces/Symbol.swift
> +}
위에 질문을 남겼습니다!

2021-12-15 07:10 UTC, ICS-Asan commented on Expo1900/Expo1900/Controller/ExpoMainViewController.swift
> +}
처음 메서드 구현 시 범용적으로 사용될 수 있도록 로직을 구현했었습니다.
그래서 String+Extension 파일로 분리해보았습니다!!

2021-12-15 07:13 UTC, ICS-Asan commented on Expo1900/Expo1900/Controller/ExpoItemsTableViewController.swift
> +        } catch JSONDataError.fileConversionFailed(let fileName) {
저희는 decodeExpoItemsJsonData()에서 `expoItems `에 바로 넣어준다면 하나의 메서드에서 많은 일을 하는것이 아닐까 생각을 했습니다.
그래서 역할을 명확히 구분하고자 할당하는 부분을 따로 분리하였습니다.

2021-12-15 08:45 UTC, ICS-Asan commented
### < 미구현된 사항 >
- ExpoMainView 스크롤했을 때 네비게이션 영역 보이지 않도록 처리
    - 네비게이션바를 숨기는 방향으로 수정했습니다!
- ExpoItemDetailView 네이게이션 바의 상태가 스크롤하기 전에도 색상과 디바이더 부분이 보이도록 처리
    - iOS15로 업데이트 되면서 NavigationBar의 속성이 일부 변경되었다는 것을 찾았습니다.
그래서 저희가 해봤을 때 14.4에서는 정상적으로 나오고 15.2에서는 디바이더가 생기지 않았습니다.
구글링을 통해 AppDelegate에 코드를 추가하였고, 추후에 속성들에 대해 좀 더 자세히 알아보도록 하겠습니다!
```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        if #available(iOS 15.0, *) {
            let navigationBarAppearance = UINavigationBarAppearance()
            navigationBarAppearance.configureWithDefaultBackground()

            UINavigationBar.appearance().standardAppearance = navigationBarAppearance
            UINavigationBar.appearance().compactAppearance = navigationBarAppearance
            UINavigationBar.appearance().scrollEdgeAppearance = navigationBarAppearance
        }
        return true
    }
```
- 요구사항 문서처럼 뒤로가기 버튼이 `메인`, `한국의 출품작` 이 표시되도록 수정
    - 수정하는 것을 놓쳤습니다. 수정해두었습니다!

### < 메인화면 레이블 분리 VS 일부 문자 폰트 수정 >
- 저희도 이 부분에 대해서 고민을 해봤는데 구체적으로 재사용을 어떻게 해야할지 떠오르지 않았습니다.
다음 스텝을 진행하면서 꾸준히 개선 방법에 대해 고민해보겠습니다!

### < 스택뷰 관련 >
- 활동학습시간에 AutoLayout에 대해 배우면서 StackView를 이용하여 AutoLayout을 설정하면 내부의 뷰들에 대한 제약조건은 일일히 지정해주지 않아도 되는 간편함이 있는 것 같아 스택뷰를 사용하였습니다.
다음 스텝에서 AutoLayout을 적용할 때 스택뷰를 사용하지 않고 구현해보면서 어떤 차이점이 있는지 알아보겠습니다.

### < 파일 분리 및 타입 관련 >
- 타입을 기준으로 파일분리를 하기로 정하고 프로젝트를 진행했습니다.
그런데 하다보니 하나의 파일에서만 쓰는 enum인데 파일로 분리를 하니 오히려 더 가독성이 떨어지지 않나?라는 생각이 들었습니다.
우선은 처음 정한 기준으로 분리를 하였는데 상황에 따라 예외사항을 두어도 되는지 궁금합니다.
예외가 있다면 처음 코드를 보는 사람들은 헷갈릴 수도 있다고 생각되어 그래도 기준을 따르는 것이 좋은 것 같다는 생각과 가독성을 위해 하나의 파일에 같이 구현을 하는 것이 좋은 것 같다는 두가지 생각이 공존했습니다.

### < tableView 내 강제 언래핑 >
- 저희가 판단했을 때 의미없는 빈 셀을 리턴하는 것 보다 강제언래핑이 더 적합하다고 생각됩니다.
그리고 저희 코드의 경우에는 실패할 경우가 없다고 판단되어 사용에 문제가 없을 것 같은데 강제언랩핑을 지양하는 것이 맞을까요?

### < UI 구현 방법 >
- 저희가 구현을 함에 있어서 명확한 기준은 없었던 것 같습니다.
하지만 최대한 처음 생성 및 배치나 AutoLayout의 경우에는 Storyboard에서 구현을 하고자 했고, 이외의 내부 값을 할당하는 부분의 경우에는 코드로 구현을 하고자 했습니다.
저희가 직접해보니
Storyboard로 구현을 하면 변경사항이나 적용된 속성을 직관적으로 바로 확인을 할 수 있는 장점이 있었습니다.

    코드로 구현을 하면 생성되지 않은 UI요소들의 속성들을 다양하게 설정할 수 있는 장점이 있었습니다.
    그리고 속성들을 한눈에 파악할 수 있고 하드코딩을 하지 않게되는 이점도 있었습니다.

    위 각 장점들이 서로의 단점이 된다고 생각이 들었습니다.

2021-12-15 15:05 UTC, delmaSong approved these changes
수고하셨습니다! 미구현된 사항과 개선하면 좋을 점들이 잘 반영이 되었네요 😃
테이블뷰 셀을 리턴하는 경우에 실패 할 가능성이 없다면 강제 언래핑을 사용해도 큰 문제 없을 것 같아요
세 분 다 모두 수고 많으셨고 다음 스텝에서 만나요 😆 홧팅!

2021-12-15 15:07 UTC, merged

2021-12-15 15:08 UTC, delmaSong commented on Expo1900/Expo1900/Namespaces/LabelTitle.swift
> +}
가능한한 작은 곳에만 영향을 끼치도록 만들고 사용하는 곳이 많아질 때 노출되는 범위도 같이 넓어지도록 하는 것이 좋지 않을까 해요!