만국박람회 [STEP 2] 호박, 예거
yagom-academy/ios-exposition-universelle pull request #123
Opened 2021-12-13 10:21 UTC by hoBahk

안녕하세요 콘! @protocorn93 
주말 잘 보내셨나요? 😃
Step2 PR 보내드립니다. 잘 부탁드립니다. 🙏 

## 🤔  질문드리고 싶은 부분

### ❓ 인스턴스 생성 시점

`KoreanEntryTableViewController`에서 `EntryDataSource`의 인스턴스를 생성하기 위해  아래와 같이 옵셔널로 선언 후 viewDidLoad()에서 인스턴스를 할당해주었습니다.

```swift
    // 옵셔널로 선언
    private var dataSource: EntryDataSource?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        dataSource = EntryDataSource()
    }

    // lazy 사용하여 인스턴스 할당
    private lazy var dataSource: EntryDataSource = EntryDataSource()
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
```

옵셔널로 선언을 해주고 `viewDidLoad()`메서드에서 인스턴스를 할당해주는 것과 인스턴스를 `lazy`를 사용하여 바로 할당 해주는 것 중 어떤 차이가 있을지 궁금합니다.
현재 구조에서는 두 가지 방법 모두 같은 시점(super.viewDidLoad() 다음 줄)에서 인스턴스 할당이 되는 것으로 보입니다. 

#### 🤚 질문
그래서 두가지 방법 중 어떤 방법을 사용해도 괜찮을 것 같은데 저희가 고려하지 못한 부분이 있을까요?
메모리 효율이나 향후 확장성 등 여러가지를 고려했을 때 더 좋은 방법은 어떤 것인지 궁금합니다!

<br>

### ❓ 오류 처리에 대한 질문

JSON파일을 불러오지 못했을 때 어떻게 처리를 해야할지 고민을 많이 했습니다.
처음에는 Error 열거형 타입을 사용하여 오류처리를 하려고 하였습니다. 

그런데 JSON을 파싱할 때 마다 `do-try-catch`를 사용하게 되면 코드가 가독성이 떨어지기도 하고 결정적으로 `prepare`메서드는 override 메서드이기 때문에 오류를 `throws` 할 수 없었고 `tableView` 메서드도 `UITableViewDataSource` 프로토콜에 정의되어 있지 않아서 오류를 `throws` 할 수 없었습니다.
그래서 오류 처리를 `Alert`을 발생시키고 되돌아가거나 빈셀을 반환하는 방식으로 구현하기로 했습니다.

하지만 `Alert`을 만들고 `present`를 하는 과정에서 `UIViewController`가 아니면 `present`를 할 수가 없었습니다.
그래서 `Delegate` 패턴을 사용하여 `DataSource`에서 빈셀을 반환하게 될 경우 `UITableViewController`에서 대신 `Alert`을 처리할 수 있도록 구현하였습니다.

`showAlert` 메서드를 `UIViewController`의 `Extension`에서 구현 하였습니다.
`Delegate`프로토콜인 `AlertDelegate`프로토콜을 사용하여 `UIViewController`의 `Extension`에서 구현해 놓은 `showAlert` 메서드를 요구사항으로 정의하였습니다.

####  🤚  질문
`Delegate` 패턴을 사용이 올바르게 되어있는 것인지 궁금합니다.
	- `AlertDelegate`프로토콜에서 `extension`으로 구현해 놓은 메서드인 `showAlert`을 요구사항으로 두었는데 이렇게 `Delegate`패턴을 사용해도 되는지 궁금합니다.

```swift
// Alert.swift
extension UIViewController {
    
    func showAlert(alertMessage: AlertMessage, buttonMessage: AlertMessage) {
	…
    }
}

// EntryDataSource.swift
protocol AlertDelegate: UIViewController {
    func showAlert(alertMessage: AlertMessage, buttonMessage: AlertMessage)
}
```

#### 저희가 구현한 Alert 시연 스크린샷 입니다.
<p align="center"><img src="https://user-images.githubusercontent.com/71127966/145792089-3ed26e43-db54-4590-9036-49cf8faf378b.png" width="70%"></p>

<br>

### ❓ 프로토콜에 대한 질문

Alert을 띄우기 위한 `present`메서드는 `UIViewController` 타입에서만 사용할 수 있기 때문에
프로토콜을 구현할 때 `UIViewController`만 사용할 수 있도록 아래와 같이 코드를 작성하였습니다.
클래스만 채택할 수 있게 `AnyObject`를 사용할 수 있도록 하는 것을 한번 더 생각하여 `UIViewController`를 쓰면 `UIViewController`타입을 상속하는 모든 타입들만 채택할 수 있게 만들었습니다.

#### 🤚 질문
이렇게 사용하는 것이 괜찮은 방법인가요? 혹은 더 좋은 방법이 있을 까요?
더 좋은 방법이 있다면 알려주시면 감사하겠습니다 🙏

```swift
protocol AlertDelegate: UIViewController {
    func showAlert(alertMessage: AlertMessage, buttonMessage: AlertMessage)
}
```
<br>

### ❓ 네임스페이스에 대한 질문

네임스페이스를 별도 파일로 관리하는 것이 좋다고 생각하여 `JSONFileName`과 `AlertMessage`를 만들어 관리하도록 했습니다.
그런데 `identifier`의 경우는 `cell`의 `identifier`도 있고 `seuge`의 `identifier` 등 여러 UI요소에 `identifier`가 있어 쓰임새를 나눠서 관리할지 고민 하다가 결국 각 클래스에 `static let`으로 정의하였습니다.

#### 🤚 질문
`String`이라고 모두 모아서 관리하기 보다는 각자 쓰이는 곳에 `static let`으로 정의해 두었는데 현업에서 `identifier`는 보통 어떻게 관리하시는지 궁금합니다.

```swift
// EntryDataSource.swift
class EntryDataSource: NSObject, UITableViewDataSource {
    static let entryCell = "entryCell"
    … 
}

// KoreanEntryTableViewController.swift
class KoreanEntryTableViewController: UITableViewController, AlertDelegate {
    static let goToEntryDetail = "goToEntryDetail"
    …
}
```

2021-12-14 09:35 UTC, protocorn93 requested changes
@hoBahk @Jager-yoo 수고하셨습니다! 피드백 확인 부탁드릴게요! 

# 질문

## 인스턴스 생성 시점
`lazy` 키워드에 대해서 학습을 해보셨으면 아시겠지만, 해당 프로퍼티에 최초로 접근할 때 생성되고, 이후에는 최초에 생성된 객체를 사용합니다. 그렇기 때문에 `viewDidLoad`에서 생성이 되는겁니다. 왜냐하면 그 안에서 `tableView.dataSource = dataSource` 이렇게 접근해서 테이블 뷰에 할당해주고 있기 때문이죠. 

그나저나 현재 상황에선 굳이 옵셔널이나 `lazy`를 사용할 필요 없이 `private let dataSource = EntryDataSource()`로 바로 할당해주어도 상관없지 않나요? 생성 과정에서 `self`로 접근이 없어보이는데 말이죠. 

## 오류 처리에 대한 질문

음 현재 이 질문의 시작은 결국 json 파싱 결과가 필요할 때마다 매번 파싱해서 가져와 사용하기 때문인데요. 굳이 이렇게 매번 파싱해서 결과를 가져와 사용할 필요가 있을까요? (코멘트에도 잠깐 언급을 했지만) 첫 화면 진입때 한번 불러오고 이를 재사용하는게 더 좋은 방법인 것 같습니다. 

이와 별개로 데이터소스 객체를 별도로 분리한 점은 훌륭해요! 👍👍👍 이렇게 분리가 되었기 때문에 예거와 호박이 구현한 것처럼 에러 발생시 알럿을 띄어주고 싶을 때는 작성해주신 것처럼 델리게이트 패턴을 통해 이벤트를 전달해주는 것도 좋은 방법 중 하나라고 생각해요. 다만 여기서 다시 생각해보아야 할 것은

1.  셀 dequeue에 실패한 것을 사용자에게 알럿을 통해 알릴 필요가 있을까?
2. 셀 dequeue 실패가 "출품작 로딩에 실패"에 해당할까?

입니다. 이 부분에 대해서 다시 한번 고민해보셨으면 좋겠어요! 그리고 `delegate` 패턴 사용법에 대해서는 메모리 누수 디버깅에 대해서 학습해보시고 실제로 디버깅을 해보시는걸 권장드립니다. 참고로 현재 실행 결과의 메모리 상태를 간단히 보여드리자면 아래와 같습니다. 

<img width="387" alt="스크린샷 2021-12-14 오후 5 53 58" src="https://user-images.githubusercontent.com/20634806/145971091-40e97313-71cf-4f72-aa5d-a66644d51d04.png">

<img width="388" alt="스크린샷 2021-12-14 오후 5 54 06" src="https://user-images.githubusercontent.com/20634806/145971141-99e28ace-ac95-445f-bac1-62b49e10d3d2.png">

이 두 캡처가 무엇을 의미하는지 한번 학습해보시는걸 권장드려요! 매우 중요한 주제입니다. 

## 프로토콜에 대한 질문

전 괜찮은 방법이라고 생각해요! 알럿은 앱 전역에서 다양한 이유로 뜰 수 있습니다. 제가 속한 팀에서도 유사한 방법으로 구현하고 있어요! 

## 네임스페이스에 대한 질문

`identifier`에 대한 저의 의견은 코멘트에 남겨 놓았습니다. 

네임스페이스를 사용하면 보다 깔끔하게 raw value를 관리할 수 있습니다. 다만 그 범위, 즉 scope에 대한 고려도 필요하다고 생각해요. 

---

# 추가의견

1. 현재 디렉토리 구조와 이에 속한 파일들을 보면 일관성이 조금 부족해보이고, 해당 디렉토리에 속하기에는 애매한 파일들도 몇몇 보이는데요. 보다 디렉토리를 상세하게 구분하는게 좋아보입니다. `Extensions`라던지, `Services` 혹은 `Utils`처럼요! 

2. 스토리보드 역시 분리해서 관리하는 연습을 해보세요. 저는 스토리보드를 사용해 UI를 그릴 땐 하나의 뷰컨에 하나의 스토리보드(내비게이션 컨트롤러포함)를 지향하는 편입니다.

2021-12-14 09:35 UTC, protocorn93 commented on Expo1900/Expo1900/Model/EntryDataSource.swift
> +    static let entryCell = "entryCell"
reuse identifier의 정보의 주체는 cell이 되어야 합니다. `static let`으로 선언한다면 cell 클래스 내부에서 선언되어야 할 것 같아요. 
아직은 테이블 뷰에 대한 경험이 부족하기에 이렇게 구현하셨을텐데, 보통 현업에선 reuse identifier를 클래스명으로 지정합니다. 

또한 매번 `static let`을 선언할 필요없이, 간단한 `extension` 혹은 프로토콜+기본구현을 통해 reuse identifier를 제공하는데요. 제가 말씀드린 방법을 기반으로 구글링을 해보시면 정~말 많은 글들을 찾아보실 수 있을거에요!

2021-12-14 09:35 UTC, protocorn93 commented on Expo1900/Expo1900/Model/EntryDataSource.swift
> +              let entries = JSONParser<[KoreanEntry]>.decode(from: JSONFileName.koreanEntry) else {
이렇게 되면 매번 셀을 생성하고 재사용할 때마다 json 파일을 파싱해야하는데, 이는 굉장히 비효율적이라는 생각이 듭니다. 보다 쉽게 효율적으로 구현할 수 있는 방법이 있을 것 같은데요. 🤔

2021-12-14 09:35 UTC, protocorn93 commented on Expo1900/Expo1900/Model/ParisExpoInformation.swift
> +    var formattedVisitors: String {
현재 `ParisExpoInfomation` 구조체는 두 가지 역할을 하고 있는 것 같아요. 

1. DTO : 서버 응답값 매핑
2. Presenter : 화면에 보여주는 형태로의 가공

이렇게 두 가지의 역할을 하나의 객체가 담당하게 되고 이를 사용하게 된다면, 서버 응답값(현재는 단순한 json file을 사용하지만)이 변경되면 그 변경의 여파가 이를 사용하는 곳 전부로 퍼져나갑니다. 

그렇기에 저는 이러한 모델 성격의 객체들도 그 역할에 대해 최대한 나누어서 관리하려고 해요! 이 부분은 단순한 코멘트이기에 굳이 수정하실 필요는 없습니다. 다만 예거랑 호박이 앞으로 역할과 구조 그리고 아키텍처에 대해서 공부하시다보면 자연스럽게 접하게 될 주제라고 생각해요!

2021-12-14 09:35 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +        navigationItem.title = entry?.name
이 라인은 다른 아래의 코드들과 추상화 레벨이 달라보이는데요. 이를 통일시켜주는 것이 좋아보입니다.

2021-12-14 09:35 UTC, protocorn93 commented on Expo1900/Expo1900/Model/EntryDataSource.swift
> +    var delegate: AlertDelegate?
`UITableView`의 `delegate`와 `dataSource`의 선언부를 확인해보시길 바랍니다. 😁

2021-12-14 09:35 UTC, protocorn93 commented on Expo1900/Expo1900/Model/JSONFileName.swift
> +enum AssetName {
네임스페이스의 용도에 대해서는 이해했으나, 에셋명까지 이를 통해 관리하기에는 무리같아요. 앱이 커진다면 앱의 모든 에셋명을 여기서 관리하게 될텐데 이는 불필요할 것 같아요. 

만일 코드를 통해 에셋명이 필요할 경우에는 해당 클래스 안에서 상단 선언부에 선언해놓는게 더 좋아보입니다. 그게 아니라 공통 영역이라면 그때 앱 전역에서 쉽게 접근할 수 있는 네임스페이스에 대해 고민해보면 좋을 것 같구요.

2021-12-14 09:35 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/KoreanEntryTableViewController.swift
> +    private var dataSource: EntryDataSource?
이 프로퍼티는 옵셔널이나 `var`로 선언될 필요가 없어보입니다.

2021-12-14 09:38 UTC, protocorn93 commented on Expo1900/Expo1900/Model/AlertMessage.swift
> +enum AlertMessage: String {
`AssetName`에 남겨놓은 코멘트는 여기에도 해당할 것 같습니다.

2021-12-15 08:03 UTC, Jager-yoo commented on Expo1900/Expo1900/Controller/ParisExpoInformationViewController.swift
> +    private func setImages() {
먼저, 코드를 통해서 이미지를 넣어주는 목적의 `ImageView` 가 맞습니다.
인터페이스 빌더에서 이미지를 할당하지 않으니까 비어보이는 게 허전하기도 하고, 무엇보다 오토레이아웃을 맞춰두기가 애매하더라구요.
이미지를 미리 할당하니까 오토레이아웃 문제가 사라지길래, 그대로 유지해두게 됐습니다.

코드로 어차피 이미지를 넣어줄 거라면, 비어있는 이미지로 놔두는 게 좋을까요? (오토레이아웃은 어떻게든 해결하구요)

2021-12-15 08:07 UTC, hoBahk commented on Expo1900/Expo1900/Model/EntryDataSource.swift
> +    static let entryCell = "entryCell"
extension과 protocol 중 고민을 하였는데,
extension이 간단하고 보기 쉬운 것 같아 Class의 이름과 identifier를 동일하게 맞추고,
NSOject의 extension으로 identifier를 관리할 수 있도록 했습니다.

```swift 
extension NSObject {
    static var reuseIdentifier: String {
        return String(describing: self)
    }
}
```

2021-12-15 08:12 UTC, Jager-yoo commented on Expo1900/Expo1900/Model/EntryDataSource.swift
> +              let entries = JSONParser<[KoreanEntry]>.decode(from: JSONFileName.koreanEntry) else {
EntryDataSource() 클래스 내부에 `이니셜라이저`를 만들고,
외부에서 생성된 [KoreanEntry] 타입의 인스턴스를 `주입`받는 식으로 리팩토링했습니다!

```swift
// EntryDataSource.swift
class EntryDataSource: NSObject, UITableViewDataSource {
    let entries: [KoreanEntry]
    
    init(entries: [KoreanEntry]) {
        self.entries = entries
    }
}

// KoreanEntryTableViewController.swift
class KoreanEntryTableViewController: UITableViewController, AlertDelegate {
    private let dataSource = EntryDataSource(entries: JSONParser<[KoreanEntry]>.decode(from: JSONFileName.koreanEntry) ?? [])
```

2021-12-15 08:22 UTC, Jager-yoo commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +        navigationItem.title = entry?.name
좋은 포인트 코멘트주셔서 감사합니다!
다른 두 개는 메서드로 `캡슐화`를 했는데, 네비게이션 바의 title 에 접근할 때는 그냥 접근했군요. 😅 
아래와 같이 추가로 메서드 만들어서, `동일한 추상화 레벨`로 만들었습니다.

```swift
private func setNavigationBarTitle() {
    navigationItem.title = entry?.name
}
```

2021-12-15 08:30 UTC, hoBahk commented on Expo1900/Expo1900/Model/EntryDataSource.swift
> +    var delegate: AlertDelegate?
UITableView의 delegate와 dataSource의 선언부를 확인해 보았습니다.

```swift
weak open var dataSource: UITableViewDataSource?
weak open var delegate: UITableViewDelegate?
```

아래와 같이 코멘트 달아 주신 것과 같은 의미라고 생각하여 delegate를 weak으로 선언하였습니다.
dataSource의 경우에는 weak으로 할 시 메모리가 바로 해제되어 강한참조를 하였습니다.

![image](https://user-images.githubusercontent.com/90945013/146150912-acd58895-7ea2-423b-9a67-dcb6c72a6697.png)


저희가 이해한 것이 콘이 의도하신 질문에 대한 답이 맞을까요?

2021-12-15 08:33 UTC, Jager-yoo commented on Expo1900/Expo1900/Model/JSONFileName.swift
> +enum AssetName {
AssetName 열거형은 삭제하고, 해당 String 이 사용되는 클래스의 상단부에 `private let`으로 선언하는 식으로 수정했습니다!

```swift
class ParisExpoInformationViewController: UIViewController {
    private let parisExpoPoster = "poster"
    private let koreanFlag = "flag"
    ...
}
```

2021-12-15 08:35 UTC, Jager-yoo commented on Expo1900/Expo1900/Model/AlertMessage.swift
> +enum AlertMessage: String {
`AssetName`과 마찬가지로 AlertMessage 열거형도 삭제하고
해당 String 이 사용되는 클래스의 상단부에 `private let`으로 선언하여 사용했습니다! 😄 

```swift
class EntryDataSource: NSObject, UITableViewDataSource {
    private let jsonDecodingFailed = "정보를 불러오는데 실패했습니다."
    private let confirm = "확인"
```

2021-12-15 08:44 UTC, hoBahk commented on Expo1900/Expo1900/Controller/KoreanEntryTableViewController.swift
> +    private var dataSource: EntryDataSource?
위에서 답변 해주신 것을 참고하여 수정하였습니다. 

```swift
private let dataSource = EntryDataSource(entries: JSONParser<[KoreanEntry]>.decode(from: JSONFileName.koreanEntry) ?? [])
```

그런데 아래의 답변 중에서 "생성 과정에서 self로 접근이 없어보이는데 말이죠."의 의미를 이해하지 못했습니다. 
관련해서 힌트를 좀 더 주실 수 있을까요? 🤔 

![image](https://user-images.githubusercontent.com/90945013/146152892-9482388b-8bb5-4de0-bb67-c29c4053bfba.png)

2021-12-15 09:16 UTC, protocorn93 commented on Expo1900/Expo1900/Model/EntryDataSource.swift
> +    var delegate: AlertDelegate?
네네 델리게이트 패턴은 서로가 서로를 참조하고 있는데, 이런 상황에선 메모리 누수에 특히 유의해야 합니다!

2021-12-15 09:30 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/KoreanEntryTableViewController.swift
> +    private var dataSource: EntryDataSource?
네네~ 기본적으로 클래스 프로퍼티에 기본값을 할당할 때, `self`에 접근이 필요한 경우가 있습니다. 근데 프로퍼티 선언 시점에는 실제로 해당 클래스의 인스턴스는 생성되지 않았죠.

이럴 때도 우리는 `lazy` 키워드를 이용해서 변수할당을 미루면, 클래스 인스턴스가 생성된 후 런타임 시점에 프로퍼티에 접근을 하고 그때가 되어서야 `lazy`에 할당한 객체가 생성이되겠죠, 그러면 클래스 인스턴스(`self`)에 접근이 가능합니다. 

코드를 통해 말씀드리는게 더 이해가 잘될것 같은데요. 아래는 코드로 뷰를 만들 때의 코드입니다. 

```swift
class MyViewController: UIViewController { 
  private let myButton: UIButton = { 
    let button = UIButton(...)
    button.addTarget(self, #selector(myButtonDidTapped)
    return button
  }()

  ...

  override func viewDidLoad() { 
    super.viewDidLoad() 

    view.addSubview(myButton)
    .. 
  }

  @objc 
  private func myButtonDidTapped() { 
    .. 
  }
}
```

실제로 이런 코드를 작성하면 컴파일 에러가 발생합니다. `myButton` 인스턴스 생성시점은 컴파일 타임이고, 그 시점에 `MyViewController`는 생성되지 않은 상태이기에 `self` 접근이 불가능합니다. 

이런 상황에서 `lazy` 키워드를 사용해서 `private lazy var myButton: UIButton = { ... } ` 이와 같이 사용한다면 `viewDidLoad()` 안에서 `myButton`에 접근하는 시점에 `myButton`이 생성되기 때문에 `self` 접근이 가능해지겠죠!

2021-12-15 09:33 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/ParisExpoInformationViewController.swift
> +    private func setImages() {
네네. 굳이 중복해서 할당할 필요는 없어보이는데요~ 오토레이아웃이 에러가 거슬린다면 이미지의 너비와 높이 역시 함께 지정해주면 해결 가능할것같아요!

2021-12-15 09:34 UTC, protocorn93 commented on Expo1900/Expo1900/Model/EntryDataSource.swift
> +    static let entryCell = "entryCell"
이렇게 되면 `NSObject`를 상속받는 모든 클래스에서도 접근이 가능할텐데요. 

보다 specific한 역할을 위해선 `UICollectionViewCell`, `UITableViewCell`에만 특정해서 `extension`을 구현해주어도 될 것 같아요. 이것은 다음 스탭에서 구현해보시죠~

2021-12-15 12:07 UTC, Jager-yoo commented on Expo1900/Expo1900/Controller/ParisExpoInformationViewController.swift
> +    private func setImages() {
넵! 어차피 고정된 이미지가 들어갈 공간이고, STEP 3 에서 Accessibility 향상을 위해, 글자 크기가 커지면 이미지도 커지게 만들려고 합니다.
그러면 절대적인 width, height 를 주는 것 보다는, 이미지의 `가로/세로 ratio` 에 대한 constraint 만 주어서 다양한 크기에 대응할 수 있게 만들었습니다! 😄

2021-12-15 12:26 UTC, hoBahk commented on Expo1900/Expo1900/Model/EntryDataSource.swift
> +    static let entryCell = "entryCell"
UITableViewCell에서만 사용할 수 있도록 하였습니다! 😃
```swift
extension UITableViewCell {
    static var reuseIdentifier: String {
        return String(describing: self)
    }
}
```

2021-12-15 13:12 UTC, merged

2021-12-15 13:12 UTC, protocorn93 commented
@hoBahk @Jager-yoo 수고하셨습니다!