만국박람회 [STEP3] 조이 & 요한
yagom-academy/ios-exposition-universelle pull request #126
Opened 2021-12-15 12:33 UTC by YohanBlessYou

## 인사말

안녕하세요 쿠마~ @leejun6694 
벌써 STEP3네요! 이번 PR도 잘 부탁드려요🙏🙏

---

## 📌 STEP3 주요 요구사항
이전까지 구현했던 3개 화면에 대해 오토레이아웃과 Accessibility를 적용하는 것이 목표입니다

### 1. Orientation
1. 첫 화면은 세로 방향만 지원
2. 나머지 두 화면은 모든 방향 회전 지원

### 2. Dynamic Type
1. 모든 화면에서 Dynamic Type 지원
2. 아이패드를 제외한 모든 기기의 크기에 맞도록 구현
3. 텍스트가 잘리거나 줄임표(...) 처리가 되지 않도록

---

## 🤔 신경쓴 점 & 고민한 점

### 1. cellForRowAt 메서드 개선
스텝2에서는 cell의 레이블이나 이미지를 주는 작업을 cellForRowAt에서 했습니다

스텝3에서 커스텀 셀을 만들면서 해당 작업들을 cell 클래스 안으로 옮기고

```swift
override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: cellIdentifier, for: indexPath) as? EntryTableViewCell else {
            return UITableViewCell()
        }
        guard let entry = entries[index: indexPath.row] else {
            return cell
        }
        cell.configureContent(from: entry)
        cell.configureAccessibility(from: entry)
        
        return cell
    }
```
cellForRowAt 안에서는 cell 에서 정의한 메서드를 호출하는 식으로 변경했습니다
스텝2보다 가독성이 높아졌고 뷰와 뷰컨의 역할을 분리했다는 점에서 의의가 있는 것 같습니다

<br>

### 2. 버튼과 레이블이 겹쳐서 보이는 문제
**✔️ 문제상황**
!<img src="https://i.imgur.com/YAFqkFE.png" width="20%" height="30%">

**✔️ 문제**
첫번째 화면에서 글씨크기를 키우면 버튼과 레이블이 겹쳐서 보이는 문제가 있었습니다. 원인은 `태극기 + 버튼 + 태극기` 스택뷰의 Alignment가 fill 이었습니다

**✔️ 해결**
스택뷰의 Alignment를 `center`로 바꾸고, 임의의 숫자로 고정해 놓았던 스택뷰의 높이 제약을 제거해서 해결했습니다

<br>

### 3. 가로보기 모드에서 두번째 화면 진입 시 자동회전이 안되는 문제

**✔️ 문제**
(세로보기로 orientation이 고정된) 첫번째 화면에서 device를 눕힌 채로, (가로/세로 모두를 지원하는) 두번째 화면으로 전환하면 자동으로 가로보기가 되지 않는 문제가 있었습니다

**✔️ 해결**
`EntryTableViewController` 에서 아래 메서드를 호출해서 해결했습니다.

```swift
UINavigationController.attemptRotationToDeviceOrientation()
```
기능: 뷰 컨트롤러 별로 인터페이스 방향이 다를 때 이 메서드를 호출하면 시스템이 즉시 새 방향으로 회전을 시도한다

<br>

### 4. ImageView에 대한 Voice Over를 고민했습니다
VoiceOver 사용자에게 이미지 정보는 그다지 유효하지 않은 경우가 많다고 합니다. 그렇기 때문에 이미지에 대한 VoiceOver를 지원하지 않는 경우도 꽤 흔하게 볼 수 있습니다. 비록 이미지에 대해서 꼭 보이스 오버를 지원할 필요는 없지만, 어떻게 지원할 수 있을지 고민해봤고 최대한 정보를 전달할 수 있도록 노력했습니다.

---

## 🔍 궁금한 점 🔎

### Q1. Label 텍스트 가공을 Model에 구현하는게 맞을까요?
첫 화면에서 박람회에 대한 정보를 제공하는 Label에는 font size가 다른 텍스트가 혼합되어 있습니다

이를 표현하기 위해 `NSMutableAttributedString` 타입을 활용하고는, 이 가공 작업을 Model에 줄지 ViewController에 줄지 고민되었습니다

JSON에서 추출한 `Exposition` Model 데이터는, 이렇게 가공된 형태로만 사용되므로 뷰컨의 규모를 덜고자 `Exposition`의 computed 프로퍼티에 가공 작업을 구현하였습니다

> 질문: 하지만, 결국은 텍스트 가공이라는게 데이터를 '어떻게 보여줄 것인가'에 대한 것이라는 관점에서 View 혹은 ViewController에 구현했어야 했을까 하는 궁금증이 남아 쿠마의 의견을 묻습니다!

<br>

### Q2. device가 굉장히 많은데 UI 테스트를 일일히 시뮬레이터 돌려봐야 하나요?

모든 device에서 UI가 문제가 없는지 테스트가 필요했습니다 

효율적인 방법이 떠오르지 않아서 device 한 두개씩 device를 바꿔가며 시뮬레이터를 실행하고 모든 화면을 체크하였는데 하면서 이게 맞나? 싶더라구요😂

> 질문1: UI 테스트를 모든 device에 대해 해야 하는지 궁금합니다!
(디스플레이 크기 별로 하나씩만 하면 된다던지..)

> 질문2: 테스트해야 할 device가 많은데 시뮬레이터 레벨에서 한꺼번에 테스트 할 방법이 있을까요? (혹은 테스트 자동화?)

> 질문3: 현업에서는 어떻게 많은 device들을 테스트하시는지 궁금합니다!

<br>

### Q3. Cell 내부의 UI 요소에 대한 VoiceOver가 Accessibility Inspector에서 확인이 안되는 문제가 있었습니다

TableView에 VoiceOver Label을 지정해보았습니다
대상은 Cell 전체와 Cell 내부의 UI 요소였습니다

문제가 발생한 점은, Accessibility Inspector에서 title Label에 대해서는 VoiceOver를 테스트해볼 수 없었다는 점입니다
(Cell 전체에 대해선 테스트가 가능하나 Cell 내부의 title Label은 테스트 타겟으로 선택 자체가 되지 않았습니다)

> 질문: Cell 전체가 아닌 Cell 내부의 UI 요소들에 대해서 별도의 VoiceOver를 지정하는건 불가능한지 궁금합니다!

코드로 Label에 `accessibilityLabel`을 적용하는것은 가능한데 이를 테스트하거나 device에서 VoiceOver를 발동시키는게 가능한지 궁금합니다

*p.s. 상용 App인 카카오톡에서 대화내용 목록의 VoiceOver를 확인해봤을 때는, Cell 전체에 대해서만 걸려있었습니다*

2021-12-16 16:40 UTC, leejun6694 requested changes
조이, 요한 안녕하세요 : )
step 3 도 구현을 잘해주셔서 리뷰 내용이 조금 짧네요ㅎㅎ
몇 가지 포인트 확인 부탁드려요~~!

2021-12-16 16:40 UTC, leejun6694 commented on Expo1900/Expo1900/ViewController/NavigationController.swift
> +    }
NavigationController 에서 설정해준 이유가 궁금합니다 : )

2021-12-16 16:50 UTC, leejun6694 commented
> Q1. Label 텍스트 가공을 Model에 구현하는게 맞을까요?

음.. 정답이 아닐 수 있지만 저는 직관적으로 봤을 때, 말씀주신 것처럼 `어떻게 보일 것인지에 대한 문제`이므로 model 에서 구현을 하지 않을 것 같네요.

> Q2. device가 굉장히 많은데 UI 테스트를 일일히 시뮬레이터 돌려봐야 하나요?
> 질문1: UI 테스트를 모든 device에 대해 해야 하는지 궁금합니다!
(디스플레이 크기 별로 하나씩만 하면 된다던지..)
> 질문2: 테스트해야 할 device가 많은데 시뮬레이터 레벨에서 한꺼번에 테스트 할 방법이 있을까요? (혹은 테스트 자동화?)
> 질문3: 현업에서는 어떻게 많은 device들을 테스트하시는지 궁금합니다!

- 테스트 요구에 따라 달라지겠네요...!
- 필요한 시뮬레이터를 한번에 띄워주는 자동화는 있는 것으로 알고 있어요
- 저의 경우는 테스트 기기 하나로만 확인을 하고, 필요에 따라 SE 나 아이패드는 확인하고 있어요. 다른 크기의 device 는 검증팀에서 진행해주고 있습니다.

> Q3. Cell 내부의 UI 요소에 대한 VoiceOver가 Accessibility Inspector에서 확인이 안되는 문제가 있었습니다

cell 전체는 accessibility 를 disabled 시켜볼 수 있을까요?
저도 같이 확인해보고 싶어요~!

2021-12-17 05:39 UTC, na-young-kwon commented on Expo1900/Expo1900/View/EntryTableViewCell.swift
> +    @IBOutlet weak var entryImageView: UIImageView!
모두 외부로 노출될 일이 없을 것 같아 `private` 으로 접근제어 수정했습니다! 
꼼꼼한 리뷰 감사해요😁

2021-12-17 06:19 UTC, na-young-kwon commented on Expo1900/Expo1900/Extension/NSMutableAttributedString+Extension.swift
> +    func append(_ text: String, forTextStyle: UIFont.TextStyle) {
```swift
func append(string: String, forTextStyle: UIFont.TextStyle) {
    append(NSAttributedString(string: string, attributes: attributes))
}

// 사용처
description.append(string: "개최지", forTextStyle: .title3)
```

이렇게 수정해봤어요
- `NSAttributedString(string: )`에서도 `string`이라는 파라미터 명을 사용하고 있고
- 사용처에서도 파라미터가 없는것 보단 `string` 이라는  파라미터를 사용하는게 좀 더 명확하다는 생각이 들었습니다~!

2021-12-17 06:20 UTC, YohanBlessYou commented on Expo1900/Expo1900/ViewController/NavigationController.swift
> +    }
아래 그림처럼 Navigation 화면의 경우, NavigationController를 상위 뷰컨으로 가지므로 여기에 orientation 제약을 우선적으로 거는게 필요했습니다

다만 뷰컨마다 그 제약을 달리하기 위해, topViewController의 제약을 매번 읽어와 업데이트하는 방식을 사용했습니다

!<img src="https://user-images.githubusercontent.com/39155090/146498027-72a65c5e-66de-4b13-997e-9390f790374f.png" width="40%" height="50%">

2021-12-17 08:15 UTC, leejun6694 commented on Expo1900/Expo1900/ViewController/EntryTableViewController.swift
> +              }
해결~

2021-12-17 08:19 UTC, na-young-kwon commented on Expo1900/Expo1900/ViewController/EntryTableViewController.swift
> +              }
xcode가 권장하는 띄어쓰기로 `(control + i)` 통일하는것으로 이야기 나눴습니다😀

장점
- 코드의 통일성이 높아진다
- 협업시 띄어쓰기로 충동이 날 일이 없다

2021-12-19 17:50 UTC, leejun6694 approved these changes
LGTM

2021-12-19 17:50 UTC, merged