만국 박람회 [STEP 1] Lingo, 마이노
yagom-academy/ios-exposition-universelle pull request #135
Opened 2022-04-11 12:46 UTC by llingo

@wonhee009 
안녕하세요 라자냐 👍
만국 박람회 [STEP 1] PR 보냅니다. 잘 부탁드립니다!

### 고민 및 해결한 점
- 서로 커뮤니케이션을 통해 코딩 컨벤션을 맞추는 것을 고민했습니다.
- Info.plist를 Resource 폴더로 옮기는 과정에서 Packaging의 절대경로가 표시되지 않는 문제가 발생했고 
한번 빌드를 해줘야 절대경로가 표시되는 것을 알 수 있었습니다.
- 로컬에 있는 json 파일에서 데이터를 가져오는 방법에 대해 고민했고 
메인 Bundle에서 파일의 Path를 가져온 후 URL로 데이터를 가져오는 방법으로 해결할 수 있었습니다.

### 조언 받고 싶은 점
- Asset과 Info.plist 파일의 위치를 기존에는 View 폴더에서 관리 했었는데 Resource로 빼는 것에 대해 어떻게 생각하시는 지 궁금합니다.
- if의 조건문이 길어졌을때 아래의 코드처럼 줄바꿈을 하는 것에 대해 어떻게 생각하시는 지 궁금합니다. 
다른 방법이 있다면 조언 부탁드립니다! 🙇🏻 🙇🏻 🙇🏻
```swift
if let path = Bundle.main.path(forResource: "exposition_universelle_1900", ofType: "json"),
   let data = try? Data(contentsOf: URL(fileURLWithPath: path)) {
  XCTAssertNoThrow(try decoder?.decode(Expo.self, from: data))
}
```

2022-04-12 02:57 UTC, wonhee009 requested changes
스텝1 수고하셨습니다! 👏 
코멘트 확인 부탁드려요~ 🙏 

Q. Asset과 Info.plist 파일의 위치를 기존에는 View 폴더에서 관리 했었는데 Resource로 빼는 것에 대해 어떻게 생각하시는 지 궁금합니다.
A. 네 저는 좋은거 같습니다. 나중에 파일이 많아지면 이렇게 구분해두는게 나중에 찾을때 편하더라구요. 그리고 이런 구조들이 어느정도 개발자의 생각이나 프로젝트의 흐름을 대변해줄 수 있다고 생각합니다. (Application이라는 폴더 네이밍만 다시 한 번 생각해주세요:))

Q. if의 조건문이 길어졌을때 아래의 코드처럼 줄바꿈을 하는 것에 대해 어떻게 생각하시는 지 궁금합니다.
다른 방법이 있다면 조언 부탁드립니다! 🙇🏻 🙇🏻 🙇🏻
A. 조건문이 길어지면 코드가 조건이 한 눈에 들어오지 않아서 이렇게 줄바꿈을 합니다 좋아요!

<img width="40%" alt="image" src="https://user-images.githubusercontent.com/30456206/162869409-3c8c23d8-a3ae-4a45-9ed2-182df8c4215c.png">
혹시 AppDelegate를 삭제하고 새로 만든걸까요?

2022-04-12 02:57 UTC, wonhee009 commented on Expo1900/Expo1900/Model/Expo.swift
> +struct Expo: Codable {
`Codable`을 사용해보셨군요👍

[공식 문서](https://developer.apple.com/documentation/swift/codable)를 확인해보면 Codable은 
`typealias Codable = Decodable & Encodable` 이렇게 이뤄져 있는데요.
여기서 `Decodable`과 `Encodable`은 어떤 역할일까요?

2022-04-12 02:57 UTC, wonhee009 commented on Expo1900/Expo1900Tests/JSONDecodeTests.swift
> +  }
테스트에 사용되는 Asset name이 반복되어 사용되는거 같은데요.
이런 경우 상수로 관리하는건 어떨까요?
나중에 asset의 이름이 변경된다면 현재 코드에서는 모든 name을 바꿔줘야하지만 상수로 관리한다면 수정 한번이면 가능할거 같습니다 😄

2022-04-12 05:21 UTC, llingo commented on Expo1900/Expo1900/Model/Expo.swift
> +struct Expo: Codable {
### Encodable
> 인코딩을 할 수 있도록 해주는 프로토콜입니다.

Encoder에서 Swift 객체를 JSON 과 같은 데이터로 인코딩을 해줄 때 사용합니다.

### Decodable
> 디코딩을 할 수 있도록 해주는 프로토콜입니다.

Decoder가 JSON과 같은 데이터를 Swift 객체로 디코딩을 해줄 때 사용합니다.

---

🤔  다시 생각해보니 현재 프로젝트에는 JSON 형식으로 인코딩할 필요가 없기 때문에 `Codable`를 `Decodable`로 수정했습니다.

2022-04-12 05:42 UTC, Mino777 commented on Expo1900/Expo1900Tests/JSONDecodeTests.swift
> +  }
네임스페이스를 만들어 Asset Name을 상수로 관리하도록 변경하였습니다!
감사합니다!

2022-04-12 05:51 UTC, llingo commented
@wonhee009 

**1. Application이라는 폴더 네이밍만 다시 한 번 생각해주세요:)**
 AppDelegate와 SceneDelegate는 View의 라이프사이클보단 앱의 라이프사이클을 관리한다고 생각하여 Application으로 네이밍 했었습니다. 

> 🤔  라자냐는 어떻게 네이밍 하는 것이 좋다고 생각하시나요?

**2. 혹시 AppDelegate를 삭제하고 새로 만든걸까요?**
AppDelegate와 SceneDelegate 파일을 Application 폴더로 이동해서 파일이 변경된 것 같습니다.

2022-04-12 07:04 UTC, wonhee009 commented
AppDelegate나 SceneDelegate는 앱 전반적으로 영향을 준다고 생각해서 폴더링을 안하는 편이긴 합니다.
AppDelegate, SceneDelegate, Controller folder, Model folder... 이렇게 같은 계층에 놓는 편이에요.

`AssetName`을 별개의 파일로 관리하는데 현재는 test에서만 사용하는거 같습니다. 이후에 다른 곳에서도 사용할 예정으로 따로 분리해둔걸까요?

2022-04-12 12:56 UTC, Mino777 commented
@wonhee009 

**1.AppDelegate나 SceneDelegate는 앱 전반적으로 영향을 준다고 생각해서 폴더링을 안하는 편이긴 합니다.
AppDelegate, SceneDelegate, Controller folder, Model folder... 이렇게 같은 계층에 놓는 편이에요.**
아하..! 저희도 생각해보니 같은 계층에 두는 것이 맞다고 생각해서 라자냐 말씀처럼 수정하였습니다!
감사합니다!

**2. AssetName을 별개의 파일로 관리하는데 현재는 test에서만 사용하는거 같습니다. 이후에 다른 곳에서도 사용할 예정으로 따로 분리해둔걸까요?**
넵 맞습니다! 추후 STEP에서 다른 곳에서도 해당 AssetName들을 사용할 것이라고 판단해서 별개의 파일로 분리해서 관리하도록 진행하였습니다!
감사합니다!

2022-04-13 02:09 UTC, wonhee009 approved these changes
스텝1 수고하셨습니다! 🎉

2022-04-13 02:09 UTC, merged