만국 박람회 [STEP 1] 쿼카, Tiana
yagom-academy/ios-exposition-universelle pull request #137
Opened 2022-04-11 14:36 UTC by Quokkaaa

@Monsteel 
안녕하세요 토니!! 
STEP1 PR 잘 부탁드립니다. 🙇‍♂️🙇‍♂️

### 구현한 내용
* struct KoreanHistoricalItem: Decodable
    * name: String
    * imageName: String
    * shortDesciption: String
    * description: String
    
    * enum CodingKeys: String, CodingKey
        * case name
        * case imageName = "image_name"
        * case shortDesciption = "short_desc"
        * case description = "desc"

* struct ParisExpo: Decodable
    * title
    * visitors
    * location
    * duration
    * description

---

### 고민한 점
- encode할 필요가 없다고 판단되어 Codable에서 Decodable로 채택 수정한 점
- 출품작이라는 네이밍 고민
- testcase에서 XCTAssertEqual() 메서드를 사용해서 타입이 json data를 잘 decode하는지 확인
- 공식문서에는 프로퍼티들이 var로 설정되어있었으나 만국박람회 프로젝트에서는 수정할 필요가 없을것같아 let으로 변경

2022-04-12 14:07 UTC, 1Consumption requested changes
안녕하세요 티아나 쿼카~
잘부탁드립니다 🙇‍♂️ 

스텝이 작기도하고, 깔끔하게 잘 짜주셔서 리뷰할게 별로 없네요.

코멘트 참고해주세요.

2022-04-12 14:07 UTC, 1Consumption commented on Expo1900/Expo1900/Application/SceneDelegate.swift
> +
사용하지 않는 주석 제거 좋습니다 👍

2022-04-12 14:07 UTC, 1Consumption commented on Expo1900/Expo1900/Model/KoreanHistoricalItem.swift
> +
바뀌지 않을 값이라고 판단해서 let으로 선언하셨군요. 이부분도 좋습니다

2022-04-12 14:07 UTC, 1Consumption commented on Expo1900/KoreanHistoricalItemTests/KoreanHistoricalItemTests.swift
> +        }
이렇게 모든 값을 비교하기 보다는 Equatable을 채택해서 객체 자체를 비교하는건 어떨까요?

2022-04-13 08:01 UTC, Quokkaaa commented on Expo1900/KoreanHistoricalItemTests/KoreanHistoricalItemTests.swift
> +        }
https://github.com/yagom-academy/ios-exposition-universelle/pull/137/commits/521190a9050cd333de11c30fd65713e3db57afb1

2022-04-13 12:13 UTC, merged