만국 박람회 [STEP1] Onetool, Eddy
yagom-academy/ios-exposition-universelle pull request #138
Opened 2022-04-12 02:47 UTC by kimkyunghun3

@1Consumption 
안녕하세요 올라프
프로젝트 첫 번째 PR 보냅니다! 
잘부탁드려요~

# 구현 사항
`WorldFairPoster: Codable` : 만국박람회의 메인 화면에 대해 decode 진행을 위한Json 키값을 매칭

`KoreaEntryDetail: Codable` : 만국박람회의 한국의 박람회에 대해 decode 진행을 위한 Json 키 값을 매칭

`Expo1900Tests: XCTestCase` : unit test code 작성

# 고민한 점 및 조언 얻고 싶은 부분
- Testcode 작성

작성한 Decoder 파일을 이용해서 Test code를 통해 제대로 되는지 확인하고 싶었습니다.
첫 번째 테스트 코드는 `exposition_universelle_1900.json` 이 있고 이에 대한 데이터가 존재하는지를 Throw를 통해 확인했습니다.

두 번째 테스트 코드는 실제 Decode된 것이 우리가 만든 Decoder와 매칭이 되는지 확인하는 테스트 코드를 작성했습니다.
저희가 처음 의도는 Mock.json 파일을 만들어서 이곳에서 읽어서 매칭이 되는 것을 확인하려고 했는데, 실제 코드를 돌렸을 때 테스트 코드가 작동 잘되는 것처럼 보였지만 else에 출력을 찍어보니 이곳으로 넘어가는 것을 보게 되었습니다.
그래서 경로의 문제인가 여러 시도를 해보았지만 잘 되지 않아서 Assets 파일에 넣어서 NSDataAsset를 활용해서 경로 파악 후 디코더 하는 식으로 했습니다. NSDataAsset는 asset 카테고리에 저장된 데이터 중 인스턴스를 불러올 수 있어서 가능했는데. `Bundle.main.url` 방식으로 했을 때에는 Mock.json에 접근이 안되어서 이 이유를 정확히 몰라서 조언을 얻고 싶습니다.

- Assets에 추가하지 않고, 직접 경로를 지정해줄 수 있나요?

- 불필요한 CodingKeys 해야할 필요 있을지

Docoder를 만들 때 변수명이 카멜케이스 방식이 아닌 경우 CodingKeys를 통해 해야하는 것은 맞지만 그 외에 name를 title로 바꾸는 작업같은 경우는 같이 작업하는 개발자끼리 협의에 따라 결정짓는 것처럼 보였는데 그렇게 저희 팀이 자의적 판단으로 할지말지 결정하면 될까요?

- Decoder 구조체 네이밍

Codable로 사용하는 구조체들에 대한 네이밍을 정할 때 가져오는 데이터들을 표시하는 화면을 네이밍 정하면 괜찮을지 궁금하네요!

2022-04-12 14:01 UTC, 1Consumption requested changes
안녕하세요 에디 원툴~
잘부탁드립니다🙇‍♂️ 

아래와 같은 커밋은 어떤걸 의미하는 건가요? 특히 맨 아래 커밋은 하나의 역할을 하는게 아닌 거 같아요.
<img width="619" alt="image" src="https://user-images.githubusercontent.com/37682858/162978062-96b35089-ad9e-420a-a05b-527ac8f9d73a.png">

아래는 질문 주신 부분에 대한 답변입니다.

> 작성한 Decoder 파일을 이용해서 Test code를 통해 제대로 되는지 확인하고 싶었습니다.
첫 번째 테스트 코드는 `exposition_universelle_1900.json` 이 있고 이에 대한 데이터가 존재하는지를 Throw를 통해 확인했습니다.
두 번째 테스트 코드는 실제 Decode된 것이 우리가 만든 Decoder와 매칭이 되는지 확인하는 테스트 코드를 작성했습니다.
저희가 처음 의도는 Mock.json 파일을 만들어서 이곳에서 읽어서 매칭이 되는 것을 확인하려고 했는데, 실제 코드를 돌렸을 때 테스트 코드가 작동 잘되는 것처럼 보였지만 else에 출력을 찍어보니 이곳으로 넘어가는 것을 보게 되었습니다.
그래서 경로의 문제인가 여러 시도를 해보았지만 잘 되지 않아서 Assets 파일에 넣어서 NSDataAsset를 활용해서 경로 파악 후 디코더 하는 식으로 했습니다. NSDataAsset는 asset 카테고리에 저장된 데이터 중 인스턴스를 불러올 수 있어서 가능했는데. `Bundle.main.url` 방식으로 했을 때에는 Mock.json에 접근이 안되어서 이 이유를 정확히 몰라서 조언을 얻고 싶습니다.

엑스코드 버전이 올라가면서 직접 접근하면 안되고, NSDataAsset으로 접근해야 하는거로 알고 있습니다.

> Docoder를 만들 때 변수명이 카멜케이스 방식이 아닌 경우 CodingKeys를 통해 해야하는 것은 맞지만 그 외에 name를 title로 바꾸는 작업같은 경우는 같이 작업하는 개발자끼리 협의에 따라 결정짓는 것처럼 보였는데 그렇게 저희 팀이 자의적 판단으로 할지말지 결정하면 될까요?

네~ 직접 판단 할 문제 같아요.

> Codable로 사용하는 구조체들에 대한 네이밍을 정할 때 가져오는 데이터들을 표시하는 화면을 네이밍 정하면 괜찮을지 궁금하네요!

어떤걸 질문하는지 잘 모르겠어요. 조금 더 구체적으로 말씀해주시면 답변하는데 도움이 될 거 같습니다.

나머지는 코멘트로 남겼습니다.

2022-04-12 14:01 UTC, 1Consumption commented on Expo1900/Expo1900/Model/WorldFairPoster.swift
> +struct WorldFairPoster: Codable {
Codable은 어떤 프로토콜인가요? 어떤 프로토콜들로 이루어져 있나요?
어떤 프로토콜로 이루어져 있는지 확인했다면, 필요없는 프로토콜을 채택한게 아닐까 생각해볼까요?
힌트를 드리자면 지금 encoding할 일이 있을까요?

2022-04-12 14:01 UTC, 1Consumption commented on Expo1900/Expo1900/Model/KoreaEntryDetail.swift
> +}
다 변수로 선언되어 있네요! 바뀔 값일까요?

2022-04-12 14:01 UTC, 1Consumption commented on Expo1900/Expo1900/Model/WorldFairPoster.swift
> +    var description: String
여기도 변수네요.

2022-04-12 14:01 UTC, 1Consumption commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +        }
스텝1은 asset을 받아서 처리하는게 아니라 모델 구조를 만드는 거 아닌가요? 이부분은 스텝을 넘은 거 같습니다.

그리고 이 메소드는 정확히 어떤걸 테스트 하는 건가요? JsonDecoder 자체의 동작을 테스트하는 건가요? 아니면 내가 만든 로직을 테스트하는 건가요? 
사실 이 테스트 코드는 아래에 작성하신 메소드로 대체될 수 있을 거 같은데요...

2022-04-12 14:01 UTC, 1Consumption commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +}
과연 title만 같으면 같은 객체라고 볼 수 있을까요? 객체 전체를 비교하는게 맞지 않을까요? `Equatable`이라는 프로토콜에 대해서 학습해보시면 좋을 거 같습니다.

2022-04-14 04:28 UTC, kimt4580 commented on Expo1900/Expo1900/Model/KoreaEntryDetail.swift
> +}
바뀌지 않을 값이라고 한단하여, let 으로 변경해주었습니다!

2022-04-14 04:28 UTC, kimt4580 commented on Expo1900/Expo1900/Model/WorldFairPoster.swift
> +    var description: String
let 으로 변경해주었습니다!

2022-04-14 04:29 UTC, kimt4580 commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +        }
대체 하기 위하여, test 코드를 삭제해주었습니다!

2022-04-14 04:29 UTC, kimkyunghun3 commented on Expo1900/Expo1900/Model/WorldFairPoster.swift
> +struct WorldFairPoster: Codable {
Codable 에는 Encodable과 Decodable 프로토콜로 이루어져 있습니다. Codable 는 디코더와 인코더 둘다 가능하게 만드는 프로토콜입니다. 하지만 여기에서는 저희는 받아와서 Decode해주기만 하기 때문에 Encodable이 필요하지 않습니다. 그러므로 Decodable만 채택하여 다른 사람이 보았을 때 어떤 역할인지 더 명확할 것 같다고 생각해서 수정했습니다!

2022-04-14 04:32 UTC, kimkyunghun3 commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +}
Equtable을 사용해서 연산자를 확장해서 사용하면 좋겠군요! 그래서 저희는 이 내부에서 '==' 를 통해 필요한 JSON 내부의 요소들을 체크할 수 있도록 생각했습니다. 이로써 내부 코드를 은닉화 할 수 있을 것 같았습니다.
그리고 이를 실제 사용할 떄에는 WorldFairPoster에 있는 것과 result 상수에 들어갈 실제 내용을 적고 이들이 같은지 비교해서 같으면 테스트를 통과하도록 구현했습니다!

2022-04-14 05:43 UTC, merged