만국박람회 [STEP 1] Donnie, Grumpy
yagom-academy/ios-exposition-universelle pull request #139
Opened 2022-04-12 03:20 UTC by grumpy-sw

안녕하세요 스티븐! 🙇🏻‍♂️🙇🏻‍♂️
@stevenkim18

[STEP 1] PR 요청보냅니다!🙌
잘 부탁드리겠습니다.😄

### [STEP 1] 기능 구현 사항 📝 
- `Entry: Codable`
    - `name: String`
    - `imageName: String`
    - `introduction: String`
    - `description: String`
    - `enum CodingKeys: CodingKey`
        - `case name`
        - `case imageName = "image_name"`
        - `case introduction = "short_desc"`
        - `case description = "desc"`
- `Exposition: Codable`
    - `title: String`
    - `visitors: Int`
    - `location: String`
    - `duration: String`
    - `description: String`

### [STEP 1] 궁금한 점 ⁉️
1. 테스트코드 작성 시 타입으로 `Decode`가 제대로 되었는지 확인하기 위해 `XCTAssertEqual`함수를 사용하여 `JSON`의 내용과 비교하였는데 일일이 값 비교를 하지 않는 방법이 있는지 궁금합니다.

2. 현재 프로젝트는 `Asset`으로 데이터를 담아서 진행하는데, 현업에서도 `Asset`을 활용하여 프로젝트를 하나요? 어떤 방식으로 진행하게 되나요?

3. `Codable`은 `Encoder`와 `Decoder`가 합쳐져있는걸로 알고 있는데, 때에 따라서 용도에 맞게 각각 채택을 해줘도 될거 같다는 생각이 들었습니다. 그럼에도 Codable을 사용하는 이유가 편리성 때문일까요? 개발자의 취향 혹은 선택의 문제일까요?

2022-04-12 12:03 UTC, stevenkim18 commented
안녕하세요! 도니 그럼피!! 저도 잘 부탁드립니다! 

처음 들어오셨을 때 PR 관련 필독사항에도 적혀있듯이 코드리뷰는 저와 의견을 나누는 자리입니다!!

코드에는 정답은 없습니다!! 제가 틀리다면 근거를 가지고 지적해주세요!!

질문을 받는 저도 성장하는 시간입니다!! **많이 질문해주세요!!** ㅎㅎ

저는 **커뮤니케이션**을 매우 중시합니다! 실제로도 현업에서 매우 중요한 것 중 하나입니다!!

- PR을 보낼 때 어떻게 하면 최대한 **2분이서 짠 코드를 효과적으로 보여줄 수 있을지**를 고민해주세요!!
    - 최대한 글을 **가독성** 있게 작성해주시고 글로 부족하다면 저에게 음성 쳇을 요청해주세요!
- 질문을 할 때 이 **질문을 한 배경**과 **고민한 점**을도 같이 남겨주시면 제가 더 많은 이야기를 해드릴 수 있습니다.
- 코딩 뿐만 아니라 글, 말 등도 많이 훈련하셔서 여기서 많은 것들을 얻어가셨으면 합니다! ㅎㅎ

---

### 요청 사항

- **가능하시면 PR은 main 브랜치에서 해주세요!** 제가 클론하기도 편하고 브랜치 전략을 조금 데도 도움이 됩니다.
- 커밋 컨벤션 규칙을 보고 싶은데 리드미에 없더라구요. 캠프 사이트에 가서 제가 직접 찾았습니다. 두분의 개발 규칙들은 리드미에 적어주시면 좋을 것 같아요.

## 궁금한 점

1.  테스트코드 작성 시 타입으로 `Decode`가 제대로 되었는지 확인하기 위해 `XCTAssertEqual`함수를 사용하여 `JSON`의 내용과 비교하였는데 일일이 값 비교를 하지 않는 방법이 있는지 궁금합니다.

> ****Equatable을 한번 찾아보세요!****
> 

1. 현재 프로젝트는 `Asset`으로 데이터를 담아서 진행하는데, 현업에서도 `Asset`을 활용하여 프로젝트를 하나요? 어떤 방식으로 진행하게 되나요?

> 이미지를 사용할 떄는 많이 사용하고 json 파일은 거의 사용하지 않습니다. 저의 경우는 그렇습니다!
> 

1. `Codable`은 `Encoder`와 `Decoder`가 합쳐져있는걸로 알고 있는데, 때에 따라서 용도에 맞게 각각 채택을 해줘도 될거 같다는 생각이 들었습니다. 그럼에도 Codable을 사용하는 이유가 편리성 때문일까요? 개발자의 취향 혹은 선택의 문제일까요?

> 아마 같이 자주 사용하기 떄문에 Coable을 애플에서 만들어 주지 않을까요? ㅎㅎ Decode만 하면 Decoder만 채택하고 Encode도 마찬가지라고 생각합니다.
>

2022-04-12 12:49 UTC, stevenkim18 requested changes

2022-04-12 12:49 UTC, stevenkim18 commented on Expo1900/Expo1900/Model/Entry.swift
> +struct Entry: Codable {
위에 말씀드린것 처럼 언제 Codable을 쓰고 Decoable을 사용할지 고민해보세요!

2022-04-12 12:49 UTC, stevenkim18 commented on Expo1900/Expo1900/Model/Entry.swift
> +    var description: String
var로 하신 이유가 있을까요?

2022-04-12 12:49 UTC, stevenkim18 commented on Expo1900/Expo1900/Model/Entry.swift
> +    }
CodingKeys를 private으로 놓으셨군요!! 아주 잘하셨습니다!!

2022-04-12 12:49 UTC, stevenkim18 commented on Expo1900/Expo1900Tests/JsonParsingTests.swift
> +        guard let asset = NSDataAsset.init(name: "exposition_universelle_1900") else { return }
NSDataAsset에 꼭 init을 써야하나요?

2022-04-12 12:49 UTC, stevenkim18 commented on Expo1900/Expo1900Tests/JsonParsingTests.swift
> +    }
decode가 실패했을 때는 어떻게 알 수 있을까요?
decode가 실패하던 파싱한 title이 다르던 같은 fail이 뜰 것 같아요!

2022-04-12 12:49 UTC, stevenkim18 commented
그리고 Asset에서 이미지 json 파일은 분리해주면 더 좋을 것 같습니다!!

2022-04-13 08:41 UTC, westeastyear commented on Expo1900/Expo1900/Model/Entry.swift
> +struct Entry: Codable {
만국박람회 프로젝트에서는 `JSON`데이터를 받기만 해도 돼서 `Decodable로` 충분하다고 생각되어 변경하였습니다.
`Codable`은 `Encodable`, `Decodable` 두가지 기능이 필요할때가 아니면 불필요하다고 생각됩니다⭐️

2022-04-13 08:42 UTC, grumpy-sw commented on Expo1900/Expo1900/Model/Entry.swift
> +    var description: String
변수가 아닌 상수로 선언해도 될 것 같네요! 수정하겠습니다.

2022-04-13 08:45 UTC, grumpy-sw commented on Expo1900/Expo1900Tests/JsonParsingTests.swift
> +        guard let asset = NSDataAsset.init(name: "exposition_universelle_1900") else { return }
`NSDataAsset` 공식문서에 따르면 Initializing the Data Asset 하기 위해서는 `init?(name:)` 메서드를 사용한다고 적혀 있는데, 테스트 코드로 확인한 결과 `NSDataAsset(name: "exposition_universelle_1900")` 와 같이 사용할 수 있는 것으로 보입니다 ㅎㅎ 변경했습니다.

2022-04-13 08:58 UTC, grumpy-sw commented on Expo1900/Expo1900Tests/JsonParsingTests.swift
> +    }
decode가 성공했다고 가정하고 그 결과를 비교하는 것만 생각했던 것 같습니다.
decode가 실패했을 때 테스트 오류를 잡는 코드와 파일을 찾지 못했을 때 오류를 잡는 코드를 삽입하였습니다.

2022-04-13 09:10 UTC, grumpy-sw commented
@stevenkim18  안녕하세요 스티븐!

피드백 주신 부분 반영해서 소스 업데이트 해봤습니다~
코멘트 남겨주신 부분에는 저희의 생각을 적어두었습니다.

더불어 말씀해주신 대로 PR을 main 브랜치에서 하도록 수정했습니다😆

2022-04-14 01:08 UTC, stevenkim18 approved these changes
고생하셨습니다!!! 
머지하겠습니다!! 다음 스탭 진행해주세요!!
(언제까지 보내주실지도 디엠으로 알려주세요!!)

2022-04-14 01:08 UTC, stevenkim18 commented on Expo1900/Expo1900Tests/JsonParsingTests.swift
> +        }
잘하셨습니다!!

저는 개인적으로 when then을 깔끔하게 하고 싶어서 do catch를 지양해서
```swift
// when
guard let decodedData = try? decoder?.decode(Exposition.self, from: asset.data) else {
    XCTFail()
    return
}
        
// then
XCTAssertEqual(decodedData.title, "파리 만국박람회 1900(L'Exposition de Paris 1900)")
```
이렇게도 쓸 수 있을 것 같아요!

2022-04-14 01:08 UTC, merged