만국박람회 [STEP 1] Doogie, Red
yagom-academy/ios-exposition-universelle pull request #140
Opened 2022-04-12 03:57 UTC by doogie97

@TTOzzi
안녕하세요! 또치🦔 STEP1 완료해서 보냅니다!
잘부탁드립니다!😁😄

## UML
![](https://i.imgur.com/H8wuVgU.png)

## 고민했던 것들 
### 1. private(set)
![](https://i.imgur.com/5JbTLf9.png)
읽기 전용으로 접근제어를 설정해주고자 private(set)으로 설정하려고 했으나 let 자체가 읽기 전용이라 에러가 발생해 따로 접근제어를 걸어두지 않았습니다

### 2. decoder 위치
저희가 decode 라는 메서드를 만들면서 위치에 대한 논의가 있었습니다.

처음엔 아래 코드와 같이 모델에 Decoding 이라는 구조체를 만들어 주었습니다.
```swift 
struct Decoding {
    let decoder = JSONDecoder()
    func decoding() -> Exposition? {
        guard let expositionAsset = NSDataAsset.init(name: "exposition_universelle_1900") else { return nil }
        do {
            let expositionJSON = try decoder.decode(Exposition.self, from: expositionAsset.data)
            return expositionJSON
        } catch {
            print("error: \(error)")
        }
        return nil
    }
}
```
논의 끝에 이 구조체가 꼭 필요하지 않다는 결론을 내리고 아래와 같이 
Exposition 타입안에 static 을 사용해서 메서드를 넣어주었습니다.
```swift 
struct Exposition: Codable {
    //생략
    static func decode() -> Exposition? {
        let decoder = JSONDecoder()
        guard let expositionAsset = NSDataAsset.init(name: "exposition_universelle_1900") else { return nil }
        let expositionJSON = try? decoder.decode(Exposition.self, from: expositionAsset.data)
        return expositionJSON
    }
}
```

그런데 각각의 메서드에서 같은 역할을 하고 있어 제네릭으로 시도를 해 보았지만 return Type 이 
T, [T] 로 달라 실패 했습니다. 

그래서 두 메서드를 합치기 위해서 Decodable 프로토콜에 익스텐션에 return 타입을 Decodable? 로 가지는 메서드를 만들고 추후에 다운 캐스팅 해주도록 만들었습니다. 
```swift
extension Decodable {
    static func decode(with assetName: String) -> Decodable? {
        guard let asset = NSDataAsset.init(name: assetName) else { return nil }
        
        let decoder = JSONDecoder()
        if assetName == "items" {
            let items = try? decoder.decode([Self].self, from: asset.data)
            return items
        } else {
            let exposition = try? decoder.decode(Self.self, from: asset.data)
            return exposition
        }
    }
}
```

## 조언 받고 싶은 내용

### 1. JSON에서 각각의 key가 하는 역할
```swift{
  "data" : [
    {
      "filename" : "items.json",
      "idiom" : "universal"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
```
`filename, scale`의 경우 파일 이름을 가리키는구나, 이미지의 크기를 나타내는구나 하고 생각할 수 있었으나 `idiom, author, version`의 경우 asset에 들어가기 위해 작성된 것 같다는 내용을 지레짐작만 하고 있을 뿐 어떤 역할을 하는 것인지 감이 잡히지 않아 이 부분에 대해 여쭤보고 싶습니다

### 2. decode 메서드의 위치 
저희가 고민했던 점 2번에서 이야기 드린 것 처럼 decode 메서드의 위치를 고민했었는데요, 일반적인 예제 코드에서는 decode 를 View Controller 에서 많이 처리 하더라구요. 저희는 데이터를 주관하는 부분은 되도록이면 모델이 있어야 한다고 생각해서 모델 쪽에 두도록 했는데요, View Controller 에 넣는 다른 의미가 있는데 저희가 모르는 걸까요? 만약 모델이 넣는다고 하면 각각 메서드를 만들어 주는 쪽이 좋을까요? 아니면 저희가 마지막에 결정한 것처럼 protocol 로 빼는 것이 좋을까요? 조언 부탁 드립니다.

### 3. UML에서 typealias 표현 방법
Codable이 codable과 decodable의 typealias인데 이를 UML에 한 번에 표현 할 방법이 있는지 궁금합니다
(일단은 protocol을 두개를 만들어서 채택하는 형식으로 표현함)

### 4. Decodable? 로 반환할 때 [Self]? 도 반환이 되는 경우
![](https://i.imgur.com/t4cuROs.png)

[Self]? == Decodable? 로 인식이 돼서 정상적으로 반환이 되는 것 같은데 왜 배열타입과 Decodable타입이 동일 타입으로 취급되는 것인지 궁금합니다.

2022-04-12 15:47 UTC, TTOzzi requested changes
안녕하세요 두기 레드!
고민하신 부분, 궁금한 점에 대한 답변과 코드에 코멘트 몇 개 남겨두었어요~
보시고 이해가 어려운 부분이 있다면 언제든지 말씀해주세요 🙏 
고생하셨습니다 🙇 


### private(set)

`private(set)` 은 말 그대로 `get` 은 열어두고  `set` 만 감추는 접근 제한자이므로 이미 `set`을 할 수 없는 `let`을 사용한다면 붙여줄 필요가 없습니다.
`private(set)`은 해당 프로퍼티가 선언된 객체 내부에서 변경할 필요가 있을 때 사용하시면 됩니다.

### JSON에서 각각의 key가 하는 역할

[Asset Catalog Format Reference](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/ImageSetType.html) 요기 관련 공식 문서가 있네요 😎
애플에서 제공하는 기능에 대해 궁금한 점이 생기면 항상 공식 문서를 먼저 찾아보시는게 좋습니다.

### decode 메서드의 위치

> 저희가 고민했던 점 2번에서 이야기 드린 것 처럼 `decode` 메서드의 위치를 고민했었는데요, 일반적인 예제 코드에서는 `decode` 를 `View Controller` 에서 많이 처리 하더라구요. 저희는 데이터를 주관하는 부분은 되도록이면 모델이 있어야 한다고 생각해서 모델 쪽에 두도록 했는데요, `View Controller` 에 넣는 다른 의미가 있는데 저희가 모르는 걸까요?

예제라 최대한 간단하게 실행 가능한 코드를 제시하기 위해 `ViewController`에 구현하지 않았을까 싶네요 :thinking:
말씀하신대로 디코드 로직은 뷰단과 분리하는 게 좋다고 생각합니다. 지금 구현도 괜찮아보여요!

### UML에서 typealias 표현 방법

흠 글쎄요.. `typealias` 는 UML에서 이렇게 그려야 한다! 라고 정해진 건 없습니다 :thinking:
`typealias` 도 하나의 타입이니 타입 하나로 표현해도 될 것 같고, 지금 그리신 것 처럼 두 개로 분리해서 둬도 될 것 같네요.
생각하기 나름인 것 같아요!

### Decodable의 확장으로 decode 메서드를 만들었는데 Decodable의 배열인 [Decodable] 또한 decode메서드를 사용 가능 한 이유

제가 질문을 잘 이해한지 모르겠지만.. 
`[Item]` 타입에 `.decode(with:)`를 붙였을 때도 왜 디코드가 잘 되는 것인가 가 궁금하신 거라면, `[Item]` 타입에서 호출할 땐 `Self`가 `Item`이 아닌 `[Item]`이므로 자연스럽게 반환값도 `[Item]`이 되게 됩니다!

특정 타입 `Item`이 `Decodable` 인데 어떻게 자동으로 `[Item]`도 `Decodable`을 채택한 것처럼 동작하는가 가 궁금하신 것이라면, [Array](https://developer.apple.com/documentation/swift/array) 공식문서의 **Encoding and Decoding** 부분을 보시면 아주 작은 글씨로 배열 내부 요소가 `Decodable`을 채택하고 있다면 디코드 관련 기능을 제공해준다고 적혀있는 것을 확인하실 수 있습니다 😎

2022-04-12 15:47 UTC, TTOzzi commented on Expo1900/Expo1900/Extension/extension+Decodable.swift
> +import UIKit
`Foundation`과 `UIKit`은 어떤 차이가 있을까요?
불필요한 코드를 줄여볼 수 있을 것 같아요!

2022-04-12 15:47 UTC, TTOzzi commented on Expo1900/Expo1900/Extension/extension+Decodable.swift
> +    }
디코드 로직은 `key` 한 개, `value` 하나의 타입만 변경되어도 실패하게 됩니다.
그럼 `json` 파일의 어느 부분이 잘못되었는지, 선언한 모델 구조체의 타입이 잘못 맞춰지진 않았는지 확인이 필요해요.
`decode`를 사용하면 실패 시 어느 부분이 잘못되었는지 에러를 던져서 개발자에게 알려주는데요.
그 부분을 `try?`로 처리하고 있어 실패하더라도 어느 부분이 잘못되었는지 파악하기 어려울 것 같습니다 😢 

지금 구현에서 이 메서드가 실패하면 전달받은 `assetName`이 잘못되어 `nil`이 반환되었는지, `decode`가 실패해서 `nil`이 반환되었는지 알 수 있을까요?
실패했을 때 어떤 이유로 실패했는지 명확하게 알 수 있도록 개선해보면 좋을 것 같아요 🙂

2022-04-12 15:47 UTC, TTOzzi commented on Expo1900/Expo1900/Model.swift
> +//  Model.swift
Xcode navigator에서 이 파일 이름만 보고 파일 내에 어떤 타입이 선언되어있는지 알 수 있을까요?
현재는 프로젝트 규모가 작아 요렇게 한 곳에 몰아둬도 전반적인 프로젝트 구조를 이해하는데에 문제는 없지만, 나중에 큰 규모의 프로젝트를 진행하게 되면 어떤 타입이, 어떤 파일에 있는지 알기 어려울 것 같아요.

두 타입이 서로가 서로를 가지는 등 연관되어있는 경우가 아니라면 각각의 파일로 나눠주는 게 좋을 것 같아요 🙂

2022-04-12 15:47 UTC, TTOzzi commented on Expo1900/Expo1900/Model.swift
> +struct Item: Codable {
PR 내용에서 `Codable` 이 "`Encodable`과 `Decodable`의 `typealias`" 라고 하셨는데요.
두 프로토콜의 기능을 모두 사용하고 있나요? 👀

2022-04-12 15:47 UTC, TTOzzi commented on Expo1900/Expo1900Tests/ModelTest.swift
> +    }
현재는 성공하는 경우에 대한 테스트만 작성되어있는데요.
단위 테스트에선 실패하는 경우에 대한 테스트도 작성되어야 합니다.
구현하신 로직은 언제든 실패할 수 있고, 실패했을 때에 대한 처리도 이루어져야 하니까요 🤔

엉뚱한 asset을 전달했는데 `Exposition` 타입이 정상적으로 디코드되어 나온다던지, 현재 프로젝트에 없는 asset 이름을 전달했는데 어떤 타입을 반환한다던지 하면 안되겠죠?
asset 이름이 잘못되었을 때 의도한대로 실패하는지, 전달한 json asset과 맞지 않는 타입으로 디코드를 시도했을 때도 실패하는지 테스트 코드를 작성해주면 더 좋을 것 같아요!

2022-04-12 15:47 UTC, TTOzzi commented on Expo1900/Expo1900Tests/ModelTest.swift
> +    func test_Item_decode호출시_올바른값을가져오는지() {
테스트의 목적이 프로젝트 내의 `items` JSON 파일이 의도한대로 작성된 파일인지 확인하는 것인지, 구현하신 `decode` 메서드가 정상적으로 동작하는지 확인을 위한 것인지에 따라 다르겠지만..
테스트의 목적이 후자라면 "asset을 찾아서, 정해진 타입으로 디코드 하는가" 에 대한 테스트는 이미 위 케이스에서 이루어져서 요 테스트는 없어도 될 것 같네요 🤔

2022-04-13 13:33 UTC, cherrishRed commented on Expo1900/Expo1900/Extension/extension+Decodable.swift
> +import UIKit
UIKit은 `user interface` 포함한` app` 개발할 때 사용하고
Foundation은 `Strings, Dates`를 사용해야 할 때, `NSObject`의 클래스 계층구조가 필요할 때 사용합니다.
그런데 기본적으로 `UIKit` 을 `import`하면 `Foundation`도 자동으로 `import`가 되기 때문에 `Foundation`을 따로 `import`해줄 필요가 없으며 모델에서도 `Foundation` 이 사용 되지 않는 것을 확인해 제거해 주었습니다. 
(참고 문서: https://daheenallwhite.github.io/ios/2019/07/17/UIKit-Foundation-SwiftStandardLibrary/)

2022-04-13 15:34 UTC, cherrishRed commented on Expo1900/Expo1900/Model.swift
> +//  Model.swift
네 모델 폴더를 만들고 두 타입을  각각 나눠주었습니다!

2022-04-13 15:35 UTC, doogie97 commented on Expo1900/Expo1900/Extension/extension+Decodable.swift
> +    }
말씀하신 내용을 반영해 에러타입을 만들었으며 Result타입으로 반환 할 수 있게 구현하였습니다.
아울러, 이 과정에서 궁금한게 Error를 담고있는 파일의 위치는 어디에다가 위치시켜야 하는지 궁금합니다!

2022-04-13 15:36 UTC, doogie97 commented on Expo1900/Expo1900Tests/ModelTest.swift
> +    func test_Item_decode호출시_올바른값을가져오는지() {
JSON을 처음 다뤄보다 보니 배열은 어떻게 읽어오는지 궁금해서 추가 작성하게 되었습니다. 
그치만 테스트의 목적은 후자가 맞기에 하나만 있어도 충분할 것 같아 지워주었습니다

2022-04-13 15:36 UTC, cherrishRed commented on Expo1900/Expo1900/Model.swift
> +struct Item: Codable {
저희가 생각해 보니 Codable 의 기능 중에서 Decodable 만 사용하고 있네요! Decodable 로 채택해 주었습니다!

2022-04-13 15:41 UTC, doogie97 commented on Expo1900/Expo1900Tests/ModelTest.swift
> +    }
말씀하신대로 테스트 코드를 작성해 두가지 에러에 대한 결과를 확인 할 수 있게 구현해 보았습니다.

2022-04-13 15:48 UTC, cherrishRed commented
@TTOzzi  리펙토링 완료 했습니다! 😁

## 변경한 내용 
* 사용하지 않는 import 제거
* Model 파일 분리및 채택 프로토콜 변경
* Error 타입 생성 
* decode 의 return 타입 Result 타입으로 변경.
* test 코드가 에러도 테스트 할 수 있도록 수정

## 추가적으로 궁금한 점
**Error 파일의 위치**
말씀하신 내용을 반영해 에러타입을 만들었으며 Result타입으로 반환 할 수 있게 구현하였습니다.
아울러, 이 과정에서 궁금한게 Error를 담고있는 파일의 위치는 어디에다가 위치시켜야 하는지 궁금합니다!

**테스트 코드 안의 struct**
decode과정에서 오류가 발생하는 경우는 data를 받으려는 타입이 잘못되었을 경우에 일어난다고 생각해 test코드 안에 struct를 생성했는데 이렇게 생성해도 괜찮은지, 아니라면 어디에 코드를 작성해야하는지 궁금합니다

2022-04-13 15:56 UTC, TTOzzi commented on Expo1900/Expo1900/Extension/extension+Decodable.swift
> +    }
음 저는 `Error`를 던지는 곳이 한 곳이라면 그곳에, 여러 곳에서 던진다면 별도의 파일로 분리하는 편이에요.
요런 건 정하기 나름이라 두기, 레드가 컨벤션을 정하고 그대로 구현하시면 될 것 같습니다!

2022-04-13 16:01 UTC, TTOzzi commented on Expo1900/Expo1900/Error.swift
> +//  Error.swift
`Error` 파일명도 이전의 `Model`과 같이 너무 제너럴한 것 같아요!
에러 타입이 많아질 것을 대비해 명확하게 바꿔주면 좋을 것 같습니다 🙂

2022-04-13 16:15 UTC, TTOzzi commented on Expo1900/Expo1900/Extension/extension+Decodable.swift
> +            return .failure(.decodeError)
디코드에 실패했을 때, 어떤 이유로 실패했는지에 대한 설명은 (지금은 생략되어있지만) `catch` 블럭의 인자로 들어오는 `error`가 가지고 있어요.
구현하신 커스텀 에러 타입 `DataLoadError`의 `decodeError`가 associated value를 가지도록 해서 디코드 실패 이유를 전달할 수 있으면 더 좋을 것 같아요 🤔

2022-04-13 16:20 UTC, TTOzzi commented on Expo1900/Expo1900/Extension/extension+Decodable.swift
> +    static func decode(with assetName: String) -> Result<Self, DataLoadError> {
이 함수는 비동기 로직이 없기에 `throws`로 처리할 수도 있을 것 같네요.
`Result`로 처리하는게 잘못됐다는 건 아니고, 에러를 처리하는 방식인 `throws`와 `Result`가 어떤 차이가 있는지 정도만 알아보심 좋을 것 같아요.

2022-04-13 16:23 UTC, TTOzzi commented on Expo1900/Expo1900Tests/ModelTest.swift
> +            }
들여쓰기가 조금 어색한 것 같아요..!
추가로 switch 로 분기하는 것과 큰 차이는 없지만.. `Result` 타입에서 성공했을 때의 값만 필요하다면, `Result` 타입의 `get` 메서드도 활용해볼 수 있습니다.

2022-04-13 16:25 UTC, cherrishRed commented on Expo1900/Expo1900/Extension/extension+Decodable.swift
> +            return .failure(.decodeError)
여기서 이야기 하시는 실패 이유라고 하심은 어떤 CodingKey 가 잘못됐는지를 뜻하시는 건가요? 🤔

2022-04-13 16:26 UTC, TTOzzi commented on Expo1900/Expo1900Tests/ModelTest.swift
> +        XCTAssertEqual(title, "파리 만국박람회 1900(L'Exposition de Paris 1900)")
요렇게 옵셔널 변수를 선언한 후, 값을 할당하고 뒤에서 유효성 검사를 해줄 수도 있지만, switch-case 내부에서 성공 케이스엔 `XCTAssertEqual`로 정상적인 값인지 체크를 하고 도달하면 안되는 케이스인 `.failure`에는 `XCTFail`로 실패하도록 작성해줄 수도 있어요!

2022-04-13 16:29 UTC, TTOzzi commented on Expo1900/Expo1900Tests/ModelTest.swift
> +        }
흠 이 테스트 케이스에서만 쓰이니 딱히 상관없을 것 같긴 한데.. 그래도 개인적인 생각으론 밖으로 꺼내거나 분리하는 게 나아보여요 🤔 
추가로 테스트를 위해 생성된 객체의 네이밍은 **Test Double**이란 키워드로 검색해보시고, 의도에 맞게 이름을 부여해주시면 더 좋을 것 같습니다.

2022-04-13 16:29 UTC, doogie97 commented on Expo1900/Expo1900Tests/ModelTest.swift
> +            }
최초에는 또치 말씀대로 get메서드를 이용해 가져오긴 했는데 추후 해당 메서드는 이런 지금 작성한 방식으로 사용할 것 이라고 생각해 테스트 코드도 동일한 방식으로 작성하였습니다!

아울러, 들여쓰기가 어색하다고 말씀하신 부분은
```swift
            default:
                break }
```
이런 식으로 수정하면 괜찮을까요?

2022-04-13 16:31 UTC, TTOzzi commented on Expo1900/Expo1900Tests/ModelTest.swift
> +    func test_Exposition_decode호출시_파일명이잘못되었을때_적절한에러를던지는지() {
테스트 케이스의 이름도 "적절한 에러를 던지는지" 보단 "`assetLoadError`를 던지는지" 와 같이 좀 더 명확하게 작성해주시면 더 좋을 것 같습니다.
테스트 케이스가 많아지면 Xcode의 navigator를 통해 테스트 케이스 이름만 띄워진 목록을 볼 텐데, 지금 이름으론 테스트 케이스의 구현부를 보지 않고는 파일명이 잘못됐을 때 어떤 에러를 던지지 못해 실패한건지 알 수 없을 것 같아요 🤔

2022-04-13 16:34 UTC, TTOzzi approved these changes
고생하셨습니다!
추가적으로 궁금한 점 질문주신 건 코멘트로 답변됐을거라 생각하는데, 혹시나 제가 놓친 부분이 있다면 말씀해주세요 🙏 
추가로 남긴 코멘트는 마이너한 수정사항들이고 반영 여부는 두기, 레드가 판단하시고 다음 스텝 진행해주시면 될 것 같습니다!!

2022-04-13 16:37 UTC, TTOzzi commented on Expo1900/Expo1900/Extension/extension+Decodable.swift
> +            return .failure(.decodeError)
음! 말씀하신 것 처럼 `json`의 키와 `CodingKey`가 일치하지 않아서일 수도 있고, 값의 타입이 달라서일 수도 있고 여러가지 이유가 있을 것 같아요 🤔 
에러가 발생했을 때 `decoder`가 던져주는 에러가 어떤 정보를 가지고 있는지는 작성하신 `return` 앞에다가 브레이크 포인트를 걸어서 `error`를 찍어보시면 보실 수 있어요!

2022-04-13 16:38 UTC, TTOzzi commented on Expo1900/Expo1900Tests/ModelTest.swift
> +            }
엇 아뇨아뇨!
```suggestion
        switch result {
        case .success(let data):
            title = data.title
        default: break
        }
```
요렇게 바로 윗 라인에 선언된 `var title: String?`와 들여쓰기가 맞춰져야하는 것 아닌가..? 하는 생각이었어요!

2022-04-13 16:40 UTC, merged

2022-04-14 04:08 UTC, doogie97 commented on Expo1900/Expo1900/Error.swift
> +//  Error.swift
에러 폴더를 만들어 말씀하신 대로 현재 필요한 상황의 에러로 파일명을 변경하였습니다!

2022-04-14 04:09 UTC, doogie97 commented on Expo1900/Expo1900/Extension/extension+Decodable.swift
> +            return .failure(.decodeError)
최초에는 발생되는 DecodingError를 XCTAssertEqual을 통해 비교하려 했으나 DecodingError는 Equatable을 채택하고 있지 않아 비교가 불가해 
```swift
        do {
            try DummyWrongPropertyName.decode(with: "exposition_universelle_1900")
        } catch DecodingError.keyNotFound(let key, let value) {
            print("\n key: \(key) \n value: \(value) \n")
        } catch {
            XCTFail()
        }
```
위와같이 원하는 에러가 발생된 경우 해당 내용을 프린트 해 통과하게 만들었고 원하는 에러가 발생되지 않는 경우에는 실패하도록 테스트 코드를 작성했습니다

2022-04-14 04:10 UTC, doogie97 commented on Expo1900/Expo1900/Extension/extension+Decodable.swift
> +    static func decode(with assetName: String) -> Result<Self, DataLoadError> {
또치 말씀 듣고 레드와 함께 고민해 본 결과 throws로 변경하기로 했습니다!

2022-04-14 04:11 UTC, doogie97 commented on Expo1900/Expo1900Tests/ModelTest.swift
> +            }
해당 부분은 테스트 케이스를 수정하면서 삭제되었습니다