만국 박람회 [Step1]  우롱차, marisol
yagom-academy/ios-exposition-universelle pull request #141
Opened 2022-04-12 05:48 UTC by dnwhd0112

@lina0322 
안녕하세요 엘림 이번 Pr도 잘 부탁드려요

고민한 점

1. JsonManager를 이용해서 객체를 가져오는것과 각 객체에서 static 메소드를 통하여 json 디코딩을 하여 해당 객체를 가져오는 방법중에 어느 방법이 더 나은것일지 고민했습니다. (JsonManger를 사용하는 방식을 채택했습니다.)

2.접근 수준이 private인 구조체에 대한 test 실행
Item과 ExpositionInfo 구조체의 프로퍼티 모두 현재로서는 외부에서 접근할 필요가 없다고 생각해서 접근수준을 private으로 설정했습니다.

그런데 접근 수준이 private일 경우, test시 직접 접근할 수가 없었습니다. 그래서 private인 대상을 직접 호출하여 테스트 하는 것이 아니라, XCTAssertNotNil을 이용해서 리턴값이 nil이 아닌지를 테스트했습니다.

2022-04-13 02:23 UTC, lina0322 requested changes
안녕하세요, 우롱차, marisol!
이렇게 만나뵙게 되어서 반갑습니다🙇🏻‍♀️
이 프로젝트도 힘내서 함께 공부해보아요~~

이번 스텝에서 겪었던 문제는 많이 없었나요?
다소 고민한 점이나 생각한 부분이 적어보이는데요👀
간단한 트러블이어도 정리해놓고 나면 나중에 필요할지도(???)

또 두 분의 커밋 컨벤션이 아직 적응이 안되신 것 같네요ㅎㅎ 
대문자와 소문자, 그리고 괄호가 숑숑
다음 커밋부터는 조금 더 신경써보죠!🤗

---
> JsonManager를 이용해서 객체를 가져오는것과 각 객체에서 static 메소드를 통하여 json 디코딩을 하여 해당 객체를 가져오는 방법중에 어느 방법이 더 나은것일지 고민했습니다. (JsonManger를 사용하는 방식을 채택했습니다.)

ㅎㅎ 저 이게 무슨말인지 이해가 안 가서요! 각 객체에서 static 메소드를 확용한다는게 어떤것을 의미하신 걸까요?

---

코멘트로 리뷰 남겨두었으니 확인 부탁드려요🙏

2022-04-13 02:23 UTC, lina0322 commented on Expo1900/ExpositionInfo.swift
> +    private let description: String
private로 하면... 나중에 활용이 가능한가요?🤔 
다소 걱정이 되는데🥲 
어떻게 되는지 경험하기 위해, 이렇게 한 번 다음 스텝을 해볼까요...??

2022-04-13 02:23 UTC, lina0322 commented on Expo1900/Item.swift
> +struct Item: Codable {
Codable은 어떤 프로토콜인가요??

2022-04-13 02:23 UTC, lina0322 commented on Expo1900/Item.swift
> +    private enum CodingKeys: String, CodingKey {
CodingKeys는 꼭 필요하나요?👀

2022-04-13 02:23 UTC, lina0322 commented on Expo1900/JsonManager.swift
> +import UIKit
Foundation을 추가한 이유는 무엇일까요?
마찬가지로 UIKit을 추가한 이유는 무엇일까요💁🏻‍♀️

2022-04-13 02:23 UTC, lina0322 commented on Expo1900/JsonManager.swift
> +    func getDecodedExpositionInfo() -> ExpositionInfo?
꼭 get으로 시작했어야 했나요..?🤔 
다른 좋은 이름은 없었을까요?!

2022-04-13 02:23 UTC, lina0322 commented on Expo1900/JsonManager.swift
> +struct JsonManager: JsonManagerable {
JsonManagerable 프로토콜을 생성한 이유와 채택한 이유가 궁금합니다~!🙂

2022-04-13 02:23 UTC, lina0322 commented on Expo1900/JsonManager.swift
> +        var items: [Item]? = []
optional이 아니라, 빈 배열로 보낼 수도 있었을 텐데요! 어떤 기준으로 하셨나요?😀

2022-04-13 02:23 UTC, lina0322 commented on Expo1900/JsonManager.swift
> +        let jsonDecoder = JSONDecoder()
파싱을 할때마다 JSONDecoder객체가 생성되어도 문제는 없을까요?🙏

2022-04-13 02:23 UTC, lina0322 commented on Expo1900/JsonManager.swift
> +        guard let itemData: NSDataAsset = NSDataAsset(name: "items") else { return nil }
items 파일 이름이 변경되거나 오타가나면 어떡하죠..?🥺

2022-04-13 02:23 UTC, lina0322 commented on Expo1900/JsonManager.swift
> +        guard let itemData: NSDataAsset = NSDataAsset(name: "items") else { return nil }
`return`을 되도록 줄바꿈 해주시는게 좋아요.
디버깅 할 때, 브레이크 포인트 걸려면 화가나거든요...ㅎ
하지만 개인 취향이 있고, 회사마다 컨벤션이 다르기 때문에 강요하지는 않습니다🙇🏻‍♀️

2022-04-13 02:23 UTC, lina0322 commented on Expo1900/JsonManager.swift
> +        items = try? jsonDecoder.decode([Item].self, from: itemData.data)
혹시 이 try? 때문에 return 값이 nil일까요?
try에서 실패하는 원인을 모르고 지나가도 괜찮을까요ㅎㅎ.. 
이것도 이대로 뒀다가 다음에 디코딩 안 됐을때 당황 한 번 해봐도...ㅎㅎㅎ....

try, try!, try?의 차이점은 무엇인가요?💁🏻‍♀️

2022-04-13 02:23 UTC, lina0322 commented on Expo1900/JsonManager.swift
> +        guard let expositionInfoData: NSDataAsset = NSDataAsset(name: "exposition_universelle_1900") else { return nil }
거 참 오타나기 딱 좋은 스트링이네요😎

근데 왜 expositionInfoData에 NSDataAsset 타입을 명시해주었나요?
jsonDecoder는 타입 명시를 안해주었네욥?👀

2022-04-13 02:23 UTC, lina0322 commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +    }
이 테스트 코드로 확인하고자 하는게 무엇일까요..?!🧐

2022-04-13 04:08 UTC, marisol-develop commented on Expo1900/Item.swift
> +struct Item: Codable {
Codable은 Decodable 프로토콜과 Encodable 프로토콜을 아울러 얘기하는 typealias로 알고 있습니다!
이 경우에는 Decodable을 채택해도 될 것 같지만, Encodable도 가능한 Codable을 우선 채택해두었습니다.

2022-04-13 04:08 UTC, dnwhd0112 commented on Expo1900/ExpositionInfo.swift
> +    private let description: String
저희가 이렇게 한 이유는 캡슐화 측면에서 내부를 숨기는게 좋지 않을까 라고 생각했는대, 리뷰 남겨주신것 처럼 나중에 활용이 힘들겠네요. 언재 internal으로 써야할지 private로 써야할지 기준이 필요한거 같습니다.
-> 외부에서 접근할 필요가 있을때는 Internal 로 선언하는게 맞는거 같습니다. 그러므로 private을 제거하도록 하겠습니다.

2022-04-13 04:10 UTC, marisol-develop commented on Expo1900/Item.swift
> +    private enum CodingKeys: String, CodingKey {
JSON형식의 데이터에서 key를 swift 형식으로 변환하기 위해서 CodingKey를 사용했습니다.
혹시 다른 방법으로도 key를 변환할 수 있나요?!

2022-04-13 04:16 UTC, marisol-develop commented on Expo1900/JsonManager.swift
> +import UIKit
Foundation은 디폴트로 import되어 있었고, NSDataAsset을 사용하기 위해 UIKit을 추가했습니다!
그런데 Foundation이 없어도 빌드가 되는 것을 확인해서 Foundation이 왜 필요하지 않은지는 더 공부해보고 
불필요한게 맞다면 삭제하도록 하겠습니다. 🥲

2022-04-13 04:20 UTC, marisol-develop commented on Expo1900/JsonManager.swift
> +    func getDecodedExpositionInfo() -> ExpositionInfo?
API 네이밍 가이드의 "Begin names of factory methods with “make”, e.g. x.makeIterator()."를 참고해서 아래와 같이 네이밍 수정하겠습니다.

- `makeDecodedItems()`
- `makeDecodedExpositionInfo()`

그런데 get으로 시작하는 네이밍을 피해야 하는 이유는 혹시 어떤걸까요?!🧐

2022-04-13 04:30 UTC, dnwhd0112 commented on Expo1900/JsonManager.swift
> +struct JsonManager: JsonManagerable {
저번 리뷰때 POP를 배워서 이번에 한번 적용시켜 보고 싶었습니다. 개인적으로 이런식으로 프로그래밍 하는것이 좋아보여서요.

2022-04-13 04:31 UTC, lina0322 commented on Expo1900/Item.swift
> +struct Item: Codable {
`채택해도 될 것 같지만, Encodable도 가능한 Codable을 우선 채택해두었습니다.`가 납득이 가지 않네요🧐
사용하지 않을 Encodable을 채택해야할 이유가 있나요??

2022-04-13 04:32 UTC, lina0322 commented on Expo1900/Item.swift
> +    private enum CodingKeys: String, CodingKey {
ㅎㅎ지금은 CodingKey가 필요한 상황이죠! 
가끔 스네이크 -> 캐멀 정도의 변화라면 옵션을 주는 것만으로 처리할 수도 있고, 변경이 필요없다면 당연히 사용하지 않아도 됩니당

2022-04-13 04:33 UTC, lina0322 commented on Expo1900/JsonManager.swift
> +    func getDecodedExpositionInfo() -> ExpositionInfo?
get을 피하라는 내용이 공식문서 어딘가에 있을텐데, 
두 분이 한 번 찾아볼까요?ㅎㅎ 정 못찾겠다면 말씀해주세요.
(참고로 저희 디스코드에서도 종종 get naming 질문과 함께 나오는 문서입니다)

2022-04-13 04:33 UTC, dnwhd0112 commented on Expo1900/JsonManager.swift
> +        var items: [Item]? = []
에러처리를 하는 대신에 nil이 반환되면 오류라고 기준을 잡았습니다.

2022-04-13 04:34 UTC, lina0322 commented on Expo1900/JsonManager.swift
> +struct JsonManager: JsonManagerable {
`개인적으로 이런식으로 프로그래밍 하는것이 좋아보여서요.`
캠프니까 해보고싶은거 해보는 것 좋습니다.👍
그런데 왜 좋아보였나요? 어떤 이유로 사용하게 되었고, 어떤 이득을 보고있습니까? 어떤 미래를 그리고 있나요? POP가 무엇이죠?

2022-04-13 04:36 UTC, marisol-develop commented on Expo1900/JsonManager.swift
> +        let jsonDecoder = JSONDecoder()
메서드 내에서 jsonDecoder 객체가 생성이 되고, 메서드가 끝나면 메모리에서 해제되기 때문에 문제가 없을거라고 생각했습니다.
하지만 공통으로 빼줄 수도 있겠네요! 혹시 파싱할 때마다 jsonDecoder 객체가 생성되면 발생하는 문제가 있을까요?!🙇‍♀️

2022-04-13 04:37 UTC, marisol-develop commented on Expo1900/JsonManager.swift
> +        guard let itemData: NSDataAsset = NSDataAsset(name: "items") else { return nil }
오타 나기 쉬운게 맞는거 같아요ㅠㅠ
enum으로 필요한 리터럴들을 따로 관리하여 사용하도록 하겠습니다!😇

2022-04-13 04:38 UTC, marisol-develop commented on Expo1900/JsonManager.swift
> +        guard let itemData: NSDataAsset = NSDataAsset(name: "items") else { return nil }
디버깅할 때 브레이크 포인트 걸리면 혼동이 있을 수 있겠네요..!
수정하도록 하겠습니다 조언감사합니다!☺️

2022-04-13 04:40 UTC, marisol-develop commented on Expo1900/JsonManager.swift
> +        items = try? jsonDecoder.decode([Item].self, from: itemData.data)
이 부분은 에러처리를 따로 해주도록 하겠습니다!🙂

do-catch 문에서 try한 메서드에서 에러가 발생하면 catch문에서 처리합니다.
try?는 에러 발생시 nil을 반환하고, try!는 에러 발생시 crash가 발생하는 걸로 알고 있습니다.

2022-04-13 04:42 UTC, marisol-develop commented on Expo1900/JsonManager.swift
> +        guard let expositionInfoData: NSDataAsset = NSDataAsset(name: "exposition_universelle_1900") else { return nil }
이 부분은 타입 명시를 통한 타입 추론이 필요하지 않고, 타입이 명확하다는 생각이 들어서,
타입 명시 부분은 삭제하는 걸로 통일하겠습니다!

2022-04-13 04:49 UTC, marisol-develop commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +    }
저희가 처음에 디코딩에 실패하면 nil을 반환하도록 해서, 디코딩이 정상적으로 성공했는지를 확인하려고 테스트 코드를 이렇게 작성했습니다.
특정 값을 비교하는 테스트를 하게 되면, 테스트가 해당 파일에 의존하게 되어서 적절한 테스트가 아니라고 생각했습니다.

```swift
let jsonManager = JsonManater()
let item = jsonManager.getDecodedItems.first.name
XCTAssertEqual("직지심체요절", item)
```

이 경우 파일의 item이 바뀌면 테스트가 실패하게 되므로 적절한 테스트가 아니라고 생각합니다.

2022-04-13 04:51 UTC, marisol-develop commented on Expo1900/Item.swift
> +struct Item: Codable {
혹시 다음 스텝들에서 Encodable을 사용할 경우가 있을 수도 있다고 생각했고,
프로젝트 요구사항의 핵심 경험에 Codable을 채택하라고 되어 있어서 채택하였습니다!

2022-04-13 05:04 UTC, dnwhd0112 commented on Expo1900/JsonManager.swift
> +struct JsonManager: JsonManagerable {
1. 변경에서 조금 더 유리한거 같습니다.
변경: 만약 추후 변경이 필요할때 해당 프로토콜을 채택하는 객체로 갈아끼워주면 기존에 코드에 영향 없이 변경이 가능합니다.
MOCK 테스트가 가능해 집니다.

POP란? -> 프로토콜 지향 프로그래밍 으로써 이걸 써야되는 이유는...
wwdc 2015 보고 답변 해드릴게요... 좀 만 기다려주세요 ㅠ

https://developer.apple.com/videos/play/wwdc2015/408/

2022-04-13 05:12 UTC, marisol-develop commented on Expo1900/JsonManager.swift
> +    func getDecodedExpositionInfo() -> ExpositionInfo?
API Design Guidelines에서는 못찾았네요ㅠㅠ
생각을 해보자면 get, getter 등 과 혼동할 여지가 있어서 그런걸까요?🥲

2022-04-13 05:14 UTC, lina0322 commented on Expo1900/Item.swift
> +struct Item: Codable {
Encodable을 사용하게 될 때 채택하는게 더 올바른 방향이라는 생각이 들어요🙏

Codable이 채택되어있으면, 아 이거는 서버한테 받기도하고 주기도 하는가보다 할텐데, 알고보니 받기만 하는 상황이라면 
기타 수정할때 오히려 혼돈을 줄 수 있거든요.
지금은 프로젝트 규모가 상당히 작고, 여러분들이 당장 작성하고 있어서 기억을 하겠지만
이것보다 10배는 더 큰 프로젝트라 모델이 20개~40개가 넘어가고, 코드를 작성한지 1~2년 지나가면 정말 기억이 추우웅분히 안날 수 있기 때문이죠.

또한, 기획서에서 이런 기능 사용해주세요! 했을때, 어떤 기능인지 정확히 파악이 되었다면 개발자는 스스로 필요 여부를 판단해서 뺄 수도 있어야 한다고 생각해요. 
반드시 쓰세요! 안쓰면 총으로 쏠거에요 이런거 아니멶ㅎㅎㅎㅎ 저와 조율이 가능한 부분이겠죠?^.~

2022-04-13 05:16 UTC, lina0322 commented on Expo1900/JsonManager.swift
> +    func getDecodedExpositionInfo() -> ExpositionInfo?
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html

2022-04-13 05:18 UTC, lina0322 commented on Expo1900/JsonManager.swift
> +        let jsonDecoder = JSONDecoder()
두 분 생각은 어떤가요? 요 부분 두 분의 의견이 궁금하네요!👀

2022-04-13 05:23 UTC, marisol-develop commented on Expo1900/JsonManager.swift
> +    func getDecodedExpositionInfo() -> ExpositionInfo?
The use of "get" is unnecessary, unless one or more values are returned indirectly라는 부분이 있는데요,
하나 이상의 값을 간접적으로 리턴하지 않는한 get을 사용하지 말라는 뜻으로 이해했습니다.
그런데 값을 간접적으로 리턴하는 것이 무엇인지 일단 이해가 잘 가지 않았고,
이 문장 아래 예시를 보면 getCellSize 대신 cellSize라는 네이밍을 사용하라고 되어 있는데
메서드 명이 동사가 아닌 명사로 시작해도 문제가 없는 것인지 궁금합니다!

2022-04-13 05:25 UTC, lina0322 commented on Expo1900/JsonManager.swift
> +    func getDecodedExpositionInfo() -> ExpositionInfo?
자, 우리 이 질문을 디코 질문-답변으로 쓱 가져가볼까요?ㅎㅎ 
너무 부끄럽다면 동기들만 있는 곳도 괜찮아요. 많은 사람들의 의견을 들어보는 것도 좋으니까요👍

2022-04-13 05:30 UTC, marisol-develop commented on Expo1900/JsonManager.swift
> +        let jsonDecoder = JSONDecoder()
파싱할 때마다 매번 jsonDecoder 객체를 생성하고 해제해야 한다면 성능 면에서 좋지 않을 수 있을 거라는 생각은 드는데, 
다른 문제가 발생할 여지가 있을까요?👀

2022-04-13 06:33 UTC, dnwhd0112 commented
JsonManager를 이용해서 객체를 가져오는것과 각 객체에서 static 메소드를 통하여 json 디코딩을 하여 해당 객체를 가져오는 방법중에 어느 방법이 더 나은것일지 고민했습니다. (JsonManger를 사용하는 방식을 채택했습니다.)

방법 1. JsonManger를 사용해서 Decoding을 하고 각 객체를 반환하는 방법
방법 2. Item, ExpositionInfo struct 에서 각자 static 메소드를 사용하여 각자 decoding을 하여 반환해주는 방법
을 생각하였는대 decoding 하는 역할이 따로 필요할꺼 같아서 JsonManger를 구현하여 작동하도록 하였습니다.

2022-04-13 06:42 UTC, marisol-develop commented
안녕하세요 엘림! 
저희가 프로젝트 시작이다보니 커밋 컨벤션 등을 조율하는게 시간이 걸렸습니다ㅜㅜ 🥲
앞으로 커밋이나 코딩 컨벤션에 더 신경 쓰도록 하겠습니다!

---

## 고민한 점

1. 에러처리의 유닛테스트 방법

ExpoError에 정의한 noFileError과 decodingError를 테스트하기 위한 방법을 고민했습니다.
의도적으로 error를 발생시키기 위해 `MockJsonManager`라는 구조체를 만들었고, 
NSDataAsset의 name을 잘못 설정하여 `noFileError`를 발생시키고, 파일명과 실제 디코딩할 파일을 다르게 설정하여 `decodingError`를 발생시켰습니다.

그런데 MockJsonManager 파일을 Expo1900Tests 내부에 위치시키고 싶었는데 Expo1900에 데이터들을 불러오지 못해서, `@testable import Expo1900`하여 문제를 해결했습니다.

2. 에러처리 방법

처음에 JsonManager 내부에서 오류 발생시 return nil하는 방식으로 구현을 했는데, 말씀하신대로 어떤 오류가 발생했는지 모르고 지나갈 수 있어서 다시 오류 처리를 해주었습니다. guard 문을 통과하지 못하면 error를 throw하도록 했고, 해당 메서드를 사용하는 곳에서 catch해서 에러처리하도록 구현했습니다.

2022-04-13 14:29 UTC, dnwhd0112 commented on Expo1900/JsonManager.swift
> +struct JsonManager: JsonManagerable {
WWDC와 야곰 영상을 보고왔는대요! 생각해보니 이 코드에서는 굳이 POP 를 사용할 필요는 없을꺼 같아요. POP를 설명하는 영상들을 보니 대부분 재사용성을 강조하는것 같아요. (서로 다른 객체에서 같은 부분을 프로토콜로 구현하여 사용)

2022-04-14 08:57 UTC, lina0322 commented on Expo1900/JsonManager.swift
> +        let jsonDecoder = JSONDecoder()
매번 객체를 생성하고 해제하면 성능에 안좋나욥? 해제하면 괜찮을 것 같기도 한데요~?😆 어떻게 생각하세용

2022-04-14 09:02 UTC, lina0322 approved these changes
새 코멘트는 다음 스텝에서 함께 또 얘기해보죠😎
한 스텝을 진행했을 뿐인데 두 분이 많이 발전한 것 같은 느낌적인 느낌이에요👏
이번 스텝 고생하셨습니다~ step2에서 만나요🤗

2022-04-14 09:02 UTC, lina0322 commented on Expo1900/DataFileName.swift
> +}
LGTM💕

2022-04-14 09:02 UTC, lina0322 commented on Expo1900/ExpoError.swift
> +}
LGTM2💕

2022-04-14 09:02 UTC, lina0322 commented on Expo1900/Expo1900Tests/MockJsonManager.swift
> +struct MockJsonManager: JsonManagerable {
MockJsonManager로 테스트하고자 하는 대상은 어떤걸까요??

2022-04-14 09:02 UTC, merged

2022-04-14 09:32 UTC, dnwhd0112 commented on Expo1900/Expo1900Tests/MockJsonManager.swift
> +struct MockJsonManager: JsonManagerable {
에러가 정상적으로 반환되는지 체크해보기 위한 가짜 객체입니다!

2022-04-24 14:16 UTC, dnwhd0112 commented on Expo1900/JsonManager.swift
> +struct JsonManager: JsonManagerable {
조금 더 공부해보니 제가 POP를 채택한게 아니라 디자인 패턴을 채택한거 같네요. 디자인 패턴은 공부중입니다.

2022-04-24 14:17 UTC, dnwhd0112 commented on Expo1900/JsonManager.swift
> +        let jsonDecoder = JSONDecoder()
객체를 생성하는대 비용이 많이들긴 하죠! 지금 생각해보니 객체의 프로퍼티로 가져가는게 맞는거 같네요.