만국 박람회 [STEP 2] Lingo, 마이노
yagom-academy/ios-exposition-universelle pull request #146
Opened 2022-04-14 07:12 UTC by llingo

@wonhee009 
안녕하세요 라자냐 👍
만국 박람회 [STEP 2] PR 보냅니다. 잘 부탁드립니다!

### 고민 및 해결한 점
- 요구사항에 오토레이아웃은 STEP 3부터 적용한다고 되어있었지만 보기에 불편하지 않게끔만 적용했습니다. 
- Decodable Extension으로 JSON 디코딩 기능을 분리하여 재사용할 수 있도록 했습니다.
- Asset을 가져오는 과정에서의 에러와 Decode 에러 처리를 분리하였습니다.
- 디코딩의 결과를 Result 타입을 통해 반환하여 ViewController에서 `success`, `failure` 케이스에 따라 사용할 수 있도록 했습니다.
- 테이블 뷰를 ViewController에 Delegate, Datasource로 생성하는 방법도 있지만 이번 프로젝트에서는 UITableViewController를 사용해봤습니다.
- Alert을 효율적으로 재사용하기 위해 Builder 패턴을 적용하여 AlertBuilder로 생성할 수 있도록 했습니다.
- 매직리터널을 제거하기 위해 상수로 분리했습니다.
- MainViewController의 크기가 다른 Label을 하나의 Label로 할지 Label를 분리할 지 고민하였고 
STEP 3에서 `AttributedText`를 사용해서 각 문자의 크기를 변경해보기로 했습니다.
- ViewController과 TableViewCell의 identifier를 사용하는 코드의 중복을 막기 위해 Extension으로 아래와 같이 분리했습니다.
```swift
extension UIViewController: UIViewControllerable {
  static var identifier: String {
    return String(describing: self)
  }
}

extension UITableViewCell {
  static var identifier: String {
    return String(describing: self)
  }
}
```

### 조언 받고 싶은 점
MainViewController의 네비게이션바를 MainViewController의 라이프사이클에서 hidden 처리를 했는데 더 좋은 방법이 있을 지 궁금합니다.
```swift
override func viewWillAppear(_ animated: Bool) {
  self.navigationController?.isNavigationBarHidden = true
}

override func viewWillDisappear(_ animated: Bool) {
  super.viewWillDisappear(animated)
  self.navigationController?.isNavigationBarHidden = false
}
```

2022-04-15 12:32 UTC, wonhee009 requested changes
step2 수고하셨습니다 🎉 
몇몇 코멘트 남겨두었으니 확인 부탁드립니다 🙏 

#### 조언 받고 싶은 점
MainViewController의 본인의 navigationBar의 역할을(hidden/not hidden) 갖도록 잘 처리해주신거 같습니다. 👍 


<img width="60%" alt="image" src="https://user-images.githubusercontent.com/30456206/163567049-645b94d8-3cb5-4035-8d03-2e45ab76fe81.png">
네비게이션 하단 왼쪽의 선이 잘리는거 같은데 확인 부탁드립니다 🙏

2022-04-15 12:32 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +final class ExpoItemDetailViewController: UIViewController {
`final`을 선언하셨군요 👍

2022-04-15 12:32 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +  var expoItem: ExpoItem?
`expoItem`은 ExpoItemDetailViewController에서만 사용되어지는데 private으로 숨기고 `func setupExpoItem(_ item: ExpoItem)`과 같은 인터페이스를 추가하는건 어떤가요?

2022-04-15 12:32 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +}
`extension`으로 분리한 기준이 있을까요?.?

2022-04-15 12:32 UTC, wonhee009 commented on Expo1900/Expo1900/Util/Error/DecodeError.swift
> +    }
[LocalizedError](https://developer.apple.com/documentation/foundation/localizederror)를 활용해볼 수도 있을거 같아요 😄

2022-04-15 12:32 UTC, wonhee009 commented on Expo1900/Expo1900/Util/Extension/Decodable+Extension.swift
> +  }
`Decodable`의 extension으로 `decode`를 구현하셨군요 👍 
여기에 구현한 이유가 있을까요?
메서드의 내용을 보면 json으로 디코딩을 해주는데 메서드의 이름은 `decode`라서 그 내용을 다 담기 어려운거 같습니다. 네이밍 한 번 확인 부탁드립니다 🙏

2022-04-15 12:32 UTC, wonhee009 commented on Expo1900/Expo1900/Util/Extension/UIViewController+Extension.swift
> +}
모든 VC가 alert을 만드는 책임을 갖는게 맞을까요?.?

2022-04-15 12:32 UTC, wonhee009 commented on Expo1900/Expo1900/Util/Const.swift
> +}
`Const`는 상수의 의미로 사용하신거 같은데요.
약어는 지양해주세요 😄 
또한, "확인"이라는 텍스트가 alert을 생성할때 사용되어야 해서 어디서든 사용할 수 있도록 따로 정의하신거 같습니다.
현재 명세상으로는 모든 alert에 확인이 들어가지만 이후 스펙이 수정 혹은 추가되면서 어떤 view에서는 '확인 -> ok'로 수정될 경우에는 더이상 confirm이 글로벌하게 있을 필요가 없을거 같은데요.
이런 상수들은 각 view에서 따로 관리하는건 어떨까요?

2022-04-15 12:32 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +  static let spacingBracket = "\n("
```swift
static let visitorText: String = "방문객 : %@ 명"

String(format: visitorText, 10)
```
format을 이용할 수 있을거 같습니다 😄

2022-04-15 12:32 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +  }
`super.viewWillAppear(animated)`가 없는 이유가 있을까요?

2022-04-15 12:32 UTC, wonhee009 commented on Expo1900/Expo1900/Util/AlertBuilder/AlertBuilder.swift
> +  }
사용되는 곳이 있는 메서드일까요?.?

2022-04-15 12:32 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/ExpoItemTableViewController.swift
> +    cell.expoItemImageView.image = UIImage(named: self.expoItems[indexPath.row].imageName)
tableView에서 cell의 view를 설정해주고 있는데요.
cell의 view를 설정하는 역할은 cell의 역할이 아닐까요?

2022-04-18 02:00 UTC, Mino777 commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +  var expoItem: ExpoItem?
라자냐가 추천해주신대로, 메서드로 ExpoItem을 주입해주는 방식으로 변경했습니다!
감사합니다!
```swift
extension ExpoItemDetailViewController {
  
  func setUpExpoItem(_ expoItem: ExpoItem) {
    self.expoItem = expoItem
  }
}
```

2022-04-18 02:00 UTC, llingo commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +  var expoItem: ExpoItem?
메서드로 주입하는 방법도 있었지만 생성자 주입하는 방법도 있었습니다. 
하지만, `instantiateViewController`의 creator로 주입해주는 것이 좋은 방법인지는 모르겠습니다 🥲
```swift
guard let detailViewController = self.storyboard?.instantiateViewController(
  identifier: ExpoItemDetailViewController.identifier,
  creator: { coder in
    return ExpoItemDetailViewController(coder: coder, expoItem: self.expoItems[indexPath.row])
  })
else {
  return
}
```

2022-04-18 02:10 UTC, llingo commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +}
처음에는 `private` 메서드를 한 곳에 모아두는 것이 좋다고 생각하고 분리를 했었지만 기능을 흐름을 읽기가 어렵고 각각 메서드의 접근제어를 변경할 수 없는 단점이 있는 것 같습니다.

Flow들을 묶어서 분리하는 방향으로 변경했습니다 👍

2022-04-18 02:28 UTC, Mino777 commented on Expo1900/Expo1900/Util/Error/DecodeError.swift
> +    }
저희도 LocalizedError를 사용하려고 했으나, var errorDescription: String? 해당 프로퍼티가 옵셔널인 부분 때문에 바인딩 하는 과정을 없애고 싶어서 직접 description을 구현하여 사용하였습니다. 

그런데 확인해보니, 해당 errorDescription을 사용할 때 localizedDescription을 사용하면 옵셔널 바인딩이 필요없이 String값을 뽑아낼 수 있어서 LocalizedError를 채택하였습니다!

저희가 많은 경험이 없다보니, LocalizedError를 사용할 경우에 얻을 수 있는 이점이 어떤 것인지 아직 체감을 하지못하는 것 같습니다. 혹시 어떤 이점이 더 있을까요? 궁금합니다!

2022-04-18 02:41 UTC, llingo commented on Expo1900/Expo1900/Util/Extension/Decodable+Extension.swift
> +  }
> 여기에 구현한 이유가 있을까요?

Decodable 프로토콜을 채택한 모델을 JSONDecoder로 decode 해주는 작업이며 여러 ViewController에서 사용하기 때문에 재사용성을 위해 Decodable 프로토콜에 구현했습니다.

---

> 메서드의 내용을 보면 json으로 디코딩을 해주는데 메서드의 이름은 decode라서 그 내용을 다 담기 어려운거 같습니다. 네이밍 한 번 확인 부탁드립니다

말씀하신 것처럼 decode라는 이름이 `에셋에서 가져온 JSON 파일 데이터를 모델 타입으로 decode한다` 라는 이름을 모두 담지 못하는 것 같습니다. 따라서, `parseJSON` 으로 네이밍을 변경했습니다.

2022-04-18 02:58 UTC, Mino777 commented on Expo1900/Expo1900/Util/Extension/UIViewController+Extension.swift
> +}
UIViewControllerable 프로토콜을 AlertPresentable로 변경하고 알럿을 사용하는 VC에서만 해당 프로토콜을 채택하여 사용하도록 수정하였습니다!

```swift
lazy var alertBuilder: AlertBuilderable = AlertBuilder(viewController: self)
```

라자냐가 말씀해주신 부분이 이런식으로 수정한 방향이 맞을까요?

2022-04-18 03:10 UTC, llingo commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +  }
구현하던 중에 누락된 것 같습니다 🙇🏻 
수정했습니다!

2022-04-18 03:11 UTC, llingo commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +  static let spacingBracket = "\n("
`String(format: Constants.visitor, expo.visitors.toDecimal())`를 사용하여 format 해주도록 변경했습니다! 😃

2022-04-18 03:12 UTC, llingo commented on Expo1900/Expo1900/Util/Const.swift
> +}
`Constants`로 줄임표현을 수정했습니다! **약어 지양!**
글로벌하게 있던 confirm을 각 ViewController로 분리했습니다.

2022-04-18 03:18 UTC, Mino777 commented on Expo1900/Expo1900/Controller/ExpoItemTableViewController.swift
> +    cell.expoItemImageView.image = UIImage(named: self.expoItems[indexPath.row].imageName)
View를 설정하는 역할을 ExpoItemTableViewCell에 func setUpContentView(_ expoItem: ExpoItem)메서드를 통해 넘겨주었습니다.
감사합니다!

2022-04-18 03:27 UTC, llingo commented
> 네비게이션 하단 왼쪽의 선이 잘리는거 같은데 확인 부탁드립니다 🙏

iOS 15 버전부터 네비게이션 바의 backgroundColor가 투명하도록 변경되어 보이는 선은 tableView의 Separator가 표시된 것 같습니다. iOS 14 버전에서는 선이 보이지 않는 것을 확인할 수 있었습니다.

### iOS 15.4
![스크린샷 2022-04-18 오후 12 24 03](https://user-images.githubusercontent.com/94151993/163749824-87efbd6d-9d53-4b91-9f84-66fb3b92e426.png)



### iOS 14.1
![스크린샷 2022-04-18 오후 12 24 07](https://user-images.githubusercontent.com/94151993/163749830-002444a1-0844-4b47-9ba2-db342d554998.png)

2022-04-18 03:35 UTC, llingo commented on Expo1900/Expo1900/Util/AlertBuilder/AlertBuilder.swift
> +  }
현재 프로젝트에서는 사용되는 곳이 없는 것 같습니다. 말씀해주신 것처럼 사용하지 않는 메서드는 삭제했습니다!

하지만, AlertBuilder는 AlertController로 구현하던 기능의 재사용성을 위해 구현한 클래스인데 일부 기능을 빼면 재사용성이 약화하지 않을까 생각됩니다. 이 부분에 대해 라자냐는 어떻게 생각하실까요? 사용할때 기능을 추가하는 것이 좋을까요? 🙇🏻

2022-04-18 04:42 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +  var expoItem: ExpoItem?
@llingo 어떤 코드가 더 읽기 쉽고, 어떤 코드가 한번에 이해되는지 생각해보면 좋을거 같습니다!

2022-04-18 04:53 UTC, wonhee009 commented on Expo1900/Expo1900/Util/Error/DecodeError.swift
> +    }
기왕이면 애플이 만들어줬으니 두번 작업할 필요 없이 쓰자는 생각괔ㅋㅋ
현재는 description에만 사용하지만 LocalizedError에 정의된 다른 기능들을 사용하게 된다면 좀 더 좋은 에러를 표현할 수 있지 않을까요?
현재는 그럴만한 기능이 없어서 체감을 못하는건 당연하거 같습니다!

2022-04-18 05:31 UTC, wonhee009 commented on Expo1900/Expo1900/Util/AlertBuilder/AlertBuilder.swift
> +  }
음... 사용하지 않는 메서드를 삭제하는데 재사용성이 약화된다는게 이해가 가지 않는데요.
어떤 부분에서 그렇게 생각하셨는지 알 수 있을까요?

2022-04-18 06:22 UTC, wonhee009 commented on Expo1900/Expo1900/Util/Extension/UIViewController+Extension.swift
> +}
이후에 confirm, cancel 버튼이 있는 alert이 필요할 경우 AlertBuilderable에 cancel을 추가하는 메서드가 추가될거 같은데요.
그렇다면 해당 프로토콜을 채택하는 vc들은 confirm alert, cancel alert, confirm + cancel alert을 모두 만들 수 있는 역할을 갖게 되지 않을까요?
어떤 의미로는 개발자에게 혼동을 줄 수 있지 않을까요? cancel 버튼만 있는 alert을 만들고 싶은데 alertBuilder를 정의해야하고, 그 안에서 cancel뿐 아니라 confirm을 만들 수 있는 책임을 vc가 가지고 있으니까요.

private으로 감춰줘야할 필요가 있는데 private으로 감추지 못한다면 구조에 오류가 있지 않나 생각해봐야 한다고 생각합니다:)

2022-04-18 08:34 UTC, llingo commented on Expo1900/Expo1900/Controller/ExpoItemDetailViewController.swift
> +  var expoItem: ExpoItem?
메서드 주입하는 방식이 creator로 주입하는 방식보다 더 깔끔한 것 같습니다!

2022-04-18 08:48 UTC, Mino777 commented on Expo1900/Expo1900/Util/Extension/UIViewController+Extension.swift
> +}
라자냐 말씀이 맞는 것 같습니다! 저희가 이해 하기로는, 현재 AlertBuilder로 사용하는것이 아닌, 개발자가 필요할때 딱 필요한 AlertController를 해당 VC에서 만들어서 사용하는것이 VC가 알맞는 책임을 가지는 것이고, 혼동을 줄일 수 있다 라고 이해를 하였는데 맞을까요?! 그런식으로 진행하면 private과 관련된 문제점도 없어질 것 같습니다!

해당 부분은 라자냐가 컨펌 해주시면 해당 내용으로 수정하도록 하겠습니다!
감사합니다!!

2022-04-18 08:53 UTC, llingo commented on Expo1900/Expo1900/Util/AlertBuilder/AlertBuilder.swift
> +  }
"재사용성보다는 범용성이 약화된다"가 더 전달하고 싶었던 의미였던 것 같습니다. 위에서 해주신 코멘트에 대해 생각을 해보니
확실히 범용성만을 위해 지금 필요하지 않은 기능까지 구현헀을 때 개발자에게 혼동을 줄 수 있을 것 같습니다.

2022-04-18 10:22 UTC, wonhee009 commented on Expo1900/Expo1900/Util/Extension/UIViewController+Extension.swift
> +}
@llingo @Mino777 
해당 VC에서 alert를 만드는 방식도 좋고, AlertViewController를 만들어 alert 생성 책임을 맡기는 것도 좋을거 같습니다:)
책임만 잘 나누면 되는 문제니까요.
해당 부분은 다음 스텝에서 같이 반영해주세요

2022-04-18 10:22 UTC, wonhee009 approved these changes

2022-04-18 10:22 UTC, merged