만국박람회 [Step2] 쿼카, Tiana
yagom-academy/ios-exposition-universelle pull request #147
Opened 2022-04-14 17:48 UTC by Kim-TaeHyun-A

안녕하세요 올라프  @1Consumption ⛄️

step2 PR 보냅니다! 잘 부탁드려요🙇‍♀️🙇🏻
# 고민한점

### 네이밍
- fileName이 길어져 ViewController 대신에 VC라고 변경해보았는데 무리가 없을까요?

### AutoLayout
다음 스텝에서 레이아웃을 진행할 예정이지만 UI 요소를 스토리보드에서 배치하는 과정에서 약간의 레이아웃 설정을 진행했습니다.
아래의 내용에 대해 자세히 공부할 예정입니다.
- intrinsic size에 대한 공부
- Content Layout Guide, FramLayoutGuide 개념 및 차이점
- stackView의 spacing, distribution, alignment

### cell
- 요구사항에서 보인 이미지와 동일한 형태의 셀을 만들기 위해 Disclosure Indicator 악세서리를 선택했습니다.

### 에러 처리
- Result사용에 대해서
이번 프로젝트는 에러를 throw하도록 했습니다.
Result 타입을 사용하면 더 간단하게 에러를 처리한다고 하는데 동일하게 try를 사용해서 값을 꺼내오기에 더 편리한지 잘 모르겠어서 사용하지 않았습니다.

### decode 타입 메서드
- static사용한 이유는 ParisExpo.decode를 했을때 nil이므로 static을 붙여 타입 메서드로 만들었습니다.

### cell initializer 구현
```swift
override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
    mainImageView.image = UIImage(named: "poster")
    titleLabel.text = "empty title"
    descriptionLabel.text = "empty description"
    super.init(style: style, reuseIdentifier: reuseIdentifier)
}
Required init?(coder: NSCoder) {
	super.init(coder: coder)	
}
```
- cell이 원하는 타입으로 캐스팅되지 않는 경우 else문에서 cell을 반환해야 하는 경우를 처리하기 위해 이니셜라이져를 구현했습니다.

```swift
KoreanItemTableViewCell(style: .default, reuseIdentifier: "KoreanItem")
```
- 위와 같이 타입캐스팅이 실패한 경우 적절하지 못한 cell을 반환하여 에러를 알리려고 했습니다.

### 하드코딩방지에 대해서
- enum으로 데이터값을 묶어서 연산프로퍼티로 관리를 하는 방법이 있고 static 상수로 값을 관리하는 방법도 있는데 전자는 dot으로 더 접근해야하여(타입.case.rawValue or property) 코드가 길어지는 단점이 있어서 후자를 사용하였습니다.
fileprivate을 붙여 사용하는 범위내로 지정해줌으로써 더 읽기 좋게 구분할 수 있다고 판단되어 접근제어자도 붙여주었습니다.

### 파일 분리
json파일들이 존재하는 asset의 경우 Resource 그룹에, 사용자 정의 타입이 아닌 제공되는 타입의 extension을 진행한 경우 Utils안의 Extension 그룹에 작성했습니다.

# 조언받고 싶은점
### tableView의 return처리에 대해서
```swift
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if let koreanItemsCount = koreanItems?.count {
            return koreanItemsCount
        }
        return 0
    }
```
- tableView 내에서 return 0을 하는부분에대해서
tableView는 이미 정의되어있는 메서드라서 오류를 처리할 수 없었고 다른 방법으로 강제추출하기에는 예상치못한 일이 발생할 수도 있으니 0 으로 return을 처리해주었는데요 혹시 이를 0으로 처리하지않고 처리해주는 방법이 있을까요 ??

2022-04-15 17:39 UTC, 1Consumption requested changes
안녕하세요~ 쿼카 티아나 고생하셨습니다!

커밋이 조금씩 커지고 있네요! 대부분의 커밋이 한번에 하나의 역할을 하고 있지만, 몇개는 여러개의 역할을 하 고 있거나 엉뚱한 커밋에 작업 사항이 들어가있기도 했어요.
이부분은 조금 더 주의를 부탁드릴게요.

-------------------------------------------------------------

아래는 질문 주신 점에 대한 제 생각입니다.

> fileName이 길어져 ViewController 대신에 VC라고 변경해보았는데 무리가 없을까요?

글쎄요... 저는 약어는 지양하는 편입니다. 약어를 써서 오는 이점보다는 조금 길더라도 명확히 표한하는게 더 좋다고 생각해요.

> tableView 내에서 return 0을 하는부분에대해서
tableView는 이미 정의되어있는 메서드라서 오류를 처리할 수 없었고 다른 방법으로 강제추출하기에는 예상치못한 일이 발생할 수도 있으니 0 으로 return을 처리해주었는데요 혹시 이를 0으로 처리하지않고 처리해주는 방법이 있을까요 ??

아니요. 없습니다. 반환형이 옵셔널이 아니기 때문에 항상 기본값을 넣어줘야 해요.

나머지는 코멘트를 참고해주세요!

2022-04-15 17:39 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ParisExpoVC.swift
> +}
커밋이 잘못 들어갔네요! 다음 커밋에 들어갔어야 할 내용 같습니다.
https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/e94f4ad09493786bccb1f454c9fedb738ce084f4

2022-04-15 17:39 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ParisExpoVC.swift
> +    @IBOutlet weak var rightImageView: UIImageView!
이 커밋의 역할이 아닌거 같습니다. 커밋은 한번에 하나의 역할만 하도록 주의해주세요.
https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/3e4ac6d0b7a4c6d7904b81686f3a5b8802a1c40a

2022-04-15 17:39 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/KoreanItemTableViewCell.swift
> +    }
이 코드의 의도는 뭔가요?

2022-04-15 17:39 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/KoreanItemVC.swift
> +        koreanItemsTableView.dataSource = self
메소드로 추상화가 되어있으면 좋을 거 같아요.

2022-04-15 17:39 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/KoreanItemVC.swift
> +    }
view의 역할일까요?

2022-04-15 17:39 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/KoreanItemVC.swift
> +        cell.mainImageView.image = UIImage(named: koreanItems[indexPath.row].imageName)
cell에 method를 만들어서 `KoreanHistoricalItem`을 넘겨주면 어떨까요?

2022-04-15 17:39 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ParisExpoVC.swift
> +    }
여기도 view의 역할일까요?

2022-04-15 17:39 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ParisExpoVC.swift
> +    }
upload~ 라는 네이밍이 이상하다고 생각합니다. upload는 서버에 뭔가를 전달하는 느낌이랄까요.

2022-04-15 17:39 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ParisExpoVC.swift
> +    }
스토리보드에서 설정이 가능한 부분이 어느정도 있어보이는데, 코드로 한 이유가 있을까요?
언제는 스토리보드로 하고, 언제는 코드로하는지 그 기준이 궁금합니다.

2022-04-15 17:39 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ParisExpoVC.swift
> +    }
첫번째 글자가 대문자네요!

2022-04-15 17:39 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/KoreanItemVC.swift
> +        }
만약 else문이 실행된다면 어떻게 될까요? 크래시가 나지는 않을까요? 난다면 왜 날까요?
힌트를 드리자면 coder init과 frame init의 차이를 공부해보세요.

2022-04-18 01:06 UTC, Quokkaaa commented on Expo1900/Expo1900/Controller/ParisExpoVC.swift
> +}
더 역할을 쪼개어 commit을 진행해보겠습니다.

2022-04-18 01:15 UTC, Kim-TaeHyun-A commented on Expo1900/Expo1900/Controller/KoreanItemTableViewCell.swift
> +    }
셀의 속성값을 초기화하려고 prepareForReuse()를 사용하려고 했지만 다시 고민을 해보니 적절한 위치가 아니네요😢

스토리보드로 관련 값을 세팅하도록 하겠습니다!

2022-04-18 01:31 UTC, Kim-TaeHyun-A commented on Expo1900/Expo1900/Controller/KoreanItemVC.swift
> +        koreanItemsTableView.dataSource = self
메서드로 추상화했습니다!
configurateDelegateProperties() 로 네이밍했는데 적절한지 궁금하네요🤔

[b2bb5ba](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/b2bb5ba1794a2f45cb08c82738eb61540d3265db)

2022-04-18 01:40 UTC, Kim-TaeHyun-A commented on Expo1900/Expo1900/Controller/KoreanItemVC.swift
> +    }
extension으로 메서드의 위치를 옮겼는데 의도하신 것이 맞을까요?🤔

[efe9840](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/efe9840977c40d44e65ac8555ab1d7d3f9f33998)

2022-04-18 01:53 UTC, Kim-TaeHyun-A commented on Expo1900/Expo1900/Controller/KoreanItemVC.swift
> +        cell.mainImageView.image = UIImage(named: koreanItems[indexPath.row].imageName)
cell에서 세팅하도록 메서드 구현했습니다! 감사합니다

[191431c](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/191431c115c49270518accd8fb4b347a7a85ef96)

2022-04-18 01:58 UTC, Kim-TaeHyun-A commented on Expo1900/Expo1900/Controller/ParisExpoVC.swift
> +    }
extension으로 위치 이동시켰습니다!

[6176c24](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/6176c24231e385fd9b4d378742fd1dc29686b6da)

2022-04-18 02:01 UTC, Kim-TaeHyun-A commented on Expo1900/Expo1900/Controller/ParisExpoVC.swift
> +    }
네이밍 변경했습니다! 감사합니다

[b4045e8](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/b4045e867b26936b6d3100acdc382b47ab815821)

2022-04-18 02:15 UTC, Kim-TaeHyun-A commented on Expo1900/Expo1900/Controller/ParisExpoVC.swift
> +    }
스토리보드에서 생성한 UI 요소라서 스토리보드에서 설정 가능한 것은 코드로 설정 않는 것이 더 자연스러운 것 같습니다! 수정했습니다.
스토리보드에서 생성하지 않은 것이나 스토리보드로 세팅이 불가능한 속성의 경우에 코드로 작성하는 것이 좋을 것 같습니다.

[6960b1b](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/6960b1b1906a45176c964d060c70978a69748599)
[5dfb9d1](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/5dfb9d1a339edc20cfde02bd66ba495ad860e20a)
[adb6c23](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/adb6c23548bc91604993c70acd17d8739efe6f90)
[4bd6cea](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/4bd6ceac3784c7beb66ad4a83ec718f88927cf86)
[ed36f0e](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/ed36f0e2c08ecb10945957f38a9040e55ee62973)

2022-04-18 02:17 UTC, Kim-TaeHyun-A commented on Expo1900/Expo1900/Controller/ParisExpoVC.swift
> +    }
수정했습니다. 감사합니다!

[3bc771e](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/3bc771e9dc4e5107911657905f8de71054043c79)

2022-04-18 02:50 UTC, Kim-TaeHyun-A commented on Expo1900/Expo1900/Controller/KoreanItemVC.swift
> +        }
존재하지 않는 identifier로 접근을 시도해서 else로 빠졌는데 else문에서 존재하지 않는 identifier로 접근하려는 것이 문제인 것으로 보입니다.
coder init의 경우 스토리보드로 설정한 identifier를 참조해서 셀을 구성합니다. frame init의 경우 코드로 cell을 구성해서 나중에 재사용하도록 identifier를 지정해주는 것 같습니다.
위 경우는 frame init으로 해결할 수 있는 문제로 보이지만 저희가 아직 코드로만 셀을 구성하기에는 부족하여 alert문을 띄우고 return UITableViewCell()을 반환하도록 했습니다😢


[69a3ebc](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/69a3ebca2f46280eadf7806cd8cde03e6c266514)
[1cff952](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/1cff952065ed3f47c09447a28d4ea71bdd257bea)
[af1d027](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/af1d0277e3998f97cb85dbbbd550e3e8631962de)

2022-04-18 12:26 UTC, Kim-TaeHyun-A commented on Expo1900/Expo1900/Controller/KoreanItemVC.swift
> +    }
올라프가 말씀하신대로 뷰의 역할을 생각해보았는데요, 기존에 decode하는 부분을 메서드로 만들어서 Decodable+extension에서 정의했만 네이밍 때문에 혼선이 있었던 것 같습니다.

네이밍이 적절하지 못한 것 같아서 decode에서 convert로 수정했습니다. 
[42313d3](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/42313d3461e79715496227c1d85de695bf0fea02)

2022-04-18 12:35 UTC, Kim-TaeHyun-A commented on Expo1900/Expo1900/Controller/KoreanItemVC.swift
> +        }
올라프가 조언해주신대로 빈 셀을 만들고 사용자 친화적인 메세지를 출력하도록 경고문을 수정했습니다!

[005eff8](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/005eff84247280e2f0a6f43e4d25fad862c2c9cf)

[7ef18e4](https://github.com/yagom-academy/ios-exposition-universelle/pull/147/commits/7ef18e46de63aa23c72bcafac0735da89c58a90d)

2022-04-18 16:58 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/KoreanItemVC.swift
> +        }
register를 매번 해주나요? 최초 1회면 될거같은데요...

2022-04-18 16:59 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/KoreanItemVC.swift
> +    }
네이밍의 문제가 아니라 이런 로직은 모델에 들어가야한다는 의도였어요. extension으로 따로 뺀다고 역할을 분리했다고 생각하면 안됩니다.

2022-04-18 17:03 UTC, 1Consumption commented
<img width="923" alt="image" src="https://user-images.githubusercontent.com/37682858/163844167-4566e906-8312-407d-acee-09d6b3bf3e45.png">
거의 대부분의 커밋을 티아나가 했군요. 물론 리팩토링 커밋이라 그럴 수 있다고 생각이 되긴 합니다만, 페어프로그래밍인 만큼 어느정도 번갈아가며 커밋을 해주세요.
추가적으로 몇가지 코멘트를 달았는데, 다음 스텝에서 반영해주셔도 좋습니다.

2022-04-18 17:03 UTC, merged