만국박람회 [STEP 2] Doogie, Red
yagom-academy/ios-exposition-universelle pull request #149
Opened 2022-04-15 04:19 UTC by doogie97

# 만국박람회 STEP2 PR

@TTOzzi
안녕하세요! 또치🦔 STEP2 완료해서 PR보냅니다!
잘부탁드립니다!😁😄

## 고민했던 것들
* Cell custom
* alert의 재사용성
* auto layout Y 포지션 or height 설정 

### 1. Cell custom

테이블 뷰에서 셀을 생성할 때, 구현 요구 사항의 부분이 `defaultContentConfiguration` 을 이용해서 이미 구현 되어 있는 컨텐츠로 충분할 것 같아 기본값을 사용해서 구현하였습니다.
```swift
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
    let cell = tableView.dequeueReusableCell(withIdentifier: "itemCell", for: indexPath)
    var contents = cell.defaultContentConfiguration()
    contents.attributedText = NSAttributedString(string: items[indexPath.row].name, attributes: [ .font: UIFont.systemFont(ofSize: 20, weight: .bold)])
    contents.secondaryText = items[indexPath.row].shortDescription
    contents.image = UIImage(named: items[indexPath.row].imageName)
    contents.imageProperties.maximumSize.width = CGFloat(100)
    contents.imageProperties.maximumSize.height = CGFloat(100)

    cell.contentConfiguration = contents
    return cell
}
```
다만, 이 부분에 대해서 날씨에게 조언을 구했을 때는 현업에서는 여러가지 이유로 `defaultContentConfiguration` 사용하지 않는다고 이야기 하셨는데요 또치의 의견이 궁금합니다. 

저희의 의견으로는 둘다 사용할 줄 알면 좋으니 STEP3에서는 이 부분을 customCell 로 구현하는 로직으로 바꿔보려고 생각하고 있습니다.

### 2. auto layout Y 포지션 or height 설정
![](https://i.imgur.com/ECRyIZV.png)
스크롤 뷰의 높이를 따로 설정해 주지 않으면 위와 같은 오류가 발생 했었는데 이 오류의 해결 방안으로 두 가지 방법을 확인했습니다

1. 높이 설정 후 priority 낮추기
![](https://i.imgur.com/xMawy3A.png)

2. Intrinsic Size 옵션 Placeholder로 바꿔주기
![](https://i.imgur.com/0Sa5q8g.png)

위 설정 이외에 어떤 방법이 있는지 궁금하고 또 위 두가지 방법 중에서 어떤 방법이 선호되는지 궁금합니다

### 3. alert의 재사용성
```swift
    func showAlert() {
        let alert = UIAlertController(title: "오류", message: "데이터를 불러올 수 없습니다.", preferredStyle: .alert)
        let action = UIAlertAction(title: "확인", style: .default, handler: nil)
        alert.addAction(action)
        self.present(alert, animated: true, completion: nil)
    }
```
현재 프로젝트에서 위와 같이 얼럿을 나타내는 메소드를 두 개의 뷰컨트롤러에 각각 하나씩 구현되어 있는데 지금 프로젝트에서는 한번씩 밖에 사용을 하지 않아서 각 뷰컨트롤러에 생성을 했지만 이런 재사용성이 있는데 여러 곳에서 사용하는 메서드를 하나의 파일로 만들어서 관리를 해줘도 괜찮은지 고민했습니다

## 조언 받고 싶은 내용
* decode 테스트 코드 
* 코드와 스토리보드의 비율

### 1. decode 테스트 코드
저희가 또치가 조언해 주신대로 DataSourceError 를 이용해서 decodeError 의 연관값을 설정해 주고 에러를 던져주려고 하였습니다. 
```swift
static func decode(with assetName: String) throws -> Self {
    guard let asset = NSDataAsset.init(name: assetName) else { throw DataLoadError.assetLoadError }
        
    let decoder = JSONDecoder()
    do {
        //이상하게도 decode 에서 data 를 할당하지 않고 catch 문을 으로 보낼 줄 알았는데 
        //잘못된 값 임에도 data 를 할당하더라구요?
        let data = try decoder.decode(Self.self, from: asset.data)
    } catch {
        //일부러 오류가 나는 테스트를 하는데도 
        //lldb 상 이부부을 지나가지 않습니다!
        throw DataLoadError.decodeError(message: error.localizedDescription)
    }
    return data
}
```
그런데 DecodingError 자체가 다른 에러라 그런지 decodeError 에러를 통과하지 않더라구요😅 이부분을 어떻게 해결 해야 할지 궁금합니다.

### 2. 코드와 스토리보드의 비율
저희가 코드와 스토리보드를 모두 사용해서 뷰를 구현하고 로직을 작성하였는데요, 물론 개인의 취향이 많이 반영된 부분이겠지만 어느 부분을 스토리 보드로 가져가면 유리하고 어느 부분을 코드로 가져가면 좋은지 조언을 구하고 싶습니다.😁

2022-04-17 14:51 UTC, TTOzzi requested changes
안녕하세요 두기, 레드! 🙇 
크흠.. 에러 테스트 때문에 많이 헤메신 것 같은데 고생하셨습니다..!

### auto layout Y 포지션 or height 설정

말씀하신 에러가 뜨는 이유는 스크롤 뷰의 크기가 내부 컨텐츠 크기에 의해 결정되는데, 그 컨텐츠의 크기가 앱이 실행되어야(런타임) 적용되어 현재 스토리보드를 그려주고 있는 Interface Builder가 알 수 없기 때문인데요.
지금 구현하신 코드에선 둘 다 스토리보드에서의 에러 메세지를 없애기 위한 것이고 사실상 실제 실행 시에는 적용되지 않을거라 선택하기 나름일 것 같아요.
스토리보드에서의 에러만 없애기 위함이라면 `Intrinsic Size` 를 `Placeholder`로 설정해줄 것 같고, 모종의 이유로 뷰의 크기를 설정해주고 있는 스택뷰가 없어졌을 때도 뷰가 기본 크기를 유지해야 하는 것이 의도라면 오토레이아웃으로 잡아줄 것 같습니다.

### decode 테스트 코드

음.. `decode`에서 실패하면 `error`를 던져줄테고, `catch` 블럭을 지나야 하는데 이상하네요..
일단 첨부해주신 코드가 `return data`에서 `data`를 찾을 수 없어 동작하지 않는 코드라 어떤 이유로 저 부분을 통과하지 않는지 짐작이 안 되네요 :disappointed:

<img width="839" alt="스크린샷 2022-04-17 오후 11 36 30" src="https://user-images.githubusercontent.com/50410213/163719775-8e2da200-d532-4194-979e-8d21c8ee7fa8.png">
<img width="845" alt="스크린샷 2022-04-17 오후 11 36 54" src="https://user-images.githubusercontent.com/50410213/163719778-37a6d9d6-9c05-4606-b317-c14d387cf3bb.png">

제가 수정해서 테스트했을 땐 잘 잡히는 것으로 확인되는데 조금 더 자세히 설명해주실 수 있을까요?

### 코드와 스토리보드의 비율

요것도 말씀하신대로 개인의 취향이나 팀에서 정한 컨벤션(팀원들의 취향)에 따라 결정될 것 같지만, 제 생각엔 둘 중 하나를 선택해야 할 때 "UI 작성 코드까지 코드리뷰를 할 것인가" 가 가장 큰 비중을 차지한다고 생각해요.
아무래도 스토리보드는 PR에서 볼 때 `xml` 형태로 나와서 그 파일만 보고 UI가 어떻게 구현되어있는지 이해하긴 어렵거든요.

추가로 지금은 항상 같은 브랜치에서 함께 작업하고 있어서 못 느끼셨을 수 있는데, 다른 개발자와 협업할 때 스토리 보드는 충돌이 자주 발생합니다.
충돌을 해결할 때도 사람이 이해하기 힘든 `xml` 파일을 읽고 수정해야 해서 걸림돌이 될 때가 많아요.
(제가 코드로 작성하는 UI를 선호해서 조금 부정적으로 말씀드린 것 같긴 한데, 스토리보드도 한 눈에 UI를 확인할 수 있어 충분히 좋습니다 🙂)

굳이 한 프로젝트에서 코드와 스토리보드의 비율을 나눠서 가져가야 한다면.. 간단한 UI는 스토리보드로, 스토리보드로 구현하기 어려운 동적인 UI는 코드로 작성할 수 있을 것 같아요 🤔 

----

PR 내용에 남겨주신 질문은 위 내용과 코멘트로 어느 정도 해결된 것 같은데요.
혹시나 제가 빠트린 부분이 있거나, 이해가 어려운 부분이 있다면 언제든지 말씀해주세요 🙇

2022-04-17 14:51 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ItemViewController.swift
> +class ItemViewController: UIViewController {
다른 클래스가 상속받지 않는 클래스라면 `final` 을 명시해주는 게 좋아요.
개발자에게도 컴파일러에게도 의도를 명확하게 전달할 수 있습니다 🙂

2022-04-17 14:51 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ItemViewController.swift
> +    @IBOutlet weak var descriptionLabel: UILabel!
요기도 위와 마찬가지로 외부에서 접근하지 않는다면 `private` 을 명시해주세요!
관련 내용은 [Increasing Performance by Reducing Dynamic Dispatch](https://developer.apple.com/swift/blog/?id=27) 를 한 번 읽어보시면 좋을 것 같습니다.

2022-04-17 14:51 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ItemViewController.swift
> +    func displayItemInfo() {
함수도 `private` 붙여주세요!
(`final`, `private` 관련 코멘트는 여기까지만 달게요~ 전체적으로 확인 한 번 부탁드립니다 🙏 )

2022-04-17 14:51 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ItemViewController.swift
> +        descriptionLabel.text = item.description
`self`를 붙이는 기준이 어떻게 되나요? 👀 
사소하지만 `self`를 명시하는 것도 명확한 기준을 두어 일관된 코드를 작성하는 게 좋습니다.

2022-04-17 14:51 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +    }
모델의 범위를 어디까지 생각하느냐에 따라 의견이 다를 것 같긴 한데.. 두기, 레드는 MVC에서의 모델을 어떻게 정의하시나요? 👀 
저는 디코드 할 json 파일의 이름을 알고 있고, 그걸 가져오는 역할은 모델로 분리해주는 게 좋을 것 같아요 🤔 
(추가로 들여쓰기가 조금 어색한 것 같은데, 의도한 컨벤션이 아니라면 항상 코드 작성 후 `control + i`로 들여쓰기를 맞춰주세요!)

2022-04-17 14:51 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +        contents.attributedText = NSAttributedString(string: items[indexPath.row].name, attributes: [ .font: UIFont.systemFont(ofSize: 20, weight: .bold)])
배열의 요소에 `index`로 접근할 땐, 언제든 `index`가 범위를 벗어나 예상치 못한 크래시가 발생할 수 있습니다.
`index` 접근 전, 범위 체크를 해 주거나 `Array`의 `extension`으로 배열에 안전하게 접근할 수 있는 `subscript`를 구현해주는 게 좋을 것 같아요.

2022-04-17 14:51 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +        return cell
여러가지 방법을 시도하시는 것 정말 좋아요 😃
코드에 정답은 없지만.. 아무래도 애플에서 기본적으로 제공해주는 UI 외에 다른 커스텀 UI가 필요할 때가 많은데, 그 땐 애플에서 제공해주는 영역까지 커스텀하게 바꿔주기 어렵기 때문에 이 방법보단 직접 커스텀 셀을 구현하는 방법을 많이 사용하는 것 같아요.
예를들어 현재 UI 에서 제목과 설명 사이에 영문 이름 표시를 위한 라벨 하나를 하나 더 추가해달라고 한다면.. 되게 난감할 것 같네요 😖
커스텀 셀을 만들면 셀의 UI 설정하는 부분을 셀 클래스 내부로 묶어내어 여러 역할의 코드가 한 곳으로 몰리는 것을 어느 정도 방지할 수 있다는 것도 잘 사용하지 않는 이유가 될 수 있을 것 같습니다.

2022-04-17 14:51 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +        guard let itemVC = self.storyboard?.instantiateViewController(withIdentifier: "ItemViewController") as? ItemViewController else { return }
위에서 셀을 `dequeue` 해올때도 그렇고 이렇게 클래스 이름을 그대로 `identifier`로 사용하는 경우가 많아질텐데요.
클래스 이름을 직접 문자열로 전달할 때 발생하는 실수를 방지하기 위해 `extension`으로 자기 자신의 타입을 반환하는 프로퍼티를 구현해서 `identifier`로 전달해주기도 합니다.

2022-04-17 14:51 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    }
말씀하신대로 중복되는 코드라 어느 정도 변경 가능하도록 열어두고 따로 분리해주는 게 좋을 것 같네요!

2022-04-17 14:51 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        return "\(dividedTitle[0])\n(\(dividedTitle[1])"
만약 json 파일 `title`의 `(영문명)`이 누락되어 있다면 크래시가 발생할 수 있겠네요 🤔 
현재는 정적으로 json 파일을 넣어둔 채 사용해서 문제가 없지만, 나중에 서버에서 데이터를 내려받게 된다면 언제든 파일의 변경이 일어날 수 있어 예외처리를 해주는 게 좋을 것 같습니다.

2022-04-17 14:51 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    }
요정도는 (뷰에 보여주기 위한 문자열 포맷팅이긴 하지만..) 별도 객체로 따로 분리해줘도 될 것 같아요.
UI 와의 직접적인 의존 관계는 없는 것 같아서요!

2022-04-17 14:51 UTC, TTOzzi commented on Expo1900/Expo1900Tests/ModelTest.swift
> +            print(print("\n key: \(key) \n value: \(value) \n"))
여기가 문제의 부분이군요...!
일단 `print`로 테스트의 성공을 확인하는 건 직접 개발자가 콘솔을 확인해야 하기에 좋은 방법은 아닌 것 같습니다.
자세한 내용은 따로 코멘트 남겨둘게요 🙇

2022-04-17 14:51 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        guard let changedNumber = numberFormmater.string(from: number as NSNumber) else { return "" }
변환에 실패했을 때, 아무 의미 없는 빈 문자열을 반환해주기보단 명시적으로 실패를 표현할 수 있도록 `nil`을 반환하고 사용하는 곳에선 그에 따른 처리를 해주는 게 좋을 것 같네요.
지금은 실패하면 `방문객 :  명` 으로 출력될 것 같아요 🤔

2022-04-17 15:13 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +            showAlert()
DM으로 말씀해주신 에러처리 방법은 이 부분을 말씀하시는 건가요?!
지금은 에러 메세지를 항상 "데이터를 불러올 수 없습니다." 로 표시해주고 있지만, 발생한 에러에 따라 다른 메세지가 출력되어야 한다면 구현하신 `DataLoadError`가 `localizedDescription`를 가지도록 구현하고 그걸 인자로 넘겨 `alert`로 표시해볼 수 있을 것 같습니다.

2022-04-18 03:35 UTC, doogie97 commented on Expo1900/Expo1900/Controller/ItemViewController.swift
> +        descriptionLabel.text = item.description
현재 아무 기준 없이 작성 하고 있었기에 레드와 상의 후 꼭 필요한 곳에서만 self키워드를 작성하기로 하였고 가독성을 위해 생략 가능한 self는 제거해 주기로 하였습니다

2022-04-18 03:56 UTC, doogie97 commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +        return cell
이 부분은 STEP3에서 커스텀 셀로 구현해 볼 예정입니다!

2022-04-18 08:56 UTC, doogie97 commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +        contents.attributedText = NSAttributedString(string: items[indexPath.row].name, attributes: [ .font: UIFont.systemFont(ofSize: 20, weight: .bold)])
```swift
extension Array where Element == Item {
    subscript(safe index: Int) -> Item {
        if self.count > index {
            return self[index]
        }
        return Item(name: "알수없음", imageName: "알수없음", shortDescription: "알수없음", description: "알수없음")
    }
}
```

이런 식으로 index가 배열의 카운트를 넘어서게 되면 "알수없음" 이라는 String들을 가진 Item으로 반환 하게 만들었는데 
fatal오류를 방지하는 방향으로는 목적을 달성하긴 했습니다
하지만 저희는 Item?을 반환하게 만들어서 index가 count를 넘어간다면 nil을 반환해서 아무 처리도 하지 않게 만들고 싶습니다.(cell을 만들고 싶지 않습니다)

![image](https://user-images.githubusercontent.com/82325822/163783875-47171313-ae4f-4490-97f0-fd122080bd7e.png)
그런데 여기서 보면 UITableViewCell을 리턴하게 되어있어서 어쩔 수 없이 cell을 반환해야 하는데 이런 상황에서는 어떻게 처리하면 좋을까요?

2022-04-18 09:23 UTC, doogie97 commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +        guard let itemVC = self.storyboard?.instantiateViewController(withIdentifier: "ItemViewController") as? ItemViewController else { return }
UIViewController를 extension해서 self를 문자열로 반환 할 수 있도록 프로퍼티를 만들어줬습니다
cell부분 또한 지금 진행하고 싶었으나 customCell이 아니라서 할당해준 class가 없어 반환해줄 값이 없기에 차 후 customCell구현 하면서 추가적으로 구현할 예정입니다

2022-04-18 09:32 UTC, cherrishRed commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    }
네 UIViewController 에 extension을 이용해서 중복을 제거해 주었고, 파라미터 값을 이용해서 title 과 message 를 설정할 수 있도록 해 주었습니다.

2022-04-18 09:38 UTC, doogie97 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        return "\(dividedTitle[0])\n(\(dividedTitle[1])"
title의 영문명이 `()`안에 들어온다고 가정하고 `(`를 기준으로 있다면 분리해서 반환하고 없다면 그냥 들어온 그대로의 title을 반환하도록 수정 하였습니다

2022-04-18 10:02 UTC, cherrishRed commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        guard let changedNumber = numberFormmater.string(from: number as NSNumber) else { return "" }
저희가 Int extension 을 이용해서 changeNumberFormat 을 분리했습니다.
실패할 경우 nil 을 반환하도록 처리하였고, 호출부에서 nil 을 반환할 경우 "정보없음" 이라고 처리 되도록 수정 했습니다.

한가지 궁금한 점은 Numberformatter 가 비용이 많이 드는 클래스라고 들었는데, 이것을 메서드를 호출할때 마다 생성해 주는 것이 맞는 것인지 아니면 프로퍼티나 타입 프로퍼티로 선언해 준뒤 가져다 쓰는 것 중에 어느것이 비용이 적게 드는지 궁금합니다.
(현재는 단 한번밖에 사용하지 않기 때문에 메서드에서 생성 했습니다.)

2022-04-18 16:19 UTC, cherrishRed commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +            showAlert()
넵 errorDescription 을 이용해서 alert 의 에러의 종류가 반영되도록 변경했습니다!

2022-04-18 16:21 UTC, cherrishRed commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +    }
네 모델 부분으로 getItems 와 getExpoInfo 메서드를 이동하였습니다. 
들여쓰기 항상 주의하도록 하겠습니다.

2022-04-18 16:34 UTC, cherrishRed commented
@TTOzzi 저희 리펙토링 완료 했습니다!

### 추가적인 질문 
이 코드에서 is 는 어떤 원리로 작동되는 것일까요?
```swift
extension Decodable {
    static func decode(with assetName: String) throws -> Self {
        guard let asset = NSDataAsset.init(name: assetName) else { throw DataLoadError.assetLoadError }
        
        let decoder = JSONDecoder()
        do {
            let data = try decoder.decode(Self.self, from: asset.data)
            return data
        } catch is DecodingError{
            throw DataLoadError.dataLoadError
        }
    }
}
```
컴파일러가 is 를 추천해주어서 사용해 보았습니다. 작동은 잘 되는데 저희가 작동원리를 이해하지 못했습니다.
저희가 아는 is 는 타입을 비교해서 bool 값을 반환해준다고 알고 있습니다.
그래서 `catch self is DecodingError` 이라고 예상을 했는데, 이렇게 하면 작동을 안하다라구요.
우선은 이해할 수 있는 코드인  `catch _ as DecodingError` 를 사용하였습니다.

2022-04-19 17:05 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ItemViewController.swift
> +        descriptionLabel.text = item.description
넵 개인적으론 `self` 를 생략하면, `self` 가 정말 필요할 때 컴파일러가 에러를 발생시켜줘서 `self` 를 캡쳐해야하는 상황을 명확하게 파악할 수 있어 좋다고 생각해요 🙂

2022-04-19 17:15 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +        contents.attributedText = NSAttributedString(string: items[indexPath.row].name, attributes: [ .font: UIFont.systemFont(ofSize: 20, weight: .bold)])
음 일단은 `Element` 가 `Item` 일때만 사용 가능한 extension을 만들기보단, extension은 다른 `Element`를 가질때도 사용할 수 있도록 구현해두고, 기본값을 두는 처리 등은 사용하는 곳에서 해주는 게 좋을 것 같아요 🤔 
만약 똑같은 상황이 생겼는데 `Element`의 타입이 다를 경우엔 비슷한 코드가 한 셋트 더 만들어질 것 같아서요.

어쩔 수 없이 셀을 반환해야 하니 기본값 `UITableViewCell`을 생성해 앱이 터지지 않도록만 해주고, 실제 스토어에 릴리즈되는 버전엔 영향을 주지 않는 `assertionFailure`를 활용해 개발 과정에서 `index` 범위를 벗어나는 케이스가 있음을 파악할 수 있도록 해줄 것 같아요.
`index`가 범위를 벗어났을 때 서버에 로그를 기록할 수도 있을 것 같구요. 
중요한 건 앱이 종료되는 경험을 사용자가 겪지 않게 하는 것이라고 생각합니다!

2022-04-19 17:21 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        guard let changedNumber = numberFormmater.string(from: number as NSNumber) else { return "" }
아마..? `DateFormatter`가 생성/설정 첫 사용에 비용이 많이 드는 것으로 알고있고, `NumberFormatter`는 그만큼은 아닌 것 같긴 한데 그래도 생성 코드가 중복된다면 다른 곳에 하나를 생성해두고 그걸 가져다가 사용하는 것이 좋을 것 같아요!

2022-04-19 17:24 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +            showAlert()
`localizedDescription`는 아무래도 에러에 대한 설명을 문자열로 제공해주기만 할 뿐이라서, 만약 특정 타입이나 여러 개의 값을 에러에 담아 넘겨주고 싶다면 연관값을 사용해야 할 것 같아요.
용도가 달라서 구현 목적에 따라 선택하시면 될 것 같습니다. 둘 다 필요한 상황이 있을 수도 있구요!

2022-04-19 17:36 UTC, TTOzzi commented
> 컴파일러가 is 를 추천해주어서 사용해 보았습니다. 작동은 잘 되는데 저희가 작동원리를 이해하지 못했습니다.
저희가 아는 is 는 타입을 비교해서 bool 값을 반환해준다고 알고 있습니다.
그래서 catch self is DecodingError 이라고 예상을 했는데, 이렇게 하면 작동을 안하다라구요.
우선은 이해할 수 있는 코드인 catch _ as DecodingError 를 사용하였습니다.

catch 블럭에 들어오는 숨겨진 인자는 `Error` 타입의 값이라 `catch self is DecodingError`에서 `self`는 에러가 아닌, "Decodable을 채택한 어떤 타입"이 될거라 동작하지 않을거예요.
catch 옆에 `error` 인자가 생략되어있다고 생각하시면 될 것 같습니다! 따로 정의해주지 않아도 발생한 `error` 에 접근할 수 있는 것도 이것 때문이구요.
비슷한 문법으론 `switch-case` 문에서 `case is Type:`도 가능해요! 
요것도 예시로 작성해주신 코드와 같이 읽히는 그대로 해당 케이스가 ~~ 타입일때 동작하게 됩니다.

그리고 추가로 덧붙이자면.. 지금 예시로 보여주신 코드처럼 catch 블럭에 조건을 걸면, `decoder.decode`에서 던져진 에러가 `DecodingError` 타입일 때만 `DataLoadError.dataLoadError`를 던지고 다른 타입의 에러가 발생하면 그걸 그대로 외부로 던져버릴거에요.
요건 의도하신 동작일까요? 👀 
관련된 자세한 내용은 https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html 요기 문서에 **Handling Errors Using Do-Catch** 부분 읽어보시면 좋을 것 같습니다 🙂

2022-04-19 18:08 UTC, TTOzzi approved these changes
고생하셨습니다!
저번에 말씀드렸듯이 제 코멘트는 꼭 반영하지 않으셔도 됩니다 🙏 
두기, 레드가 생각하셨을때 괜찮은 것 같으면 반영하시고, 아니면 그냥 넘어가시거나 의문이 생기는 부분에 대해 추가 질문을 주셔도 돼요!
ChangeRequest가 1회 제한이 있어서 다음 스텝 진행을 위해 요기서 머지할게요 🙇

2022-04-19 18:08 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ItemTableViewCell.swift
> +class ItemTableViewCell: UITableViewCell {
요기도 `final` 붙여주세요! 항상 습관처럼 작성해주는 게 좋아요 
상속이 필요하면 컴파일러가 에러를 표시해줄테니 그 때 바꿔주면 되구요!

2022-04-19 18:08 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ItemViewController.swift
> +    var item: Item?
이렇게 열어두게 되면 뷰컨이 생성, 보여지고 난 이후에도 언제든 `item`이 바뀔 수 있을 것 같아요.
지금은 두 분이서만 협업을 하고 있고, 프로젝트 규모가 작다보니 처음에만 할당해준다는 것을 알고있지만 코드가 복잡해지고 여러 명이서 협업을 한다면 이 `item`을 첫 생성 시점에만 할당하고, 그 이후는 변경이 없음을 코드로 표현해주는 게 좋아요.

"storyboard creator init" 과 "의존성 주입" 이라는 키워드를 찾아보시면 좋을 것 같습니다!
(요건 지금 당장 꼭 필요하진 않으니 이런게 있구나 정도만 생각해주셔도 됩니다 🙏 )

2022-04-19 18:08 UTC, TTOzzi commented on Expo1900/Expo1900/Extension/extension+Array.swift
> +        if self.count > index {
`Item`에 의존하는 부분에 대한 건 따로 코멘트 남겨뒀고, `index`가 음수로 들어오는 경우도 추가로 처리해주면 더 좋을 것 같습니다!
혹~~시 모르니까요 ㅎㅎ

2022-04-19 18:08 UTC, TTOzzi commented on Expo1900/Expo1900/Extension/extension+Int.swift
> +}
특정 화면에서만 쓰이는 이 로직을 `Int`의 extension으로 구현할 필요가 있을까 하는 생각이 드네요 🤔 
`NumberFormatter`를 가지고 있는 별도의 객체를 만들고, 그 객체를 뷰컨이 들고있으면서 `Int` 값을 넘겨주면 문자열을 반환하도록 구현해도 될 것 같아요.

2022-04-19 18:08 UTC, TTOzzi commented on Expo1900/Expo1900/Model/Exposition.swift
> +    }
헉 단순 데이터 구조였던 `Exposition` 구조체가 뷰컨을 받아 알러트를 띄워주는 역할까지 맡게되어버렸네요 😮
주관이 살짝 들어간 코멘트이긴 한데, "모델"은 꼭 요런 데이터 구조가 아니더라도 특정 로직을 갖고 있는 객체가 될 수도 있다고 생각합니다.
모델의 책임은 `json` 파일 이름을 알고있고, 호출하는 메서드에 따라 특정 `json` 파일을 파싱 후 데이터를 반환하는 것 까지일 것 같고 알러트를 표시하는 로직은 뷰컨이 가져야 할 것 같아요 🤔

2022-04-19 18:08 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +        itemCell.shortDescriptionLabel.text = items[safe: indexPath.row].shortDescription
`indexPath`에 해당하는 `Item`의 값들을 하나씩 꺼내서 `itemCell`이 가진 뷰들에 직접 접근해서 설정해주고 있는데요.
`itemCell`에 `item`을 넘기는 메서드를 만들어줘서 그 메서드 내에서 셀의 설정들을 수행한다면, `itemCell`이 가진 뷰들도 감추고 뷰 컨트롤러의 코드를 줄여줄 수 있을 것 같아요!

2022-04-19 18:09 UTC, merged