만국박람회 [Step2] mmim, Minseong
yagom-academy/ios-exposition-universelle pull request #150
Opened 2022-04-15 04:21 UTC by JoSH0318

@AppleCEO  안녕하세요! 도미닉 👑  
STEP 2 PR 입니다!
이번에도 잘 부탁드립니다! ☺️

---

## [STEP 2]
### 고민 및 해결한 점

1️⃣ 메인화면의 navigationBar만 없애야 되는 이슈
- 메인화면은 navigationBar가 없는 것을 요구사항 이미지에서 확인하였습니다
> isNavigationBarHidden를 이용해 navigationBar를 없앨 수 있다

- isNavigationBarHidden사용하면 다른 뷰에도 영향을 주는 이슈가 발생했습니다
- isNavigationBarHidden사용하면 navigationController의 navigation bar를 없애게 되어 모든 화면의 bar가 사라지는 것을 알게 됐습니다
- 따라서 화면이 전환되는 시점에 다시 해제시켜줘야 합니다
> viewWillAppear -> isNavigationBarHidden = true
> viewWillDisappear -> isNavigationBarHidden = false
> 를 통해 해결하였습니다 

2️⃣ 첫번째 화면 TextLabel을 원하는 곳에서 줄바꿈 하는법
- 요구사항 이미지에서 "파리 만국 박람회 1900"뒤로 부연설명 부분이 줄바꿈 되어있는것을 확인하였습니다
- label의 줄바꿈 속성 lineBreakMode에 Word Wrap을 이용하여 해결하려고 시도해 보았습니다
    - "1900()"이런식으로 부연설명이 붙어 있어서 단어 구별을 실패했습니다ㅠㅠ
- "("를 기준으로 문자열을 나누고 첫번째 문자열은 title에, 두번째 문자열은 subtitle에 넣는 방식을 시도해보았다.
    - 이번 프로젝트 예시에 한정된 방법이라고 생각하여 철회했습니다 ㅠㅠ

3️⃣ asset이미지는 어떻게 삽입해줄 것인가
- 1.스토리보드에서 asset이미지 파일을 써서 바로 넣어주는 것 
- 2.코드로 이미지를 넣어주는 것
> 이미지를 한번 넣으면 고정될 이미지라고 생각했습니다, 스토리보드에서 제공하는 기능을 이용하여 바로 이미지를 넣어 주는것이 효과적이라고 생각했습니다

4️⃣ 화면 전환 시, 셀의 데이터 전달
- 세번째 뷰로 셀의 데이터를 어떻게 전달해야 하는가?? 고민하였습니다
> Instance Property를 이용하여 전달하는 방식으로 해결해 주었습니다

5️⃣ cell 만들기 - tableView(_ tableView:,cellForRowAt: )
1. tableView(_ tableView:,cellForRowAt: ) 메서드 내부에 `textLabel`을 이용하여 스토리보드 구현없이 cell을 만들고자 했습니다.
    - `Deprecated`될 것이라는 경고가 뜨는 것을 확인했고, 가능한한 사용하지 않기로 결정했습니다.
    - `defaultContentConfiguration`가 대신하여 새롭게 생긴 메서드인 것을 확인!
    
2. `textLabel`이 `Deprecated`되고 새롭게 통합된 `defaultContentConfiguration`를 사용하여 cell을 만들기!
```swift
var content = view?.defaultContentConfiguration()  
    content?.text = "some data" 
    cell?.contentConfiguration = content 
    return cell
```
- 이러한 방법으로 구성해봤으나 Image의 크기를 설정할 수가 없었습니다. 
    - 크기를 설정하는 메서드를 찾아봤으나 찾지 못했습니다.(size, frame 등은 전부 get only였음)

3. custom cell을 이용하여 cell을 만들기!
- 이미지와 label들의 크기/위치를 자유롭게 설정할 수 있어야 한다고 생각했고, custom cell을 이용하는 것이 가장 용이하다 판단했습니다.
```swift
 guard let cell = tableView
                .dequeueReusableCell(withIdentifier: "cell",
                                     for: indexPath) as? ExhibitionItemsTableViewCell
        else {
            return UITableViewCell()
        }
        
        cell.itemImageView.image = UIImage(named: exhibitionItems[indexPath.row].imageName)
        cell.titleLabel.text = exhibitionItems[indexPath.row].name
        cell.subtitleLabel.text = exhibitionItems[indexPath.row].shortDescription
```
> - 스토리보드에 이미지와 label들을 구현하고 UITableViewCell에 IBOutlet을 연결했습니다.
> - 위 코드와 같이 tableView(_ tableView:,cellForRowAt: ) 메서드 내부에서 image와 label에 값을 할당해주었습니다.

---

### 궁금한 점 및 질문사항 
1️⃣ Error Handling
프로젝트를 진행하다 보니 error를 처리해줘야하는 몇 가지 경우가 생겼습니다. 대부분 JSON file과 매칭이 되지 않을 때(찾을 수 없게 될 때) 생기는 에러입니다. 만약 에러가 발생했을 경우, 어떠한 동작을 해야할 지 결정하지 못했습니다.(요구사항에 없는 내용이라 😭)
저희가 생각해본 방법은 이러합니다.
- 알럿을 띄운 후, 확인을 누르면 빈 화면 제공
- 빈 화면 (무반응)
- label.text들에 에러 메시지 할당 
> 혹시 이런 방법들로 요구사항과 다르게 구현해봐도 될까요? 그리고 더 추천해주실 에러핸들링 방법이 있다면 조언을 받고 싶습니다.🙏

2️⃣ (고민한 점 2️⃣ 번 내용)첫번째 화면 TextLabel을 원하는 곳에서 줄바꿈 하는법
- 이 부분에 대해서 조언??힌트를 얻을 수 있을까요??😂❤️

3️⃣ (고민한 점 3️⃣ 번 내용)asset이미지는 어떻게 삽입해줄 것인가??
- 저희의 생각이 더 효율적인 것이 맞을까요??

2022-04-17 11:40 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
@JoSH0318 , @Minseong-yagom 고생하셨습니다!
리뷰가 예정보다 늦어져서 미안합니다.
몇가지 코멘트 남겨봤습니다. 개선하고 넘어갔으면 좋겠습니다~

질문에 대한 답변
1️⃣ Error Handling
- 3가지 방법 다 고려해 볼 수 있을 것 같습니다! 정답은 없을 것 같네요. 어떤 방법이 적합하다고 생각하시나요?
- 요구사항이 없다면 어떤 것이든 선택해봐도 좋을 것 같습니다. 일정이 촉박하다면 너무 이 것에 시간을 많이 들이는 것이 안 좋을 수도 있겠네요!

2️⃣ (고민한 점 2️⃣ 번 내용)첫번째 화면 TextLabel을 원하는 곳에서 줄바꿈 하는법
- \n 으로 줄바꿈이 혹시 될까요?

3️⃣ (고민한 점 3️⃣ 번 내용)asset이미지는 어떻게 삽입해줄 것인가??
- 저는 고정된 이미지라면 스토리보드에서 넣어주고 있습니다. 만약 가변적인 것이라면 코드로 이름에 따라서 넣어주게 구성합니다~

2022-04-17 11:40 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/DetailViewController.swift
> +        self.title = exhibitionItem.name
self가 붙은 프로퍼티와 안 붙은 프로퍼티는 어떤 기준으로 나눠진 것일까요?
self를 붙인 것과 안 붙인 것 어떤 차이가 있을까요?

2022-04-17 11:40 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/ExhibitionItemsViewController.swift
> +    @IBOutlet weak var tableView: UITableView!
어떤 내용이 들어갈 테이블뷰인지 적혀있으면 더 좋을 것 같네요.
ExhibitionItemsTableViewCell 에 titleLabel, itemImageView 처럼요~

2022-04-17 11:40 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/DetailViewController.swift
> +        }
guard let 으로 안정적으로 옵셔널 바인딩을 하는 것 좋네요! 👍

2022-04-17 11:40 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/ExhibitionItemsViewController.swift
> +    private func decode() -> [ExhibitionItem] {
decode 라는 메소드는 무엇을 복호화하는지 불명확하네요.
아랍 언어를 독해하는지, 암호화된 파일을 복호화하는지 불명확한 메소드명이네요!

2022-04-17 11:40 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/ExhibitionItemsViewController.swift
> +                                     for: indexPath) as? ExhibitionItemsTableViewCell
줄넘김이 어색해보이네요. 한 줄로 작성하지 않고 이렇게 줄넘김을 한 이유가 있을까요?

2022-04-17 11:40 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/ExhibitionItemsViewController.swift
> +        return cell
셀이라는 이름도 어색하네요.
보통 decode, cell 과 같은 많이 쓰이는 이름은 이미 예약어로 등록이 되어있을 수 있고 스위프트에 기본 메소드와 혼돈이 생길 수 있어서 조금 더 명확한 이름으로 더 길게 작성하는 것이 좋다고 생각합니다.

2022-04-17 11:40 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +            return ExpoInformation(title: "",
do와 catch에 return이 각각 있는 것도 저는 조금 어렵게 읽히는 것 같네요.
더 읽기 좋게 개선해 볼 수 있을까요?

2022-04-17 11:40 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/ExhibitionItemsViewController.swift
> +        cell.subtitleLabel.text = exhibitionItems[indexPath.row].shortDescription
이렇게 셀의 프로퍼티에 각각 직접 값을 넣어주는 것이 아니라 cell의 프로퍼티는 private 접근제어자를 사용하고 셀의 메소드로 이 값들을 전달해서 셀이 직접 데이터를 갱신하도록 해볼 수 있을까요?

2022-04-17 11:40 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/ExhibitionItemsViewController.swift
> +        }
여기 줄 바꿈도 어색하네요.
읽기 힘든 것 같습니다.
어디에서 봤는데 한 줄에 ? 는 하나만 나오는게 좋다는 이야기도 있더라고요.
가독성을 높여볼 수 있을까요?

2022-04-17 11:40 UTC, AppleCEO commented on Expo1900/Expo1900/Util/Extension/Decodable+Extension.swift
> +extension Decodable {
Decodable도 풀 수 있는 이라고 번역이 되는데요.
어떤 암호도 풀 수 있는 프로토콜일까요?
무엇을 푸는지 조금더 길고 명확한 이름이 있을 것 같아요!

2022-04-17 11:40 UTC, AppleCEO commented on Expo1900/Expo1900/Util/Extension/Int+Extension.swift
> +extension Int {
Int를 extension 으로 사용해보셨군요.
이렇게 extension 으로 Int에 메소드를 추가해주는 것과 구조체를 만들어서 그 구조체에 같은 메소드를 만들어주는 것에 어떤 차이가 있을까요?
두가지 방법은 각각 어떤 장단점이 있을까요?

2022-04-18 11:40 UTC, JoSH0318 commented on Expo1900/Expo1900/Controller/DetailViewController.swift
> +        self.title = exhibitionItem.name
누락된 부분이 있는 것 같습니다. 😂
저희끼리 컨벤션을 정해봤고, 타입 내에 있는 프로퍼티와 메서드를 호출할 때 self 키워드를 붙여주는 것으로 정해봤습니다. 🤓 
성능적인 측면에서 큰 차이는 없다고 생각합니다. 다만 가독성 측면에서 명시적으로 적어주는게 좋다고 생각합니다. 👍

2022-04-18 12:05 UTC, JoSH0318 commented on Expo1900/Expo1900/Controller/ExhibitionItemsViewController.swift
> +                                     for: indexPath) as? ExhibitionItemsTableViewCell
가독성 측면에서 볼 때, 
코드가 한줄로 너무 길면 가독성이 떨어지는 것을 느꼈고, 실제로 좌우보단 상하로 긴 코드를 추구한다고 들었습니다.
그래서 개행을 통한 가독성 높이기를 연습중이었습니다 😂
아직 많이 부족한 것 같습니다. 좀더 가독성을 높이는 쪽으로 생각해보겠습니다.

2022-04-18 14:18 UTC, JoSH0318 commented on Expo1900/Expo1900/Controller/ExhibitionItemsViewController.swift
> +        cell.subtitleLabel.text = exhibitionItems[indexPath.row].shortDescription
IBOutlet 변수에 private 키워드 붙여주고 각 변수에 값을 할당하기 위한 setUpCell() 메서드를 구현했습니다.

파라미터로 exhibitionItems[indexPath.row]를 받음으로써 Cell이 직접 데이터를 갱신하도록 만들었습니다. 😀

2022-04-18 15:18 UTC, JoSH0318 commented on Expo1900/Expo1900/Util/Extension/Int+Extension.swift
> +extension Int {
일단 차이점은 
<Int 타입이면 누구든 접근 가능하다.> vs <구조체 타입을 따르는 인스턴스만 접근 가능하다.>가 가장 큰 차이점일 것 같습니다.
이 차이점으로 인해 각각 장단점이 생기는 것 같습니다.
이러한 점 때문에 저희 프로젝트에서는 후자가 더 적합할수도 있다 판단했고, 수정하려고 했습니다.
---
여기서 문제점 이 생겼습니다.
1. 전자의 경우, decodedData.visitors.convertNumberFormat()와 같은 방법으로 접근하여 의미가 명확합니다.
2. 후자의 경우, decodedData.convertNumberFormat()와 같은 방법으로 접근하여 데이터의 어떤 부분을 convert해주는 지 명확하지 않습니다. 그래서 명확한 의미 전달을 위해 decodedData.convertVisitorsToNumberFormat()로 변경했고, 메서드명이 너무 길어져서 오히려 가독성이 떨어집니다.

이번 프로젝트에서 서로의 장단점이 팽팽히 대립하는 것 같습니다. 어떠한 선택을 해야할 지 잘 모르겠습니다.
도미닉의 의견을 듣고싶습니다! 조언 부탁드립니다!

2022-04-19 00:14 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/DetailViewController.swift
> +        self.title = exhibitionItem.name
아.. 문서에도 아마 스타일쉐어 스위프트 스타일 가이드를 따른다고 적혀있던 것 같은데.. 맞나요?
그 쪽에도 self를 어느 곳에 쓸지에 대해 명시되어 있으니 참고해보셔도 좋을 것 같습니다~

2022-04-19 00:16 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/ExhibitionItemsViewController.swift
> +                                     for: indexPath) as? ExhibitionItemsTableViewCell
오호... 규칙을 뒀었군요.
저는 한 줄로 길게 작성해도 괜찮다는 의견입니다.
오히려 예상치 못한 곳에 줄넘김이 자주 있으면 이게 guard let 구문이 시작되는 코드인지, 아직 guard let 코드가 진행 중인지 위에 줄 끝까지를 확인해야해서 더 힘들더라고요.
이런 의도적인 줄바꿈 말고 한 줄이 길게 작성되지 않도록 다른 방법을 사용해 볼 수도 있을 것 같네요.
예를 들어 타입 캐스팅은 우선 상수에 할당한 뒤에 한다던지요!

2022-04-19 00:24 UTC, AppleCEO commented on Expo1900/Expo1900/Util/Extension/Int+Extension.swift
> +extension Int {
저는 이름이 그렇게 길다고 생각하지 않습니다.
긴 코드에 대한 안 좋은 생각이 많이 있는 것 같은데 불명확하고 짧은 코드보다 길고 명확한 코드(있어야할 곳에 코드들이 있는)가 좋은 코드라고 생각합니다~

2022-04-19 01:20 UTC, merged