만국박람회 [STEP 2] Donnie, Grumpy
yagom-academy/ios-exposition-universelle pull request #151
Opened 2022-04-15 06:31 UTC by westeastyear

안녕하세요 스티븐! 🙇🏻‍♂️🙇🏻‍♂️
@stevenkim18 

[STEP 2] PR 요청보냅니다!🙌
잘 부탁드리겠습니다.😄

## 🤔 고민한 점 & 해결한 방법
**1. 메인뷰의 제목을 원하는 부분에서 개행을 하기위해 고민하였습니다.** 
> => `insertNewLine()`함수를 새로 만들고 메인뷰의 제목 데이터를 매개변수로 받아서 원하는 위치`"("`앞에 `"\n"`을 넣어주어 해결하였습니다.

**2. 메인뷰에서 방문객, 개최지, 개최 기간의 `label`의 크기가 다르다고 생각하여 같은 문자열에서 다른 폰트크기를 주는 방법에 대해 고민하였습니다.**
> => 처음엔 별도의 `label`을 사용하는 방식을 채택했으나, `NSMutableAttributedString`의 `addAttribute()`함수를 활용하여 방문객, 개최지, 개최 기간이 적힌 부분에만 폰트 크기가 변경된 `alternativeFont`의 속성을 부여하는 방법으로 해결했습니다.
```swift
private func convertTextSize(of value: String, target: String) -> NSAttributedString {
        let alternativeFont = UIFont.systemFont(ofSize: 20)
        let attributedText = NSMutableAttributedString(string: value)
        attributedText.addAttribute(.font, value: alternativeFont, range: (value as NSString).range(of: target))
        return attributedText
    }
```

**3. 방문객의 `Int`값에 콤마를 넣어주기 위해 고민하였습니다.**
> => `insertComma()`함수 내에 `numberFormatter`를 구현하여 방문객`Int`을 매개변수로 받고 콤마를 추가하여 반환하는 형태로 구현하였습니다.

**4. 메인뷰에서는 `NavigationBar`가 안보여야하고 다음뷰에서 부터는 `NavigationBar`가 보여야 해서 이를 구현하기 위해 고민하였습니다.**
> => 메인뷰에서 `View`의 `LifeCycle`메서드를 활용하였습니다.
메인뷰가 `viewWillAppear`되면 `isNavigationBarHidden = true`을 하여 숨김처리를 하였습니다. 
다른 뷰에서는 `NavigationBar`가 보여야 하기에 메인뷰가 `viewWillDisappear`되면 `isNavigationBarHidden = false`을 하여 해결하였습니다.
```swift
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        self.navigationController?.isNavigationBarHidden = true
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        self.navigationController?.isNavigationBarHidden = false
    }
```

**5. `TableViewList`에서 `DetailView`로 전환될때 선택한 `Cell`의 데이터를 넘겨주는 방법을 고민하였습니다.**
> => 데이터를 받는 `ViewController`에서 미리 데이터를 담을 변수를 구현한 후, 데이터를 보내는 `ViewController`에서 `prepare(for segue: UIStoryboardSegue)`메서드를 구현하였고 이를 활용하여 해결하였습니다.

**6. `iOS15`부터 업데이트된 `NavigationBar`의 기본적으로 투명한 상태를 화면구현예시와 같은 불투명 상태로 설정하기 위해 고민하였습니다.**
> => `AppDelegate`에서 전체적으로 `NavigationBar`의 상태를 설정하기 위해 다음과 같은 코드를 작성하여 해결하였습니다.
```swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        let navigationBarAppearance = UINavigationBarAppearance()
        navigationBarAppearance.configureWithDefaultBackground()
        UINavigationBar.appearance().standardAppearance = navigationBarAppearance
        UINavigationBar.appearance().scrollEdgeAppearance = navigationBarAppearance
        return true
    }
```

## 🤔 궁금한 점
**1. 뷰 컨트롤러 사이의 데이터 전달**
> - 출품작 목록에서 출품작 상세화면으로 이동할 때, 상세화면에 표시할 내용을 전달하기 위해 해당 뷰 컨트롤러의 변수에 값을 할당하는 방법을 채택했습니다. 
> - 그러나 출품작 상세화면을 관장하는 뷰 컨트롤러에서 해당 값을 `private`으로 설정하지 못하게 되어 외부에서 값을 변경이 가능할 위험이 있다고 생각됩니다.😱
> - 이에 대해 스티븐의 생각이 궁금합니다. 

```swift
let entryDetailViewController = segue.destination as? EntryDetailViewController
            
entryDetailViewController?.detailDescription = entries[indexPath.row].description
entryDetailViewController?.imageName = entries[indexPath.row].imageName
entryDetailViewController?.koreanEntryTitle = entries[indexPath.row].name
```

**2. 에러 핸들링**
> - 이번 프로젝트를 진행하면서 `NSDataAsset(name:)`으로 불러올 파일이 없는 경우를 제외하면 에러가 발생할 상황이 없다고 생각해서 별도의 Error Handling을 하지 않았습니다. 
> - JSON 파싱할 때 매칭이 되지 않는 경우 `nil`을 반환하기 때문에 충분히 제어가 가능하다고 판단했는데요, 혹시 저희가 놓친 부분이 있을지 의견을 듣고 싶습니다.🤩

**3. 뷰 컨트롤러 내 상수 사용**
> - 프로그램 내에서 하드코딩을 지양하기 위해 상수를 사용하고자 노력했는데요, 어느 정도까지 상수로 생성해야 할 지 많은 고민을 했습니다. 
> - 자주 사용하는 `Identifier`나 특수 문자 같은 경우는 어려움이 없었으나 파일 이름이나 폰트 사이즈, "방문객"이나 "개최 기간" 같은 문자열까지 상수로 만들어야 할 지 나름대로의 기준을 잡는 게 무척 어려웠습니다.😂 
> - 스티븐이 생각하시기에 개선해야 할 점("이건 상수로 사용하는 것이 좋겠다"라고 생각하시는 것)이 있다면 알려주시면 감사하겠습니다! 그리고 스티븐이 생각하는 기준도 말씀해주시면 좋을 것 같아요.

**4. Naming**
> - 리팩토링 과정 진행 중 다음 세 함수의 이름을 어떻게 작성할 지 고민했습니다. 
> - "어떤 동작을 수행하는지"와 "어떤 결과물을 반환하는지"의 관점에 따라 명사형으로 지을 것인지 동사형으로 지을 것인지, 어떤 단어를 사용할 것인지가 정해진다고 생각하는데요.
> - 스티븐은 이런 함수 네이밍에 있어 어떤 부분을 중요하게 생각하시는지 의견을 듣고 싶습니다.🤔

```swift
private func insertNewLine(at value: String) -> String
private func insertComma(at value: Int) -> String
private func convertTextSize(of value: String, target: String) -> NSAttributedString
```

2022-04-18 04:51 UTC, stevenkim18 commented
도니 그럼피!! 스탭2까지 너무 수고 많으셨습니다.

고민한 흔적을 잘 적어주셔서 코드를 보기가 수월했습니다!

마크다운 문법을 아주 잘 사용하셔서 가독성이 올라가는 것 같아요! 너무 좋아요!!

한가지 아쉬운 부분은 PR 도입 부분에 두분이서 구현하신 UI를 사진이 gif로 보내주셨으면 더 훌룡한 PR이 되었을 것 같아요 ㅎㅎ 물론 프로젝트 요구사항에 보면 있긴 하지만 여기에 첨부해 주면 제가 따로 찾아보지 않아도 되기 때문에 더 좋았겠죠? ㅎㅎ 계속 너 나은 커뮤니케이션을 위해 노력해주세요!!(저한테도 적극적으로 물어봐주세요 ^^)

## 고민한점

**1. 메인뷰의 제목을 원하는 부분에서 개행을 하기위해 고민하였습니다.**

- 너무 잘 구현하셨습니다!!
- 저번 목요일에 구두로 말씀 드렸다 싶이 `insertNewLine()`함수가 뷰컨트롤러 안에 있어야 할 함수인지 다른 곳에 있어야 할 함수인지 더 고민해주세요!

**2. 메인뷰에서 방문객, 개최지, 개최 기간의 `label`의 크기가 다르다고 생각하여 같은 문자열에서 다른 폰트크기를 주는 방법에 대해 고민하였습니다.**

- 이 부분도 너무 잘 구현해주셨습니다.
- 기획의 큰 변동이 없다면 별도의 label을 사용하는 것도 방법이 되겠네요ㅎㅎ
- `convertTextSize` 함수가 20이 사이즈 밖에 줄 수 없는데 어떻게 하면 더 유연하게 할 수 있을 지 고민해주세요!
- 마찬가지고 이 함수도 꼭 여기에 있어야 할 함수인지도 고민해주세요!!

**3. 방문객의 `Int`값에 콤마를 넣어주기 위해 고민하였습니다.**

- `numberFormatter` 사용은 매우 잘하셨습니다.
- `insertComma` 함수가 매번 호출 될때 마다 `numberFormatter` 인스턴스가 매번 생성되어야 될까요? 한번만 호출 할 수 있는 방법은 없을까요?
- `insertComma` 함수도 뷰컨에 있어야 할 함수인지 고민해주세요!

**4. 메인뷰에서는 `NavigationBar`가 안보여야하고 다음뷰에서 부터는 `NavigationBar`가 보여야 해서 이를 구현하기 위해 고민하였습니다.**

- 매우 잘하셨습니다!
- 다른 방법은 없었나요?
- 지금 기획에서는 괜찮겠지만 메인 뷰컨에서 다른 화면으로 이동하는데 그 화면의 네비게이션바는 사라져야 되지 않는다면 어떻게 해결하실건가요?

**5.** **`TableViewList`에서 `DetailView`로 전환될때 선택한 `Cell`의 데이터를 넘겨주는 방법을 고민하였습니다.**

- 세그를 활용하셨네요!! 다른 방법은 고려해 보셨나요?

**6. `iOS15`부터 업데이트된 `NavigationBar`의 기본적으로 투명한 상태를 화면구현예시와 같은 불투명 상태로 설정하기 위해 고민하였습니다.**

- 오 이부분은 저도 처음 알았습니다!!

### 궁금한 점

**1. 뷰 컨트롤러 사이의 데이터 전달**

- 네 맞습니다. 이렇게 되면 두 뷰컨가 강하게 결합되어 있겠죠.
- title, imageName, description를 담는 데이터를 타입을 만들고 그 인스턴스를 넘겨주면 어떨까요? 그러면 private으로 할 수 있겠네요.

**2. 에러 핸들링**

- 지금은 로직이 간단해서 nil로도 처리 가능해 보입니다. 만약 로직이 복잡해 지면 오히려 throw로 던져서 애러를 관리하는 것이 편할 수도 있습니다.
- 코드를 돌려보니 `decodeExpositionContent()` 가 nil이면 화면에 아무것도 뜨지 않더라구요. 이럴때는 사용자에게 어떤 데이터를 보여주면 좋을까요?

**3. 뷰 컨트롤러 내 상수 사용**

- 저라도 “방문객", “개최기간" 같은 것은 그냥 상수로 따로 안뺐을 것 같아요.
- 변경되지 않는 문구는 스토리보드에서 구현해도 좋을 것 같습니다.
- 저도 자주 사용되는 문구나 기호는 따로 상수도 빼는데 그냥 한번만 쓰이면 바로 그 문구를 적는편입니다.

**4. Naming**

- 저는 보통 주체가 무엇인지를 살펴 봅니다. 클래스가 주체로 동작을 하게 되면 현재형 동사를 사용하고, 당하게 되면 수동태 동사를 사용합니다. 말씀하신 것 처럼 결과값이 중요하면 명사로 하는 경우도 있습니다.(그래도 대부분은 동사로 하는 것 같아요)

2022-04-18 14:05 UTC, stevenkim18 requested changes
도니 그럼피!! 코드에 댓글도 남겼습니다.

이해 안되시거나 애매한 것들이 있으시면 질문주세요!

2022-04-18 14:05 UTC, stevenkim18 commented on Expo1900/Expo1900/Controller/ExpositionMainViewController.swift
> +    @IBOutlet private weak var expoDescriptionLabel: UILabel!
expo로 줄이신 것을 매우 잘하셨습니다!!

하지만 이미 클래스 이름에 전시가 들어갑니다. 그러면 expo를 빼도 의미 전달되지 않을까요? 어떻게 생각하시나요?

2022-04-18 14:05 UTC, stevenkim18 commented on Expo1900/Expo1900/Controller/ExpositionMainViewController.swift
> +    private let leftParentheses: Character = "("
지금은 상수는 여기서만 쓰이지만 
프로퍼티가 많게 되면 나중에 유지보수하기 힘들어 집니다!! 

저는 상수들은 따로 빼는 편입니다.

2022-04-18 14:05 UTC, stevenkim18 commented on Expo1900/Expo1900/Controller/ExpositionMainViewController.swift
> +        let decoder = JSONDecoder()
decodeExpositionContent() 함수를 호출 할때 마다 JSONDecoder() 인스턴스가 생생되네요!! 어떻게 하면 인스턴스를 한번 생성할 수 있을까요?

2022-04-18 14:05 UTC, stevenkim18 commented on Expo1900/Expo1900/Controller/ExpositionMainViewController.swift
> +    }
`var result = value` 을 사용하신 것을 보니 이 함수는 다른 곳에 있어야 할 것 같네요!

extension을 활용해서 String에 구현하는 것은 어떨까요?

2022-04-18 14:05 UTC, stevenkim18 commented on Expo1900/Expo1900/Controller/ExpositionMainViewController.swift
> +    }
위에서도 언급했지만 여기도 NumberFormatter 인스턴스가 계속 만들어 지겠네요. 어떻게 하면 좋을까요?

2022-04-18 14:05 UTC, stevenkim18 commented on Expo1900/Expo1900/Controller/ExpositionMainViewController.swift
> +}
라이프 사이클 관련함수를 따로 뺴신 것은 매우 잘하셨습니다.

`//MARK: Life Cycle` 이런식으로 extension 위에 마크 주석을 사용해주면 더 좋을 것 같아요!!

2022-04-18 14:05 UTC, stevenkim18 commented on Expo1900/Expo1900/Controller/KoreanEntryViewController.swift
> +    }
여기서 더 확실하게 드러나네요!! ExpositionMainViewController 의 코드와 중복되네요!! 어떻게 하면 중복을 제거하고 한개의 decoder인스턴스를 만들 수 있을까요?

2022-04-18 14:05 UTC, stevenkim18 commented on Expo1900/Expo1900/Controller/KoreanEntryViewController.swift
> +    }
혹시 커스텀 cell은 만들어 보셨을까요??

2022-04-18 14:05 UTC, stevenkim18 commented on Expo1900/Expo1900/Controller/KoreanEntryViewController.swift
> +}
세그를 사용하신 이유가 있을까요? 화면을 전환하는 다른 방법에는 무엇이 있을까요?

2022-04-19 01:45 UTC, grumpy-sw commented on Expo1900/Expo1900/Controller/ExpositionMainViewController.swift
> +    @IBOutlet private weak var expoDescriptionLabel: UILabel!
expo를 뺀 이름으로 수정했습니다!

2022-04-19 01:49 UTC, westeastyear commented on Expo1900/Expo1900/Controller/ExpositionMainViewController.swift
> +    private let leftParentheses: Character = "("
`struct` 또는 `enum`으로 관리할 수 있다고 이해했습니다.
지금은 한번씩 밖에 사용되지 않아서 왠만하면 하드코딩식으로 작성하였습니다.

2022-04-19 01:59 UTC, grumpy-sw commented on Expo1900/Expo1900/Controller/ExpositionMainViewController.swift
> +    }
해당 함수는 `Exposition`내부에서 수행되도록 위치를 변경하였습니다!

2022-04-19 02:12 UTC, westeastyear commented on Expo1900/Expo1900/Controller/ExpositionMainViewController.swift
> +    }
`ExpositionMainViewController`에서 `numberFormetter`상수를 만들어주고 `static`을 붙여주어서 `Exposition`모델에서 접근할 수 있도록 하였습니다.

2022-04-19 02:15 UTC, grumpy-sw commented on Expo1900/Expo1900/Controller/ExpositionMainViewController.swift
> +}
넵! 적용하겠습니다.

2022-04-19 02:55 UTC, grumpy-sw commented on Expo1900/Expo1900/Controller/KoreanEntryViewController.swift
> +    }
코드의 중복을 피하기 위해 decode 기능을 관리하는 `parsingAssistant`를 만들어서 값을 받도록 했습니다.

2022-04-19 08:00 UTC, westeastyear commented on Expo1900/Expo1900/Controller/KoreanEntryViewController.swift
> +    }
`customCell`로 수정해보았습니다.

2022-04-19 08:04 UTC, grumpy-sw commented on Expo1900/Expo1900/Controller/ExpositionMainViewController.swift
> +        let decoder = JSONDecoder()
decode를 도와주는 어떤 것이 존재하고 필요할 때마다 그에게 요청한다면, 인스턴스를 반복적으로 생성하는 불필요한 일을 피할 수 있을 것 같습니다

2022-04-19 08:05 UTC, westeastyear commented on Expo1900/Expo1900/Controller/KoreanEntryViewController.swift
> +}
화면을 전환하는 방법에는 `present`와, `push`가 있습니다.
기능구현예시에서 `navigation`을 사용하였기에 `navigation`으로 `push`하여 화면을 전환하였고, 스토리보드를 사용하여 프로젝트를 하고 있기 때문에 충분히 활용할 수 있는 `prepare(for segue)`를 활용해 보았습니다.

2022-04-19 08:07 UTC, westeastyear commented on Expo1900/Expo1900/Controller/ExpositionMainViewController.swift
> +        let decoder = JSONDecoder()
아래에서 댓글 남겼습니다!

2022-04-20 13:38 UTC, stevenkim18 commented on Expo1900/Expo1900/Controller/ExpositionMainViewController.swift
> +    private let leftParentheses: Character = "("
나중에 코드가 많아지면 원하는 프로퍼티를 찾기 힘들까요? 같은 파일에 `fileprivate` enum으로 빼시는건 어떤가요?

2022-04-20 13:52 UTC, stevenkim18 commented on Expo1900/Expo1900/Model/Exposition.swift
> +    }
이렇게 사용하시는 거면 연산프로퍼티가 좋지 않을까요?

2022-04-20 13:52 UTC, stevenkim18 commented on Expo1900/Expo1900/View/KoreanEntryCell.swift
> +}
이렇게 커스텀 셀을 만들어서 셀에서 하게 해주신것은 매우 잘하셨습니다.

이것도 위에서 처럼 하나의 모델을 매개변수로 넘겨주어도 좋겟네요

2022-04-20 13:52 UTC, stevenkim18 commented on Expo1900/Expo1900/Controller/ParsingAssistant.swift
> +}
와우 제네릭을 사용하셔서 바깥으로 빼신 것은 매우 잘하셨습니다!!

저라면 싱글톤으로 인스턴스를 관리해주는 것도 고려해 볼 것 같아요!

2022-04-20 13:52 UTC, stevenkim18 commented on Expo1900/Expo1900/Controller/KoreanEntryViewController.swift
> +                                               koreanEntryTitle: entries[indexPath.row].name)
`entries[indexPath.row]`가 반복되네요.
따로 지역변수로 빼주어도 좋을 것 같아요!

2022-04-20 13:53 UTC, stevenkim18 commented on Expo1900/Expo1900/Controller/KoreanEntryViewController.swift
> +}
지금은 뷰가 단순해서 세그를 사용해도 좋지만 뷰컨들의 관계가 복잡해지면 잘 사용하지 않는 것 같습니다!!

2022-04-20 13:53 UTC, stevenkim18 commented on Expo1900/Expo1900/Controller/ExpositionMainViewController.swift
> +    }
`numberFormetter` 도 싱글톤으로 관리해주면 어떨까 싶네요 ㅎㅎ 그래도 잘하셨습니다!

2022-04-21 01:48 UTC, grumpy-sw commented on Expo1900/Expo1900/Model/Exposition.swift
> +    }
연산 프로퍼티 사용 시 infinite recursion 경고를 확인했고, 방문객의 경우 decode된 `Int` 타입을 `String` 타입으로 변경해주어야 하기 때문에 별도의 프로퍼티를 생성해야 했습니다.
Json에 없는 프로퍼티를 생성하기보다는 함수로 변환한 값을 반한해주는 것이 더 좋다고 판단하여 함수로 작성했습니다.

2022-04-21 01:49 UTC, grumpy-sw commented on Expo1900/Expo1900/Controller/ParsingAssistant.swift
> +}
싱글톤도 좋은 방법인 것 같습니다 :)

2022-04-21 01:54 UTC, grumpy-sw commented on Expo1900/Expo1900/Controller/KoreanEntryViewController.swift
> +                                               koreanEntryTitle: entries[indexPath.row].name)
`let entry = entries[indexPath.row]` 로 지역상수로 사용했습니다!

2022-04-21 02:38 UTC, westeastyear commented on Expo1900/Expo1900/View/KoreanEntryCell.swift
> +}
`CellContent` 모델을 생성하여 넘겨주는 방식으로 수정하였습니다.

2022-04-22 01:47 UTC, merged