만국박람회 [STEP 2] Malrang, Cathy
yagom-academy/ios-exposition-universelle pull request #152
Opened 2022-04-15 12:03 UTC by malrang-malrang

안녕하세요 린생! @jungseungyeo 
Step2 PR 잘부탁드립니다! :)

Step2 는 오토레이아웃은 설정이 되어있지 않아 코드가 잘 작동이되는지 린생이 확인하시기에 조금 불편할수 있을것같아요 ㅠ
최대한 오토레이아웃까지도 적용시켜보려 했으나..어디를 어떻게해야할지 모르겠는 부분이 투성입니다ㅠㅠ 
오토레이아웃 부분은 Step3 에서 더 공부해서 적용해보도록 하겠습니다! 

## 고민했던것, 조언을 받고싶은 부분

**1. `Custom Cell`을 `EntryListViewController` 와 다른 파일에서 구현할 경우 인식하지 못하는 문제**
>파일 분리를 하기위해  `Cell` 을 다른 파일에서 구현했더니 스토리보드에서 인식하지못하는 상황이 발생했습니다.
>`EntryListViewController: UIViewController` 내부에서 사용될 `Cell` 이기때문에 EntryListViewController 와 같은 파일 내에서 구현해주어야 하는걸까요~?
```swift
final class CustomCell: UITableViewCell {
    @IBOutlet weak var itemImage: UIImageView!
    @IBOutlet weak var itemTitle: UILabel!
    @IBOutlet weak var itemShortDiscription: UILabel!
}
```
**2. tableView의 `dequeueReusableCell` 메서드에서 재사용이 가능한 `cell`을 반환할 때 만약 등록된 `cell`이 없다면 `CustomCell()`을 반환하도록 해주었는데 맞게한 것인지 여쭤보고 싶습니다.**
```swift
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell: CustomCell = tableView.dequeueReusableCell(withIdentifier: Exposition.customCell, for: indexPath) as? CustomCell ?? CustomCell()
        let item = expositionItems?[indexPath.row]
        cell.imageView?.image = UIImage(named: item?.imageName ?? Exposition.emptyImage)
        cell.itemTitle.text = item?.name
        cell.itemShortDiscription.text = item?.shortDescription
        return cell
    }
```

2022-04-16 02:11 UTC, jungseungyeo requested changes
말랑, 캐시 고생하였습니다 :) 

### 1. Custom Cell을 EntryListViewController 와 다른 파일에서 구현할 경우 인식하지 못하는 문제

`파일을 분리하였지만 타켓과 참조가 걸려있지 않으거 같아요. 파일을 만들떄 참조와 타켓설정을 해주세요 :) `

### 2. tableView의 dequeueReusableCell 메서드에서 재사용이 가능한 cell을 반환할 때 만약 등록된 cell이 없다면 CustomCell()을 반환하도록 해주었는데 맞게한 것인지 여쭤보고 싶습니다.

`큰 문제는 없어보이지만 주로 guard문으로 하는 편입니다. guard를 사용해서 특정 조건을 완료후 실행하는 절차를 가지게 작성을 하는 스타일이 많습니다. :) `

말랑, 캐시 고생하셨습니다. 리뷰를 하면서 몇가지 수정 상황이 있어서 글을 남깁니다.

1. 파일의 위치 
`- 질문 1번과 같이 파일을 따로 생성하는 경우 타켓과 참조가 설정이 안되어 있어요. 파일을 만들때 어느 프로젝테 어떻게 참조를 걸지 표시가 나오죠? 이러 부분을 보면서 작성하면 좋을거같아요. `
![image](https://user-images.githubusercontent.com/32052386/163657555-839dcfe9-93c8-4c69-bb4c-113449038029.png)

2. MVC 패턴을 지키면서 작성

`파일이나 위치는 MVC패턴이 맞으나 model을 업데이트 되면 Controller에게 노티를 주는 부분이 존재하지 않아요. 이 부분이 가능하게 작성을 해주시면 좋을거같아요. 또 model을 가져오는 부분과 ui에 바인딩하는 부분을 분리하여 작성하면 좋을거같아요.`

3. 캡슐화
`캡슐화의 데이터 은닉화에 있습니다. 은닉화를 지키기위해서는 접근제어자로 private을 사용하여 작성하는게 기본 원칙입니다. 지금 작성한 코드는 대부분 위반을 하고 있어서 캡슐화를 지키면서 작성을 해주시면 좋을거같습니다. :) `

말랑 캐시 위의 리뷰를 보시고 수정해주시면 좋을거같아요. 궁금한점이 있다면 언제든지 물어봐주세요

2022-04-16 02:11 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        cell.imageView?.image = UIImage(named: item?.imageName ?? Exposition.emptyImage)
`cell.itemView?.image` 이 처럼 데이터를 넣는다면 캡슐화를 위반하게 되는거 같아요. 캡슐화를 지키게 수정하면 좋을거같아요.

2022-04-16 02:11 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/ExpositionPosterViewController.swift
> +        let poster = ExpositionPoster.parse(JsonFile.poster)
모델을 받는 부분과 데이터를 ui에 바인딩 하는 부분을 분리하면 좋을거같아요.

2022-04-16 02:11 UTC, jungseungyeo commented on Expo1900/Expo1900/View/mycellTableViewCell.swift
> +class mycellTableViewCell: UITableViewCell {
이 파일은 참조가 안걸려있네요 사용하지 않는 파일은 삭제해주세요 :)

2022-04-16 02:11 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/ExpositionPosterViewController.swift
> +        let poster = ExpositionPoster.parse(JsonFile.poster)
ExpositionPosterViewController <- 이 패턴이 MVC패턴을 지키고 있나요? MVC를 지키면서 작성을 해주세요 :)

2022-04-16 02:11 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +final class CustomCell: UITableViewCell {
네이밍이 CustomCell이면 안될거같아요. 네이밍만 보고도 무슨 cell인지 알수있으면 좋을거같아요.

2022-04-16 02:11 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +            entryItemViewController.item = item
위와 같이 넣어주면 캡슐화를 위반하는거죠? ㅎㅎ 캡슐화를 지키면서 작성해주세요 :)

2022-04-16 02:11 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +    let expositionItems = [ExpositionItems].parse(JsonFile.items)
접근제어자가 private으로 작성해주세요 :)

2022-04-16 02:11 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryItemViewController.swift
> +    var item: ExpositionItems?
접근제어자 private으로 하여 은닉화를 해주세요 :)

2022-04-16 02:11 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/CustomCell.swift
> +class CustomCell: UITableViewCell {
이 파일도 참조가 안걸려있네요 파일 정리 부탁드립니다.

2022-04-16 02:11 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/Exposition.swift
> +enum Exposition {
위와 같이 작성하는 형태 좋습니다 하지만 파일 위치는 고민 할 포인트가 있네요. 한 곳에서 정리 하는 것보다 사용하는 곳에서 가지고 있는게 좋지 않을까라는 생각을 하는데 어떤가요?

2022-04-18 15:24 UTC, malrang-malrang commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        cell.imageView?.image = UIImage(named: item?.imageName ?? Exposition.emptyImage)
확실히 캡슐화와 은닉화에 대해 고려하지 않았던것 같습니다!
현재는`EntryListViewController: UITableViewDataSource` 에서 `EntryCell` 의 프로퍼티에 접근해 값을 변경해주었는데 
린생의 조언대로 수정하니`tableView cellForRowAt` 메서드도 보기좋아진것 같습니다! :)

2022-04-18 15:24 UTC, ghost commented on Expo1900/Expo1900/Controller/Exposition.swift
> +enum Exposition {
넵 Exposition 네임스페이스를 사용하는 파일로 각각 분리해주었습니다.
namespace가 여러번 반복되는 부분이 있어서 각 파일마다 명시를 해주었는데, 가독성 측면에서는 좋아보이지만 이렇게 매번 적어주는 것이 좋은 방법인지 궁금합니다..!

2022-04-18 15:24 UTC, malrang-malrang commented on Expo1900/Expo1900/View/mycellTableViewCell.swift
> +class mycellTableViewCell: UITableViewCell {
네! 파일을 제거하는 방법에도 참조만 제거하는게 있고 참조 파일 모두 제거하는게 있다는걸 알게되었습니다! 😀

2022-04-18 15:25 UTC, cathy171 commented on Expo1900/Expo1900/Controller/CustomCell.swift
> +class CustomCell: UITableViewCell {
넵 수정하였습니다!

2022-04-18 15:26 UTC, cathy171 commented on Expo1900/Expo1900/Controller/EntryItemViewController.swift
> +    var item: ExpositionItems?
넵 private으로 은닉화해주었습니다!

2022-04-18 15:26 UTC, cathy171 commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +    let expositionItems = [ExpositionItems].parse(JsonFile.items)
동일하게 private으로 은닉화해주었습니다!

2022-04-18 15:28 UTC, malrang-malrang commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +            entryItemViewController.item = item
네! 이부분도 위와 같이 캡슐화를 고려하지 않았던 부분인것 같아요!
`entryItemViewController` 의 프로퍼티인 `item`에 직접 접근하여 데이터를 넘겨주는 방식은 좋지 못한것같습니다!
entryItemViewController 에서 타입 메서드를 이용해 파라미터로 `item` 을 받아 자기 자신의 타입을 반환하는 방법은 앞으로도 유용하게 사용할것 같습니다! 조언해주셔 감사합니다 :)

2022-04-18 15:29 UTC, malrang-malrang commented on Expo1900/Expo1900/Controller/EntryItemViewController.swift
> +    var item: ExpositionItems?
네! 은닉화 캡슐화! 항상 신경쓰도록 하겠습니다!

2022-04-18 15:30 UTC, malrang-malrang commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +final class CustomCell: UITableViewCell {
네! 어떤것을 담을 cell 인지 현재 네이밍으로는 명확하지 않은것 같습니다!
수정하도록 하겠습니다! :)

2022-04-19 02:14 UTC, malrang-malrang commented on Expo1900/Expo1900/Controller/ExpositionPosterViewController.swift
> +        let poster = ExpositionPoster.parse(JsonFile.poster)
네! 해당 부분 조언해주신데로 수정해보았습니다! :)

2022-04-20 15:11 UTC, jungseungyeo approved these changes
말랑, 캐시 

너무 고생하셨어요.

제가 의도한 대로 잘 작성되었네요 ㅎㅎ
MVC패턴은 파일을 분리하는 것도 중요하지만 각 역할별로 이벤트를 전달하는 것도 중요합니다.

2022-04-20 15:11 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryCell.swift
> +    func configure(item: ExpositionItems?) {
너무 좋습니다 데이터를 전달하는 것을 잊지말아주세요 :)

2022-04-20 15:11 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryItemViewController.swift
> +    static func instance(item: ExpositionItems?) -> EntryItemViewController? {
디코에서 이야기 한 거 처럼 잘 적용한거 같아요 ㅎㅎ

2022-04-20 15:11 UTC, jungseungyeo commented on Expo1900/Expo1900/Utils/Int+Extension.swift
> +    static func numberFormatter(by inputText: Int?) -> String? {
네이밍 좋네요 ㅎㅎ

2022-04-20 15:11 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/ExpositionPosterViewController.swift
> +    @IBOutlet private weak var descriptions: UILabel!
접근제어자를 붙여주는 습관 너무 좋습니다

2022-04-20 15:11 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/ExpositionPosterViewController.swift
> +        poster = ExpositionPoster.parse(JsonFile.poster)
함수로 분리하면 더욱 좋았을거같아요. 이렇게 생성하는 것도 좋네요 ㅎㅎ

2022-04-20 15:11 UTC, merged

2022-04-20 15:18 UTC, malrang-malrang commented on Expo1900/Expo1900/Controller/EntryCell.swift
> +    func configure(item: ExpositionItems?) {
네! 이런 방법 너무 좋은것 같습니다! :)
잊지않고 다른 프로젝트에서도 적용해보도록 하겠습니다!!

2022-04-20 15:18 UTC, malrang-malrang commented on Expo1900/Expo1900/Controller/EntryItemViewController.swift
> +    static func instance(item: ExpositionItems?) -> EntryItemViewController? {
이런방법으로 item 프로퍼티를 접근제어 걸어줄수 있을거란 생각을 못했습니다! 
앞으로도 유용할것같아요!

2022-04-20 15:20 UTC, malrang-malrang commented on Expo1900/Expo1900/Controller/ExpositionPosterViewController.swift
> +    @IBOutlet private weak var descriptions: UILabel!
private 가 기본..!
린생덕분에 pop, oop 에대해 좀더 고민할수 있었던것 같습니다!

2022-04-20 15:22 UTC, malrang-malrang commented on Expo1900/Expo1900/Controller/ExpositionPosterViewController.swift
> +        poster = ExpositionPoster.parse(JsonFile.poster)
음..그렇군요! 모델의 데이터를 업데이트 하는 부분을 따로 함수에 넣어주는편이 좋았을까요~~?