만국박람회 [Step3] Taeangel, dudu
yagom-academy/ios-exposition-universelle pull request #155
Opened 2022-04-19 08:07 UTC by FirstDo

안녕하세요 린생 @jungseungyeo !!
만국박람회 STEP3 PR보냅니다 :)
지금까지 린생이 디코와 PR에서 많이 도와주셔서 정말 많이 배웠습니다!!
감사합니다 !!!!!!!!!!

### 구현한점

#### DetailkView와 HeritageView의 좌우 layout수정
safeAreaLayoutGuide로 제약을 변경
#### label의 DynamicType 적용
```swift
label.adjustsFontForContentSizeCategory = true
```
#### cell deselect
```swift
tableView.deselectRow(at: indexPath, animated: true)
```
#### StackView의 Margin
```swift
baseStackView.directionalLayoutMargins = .init(top: Const.Stack.margin, leading: Const.Stack.margin, bottom: Const.Stack.margin, trailing: Const.Stack.margin)
    baseStackView.isLayoutMarginsRelativeArrangement = true
```
#### navigationBar Custom
```swift=
let navigationAppearance = UINavigationBarAppearance()
navigationAppearance.configureWithDefaultBackground()
UINavigationBar.appearance().standardAppearance = navigationAppearance
UINavigationBar.appearance().compactAppearance = navigationAppearance
UINavigationBar.appearance().scrollEdgeAppearance = navigationAppearance
 
```
#### 특정화면 portrait고정
```swift
 private func fixDevice(orientation: UIDeviceOrientation) {
    let value = orientation.rawValue
    UIDevice.current.setValue(value, forKey: Const.Device.orientation)
  }
```
#### 오류 alert구현
```swift
extension UIViewController {
  
  func showAlert(errorMessage: String) {
    let alertController = UIAlertController(title: Const.Alert.title, message: errorMessage, preferredStyle: .alert)
    let alertAction = UIAlertAction(title: Const.Alert.okAction, style: .default)
    alertController.addAction(alertAction)
    present(alertController, animated: true)
  }
}
```

### 궁금한점

#### 모델을 parse하는 곳의 위치

기존 Decodable Extension으로 하던 것을 아예 삭제하고, Controller의 request() 매서드에서 직접 요청하는 느낌으로 바꿨습니다 

```swift
private func request(name: String, completion: (Result<Expo, ParseError>) -> Void) {
    guard let data = NSDataAsset(name: name)?.data else {
      completion(.failure(.invalidName))
      return
    }
    do {
      let decodedData = try JSONDecoder().decode(Expo.self, from: data)
      completion(.success(decodedData))
    } catch {
      completion(.failure(.decodeFail))
    }
}
```

실제 사용

```swift
request(name: Const.File.name) { result in
  switch result {
  case .success(let data):
    expo = data
  case .failure(let error):
    showAlert(errorMessage: error.localizedDescription)
  }
}
```

이렇게 하니까, request매서드를 사용하는 모든 VC마다 코드를 다 작성해주어야 하던데, 저희가 피드백을 제대로 이해한것이 맞나요 ㅠㅠ ?

기존 코드에서 Decodable의 extension으로 하던게 NetworkManager의 역할처럼 동작한다고 생각해서, 그곳에 모든 코드를 작성하였습니다(completion 클로져 포함..)
그곳에 작성되있다고 Model에서 직접 결과를 내는것은 아니지 않나요?

아래처럼 동작한다고 생각 해서 Decodable extension에 모든 코드를 작성한 것이었습니다
```swift
struct NetworkManager {
    static func download(url: String, completion: (Result<Item, MyError>) -> Void) {
        
        // ... 대충 데이터 다운로드
        
        //성공
        completion(.success(data))
        //실패
        completion(.failure(.netWorkError))
    }
}
```

#### 특정 ViewController만 세로로 표시하는 방법

찾아보니 `supportedInterfaceOrientations` 를 override 하라는데, 아무리 해도 안되더라구요 ㅠㅠ..
문서를 읽어보니, NavigationController 같은 곳에 embed되어 있을때는 무조건 NavigationController 기준으로 동작한다고 나와있었습니다.

그래서 CustomNavigationController를 만들고, 거기서 해당 프로퍼티를 오버라이딩했습니다

//topVC가 첫번째 VC라면 .portrit만!
//아니면 .all

```swift
class ExpoNavigationController: UINavigationController {
  override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
    if self.topViewController as? ExpoViewController == nil {
      return .all
    } else {
      return .portrait
    }
  }
}
```

근데 이렇게 까지만 하니까 두번째 VC에서 landscape모드인 상태에서,
첫번째 VC로 화면전환을 하니깐 portrait로 고정되어야 할 첫번째 VC에서 landscape모드로 보이는 현상이 발생했습니다

두번째 VC
![](https://i.imgur.com/zAAyZ8Z.png)

pop

첫번째 VC
![](https://i.imgur.com/5i3Rb5B.png)

다음과 같은 코드를 첫번째 VC의 viewWillAppear에 넣어서 해결하기는 했는데 이 방법 괜찮은지? 일반적인 방법인지 궁금합니다

```swift
  private func fixDevice(orientation: UIDeviceOrientation) {
    let value = orientation.rawValue
    UIDevice.current.setValue(value, forKey: Const.Device.orientation)
  }
```

2022-04-20 15:42 UTC, jungseungyeo requested changes
두두, 태엔절 고생하셨습니다 :) 

### 궁금한점 

### 모델을 parse하는 곳의 위치

`잘 적용을 한게 맞습니다. 주로 모델을 매핑하는 것을 비동기 로직으로 동작하고 실패, 성공여부는 비지니스로직을 담당하는 곳에서 구현하는 편입니다. 이부분을 전에 코드에서 model하고 있어서 수정을 요청한 것였습니다. :) 제 의도와 맞게 잘 구현했습니다.`

### NetworkManager

`맞습니다. NetworkManager 이런 부분이 있다면 여기서 작성을 해야겠죠. 이 부분을 디자인 패턴에서 레파지토리 패턴이라고 존재합니다. https://eunjin3786.tistory.com/198 이 블로그를 참조하면 좋을거같아요`

### 특정 ViewController만 세로로 표시하는 방법

`맞아요 이부분 상위 뷰를 따라가게 되어있어요. 그래서 가로모드 세로모드를 따로 하고 싶다면 작성한 부분처럼 해야되는 문제가 있습니다. ㅠㅠ`

### 두번째 VC, 첫번째 VC

`주로 상위 뷰를 만들어서 supportedInterfaceOrientations 를 오버라이딩해서 사용하는 편입니다. 이 부분은 따로 flag를 만들어서 적용도 하는 편이예요. UIDevice.current.setValue(value, forKey: Const.Device.orientation)를 하는 방식은 사용하지 않는 편입니다. ㅠㅠ 이 부분은 수정하면 좋을거같습니다.`

두두, 태엔젤 너무 고생하셨습니다. 코멘트 단 부분을 수정하고 제 욕심이지만 에러부분에서 alert을 구현한 부분을 protocol을 활용하여 중복코드를 제거하면 더욱 좋을거같아요 이부분도 수정해주세요 :)

2022-04-20 15:42 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/ExpoViewController/ExpoViewController.swift
> +        showAlert(errorMessage: error.localizedDescription)
에러처리 너무 좋습니다 :)

2022-04-20 15:42 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/ExpoViewController/ExpoViewController.swift
> +    UIDevice.current.setValue(value, forKey: Const.Device.orientation)
이거는 주로 shouldAutorotate이거나, supportedInterfaceOrientations를 오버라이딩해서 사용하는 편입니다. :)

2022-04-20 15:42 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/ExpoViewController/ExpoViewController.swift
> +  private func request(name: String, completion: (Result<Expo, ParseError>) -> Void) {
컨트롤로에서 작성해서 너무 좋습니다 :) 이렇게 요청후 에러처리 혹은 mapping 작업은 controller가 하는게 MVC패턴에서 비지니스 로직이 controller에게 적용하는 거라고 이해하면 좋을거같아요.

2022-04-20 15:42 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/HeritageDetailViewController/HeritageDetailView.swift
> +      baseScrollView.trailingAnchor.constraint(equalTo: safeAreaLayoutGuide.trailingAnchor)
코드베이스로 작성하여 바로바로 오토레이아웃을 적용이 빠르네요 ㅎㅎ

2022-04-20 15:42 UTC, jungseungyeo commented on Expo1900/Expo1900/Extention/UIViewController+.swift
> +  func showAlert(errorMessage: String) {
extension으로 작성하는거 너무 좋아요 하지만 더 좋은 방법이 있을거같아요. protocol을 사용하여 공통적으로 적용하는 역할을 만들어보면 좋을거같아요.

2022-04-20 15:42 UTC, jungseungyeo commented on Expo1900/Expo1900/Scene/AppDelegate.swift
> +      UINavigationBar.appearance().scrollEdgeAppearance = navigationAppearance
이부분은 공통으로 적용하는 rootnavigation에서 적용하면 좋을거같아요.

2022-04-20 15:42 UTC, jungseungyeo commented on Expo1900/Expo1900/Model/ParseError.swift
> +enum ParseError: Error {
CustomError 너무 좋아요 ㅎㅎ

2022-04-21 00:44 UTC, Taeangel commented on Expo1900/Expo1900/Extention/UIViewController+.swift
> +  func showAlert(errorMessage: String) {
```swift 

protocol Alertalble {
  func showAlert(errorMessage: String, viewController: UIViewController)
}

extension Alertalble {
  func showAlert(errorMessage: String, viewController: UIViewController) {
    let alertController = UIAlertController(title: Const.Alert.title, message: errorMessage, preferredStyle: .alert)
    let alertAction = UIAlertAction(title: Const.Alert.okAction, style: .default)
    alertController.addAction(alertAction)
    viewController.present(alertController, animated: true)
  }
}

```
이와같이 protocol을 사용하여 변경하였습니다.

2022-04-21 00:45 UTC, FirstDo commented on Expo1900/Expo1900/Scene/AppDelegate.swift
> +      UINavigationBar.appearance().scrollEdgeAppearance = navigationAppearance
RootNavigationController에서 다음과 같이 적용해 주었습니다 :)

```swift
  override init(rootViewController: UIViewController) {
    super.init(rootViewController: rootViewController)
    attribute()
  }

  private func attribute() {
    let navigationAppearance = UINavigationBarAppearance()
    navigationAppearance.configureWithDefaultBackground()
    navigationBar.standardAppearance = navigationAppearance
    navigationBar.compactAppearance = navigationAppearance
    navigationBar.scrollEdgeAppearance = navigationAppearance
  }
```

2022-04-21 01:55 UTC, Taeangel commented on Expo1900/Expo1900/Controller/ExpoViewController/ExpoViewController.swift
> +    UIDevice.current.setValue(value, forKey: Const.Device.orientation)
```swift 
override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
    return .portrait
  }
```
```swift
 override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
    return self.topViewController?.supportedInterfaceOrientations ?? .all
  }
 ```
supportedInterfaceOrientations를 오버라이딩하여 변경하였습니다.

2022-04-21 01:59 UTC, FirstDo commented on Expo1900/Expo1900/Controller/ExpoViewController/ExpoViewController.swift
> +    UIDevice.current.setValue(value, forKey: Const.Device.orientation)
![화면전환에러](https://user-images.githubusercontent.com/69573768/164356437-e06a895e-00a6-40e1-8927-99acdeade7b0.gif)

2022-04-21 11:10 UTC, jungseungyeo commented on Expo1900/Expo1900/Scene/AppDelegate.swift
> +      UINavigationBar.appearance().scrollEdgeAppearance = navigationAppearance
좋습니다 :)

2022-04-21 12:20 UTC, jungseungyeo approved these changes
두두, 태엔젤 고생하셨습니다. 

이번 스탭을 delegate, datasource의 대한 이해하고 코드베이스로 ui를 작성하는 것을 잘해주셨습니다. ㅎㅎ
Alertable이라는 프로토콜을 확장하여 작성을 하였는데 이 부분을 잊지 말아주세요 고생하셨습니다.

2022-04-21 12:20 UTC, jungseungyeo commented on Expo1900/Expo1900/Protocol/Alertable.swift
>    func showAlert(errorMessage: String, viewController: UIViewController) {
너무 좋아요 ㅎㅎ 하지만 where절을 써서 조건을 주면 더욱 좋을거같아요 :) 그러면 viewController를 받지 않아도 될거같아요

2022-04-21 12:20 UTC, merged