만국 박람회 [STEP 3] mmim, Minseong
yagom-academy/ios-exposition-universelle pull request #157
Opened 2022-04-20 14:35 UTC by JoSH0318

@AppleCEO 안녕하세요! 도미닉!👑
만국박람회 STEP3 PR 입니다!
이번에도 잘 부탁드립니다.😉

---
## 고민 및 해결한 점

1️⃣ 첫 화면 세로로 고정
<img width="500" src= "https://i.imgur.com/JyHjRqA.png"/>
- Deployment Info에서 Device Orientation을 통해 원하는 회전 방법을 선택해주었습니다.
- 위 방법은 디바이스 화면 전체에 영향을 줌
- 이 때, 원하는 화면에서만 세로모드만 지원하는 것처럼 특정 orientation값을 갖게 해주고 싶었습니다.
- UIInterfaceOrientationMask를 이용하면 원하는 view에서의 orientation을 코드로 바꿔줄 수 있다고 생각했습니다.
>아래 메서드와 화면의 위치를 알려줄 flag를 이용해 첫 번째 화면에서만 세로 값을 할당하여 문제를 해결해 주었습니다.
```swift
func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask
```

2️⃣ 하나의 label에 두 개의 다른 Font
<img width="500" src= "https://i.imgur.com/w1PXlug.png"/>

- 처음에는 한 줄에 다른 폰트를 표현하기 위해 위의 예시처럼 두개의 label를 horizontal stackView에 넣어주었습니다. 
- 하지만 이런 방법으로 했을 경우, Dynamic Type을 적용했을 때 각 label마다 다른 기준으로 글자가 커졌습니다. 그로 인해 필요없는 공백이 생기고, 사용자가 받아드리기에 불편한 텍스트가 출력되는 문제가 생겼습니다.
>하나의 label에 다른 성격의 두 Font가 존재하면 문제를 해결할 수 있다고 생각했고, NSMutableAttributedString을 통해 해결할 수 있었습니다.
>UILable Extension을 통해 필요한 Label에서 downSize()메서드를 사용하여 문제를 해결하게끔 만들어 해결해 주었습니다
```swift
func downSize(targetString: String) {
        let font = UIFont.preferredFont(forTextStyle: .body)
        let fullText = self.text ?? ""
        let range = (fullText as NSString).range(of: targetString)
        let attributedString = NSMutableAttributedString(string: fullText)
        attributedString.addAttribute(.font, value: font, range: range)
        self.attributedText = attributedString
}
```
3️⃣ AutoLayout - image
- image view에 AutoLayout을 적용함에 있어서 원하는 image의 크기, 비율이 출력되지 않았습니다.
- Aspect To Fit은 비율은 유지되고 imageView밖으로 사진이 나가지 않는 선에서 최대치 값을 갖습니다. 아래 그림과 같이 iamgeView에 크기를 정하게 되면 사진은 비율을 헤치지 않는 선에서 최대치 값을 갖습니다. 그렇다면 남게 되는 영역이 생기는데 에러가 생기지 않는 것에 의문이 생겼습니다. 
<img width="500" src= "https://i.imgur.com/ehoFplS.png"/>
- image view에 공백이 있는 것을 backgroundColor를 주어서 남은 영역은 공백으로 채우게 되고 image 자체가 공백과 합쳐진다는 것을 알았습니다.
>Scale to fill / Aspect to fit / Aspect to fill의 차이점을 찾는 것을 시작으로 적절한 방법을 사용하는 것을 통해 문제를 해결했습니다.

4️⃣ AutoLayout - stackView > Distribution > fill
- stackView > Distribution > fill을 적용했을 때 마지막 stack이 남은 비율을 꽉채우는 현상이 생겼고, 공백 부분에 컨텐츠가 채워지는 오류가 생겼습니다.
- fill은 가능한 공간을 채우도록 크기를 조정하는 특징을 가졌고, arranged view들의 크기가 넘어가면 compression resistance priority에 따라 뷰가 축소 / 공간이 남는다면 hugging priority에 따라 뷰가 늘어난다는 사실을 확인했습니다.
<img width="200" src= "https://i.imgur.com/3kmbbL7.jpg"/>
- 이번 프로젝트의 경우 공간이 남기 때문에 hugging priority에 따라 뷰가 늘어납니다. 때문에 hugging priority가 가장 낮은 마지막 arranged view(stack)가 늘어납니다. 
> hugging priority가 가장 낮은 마지막 arranged view(stack)에 높이를 줌으로써 늘어나는 것을 방지했고, 이를 통해 해결했습니다.

---

## 궁금한 점 및 질문사항 
1️⃣ ExhibitionItemsView Cell AutoLayout
- titleLabel과 subtitleLabel "missing Constraints" 문제
- titleLabel과 subtitleLabel를 스택뷰 안에 넣어주었습니다, 높이에 대한 문제가 자꾸 발생을 하는 것 같아 높이에 대한 Constraints를 주었는데도 다시 또 나타났습니다ㅠ 어떤 점 때문에 자꾸 높이를 못잡는건지 확인하지 못하였습니다

2️⃣ AutoLayout
- auto layout의 빨간색 오류를 전부 해결했지만, 간혹 다시 오류가 생기고, 다시 없어지기를 반복합니다. 아무런 변경사항이...없는데 말이죠 🤔
- 이런 현상을 미흡한 제약조건으로 인한 현상으로 바라봐야할 지, 단순 XCode 오류로 봐야할지 궁금합니다 😭

3️⃣ 
autoLayout에 대한 부분은 글로써 무언가를 질문하거나 말하는게 어려운 것 같습니다 ㅠㅠ
혹시 시간이 괜찮으시다면 회의실을 통해 autoLayout에 대해 질문을 드려도 될까요??

2022-04-21 01:30 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
@JoSH0318 , @Minseong-yagom 고생하셨습니다!
3가지 질문 다 댓글로는 힘들 것 같아서 함께 회의실에서 한번 만나보면 좋겠네요.
오늘은 오후 7시 이후에 괜찮고요.. 채팅으로 시간 한번 맞춰봐요.
몇가지 코멘트 남겼으니 확인 부탁드려요~

2022-04-21 01:30 UTC, AppleCEO commented on Expo1900/Expo1900/AppDelegate.swift
> +        if shouldSupportAllOrientaion == true {
여기 == true 라는 코드가 꼭 필요할까요? ㅎㅎ

2022-04-21 01:30 UTC, AppleCEO commented on Expo1900/Expo1900/AppDelegate.swift
> -
사용하지 않는 코드 공백을 제거한 부분 좋습니다! 💯

2022-04-21 01:30 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/DetailViewController.swift
> +                                           ?? Constant.defaultValue)
저는 이런 코드 조금 보기 어렵습니다. 무엇의 기본 값일지 위 아래를 왔다갔다 하면서 확인해야할 것 같아요.
UIImage 의 기본 이미지인지 헷갈릴 수 있을 것 같습니다!

2022-04-21 01:30 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/ExhibitionItemsTableViewCell.swift
> +                                           ?? Constant.defaultValue)
위에 코드와 중복되는 것 같은데 이 역할을 하는 함수를 만들어 볼 수도 있을 것 같네요!
당근마켓에 다니는 개발자 분과 이야기를 한 적 있는데 2번만 반복되도 함수로 작성하는 것이 좋다고 합니다~

2022-04-21 01:30 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/ExhibitionItemsViewController.swift
> +    private var exhibitionItems: [ExhibitionItem] = []
접근제어자를 설정한 부분 좋습니다! 👍

2022-04-21 01:30 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/ExhibitionItemsViewController.swift
> +            let decodedData = try [ExhibitionItem].decode(from: Constant.exhibitionItemFileName)
. 이 자꾸 들어가서 조금 난해한 것 같아요.
위에서도 그렇고 Constant. 으로 시작하는 이름이 자주 들어가네요.
상수에 이런 값을 먼저 할당해주고 그 상수를 decode 함수에서 사용해 볼 수 있을까요?

2022-04-21 01:30 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    private let appDelegate = UIApplication.shared.delegate as? AppDelegate
여기 as? AppDelegate 가 꼭 필요한 코드일까요?

2022-04-21 01:30 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        var decodedData = ExpoInformation()
코드가 더 깔끔해졌네요~ 🥇

2022-04-21 01:30 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +                                                .formatString() ?? Constant.defaultValue)
저는 요렇게 많이 안 쓸 것 같아요 ㅜㅜ
고대 이집트에 써있는 벽화 같네요
한 줄에 하나씩 상수에 할당해주는 식으로 개선해 볼 수 있을까요?

2022-04-21 01:30 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        let durationValue = Constant.colon + (decodedData.duration ?? Constant.defaultValue)
이 부분도 한번 기본 값 대신에 다른 방식으로 개선해 볼 수 있을까요? 라인이 길어지네요~

2022-04-21 01:30 UTC, AppleCEO commented on Expo1900/Expo1900/Model/ExhibitionItem.swift
> +    let description: String?
옵셔널로 변경한 이유가 있을까요?

2022-04-21 01:30 UTC, AppleCEO commented on Expo1900/Expo1900/Util/Extension/Int+Extension.swift
>          }
이렇게 값이 없을 때 "" 대신에 사용할 수 있는 방법이 있습니다!
그 방법을 활용해보면 어떨까요?

2022-04-21 01:30 UTC, AppleCEO commented on Expo1900/Expo1900/Util/Extension/UILabel+Extension.swift
> +        let fullText = self.text ?? ""
하드코딩을 줄여볼 수도 있을 것 같고.. 기본 값 대신에 다른 방식을 사용해 볼 수도 있을 것 같아요~

2022-04-21 01:30 UTC, AppleCEO commented on Expo1900/Expo1900/Util/Extension/UILabel+Extension.swift
> +    func downSize(targetString: String) {
다운사이즈라고 읽히는데 글씨 폰트를 작아지게 해주는 메소드일까요?

2022-04-21 14:04 UTC, Miinseong commented on Expo1900/Expo1900/AppDelegate.swift
> +        if shouldSupportAllOrientaion == true {
그렇네요!!

2022-04-22 02:05 UTC, Minseong-yagom commented on Expo1900/Expo1900/Model/ExhibitionItem.swift
> +    let description: String?
JSON데이터에 의도된 nil값이 있는 경우가 있을 것 같다는 생각이 들었습니다. 
거기에 맞춰서 디코드된 값을 받을 수 있게 옵셔널로 해야 된다고 생각했습니다.
ex) Item중에 shortDescription이 없어서 nil로 넣어준 JSON데이터가 있을 수도 있다

2022-04-24 10:35 UTC, AppleCEO commented
요구사항은 다 충족하셨네요! 고생하셨습니다~
추가적으로 하나 이야기 드리면 마지막으로 선택한 항목이 이렇게 회색으로 강조되어있는데요. 이 부분은 빼 볼 수 있으면 좋을 것 같습니다. 👍 
![image](https://user-images.githubusercontent.com/47517256/164972390-9a38faee-e74c-4d21-bdd6-c528746d5ef2.png)

2022-04-25 05:00 UTC, merged