만국 박람회 [STEP 3] 쿼카, Tiana
yagom-academy/ios-exposition-universelle pull request #158
Opened 2022-04-21 01:17 UTC by Quokkaaa

@1Consumption 
울라프! ⛄ 
마지막 STEP3 PR 잘부탁드립니다.🙇‍♀️🙇‍♂️

# 고민한 점
1. decode 타입 생성
    * 캡슐화된 메서드에 접근하기 위한 인스턴스 생성은 불필요해 보였기에 타입 메서드로 구현했습니다. case가 없는 enum으로 인스턴스 생성이 힘들도록 구현했습니다.
    * ParserManager에서는 기존에는 KoreanHistoricalItem 모델과 ParisExpo 모델 타입에 중복으로 구현된 부분을 제거하고자 제네릭으로 타입을 구현했습니다.
    * Asset 타입의 타입 메서드로 뷰 컨트롤러에서는 뷰의 역할(= model에서 데이터를 꺼내서 보여주고 user와 interaction하는 것)에 충실할 수 있도록 했습니다.

2. 첫번째 화면 세로로 고정
    * 처음에는 UINavigationController를 확장해서 구현했는데 기기가 가로일 때 세로로 화면이 나오지 않는 문제가 생겨서 실패했습니다.
    ```swift
    extension UINavigationController {
    override open var shouldAutorotate: Bool {
        get {
            if let _ = topViewController as? ParisExpoViewController {
                return false
            }
            return true
            }
        }
    }
    ```
    * UIAppDelegate에 Bool 변수로 플래그를 선언했습니다.
    * 특정 윈도우의 뷰 컨트롤러들의 orientation 설정에 사용되는 `application(_:supportedInterfaceOrientationsFor:)` 메서드를 사용해서 `UIInterfaceOrientationMask`를 설정했습니다.
    * 플래그를 사용않고 아래처럼 젤 상단의 뷰 컨트롤러에 접근하고 싶었지만 잘 되지 않네요.🤔
    `if let _ = window?.rootViewController?.navigationController?.topViewController as? ParisExpoViewController`

3. AutoLayout
    * stakView에서 alignment와 distribution을 설정할 때 중앙 정렬을 하고 싶은 경우에는 Center로, 왼쪽으로 정렬하고 싶을 땐 leading, 가득 채울 땐 fill로 설정했습니다.
    * intrisic content size는 고유 컨텐츠 사이즈로, 버튼이나 레이블의 경우 내부 텍스트를 통해 사이즈 추측이 가능하여 오토 레이아웃 설정 시 높이 설정이 필요 없었습니다.
    * 테이블 뷰의 cell의 오토레이아웃 설정 시 처음에는 cell과 내부 stack의 상하좌우를 맞췄으나 제대로 설정되지 않아서 content view에 연결해서 해결했습니다.
    * 스크롤 뷰의 스크롤바를 오른쪽에 붙이며 좌우 간격을 띄우기 위해서 스크롤 뷰 내부에 위치한 스택뷰의 너비를 띄우고자 하는 간격만큼 작게 설정하는 것으로 해결했습니다.

4. 하드 코딩 지양

5. 단일 책임을 가지는 메서드가 되도록 분리

6. Dynamic Type
    * 버튼의 레이블 텍스트를 스토리보드에서 dynamic type으로 설정하고 싶었지만 xcode의 버그인지 저희가 제대로 적용시키지 못한 것인지 실패했습니다.
    * 따라서, 코드에서 `UIFont.preferredFont(forTextStyle: .callout)`를 통해 스타일을 지정하였고 제대로 적용된 것을 확인했습니다.
    * autoshrink를 스토리보드에서 적용시켜서 사용자가 글자 크기를 크게 설정해도 어느정도 이상은 커지지 않도록 막았습니다.
    ![](https://i.imgur.com/0bZyvTq.png)

7. 버튼 텍스트 오류
    * 버튼의 텍스트 레이블을 코드로 작성했을 때 제대로 출력되지 않아서 스토리보드에서 세팅했습니다.

8. 네이밍

2022-04-21 18:07 UTC, 1Consumption requested changes
안녕하세요 쿼카 티아나~
고생 많으셨습니다.

저번 스텝도 그렇고 워낙 잘하셔서 리뷰할 내용이 별로 없네요.
커밋도 잘 나누고 있고... 지금처럼 하시면 좋겠습니다!

아래는 고민한 점에서 제가 답변할만한 내용입니다.

> 플래그를 사용않고 아래처럼 젤 상단의 뷰 컨트롤러에 접근하고 싶었지만 잘 되지 않네요.🤔
if let _ = window?.rootViewController?.navigationController?.topViewController as? ParisExpoViewController

window의 rootViewController가 NavigationController인가요? 아니면 window의 rootViewController의 navigationController에 접근한건가요? 이부분을 확인해보시면 왜 안되었는지 해답이 될 듯 합니다.

혹시 리뷰에 부족한 점이 있거나 궁금한 점이 있다면 언제든 연락 주세요~

2022-04-21 18:07 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ParisExpoViewController.swift
> +    }
이 메소드의 역할을 설명해주실 수 있으신가요?

2022-04-21 18:07 UTC, 1Consumption commented on Expo1900/Expo1900/Model/AssetData.swift
> +}
이 메소드가 전역적으로 필요한 이유가 있을까요? 특정 화면에만 필요한 기능 같은데요.

2022-04-21 18:07 UTC, 1Consumption commented on Expo1900/Expo1900/Model/ParserManager.swift
> +import UIKit
두 모듈의 상관관계는 어떻게 되나요? 두개를 꼭 임포트 해야하나요?

2022-04-21 18:07 UTC, 1Consumption commented on Expo1900/Expo1900/Model/ParserManager.swift
> +}
사실 이부분도 전역적으로 가져갈 부분일까 라는 생각이 들긴 하는데... 어떻게 생각하시나요? 의견이 궁금합니다.

2022-04-22 06:31 UTC, Quokkaaa commented on Expo1900/Expo1900/Controller/ParisExpoViewController.swift
> +    }
저의가 발생했던 문제가 두번째화면에서 첫번째로 이동시 세로일땐 문제가없지만 가로인 상태에서 첫번째 화면으로 돌아갈때 가로 상태로 돌아가면 바로 세로로 고정이되지않고 세로로 화면을 돌려야만 고정이 됩니다. 이를 해결하기위해 방향을 세로로 설정해주는 setValue메서드를 사용했습니다.

2022-04-22 06:33 UTC, Kim-TaeHyun-A commented on Expo1900/Expo1900/Model/AssetData.swift
> +}
타입 메서드를 인스턴스 메서드로 바꾸는 것이 좋을 것 같습니다.
위 타입이 사용되는 곳에서 인스턴스를 생성해서 메서드를 호출하도록 변경했습니다.

타입 메서드의 경우 참조 이후 계속 불필요하게 메모리에 남아있기 때문에 인스턴스 메서드가 더 적절해 보입니다!

2022-04-22 06:33 UTC, Kim-TaeHyun-A commented on Expo1900/Expo1900/Model/ParserManager.swift
> +import UIKit
UIKit 안에 Foundation 프레임워크가 있는 것을 확인하고 불필요한 코드는 제거했습니다!

2022-04-22 06:33 UTC, Kim-TaeHyun-A commented on Expo1900/Expo1900/Model/ParserManager.swift
> +}
위 코멘트에서 답변 달았습니다!

2022-04-22 06:36 UTC, Kim-TaeHyun-A commented
```swift
    func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
        if let nv: UINavigationController = window?.rootViewController as? UINavigationController,
           let _ = nv.topViewController as? ParisExpoViewController
             {
            return .portrait
        }
        return .all
    }
```

조언해주신 것을 참고해서 디버깅으로 rootViewcontroller를 찾아보니 루트가 UINavigationCotroller 타입 인 것을 확인했고 코드를 위처럼 수정해서 플래그를 제거했습니다!

2022-04-26 02:01 UTC, merged