만국 박람회 [Step3] Eddy, Onetool
yagom-academy/ios-exposition-universelle pull request #160
Opened 2022-04-21 13:48 UTC by kimt4580

# STEP3 PR

@1Consumption
안녕하세요 올라프☃️
프로젝트 마지막 PR 보냅니다!
잘 부탁드립니다👍

## 구현 사항

`enum ExpoMagicNumberEnum`: Expo 매직넘버 처리를 위한 Enum

`enum ExpoStringEnum` : Expo 내 String 처리하는 Enum

`WorldFairPoster: Codable` : 만국박람회의 메인 화면에 대해 decode 진행을 위한Json 키값을 매칭
 - `private func replaceTitle() -> String` : 타이틀 2줄로 나누기 위한 메서드
 - `override func viewWillAppear(_ animated: Bool)` : 첫 화면 세로 회전 처리
 - `override func viewWillDisappear(_ animated: Bool)` : 2,3번 째 화면 가로 회전 가능 처리

`KoreaEntryDetail: Codable` : 만국박람회의 한국의 박람회에 대해 decode 진행을 위한 Json 키 값을 매칭

`Expo1900Tests`: XCTestCase : unit test code 작성

`parse` : JSON 파일을 디코딩 해주는 함수

`makeCell` : customCell 생성을 위한 함수

`decodeWorldFairPoster` : WorldFairPosterViewController에 필요한 JSON 파일을 디코딩

`updateImageViews` : WorldFairPosterViewController의 image를 업데이트

`prepare` : segue간 데이터 전송을 위한 함수

`transferData` : indexPath 데이터 할당을 위한 함수

`decodeKoreaEntry` : KoreaEntriesViewController에 필요한 JSON 파일을 디코딩

`override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int)` : koreaEntryDataArray의 카운트를 세어주기 위한 오버라이딩

`override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath)` : customCell의 reuse를 위한 오버라이딩

`showAlert` : 오류 발생 시, Alert을 띄워주는 함수

`enum ExpoError` : Error : Error 발생 시, 처리 해주는 컬렉션 타입

## 고민한 점 및 조언 얻고 싶은 부분
```swift
guard let separatedData = data?.title.components(separatedBy: ExpoMagicNumberEnum.separatePoint) else {
            return ExpoMagicNumberEnum.notFoundDate
        }
        replacedTitleText += separatedData[0]
        replacedTitleText += ExpoMagicNumberEnum.newLine + ExpoMagicNumberEnum.separatePoint + separatedData[1]
```
> 첫 번째 View의 main tile text가 요구사항서를 보니, 1900이라는 숫자를 기점으로 줄 바꿈이 일어나서 위 코드처럼 따로 분리하여 합친 후 title text를 만들어 주었는데 조금 억지 같은 느낌이 들었습니다. 위 방법말고 효율적인 방법이 있을까요?
---
```swift
enum ExpoMagicNumberEnum {
    static let defaultRowCount: Int = 0
    static let defaultVisitor: Int = 0
    static let notFoundImageFile: String = ""
    static let defaultValue: String = "0"
    static let notFoundDate: String = ""
    static let separatePoint: String = "("
    static let newLine: String = "\n"
}
```
> 위 코드처럼 magic number가 같은 string 또는 0을 사용하고 있는데, 다른 역할들을 표현해주고 있습니다. 포괄적인 의미로 묶어서 사용해도 되는지 아니면 기능에 따라 같은 string과 0이라도 따로 만들어 줘야하는지 궁금합니다.

---
![스크린샷 2022-04-21 오후 10 37 46](https://user-images.githubusercontent.com/52434820/164470217-16ed9c47-ee2f-4c1a-9970-d776b39792b8.png)
> 저희가 첫 번쨰와 마지막 뷰의 양옆을 constraint 10씩 띄어주려고 했는데, 스택뷰에서 설정하니 오토레이아웃이 이상하게 잡혀서 leading에 0를 주면 trailing이 10이 떙겨오는 현상이 생겼습니다. 그래서 양옆에 10을 주는 것이 어려워 내부 패딩을 활용해서 아래와 같이 해결했습니다. 이처럼 해결해도 괜찮은 방식인지 궁금하네요
---
> 테이블 뷰내에서 Stackview에 imageView를 하나만 넣고 그 옆에 라벨 수평적으로 두개를 또 다른 스택뷰로 채워넣어서 사용했습니다. Stackview에 이미지뷰를 하나만 넣는 이유는 스택뷰의 사이즈만 정해주게 되면 편하기 때문에 이렇게 했는데 이런 방식도 괜찮은 건가요? 원툴이 제안한 방법인데 에디가 생각했을 때 스택뷰에 하나만 넣는 게 어색하다고 느껴서 이를 질문하고 싶었습니다!

2022-04-21 18:29 UTC, 1Consumption requested changes
안녕하세요 에디 원툴~ 고생하셨습니다!

커밋도 잘 나눴네요. 좋습니다!

아래는 질문 주신 내용에 대한 제 답변입니다.

> 첫 번째 View의 main tile text가 요구사항서를 보니, 1900이라는 숫자를 기점으로 줄 바꿈이 일어나서 위 코드처럼 따로 분리하여 합친 후 title text를 만들어 주었는데 조금 억지 같은 느낌이 들었습니다. 위 방법말고 효율적인 방법이 있을까요?

아니요. 없어보입니다. 사실 저렇게 나와야한다면 애초에 개행된채로 내려오는게 가장 맞아보여요. 하지만 그렇지 못한 상황에서 최대한 잘 해결하신거 같습니다.

> 위 코드처럼 magic number가 같은 string 또는 0을 사용하고 있는데, 다른 역할들을 표현해주고 있습니다. 포괄적인 의미로 묶어서 사용해도 되는지 아니면 기능에 따라 같은 string과 0이라도 따로 만들어 줘야하는지 궁금합니다.

저라면 따로 만들거 같아요. 상수의 이름은 `어떤 값이 들어가있냐` 보다는 `어떻게 쓰이냐`에 집중해야 가독성이 좋습니다. 

>저희가 첫 번쨰와 마지막 뷰의 양옆을 constraint 10씩 띄어주려고 했는데, 스택뷰에서 설정하니 오토레이아웃이 이상하게 잡혀서 leading에 0를 주면 trailing이 10이 떙겨오는 현상이 생겼습니다. 그래서 양옆에 10을 주는 것이 어려워 내부 패딩을 활용해서 아래와 같이 해결했습니다. 이처럼 해결해도 괜찮은 방식인지 궁금하네요
테이블 뷰내에서 Stackview에 imageView를 하나만 넣고 그 옆에 라벨 수평적으로 두개를 또 다른 스택뷰로 채워넣어서 사용했습니다. Stackview에 이미지뷰를 하나만 넣는 이유는 스택뷰의 사이즈만 정해주게 되면 편하기 때문에 이렇게 했는데 이런 방식도 괜찮은 건가요? 원툴이 제안한 방법인데 에디가 생각했을 때 스택뷰에 하나만 넣는 게 어색하다고 느껴서 이를 질문하고 싶었습니다!

이 두 질문은 글로만 봐서는 잘 모르겠으니 디코에서 얘기를 해보도록 해요.

2022-04-21 18:29 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/AppDelegate.swift
> +        if shouldSupportAllOrientation == true {
if문의 컨디션으로 bool타입 변수가 들어갔으면 값을 비교하지 않아도 됩니다. 변수 그 자체가 bool이니까요.

2022-04-21 18:29 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/AppDelegate.swift
> +        return UIInterfaceOrientationMask.portrait
타입을 축약하지 않고 명시해준 이유가 있을까요?

2022-04-21 18:29 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/WorldFairPosterViewController.swift
> +
프로퍼티로 들고있기 보다는 필요할 때 까서 쓰는게 좋아보입니다. 사실 이 부분은 직접 접근하는거 자체가 별로 좋아보이진 않네요.

2022-04-21 18:29 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/WorldFairPosterViewController.swift
> +        let data = try? decodeWorldFairPoster()
try? 를 해준 이유가 있을까요? 에러 처리를 누락한거 처럼 보이네요?
`decodeWorldFairPoster` 메소드 내부를 봤더니 catch 부분에서 alert를 띄우고 있네요. 이렇게 분산해서 에러 처리를 하지말고, 최종적으로 사용하는 곳에서 한번에 처리했으면 좋겠습니다.

2022-04-21 18:29 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/WorldFairPosterViewController.swift
> +        return replacedTitleText
사실 이부분도 모델의 역할같긴 합니다.

2022-04-21 18:29 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/WorldFairPosterViewController.swift
> +        durationLabel.text = "개최 기간 : " + (worldFairPosterData?.duration ?? ExpoMagicNumberEnum.defaultValue)
여기도 어떤 값이 들어가는지를 view가 알고 있네요. 모델의 역할이 더 맞아보여요.

2022-04-21 18:29 UTC, 1Consumption commented on Expo1900/Expo1900/Model/KoreaEntryDetailTableViewCell.swift
> +        shortDescriptionLabel.sizeToFit()
sizeToFit을 해준 이유가 있을까요?

2022-04-21 18:29 UTC, 1Consumption commented on Expo1900/Expo1900/Utils/Enum/ExpoMagicNumberEnum.swift
> +    static let defaultValue: String = "0"
어떤 값의 기본값인지에 대한 설명도 있으면 좋겠습니다.

2022-04-22 01:59 UTC, kimkyunghun3 commented on Expo1900/Expo1900/Controller/AppDelegate.swift
> +        if shouldSupportAllOrientation == true {
그러네요! 불필요한 true 조건 수정했습니다!

2022-04-22 01:59 UTC, kimkyunghun3 commented on Expo1900/Expo1900/Controller/AppDelegate.swift
> +        return UIInterfaceOrientationMask.portrait
처음 생각에는 명시해주는게 가독성이 높다고 생각했는데, 굳이 그럴 필요가 없다고 생각해서 축약형으로 바꿨습니다.

2022-04-22 02:03 UTC, kimkyunghun3 commented on Expo1900/Expo1900/Controller/WorldFairPosterViewController.swift
> +
전역으로 가지고 있는 것보다 사용하는 곳에만 쓰는게 좋아보여서 수정했습니다!

2022-04-22 02:03 UTC, kimkyunghun3 commented on Expo1900/Expo1900/Model/KoreaEntryDetailTableViewCell.swift
> +        shortDescriptionLabel.sizeToFit()
처음 테이블뷰쪽 레이아웃 설정한다고 한건데, 불필요한 코드인데 까먹고 안뺏습니다. 제거했습니다!

2022-04-22 02:03 UTC, kimkyunghun3 commented on Expo1900/Expo1900/Utils/Enum/ExpoMagicNumberEnum.swift
> +    static let defaultValue: String = "0"
사용되는 곳마다 다르게 설정해서 수정했습니다!

2022-04-22 03:16 UTC, kimt4580 commented on Expo1900/Expo1900/Controller/WorldFairPosterViewController.swift
> +        let data = try? decodeWorldFairPoster()
에러 처리 누락한 게 맞습니다. 분산해서 최종적으로 사용하는 곳에서 한번에 처리하도록 변경하였습니다!

2022-04-22 03:17 UTC, kimt4580 commented on Expo1900/Expo1900/Controller/WorldFairPosterViewController.swift
> +        return replacedTitleText
Model로 역할 분리 해주었습니다!

2022-04-22 03:17 UTC, kimt4580 commented on Expo1900/Expo1900/Controller/WorldFairPosterViewController.swift
> +        durationLabel.text = "개최 기간 : " + (worldFairPosterData?.duration ?? ExpoMagicNumberEnum.defaultValue)
이 부분도 Model로 역할을 분리해주었습니다!

2022-04-26 02:01 UTC, merged