만국박람회 [STEP3] Doogie, Red
yagom-academy/ios-exposition-universelle pull request #164
Opened 2022-04-22 04:28 UTC by doogie97

# 만국박람회 STEP3 PR

@TTOzzi
안녕하세요! 또치🦔 STEP3 완료해서 PR보냅니다!
잘부탁드립니다!😁😄

## 고민했던 것들
* ViewController의 init
* 의존성 주입
* AutoLayout(accessability 에 따른 정갈한 UI)
* 화면회전

### 1. ViewController의 init
#### [기존 코드]
```swift
final class ItemViewController: UIViewController {
    @IBOutlet weak private var itemImageView: UIImageView!
    @IBOutlet weak private var descriptionLabel: UILabel!
    
    var item: Item?
```
위 코드에서 item에 데이터를 넣어주기 위해서는 `ItemViewController`의 인스턴스를 생성해 직접 접근을 해줬어야 했는데 그러면 외부에서 데이터가 변경되지 않도록 하는 접근제어 설정도 하지 못하고 또 직접 접근한다는 것을 문제점으로 말씀해 주셨고 `storyboard creator init`에 대해 공부해보길 권유해주셨습니다

```swift
final class ItemViewController: UIViewController {
    @IBOutlet weak private var itemImageView: UIImageView!
    @IBOutlet weak private var descriptionLabel: UILabel!
    
    private let item: Item
    
    init(item: Item) {
        self.item = item
        super .init(nibName: nil, bundle: nil)
    }
    
    init?(_ coder: NSCoder, _ item: Item) {
        self.item = item
        super.init(coder: coder)
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
```
그래서 공부 후 위 과정을 통해 `ItemViewController`의 init을 통해 item을 할당해주도록 하였습니다
(공부하면서 이해가 안되는 부분도 많았지만 이 부분은 앞으로 자주 사용해보면서 조금 더 파악이 필요 할 것 같습니다)

### 2. 의존성 주입

`ListViewController` 와 `ItemViewController` 사이의 의존성을 낮춰 주기 위해서, Item 이라는 프로토콜을 만들었습니다.

### 3. AutoLayout(accessability 에 따른 정갈한 UI)
`accessability` 의 `dynamic font` 를 지원했습니다.
* main View 의 버튼이 위의 컨텐츠와 겹치지 않도록 `maximumContentSizeCategory` 사이즈를 `.accessibilityExtraLarge` 로 설정해 주었습니다. 
* 2번 째 스크롤 뷰의 `accessibilityExtraLarge` 사이즈 이상의 뷰에서는 사진과 글씨의 가독성을 위해서 stackView 를 세로로 돌리도록 설정했습니다. 

### 4. 화면회전
첫번째 화면을 고정하기 위해서 다음과 같은 방법들을 사용했습니다. 
1. mainViewController 에서 AppDelegate 를 받아와서 고정을 해주었습니다.
2. AppDelegate 내부에서 mainViewController 를 받아와 고정해주기 
3. AppDelegate 와 mainViewController 사이의 객체를 만들어서 그 객체에서 고정해주는 메서드를 생성하기 
4. `supportedInterfaceOrientations` 메서드를 override 해서 화면 고정하기

1, 2, 3 과 같은 다양한 방법을 시도해 보았지만 AppDelegate 와 mainViewController 사이의 의존성이 높아 진다는 점등의 단점으로 사용하지 않았고 결국엔 `ExpoNavigationController` 와  `mainViewController` 에 아래의 메서드를 구현해 주어 문제를 해결했습니다.

```swift 
override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
    guard let _ = self.topViewController as? MainViewController else {
        return .all
    }
    return .portrait
}
```

가로상태에서 2번째 화면으로 화면 회전이 일어났을 때 
회전이 되는 상황을 만들기 위해서 

`viewDidAppear` 에 `attemptRotationToDeviceOrientation` 메서드를 호출해 주었습니다.

```swift 
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    UIViewController.attemptRotationToDeviceOrientation()
}
```

## 조언 받고 싶은 내용

### 1. 폰트 변경시 앞쪽 text로 범위 설정시 적용이 안되는 문제
![](https://i.imgur.com/xuDiYBW.gif)

```swift
private func changeFontSize(for expoInfo: Exposition) {
    let bodyFont = UIFont.preferredFont(forTextStyle: .body)
    visitorsLabel.changeFontSize(bodyFont, targetString: "방문객")
    locationLabel.changeFontSize(bodyFont, targetString: "개최지")
    durationLabel.changeFontSize(bodyFont, targetString: "개최 기간")
    }
```

![](https://i.imgur.com/llFBBuV.gif)

```swift
private func changeFontSize(for expoInfo: Exposition) {
    let bodyFont = UIFont.preferredFont(forTextStyle: .body)
    visitorsLabel.changeFontSize(bodyFont, targetString: ": \(ExpoNumberFormatter.changeVisitorsFormat(from: expoInfo.visitors) ?? "정보 없음")")
    locationLabel.changeFontSize(bodyFont, targetString: ": \(expoInfo.location)")
    durationLabel.changeFontSize(bodyFont, targetString: ": \(expoInfo.duration)")
    }
```

최초에 "방문객", "개최지" 등 이런 제목? 같은 곳에 다른 폰트를 적용해 주는 것이 코드도 길어지지 않고 보기 좋을 것 같아 그렇게 진행 했으나 구동 화면에서는 뒤쪽 부분이 dynamic type 적용이 되지 않는 문제가 있었습니다

결과적으로는 아래 코드로 변경하면서 문제는 해결되었으나 왜 이전 방법은 적용이 되지 않았는지 이유를 찾지 못해 한 번 여쭤보고싶습니다!

### 2. 의존성 주입
STEP2 의 조언해 주신 내용을 바탕으로 의존성 주입을 시도해 보았는데, 처음 시도해 보는 것이라 이런식으로 사용하는 것이 맞는지 궁금 합니다. 

### 3. 가로일 때 회전
가로일 때 화전하는 것이 지금 잘 되고 있는데요 버그를 하나 발견했습니다. 
처음부터 시뮬레이터를 가로로 두고 어플을 실행시키면 2번 화면으로 넘어갈 때 화면 회전이 일어나지 않습니다.😭 이유가 무엇일까요?

2022-04-24 17:22 UTC, TTOzzi requested changes
안녕하세요 두기, 레드 🙇 
항상 코드도 읽기 쉽게 작성해주시고, 커밋 자세하게 분리해서 적으시는 것도 많이 번거로우셨을 텐데 끝까지 깔끔하게 작성해주셔서 너무 좋네요 😊
덕분에 어떤 흐름으로 작업하셨는지 알기 쉬워 더 자세하게 리뷰할 수 있었던 것 같습니다.
프로젝트가 끝났더라도 남겨드린 코멘트 중 이해안되는 부분이 있다면 언제든지 말씀해주세요~!
마지막까지 고생하셨습니다!!

### ViewController의 init

헛 이해 안되는 부분이 많았다면, (제가 답변드릴 수 있을진 모르겠지만.. )디엠으로 언제든 질문 주셔도 됩니다!

### 폰트 변경시 앞쪽 text로 범위 설정시 적용이 안되는 문제

우와.. 역대급 어려운 질문이었어요..
저도 깊게 생각해본 적 없던 부분이라 열심히 테스트하며 찾아봤습니다.
명확하게 이래서 적용이 안된다! 는 정보는 찾지 못해.. 추측이지만 지금까지 찾은 정보로 코멘트 달아두겠습니다 :sob:

`AttributedString` 으로 `font` 스타일을 적용할 때, 첫 글자에 적용되었을 때만 말씀해주신 상황이 재현되더라구요.
그래서 찾아보니..! `attributedText`가 적용되는 시점에 첫 번째 문자의 스타일 정보로 `UILabel`의 스타일 관련 프로퍼티들을 업데이트 한다고 합니다!

https://developer.apple.com/documentation/uikit/uilabel/1620542-attributedtext

> Assigning a new value to this property also replaces the value of the [`[text](https://developer.apple.com/documentation/uikit/uilabel/1620538-text)`](https://developer.apple.com/documentation/uikit/uilabel/1620538-text) property with the same string data, although without any formatting information. In addition, assigning a new value updates the values in the [`[font](https://developer.apple.com/documentation/uikit/uilabel/1620532-font)`](https://developer.apple.com/documentation/uikit/uilabel/1620532-font), [`[textColor](https://developer.apple.com/documentation/uikit/uilabel/1620531-textcolor)`](https://developer.apple.com/documentation/uikit/uilabel/1620531-textcolor), and other style-related properties so that they reflect the style information starting at location `0` in the attributed string.

실제로 디버거에서 `attributedText`를 할당하고 난 이후, `self.font`를 찍었을 때 값이 다르더라구요!
첫 번째 문자에 스타일을 지정하지 않았을 땐 기본값이 유지되어 모든 텍스트에 dynamic type이 적용되고, 첫 번째 문자에 스타일을 지정했을 땐 UILabel의 font가 첫 번째 문자 기준으로 변경되어 같은 스타일을 가진 텍스트들만 적용되지 않았을까 싶네요 :thinking:

### 의존성 주입

관련해서 코멘트 남겨뒀어요!
좀 더 디테일하게 이야기하면 많이 길어질 것 같은데.. `단위테스트와 의존성 주입` 키워드로 검색해보시면 잘 설명된 예제 코드들이 많을거예요.
찾아보시고도 이해가 어렵다면 말씀해주세요 :pray:

### 가로일 때 회전

음.. `attemptRotationToDeviceOrientation` 가 실행될 때 현재 기기가 가로모드인지, 세로모드인지 판단하는 기준이 `UIDevice.current.orientation` 이라 그런 것 같네요.
`UIDevice.current.orientation` 은 실제로 기기의 방향이 변경되었을 때 업데이트되고, 그 전까진 `unknown`을 반환합니다. 이걸 해결하기 위해선.. 직접 그 시점의 방향을 계산해서 가져오는 로직을 구현해야 할 것 같아요 :thinking:

2022-04-24 17:22 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ItemTableViewCell.swift
> +    }
사용하지 않는 메서드는 지워주세요 🙂

2022-04-24 17:22 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ItemViewController.swift
> +    }
이 생성자는 어떤 이유로 구현된 건가요?!
`ItemViewController`는 Interface Builder로 구현되어있어 만약 이 생성자를 통해 생성된다면 크래시가 발생할 것 같아요 🤔

2022-04-24 17:22 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ItemTableViewCell.swift
> +            itemImageView.widthAnchor.constraint(equalTo: itemStackView.widthAnchor, multiplier: 0.6).isActive = true
오.. 글씨 크기가 많이 커지더라도 자연스럽게 보여줄 수 있도록 조건을 걸어두셨군요 👍 

다만.. 실행에 큰 문제는 없긴 하나, 이렇게 매번 제약조건을 잡아주는 코드를 실행하게 되면 셀은 계속 재사용되기 때문에 스크롤할 때 마다 제약조건이 쌓이고 있을 것 같아요 🤔 
`NSLayoutConstraint`를 내부 프로퍼티로 할당해 가지고있다가, 재사용되는 시점마다 활성화/비활성화 처리를 해주는 게 좋을 것 같습니다.

2022-04-24 17:22 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ItemTableViewCell.swift
> +    func displayWith(item: Item) {
사소한 코멘트! `with` 는 argument label로 처리해주면 호출부에서 더 자연스럽게 읽힐 것 같아요.

2022-04-24 17:22 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +    private func storeItem(item: Item.Type) {
여기도 사소한 코멘트..! 함수 이름의 `Item`과 인자의 `item`이 의미가 겹치는데 하나로 줄이면 더 자연스럽게 읽힐 것 같아요.

2022-04-24 17:22 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +        itemCell.changeItemStackViewSetting()
외부와 의존성을 가지지 않고(외부로부터 데이터를 전달받을 필요가 없는 경우), 셀이 재사용되는 시점에 실행되어야 하는 로직이라면 셀의 `prepareForReuse` 시점에 호출해줘도 될 것 같아요 🤔

2022-04-24 17:22 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +            })
앗! 요기서 위에 코멘트한 생성자가 쓰이는군요..!
지금은 `.init(coder, item)`가 실패하면 `fatalError`가 호출되도록 처리한 것과 다름없을 것 같습니다 🤔 
```suggestion
        let itemVC = storyboard?
            .instantiateViewController(identifier: ItemViewController.identifier,
                                       creator: { coder -> ItemViewController? in
                return .init(coder, item)
            })
```
요렇게 바꾸면 혹시나 `.init(coder, item)`가 실패하더라도 앱이 종료되는 상황은 막을 수 있을 것 같아요!

2022-04-24 17:22 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/NavigationViewController.swift
> +class ExpoNavigationController: UINavigationController {
`final` 이 빠졌어요! 👮‍♂️

2022-04-24 17:22 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/NavigationViewController.swift
> +    }
요것도 지워도 되겠네요!

2022-04-24 17:22 UTC, TTOzzi commented on Expo1900/Expo1900/Controller/NavigationViewController.swift
> +        }
타입 캐스팅한 값을 사용하지 않고 단순 타입 체크 정도만 하고 있으니 `as`보단 `is`가 더 적합할 것 같아요!

```suggestion
        guard topViewController is MainViewController else {
            return .all
        }
```

2022-04-24 17:22 UTC, TTOzzi commented on Expo1900/Expo1900/Extension/extension+Array.swift
>          }
요건 약간 취향 차이이긴 한데.. 이렇게 로직의 앞단에서 조건을 체크하고, 넘어가지 못할 때 반환하는 방어로직 느낌의 로직은 `if`보단 `guard`가 더 이해하기 쉬운 것 같아요 🤔 
범위 체크 조건문도 `||` 연산자보다 `contains`를 활용하면 더 깔끔해질 것 같습니다.
(이건 주관적인 생각이니 참고만 해주세요 🙏 )
```suggestion
        guard (0..<count).contains(index) else {
            return nil
        }
```

2022-04-24 17:22 UTC, TTOzzi commented on Expo1900/Expo1900/Extension/extension+UILabel.swift
> +        self.adjustsFontForContentSizeCategory = true
`adjustsFontForContentSizeCategory`를 `true`로 설정해주는 건 특정 범위에 폰트 사이즈를 설정해주는 로직과는 별개로 봐야하지 않을까.. 하는 생각이 드네요.
실제로 위에서도 따로 호출해주고 있기도 하구요 🤔

2022-04-24 17:22 UTC, TTOzzi commented on Expo1900/Expo1900/Model/Heritage.swift
> +}
`Item` 프로토콜의 구현 의도가 `ListViewController` 와 `ItemViewController` 사이의 의존성을 낮춰 주기 위해서 라고 말씀하셨는데, 정확히 어떤 이유로 두 뷰컨간의 의존성이 낮춰지는 건지 모르겠어요 🤔 
지금 작성된 코드론 뷰컨간의 의존성이 낮아졌다기 보단, 구체타입 `Heritage`와 `ListViewController`의 메서드 `storeItem(item:)`의 의존성이 낮아진 것 같네요.

만약 목적이 `ItemViewController`와 `ListViewController`에서 전달하는 구체타입 `Heritage` 사이의 의존성을 줄이기 위함이었다면, `Item` 프로토콜의 요구사항을 `ItemViewController`에서 필요로 하는 정보만 가지도록 해야할 것 같아요.

2022-04-24 17:22 UTC, TTOzzi commented on Expo1900/Expo1900/Model/NumberFormatter.swift
> +struct ExpoNumberFormatter {
지금 구현에선 `struct`, `enum`, `class` 어떤 것으로 선언해도 똑같이 동작할 것 같은데, `struct`로 선언하신 이유가 궁금해요 👀

2022-04-24 17:22 UTC, TTOzzi commented on Expo1900/Expo1900/Model/NumberFormatter.swift
> +    static let shared = NumberFormatter()
`shared`라는 네이밍이.. 싱글톤 패턴을 구현하려 하신 건가요?!

2022-04-25 01:50 UTC, doogie97 commented on Expo1900/Expo1900/Extension/extension+UILabel.swift
> +        self.adjustsFontForContentSizeCategory = true
맞습니다
제거해줘도 정상 작동도 되고 이미 스토리보드에서 설정하고 있기 때문에 제거해주었습니다

2022-04-25 02:13 UTC, cherrishRed commented on Expo1900/Expo1900/Controller/ItemViewController.swift
> +    }
넵 필요없는 생성자를 삭제해 주었습니다!

2022-04-25 02:19 UTC, cherrishRed commented on Expo1900/Expo1900/Controller/ItemTableViewCell.swift
> +    func displayWith(item: Item) {
넵 네이밍 수정 했습니다!

2022-04-25 02:32 UTC, cherrishRed commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +            })
네넵 이부분을 수정해 주었습니다!! fatalError 를 쓰지 말았어야 하는 것을 잘 몰랐었네요ㅠㅠ

2022-04-25 02:39 UTC, doogie97 commented on Expo1900/Expo1900/Model/NumberFormatter.swift
> +struct ExpoNumberFormatter {
struct가 제일 익숙해서 이렇게 만든거긴 한데 이 부분은 프로퍼티로 생성될 필요가 없으니까 enum으로 구현해주는게 좋을 것 같습니다

2022-04-25 02:41 UTC, doogie97 commented on Expo1900/Expo1900/Model/NumberFormatter.swift
> +    static let shared = NumberFormatter()
이 부분은 저희도 작성하면서 약간 갸우뚱 하면서 작성하긴 했는데 그냥 `numberFormatter`로 변경해 주었습니다
하면서 접근제어 설정까지 진행했습니다!

2022-04-26 03:50 UTC, cherrishRed commented on Expo1900/Expo1900/Controller/ItemTableViewCell.swift
> +            itemImageView.widthAnchor.constraint(equalTo: itemStackView.widthAnchor, multiplier: 0.6).isActive = true
넵 `NSLayoutConstraint` 프로퍼티를 만들어 수정해 주었습니다!

2022-04-26 03:56 UTC, doogie97 commented on Expo1900/Expo1900/Model/Heritage.swift
> +}
의존성 주입을 공부하고 적용해보고 싶었는데 모든 부분에 다 적용하기에는 조금 벅차서 한 부분만 적용해보고자 했습니다
그 부분이 heritage와 ListVC의 의존성을 낮춰준 것인데 처음 공부하다보니까 전달하는 과정에 약간 혼동이 있었던 것 같습니다

2022-04-26 03:59 UTC, doogie97 commented on Expo1900/Expo1900/Controller/ListViewController.swift
> +        itemCell.changeItemStackViewSetting()
이 부분은 저희 둘 다 공부가 필요한 부분인 것 같은데 다음 프로젝트가 시작되어서 각자 공부해보기로 했습니다!

2022-04-26 11:04 UTC, TTOzzi approved these changes
앱 아이콘까지 넣어주셨군요 ㅋㅋㅋ
수정하신 부분 확인했고 이견 없습니다! 머지할게요!
고생하셨습니다 🙇

2022-04-26 11:05 UTC, merged