만국박람회 [STEP 1] derrick, baekgom
yagom-academy/ios-exposition-universelle pull request #165
Opened 2022-06-13 08:04 UTC by derrickkim0109

안녕하세요 그린! @GREENOVER 
Step01 첫 PR을 올립니다. ! @Baek-Gom-95

# 배경 
> JSON 포멧의 데이터와 매칭할 모델 타입을 구현

- Contents.json
```json
{
  "images" : [
    {
      "filename" : "bangjja~universal@1x.png",
      "idiom" : "universal",
      "scale" : "1x"
    },
    {
      "filename" : "bangjja~universal@2x.png",
      "idiom" : "universal",
      "scale" : "2x"
    },
    {
      "filename" : "bangjja~universal@3x.png",
      "idiom" : "universal",
      "scale" : "3x"
    }
  ],
  
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
```
- items.json 

```json
[
	{
		"name":"직지심체요절",
		"image_name":"jikji",
		"short_desc":"백운화상 경한(景閑)이 1372년에 초록한 불교 서적",
		"desc":"《'백운화상초록불조직지심체요절》(白雲和尙抄錄佛祖直指心體要節)은 백운화상 경한(景閑)이 1372년에 초록한 불교 서적이다. 간단히 직지심체요절(直指心體要節) 또는 직지(直指, JUKJI)라고 부르기도 한다.\n\n1372년(공민왕 21)에 백운화상 경한이 임제종 18대 법손 석옥청공(石屋淸珙) 화상(和尙)으로부터 받아 온 《불조직지심체요절》을 증보하여 상·하 2권으로 엮은 것이다. 백운화상이 입적하고 3년 뒤인 1377년에 청주 흥덕사(興德寺)에서 금속활자로 찍어 낸 것이 초인본(初印本)이다. 이는 현존하는 금속활자로 인쇄된 책 중 가장 오래된 것이다. 금속활자본은 현재 하권만이 전해지고, 프랑스 국립도서관에 소장되어 있다. 고간본(古刊本)으로는 1378년 백운화상이 입적한 여주 취암사(鷲巖寺)에서 간행한 목판본이 있다. 목판본은 1992년 4월 20일 보물 제1132호로 지정되었고, 현재 한국학중앙연구원 장서각과 국립중앙도서관에 상하권 1책이 각각 소장되어 있다.\n\n중심 주제인 직지심체(直指心體)는 ‘직지인심견성성불(直指人心見性成佛)’이라는 오도(悟道)의 명구에서 따온 것이다. 그 뜻은 사람이 마음을 바르게 가졌을 때 그 심성이 곧 부처의 마음임을 깨닫게 된다는 뜻이다. 사람의 본성은 그 자체가 본시 청정하므로 선지식(善知識)의 도움에 의하여 자기 마음 속에서 그 심성이 자정(自淨)함을 깨닫고 늘 자수(自修)·자행(自行)하면 곧 불성(佛性)을 체득하여 자기 자신이 바로 법신(法身)이 되며, 자기 마음이 바로 불심이 된다는 요지이다.\n\n정식 명칭은 ‘백운화상초록불조직지심체요절’(白雲和尙抄錄佛祖直指心體要節)이며, 간략 서명은 ‘불조직지심체’(佛祖直指心體)이다. 판심제(版心題)는 직지(直指) 또는 심요(心要)이다. 간단히 '직지심체요절(直指心體要節)', '직지(直指)'로 불리며, 영어권에도 'Jikji'로 통용된다.\n\n흔히 직지심경(直指心經)으로도 불리는데, 불서(佛書) 중 직지는 경(經)이 아니라 요절(要節)이기 때문에 이는 잘못된 표현이다."
	},
```

# 작업내용

1. Codable을 채택하여 JSON 데이터와 매칭할 모델 타입 구현

2. 스네이크 케이스 또는 축약형인 JSON 키 값을 스위프트의 네이밍에 맞게 변환
```swift=
extension EntryEntity {
    enum CodingKeys: String, CodingKey {
        case name
        case imageName = "image_name"
        case shortDescription = "short_desc"
        case description
    }
}
```
- CodingKey 타입을 채택한 enum을 사용하여 JSON 키 값에 대칭

# 리뷰 노트 

1. Json 파일을 서버를 통해 파싱 받는 것이 아니라 strings file로 json 파일을 생성하여 파싱하는 방식일까요?/ 파일들 디렉토리를 프로젝트 내에 넣어서 경로를 읽어오는 방식일까요? 

2. Content.json 파일을 파싱할 필요가 있을까요? image 파일들을 Assets에 넣고 해당 이름들을 ImageView에 올리기만 하면 되는 것 아닌가요?

2022-06-13 09:08 UTC, GREENOVER requested changes
@derrickkim0109 @Baek-Gom-95 
두분 안녕하세요!
이번 2주동안 만국박람회 프로젝트를 리뷰하게되어 영광입니다🙌
리뷰를 드리는것은 정답지가 아닌 팀원으로써의 의견 및 질문들이라고 생각해주시면 좋겠습니다!
그렇기에 여러분의 코드에서 정말 궁금한것들을 여쭤보는것도 있을것이고 제가 생각하는 더 나은 방향도 던져볼 수 있을텐데
만약 그 과정에서 여러분들의 의견이 더 적절할것 같으면 언제든지 코멘트로 말씀해주시고 밀고 나아가시면 됩니다😀
(리뷰 코멘트로 남긴것을 다 수정해야되는 강박에 사로잡히지 않았으면 좋겠어서 미리 말씀드려요..!)
그럼 리뷰를 드려보겠습니다!
우선 스텝 1 정말 빠르게 모델 타입을 구성해주셨네요ㅎㅎ
고생 많으셨습니다👍
다만 필요한 모델 타입 정의가 누락된 부분도 있고 불필요한 부분도 있는것 같아 그 위주로 리뷰를 드려봤습니다.
***
### 칭찬 드리고 싶은 부분 
- 모델 타입에 대해 기초 개념을 잘 이해하신점 💯
- 커밋을 단위별로 잘 나눠 페어로 작업해주신점 💯
- 파일 구조를 View / Model로 초기에 관심사별로 잘 나눠주신점 💯
***
### 궁금하신 부분에 대한 저의 의견
1. Json 파일을 서버를 통해 파싱 받는 것이 아니라 strings file로 json 파일을 생성하여 파싱하는 방식일까요?/ 파일들 디렉토리를 프로젝트 내에 넣어서 경로를 읽어오는 방식일까요?
- 현업을 기준으로 원래라고 친다면 당연히 서버 API를 통해 JSON 데이터를 받아와 파싱해 사용합니다.
다만 해당 이번 만국박람회 프로젝트에서는 Mock JSON 데이터를 통해 구현해주는것이 요구사항이기에 파일로 파싱하는 방법을 택해야될것 같습니다.
즉 이번에는 파일들을 에셋에 넣고 파싱하는게 적절할것 같아요🙌
2. Content.json 파일을 파싱할 필요가 있을까요? image 파일들을 Assets에 넣고 해당 이름들을 ImageView에 올리기만 하면 되는 것 아닌가요?
- 해당 파일은 파싱할 필요가 없을것 같아요.
저도 두분이 이해하신바와 같이 이미지 파일들을 Assets에 Images 폴더 하위로 넣어두고 모델 타입에서 UIImage로 프로퍼티를 가질 수 있도록 하는것이면 충분할것 같아요🙋🏻
***
### 개선되어야 할 부분
- 우선 스텝 2에서 표지 즉 주어진 expo_assets 폴더에서 exposition_universelle_1900.dataset > exposition_universelle_1900.json 파일의 파싱될 모델 타입이 없습니다.
![스크린샷 2022-06-13 오후 6 05 12](https://user-images.githubusercontent.com/72292617/173319252-9497ff1a-e28a-4519-a441-b698da090f98.png)
![스크린샷 2022-06-13 오후 6 05 50](https://user-images.githubusercontent.com/72292617/173319401-a238b466-0e4c-474e-ad02-765d6d60fc70.png)
요 부분에 대해 필요하지 않을까 합니다..!
- 추가로 위에서도 코멘트에서도 언급했지만 FileEntity 모델 타입은 불필요하지 않을까 생각합니다🤔
실제로 디코딩을 시키고 파싱하는곳이 없지 않을까해요🙋🏻
***
고생 많으셨습니다!
우선 필수 구현되어야할 모델이 없기에 request Changes로 요청 드리겠습니다!
리팩토링이 되면 언제든 리뷰 재요청을 해주시면 감사하겠습니다🥳

2022-06-13 09:08 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +import Foundation
필요한 import 일까요~?🙋🏻

2022-06-13 09:08 UTC, GREENOVER commented on Expo1900/Expo1900/Model/FileEntity.swift
> +import Foundation
필요한 import 일까요~?🙋🏻

2022-06-13 09:08 UTC, GREENOVER commented on Expo1900/Expo1900/Model/FileEntity.swift
> +}
해당 모델타입은 스텝2의 요구사항을 보면 정의될 필요가 없을것 같은데 정의해주신 이유가 있을까요?

2022-06-13 09:08 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +    let imageName: String
이미지를 String으로 모델타입에서 정의하고 뷰컨에서 실제 사용될때 UIImage 타입으로 변경해야될것 같은데 해당하는 변환 작업과 같은 뷰컨에서 하는 역할을 모델의 역할로 옮겨보면 어떨까요?🙋🏻
뷰컨의 할일을 줄이고 관심사를 명확히 가져갈 수 있지 않을까합니다..!

2022-06-13 09:08 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +struct EntryEntity: Codable {
해당 객체가 Encodable을 채택할 필요가 있을까요??🙋🏻
Codable은 어떤 특성을 갖고 있을까요?

2022-06-13 09:08 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +}
해당 모델 타입의 이니셜라이저를 생성해준다면 추후 요긴하게 쓰일 수 있을것 같은데 두분 의견은 어떠실까요~?🙋🏻

2022-06-13 09:08 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +extension EntryEntity {
extension으로 코딩키 구현을 빼주신 이유가 어떤건지 궁금합니다🙋🏻

2022-06-13 09:08 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +        case description
그대로 사용되는 코딩키에 대해 `case name, description`으로도 사용될 수 있을 수 있고 지금처럼 사용하실 수도 있습니다..!
두분은 어떤 스타일을 어떤 이유로 선호하실까요~?🙋🏻

2022-06-13 09:08 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +        case shortDescription = "short_desc"
만약 이렇게 단순 스네이크 케이스를 카멜 케이스로만 프로퍼티명을 변경하기 위해 사용된다면 이런것도 있습니다..!
디코딩 전략을 수립 시 스네이크 -> 카멜로 변환해줄 수 있습니다.
저도 커스텀하게 크게 사용하지는 않는데 이러한 단순한 상황일때는 사용할 수도 있을거라 레퍼를 공유드립니다🙌
https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy/convertfromsnakecase

2022-06-13 09:08 UTC, GREENOVER commented on README.md
> +## 만국박람회 프로젝트 저장소
리드미 작성도 스텝마다 이뤄진다면 분명 도움이 많이 되실꺼에요..!😄

2022-06-13 09:08 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +    enum CodingKeys: String, CodingKey {
internal 하게 사용될 일이 있을지 궁금합니다🙋🏻

2022-06-13 10:06 UTC, derrickkim0109 commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +struct EntryEntity: Codable {
Codable은 Encodable & Decodable 두 프로토콜을 이 결합된 typealias로 두 프로토콜을 준수해야합니다. 
Encodable은 사람이 인지할 수 있는 데이터를 컴퓨터가 인지 할 수 있는 기계어 0과 1로 변환하는 것이고
Decodable은 컴퓨터가 사람이 이해할 수 있도록 변환해주는 것으로 알고 있습니다. 

Encoding은 데이터를 서버로 던질때,
Decoding은 서버로부터 데이터를 받을때로 생각하면 될까요? 

제가 찾아본게 맞다면 Encoding은 필요 없을 것 같습니다.

2022-06-13 10:08 UTC, derrickkim0109 commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +    enum CodingKeys: String, CodingKey {
알려주신 카멜로 변환해주는 설정을 한다면 CodingKeys가 불필요할 것 같아 제거하였습니다.

2022-06-13 12:40 UTC, derrickkim0109 commented on Expo1900/Expo1900/Model/FileEntity.swift
> +}
해당 모델의 사용유무를 생각해보지 못하였습니다. 다만 json파일로 존재하여 해당 모델을 만들었었습니다.

2022-06-13 12:46 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +struct EntryEntity: Codable {
넵 찾고 이해하신 부분이 맞다고 저도 생각합니다~!
그렇다면 Decodable 채택만으로도 명확하고 충분하겠네요..!

2022-06-13 12:48 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +    enum CodingKeys: String, CodingKey {
좋습니다!
그런데 만약 추후 해당 모델 타입에 더 정의될 필드들이 스네이크 케이스를 단순 카멜 케이스로 변환 시 어색할 수도 있고 그럴 경우 아예 새로운 프로퍼티 네이밍을 줘야할 상황도 있을것 같아요.
이럴때도 있긴해서 딜레마이긴합니다만 현재로썬 무리가 없을것 같아요.
정말 스타일 차이니 각자의 장단점을 보고 더 괜찮은걸 택해보시몈 좋겠습니다!

2022-06-13 13:04 UTC, derrickkim0109 commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +import Foundation
제거했습니다!

2022-06-13 13:04 UTC, derrickkim0109 commented on Expo1900/Expo1900/Model/FileEntity.swift
> +import Foundation
제거했습니다!

2022-06-13 13:05 UTC, derrickkim0109 commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +extension EntryEntity {
코딩키는 제거하였습니다.!

2022-06-13 13:10 UTC, derrickkim0109 commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +        case description
case name, description, shortDescription 이런식으로 빼는 것만으로도 가독성이 떨어지지만 
case imageName = "image_name" raw 값을 지정해 주면 더욱 길어질 수 있어서 위의 방식을 선호합니다.

2022-06-13 13:11 UTC, derrickkim0109 commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +    enum CodingKeys: String, CodingKey {
넵 알겠습니다!

2022-06-14 00:08 UTC, GREENOVER approved these changes
@derrickkim0109 @Baek-Gom-95 
리팩토링 하시느라 고생 많으셨습니다!
다음 스텝으로 넘어가기에 필요한 부분들은 다 경험하신것 같아 이번 스텝은 여기서 어프로브 후 머지하겠습니다~
다만 다음 스텝을 바로 시작 하기전 보완되면 좋을 부분들에 대해 코멘트 남겼습니다🙌
(꼭 확인해주세요..!)
***
아..! 또한 추가로 제가 디코딩 키 전략을 말씀드려서 해당 전략을 따르심으로 코딩키를 제거하셨는데 제가 간과한게 있네요ㅠㅠ
스텝 1의 핵심 경험 요구사항에 "JSON 키 값을 스위프트 네이밍에 맞게 변환" 이라는 항목이 있어서 물론 디코딩 키 전략을 통해 이후 스텝에서 이를 충족할 수 있지만 스텝 1의 요구사항이기에 이를 지켜야할것 같습니다..!
번거로우시겠지만 스텝 1에서는 해당 요구사항대로 반영해보고 추후 디코딩 키 전략이 필요하면 리팩토링을 하는 방향으로 가면 좋을것 같아요..!
![스크린샷 2022-06-14 오전 9 04 35](https://user-images.githubusercontent.com/72292617/173466646-8b9322c5-07bd-4e65-97ba-a8a15fb8da16.png)
***
마지막으로 깃헙 PR에서 리뷰 재요청을 하시고 싶으실때는 우측 상단에 리뷰어 부분에서 저 리프레쉬 버튼을 눌러주시면 저한테 알림이 가기에 이를 활용해주시면 더 빠른 리뷰를 드릴 수 있으니 참고해주시면 감사하겠습니다🙌
![스크린샷 2022-06-14 오전 8 51 36](https://user-images.githubusercontent.com/72292617/173466910-ce7563ef-17c3-471f-a86c-e9451ad2b3b6.png)
***
스텝 1 다시 한번 고생 많으셨고 스텝 2도 화이팅입니다🥳

2022-06-14 00:08 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +//  Entry.swift
사소하지만 파일명 주석과 실제 파일명과 다릅니다🙋🏻

2022-06-14 00:08 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +    let imageName: String
더이상 imageName이 직접적으로 호출될 경우가 없을것 같은데 private해도 괜찮지 않을까요~?🙋🏻

2022-06-14 00:08 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +        return uiImage
`return UIImage(named: self.imageName)`처럼 한 라인에 표현할 수도 있을텐데 지금같이 구현하였을때의 이점은 어떤게 있을까요?🤔
잘못되었으니 수정하자는 의미는 절대 아닙니다..!
두분의 의견이 궁금해요ㅎㅎ

2022-06-14 00:08 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +    var convertedUIImage: UIImage? {
단순히 image로 네이밍을 하는것이 더 깔끔하다고 생각이 드는데 두분 의견은 어떠세요?
현재 네이밍을 직역하자면 "변환된 UIImage"인데 무언가 네이밍만 보고서 다른 형태에서 변환되었다고 생각들것 같아요.
당연하게 string 즉 이미지네임을 가지고 UIImage를 만들어준것을 변환되었다고 생각하기 힘들지 않을까해서요🤔

2022-06-14 00:08 UTC, GREENOVER commented on Expo1900/Expo1900/Model/ExpositionPostEntity.swift
> +    let duration: String
스텝 2의 화면을 보면 이 프로퍼티들이 직접적으로 사용되는것보다 변환되어 사용될 경우가 많은것 같아요.
예를들어, 아래와 같이 개최지 부분을 보더라도 "개최지: 프랑스 파리" 처럼 location을 개최지라는 prefix 문자열과 합쳐 사용될것 같아요.
물론 이 "개최지: " 문자열을 직접 뷰컨이나 뷰에서 따로 구현해줄 수도 있겠지만 모델 부분에서 해주는것이 더 관심사에 맞을것 같아요.
뷰컨에서 모델 타입을 가공하는것보다 모델에서 다 끝내고 뷰컨에서 뷰에 올릴 수 있도록 연결만 해주는게 맞지 않을까합니다🙋🏻
즉 title부터 duration은 실제 뷰에서 다른 형태의 요소로 보여주니 해당 모델 타입에서 그에 맞는 프로퍼티 정의가 있으면 좋을것 같아요..!
![스크린샷 2022-06-14 오전 8 59 22](https://user-images.githubusercontent.com/72292617/173466280-0ab39042-259a-4f0f-860b-2e186cdb0222.png)

2022-06-14 00:08 UTC, GREENOVER commented on README.md
> +- Contents.json
리드미도 업데이트 되면 훨씬 좋을것 같아요🙌
스텝마다 차곡차곡 해두시면 분명 자산이 될거에요😀

2022-06-14 00:08 UTC, merged

2022-06-14 00:55 UTC, Baek-Gom-95 commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +        return uiImage
return UIImage(named: self.imageName) 처럼 한줄로 표현할수 있으면 한줄로 표현하는게 좋다고 생각합니다 현재 쓰이지않는 변수나 상수가 선언 및 할당 된것이 한개가 아니라 10개 100개 가 되면 프로그램이 무거워 질수있을거 같아서요.

2022-06-14 01:07 UTC, derrickkim0109 commented on Expo1900/Expo1900/Model/EntryEntity.swift
> +        return uiImage
제가 생각했을 때에는 해당부분이 상수나 변수가 할당 되더라도 메모리상에 큰 무리가 없을 것 같다고 생각하였고 
`return UIImage(named: self.imageName)`을 그대로 작성하는 방식보다는 상수에 할당하여 코드를 작성하는게 추후에 있을 다른 코드 작업에 통일성을 줄 수 있을 것 같습니다.