만국박람회 [STEP 1] 웡빙, bonf
yagom-academy/ios-exposition-universelle pull request #171
Opened 2022-06-14 02:46 UTC by apwierk2451

안녕하세요 @corykim0829 ! 😁😁
@wongbingg @apwierk2451 입니다!
STEP1 PR 보내드립니다! 2주 동안 잘 부탁드립니다 !

# Step1 

## 모델타입 구현
"items.json" 파일, "exposition_universelle_1900.json" 파일
- **Item.swift** (items 파일의 모델타입을 구현했다.)
- **Exposition.swift** (exposition_universelle_1900 파일의 모델타입을 구현했다.)
## snake케이스와 축약형
- CodingKey를 이용하여 JSON 키 값을 스위프트의 네이밍에 맞게 변환했다.

## JSON 테스트

- 각 JSON 파일마다 manager 를 만들어 파싱이 되는지 테스트를 진행했다.
--- 

## 문제점에서 해결한 점
- **로컬에 있는 json 파일을 파싱하는 방법에 대한 고민.**
파일의 경로를 찾는 과정에서 다른 사용자가 pull을 받았을 때 경로를 찾지 못하는 문제가 발생했다.
`Bundle.main.path(forResource: 파일명, ofType: 파일타입, inDirectory: 파일경로(상위 폴더이름))` 메서드를 이용하여 상대 경로를 찾아줬다.
`try? String(contentsOfFile: ).data(using: .utf8)`메서드를 이용하여 Data타입으로 변환하였고, 디코딩을 할 수 있었다.
- **`exposition` 타입과 `Item` 타입의 차이점.**
기존의 `ItemDataManager` 에서 getData() 메서드를 수행하여 json을 읽어왔다. 이를 이용해 유닛테스트를 진행하였고, 똑같이 `ExpositionDataManager` 에서도 같은 getData()메서드를 사용하여 테스트를 진행 하였는데 오류가 생겼다. 이유는 decode 메서드에 type에 형태가 달랐기 때문이었다. Item 에선 [{}] 이런 식의 json 이 들어있고, Exposition 에선 {} 이런 식의 json 이 들어있었다. 
대괄호 하나 차이로 인해 오류가 났던 것이었다. 그래서 ExpositionDataManager 에 getData() 메서드에 들어가는 type 에 대괄호를 제거해주니 해결이 되었다. 
```swift=
func decode<T>(_ type: T.Type, from data: Data) throws -> T where T : Decodable
```

- **본프와 웡빙의 xcode 버전이 달라 테스트코드가 실행되지 않는 문제**
본프가 작성한 테스트코드를 웡빙이 pull 을 받고 웡빙 xcode에서 테스트를 실행했을 때, 오류가 났다. xcode의 버전 차이 때문인 것 같았다. iOS Deployment Target 이 15.5 로 설정 되어있어 오류가 난 것인데, 이것을 15.2 로 설정 해주니 해결이 되었다.
![](https://i.imgur.com/rn65HjB.png)

2022-06-14 13:04 UTC, corykim0829 requested changes
수고 많으셨습니다!

프로젝트를 진행 하면서 생긴 이슈와 해결내용을 정리한 부분이 좋았습니다! 👍

피드백 반영해서 개선해보면 좋을 것 같습니다!

2022-06-14 13:04 UTC, corykim0829 commented on Expo1900/Expo1900/Model/Exposition.swift
> +struct Exposition: Codable {
Codable 프로토콜을 채택하였는데, 현재는 Decodable만 사용한다면 먼저 Decodable만 채택하는건 어떨까요?

2022-06-14 13:04 UTC, corykim0829 commented on Expo1900/Expo1900/Model/ExpositionDataManager.swift
> +            expositionList = try decoder.decode(Exposition.self, from: data)
에러가 발생하면, print만 하고 끝나버리는 부분이 아쉽네요. 추가적으로 처리할 수 있도록 로직이 구성되면 좋을 것 같습니다!

2022-06-14 13:04 UTC, corykim0829 commented on README.md
> +기존의 `ItemDataManager` 에서 getData() 메서드를 수행하여 json을 읽어왔다. 이를 이용해 유닛테스트를 진행하였고, 똑같이 `ExpositionDataManager` 에서도 같은 getData()메서드를 사용하여 테스트를 진행 하였는데 오류가 생겼다. 이유는 decode 메서드에 type에 형태가 달랐기 때문이었다. Item 에선
문제점 해결을 정리한 부분 매우 좋습니다! 👍
어떤 오류가 발생했는지, 실제 오류 객체의 description은 무엇이였는지 상세하게 메모하는 것도 좋을 것 같습니다!
제가 봤을 때, 두 타입 명시 자체가 다르기 때문에 타입의 차이점은 당연한 것으로 보입니다. 그러므로 해당 부분은 Decoding Error로 분류하여서 정리하면 좋을 것 같습니다.

2022-06-14 13:04 UTC, corykim0829 commented on README.md
> +대괄호 하나 차이로 인해 오류가 났던 것이었다. 그래서 ExpositionDataManager 에 getData() 메서드에 들어가는 type 에 대괄호를 제거해주니 해결이 되었다.
왜 대괄호 때문에 오류가 난 것인지 구체적인 이유는 없어서 아쉬워요! 조금 더 명확하게 설명을 해주면 좋을 것 같아요!

2022-06-14 13:04 UTC, corykim0829 commented on README.md
> +본프가 작성한 테스트코드를 웡빙이 pull 을 받고 웡빙 xcode에서 테스트를 실행했을 때, 오류가 났다. xcode의 버전 차이 때문인 것 같았다. iOS Deployment Target 이 15.5 로 설정 되어있어 오류가 난 것인데, 이것을 15.2 로 설정 해주니 해결이 되었다.
이슈 해결 정리 매우 좋습니다! 👍

2022-06-14 13:04 UTC, corykim0829 commented on Expo1900/Expo1900/Model/Item.swift
> +    enum CodingKeys: String, CodingKey {
CodingKeys 깔끔하게 잘 사용하셨습니다 👍

2022-06-14 13:04 UTC, corykim0829 commented on Expo1900/Expo1900Tests/ExpositionDataManagerTests.swift
> +        let result = sut.getData()!
`!` 사용하지 않고 처리하면 좋을 것 같아요!

2022-06-14 13:04 UTC, corykim0829 commented on Expo1900/Expo1900Tests/ItemDataManagerTests.swift
> +        let result = sut.getData()!
여기도 마찬가지로 `!` 사용하지 않고 처리하면 좋을 것 같아요

2022-06-14 13:04 UTC, corykim0829 commented on Expo1900/Expo1900/Model/ItemDataManager.swift
> +            print(error)
여기도 위 해드린 피드백과 마찬가지로 수정하면 좋을 것 같아요!

2022-06-14 14:46 UTC, apwierk2451 commented on Expo1900/Expo1900/Model/Exposition.swift
> +struct Exposition: Codable {
Decodable만 사용한다고 판단하여 Decodable로 수정하였습니다 ! 😄

2022-06-15 01:24 UTC, wongbingg commented on README.md
> +대괄호 하나 차이로 인해 오류가 났던 것이었다. 그래서 ExpositionDataManager 에 getData() 메서드에 들어가는 type 에 대괄호를 제거해주니 해결이 되었다.
리드미에 ErrorDescription 내용을 적어 주었습니다!

2022-06-15 01:25 UTC, wongbingg commented on README.md
> +본프가 작성한 테스트코드를 웡빙이 pull 을 받고 웡빙 xcode에서 테스트를 실행했을 때, 오류가 났다. xcode의 버전 차이 때문인 것 같았다. iOS Deployment Target 이 15.5 로 설정 되어있어 오류가 난 것인데, 이것을 15.2 로 설정 해주니 해결이 되었다.
감사합니다 !! 👍

2022-06-15 01:29 UTC, wongbingg commented on README.md
> +기존의 `ItemDataManager` 에서 getData() 메서드를 수행하여 json을 읽어왔다. 이를 이용해 유닛테스트를 진행하였고, 똑같이 `ExpositionDataManager` 에서도 같은 getData()메서드를 사용하여 테스트를 진행 하였는데 오류가 생겼다. 이유는 decode 메서드에 type에 형태가 달랐기 때문이었다. Item 에선
말씀대로 Decoding Error 로 내용을 분류하여 정리 해주었습니다 ! 실제 오류 객체의 description 또한 첨부 하였습니다

2022-06-15 02:48 UTC, wongbingg commented on Expo1900/Expo1900Tests/ItemDataManagerTests.swift
> +        let result = sut.getData()!
forced unwrapping 을 사용한 이유는, 유닛 테스트 에서 getData() 의 수행에 오류가 있을 때, 그 에러에 대한 description 을 출력 하도록 getData() 메서드에 설정 해주었기 때문입니다. 
 if let 또는 guard let 으로 바인딩 처리할 시 else 문에서 결과가 nil일 경우를 처리한다고 하더라도 test 코드를 실패 시키려면 print 나 return 을 사용하면 안되던데, 이 부분 또한 어떻게 처리 해야할 지 모르겠습니다..  " ! " 로 처리 했을 때 만큼 간결한 코드가 나오지 않을 것으로 판단되어,  " ! "  를 사용하지 않았을 때 코드 상 어떤 이점이 있을지 궁금합니다 ! 또한 테스트 코드에서도 강제언래핑을 지양하고 방어적인 코드를 짜야하는 지도 궁금합니다 !

2022-06-15 03:14 UTC, wongbingg commented on Expo1900/Expo1900/Model/ExpositionDataManager.swift
> +            expositionList = try decoder.decode(Exposition.self, from: data)
DecodingError의 모든 케이스에 대한 에러 핸들링을 추가 해주었습니다 !

2022-06-15 03:17 UTC, wongbingg commented on Expo1900/Expo1900/Model/ItemDataManager.swift
> +            print(error)
DecodingError의 모든 케이스에 대한 에러 핸들링을 추가 해주었습니다 !

2022-06-15 03:17 UTC, apwierk2451 commented on Expo1900/Expo1900/Model/Item.swift
> +    enum CodingKeys: String, CodingKey {
감사합니다 ! 😁

2022-06-15 13:47 UTC, corykim0829 approved these changes
수고하셨습니다! 😀
아래 질문에 대한 내용은 다음 스텝 진행하면서 수정하면 좋을 것 같습니다! 

> forced unwrapping 을 사용한 이유는, 유닛 테스트 에서 getData() 의 수행에 오류가 있을 때, 그 에러에 대한 description 을 출력 하도록 getData() 메서드에 설정 해주었기 때문입니다.
if let 또는 guard let 으로 바인딩 처리할 시 else 문에서 결과가 nil일 경우를 처리한다고 하더라도 test 코드를 실패 시키려면 print 나 return 을 사용하면 안되던데, 이 부분 또한 어떻게 처리 해야할 지 모르겠습니다.. " ! " 로 처리 했을 때 만큼 간결한 코드가 나오지 않을 것으로 판단되어, " ! " 를 사용하지 않았을 때 코드 상 어떤 이점이 있을지 궁금합니다 ! 또한 테스트 코드에서도 강제언래핑을 지양하고 방어적인 코드를 짜야하는 지도 궁금합니다 !

➡️ 넵 일단은 테스트 코드에서도 똑같이 강제 언래핑은 지양하는게 좋습니다!
현재 테스트가 어려운 이유는, 테스트가 잘 되지않는 구조라는 걸 뜻하기도 합니다. 또한 현재 테스트 코드는 전체적으로 테스트 코드를 위한 테스트코드 같은 느낌이 듭니다!

제가 봤을 때에는 getData()함수에서 안에 에러가 발생하게 됐을 때 print만 하고 끝나버리면 안되고, 예외 처리 로직이 필요합니다. 이 예외 로직이 잘 구현된다면, 테스트 코드에서도 예외 처리도 가능한 부분입니다.

그리고 json 같은 데이터 디코딩을 테스트할 때에는 하나 데이터를 직접 비교하는 건 번거로운 작업으로 보입니다. 직접 비교하는 법이 아닌 다른 방법으로 테스트를 해보면 좋을 것 같습니다!

2022-06-15 13:48 UTC, merged