만국박람회 [STEP 1: Kay, 나이든별]
yagom-academy/ios-exposition-universelle pull request #174
Opened 2022-06-14 06:18 UTC by KayAhnDS

안녕하세요 @jryoun1 !
만국 박람회 첫번째 Pull - Request 보내드립니다. 잘 부탁 드립니다!🙇🏻‍♂️

### 작업한 내용
* 만국박람회 포스터를 위한 모델 타입을 제작했습니다.
    * JSON 파일 내 스네이크 케이스 or 축약형으로 되어있는 프로퍼티가 없어 CodingKey를 사용하지 않았습니다.
* 만국박람회 개별 출품작을 위한 모델 타입을 작성했습니다.
    * JSON 파일 내 스네이크 케이스 or 축약형인 JSON 키 값을 스위프트의 네이밍에 맞게 변환 하기 위해서 CodingKey 프로토콜을 채택하는 열거형을 생성 했습니다.

### 고민한 점 및 조언을 얻고 싶은 점
* `Content.json` 파일의 역할에 대해 고민했습니다.
    * 처음에는 해당 파일도 모델링해주어야 하나 고민했습니다. 하지만 이미지 배율에 관한 정보만 가지고 있었기 때문에 위화감을 느꼈습니다. 해당 파일이 하는 역할에 대해 검색해본 결과, [이 문서](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/Contents.html)를 발견했습니다.
    * 저희가 지금까지 파악한 바대로라면, `Content.json`은 Xcode가 컨텐츠를 자동으로 조절해주기 위해, 예를 들면 적절한 크기의 이미지를 앱에 적절히 적용하기 위해, 사용하는 파일 경로의 의미 이상은 아니라는 것입니다.
* 모델에서 이미지를 컨트롤하는 방법에 대해 고민했습니다.
    * 처음 모델을 작성할 때는, `UIImage`의 형태로 이미지를 모델이 직접 들고 있어야 한다고 생각했습니다. 하지만, `UIImage`를 직접 사용할 시 `Codable` 프로토콜에 부합하지 않았습니다.
    * 이미지의 주소(이 경우에는 파일의 주소)를 모델이 들고 있으면서, 이후 `UIImageView`에서 필요할 때마다 해당 주소를 바탕으로 이미지를 불러오는 방법을 사용하기로 하고, `imageAddress` 프로퍼티를 지정해줌으로써 해당 프로퍼티에 주소 정보가 담기게끔 했습니다.

2022-06-14 13:25 UTC, jryoun1 requested changes
@KayAhnDS @OldStarKR 
두 분 모두 step1을 진행하시느냐고 고생많으셨습니다.
2주 동안 만국박람회 프로젝트를 리뷰하게 되어서 영광이네요 ㅎㅎ 

제가 드리는 리뷰는 절대 정답은 아니니 의견 및 질문들이라고 생각해주시고, 두 분의 의견을 편하게 말씀해주시면 감사하겠습니다 🙇🏻‍♂️

## 고민하신부분에 대한 답변
> 1. Content.json 파일의 역할에 대해 고민했습니다

두 분이 찾아보시고 말씀해주신 것처럼 저도 해당 파일에 대한 모델링은 필요 없다고 생각합니다 🙏🏻

> 2. 모델에서 이미지를 컨트롤하는 방법에 대해 고민했습니다.

이 부분에 대해서는 아래 리뷰에서 추가적으로 코멘트를 남겨두었습니다. 확인 부탁드려요~

2022-06-14 13:25 UTC, jryoun1 commented on Expo1900/Expo1900.xcodeproj/project.pbxproj
> +				4F982FBA28582B4500FCB18D /* Assets */,
파일별로 들어갈 폴더들을 잘 나눠주셨네요 👏

2022-06-14 13:25 UTC, jryoun1 commented on Expo1900/Expo1900/Assets/Assets.xcassets/bangjja.imageset/Contents.json
> +{
벌써 assets을 import 해주셨네요! 좋습니다 👍🏻

2022-06-14 13:25 UTC, jryoun1 commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +struct ExpositionEntry: Decodable {
궁금한 점이 있습니다 🙋‍♂️
파일을 생성 했을 때 생기는 아래 예시와 같은 주석을 삭제하신 특별한 이유가 있을까요? 👀
```swift
//
//  Expo1900 - ViewController.swift
//  Created by yagom. 
//  Copyright © yagom academy. All rights reserved.
// 
```

2022-06-14 13:25 UTC, jryoun1 commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +    let imageAddress: String
Address라는 네이밍보다는 Url을 일반적으로 사용하는 것 같습니다.
이번 프로젝트에서는 네트워크 통신을 하면서 실제 Url에서 이미지를 다운 받아오는 것이 아니라 assets에 있는 이미지를 가져올 것 같은데, address로 네이밍을 하신 이유가 있을까요? 

실제 imageAddress에 들어올 값 들이 어떤 것인지 생각해보고 네이밍을 해보시면 좋을 것 같아요 🙏🏻

2022-06-14 13:25 UTC, jryoun1 commented on Expo1900/Expo1900/Models/ExpositionPoster.swift
> +struct ExpositionPoster: Decodable {
Decodable을 사용해보셨네요 👏
Decodable은 어떤 프로토콜인가요?

2022-06-14 13:25 UTC, jryoun1 commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +    let imageAddress: String
추가로 고민하신 부분이 UIImage 타입을 직접 가지지 않는 것이였습니다. 
따라서 이미지를 String으로  `ExpositionEntry` 타입에서 정의하게 되었고, 실제로 사용을 하는 시점에는 ViewController에서 UIImage 타입으로 변경해야 될 것 같아 보입니다. 이러한 변환 작업을 VC에서 하는 것이 아니라 model에서 할 수 있도록 역할로 옮겨보는 것은 어떨까요? 🤔

즉, `ExpositionEntry` 타입 내부에 UIImage 타입을 반환해줄 수 있는 함수나 연산프로퍼티가 있는 것은 어떠할까요?

2022-06-14 13:25 UTC, jryoun1 commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +    let shortDescription: String
축약어를 사용하지 않은 점 매우 좋습니다 👍🏻

2022-06-14 13:25 UTC, jryoun1 commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +    enum CodingKeys: String, CodingKey {
CodingKey를 사용해보셨네요 👏
CodingKey는 어떤 프로토콜인가요?

2022-06-14 13:25 UTC, jryoun1 commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +    enum CodingKeys: String, CodingKey {
internal로 선언되어야할 이유가 있을까요? 👀

2022-06-15 05:08 UTC, KayAhnDS commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +struct ExpositionEntry: Decodable {
그동안 프로젝트를 하면서 불필요한 신원의 노출도 막고 코드를 실행시킬때 필요하지 않은것같아 지워왔는데 달아주신 코멘트를 생각해보니 이름만 바꿔줘도 괜찮았을것 같습니다!

2022-06-15 05:11 UTC, OldStarKR commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +    let imageAddress: String
말씀해주신 대로 원래는 `imageURL`이라는 네이밍을 자주 사용하는 것으로 알고 있습니다! 다만, 해당 어셋이 말씀해주신 대로 서버에서 가져오는 것이 아니고 로컬에서 가져오는 것이기 때문에, 파일 '주소'를 담고 있고 그것으로 불러온다는 점에 착안해 `imageAddress`라는 네이밍을 사용하게 되었습니다. 로컬에서 파일을 불러오는 경우에 어떤 네이밍을 사용하면 좋을지에 대해서는 아직 저희가 분명하게 파악하지 못한 부분이 있는 것 같습니다🥲 향후 프로젝트 진행 과정에서 이에 대해 좀 더 알아보고 수정하도록 하겠습니다!!

2022-06-15 05:19 UTC, KayAhnDS commented on Expo1900/Expo1900/Models/ExpositionPoster.swift
> +struct ExpositionPoster: Decodable {
JSON 파일처럼 외부에서 사용하는 객체의 형태를 프로젝트 내부에서 사용할 수 있는 형태로 사용하기 위해 주어진 디코더를 통해 새로운 인스턴스를 생성하는 프로토콜 타입 입니다.

2022-06-15 05:25 UTC, OldStarKR commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +    enum CodingKeys: String, CodingKey {
[공식 문서](https://developer.apple.com/documentation/swift/codingkey)에 따르면, `CodingKey`는 인코딩과 디코딩을 할 때 키로써 사용될 수 있는 타입이라고 써 있습니다. 

이번 프로젝트에서 사용하는 json의 경우, key-value형식으로 데이터가 저장되어 있는데, 이 key가 snake case로 표기되어 있어, Swift의 컨벤션과 다릅니다. 디코딩의 목적은 외부 데이터 타입을 Swift 프로젝트 내부에서 사용하고자 하는 것이므로, 타입 내부 프로퍼티의 네이밍은 Swift의 룰인 camel case를 준수할 필요가 있습니다. 그래서 외부 데이터 형식에서 알맞은 key와 매칭하기 위해 Coding Keys를 별도로 지정하고, `CodingKey` 프로토콜을 통해 이를 인식할 수 있게 해 주는 것으로 알고 있습니다.

2022-06-15 05:31 UTC, OldStarKR commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +    enum CodingKeys: String, CodingKey {
이 경우의 `CodingKeys`는 `ExpositionEntry` 타입만을 위한 코딩 키라고 생각하여 해당 타입 안에 작성해 주었습니다. 글로벌하게 해당 코딩키가 쓰인다고 하기에는, 저희가 함께 작성한 `ExpositionPoster`는 json 안에서도 다른 코딩 키를 사용하고 있기 때문에 이렇게 생각했습니다.

2022-06-15 06:17 UTC, OldStarKR commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +    let imageAddress: String
이미지 이름을 통해 Assets에서 이미지를 가져온다는 것에서 착안하여, `UIImage(name:)` 메서드를 사용하여 `UIImage`를 반환하는 연산 프로퍼티를 새로 작성해 주었습니다! 제시해주신 방법이 저희가 미처 생각해보지 못한 방법이었습니다😅 감사합니다!

2022-06-15 15:20 UTC, jryoun1 commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +struct ExpositionEntry: Decodable {
불필요한 신원의 노출에 대해서는 저도 생각해 본 적이 없긴한데, 굳이 막아야할 필요가 있을까요? 
git을 사용한다면 author를 통해서 누가 언제 커밋 했는지, 생성했는지도 알 수 있기 때문에 해당 부분을 지우는 것이 신원의 노출을 막아주는지는 잘 모르겠습니다 🙏🏻
![image](https://user-images.githubusercontent.com/45090197/173864163-df7832d2-eeed-4a0f-a684-3e5fbe1e753b.png)

오히려 `ctrl + shift + f` 로 파일을 찾거나 할 때 파일명이 없거나, 해당 파일에 선언된 타입과 동일하지 않다면 문제가 생기는 경우는 종종 본 것 같습니다.

2022-06-15 15:23 UTC, jryoun1 commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +    let imageAddress: String
이번에 학습할 필요는 없다고 생각되지만 추후에 프로젝트를 진행하실 때 여러 디자인 패턴(e.g. MVVM, MVP, MVI 등)에 대해서 공부를 하시게 될 것 같은데, 
지금부터 역할을 분리하시는 기준을 잡고 연습하신다면 도움이 될 것 같습니다. 🙏🏻 
물론 디자인 패턴은 이번 프로젝트에서는 중요한 것은 아니기 때문에 나중에 시간이 나실 때 확인해보시면 좋을 것 같네요 ㅎㅎ

2022-06-15 15:25 UTC, jryoun1 commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +    enum CodingKeys: String, CodingKey {
외부에서 해당 CodingKeys 열거형 타입에 접근할 일은 없기 때문에 접근 제한을 더 엄격하게 해도 괜찮을 것 같습니다 🙏🏻

2022-06-15 15:30 UTC, jryoun1 approved these changes
수정해주신 부분 확인했습니다! 
간단히 몇 가지 코멘트와 답글로 남겨주신 부분에 대댓글 남겼습니다 🙏🏻

해당 부분들은 이번 step1이 아니라 다음 step에서 반영되어도 될 것 같아서 step1은 여기서 머지하도록 하겠습니다!
다음 step도 화이팅입니다 💪🏻

2022-06-15 15:30 UTC, jryoun1 commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +    let imageName: String
실제로 VC에서는 작성해주신 thumbnail 연산 프로퍼티를 사용할 것 같은데 `imageName`은 internal이 아니지 않아도 될 것 같은데 어떻게 생각하시나요? 🤔

2022-06-15 15:30 UTC, jryoun1 commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +    var thumbnail: UIImage? {
질문이 있습니다 🙋‍♂️
함수를 작성하셨다가 연산프로퍼티로 변경하셨는데, 함수와 연산프로퍼티를 사용하시는 기준이 따로 있을까요?

2022-06-15 15:30 UTC, merged

2022-06-16 05:27 UTC, OldStarKR commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +    var thumbnail: UIImage? {
연산 프로퍼티와 메서드 중 하나를 고르는 기준으로써 크게 두 가지를 가지고 있습니다. 하나는 안에서 복잡한 연산을 거치는지 여부이며, 다른 하나는 매개변수가 필요한지 여부입니다. 

`thumbnail` 프로퍼티의 경우, 외부에서 별도의 매개변수를 받을 필요는 없습니다. 이미지 이름에 대한 프로퍼티만 가지고도 이미지를 반환할 수 있기 때문입니다. 또한 내부에서 복잡한 연산이 이루어지지도 않는다고 생각했습니다. 그래서 최종적으로 연산 프로퍼티를 사용하는 것이 좋겠다고 생각했습니다.

2022-06-16 05:28 UTC, OldStarKR commented on Expo1900/Expo1900/Models/ExpositionEntry.swift
> +    let imageName: String
말씀해주신 대로 `imageName`은 이제 `private`해져도 되겠다는 생각이 들었습니다! 항상 세세한 부분에 주의해서 작업해야 하는데, 이 케이스에서는 놓친 것 같네요🥲