만국박람회 [Step2] unchain, bard
yagom-academy/ios-exposition-universelle pull request #176
Opened 2022-06-16 08:43 UTC by bar-d

@protocorn93 
안녕하세요 콘!!  
우선 두 방식의 프로젝트 중 스토리보드로 구현한 프로젝트를 PR보내겠습니다!  
두 방식 모두 리뷰해주셔서 감사합니다!🙇‍♂️🙇‍♂️
이번 스텝도 잘 부탁드리겠습니다!

---
## 고민한점

### `XCode 자체 오류`

&nbsp;&nbsp;&nbsp;  <img src="https://i.imgur.com/uGjVTvP.gif" width="250" height="450"/>  

- 처음 네비게이션 바 아이템의 백 버튼의 텍스트를 한국의 출품작으로 변경을 해주었는데, 첫번째 셀에서만 동작하지 않는 일이 발생했습니다    
아무리 봐도 코드에 문제가 없는 것 같아 클린 빌드도 해보고, XCode를 종료하고 켜보았는데도 전혀 달라진 점이 없었습니다;;  
- 해결방법
-> unchain이 pull을 받아 실행해보니 정상적인 작동을 하더라고요🥲  
추후에 언체인이 코드 작성 후 push를 한 후 제 레포지토리에 pull을 하니 정상적인 작동을 하였습니다..

### `오토레이아웃`
- 아직 오토레이아웃에 대한 정확한 개념이 잡힌 것 같지가 않아 스토리보드로 될 것 같은 방식으로 구현 후, 이것저것 시도해보며 오토레이아웃 작성  
테이블 뷰 및 스크롤 뷰에서 뷰를 추가하지 않으면 스크롤링이 되지 않는다는 것을 늦게 깨달아 프로젝트를 진행하는데 시간이 오래 걸렸습니다

### `huggingPriority, ResistancePriority`
- 첫번째 뷰컨트롤러에서 이미지 뷰와 버튼 간의 크기를 설정하는 과정에서 버튼에 텍스트가 추가 되었을 때 버튼의 컨텐츠가 양 옆의 이미지뷰에 밀리면서 두줄로 나오는 현상이 발생해서 이를 해결하기 위해 huggingPriority, ResistancePriority를 사용해보려 했지만 변화가 없었습니다. 그래서 이미지뷰의 크기를 줄여서 해결을 했습니다. 자세한 오토레이아웃 설정은 STEP3에서 진행하기 때문에 다시 공부해서 다음 스탭에서 적용해 보겠습니다. 

---

## 궁금한점

### `Json Parsing`
>@bar-d @unchain123 지금은 NSDataAsset을 통해 파일을 불러오고 있는데요. Bundle.main.path를 사용해서도 파일을 읽어서 파싱을 할 수 있는데요. 전자를 선택하신 이유도 궁금하네요!

처음 파싱을 할 때 사용한 방법은 String파일을 통해 JSON 목데이터를 만들어서 Bundle.main.path을 찾게 되었는데,
현재 콘의 피드백을 통해 JSON데이터를 Assets 카탈로그에 저장을 하여 파일을 불러오고 있습니다.
따라서 NSDataAsset을 통해 Assets 카탈로그에서 불러오는 방식을 택했습니다
-> STEP1에서 답변 드렸는데 말씀이 없으셔서 다시 한번 올렸습니다..!

### `폴더 정리`
- 현재 MVC 패턴을 적용하여 폴더를 정리하고 있는데, `AppDelegate`, `SceneDelegate` 파일은 생명주기를 관리해주는 파일인데 `Model` 폴더에 넣어야 할까요?
- 또한 `Assets.xcassets` 파일이나, `info.plist`파일은 어디에 넣어두어야 할까요?   
아니면 폴더 내에 넣지않고 그대로 두면 되는 것일까요?

### `타이틀 개행`
- 현재 첫번째 메인 화면에서 `파리 만국박람회 1900(L'Exposition de Paris 1900)` 이라는 텍스트는  프로젝트 명세서에 있는 사진을 보면 한글과 영어를 따로 개행시켜 주었습니다.
- 이 것을 구현하기 위해서는 JSON 파일을 파싱한 값을 통해 불러오기에 파싱한 데이터를 통해 들어온 `파리 만국박람회 1900(L'Exposition de Paris 1900)`  문자열을 `(` 기준으로 `split(separator:)` 함수를 사용하여 분리해주고 빠진 `(` 문자열을 따로 넣어주었습니다.  
현재 저희가 이 문제를 해결하기 위한 방식으로는 위에서 말씀드린 `split`함수를 이용하는 방법과 `replacingOccurrences(of:, with:)`함수를 사용하여 `of` 매개변수에 `"("`를 넣어주고 `with` 매개변수에 `"\n("`를 넣어주는 방식이 있을 것 같습니다  
하지만 하면서도 이게 맞는 방법인가 싶어서 다른 방법으로 할 수 있는지 궁금합니다!

2022-06-17 14:28 UTC, protocorn93 requested changes
두 분 모두 고생하셨어요! 👍 이번엔 코멘트가 조금 길 것 같네요! 

## 궁금한점

> Json Parsing

네네 확인했습니다! 제가 추가 코멘트를 남기지 않았네요! 👍

> 폴더 정리

보통 저는 `AppDelegate`, `SceneDelegate`, `info.plist` 앱의 라이프사이클이나 전체 동작과 관련된 파일들을 `Applications`라는 디렉토리로 묶곤해요! `Assets`나 와 같은 리소스 성격의 파일들은 `Resources`로 묶곤해요.

> 타이틀 개행

제가 생각했을 때는 이 부분이 프로젝트 명세는 아니라고 생각이 드네요. 단순히 아이폰 미니 해상도이고 UILabel가 화면 가운데 위치하며 UILabel의 텍스트 정렬이 가운데이기에 예제 이미지처럼 나온 것이라고 생각해요. 그렇기 때문에 크게 신경쓰지 않으셔도 되는 부분이라고 생각이 드네요. 

만일 저게 프로젝트 명세였다면 title과 subtitle로 두 부분을 나눠서 제공했을 것이구요. 그렇기 때문에 이 부분 구현에는 신경을 쓰지 않으셔도 될 것 같지만 그럼에도 개행을 하고 싶으시다면 말씀하신 방버으로 직접 원하는 위치에 적절히 개행문자를 삽입하는 것이 방법일 것 같아요. 다만 이러한 방법은 유연한 방법은 아니겠죠! 해당 영역의 값이 달라지면 소용이 없을테니까요~! 

---

## 말씀드리고 싶은 부분

1. 추상화와 역할의 분리 

먼저 현재 작성된 코드는 아키텍처와는 별개로 유연하지 못한 구조를 갖고 있어요. 유연하지 못하다는 것은 객체가 다른 객체의 내부 구현이나 정보를 알고 있다는 것이에요. 이렇게 되면 유연성이 떨어지고 요구사항이 바뀌었을 때 공수가 크며 극단적으로는 요구사항 변경에 대응하지 못할 수도 있어요. 두 분의 코드에서 대표적으로 `JSONParser`가 그 예가 될 수 있을 것 같아요. 

현재 프로젝트의 요구사항은 파일에서 읽어오는 것인데, 만일 서버에서 내려준다면, Core Data에 저장된 것을 불러와야 한다면 어떻게 대응할 수 있을까요? 

현재 리스트 화면에서 원하는 것은 화면에 뿌려줄 데이터입니다. 그 화면이 데이터는 원래 JSON 형식으로 제공되고 있으며 이는 파일에 저장되어 있다는 사실은 몰라야 합니다. 단순히 화면에 뿌려줄 데이터의 배열을 원할 뿐이죠. 즉 추상화가 필요해요. "어디서 어떻게 주던 나는 모르겠고 데이터만 있으면 된다!"가 그 화면이 요구하는 것이에요. 추상화를 하기 위해선 두 가지를 구분할 수 있어야 해요. 

1. 변하는 것
2. 변하지 않는 것 

이 상황에서 **변하는 것은 데이터의 저장소**겠죠. 로컬 파일, Core Data, 서버 등 그리고 **변하지 않는 것은 특정 데이터 타입의 배열을 반환하는 것**이에요

이를 코드로 대략적인 코드로 작성해보면 다음과 같아요. 

```swift 
protocol EntryListRepository { 
  func fetch() -> [EntryList]
}

// 파일로 부터 데이터 추출

final class FileEntryListRepository: EntryListRepository { 
  func fetch() -> [EntryList] { 
    // NSDataAsset을 통해 추출
  }
}

// 서버로부터 데이터 추출

final class FileEntryListRepository: EntryListRepository { 
  func fetch() -> [EntryList] { 
    // URLSession을 통한 추출
  }
}

final class EntryListViewController: UIViewController { 
  init(entryListRepository: EntryListRepository) { 
    self.entryListRepository = entryListRepository
  }
}
```

이렇게 되면 `EntryListViewController`는 요구사항이 바뀌어도 코드가 변경을 하지 않아도 되요. 단순히 `EntryListRepository`를 따르고 객체를 만들어 주입해주면 되기 때문이에요. 

테스트 코드도 마찬가지에요. `FileEntryListRepository`는 테스트 대상이 아니에요. 이를 사용하는 화면을 테스트할 때 가짜 데이터를 제공하는 `MockEntryListRepository`를 구현해서 가짜 데이터를 집어 넣어 `EntryListViewController`를 테스트하는 것이죠! 

아직은 제가 하는 말이 모두 이해가 되진 않을거에요. 다만 추상화와 의존성 주입에 관해서 학습을 해보시는 걸 권장드려요. 객체지향의 사실과 오해, 오브젝트 이 두책은 강력 추천하구요. 


## 스토리보드 나누기에 관한 피드백에 해당하는 코드

먼저 스토리보드를 사용하지 않고 코드로 화면을 그리는 대표적인 이유는 두 가지에요. 

1. 협업이 어렵다, 머지 충돌이 일어나기 쉽고 이를 해결하기가 어렵다. 
2. 코드 리뷰가 거의 불가능하다. 실행해서 직접 돌려보기 전까진 알 수 없다. 

그럼에도 불구하고 스토리보드를 사용하는 회사들은 많습니다. 하지만 이들 회사들을 각각 규칙이 있는데 대부분은 아래와 비슷해요.

1. 하나의 스토리보드 파일에는 하나의 뷰컨트롤러만 존재한다. 
2. 화면 이동은 코드로 한다. 
3. 하나의 스토리보드에서 한 사람만 작업한다. 

여기서 두 분이 적용해보셨으면 하는 부분은 1번, 2번인데요. 이 부분에 대해서는 한번 직접 학습을 해보시면 좋을 것 같아요.  `UIStoryboard` 클래스를 통해 해당 스토리보드의 뷰컨트롤러를 생성할 수 있습니다. 

[이 글](https://www.hackingwithswift.com/example-code/uikit/how-to-use-dependency-injection-with-storyboards)을 읽어보시면서 관련된 키워드들을 학습해보시면 좋을 것 같아요.

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Model/Extension/Int+extension.swift
> +    }
`formatNumber`라는 메서드명이 너무 모호한 것 같아요. `.decimal`을 고정해서 사용할 것이라면 메서드 네이밍을 보고도 알 수 있어야 할 것 같아요.

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Model/JSONParser.swift
> +struct JsonParser {
`JSONParser` 네이밍이 더 적절해보여요!

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/Cell/CustomTableViewCell.swift
> +    var cellImage: UIImageView?
접근제어자들이 필요하지 않을까요?! (나머지 클래스들의 접근제어자도 한번 확인 부탁드릴게요)

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/Cell/CustomTableViewCell.swift
> +    }
오버라이딩 하고 별 다른 코드가 없는데, 이 코드는 제거해도 되지 않을까요?

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        self.navigationController?.isNavigationBarHidden = true
`super.viewWillAppear(animated)` 호출해주지 않아도 될까요?

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        firstNavigationItem?.backButtonTitle = "메인"
전체적으로 가독성이 떨어지는 것 같아요. 역할별로 적절한 네이밍의 메서드로 나눠보는게 좋을 것 같아요.

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        cell.detailedDescription = entryList[indexPath.row].description
셀의 UI에 직접 접근해서 값을 할당해주는건 좋지 않은 방법이에요. 셀에서 보여줄 데이터를 하나의 타입으로 묶어서 메서드를 통해 전달하는 것이 적절해요. 

```swift
struct CellViewModel { 
  let value1: String 
  let value2: String
  ...
}

...

cell. configure(viewModel: viewModel)

```

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        cell.detailedDescription = entryList[indexPath.row].description
UI는 최대한 숨기는게 바람직해요. 어떻게 어디에 그려줄지는 해당 뷰가 내부적으로 판단한는게 옳습니다. 객체의 상세 구현은 최대한 숨겨주는 것이 바람직해요!

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        self.navigationController?.isNavigationBarHidden = false
이 영역도 역할별로 메서드로 나눠보면 좋을 것 같아요. 한 줄 짜리 코드 메서드라도 그 네이밍이 주는 의도가 명확하다면 전 그 방법을 선택할 것 같아요.

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +    let entryList = try! JsonParser.parseEntryList()
`viewDidLoad` 시점에 적절하게 생성해주는게 좋을 것 같아요. 그리고 강제 언랩핑은 왠만하면 지양하시는게 좋아요!

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Model/JSONParser.swift
> +    }
### 역할과 추상화에 관한 피드백에 해당하는 코드

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +    let entryList = try! JsonParser.parseEntryList()
### 역할과 추상화에 관한 피드백에 해당하는 코드

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/DescriptionViewController.swift
> +    var imageToSet: UIImageView?
`-ToSet`이라는 네이밍은 적절해보이지 않은 것 같아요

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/DescriptionViewController.swift
> +    var imageToSet: UIImageView?
### 스토리보드 나누기에 관한 피드백에 해당하는 코드

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/DescriptionViewController.swift
> +        self.detailedDescription.text = self.textToSet
### 스토리보드 나누기에 관한 피드백에 해당하는 코드

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +    }
### 스토리보드 나누기에 관한 피드백에 해당하는 코드

2022-06-17 14:28 UTC, protocorn93 commented on Expo1900/ParsingTests/ParsingTests.swift
> +    }
### 역할과 추상화에 관한 피드백에 해당하는 코드

이전 스탭에선 너무 길어질 것 같아 언급을 하지 않았지만, 사실 현재 작성된 테스트 코드는 사실 불필요한 코드에 가까워요. 애플이 제공하는 코드를 테스트 하고 있다고 봐도 무방해요. 

사실 프레임워크의 코드를 우리가 테스트할 필요는 없어요. 이 부분에 관해서는 코멘트로 좀 더 자세히 남겨놓을게요.

2022-06-21 18:13 UTC, bar-d commented
@protocorn93 
안녕하세요 콘! 기존에 존재하던 브랜치를 원격 저장소와 로컬 저장소에서 지워주고 새로 같은 이름의 `step2`브랜치를 파서 진행을 하고 있었습니다.  
그런데 오늘 PR을 보내기 위해 확인을 해봤더니, 이전 PR에 커밋이력이 남아있어서 PR문을 새로 안보내도 될 것 같습니다..!  
생각보다 늦게 제출해서 죄송합니다 🙇‍♂️🙇‍♂️

### `네임스페이스 생성`
- 리터럴로 적혀있는 문자열들을 열거형을 사용해서 이름을 바꿔 주었습니다. 코드를 보는 사람이 직관적으로 이해 할 수 있는 이름으로 변경해주었습니다.

### `추상화와 역할의 분리`
- 현재 이전 코드와 달리 `JSONParser` 구조체에 `DataRepository` 프로토콜을 생성하여 채택을 해주었습니다.  
- `DataRepository` 내에 제네릭을 사용하여 타입함수인 fetch() 함수를 만들어 주었고, 각 뷰 컨트롤러 내에 필요한 타입을 넣을수 있도록 만들어 주었습니다.

- 각 역할별로 메서드로 분리해 넣어주었습니다.
- 코드의 분리를 안해주어 콘의 말씀대로 코드가 많이 지저분해 보여서 이번에는 역할분리에 신경을 써주면서 코드를 작성하였습니다.

### `tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)`
- 각 셀에 대한 정보를 넘겨주기 위해 `UITableViewDelegate` 내에 있는 `optional method`인 메소드를 사용해주었습니다.

## 트러블 슈팅
### `테이블 뷰 셀`
- 테이블 뷰 셀을 선택 후 다시 돌아왔을 때 선택된 색깔이 남아있는 현상이 발생하였습니다.
```swift
self.tableView.deselectRow(at: indexPath, animated: true)
```
- deselfectRow를 사용해서 해결 했습니다.

### `branch 관련`
- 작업중이던 step2브랜치에 다른 캠퍼의 커밋 내역이 들어와 있는 것을 확인했습니다.
- 문제가 생긴 브랜치를 지우면 될 것이라고 생각하고 브랜치를 지웠습니다.
- PR메세지에 브랜치를 지운 이력이 남았고 그 뒤로 커밋내역이 업데이트 되지 않았습니다.
- 그래서 새로운 브랜치를 같은이름으로 파서 다시 커밋을 했는데 이 내역들이 다음날 확인하니 그대로 다 입력이 되어 있었습니다.
- 명확히 해결 하지 못했고 로컬에 있는 파일을 지우고 새로 클론 받아서 사용했습니다.

### `데이터 넘겨주기`
- 각 셀 별로 데이터를 넘겨주기 위해서 `EntryListViewController` 내 tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) 함수와 `entryList`프로퍼티를 통해서 데이터를 `DescriptionViewController`내 `entryList`프로퍼티로 주입해주려고 하였습니다. 
- 저희가 간과한 점은 두 뷰컨트롤러의 프로퍼티의 이름은 같지만 타입이 하나는 `[EntryList]`이고, `EntryList`였습니다.
- 따라서 `EntryListViewController`의 `entryList`프로퍼티에 접근을 하여 `[indexPath.row]`를 사용하여 각 셀에 대한 `entryList`로 넘겨줘야 했는데, 배열로 접근하여서 값이 nil로 나오고있다는 것을 한참 시간이 지나서야 확인했습니다.

## 고민한점

### `스토리보드 나누기`
- 스토리보드를 사용하는 회사들에게 어느 정도 컨벤션이 있다는 것을 콘을 통해 알게되었고,  그 컨벤션을 적용해보려고 노력했습니다.
- 하나의 스토리보드 파일에는 하나의 뷰컨트롤러만 존재하게 하기위해서 파일을 나누었는데, 어떤 식으로 네비게이션 컨트롤러를 넘겨줘야 하는지 고민을 했습니다. 
- 구글링을 하다 [콘의 블로그](https://baked-corn.tistory.com/40)를 찾게 되었고 참고하여 코드를 작성해보았습니다🙃
- 현 프로젝트에서는 storyboard reference를 사용하여 스토리보드 파일을 나누어주었습니다.


###

## 궁금한점

### `Test code`
- 콘이 말씀해주신 것처럼 저희가 기존에 진행한 테스트 코드는 애플이 구현해놓은 함수 그자체를 테스트하는 코드였기에 의미가 없는 테스트 코드였습니다.
- 그런데, 콘이 말씀해주신 것처럼 가짜 목데이터를 어떤식으로 구현해야하는지 아직 감이 오질 않습니다.
- JSON 파일의 목데이터를 만들어줘야 하는 것일까요?

### `show(_ vc: UIViewController, sender: Any?) vs  pushViewController(_ viewController: UIViewController, animated: Bool)`
- 네비게이션 컨트롤러 내 메서드에 이 두 메서드를 통해 뷰 컨트롤러를 넘겨줄 수 있는데, 두 메서드의 차이점이 있을까요? 
- 공식문서에서 보면은 `show`가 새로 생긴 메서드인 것 말고는 잘 모르겠습니다.
- 매개변수만 다른 것일까요?

### `self.title vs self.navigationController?.navigationBar.topItem?.title`
- 처음 계속 네비게이션 컨트롤러의 타이틀을 변경해주어서 후자의 방식을 택해 타이틀을 변경해주었습니다 하지만 마지막 뷰 컨트롤러 내에서 네비게이션 컨트롤러의 타이틀을 변경해 주었더니 두번째 뷰 컨트롤러의 타이틀이 변경이 되었습니다.
![](https://i.imgur.com/tbPlEKK.gif)

- 어떠한 뷰 컨트롤러 내에서 네비게이션 컨트롤러의 타이틀을 변경해주어도 어차피 하나의 네비게이션 컨트롤러를 사용하고 있기에 마지막 뷰컨트롤러에서 네비게이션 컨트롤러 타이틀을 변경해주는건 의미가 없다고 생각해 뷰 컨트롤러의 타이틀에 값을 넣어주었습니다. 그랬더니 아래의 그림처럼 잘 나오게 되었습니다.

![](https://i.imgur.com/nVbsFNO.gif)

2022-06-22 13:33 UTC, protocorn93 commented
수정된 코드 잘 읽어보았어요! 고생하셨어요 두 분 모두! 👏

## 고민한 점 

### 스토리보드 나누기

스토리보드를 나누어서 사용하는 방법은 정말 다양해요. 사용해주신 스토리보드 레퍼런스도 하나의 방법이 될 수 있죠. 제가 선호하는 방식은 다른데요. 저는 값을 넘겨줄 때 외부에서 인스턴스 프로퍼티에 직접 넣어주는 것을 굉장히 싫어해요. 최대한 생성자에서 모든 값을 넘겨주려해요. 내부 프로퍼티를 바깥에는 read-only로만 노출시키고 싶은거죠.
```swift
let object1 = SomeObject() 
object1.value = "Hello world"

let object2 = SomeObject(value: "Hello world")
```

그래서 저는 보통 `UIStoryboard` 인스턴스에 [instantiateInitialViewController(creator:)](https://developer.apple.com/documentation/uikit/uistoryboard/3213988-instantiateinitialviewcontroller) 이 메서드를 사용해서 스토리보드에 그린 뷰컨트롤러를 생성해요. 이를 사용하면 스토리보드에 그린 뷰컨트롤러 역시 생성자를 통해 값을 넣어줄 수 있기 때문이에요. 

[이 글](https://www.hackingwithswift.com/example-code/uikit/how-to-use-dependency-injection-with-storyboards)을 한번 참고해보셔서 다음 스탭에 적용해보시는 것도 권장드려요 

## 궁금한 점 

### Test code

네네 이 부분이 아직은 어렵고 이해가 잘 안가실 수 있는데요. 예를 들어볼게요. 할 일 목록을 갖고 할 일 목록에 대한 CRUD 작업을 처리하는 객체가 있다고 가정해볼게요. (`TodoListManager`) 대충 아래와 같은 모양새라고 해둘게요. 

```swift 
protocol TodoListManagerProtocol { 
  var todoList: [Todo] { get }
  func add(_ todo: Todo)
  func get(index: Int) -> Todo 
  func update(at index: Int, todo: Todo) 
  func remove(at index: Int)
}

protocol DataRepository { 
  func fetch() -> [Todo]
}

final class TodoListManager: TodoListManagerProtocol {
  private let repository: DataRepository

  init(repository: DataRepository) { 
    self.repository = repository
  }

  var todoList: [Todo] { 
    ... 
  }
  func add(_ todo: Todo) { 
    ...
  }
  func get(index: Int) -> Todo { 
    ...
  }
  func update(at index: Int, todo: Todo) { 
    ...
  }
  func remove(at index: Int) { 
    ...
  }
}
```
우리가 `TodoListManager`에게 기대하는 것은 CRUD 행위를 정확히 수행하는 것이죠. 여기서 사용하는 곳에선 목록을 서버에서 가져오던 로컬 DB에서 가져오건 상관없는거에요. `TodoListManager` 이 객체가 알아서 어디선가 가져오겠죠. 예를 들어 실제 앱에선 서버에서 가져온다고 했을 때, `TodoListManager`의 테스트 코드는 어떻게 작성해볼 수 있을까요? 

테스트 환경에선 실제 네트워크 호출을 하지 않아요. 테스트가 오래걸리게 될 것이고 우리가 테스트 해보고 싶은 응답을 매번 요청하거나 할 순 없는 일이죠. 비효율적이죠! 그래서 우리는 이때 가짜 데이터를 사용해요. 

위의 코드에서 DataRepository는 프로토콜이고 프로덕트 앱에선 이 프로토콜을 따르는 구현체가 실제 네트워크 호출을 실행하겠죠. 하지만 테스트 환경에선 이 프로토콜을 따르는 가짜 Mock 객체를 만들어서 TodoListManager에 주입해주면 우리가 원하는 값과 상황을 가정해가면서 테스트 코드를 작성할 수 있겠죠. 

```swift
final class MockDataRepository: DataRepository { 
  func fetch() -> [Todo] { 
    return [ 
      Todo(id: 1, value: "장보기"), 
      ....
    ]
  }
}
```

이런 의미에서 가짜 데이터를 말씀드린거에요! 


### show(_ vc: UIViewController, sender: Any?) vs pushViewController(_ viewController: UIViewController, animated: Bool)

[show(_ vc: UIViewController, sender: Any?)](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621377-show)의 문서를 읽어보면 나오지만 이 메서드는 각기 사용처에 따라 오버라이드해서 뷰컨트롤러를 display 해주는 방식을 커스터마이징하고 싶을 때 사용할 수 있어보여요. `UINavigationController`는 이 메서드를 오버라이딩해서 `push`를 구현하고 있는 것이구요. 

그렇기 때문에 현재 상황에선 `push`를 사용하는 것이 더 바람직해보여요. 


### self.title vs self.navigationController?.navigationBar.topItem?.title

내비게이션의 타이틀을 지정할 때는 보통 `self.title ="제목"`으로 지정해주곤해요.  `self.title`은 `UIViewController`의 프로퍼티에요 `UINavigationController`가 `UIViewController` 인스턴스들을 관리할 때 이 `title`을 이용해서 자신의 title을 보여주곤 하기 때문에 `self.title`을 사용하는게 좀 더 바람직할거같네요

2022-06-23 05:58 UTC, merged