만국박람회 [Step2] derrickkim0109, BaekGom
yagom-academy/ios-exposition-universelle pull request #177
Opened 2022-06-17 02:47 UTC by derrickkim0109

안녕하세요 그린! @GREENOVER 
고민한 점/궁금한 사항들에 대해서는 아래 리뷰 노트 카테고리에 적어두었습니다.

# 코드 리뷰 (작업 단위 피드백)

## 배경

### 메인화면
> ExpositionPost  Json 파일 의 데이터들을 위해 ExpositionPostEntity 타입을 생성하여 데이터로 받아주었고 두개의 StackView 통해서 보여주었습니다

### 한국 출품작 리스트
> EntryEntity Json 파일의 데이터들을 위해 EntryEntity 타입을 생성하여 배열로 데이터를 받아주었고 해당 부분을 TableView를 통해서 리스트를 보여주었습니다.  

### 상세화면 
> 이전 TableView에서 Json 파일로 불러온 데이터를 넘겨 받아서 해당 작품의 내용을 보여줍니다.

## 작업 내용

### 메인화면
- ExpositionPostView.swift를 만들어 Custom UI를 코드로 구현하였습니다.
- Json 데이터 프로젝트 요구사항에 맞게 처리하였습니다
```swift
func manufacture(_ content: ExpositionPost) -> String {
        switch content {
        case .title:
            let content = title.split(separator: "(").map{ String($0) }
            let result = content[0] + "\n(" + content[1]
            return result
        case .visitors:
            return "방문객 : \(visitors.setNumberFormatter()) 명"
        case .location:
            return "개최지 : \(location)"
        case .duration:
            return "개최 기간 : \(duration)"
        case .description:
            return description
        }
    }
```
- 메인화면에 나타낼 Json 데이터 파싱 및 데이터 뷰에 할당
```swift
    private func configureUI() {
        guard let expositionPostEntity = try? JsonParser<ExpositionPostEntity>.fetch("ExpositionPost") 
        else { 
               return
        }
        
        expositionPostView = ExpositionPostView(self, data:expositionPostEntity)
        self.navigationController?.navigationBar.isHidden = true
    }
```

### 한국 출품작 리스트
- ExpositionTableViewCell.swift를 만들어 Custom UI를 코드로 구현하였습니다. 

- 재사용되는 Cell의 프로퍼티들 초기화
```swift
    override func prepareForReuse() {
        super.prepareForReuse()
        entryImage.image = nil
        titleLabel.text = nil
        shortDescription.text = nil
    }
```

- Interface Builder를 사용하지 않는 경우 init(coder:)는 관련이 없으므로 호출되지 않음. 보일러 플레이트이다
- 해당 내용은 초기화시 제외되도록 설정
```swift
    @available(*, unavailable)
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
```    

- tableView의 높이가 내용에 맞게 커지도록 하는 설정
```swift
    expositionTableView.estimatedRowHeight = 100
    expositionTableView.rowHeight = UITableView.automaticDimension
```

- JSON Error
    - 메세지에 대한 부분은 사용하지 않고 있지만 추후 처리를 위해 생성하였습니다.
```swift
    enum JsonError: Error {
    case decodingFailure 
    }

    extension JsonError {
    var message: String {
        switch self {
        case .decodingFailure:
            return "JSON파일 디코딩을 실패했습니다.!"
        }
    }
    }

```

### 상세화면 

- 이전 페이지인 TableView에서 Row를 선택시 상세 화면의 entryEntity 프로퍼티로 Data를 넘깁니다. 
```swift
    var entryEntity: EntryEntity?
```

## 테스트 방법
- 서로 다른 시뮬레이터로 앱 실행시에 Autolayout이 잡히는지 확인합니다.

## 리뷰 노트
1. 메인화면에서 뷰의 마지막 부분인 버튼과 이미지들이 있는 뷰에서 이미지를 안쪽으로 넣기 위해서 빈 스택뷰를 바깥쪽(왼쪽/오른쪽)에 추가하였는데 이런 방법도 괜찮은 방법일까요?

2. 각 파일을 폴더별로 구분하여 두기 위해 고민하였고 Support file들을 Application과 Resources를 통해 구분하였습니다. 

3. 스택뷰 안에 존재하는 UIElement들도 저희가 한것처럼 top, bottom, leading, trailing을 지정하는 것이 맞을까요? 불필요한 부분들을 많이 설정한 것은 아닌가요? 

4. Main 스토리 보드를 제거하고 메인화면부터 뷰를 띄우는데요!. 화면을 .white로 설정하지 않으면 black 컬러로 화면이 설정됩니다. 해서 white로 화면 컬러를 지정해주니 status 바의 컬러가 white컬러로 남아있는 상황입니다. 어떻게 하면 될까요?

5. TableView를 코드로 작성해본 후 CollectionView를 통해서 list를 만들어볼 생각입니다. 시도해봐도 괜찮을까요?

6. 아직 Dynamic Types에 대한 공부를 하지 못하여 해당 부분에 대한 설정이 되어있지 않습니다.

## 스크린샷

|메인화면|한국 출품작 리스트|상세화면|
|:-:|:-:|:-:|
|<img src="https://i.imgur.com/JPkvrrN.gif">|<img src="https://i.imgur.com/DCCZnyb.gif">|![thirdScreen](https://user-images.githubusercontent.com/59466342/174215016-d71a490b-f294-42a4-8a74-513d3d279985.gif)|
|메인화면입니다 <br> "한국의 출품작 보러가기"<br>버튼 클릭시 다음화면으로 넘어 갑니다.| 한국의 출품작을 <br> 리스트로 나타내고 있습니다.<br> 작품 리스트 클릭시 상세보기 화면으로 전환 됩니다.|각 출품작의 <br>이미지와 상세설명이 있습니다.<br> 작품 설명 길이에 따라 스크롤 가능합니다|!

## 이번 프로젝트 핵심경험 안내

- [X] Codable을 채택하여 JSON 데이터와 매칭할 모델 타입 구현
- [X] 스네이크 케이스 또는 축약형인 JSON 키 값을 스위프트의 네이밍에 맞게 변환
- [X] 테이블뷰의 Delegate와 Data Source의 역할의 이해
- [X] 테이블뷰의 셀의 재사용 이해
- [X] 테이블뷰의 전반적인 동작 방식의 이해
- [X] 주어진 JSON 데이터를 파싱하여 테이블뷰에 표시
- [X] 내비게이션 컨트롤러를 활용한 화면 전환
- [X] 뷰 컨트롤러 사이의 데이터 전달
- [X] Codable을 채택하여 JSON 데이터와 매칭할 모델 타입 구현
- [X] 스네이크 케이스 또는 축약형인 JSON 키 값을 스위프트의 네이밍에 맞게 변환
- [X] 테이블뷰의 Delegate와 Data Source의 역할의 이해
- [X] 테이블뷰의 셀의 재사용 이해
- [X] 테이블뷰의 전반적인 동작 방식의 이해
- [X] 주어진 JSON 데이터를 파싱하여 테이블뷰에 표시
- [X] 내비게이션 컨트롤러를 활용한 화면 전환
- [X] 뷰 컨트롤러 사이의 데이터 전달
- [X] 오토 레이아웃을 적용하여 다양한 기기에 대응
- [ ] Word Wrapping / Line Wrapping / Line Break 방식의 이해
- [ ] 접근성(Accessibility)의 개념과 필요성 이해
- [ ] Dynamic Types를 통해 텍스트 접근성 향상

2022-06-17 06:24 UTC, GREENOVER requested changes
@Baek-Gom-95 @derrickkim0109 
두분 스텝2 빠르고 아주 정확하게 잘 해주셨네요!
고생 너무 많으셨습니다👍👍👍
특히 뷰를 코드로 전부 구현해주시면서 스텝3의 과정이였던 오토레이아웃까지 체험해보고 적용해보셔서 아주 더 퍼펙트하네요!
전체적으로 코드들의 가독성이 너무 좋고 로직 구성이나 흐름도 좋아 리뷰하기 편했습니다🥳
그럼 이번 리뷰는 조금 더 디테일한 부분에서 개선되면 좋을 부분들에 대해 드려보겠습니다!
***
### 칭찬 드리고 싶은 부분
- 코드로 뷰를 아주 짜임새 있게 잘 구성해주셨네요 💯
- 전체적인 코드 네이밍 및 코드 구성이 좋아 가독성이 최고네요 💯
- 관심사별 폴더 및 파일 관리가 아주 잘 되어있네요 💯
- 뷰와 뷰컨의 역할을 아주 잘 분리시켜 가져가 읽기 수월했어요 💯
- 접근 레벨을 적절히 잘 구분해 사용해주셨어요 💯
***
### 구현 하신 부분에 대한 저의 의견
1. 코드로 뷰를 작성하신 부분
- 두분은 코드로 뷰를 작성하시면서 어떤점이 좋았고 어떤 어려운점 및 단점이 있었는지 공유해주실 수 있을까요?🙋🏻
전체적으로 코드로 짜임새 있는 뷰를 아주 잘 작성해주셔서 놀랐습니다!
거기다 오토레이아웃까지 적용시켜주셔서 더할 나위 없어보였어요.
2. 프로젝트 요구사항에 맞는 JSON 데이터 가공
- 요 부분은 리뷰 코멘트로도 몇개 남겼지만 디테일한 부분 (폰트 등)에서 추가 처리가 필요한 부분이 있어보입니다..!
그 부분만 적용되면 좋을것 같아요ㅎㅎ
3. JSON Error
- 아이코 에러 처리에 대해 추후 구현을 하시려는 점을 알고 있었는데 제가 리뷰 코멘트에 하나 남겼네요🥲
가볍게 무시해주시고 다음 스텝에서 어떻게 처리되는지 보겠습니다..!
다만 현재 에러 enum 타입에서 디코딩 실패의 케이스만 있는데 추가적으로 다른 에러는 없을까요?
***
### 궁금하신 부분에 대한 저의 의견
1. 메인화면에서 뷰의 마지막 부분인 버튼과 이미지들이 있는 뷰에서 이미지를 안쪽으로 넣기 위해서 빈 스택뷰를 바깥쪽(왼쪽/오른쪽)에 추가하였는데 이런 방법도 괜찮은 방법일까요?
- 네! 저는 그러한 방식도 충분히 괜찮다고 생각하고 개인적으로 많이 사용하기도 합니다.
아시겠지만 anchor로 잡아줄 수도 있을것이고 지금 구현해주신것처럼 할 수 도 있는데 이건 스타일의 차이라고 생각합니다.
두분은 두 방법에서 지금 현재 구현된 빈 뷰를 넣어 레이아웃을 잡아주신 이유가 어떤건지 개인적으로 여쭤보고 싶어요!
근거있는 이유가 있다면 충분히 좋은 선택입니다.
코드에 정답은 없으니까요🙌
2. 각 파일을 폴더별로 구분하여 두기 위해 고민하였고 Support file들을 Application과 Resources를 통해 구분하였습니다.
- 너무 너무 좋네요.
파일 및 폴더를 관심사별로 아주 잘 구분시켜주셔서 가독이 좋고 탐색하기 너무 편리하네요!
저도 여러분들이 해주신 방향처럼 나눠서 그룹화를 시켜주고 있습니다🙌
3. 스택뷰 안에 존재하는 UIElement들도 저희가 한것처럼 top, bottom, leading, trailing을 지정하는 것이 맞을까요? 불필요한 부분들을 많이 설정한 것은 아닌가요?
- 레이아웃을 잡을때 현재 말씀하신 부분들이 스택뷰 안에서 anchor를 잡기에 필요한 부분들로 보여지는데 불필요하다고 생각하신 이유가 있으실까요~?
저는 필요하지 않을까 생각이 들어서요..! 당연히 그에 따라 코드가 많아지는것은 코드로 뷰를 짰기에 어쩔수 없는 부분이라고 봅니다🙋🏻
4. Main 스토리 보드를 제거하고 메인화면부터 뷰를 띄우는데요!. 화면을 .white로 설정하지 않으면 black 컬러로 화면이 설정됩니다. 해서 white로 화면 컬러를 지정해주니 status 바의 컬러가 white컬러로 남아있는 상황입니다. 어떻게 하면 될까요?
- 해당 질문에 대해 제가 정확히 이해하지 못한것 같아요..!
지금 status bar의 컬러가 white로 되어 있다는 말씀이 아래와 같은 부분을 말씀하시는거라 생각해볼께요.
근데 해당 프로젝트 요구사항이 지금 구현하신것과 동일하지 않나요?
status bar를 어떻게 하고 싶으신지 제가 잘 이해가 가지 않아서요..!
![스크린샷 2022-06-17 오후 3 20 45](https://user-images.githubusercontent.com/72292617/174237537-4e8f5355-69f0-4b5b-82ef-4df8cd89b4c8.png)
 만약 그걸 떠나서 status bar의 색상을 뷰 및 테마 컬러 스킴에 의존되지 않고 dark, light로 선택하고 싶으신거라면 간단히 해당 프로젝트 타겟에서 요 부분에서도 설정해줄 수 있습니다!
![스크린샷 2022-06-17 오후 3 19 44](https://user-images.githubusercontent.com/72292617/174237417-6e307717-d7af-4831-a476-2762ab9ac748.png)
 또한 코드로도 충분히 구현 해주실 수 있어요.
요 부분은 swift status bar라고만 구글링을 해봐도 정말 많은 레퍼들이 나오니 참고해보셔도 좋을것 같습니다!
그게 아닌 다른 질문이였다면 조금 더 구체적으로 말씀해주시면 감사하겠습니다🙇🏻
5. TableView를 코드로 작성해본 후 CollectionView를 통해서 list를 만들어볼 생각입니다. 시도해봐도 괜찮을까요?
- 어후 물론이죠 너무좋죠!
컬렉션뷰로도 리스트 표현이 충분히 가능하고 또 필요할때가 많으니 해보시면 좋을것 같습니다😀
6. 아직 Dynamic Types에 대한 공부를 하지 못하여 해당 부분에 대한 설정이 되어있지 않습니다.
- 아마 요 부분은 스텝3 혹은 그 후 스텝에서 나올 수 있는 부분일것 같습니다!
천천히 학습 후 적용해보셔도 좋을것 같아요🙌
***
다시 한번 고생 많으셨어요ㅎㅎ
이슈가 조금 있어 우선 Request Changes로 드리겠습니다..!
전반적으로 구현은 다 잘 되었고 해당 스텝2에서 필수 경험해볼 사항들은 잘 이해하고 다뤄주신것 같아 해당 부분들만 리팩토링되면 다음 스텝으로 넘어가도 좋을것 같아요ㅎㅎ
화이팅입니다🙌

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/Model/ExpositionPostEntity.swift
> +            let result = content[0] + "\n(" + content[1]
[replacingOccurrences](https://developer.apple.com/documentation/foundation/nsstring/1412937-replacingoccurrences) 메서드를 사용하면 더 간결히 해당 부분을 표현할 수 있을것 같습니다🙋🏻

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/Model/ExpositionPostEntity.swift
> +            return "개최 기간 : \(duration)"
![스크린샷 2022-06-17 오후 12 22 15](https://user-images.githubusercontent.com/72292617/174225791-06b85f04-41bb-429b-8231-deb97bc673d9.png)
요구사항에서 예시로 보여준것처럼 방문객 / 개최지 / 개최기간에 대한 폰트 사이즈가 다릅니다🙋🏻
[NSMutableAttributedString](https://developer.apple.com/documentation/foundation/nsmutableattributedstring)을 학습해보시면 여기서 충분히 처리해줄 수 있을것 같아요..!

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/Model/ExpositionPostEntity.swift
> +private extension Int {
기본 자료형의 extension은 추후에도 충분히 사용될 여지가 있을것 같은데 별도의 파일로 public하게 분리하여
사용하면 추후 재사용성에도 좋지 않을까 싶어요🙋🏻

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/Model/JsonError.swift
> +}
오호 에러까지 잘 정의해주셨네요👍
이렇게 message라는 변수를 통해 에러의 description을 정의해주는것도 있을것이고 직접적으로 rawValue로 String 값을 주는것도 있을텐데 해당하는 방식으로 구현하신 이유가 궁금합니다🙋🏻
또한 decodingFailure 외에 발생할 에러는 없을까요?
해당 에러의 정의만으로 충분할지 궁금해요🤔

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
>          return uiImage
`return UIImage(named: self.imageName)`과 같은 코드와 차이가 있나요~?
별도의 상수로 빼주었을때 얻는 이점이 어떤게 있을까요?🙋🏻

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/Resources/Assets.xcassets/flag.imageset/Contents.json
> +    }
해당 이미지에 대해서는 individual Scales 대신 single Scales로 지정해줘도 좋을것 같아 보입니다🙋🏻

2022-06-17 06:24 UTC, GREENOVER commented on README.md
> +- [X] 오토 레이아웃을 적용하여 다양한 기기에 대응
스텝3의 내용까지 미리 접해보셨군요👍👍

2022-06-17 06:24 UTC, GREENOVER commented on README.md
> +- 메인화면에 나타낼 Json 데이터 파싱 및 데이터 뷰에 할당
스텝2도 리드미 작성 아주 잘 해주고 계시네요👍👍👍

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/ExpositionDetailViewController.swift
> +final class ExpositionDetailViewController: UIViewController {
실제 각각의 출품작에 대한 상세 화면이니 `EntryDetailViewController`의 네이밍은 어떠세요~?
Exposition을 가지고 Post, Table, Detail로 하니 박람회의 포스트는 잘 이해가 되는데
직역해보면 ExpositionTable, ExposionDetail은 박람회 테이블, 박람회 상세로 해석되어 이것이 출품작의 리스트, 상세인지를 유추하기가 힘들것 같아요🥲

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/ExpositionDetailViewController.swift
> +        super.viewDidLoad()
`super.viewDidLoad()`의 코드가 필요한 이유가 무엇이라고 생각하시나요~?🙋🏻
실제로 어떤 역할을 수행하며 효과가 있나요?

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/ExpositionPostViewController.swift
> +final class ExpositionPostViewController: UIViewController {
final 키워드를 사용해줌으로 얻는 기대효과가 어떤게 있었으며
두분이 채택하신 이유가 어떤걸까요~?🙋🏻

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/ExpositionPostViewController.swift
> +        self.navigationController?.navigationBar.isHidden = true
위 코드와 중복되는것 같은데 이유가 있을까요?🙋🏻
없어도 될 코드이지 않을까 싶어서요..!

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/ExpositionTableViewController.swift
> +final class ExpositionTableViewController: UIViewController {
출품작 리스트 뷰컨트롤러라는 네이밍을 담은 `EntryListViewController`는 어떠세요?
현재 네이밍을 직역하면 박람회테이블 뷰컨이여서 네이밍만으로 어떤 뷰컨인지 유추하기가 쉽지 않아보입니다🥲

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/ExpositionTableViewController.swift
> +        entryEntity = try? JsonParser<[EntryEntity]>.fetch("EntryEntity")
실제 fetch 메서드 호출 시 디코드 에러가 나면 decodingFailure를 던져줄텐데 이를 UI에서 처리해주는 부분이 있을까요?🙋🏻
디버깅을 해준다거나 사용자에게 실패에 대해 안내하고 재시도를 유도하게 하는 과정이 필요하지 않을까 합니다🤔

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/ExpositionTableViewController.swift
> +    }
현재에서는 아래와 같이 셀 선택 시 선택하여 어두워진 배경이 다시 리스트로 돌아와도 남아있는 이슈가 있습니다🙋🏻
![Simulator Screen Shot - iPhone 11 - 2022-06-17 at 14 13 29](https://user-images.githubusercontent.com/72292617/174230024-38aa87c6-3c6c-4a8d-89b1-c140d0dc4446.png)
요 부분은 [deselectRow](https://developer.apple.com/documentation/uikit/uitableview/1614989-deselectrow) 레퍼런스를 참고해서 코드 추가를 해주시면 해결 될 수 있을거에요😀

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/ExpositionTableViewController.swift
> +        entryEntity = try? JsonParser<[EntryEntity]>.fetch("EntryEntity")
JSON 파일명과 같은 String들도 enum을 활용한 네임스페이스로 관리된다면 추후 여러 JSON 파일을 다뤄줄때나 유지보수 시 효과를 볼 수 있을것 같습니다🙋🏻

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/Model/JsonParser.swift
> +}
제네릭을 잘 활용하셨군요👍👍

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/View/ExpositionPostView.swift
> +    }()
사실상 동일한 구현이고 호출되는 부분을 확인하였을때도 굳이 두개를 따로 나눌 필요없이 하나의 EmptyStackView로 지정하고 사용하면 어떨까요~?🙋🏻

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/View/ExpositionPostView.swift
> +    }()
이 부분도 보일러 플레이트 코드라고 보여집니다🤔
하나로 합치고 사용하면 어떨까요?

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/View/ExpositionPostView.swift
> +private extension ExpositionPostView {
추후 요러한 extension들이 분기되고 많아진다면 extension 도입 라인에서 어떠한 기준 및 기능의 extension인지 주석을 달아두면 코드 파악에 더 유용할것 같습니다🙌

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/Expo1900/View/ExpositionTableViewCell.swift
> +            verticalStackView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor, constant: 20),
아래 캡쳐본처럼 description이 길때 cell의 disclosureIndicator의 영역과 겹치는 이슈가 있습니다🙋🏻
![스크린샷 2022-06-17 오후 2 52 18](https://user-images.githubusercontent.com/72292617/174234075-8ea1b3f8-6294-4939-857b-12b2dd1bc677.png)
verticalStackView의 trailing을 바로잡아봐야 할것 같아요🙋🏻

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/ExpositionTest/ExpositionTest.swift
> +class ExpositionTest: XCTestCase {
테스트에 대해 현재 최소 타겟이 iOS 15.5로 잡혀있습니다.
그런데 해당 프로젝트의 미니멈 타겟은 iOS 14.0이기에 15.5 미만에서는 테스트를 해볼 수 가 없어요😭
수정이 필요해보여요🙋🏻

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/ExpositionTest/ExpositionTest.swift
> +    var sut: ExpositionPostEntity!
강제추출외에 다른 방법은 없을까요~?🙋🏻

2022-06-17 06:24 UTC, GREENOVER commented on Expo1900/ExpositionTest/ExpositionTest.swift
> +        }
실제 catch 구현부가 비어있는데 어떤 추가가 이뤄지면 좋을까요?🙋🏻

2022-06-17 08:03 UTC, derrickkim0109 commented on Expo1900/Expo1900/Model/JsonError.swift
> +}
제가 생각하였을 때 JsonError.decodingFailure.rawValue로 코드를 사용하면 전달력이 떨어진다는 느낌이 들어 message라는 계산 프로퍼티를 활용하여 JsonError.decodingFailure.message로 사용하는 것이 가독성면에서 좋다고 생각합니다.
그리고 case 내에 rawVAlue를 설정하는 것은 타입 프로퍼티를 부른 상황에서 뿐만 아니라 JsonError 타입 내에서 코드를 읽기에도 불편하다고 생각합니다.

2022-06-17 08:04 UTC, derrickkim0109 commented on Expo1900/Expo1900/Model/EntryEntity.swift
>          return uiImage
Step01에서 답변을 달았던 부분입니다. return UIImage(named: self.imageName)로 바꾸는게 좋을까요?

2022-06-17 08:11 UTC, GREENOVER commented on Expo1900/Expo1900/Model/EntryEntity.swift
>          return uiImage
@derrickkim0109 
네 기억합니다.
그때 두분 모두 코멘트를 남겨주셨는데 서로 다른 포인트로 남겨주셔서 두분의 의견중 어떤걸로 택하게 되었는지 이유가 어떤것인지
취합된것이 있을지해서 다시 여쭤봤습니다🙋🏻

2022-06-18 05:34 UTC, derrickkim0109 commented on Expo1900/Expo1900/Controller/ExpositionDetailViewController.swift
> +        super.viewDidLoad()
loadView() -> viewDidLoad() 순서

viewDidLoad()라는 메서드는 뷰가 메모리에 로드가 된 후 한번만 호출 되는 메서드입니다. 
super.viewDidLoad() 필요할 때는 기본적으로는 super 클래스를 상속 받고 있는 sub 클래스인 경우 super 클래스의 viewDidLoad에서 구현되어 있는 기능을 상속 받기 위한 역할로 알고 있습니다.  

현재 저희의 코드에서는 UIViewController의 viewDidLoad만 상속한 경우입니다. 
super.viewDidLoad는 프로퍼티를 설정하는 것 외에는 비어 있다고 생각하면 되는 부분일까요? 


<References>
[ViewDidLoad()](https://developer.apple.com/documentation/appkit/nsviewcontroller/1434476-viewdidload)

2022-06-18 05:36 UTC, Baek-Gom-95 commented on Expo1900/Expo1900/Controller/ExpositionPostViewController.swift
> +final class ExpositionPostViewController: UIViewController {
final 키워드를 통해 더 이상 상속이 필요없음을 명시할 수 있고, 오버라이드 할 시 컴파일 에러를 발생시킬 수 있습니다! 명시적으로 상속되지 않는 것 외에 런타임 성능이 향상되어서 채택했습니다

2022-06-18 05:42 UTC, Baek-Gom-95 commented on Expo1900/Expo1900/Model/EntryEntity.swift
>          return uiImage
코드 전체적인 컨벤션 통일성 때문이기도 했고 유지보수 위한 가독성을 따졌을때 더 낫다고 생각하여 데릭의 의견으로 택하였습니다

2022-06-18 07:57 UTC, derrickkim0109 commented on Expo1900/ExpositionTest/ExpositionTest.swift
> +    var sut: ExpositionPostEntity!
강제추출 외에 chaining 처리를 하여서도 할 수 있을꺼 같아요.

2022-06-19 02:14 UTC, GREENOVER approved these changes
@derrickkim0109 @Baek-Gom-95 
리팩토링이 아주 잘되었네요!
고생 많으셨습니다 ㅎㅎ
추가적으로 여쭤보는것과 수정 및 보완되면 좋을 부분들 코멘트로 남기면서 스텝2의 요구사항 및 기능 구현은 너무 잘해주셔서 어프로브 및 머지하겠습니다!
수정이 필요한 부분이 있다면 다음 스텝에서 반영해주시면 좋을것 같아요🙌
그럼 다음 스텝도 화이팅입니다🥳🥳

2022-06-19 02:14 UTC, GREENOVER commented on Expo1900/Expo1900/Extensions/UILabel+Extensions.swift
> +    }
잘 활용해보셨네요!
그런데 다만 만약 ":"가 없는 타이틀이 존재하면 해당 코드의 재사용이 가능할까요?
재사용성이 떨어지는 느낌이 듭니다🤔
더 나은 방향이 있을것 같아요..!

2022-06-19 02:14 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/ExpositionDetailViewController.swift
> +        super.viewDidLoad()
말씀하신것처럼 통상적으로 오버라이딩 시 슈퍼 클래스의 기존 작업을 호출할지 선택사항으로 보여집니다.
현재 해당하는 경우는 View Life Cycle이 정해진 싸이클 패턴으로 되어있으며 OS가 호출하기에 대게 슈퍼 클래스의 기능을 담는것이 좋다고 해요!
데릭이 첨부해주신 viewDidLoad 공식 문서에서 discussion에도 잘 나와있네요!ㅎㅎ
마지막으로 질문주신 프로퍼티 설정 외에 비어있다라는게 무슨 말씀인지 잘 모르겠어요🙋🏻
프로퍼티는 어떤 프로퍼티를 말씀하신거죠?

2022-06-19 02:14 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/ExpositionTableViewController.swift
> +final class ExpositionTableViewController: UIViewController {
해당 부분 혹시 현재 네이밍으로 가시기로 한것인지 아직 반영전인지 궁금합니다🙋🏻

2022-06-19 02:14 UTC, GREENOVER commented on Expo1900/Expo1900/Extensions/UIViewController+Extensions.swift
> +    }
오호 얼럿 구현까지 잘 해주셨네요!👍
그런데 얼럿액션에 타이틀을 지정해주지 않아도 되나요?
아래같이 노출되시지 않을까요~?
![스크린샷 2022-06-19 오전 11 09 25](https://user-images.githubusercontent.com/72292617/174462968-b7ed52ce-c777-4ea3-88ed-3170f3cb8bc9.png)
추가로, 사용자 입장에서 생각해본다면 처음 fetch 실패 시 얼럿이 나타나고 확인 등의 버튼을 누르면 현재로썬 아무 역할을 안해주게 됩니다.
다시 통신을 시켜 데이터를 fetch 해오던지 아니면 이전 뷰로 나가거나 하는 그러한 작업들이 추가되면 좋을것 같아요!
당연히 이번 스텝에서 요구사항은 아니지만 얼럿을 시도하셨기에 얼럿의 handler도 있어야할것 같아 말씀드립니다🙌

2022-06-19 02:14 UTC, merged

2022-06-20 05:53 UTC, derrickkim0109 commented on Expo1900/Expo1900/Controller/ExpositionDetailViewController.swift
> +        super.viewDidLoad()
비어 있다는 것은 viewDidLoad() 내에서 설정될 코드가 없는 것을 의미했어요!
프로퍼티는 제가 구성해 놓은 UIElement들에 대한 말이였습니다.