만국박람회 [STEP2] 웡빙, bongf
yagom-academy/ios-exposition-universelle pull request #178
Opened 2022-06-17 07:15 UTC by wongbingg

안녕하세요 @corykim0829  step2 PR 보냅니다 ! ☺️☺️
잘 부탁드립니다
@wongbingg @apwierk2451

# Step2
기간 : 2022.6.15(수) ~ 2022.6.17(금)

## 구현사항
<p>

<div class=pull-left>

![화면_기록_2022-06-17_오후_2_59_40_AdobeExpress](https://user-images.githubusercontent.com/95671495/174245483-7ab07eaa-91e7-4106-83c3-4ecc858de8d8.gif)

</div>

### - Storyboard ID를 이용한 네비게이션
뷰 간의 이동을 하기 위해서 각 뷰의 식별자가 필요했는데, 코드로 뷰를 짠 경우 이 식별자 지정을 할 수가 없었다, 그래서 뷰마다 빈 ViewController 를 만들어 준뒤, Storyboard ID 를 지정해주어 사용 하였다. 

### - 화면전환 및 데이터 전달 
다음 뷰를 인스턴스화 시키는 `instantiate(from:, bundle:, identifier:)` 메서드를 만들어주어 , 뷰간 이동과 데이터 전달을 시켜주었습니다. 

### - 오토레이아웃
tableView에서 각 cell 마다`tableView.estimatedRowHeight = 200`,
`tableView.rowHeight = UITableView.automaticDimension`를 이용하여, content의 크기에 따라 rowheight를 맞춰주었습니다.
`image.contentMode = .scaleAspectFit`를 사용해 image의 크기를 ImageView에 맞게 설정해주고, imageView의 오토레이아웃을 설정해주었습니다.

</p>

</br>

</br>

### constraints

```swift
imageNameView.centerYAnchor.constraint(equalTo: self.contentView.centerYAnchor).isActive = true
imageNameView.widthAnchor.constraint(equalTo: self.contentView.widthAnchor, multiplier: 0.2).isActive = true
imageNameView.leadingAnchor.constraint(equalTo: self.contentView.leadingAnchor, constant: 10).isActive = true
imageNameView.heightAnchor.constraint(equalTo: self.heightAnchor).isActive = true

subStackView.topAnchor.constraint(equalTo: self.contentView.topAnchor, constant: 10).isActive = true
subStackView.leadingAnchor.constraint(equalTo: imageNameView.trailingAnchor, constant: 10).isActive = true
subStackView.trailingAnchor.constraint(equalTo: self.contentView.trailingAnchor, constant: -10).isActive = true
subStackView.bottomAnchor.constraint(equalTo: self.contentView.bottomAnchor, constant: -10).isActive = true
```

## 화면 구성

### MainViewController
- navigationItem.title = "메인"
- scrollView
    - stackView
        - **title**
        - **posterView**
        - **visitorStack**
            - visitorsTitle
            - visitorsText
        - **locationStack**
            - locationTitle
            - locationText
        - **durationStack**
            - durationTitle
            - durationText
        - **description**
        - **buttonStack**
            - firstFlagView
            - button
            - secondFlagView

### ItemTableViewController
- navigationItem.title = "한국의 출품작"
- ItemTableViewCell
    - stackView
        - **imageNameView**
        - subStackView 
            - **nameLabel**
            - **shortDescriptionLabel**

### DetailViewController
- navigationItem.title = ItemTableViewCell.nameLabel
- stackView
    - **imageNameView**
    - **descrriptionLabel**

## 🛠Trouble Shooting🛠

### - 줄바꿈이 되지 않는 문제
 JSON에서 파싱된 Data의 줄바꿈을 하기 위하여 replacingOccurences 메서드를 사용했다.
title.text 내의 "(" 를 "\n("로 변경하도록 구현했다.
``` swift
    title.text = result.title
    title.text = title.text?.replacingOccurrences(of: "(", with: "\n(")
    title.textAlignment = .center
```
<img src="https://i.imgur.com/u3W5HEU.png" width="250" height="500"/><img src="https://i.imgur.com/66t1M9e.png" width="250" height="500"/>

### - 스크롤이 되지 않는 문제
UIViewController 로 뷰를 구성하니 위아래 스크롤이 되지 않았다. 그래서, 모든 UI요소를 새로 만들어준 UIScrollerView 에 다시 추가해준 뒤, UIScrollView - SuperView 와의 Constraints 을 설정 해주었다. 

### - 사진의 크기조절 
stackView에 사진과 버튼을 addArrangedSubview 해줬을 때 사진만 크게 나와 버튼을 클릭할 수 없는 문제가 발생했다. 사진의 크기를 resize하여 문제를 해결했다.
```swift=
func resizeImage(image: UIImage, width: CGFloat, height: CGFloat) -> UIImage? {
    UIGraphicsBeginImageContext(CGSize(width: width, height: height))
    image.draw(in: CGRect(x: 0, y: 0, width: width, height: height))
    let newImage = UIGraphicsGetImageFromCurrentImageContext()
    UIGraphicsEndImageContext()
    return newImage
}
```

<img src="https://i.imgur.com/Iih7Yd6.png" width="250" height="500"/><img src="https://i.imgur.com/wuVmwG0.png" width="250" height="500"/>

## 궁금한 점

### - 해금의 사진크기

해금의 사진크기만 위아래로 길게 뻗어지는 현상이 발생하였습니다. 이 사진 하나 때문에 작업 진행이 원활하게 되지 않았습니다. 

```swift   
imageNameView.heightAnchor.constraint(equalTo: self.contentView.heightAnchor, multiplier: 0.9).isActive = true
```
contentView가 아닌 self.heightAnchor를 이용하였더니 해결되었습니다.
```swift   
imageNameView.heightAnchor.constraint(equalTo: self.heightAnchor, multiplier: 0.9).isActive = true
```
self.contentView.heightAnchor와 self.heightAnchor의 차이가 궁금합니다.

## 참고한 것

### - translatesAutoresizingMaskIntoConstraints
A Boolean value that determines whether the view's autoresizing mask is translated into Auto Layout constraints.
뷰의 자동 조절 마스크가 자동 레이아웃 제약 조건으로 변환되는지 여부를 결정하는 부울 값.

**Declaration**
```swift
var translatesAutoresizingMaskIntoConstraints: Bool { get set }
```
**Discussion**

Note that the autoresizing mask constraints fully specify the view’s size and position; therefore, you cannot add additional constraints to modify this size or position without introducing conflicts. If you want to use Auto Layout to dynamically calculate the size and position of your view, you must set this property to false, and then provide a non ambiguous, nonconflicting set of constraints for the view

코드로 오토레이아웃을 작성 해주려면 이 속성은 false 로 해주어야 한다.

2022-06-17 13:02 UTC, corykim0829 requested changes
수고하셨습니다! 웡빙, bongf!! 👏👏👏👏👏

UI를 모두 코드로 구현하시느라 고생하셨습니다! 👍 좋은 경험이 됐을 것 같습니다.
이번에 스토리보드와 코드로 구현하는 부분의 차이점을 공부하시면서 코드를 개선해 나가시면 좋은 공부가 될 것 같습니다!
전체적으로 가독성이 아쉬웠습니다. 이 부분은 계속해서 개선해 나가면 좋을 것 같습니다!

2022-06-17 13:02 UTC, corykim0829 commented on Expo1900/Expo1900/DetailViewController.swift
> +    let imageNameView: UIImageView = {
여기 UIImageView 변수명만 보면, imageName 문자열을 담고있는 View로 오해할 수 있을 것 같아요!
UIKit 클래스의 변수명은 해당 UIKit 클래스로 끝나면 코드가 더 읽기 좋아집니다. 참고하세요

2022-06-17 13:02 UTC, corykim0829 commented on Expo1900/Expo1900/DetailViewController.swift
> +        let stack = UIStackView()
stack은 다른 개발 용어에서도 쓰이니 stackView로 사용하면 좋을 것 같아요!

2022-06-17 13:02 UTC, corykim0829 commented on Expo1900/Expo1900/DetailViewController.swift
> +    override func viewDidLoad() {
viewDidLoad에 다 구현하는 것보다 기능에 따라 함수로 분리하면 더욱 가독성이 좋아질 것 같습니다. viewDidLoad() 같이 라이프사이클을 담당하는 중요한 함수에서는 더욱 더 깔끔하고 가독성있게 유지하는게 좋습니다!

2022-06-17 13:02 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewCell.swift
> +        guard let image = UIImage(named: name) else { return nil }
UIImage(named:) 함수 자체가 UIImage? 타입을 리턴해서 guard문 처리가 의미가 없는 것 같아요!

2022-06-17 13:02 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewCell.swift
> +    override func updateConstraints() {
각 뷰에 적용되는 레이아웃 코드들도 함수로 분리하면 더 읽기 좋을 것 같습니다!

2022-06-17 13:02 UTC, corykim0829 commented on Expo1900/Expo1900/MainViewController.swift
> +    override func viewDidLoad() {
ViewDidLoad 함수 하나가 100줄에 달하는 아찔한 상황이네요 👀💦
이렇게되면 가독성이 현저히 떨어지게 됩니다.
기능 단위로 함수로 분리해주세요!

2022-06-17 13:02 UTC, corykim0829 commented on Expo1900/Expo1900/MainViewController.swift
> +    @objc func buttonDidTapped(_ sender: UIButton) {
이 함수를 보면 어떤 버튼의 동작인지 유추하기 어렵습니다. 변수명, 함수명을 바꿔주세요!

2022-06-17 13:02 UTC, corykim0829 commented on Expo1900/Expo1900/MainViewController.swift
> +        let itemTableViewController = ItemTableViewController.instantiate(bundle: nil, identifier: "ItemView")
레이아웃도 모두 코드로 구성했으니, 스토리보드에서 굳이 뷰컨트롤러를 인스턴스로 만들 필요가 없이 바로 뷰컨트롤러 객체를 만들어서 처리하면 좋을 것 같습니다!

2022-06-17 13:02 UTC, corykim0829 commented on Expo1900/Expo1900/MainViewController.swift
> +    func makeScrollView() -> UIScrollView {
ItemTableViewCell에서 구현한 방식과 다르게 여기에서는 함수에서 만들어서 리턴하는 방법을 사용하고 계시는데, 되도록이면 같은 방법으로 구현하는게 코드의 일관성, 가독성 그리고 유지보수에 좋습니다.
함수러 처리하는 방식은 여러번 호출해서 UI 요소를 만들 일이 있으면 좋은 방법일 것 같아요!

2022-06-17 13:02 UTC, corykim0829 commented on Expo1900/Expo1900/MainViewController.swift
> +    func resizeImage(image: UIImage?, width: CGFloat, height: CGFloat) -> UIImage? {
이미지 리사이즈 처리 좋습니다 👍

2022-06-17 13:02 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewController.swift
> +        let detailViewController = DetailViewController.instantiate(bundle: nil, identifier: "DetailView")
여기도 마찬가지로 스토리보드에서 instantiate할 필요없이 코드로 바로 인스턴스를 생성해서 처리하면 더 깔끔할 것 같습니다

2022-06-17 13:02 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewController.swift
> +        }
기본적으로는 최대한 하위객체들이 일을 많이 처리하도록 하는게 좋습니다. 그럴수록 구조가 더 깔끔해지고 유지보수와 재사용에 편리하기 때문이죠! 그래서 뷰에게 모델을 넘겨서 뷰를 업데이트하는게 깔끔한 로직입니다. 

이렇게 하나하나 값을 지정하는 것보다는 상위객체에서 하위 객체에게 모델을 전달하면 하위객체 내부에서 UI를 업데이트하는 로직으로 수정하면 좋을 것 같습니다.

2022-06-17 13:02 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewController.swift
> +    override func viewDidLoad() {
여기 viewDidLoad도 기능 단위에 맞게 함수로 분리해주세요!

2022-06-17 13:02 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewController.swift
> +        tableView.rowHeight = UITableView.automaticDimension
이 코드는 꼭 여기 있어도 되지 않기 때문에 다른 곳에서 처리하면 좋을 것 같습니다!

2022-06-17 13:02 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewController.swift
> +        }
제가 아래 `override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)`에 해드린 피드백 처럼 뷰인 cell에게 모델만 넘겨서 UI를 업데이트하는 구조로 수정해주세요!

2022-06-17 13:58 UTC, wongbingg commented on Expo1900/Expo1900/DetailViewController.swift
> +    let imageNameView: UIImageView = {
말씀 주신대로 수정 하였습니다!

2022-06-17 13:59 UTC, wongbingg commented on Expo1900/Expo1900/DetailViewController.swift
> +        let stack = UIStackView()
이 부분도 말씀 주신대로 수정 하였습니다! ☺️☺️

2022-06-17 14:10 UTC, wongbingg commented on Expo1900/Expo1900/DetailViewController.swift
> +    override func viewDidLoad() {
viewDidLoad() 안에있던 constraint 지정 부분을 메서드로 분리하였습니다. 또한 , scrollView 객체를 생성하는 부분도 통일성 있게 만들어 주었습니다.

2022-06-17 14:16 UTC, wongbingg commented on Expo1900/Expo1900/ItemTableViewCell.swift
> +        guard let image = UIImage(named: name) else { return nil }
리팩토링 과정 중 이 함수가 필요 없다고 판단 되어 제거 해주었습니다 ☺️☺️

2022-06-17 14:31 UTC, apwierk2451 commented on Expo1900/Expo1900/ItemTableViewCell.swift
> +    override func updateConstraints() {
updateConstraints 메서드를 지우고 오토레이아웃 함수를 만들어 init에 넣어주었습니다.

2022-06-17 15:25 UTC, apwierk2451 commented on Expo1900/Expo1900/MainViewController.swift
> +    override func viewDidLoad() {
ViewDidLoad 내부의 객체들을 프로퍼티로 꺼내주었습니다.

2022-06-18 04:43 UTC, wongbingg commented on Expo1900/Expo1900/MainViewController.swift
> +    @objc func buttonDidTapped(_ sender: UIButton) {
enterButtonDidTapped 라는 네이밍으로 변경 해주었습니다 !

2022-06-18 05:22 UTC, wongbingg commented on Expo1900/Expo1900/MainViewController.swift
> +        let itemTableViewController = ItemTableViewController.instantiate(bundle: nil, identifier: "ItemView")
바로 객체를 만들어서 사용하는 것으로 수정하였습니다 ! 또한 instantiate() 메서드가 필요 없어지게 되어 제거 해주었습니다. 
 수정 과정에서 다음 뷰로 넘어갈 때 버벅거림과 화면이 다 나오지 않는 오류가 생겼었는데 ,background color 를 .systemBackground 로 설정해주니 해결이 되었습니다. 왜 이렇게 해결이 되는지 원리가 궁금합니다! 🧐🧐

2022-06-18 05:33 UTC, wongbingg commented on Expo1900/Expo1900/MainViewController.swift
> +    func makeScrollView() -> UIScrollView {
자주 사용되는 함수만 따로 만들어주고 나머지는  각 UI요소를 생성하는 closure 안에서 수행하도록 해주었습니다!

2022-06-18 05:34 UTC, wongbingg commented on Expo1900/Expo1900/ItemTableViewController.swift
> +        let detailViewController = DetailViewController.instantiate(bundle: nil, identifier: "DetailView")
이 부분도 마찬가지로 바로 detailViewController를 객체화 하여 사용하였습니다!

2022-06-18 05:46 UTC, wongbingg commented on Expo1900/Expo1900/ItemTableViewController.swift
> +        }
셀 터치시 모델에 indexPath를 적용하여 DetailView뷰에 넘겨주었습니다. 

모델 , indexPath 를 각각  넘겨주어 DetailView 에서 처리하도록 하는게 더 좋은 방법 일까요?

2022-06-18 07:05 UTC, wongbingg commented on Expo1900/Expo1900/ItemTableViewController.swift
> +        }
ItemTableViewCell 에 parseData(from:,with:) 라는 함수를 만들어서 controller로부터 모델과 indexPath를 받도록 수정 해주었습니다 !

2022-06-18 07:12 UTC, wongbingg commented on Expo1900/Expo1900/ItemTableViewController.swift
> +        tableView.rowHeight = UITableView.automaticDimension
메서드로 분리해주어 viewDidLoad에서 호출 해주었습니다 !

2022-06-18 07:13 UTC, wongbingg commented on Expo1900/Expo1900/ItemTableViewController.swift
> +    override func viewDidLoad() {
viewDidLoad 안에서 수행되는 함수들을 기능별로 분리 해주었습니다 !

2022-06-20 14:43 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewController.swift
> +        }
indexPath를 여기에서 처리해서 해당 cell의 모델만 넘겨주면 될 것 같습니다!

2022-06-20 15:02 UTC, corykim0829 approved these changes
수고하셨습니다 👍

추가로 피드백 해드린 부분은 다음 스텝 진행하면서 수정해주세요!

다음 스텝 목표 일정은 피드백 수정까지 고려해서 잡아주세요 😀

2022-06-20 15:02 UTC, corykim0829 commented on Expo1900/Expo1900/DetailViewController.swift
> +        scrollView.addSubview(stackView)
이제보니 여기서 stackView를 subview로 추가하는데, 조금 어색합니다. 
보통 이런 구현부 클로저 안에는 scrollView 인스턴스의 속성까지만 처리하는게 좋습니다!

2022-06-20 15:02 UTC, corykim0829 commented on Expo1900/Expo1900/DetailViewController.swift
> +        stackView.addArrangedSubview(descriptionLabel)
여기도 마찬가지로 분리시켜주세요!

2022-06-20 15:02 UTC, corykim0829 commented on Expo1900/Expo1900/DetailViewController.swift
> +        self.view.addSubview(scrollView)
navigation 부분도 함수로 분리해주시고, 아래 scrollView를 추가하는 부분도 위에 subview들을 분리하면서 같이 분리하면 좋을 것 같아요!

2022-06-20 15:02 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewCell.swift
> +        stackView.addArrangedSubview(shortDescriptionLabel)
마찬가지로 분리해주세요!

2022-06-20 15:02 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewCell.swift
> +        self.contentView.addSubview(labelStackView)
함수로 분리해주세요!

2022-06-20 15:02 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewController.swift
> +    var itemModel: [Item]?
모델을 Model이라고 붙이는 것보다는 배열이니 items로 표기하면 더 Swift 가이드에 맞는 네이밍입니다! 참고하세요!

2022-06-20 15:02 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewController.swift
> +    private func parseItemModel() {
이 함수에서 직접 파싱을 하는게 아니기 때문에, parse라고 하기 보다는 다른 함수명을 사용하는게 좋을 것 같아요!

2022-06-20 15:02 UTC, corykim0829 commented on Expo1900/Expo1900/MainViewController.swift
> +        scrollView.addSubview(stackView)
분리해주세요!

2022-06-20 15:02 UTC, corykim0829 commented on Expo1900/Expo1900/MainViewController.swift
> +        stackView.addArrangedSubview(enterButtonStackView)
분리해주세요!

2022-06-20 15:03 UTC, merged

2022-06-21 12:49 UTC, wongbingg commented on Expo1900/Expo1900/DetailViewController.swift
> +        scrollView.addSubview(stackView)
참고하여 addSubview 를 하는 부분을 모두 분리해 주었습니다 !

2022-06-21 12:50 UTC, wongbingg commented on Expo1900/Expo1900/ItemTableViewController.swift
> +    private func parseItemModel() {
generateItems() 로 네이밍을 변경하였습니다 !

2022-06-21 12:53 UTC, wongbingg commented on Expo1900/Expo1900/DetailViewController.swift
> +        self.view.addSubview(scrollView)
viewDidLoad() 내에서 한줄로 작성된 코드 일지라도 그 기능을 명확히 하기 위해 메서드로 분리하여 나타내는 것이 좋은 것일까요? 궁금합니다!