만국박람회 [STEP 2] Kay, 나이든별
yagom-academy/ios-exposition-universelle pull request #181
Opened 2022-06-17 08:00 UTC by OldStarKR

안녕하세요 @jryoun1 !
만국 박람회 두번째 Pull - Request 보내드립니다. 항상 좋은 리뷰와 코멘트 감사합니다!🙇🏻‍♂️

### 작업한 내용
* 인트로 화면 구현: 1900년 파리 만국박람회와 참가국으로써의 한국(당시 대한제국)을 소개
* 한국의 출품작 화면 구현: 한국의 출품작 목록 표시
* 한국의 출품작 상세 화면 구현: 각각의 출품작에 대한 상세 설명 표시

### 고민한 점 조언 받고 싶은 점
* 뷰 간 데이터를 이동 시킬때 다음 뷰 컨트롤러에 프로퍼티를 만들어 넘겨주는 방식으로 진행했는데 이 방법이 좋은 방법인지 궁금합니다. 
    * 이 과정에서 `instantiateViewController(withIdentifier:)` 메서드를 이용했습니다.
* 테이블 뷰 셀을 스토리보드로 구현하는 방법을 자세히 알고 싶습니다.
    * 야곰의 오토 레이아웃 강의를 참조했는데, 커스텀 셀을 만들 때는 코드를 기반으로 제약 사항이나 들어갈 프로퍼티 등을 설정해 주었습니다.
    * 해당 방법을 사용해 구현했지만, 최대한 다양한 방법을 경험해보고 싶다는 취지에 따라 질문드리게 되었습니다.
    * 들어갈 프로퍼티나 제약사항 등을 스토리보드에서 정하고, 안에 들어갈 컨텐츠에 대해서만 별도의 테이블 뷰 셀 클래스를 정의해서 넣어줄 수 있는지 궁금합니다.

### 앞으로 수정 해야하는 부분

* 고정된 값을 가진 String 값들을 담아주는 네임스페이스 생성 및 적용
    * 코드 전반적으로 고정된 String 값이 많이 쓰인 것을 발견했습니다. 이를 담아주는 네임스페이스를 만들어 줄 계획입니다. 
* numberFormatter 적용하기
    * 포스터 뷰 컨트롤러에서 관람객 수를 포매팅해주어야 합니다.

2022-06-19 13:49 UTC, jryoun1 requested changes
안녕하세요 @OldStarKR @KayAhnDS ~
step2도 빠르게 잘 진행해주셨네요 👍🏻
코드를 깔끔하게 잘 작성해주셔서 가독성도 좋았던 것 같습니다👏

다만 몇 가지 궁금한 점 및 기능요구서와 다른 부분이 있어서 남겨봅니다.
나머지는 코드부분의 코멘트를 확인해주시면 감사하겠습니다. 🙏🏻

## 고민한 점 조언 받고 싶은 점
> 뷰 간 데이터를 이동 시킬때 다음 뷰 컨트롤러에 프로퍼티를 만들어 넘겨주는 방식으로 진행했는데 이 방법이 좋은 방법인지 궁금합니다.

VC 간의 데이터를 전송하는 방법에는 여러 가지 방법들이 있습니다. 
(e.g. 프로퍼티를 이용해서 데이터를 주고 받기(지금 구현하신 방법), Segue를 이용하는 방법, delegation을 이용한 방법 등등)
어떤 방법이 좋고 나쁜 것은 따로 없는 것 같습니다. 물론 상황에 따라서 좋은 방법과 좋지 않은 방법들은 있을 것 같습니다. VC간의 데이터 전송에 대해서 여러 방법들을 공부해보시고 적용해보시면서 어떤 경우에 어떤 방법을 사용하면 좋을지 알아보시면 도움이 될 것 같습니다. 🙏🏻

> 테이블 뷰 셀을 스토리보드로 구현하는 방법을 자세히 알고 싶습니다.

tableview를 구현하는 것도 방법이 여러 가지 있습니다. (tableviewcell도 동일)
1. 스토리보드를 통해서 구현
2. 코드로 구현
3. Xib를 활용해서 구현

> 들어갈 프로퍼티나 제약사항 등을 스토리보드에서 정하고, 안에 들어갈 컨텐츠에 대해서만 별도의 테이블 뷰 셀 클래스를 정의해서 넣어줄 수 있는지 궁금합니다.

말씀하신 부분들도 가능합니다. 방법들을 공부해보시면 좋을 것 같습니다. [이런 글](https://shark-sea.kr/entry/iOS-TableView-Storyboard%EB%A1%9C-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0)도 있네요 ☺️

## 궁금한 점
![image](https://user-images.githubusercontent.com/45090197/174483898-c58585dc-4a6f-47ae-a295-675ef8aea2cf.png)
Main 스토리보드를 확인해보니 각각의 viewController들이 전부 NavigationController를 embed in 되어있는데 이렇게 구현하신 이유가 있을까요? 🙋‍♂️

## 기능요구서와 다른 부분 🚨 
기능요구서의 gif를 한 번 확인해주세요 🙏🏻

1. 박람회 첫 포스트 페이지에서 스크롤를 내리는 경우에 네비게이션 바가 보이고 있습니다. 
<img src="https://user-images.githubusercontent.com/45090197/174483693-20172415-04d3-4b85-9aa4-005ab0d185e8.png" width="200" height ="400">

5. 출품작의 상세 정보로 들어갔을 때 스크롤을 내리면 네비게이션 바가 보이지만 (정상), 처음 들어갔을 때는 네비게이션 바의 색상이 다른 것 같습니다. 
<img src="https://user-images.githubusercontent.com/45090197/174483796-73f41b20-7f4b-4834-94f1-fdc192f2e703.png" width="200" height ="400">

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +class ExpositionPosterViewController: UIViewController {
ViewController의 이름을 구체적으로 변경해주셨네요 👍🏻

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +//  Expo1900 - ViewController.swift
여기도 같이 변경해주시면 좋을 것 같네요 🙏🏻

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +// MARK: - 뷰 라이프사이클 메서드
이러한 주석은 꼭 필요한 걸까요? 🤔

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +extension ExpositionPosterViewController {
extension을 메서드들을 구분하는데 사용하셨네요 👏
함수들을 구분하기 위해서 extension을 사용하시는 방법도 있지만 작성하신 것과 같이 `MARK: -` 주석을 사용해서도 충분히 구분할 수 있습니다. 

저는 extension의 경우에는 주로 viewController 내부에 메서드가 너무 많거나, 비슷한 역할을 하는 함수들끼리 모으거나, 어떤 protocol을 채택해서 해당 protocol의 필수 구현 메서드를 구현하는 경우(e.g. tableView의 delegate의 경우)에 extension을 사용해서 구분을 지어주고 있습니다 🙏🏻

![image](https://user-images.githubusercontent.com/45090197/174480019-ddf493c4-6bed-4eaa-a919-05687361fdbf.png)

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +        configurePosterView()
클린코드라는 책에 **형식**과 관련된 내용중에 `수직거리`라는 것이 있습니다. 
> 서로 밀접한 개념은 한 파일에 속해야 찾기 쉽다.
밀접한 두 개념은 세로 거리로 연관성을 표현한다.

종속 함수
- 한 함수가 다른 함수를 호출한다면 두 함수는 세로로 가까이 배치.
- 가능하다면 호출하는 함수를 호출되는 함수보다 먼저 배치

물론 지금 작성하신 코드도 수직거리가 멀지는 않지만 더 가까우면 좋을 것 같습니다 🙏🏻

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +        // TODO: 방문객 숫자에 numberFormatter 적용하기
해야할 일들을 TODO 주석으로 남기는 것 아주 좋습니다 💯

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +        visitorsLabel.text = "방문객 : \(poster.visitors) 명"
ExpositionPoster model 타입에서 값 들을 바로 가져다가 쓰는 것이 아니라 ExpositionPosterViewController에서 가공해서 text를 만들어 주고 있는데, 이러한 역할을 model 타입에게 위임하는 것은 어떨까요? 🤔

hint: step1에서 UIImage를 반환하는 연산프로퍼티처럼 할 수 있을 것 같습니다.

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +        KoreanEntryTableViewContoller.entries = entries
KoreanEntryTableViewController에서 entries들을 할당해줘도 될 것 같은데 이 함수에서 entries를 할당해줘야하는 이유가 있을까요? 👀

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +    @IBAction private func didTapKoreanEntryButton(_ sender: UIButton) {
접근제한자, 함수네이밍 너무 좋네요 👏

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/KoreanEntryTableViewController.swift
> +extension KoreanEntryTableViewController {
UITableViewController를 채택하셔서 명시적으로 delegate를 채택하지는 않지만, 
이런식으로 각각의 delegate에 따라서 extension으로 구분하는 것은 아주 좋네요 👏

위에서도 언급하긴 했지만 주석들은 꼭 필요할까요? 🤔

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/KoreanEntryTableViewController.swift
> +        return entries?.count ?? 1
default로 1을 반환해주는 이유가 있을까요? 🤔

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/KoreanEntryTableViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "koreanEntryCell", for: indexPath)
reuseIdentifier에 대해서 [이 문서](https://medium.com/bleeding-edge/nicer-reuse-identifiers-with-protocols-in-swift-97d18de1b2df)를 보면 protocol을 생성하여 편리하게 관리할 수 있는 방법이 있어서 공유드립니다. 🙏🏻

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/KoreanEntryTableViewController.swift
> +        guard let entryCell = cell as? KoreanEntryTableViewCell else {
이 코드는 위의 코드와 합쳐서 아래와 같이 한 번에 쓸 수 있을 것 같습니다. 🙏🏻
```swift
let cell = tableView.dequeueReusableCell(withIdentifier: "koreanEntryCell", for: indexPath) as? KoreanEntryTableViewCell else { return UITableViewCell() }
```

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/KoreanEntryTableViewController.swift
> +        entryCell.entryImageView.image = data?.thumbnail
entryCell의 image, text 설정해주는 부분을 VC가 entryCell에 직접 접근해서 해주는 것이 아니라, data를 넘겨서 KoreanEntryTableViewCell에서 설정해주는 역할을 해줄 수 있을 것 같습니다 🙏🏻

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/SelectedEntryViewController.swift
> +    @IBOutlet weak var selectedEntryImageView: UIImageView!
외부에서 접근될 일이 있을까요? 👀

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +//  KoreanEntryTableViewCell.swift
여기는 코드로 view를 작성해주셨네요 👏
특별한 이유가 있나요? 🙋‍♂️

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +    var entryImageView: UIImageView!
[IBOutlet을 사용하는 경우](https://jeong9216.tistory.com/191)에는 강제 언래핑을 사용하긴 합니다.
반면 IBOutlet과 같은 몇 가지의 케이스를 제외한 경우에는 최대한 강제 언래핑을 지양하는 것이 안전할텐데 강제 언래핑을 사용하신 이유가 있을까요?  🤔

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +    override func awakeFromNib() {
함수의 분리가 필요해 보입니다. 🙏🏻

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +        stackView.alignment = .fill
alignment, distribution의 default 값은 fill입니다 🙏🏻

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +            stackView.leadingAnchor.constraint(equalTo: entryImageView.trailingAnchor, constant: 8),
띄어쓰기가 있거나 이런식으로 작성되면 가독성이 더 좋을 것 같아보입니다. 
```swift
contentView.addSubview(entryImageView)
NSLayoutConstraint.activate([
            entryImageView.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 8),
            entryImageView.bottomAnchor.constraint(equalTo: contentView.bottomAnchor, constant: 8),
            entryImageView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 8),
            entryImageView.widthAnchor.constraint(equalTo: contentView.widthAnchor, multiplier: 0.2),
            entryImageView.widthAnchor.constraint(equalTo: entryImageView.heightAnchor)
])

contentView.addSubview(stackView)
NSLayoutConstraint.activate([
            stackView.leadingAnchor.constraint(equalTo: entryImageView.trailingAnchor, constant: 8),
            stackView.topAnchor.constraint(equalTo: entryImageView.topAnchor),
            stackView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor),
            stackView.bottomAnchor.constraint(equalTo: entryImageView.bottomAnchor)
])


```

2022-06-19 13:49 UTC, jryoun1 commented on README.md
> +# 만국박람회 README
Readme도 잘 작성해주셨네요 👍🏻

2022-06-19 13:49 UTC, jryoun1 commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +    override func awakeFromNib() {
awakeFromNib()은 무슨 함수일까요? 🙋‍♂️

2022-06-20 06:30 UTC, OldStarKR commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +extension ExpositionPosterViewController {
말씀해주신 부분이 앞으로 extension을 사용하는 기준을 정함에 있어 또 하나의 이정표가 될 것 같습니다☺️

2022-06-20 06:44 UTC, OldStarKR commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +        visitorsLabel.text = "방문객 : \(poster.visitors) 명"
모델 타입에 가공을 위임하고, 그에 따라 외부에서 접근할 일이 없어진 프로퍼티에 `private`을 붙여 주었습니다!!

2022-06-20 07:08 UTC, OldStarKR commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +// MARK: - 뷰 라이프사이클 메서드
MARK 주석과 extension의 역할이 지금 저희의 코드에서는 중복된다고 여겼습니다. 그래서 MARK 주석을 지워 주었습니다🥲

2022-06-20 07:09 UTC, OldStarKR commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +        configurePosterView()
클린 코드.. 언젠가 꼭 봐야지 하고 생각만 하고 있던 책이었는데, 이번 기회에 공부해볼 의욕이 생겼습니다☺️

2022-06-20 07:17 UTC, OldStarKR commented on Expo1900/Expo1900/Controllers/KoreanEntryTableViewController.swift
> +extension KoreanEntryTableViewController {
`UITableViewController` 내부적으로 `UITableViewDelegate`과 `UITableViewDataSource` 프로토콜이 이미 적용되어 있다는 것을 명확히 하고 싶어서 이렇게 사용했습니다! 좋게 봐주시니, 동료에게 좋은 평가를 들은 것 같아 기분이 좋습니다😊

다만 주석은 위에서 말씀드린 대로 삭제해 주었습니다🥲

2022-06-20 07:25 UTC, OldStarKR commented on Expo1900/Expo1900/Controllers/KoreanEntryTableViewController.swift
> +        return entries?.count ?? 1
0과 1 사이에서 많이 고민했습니다😢 entries.count가 nil인 경우는 뷰 컨트롤러에서 출품작 데이터를 받는 데 실패했다는 뜻이고, 이 경우 데이터를 가져오는 데 실패했음을 알리는 셀을 별도로 만들어서, 이를 사용해서 사용자에게 안내할 수 있지 않을까? 하는 생각을 했고 그래서 1로 지정해 주었습니다. 

다만 피드백 주신 부분에 따라 코드를 수정하다 보니, entries 프로퍼티에 기본값으로 빈 배열 하나를 주고, numberOfRowsInSection에서는 entries.count만을 반환하게 한 다음에, 데이터를 불러오지 못한 경우에 대해 다른 안내 방법을 사용하는 것이 좋을 수 있겠다는 생각을 해 보았습니다. 이 경우 기본값을 1 대신 0으로 준 것과 비슷한 결과가 나올 것으로 예상됩니다.

2022-06-20 07:47 UTC, OldStarKR commented on Expo1900/Expo1900/Controllers/KoreanEntryTableViewController.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "koreanEntryCell", for: indexPath)
이전 저의 경험을 토대로 생각해보면, NSObject의 extension에 static let으로 비슷한 것을 정해준 적이 있었습니다. 프로토콜로 이런 작업을 수행해준다는 것이 굉장히 신선했습니다😃

2022-06-20 08:06 UTC, OldStarKR commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +        stackView.alignment = .fill
좀 더 알아보고 쓰지 못한 것이 부끄럽습니다🥲 해당 설정은 지워 주었습니다.

2022-06-20 08:21 UTC, OldStarKR commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +    override func awakeFromNib() {
이미지 뷰와 레이블 셋업 메서드를 각각 분리해 주었습니다! Constraint 정하는 부분에서 마저 말씀드릴게요~

2022-06-20 08:22 UTC, OldStarKR commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +//  KoreanEntryTableViewCell.swift
아래에서 말씀해주신 강제 언래핑과 같은 맥락인데요, 스토리보드에서 테이블 뷰 셀을 작성하는 방법에 대해 갈피를 잡지 못하고 있다가, 야곰의 오토 레이아웃 강의를 보고 코드로 뷰를 작성한 것을 따라한 것에 가깝습니다🥲

2022-06-20 08:27 UTC, OldStarKR commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +    var entryImageView: UIImageView!
야곰의 오토 레이아웃 강좌를 충실히 따르다 보니 발생한 해프닝이 되겠습니다🙃

하지만 아무 이유 없이 따라하지는 않았고, 왜 이렇게 지정했을까에 대해서는 생각해 보았습니다. Constraint 및 데이터 삽입을 수행할 때, addSubView할 때 등 여러 곳에서 오류가 발생했습니다. 이에 관해 생각해보았을 때, 마치 IBOutlet처럼 사용하고자 저렇게 설정해두셨고 그것을 기반으로 강의를 찍지 않으셨나? 생각이 드는 부분입니다.

지금 다시 생각해보면, UILabel() 등의 기본값을 주어서 해당 프로퍼티를 다루는 것도 괜찮았을 것 같습니다. 비록 뷰 인스턴스는 자원 소모가 크기 때문에 하나하나 더할 때 신중해야 하지만, 강제 옵셔널 언래핑에 의한 위험을 피할 수 있다면 해당 방법을 사용하는 것도 좋아 보입니다.

2022-06-20 08:28 UTC, OldStarKR commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +            stackView.leadingAnchor.constraint(equalTo: entryImageView.trailingAnchor, constant: 8),
이미지 뷰와 스택 뷰 설정하는 것을 각기 메서드로 분리해주었기 때문에, Constraint 역시 분리해서 해당하는 메서드에 넣어 주었습니다!

2022-06-20 08:52 UTC, KayAhnDS commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +        KoreanEntryTableViewContoller.entries = entries
didTapKoreanEntryButton 메서드에서 뷰를 생성할 때 생성자를 통해서 전달 하려고 했지만 다운캐스팅과 생성을 함께 하지 못한다 라고 결론이 나 이전 방식은 그대로 두었고, 대신 KoreanEntryTableViewController에서 KoreanEntryTableViewCell로 데이터를 넘기는 방식을 수정함으로써 데이터를 넘기는 다른 방법을 구현해 보았습니다. 제이크가 생각하셨던 KoreanEntryTableViewController에서 할당하는 방법을 듣고싶습니다!

2022-06-20 08:53 UTC, KayAhnDS commented on Expo1900/Expo1900/Controllers/KoreanEntryTableViewController.swift
> +        guard let entryCell = cell as? KoreanEntryTableViewCell else {
말씀해주신대로 수정했습니다!

2022-06-20 08:54 UTC, KayAhnDS commented on Expo1900/Expo1900/Controllers/KoreanEntryTableViewController.swift
> +        entryCell.entryImageView.image = data?.thumbnail
말씀하신 부분을 KoreanEntryTableCell에서 처리하도록 했습니다!

2022-06-20 08:57 UTC, KayAhnDS commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +//  Expo1900 - ViewController.swift
파일명과 동일하게 수정 했습니다!

2022-06-20 12:19 UTC, OldStarKR commented on Expo1900/Expo1900/Controllers/SelectedEntryViewController.swift
> +    @IBOutlet weak var selectedEntryImageView: UIImageView!
앗차 이 부분의 접근제한 처리를 놓쳤었군요.. 수정해 주었습니다!

2022-06-20 13:08 UTC, OldStarKR commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +    override func awakeFromNib() {
[공식 문서](https://developer.apple.com/documentation/objectivec/nsobject/1402907-awakefromnib)에 의하면, nib 로딩 구조가 nib 아카이브에 들어 있는 모든 오브젝트가 로드되고 초기화되고 난 다음에 오브젝트에 awakeFromNib 메시지를 보낸다고 합니다. 이 말은 곧, 해당 오브젝트에 필요한 IBOutlet이나 IBAction이 모두 연결되어 있음을 보장하는 것입니다. awakeFromNib를 사용하는 경우는, '디자인 타임'에 진행될 수 없는 추가적인 설정을 진행해주고자 할 때 사용한다고 합니다.

awakeFromNib에 대해 알아보면서, 해당 테이블 뷰 셀에 강제 언래핑한 것에 대해 조금 더 생각해보게 되었습니다. 비록 야곰의 예제를 보고 따라했고, 해당 강의에서는 초기값을 설정해준 후 마치 IBOutlet을 쓰는 느낌으로 사용했지만, 실은 그것보다 훨씬 위험하지 않나 하는 생각도 하게 되었습니다. 해당 방법이 왜 문제가 있는지, 또는 왜 문제가 없는지, 조금 더 알아봐야 할 것 같다고 느꼈습니다.

2022-06-20 14:53 UTC, jryoun1 reviewed
넵 수정하신 부분들 모두 확인했습니다~ 고생하셨습니다 👏
다만 이 부분도 확인이 되었는지가 궁금하네요. 🤔
- https://github.com/yagom-academy/ios-exposition-universelle/pull/181#pullrequestreview-1011512899

여기서 어떤 부분을 step3에서 수정 할 예정인지 저에게도 코멘트 혹은 dm을 통해서 알려주시면 감사하겠습니다 🙏🏻 
수정하신 부분에서 몇가지 의견 남겨두었습니다. 확인 부탁드릴게요~

2022-06-20 14:53 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +        configurePosterView()
수정된 부분이 아래와 같아서 말씀드립니다 🙏🏻
제가 설명을 헷갈리게 한 것 같네요. 🥲 
제가 말씀드린 수직거리는 configurePosterView() 함수의 실제 구현부분으로 아래와 같이 configurePosterView()가 viewDidLoad 바로 밑에 위치하는 것이었습니다. 
```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        // 여기가 수정된 부분
        configurePosterView()
    }

     private func configurePosterView() {
           guard let asset = NSDataAsset.init(name: "exposition_universelle_1900"),
                 let poster = try? JSONDecoder().decode(ExpositionPoster.self, from: asset.data) else {
               return
           }

           titleLabel.text = poster.title
           visitorsLabel.text = poster.visitorContents
           locationLabel.text = poster.locationContents
           durationLabel.text = poster.durationContents
           descriptionLabel.text = poster.description

           posterImageView.image = UIImage(named: "poster")
           leftFlagImageView.image = UIImage(named: "flag")
           rightFlagImageView.image = UIImage(named: "flag")
       }
```

2022-06-20 14:53 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +        KoreanEntryTableViewContoller.entries = entries
> didTapKoreanEntryButton 메서드에서 뷰를 생성할 때 생성자를 통해서 전달 하려고 했지만 다운캐스팅과 생성을 함께 하지 못한다 라고 결론

말씀하신 부분 중에서 위의 부분이 잘 이해가 되지 않네요. 🤔

KoreanEntryTableViewController에서 SelectedEntryViewController로 이동할 때는 tableview에서 사용자가 누른 index를 기반으로 entries 배열에 있는 데이터를 넘겨주기 때문에 버튼을 누를 때 데이터를 넘겨주게 됩니다.

반면에 ExpositionPosterViewController에서 KoreanEntryTableViewController로 넘어올 때는 굳이 `didTapKoreanEntryButton` 함수 내부에서 asset을 불러오고, decode를 하고  KoreanEntryTableViewController의 entries 라는 변수에 할당을 해주어야할 필요가 없어보입니다. 
또한 ExpositionPosterViewController가 entries라는 변수를 알아야할 이유도 없을 것 같습니다.

즉, KoreanEntryTableViewController의 viewDidLoad()에서 asset과 decode를 해주어도 될 것 같은데 어떻게 생각하시나요?

2022-06-20 14:53 UTC, jryoun1 commented on Expo1900/Expo1900/Models/ExpositionPoster.swift
> +    private let visitors: Int
👏

2022-06-20 14:53 UTC, jryoun1 commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +    private var entryImageView: UIImageView!
코드로 뷰를 작성할 때 UIComponent를 생성하는 다른 방법은 아래와 같이 생성을 해줄 수 있습니다. 
```swift
private lazy var entryImageView: UIImageView = {
      let imageView = UIImageView()
      imageView.translatesAutoresizingMaskIntoConstraints = false
      return imageView
}()
```
이렇게 된다면 아래의 각각의 UIComponent를 setup해주는 부분을 작성해주지 않아도 됩니다. 
또한 이렇게 되면 해당 UIComponent가 어떻게 초기화 되었는지 확인하기 위해서 스크롤을 내렸다가 올렸다가 하지 않아도 되는 장점도 있을 것 같네요 (수직거리가 짧으면 좋다는 것의 예시가 될 수도 있겠네요)

추가로 `lazy` 키워드에 대해서도 나중에 공부해보시면 좋을 것 같네요

2022-06-20 14:53 UTC, jryoun1 commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +    private func setupImageView() {
개인적으로는 각각의 
1. UIComponent의 attributes들을 설정하는 함수 
2. UIComponent들의 배치를 설정하는 함수

로 구분하는걸 선호합니다.

예를 들어 아래와 같이 구분할 수 있을것 같기도 하네요 🙏🏻
```swift
private func setupAttribute() { // 각각의 UIComponent들의 속성을 지정해주는 함수 }
private func setupLayout() { // 각각의 UIComponent들의 layout을 배치해주는 함수 }
```

2022-06-20 14:53 UTC, jryoun1 commented on Expo1900/Expo1900/Views/Protocols/ReuseIdentifying.swift
> +        return String(describing: Self.self)
적용해보셨네요 👏 💯

2022-06-20 15:06 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/KoreanEntryTableViewController.swift
> +        return entries?.count ?? 1
실패하는 경우까지 고려를 해주셨군요 👏 좋습니다.

entries 값은 assets에서 불러오고 decode를 했을 때 문제가 발생하는 경우 guard문의 else를 통해서 에러 처리를 해줄 수도 있겠네요. else문 블럭에서 데이터를 불러오거나 decode에 실패했음을 보여줄 수 있을 것 같네요.

그리고 실질적으로 guard문을 통과했을 때 (즉, 문제가 발생하지 않고 정상적으로 decode까지 되었을 때) 값이 0인 경우에는 실제로 값이 없는 것이기 때문에 이에 대한 처리는 따로 해주어야할 것 같다고 생각이 드네요. 

만약 사용자에게 0개일 때 불러오는 것에 실패했는지, 실제로 불러왔는데 0개인지에 대해서 인지를 시켜주고 싶다면 
1. activity indicator 사용
2. tableview의 footerview에 총 개수를 반환 
하는 등의 방법들도 존재할 것 같습니다. 🙏🏻 

이러한 부분이 현재 기획에 나와있는 것은 아니니 step3까지 마치고 나서 시간이 남는다면 한 번 진행해보셔도 좋을 것 같네요 👍🏻

2022-06-20 15:14 UTC, jryoun1 commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +    var entryImageView: UIImageView!
아마 야곰은 강의이다 보니까 각각의 UIComponent를 옵셔널로 선언하고 
이를 사용하는 부분에서 안전하게 추출해서 사용하는 것이 코드가 길어지다 보니까 강제 언래핑으로 선언하고, 
강의에서는 이러한 강제 언래핑을 지양하라고 하셨을 것 같긴합니다. 🤔

> 비록 뷰 인스턴스는 자원 소모가 크기 때문에 하나하나 더할 때 신중해야 하지만

요즘 휴대폰 성능이 좋기 때문에 너무 신중하지 않으셔도 되긴합니다 ㅎㅎ 그렇다고 막 낭비하라는 뜻은 아닙니다 ☺️ 
필요한 컴포넌트라면 생성하는 것이 옳고, 이때 선언 및 할당을 강제 옵셔널을 사용하기보다는 아래 새로운 리뷰에서 말씀드린 방법이나
```swift
var entryImageView = UIImageView() 
```
이런식으로 선언하는 것이 안전해 보입니다 🙏🏻

2022-06-22 08:36 UTC, OldStarKR commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +        configurePosterView()
수직거리의 개념에 대해 아직 저희가 잘 몰라서 일어난 해프닝인 것 같습니다😂

2022-06-22 08:38 UTC, OldStarKR commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +    private var entryImageView: UIImageView!
이렇게 생성하는 방법이 있었지!! 하고 생각이 납니다😅 수정해주었습니다!

2022-06-22 08:38 UTC, OldStarKR commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +    private func setupImageView() {
확실히 각각의 요소별로 설정하는 것보다, 같은 종류의 작업을 한 메서드에 묶어서 해 주는 것이 좋은 것 같습니다😃

2022-06-22 08:44 UTC, KayAhnDS commented
코멘트 해주신 부분은 모두 수정 하였으나 한가지를 수정하지 못했습니다.
self.navigationController?.navigationBar.standardAppearance = appearance
self.navigationController?.navigationBar.scrollEdgeAppearance = appearance
등 여러가지 방법을 적용해보았으나 말씀 해주신것처럼 출품작의 상세 정보로 처음 들어갔을 때 네비게이션 바의 색상이 다른 부분은 수정하지 못했습니다.

2022-06-22 12:19 UTC, jryoun1 approved these changes
잘 수정해주셨네요 👏
고생하셨습니다! 

![image](https://user-images.githubusercontent.com/45090197/175022623-33810bd9-e68c-4696-ac72-a5e7a6115f90.png)
이 부분에 대해서는 [이 글](https://velog.io/@wook4506/iOS-Swift-Navigation-Controller)이 navigation Controller에 대해서 설명하고 있는 것 같아서 한 번 참고해보시면 좋을 것 같습니다 🙏🏻

그리고 제가 말씀드린 navigationBar의 색상부분은 iOS 15이후로 기존과 다르게 변화가 생겼습니다. 
한 번 관련된 [글](https://www.zehye.kr/ios/2021/10/19/iOS_ios15_navigation_bar/)을 읽어보시면 좋을 것 같네요 🙏🏻

이 부분은 step3에서 반영해주셔도 될 것 같아서 step2는 여기서 merge하겠습니다~ 
그럼 남은 기간동안 step3도 화이팅입니다 💪🏻

2022-06-22 12:19 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +        self.navigationController?.isNavigationBarHidden = true
잘 숨겨주셨군요 👏
`self` 를 붙여주시는 기준이 있을까요? 🙋‍♂️

2022-06-22 12:19 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/KoreanEntryTableViewController.swift
> +    private func setupTableViewData() {
tableViewData를 셋업하는 함수인 것 같지는 않습니다 🤔

2022-06-22 12:23 UTC, merged