만국박람회 [STEP3] 웡빙, bonf
yagom-academy/ios-exposition-universelle pull request #185
Opened 2022-06-22 05:31 UTC by wongbingg

안녕하세요 @corykim0829  step3 PR 보냅니다 ! 궁금한 점 밑에 남겨 두었습니다 잘 부탁드립니다 !! 
@wongbingg @apwierk2451

# Step3
기간 : 2022.6.21(화) ~ 2022.6.22(수)
## 구현사항
### - 오토레이아웃
- **모든 아이폰 화면에 맞춤**

### - Accessibility
- **줄임표 처리**
    - Accessibility Inspector 에서 배율 조절을 최대로 했을 때, label이 ... 으로 생략되는 부분
    - UILabel의 속성 numberOfLInes = 0 으로 해주어 해결 (Line Break를 따로 설정해줄 필요가 없었다)
- **text Style**
    - Dynamic Type으로 설정 해주기 위해 폰트 스타일을 custom이 아닌 , 내장되어있는 systemFont를 이용했다. 
    - `adjustsFontForContentSizeCategory` 프로퍼티를 true 로 설정 해주었다. 
    - **결과** : Accessibility Inspector 에서 배율설정을 할 때마다 동적으로 글자 크기가 바뀐다.
- **Voice Over**
    - 개최기간에 대힌 accessibility Label 을 수정 해주었다.
    - MainViewController 에 description label 만 읽어지지 않는 현상 발생 
### - DetailView 내의 imageView 설정
- **크기지정**
    - imageView 의 contentMode 를 scaleAspectFit 으로 설정해주니 사진의 원본비율로 나왔다. 
    - 해금과 나전칠기 사진에서는 높이가 극적으로 늘어나는 현상이 발생
    - imageView의 heightAnchor.constraint(lessThanEqualToConstant:)로 높이의 최대값에 제한을 주었더니 해결 되었다.

### - Device Orientation
- **세로모드 고정**
    - AppDelegate 에 `orientationLock` 변수를 만들어 MainViewController 에서만 .portrait 로 설정 해주었다.

     <img src="https://user-images.githubusercontent.com/95671495/174949389-5c3ef202-4e57-4f03-b810-dbb905f82548.gif" width="250" height="250"/>
     <img src="https://user-images.githubusercontent.com/95671495/174949512-9cba4c2e-9b89-4a35-8d70-4e81cba5b70c.gif" width="250" height="250"/>

## 🛠Trouble Shooting🛠

### 화면전환 깨짐
<img src="https://user-images.githubusercontent.com/95671495/174950739-294f46c8-a21c-4b0f-ba60-42ceaae530bf.gif" width="250" height="500"/>

- backgoundColor를 systemBackground 로 지정해주었더니 해결 되었다. 

## 궁금한점
- **AccessibilityLabel**
    - MainViewController 의 desc 부분이 읽어지지 않았습니다. AccessibilityLabel에 다시 추가를 해주었음에도 읽히지 않는 이유가 궁금합니다 ! 
- self.contentView.heightAnchor 와 self.heightAnchor 의 차이점 
    - ItemTableViewCell 에서 오토레이아웃 constraints 작업 중, 셀의 내용이 길어지면 셀높이도 같이 조절되도록 만들어 주었는데, 해금과 나전칠기의 imageView 높이조절 문제가 있었습니다. 밑에 첨부한 코드 하나만 바꿨더니 해결이 되었습니다. 왜 이렇게 되는지 궁금해서 여쭤보고 싶습니다 !

  <img src="https://i.imgur.com/Zpc7MPj.png" width="250" height="500"/>
  <img src="https://i.imgur.com/C8DrYUN.png" width="250" height="500"/>

![](https://i.imgur.com/XL5SyIi.png)

<img src="https://i.imgur.com/juYmK7f.png" width="250" height="500"/>

![](https://i.imgur.com/Oy88MCE.png)

2022-06-22 16:12 UTC, corykim0829 requested changes
수고많으셨습니다 👏👏👏

앞서 해드린 피드백을 기반으로 코드가 전반적으로 가독성이 좋아지고, 깔끔해진 것 같습니다!

---

질문 해주셨던 부분은 저도 왜 생기는지 코드만 보고 알기 힘들었는데, 직접 코드를 몇번 실행해보고, 수정해보고나서 원인을 찾을 수 있었습니다.
비정상적으로 높이가 커지는 cell들의 특징을 살펴보니 모두 원본 이미지가 매우 컸습니다. 
imageView의 height를 contentView와 동일하게 처리하게 했지만, contentView에 있는 imageView에 이미지가 들어가게 되니 imageView, contentView가 동시에 커지게 되버립니다.

이제 두분이서 수정하신 그냥 heightAchor는 cell 자체의 heightAnchor를 같게 처리했을 때 위와 같은 현상이 나타지 않은 이유는 imageView가 contentVIew에 subview로 추가되었기 때문에, imageView가 늘어날 때, 영향을 받지 않은 것으로 보입니다.
그렇기 때문에 이제 cell의 높이를 결정짓는 것은 stackView의 top, bottom anchor이기 때문에 cell 높이가 잘 처리됐습니다!

2022-06-22 16:12 UTC, corykim0829 commented on Expo1900/Expo1900/DetailViewController.swift
> +        designateNavigationSetting()
깔끔하네요! 👍
이렇게 함수로 정리하면 viewDidLoad에서 어떤 작업을 하는지 보기 좋습니다

2022-06-22 16:12 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewCell.swift
> +    func parseData(from model: Item?) {
여기 함수명만 보면 Data를 리턴하는 함수 같아요.
또한 이 함수를 사용하는 곳에서 보게되면
`cell.parseData(from: items?[indexPath.row])`
`cell`객체가 `items?[indexPath.row]` 객체로부터 데이터를 파싱하는 것처럼 보여집니다.
`items?[indexPath.row]` 값을 cell 객체에 넘겨준다는 느낌으로 
set, update 와 같은 함수명을 사용하면 더 자연스러울 것 같은데, 어떻게 생각하시나요?

2022-06-22 16:12 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewController.swift
> +        cell.parseData(from: items?[indexPath.row])
이렇게 작성하면, 한줄에 너무 많은 코드가 들어가기 때문에, 줄을 분리시켜주는게 가독성을 높이는데 좋습니다.
``` suggestion
        let item = items?[indexPath.row]
        cell.parseData(from: item)
```

2022-06-22 16:12 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewController.swift
> +        detailViewController.parseData(from: items?[indexPath.row])
여기도 위와 마찬가지로 분리시켜서 가독성을 높여주면 좋을 것 같아요 😀

2022-06-22 16:12 UTC, corykim0829 commented on Expo1900/Expo1900/ItemTableViewController.swift
> +        detailViewController.parseData(from: items?[indexPath.row])
이 부분 pareData 함수명도 더 자연스럽게 바꾸면 좋을 것 같아요!

2022-06-23 08:37 UTC, apwierk2451 commented on Expo1900/Expo1900/ItemTableViewCell.swift
> +    func parseData(from model: Item?) {
updateData가 더 자연스럽다고 판단하여 리팩토링 실시했습니다!! 😁

2022-06-23 08:37 UTC, apwierk2451 commented on Expo1900/Expo1900/ItemTableViewController.swift
> +        cell.parseData(from: items?[indexPath.row])
가독성을 생각하여
let item = items?[indexPath.row]
cell.updateData(from: item) 로 리팩토링 하였습니다 !

2022-06-23 08:38 UTC, apwierk2451 commented on Expo1900/Expo1900/ItemTableViewController.swift
> +        detailViewController.parseData(from: items?[indexPath.row])
가독성을 생각하여
let item = items?[indexPath.row]
detailViewController.updateData(from: item) 로 리팩토링 하였습니다 !

2022-06-24 16:48 UTC, corykim0829 approved these changes
수고 많으셨습니다!
제가 접근성 관련 질문을 보지못하고 답변을 안해드렸네요! 죄송합니다 🥲

AccessibilityLabel

> MainViewController 의 desc 부분이 읽어지지 않았습니다. AccessibilityLabel에 다시 추가를 해주었음에도 읽히지 않는 이유가 궁금합니다 !

➡️ 제가 봤을 때에는 말씀해주신 MainVC의 descriptionLabel은 현재 `파리 만국박람회 1900 설명`으로 Voice over가 처리되고 있는데 이렇게 의도하신게 맞나요? 읽어지지 않는다는 것은 아예 읽어지지 않는 건지 궁금하네요!

2주간 프로젝트 진행하느라 두분 모두 고생 많으셨습니다 🙏

2022-06-24 16:48 UTC, merged