만국박람회 [STEP 3] Kay, 나이든별
yagom-academy/ios-exposition-universelle pull request #193
Opened 2022-06-23 22:34 UTC by OldStarKR

안녕하세요 @jryoun1  !
만국 박람회 마지막 Pull - Request 보내드립니다. 마지막 PR도 잘 부탁드립니다!🙇🏻‍♂️

### 작업한 내용

- 첫 화면만 세로로 고정.
- 컨텐츠가 잘 나오도록 테이블뷰 셀 오토-레이아웃 추가 및 수정.
- 포스터 모델 수정.
    - 관람객 NumberFormatter 추가
    - 문자열 포매팅 연산 프로퍼티 네이밍 통일
- 작품 상세 네비게이션바를 기능 요구서와 동일하게 수정.
- Word Wrapping 추가.
- Dynamic Type 적용.

### 고민한 점 및 조언을 얻고 싶은 점
- 이번 프로젝트에서 오토레이아웃에 많은 시간을 할애 하였습니다. 조금 더 연습 하고 싶은데 좋은 방법이 있을까요?
- 이전 PR 피드백 마지막 부분에서 `self`의 사용에 대해 기준이 있는지 여쭤봐 주셨습니다. 합의 하에 일단은, 중복된 네이밍으로 인해 혼동의 여지가 있는 경우에만 `self`를 활용했고 나머지는 모두 지워 주었는데요, 이 부분에 대해 가지고 계신 기준에 대해 여쭤보고 싶습니다.

### 참조한 사이트
https://stackoverflow.com/questions/38969419/ios-how-to-enable-and-disable-rotation-on-each-uiviewcontroller
https://developer.apple.com/documentation/uikit/uifont/scaling_fonts_automatically
https://stackoverflow.com/questions/70575637/avoid-navigation-bar-becoming-visible-when-theres-scrollable-content-beneath-it

2022-06-24 16:57 UTC, jryoun1 requested changes
@OldStarKR @KayAhnDS 안녕하세요 🙋‍♂️
step3까지 잘 마무리 해주셨네요.
2주동안 정말 고생많이 하셨고, 2주 전보다 확실히 코드 퀄리티가 많이 높아진 것 같습니다 🙏🏻

이번 스텝에서는 크게 코멘트 남길 부분이 없네요! 👏 
다만 몇 가지 이슈들이 존재해서 남깁니다.

## 고민한 점 및 조언을 얻고 싶은 점
> self의 사용에 대해 기준

아래 코멘트에 남겨두었습니다. 확인 부탁드려요 🙏🏻

> 이번 프로젝트에서 오토레이아웃에 많은 시간을 할애 하였습니다. 조금 더 연습 하고 싶은데 좋은 방법이 있을까요?

오토레이아웃을 연습하는 방법은 여러 가지가 있겠지만, 개인적으로는 많이 해보면 금방 익숙해졌던 것 같습니다. 야곰의 오토레이아웃 강의가 있었던 것 같은데 해당 강의를 수강해봐도 좋고, 6기 동기들과 오토레이아웃 스터디를 진행해도 좋은 방법이 될 수 있을 것 같네요 ☺️ 
스터디는 구현해보고 싶은 화면들을 구현해보는 방법이 있을 것 같네요! 
예를 들어 지난 프로젝트였던 계산기를 화면 부분만 구현해 본다던가, 배달의 민족의 메인화면 등 난이도를 보고 결정해서 연습해보는 것도 좋을 것 같습니다. 이때 코드로도 적용해보고 스토리보드로도 작성해보면 더욱 도움이 될 것 같네요 🙏🏻

## 이슈 🚨
1. ExpositionPosterViewController에서 방문객, 개최지, 개최기간같은 경우에는 글씨가 커지면 화면을 넘어가고 있습니다 🚨
<img src="https://user-images.githubusercontent.com/45090197/175575674-21ab74ea-95a9-46f8-9b61-e2d7048f889e.png" width=230 height=400>

2. 추가로 한국의 출품작 보러가기도 layout이 제대로 잡히지 않은 것 같습니다! 화면을 벗어나고 있습니다 🚨
<img src="https://user-images.githubusercontent.com/45090197/175576058-5888dc1c-d06f-4e1b-b4b8-ab438895e468.png" width=230 height=400>

3. KoreanEntryTableViewCell의 titleLabel에서 글씨가 커졌을 때 말줄임이 나오고 있네요 🚨
관련해서 `adjustsFontSizeToFitWidth` 에 대해서 알아보시면 좋을 것 같습니다 🙏🏻
<img src="https://user-images.githubusercontent.com/45090197/175605057-a555270e-0865-47cf-b75b-e4de60a70235.png" width=230 height=400>

2022-06-24 16:57 UTC, jryoun1 commented on Expo1900/Expo1900/AppDelegate.swift
>          // Override point for customization after application launch.
필요하지 않는 주석은 제거해주세요 🙏🏻

2022-06-24 16:57 UTC, jryoun1 commented on Expo1900/Expo1900/AppDelegate.swift
> +    var restrictOrientation = UIInterfaceOrientationMask.all
변수명은 방향 제한인데 할당되는 값은 방향인 것 같습니다. 
좀 더 명확한 네이밍은 없을까요? 🤔

2022-06-24 16:57 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/ExpositionPosterViewController.swift
> +        navigationController?.isNavigationBarHidden = true
`self`들을 제거해주셨네요 🙏🏻
`self`에 대한 저의 기준은 아래와 같습니다. 참고만 해주세요~
```swift
private let a: Int
private let b: Int

init(a: Int, b: Int) {
   self.a = a
   self.b = b
}
```
위와 같은 코드가 있을 때는 self.a를 통해 전역 프로퍼티임을 명시해주기 위해 사용하고 있습니다. 또한 클로저 내부에서 사용하는 self 또한 비슷한 이유일 것 같네요. 
이런식으로 **분명하게 명시적으로 표현을 해줘야하는 경우에는 self를 사용**하고 그렇지 않은 경우 (지난번 코멘트 드린 코드들)에서는 self를 사용하지 않아도 충분히 알 수 있다고 생각합니다 :)

2022-06-24 16:57 UTC, jryoun1 commented on Expo1900/Expo1900/Controllers/SelectedEntryViewController.swift
> +        let navigationBarAppearance = UINavigationBarAppearance()
잘 적용해보셨네요 👏

2022-06-24 16:57 UTC, jryoun1 commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +        accessoryType = .disclosureIndicator
이것도 setupAttribute() 함수에 포함될 수 있을 것 같아보입니다 🙏🏻

2022-06-24 16:57 UTC, jryoun1 commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +        shortDescriptionLabel.lineBreakMode = .byWordWrapping
iOS 14부터 새롭게 나온 [한글에 대한 설정](https://developer.apple.com/documentation/uikit/nsparagraphstyle/linebreakstrategy/3667458-hangulwordpriority)도 한 번 적용해보면 좋을 것 같습니다 🙏🏻

2022-06-29 05:40 UTC, OldStarKR commented on Expo1900/Expo1900/AppDelegate.swift
>          // Override point for customization after application launch.
맨 처음부터 생성되어 있던 주석이라 그냥 방치했던 것 같습니다😅 삭제해 주었습니다.

2022-06-29 05:41 UTC, OldStarKR commented on Expo1900/Expo1900/AppDelegate.swift
> +    var restrictOrientation = UIInterfaceOrientationMask.all
말씀해주신 대로 방향을 제한한다기보다는, 방향을 허가해준다는 느낌에 더 가까웠습니다. 그래서 `allowedScreenPosition`으로 변수명을 바꿔 주었습니다☺️

2022-06-29 05:42 UTC, KayAhnDS commented
말씀 해주신 '글씨가 커지면 화면을 넘어가고 있습니다' 와 stackView의 오토레이아웃을 각각 수정해주고, adjustsFontSizeToFitWidth에 대해 공부해보고 적용까지 해주었습니다!

2022-06-29 05:42 UTC, OldStarKR commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +        accessoryType = .disclosureIndicator
확실히 듣고 보니 굳이 따로 떨어져 있을 필요는 없다는 생각이 듭니다..! 셀이 가지고 있는 속성을 정해주는 코드니까 `setAttributes()` 안에 같이 들어 있어도 좋겠다는 생각이 드는군요

2022-06-29 05:46 UTC, OldStarKR commented on Expo1900/Expo1900/Views/KoreanEntryTableViewCell.swift
> +        shortDescriptionLabel.lineBreakMode = .byWordWrapping
`hangulWordPriority`, 나아가 `lineBreakStrategy`에 대해서도 알아보고 적용해 보았습니다! 이 경우 `lineBreakMode`를 굳이 함께 정해주지 않아도, 한글 단어 단위로 줄바꿈이 이루어지는 것을 확인했습니다. 그래서 최종적으로는 `shortDescriptionLabel.lineBreakMode = .byWordWrapping` 부분을 `shortDescriptionLabel.lineBreakStrategy = .hangulWordPriority` 로 수정해주는 방향으로 작업했습니다!!

2022-06-29 12:42 UTC, jryoun1 approved these changes
고생하셨습니다 👏
수정하신 부분 확인했습니다 🙏🏻
잘 수정해주셔서 크게 코멘트 남겨드릴게 없습니다 ㅎㅎ 

2주 동안 두 분의 코드를 리뷰하게 되어서 영광이었습니다.
그럼 남은 캠프생활동안 화이팅입니다 💪🏻

2022-06-29 12:43 UTC, merged