만국박람회 [Step 1] Ayaan, Bella
yagom-academy/ios-exposition-universelle pull request #201
Opened 2022-10-18 02:09 UTC by hyhy0429

안녕하세요! 올라프 ☃️ @1Consumption 
만국박람회 프로젝트 짝이된 아얀과 벨라입니다! 🙌🏼
잘 부탁드립니다! 🙏🏼

### [고민했던 점]
- JSON을 위한 `ExpositionUniverselleItem` 타입 구현 시, `UIImage` 타입을 계산 프로퍼티로 가지고 있도록 타입 내에서 구현하였으며, 타입 내에서만 사용하게 될 `imageName` 프로퍼티는 외부에서 알 필요가 없다고 생각되어 `private`으로 접근제어자를 지정해주었습니다.
- 타입 내의 프로퍼티를 구현할 때에, `let`과 `private(set) var` 의 차이에 대해 고민하게 되었습니다. 처음에는 둘의 차이점을 느끼지 못하였으나 서로 이야기를 나눈 후, `let`은 타입 외/내부 모두에서 변경이 불가능하고 `private(set) var`는 외부에서는 변경이 불가하나 내부에서는 변경이 가능하다는 차이점을 발견하게 되었습니다. 

### [조언이 필요한 점]
- 저희가 구현한 방법처럼, `ExpositionUniverselleItem` 타입 내에 계산 프로퍼티인 `image`를 이용하여 `UIImageView`에 할당해주는 방법과, 추후 직접적으로 `UIImage`를 생성하여 할당해주는 방법 중 어떤 방법이 더 효율적인지 올라프의 생각이 궁금합니다! 🙄

2022-10-18 14:21 UTC, 1Consumption requested changes
안녕하세요 @hyhy0429 @oneStar92
잘 부탁드립니다~🖐️

이번 스텝은 작아서 딱히 말할게 없네요.

코멘트를 참고해주세요.

2022-10-18 14:21 UTC, 1Consumption commented on Expo1900/Expo1900/ExpositionUniverselle.swift
> +struct ExpositionUniverselle: Codable {
Codable은 어떤 역할을 하나요? 그리고 지금 정말 필요한가요?

2022-10-18 14:21 UTC, 1Consumption commented on Expo1900/Expo1900/ExpositionUniverselleItem.swift
> +import UIKit
이 객체는 Model인가요 View인가요? Model이라면 UIKit을 import 하는게 역할에 맞나요?

2022-10-18 14:21 UTC, 1Consumption commented on Expo1900/Expo1900/ExpositionUniverselleItem.swift
> +    }
지금은 asset에 Image가 있는걸 알아서 이렇게 할 수 있는데, 만약 나중에 서버에서 이미지를 받아온다면 이 방법이 괜찮을까요?

2022-10-18 16:07 UTC, hyhy0429 commented on Expo1900/Expo1900/ExpositionUniverselle.swift
> +struct ExpositionUniverselle: Codable {
[Codable](https://developer.apple.com/documentation/swift/codable) 의 설명을 참고하였을 때,  encoding과 decoding을 모두 어우르는 별칭으로 알고 있습니다. 
현재 과제의 경우에, 가져오고자 하는 데이터를 JSON을 활용해, decoding하는 과정이 필요하므로 Decodable만 써도 될 것 같아 수정하였습니다.

2022-10-18 16:08 UTC, hyhy0429 commented on Expo1900/Expo1900/ExpositionUniverselleItem.swift
> +import UIKit
Model 이라고 생각하고, 파일을 생성하고 코드를 구현하는 과정에서 UIKit을 지우지 못했던 것 같습니다! 🥲

2022-10-19 13:19 UTC, oneStar92 commented on Expo1900/Expo1900/ExpositionUniverselleItem.swift
> +import UIKit
[c500f9e](https://github.com/yagom-academy/ios-exposition-universelle/pull/201/commits/c500f9e944cad42bf6919c4d7dbb006412f909d3) 해당 부분은 UIImage를 사용하기 위해서 import했습니다.
현재 리뷰 내용을 바탕으로 리팩토링을 과정을 거쳐 수정되었습니다.

2022-10-19 13:21 UTC, oneStar92 commented on Expo1900/Expo1900/ExpositionUniverselleItem.swift
> +    }
[c500f9e](https://github.com/yagom-academy/ios-exposition-universelle/pull/201/commits/c500f9e944cad42bf6919c4d7dbb006412f909d3) DM으로 이야기 해주신 내용을 바탕으로 생각하고 벨라와 이야기나눈 결과 DTO는 DTO만의 역활을 하는게 맡다고 생각되어 수정했습니다.

2022-10-19 13:28 UTC, 1Consumption approved these changes
고생하셨습니다. 다음 스탭을 진행하세요.

2022-10-19 13:28 UTC, merged