만국박람회 [STEP 1] Jeremy, 준호
yagom-academy/ios-exposition-universelle pull request #205
Opened 2022-10-18 03:05 UTC by yjjem

안녕하세요 ***`올라프`*** ☃️
@1Consumption
Jeremy 와 준호 입니다. 이번 프로젝트 잘 부탁드립니다.

## ✏️ 구현 내용
JSON 포맷의 데이터와 매칭할 모델 타입을 구현했습니다.

```swift
// 만국박람회 메인
struct Exposition: Codable {
    var title: String
    var visitors: Int
    var location: String
    var duration: String
    var description: String
}
```

```swift
// 박람회 출품작
struct ExpoEntry: Codable {
    var name: String
    var imageName: String
    var shortDescription: String
    var description: String
    
    enum CodingKeys: String, CodingKey {
        case name
        case imageName = "image_name"
        case shortDescription = "short_desc"
        case description = "desc"
    }
}
```

## 🌏 조언을 얻고 싶은 부분

공식문서에는 아래와 같이 Asset의 속성 인코딩을 가지고 있다고 적혀있어 Xcode 프로젝트 파일 내에 Asset을 추가시 요구되는 사항이라고 생각을 했습니다. 하지만 이미지만 따로 넣었을 떄 아무런 문제 없이 잘 들어가는 것을 확인한 바 있습니다.

그래서 따로 넣어준 이유가 있다고 추측하고 있습니다. Contents.json의 역할이 무엇인지 궁금합니다.

![](https://i.imgur.com/eu2zvB4.png)

 <center> <image src="https://i.imgur.com/QGgVii6.png" width="350px"/> </center>

```javascript
// Contents.json

{
  "images" : [
    {
      "filename" : "folds~universal@1x.png",
      "idiom" : "universal",
      "scale" : "1x"
    },
    {
      "filename" : "folds~universal@2x.png",
      "idiom" : "universal",
      "scale" : "2x"
    },
    {
      "filename" : "folds~universal@3x.png",
      "idiom" : "universal",
      "scale" : "3x"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
```

2022-10-18 14:49 UTC, 1Consumption requested changes
안녕하세요 @yjjem @junho15 
잘 부탁드립니다.

스텝이 워낙 작아서 코멘트는 별로 없습니다.

---------------------

Contents.json의 역할은 해상도별로 다른 이미지를 제공하거나, 이미지의 메타데이터를 담는 용도라고 알고 있습니다. 
이 [링크](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/AssetTypes.html)를 보면 required로 되어있으니 꼭 유지해주세요.

2022-10-18 14:49 UTC, 1Consumption commented on Expo1900/Expo1900/ExpoEntry.swift
> +struct ExpoEntry: Codable {
Codable은 무엇인가요? 그리고 왜 사용하셨나요? 정말 Codable의 모든 기능이 필요할까요?

2022-10-18 14:49 UTC, 1Consumption commented on Expo1900/Expo1900/ExpoEntry.swift
> +    var description: String
왜 var인가요? 바뀔 일이 있나요?

2022-10-18 14:49 UTC, 1Consumption commented on Expo1900/Expo1900/Exposition.swift
> +}
import Foundation을 안해줘도 컴파일 에러가 안나던가요?

2022-10-19 01:26 UTC, yjjem commented on Expo1900/Expo1900/ExpoEntry.swift
> +struct ExpoEntry: Codable {
```swift
typealias Codable = Decodable & Encodable
```
Codable은 위와 같이 Decodable과 Encodeable Protocol을 편의를 위해 묶어놓은 typealias라고 알고있습니다.

2022-10-19 01:37 UTC, yjjem commented on Expo1900/Expo1900/ExpoEntry.swift
> +struct ExpoEntry: Codable {
```swift
typealias Codable = Decodable & Encodable
```
Codable은 위와 같이 Decodable과 Encodeable Protocol을 편의를 위해 묶어놓은 typealias라고 알고있습니다.
잘 생각해보니 Encoding 기능이 필요없다면 Codable을 채택할 이유가 없습니다. Decodeable만 채택하도록 수정하였습니다.

[ 📝 수정 내용](https://github.com/yagom-academy/ios-exposition-universelle/pull/205/commits/8641ce46628c48a8506764a98b1098f49a57f60d)

2022-10-19 01:40 UTC, yjjem commented on Expo1900/Expo1900/ExpoEntry.swift
> +    var description: String
다시 생각해보니 데이터가 바뀔 일이 없어 `var` -> `let` 으로 수정하였습니다.

[ 📝 수정 내용](https://github.com/yagom-academy/ios-exposition-universelle/pull/205/commits/83024b7eb9e635d7291e8813064444de523b5d8c)

2022-10-19 01:47 UTC, yjjem commented on Expo1900/Expo1900/Exposition.swift
> +}
import Foundation을 제거해도 컴파일 에러는 나지 않았습니다.
이번 스탭에서는 데이터 타입에 맞는 구조체를 구현하는 것이 목표이기 떄문에 import를 생략했습니다.
Foundation의 기능이 필요할떄만 import하기로 했습니다.

2022-10-19 11:20 UTC, 1Consumption approved these changes
고생하셨습니다. 다음 스텝을 진행하세요.

2022-10-19 11:20 UTC, 1Consumption commented on Expo1900/Expo1900/ExpoEntry.swift
> +    private enum CodingKeys: String, CodingKey {
사소한 디테일 좋네요💯

2022-10-19 11:20 UTC, merged