만국박람회 [STEP 1] Gundy, Dragon
yagom-academy/ios-exposition-universelle pull request #209
Opened 2022-10-18 05:03 UTC by Gundy93

@junbangg 
안녕하세요! 알라딘! Prince Ali~🕌
만국박람회 - STEP1 완료하고 PR 드립니다.

DataSet-JSON 파일과 매칭될 `Exhibition`, `Exposition`파일을 추가하였습니다.

### 조언을 얻고 싶은 부분

- JSON 파일과 매칭할 타입을 작성할 때, Unit Test 등을 하고자한다면 어떤 방식으로 진행할 수 있을까요? 당장 에셋이 추가되는 스텝이 아니고 파일만 만드는 것이 이번 스텝의 내용이라서, 이런 경우엔 어떤 방법으로 테스트를 진행할 수 있을지 궁금합니다.
- 현재 Exhibition 타입의 경우에는 `CodingKeys`가 있기 때문에 모든 프로퍼티에 대해서 `private` 키워드를 붙여도 문제없이 디코딩이 될 것 같습니다. Exposition 타입의 경우 `CodingKey`가 없는데, 접근 제어자를 설정할 수 있는지, 앞으로 어떻게 사용될지 모르는 JSON 매칭 타입의 프로퍼티들을 접근 제어 설정하는 것이 더 좋은지! 등등이 궁금합니다!
- 프로젝트 초반부터 폴더 정리를 하면 어떨까 싶어서 폴더를 싹 정리해보았습니다. 혹시 이번 폴더 정리에 대해서 더 좋은 방향으로 개선할 사항이나, 알라딘의 방식은 이러하다 같은 조언을 구할 수 있을까요?

2022-10-19 00:14 UTC, junbangg requested changes

2022-10-19 00:14 UTC, junbangg commented on Expo1900/Expo1900/Sources/Model/Exposition.swift
> +    let visitors: Int
요건 네이밍+타입이 살짝 어색한 느낌이 들어요! 이름 명단으로도 받아들일 수 있는 느낌스?

2022-10-19 00:14 UTC, junbangg commented on Expo1900/Expo1900/Sources/Model/Exposition.swift
> +    let visitors: Int
두분은 오떻게 생각하시나요

2022-10-19 00:27 UTC, junbangg commented
스텝1은 뭐가 별로 없군요!
질문 주신거 답변 드리겠습니다~

```
JSON 파일과 매칭할 타입을 작성할 때, Unit Test 등을 하고자한다면 어떤 방식으로 진행할 수 있을까요? 당장 에셋이 추가되는 스텝이 아니고 파일만 만드는 것이 이번 스텝의 내용이라서, 이런 경우엔 어떤 방법으로 테스트를 진행할 수 있을지 궁금합니다.
```
흠 근데 역시 테스트 하고싶으신 내용은 어떤것일까요?!

```
현재 Exhibition 타입의 경우에는 CodingKeys가 있기 때문에 모든 프로퍼티에 대해서 private 키워드를 붙여도 문제없이 디코딩이 될 것 같습니다. Exposition 타입의 경우 CodingKey가 없는데, 접근 제어자를 설정할 수 있는지, 앞으로 어떻게 사용될지 모르는 JSON 매칭 타입의 프로퍼티들을 접근 제어 설정하는 것이 더 좋은지! 등등이 궁금합니다!
```
말씀하신것 처럼 해당 모델을 어떻게 사용할지에 따라 다르겠지만! 접근제어를 사용하는것도 근거만 있다면 문제 없어보입니다!!
private 같은 경우에는 나중에 어떻게 될지 모를때 저는 걸어두고 나중에 바꾸는 편이긴 해요!
안그러면 꼭 까먹더라고요...꼼꼼하질 못해서ㅋㅋ

```
프로젝트 초반부터 폴더 정리를 하면 어떨까 싶어서 폴더를 싹 정리해보았습니다. 혹시 이번 폴더 정리에 대해서 더 좋은 방향으로 개선할 사항이나, 알라딘의 방식은 이러하다 같은 조언을 구할 수 있을까요?
```
흠 두분은 그럼 이번에 다음과 같은 기준들에 대해서 고민해보고 세우신게 있을까요??

- 폴더를 나누는/정리하는 기준
- 타입들을 파일로 나눌때의 기준

2022-10-19 05:23 UTC, Gundy93 commented on Expo1900/Expo1900/Sources/Model/Exposition.swift
> +    let visitors: Int
방문객의 숫자라는 것을 더 직관적으로 알 수 있도록 네이밍 변경하도록하겠습니다! JSON 데이터의 형식에서 이름을 그대로 가져다쓰다가 생긴 문제같습니다.

2022-10-19 06:57 UTC, FlameYG commented on Expo1900/Expo1900/Sources/Model/Exposition.swift
> +    let visitors: Int
JSON 데이터의 형식을 그대로 가져오는 바람에 네이밍에서 애매함이 있었네요...
이 부분은 건디와 상의해서 네이밍 수정해보도록 하겠습니다~!

2022-10-20 03:23 UTC, FlameYG commented on Expo1900/Expo1900/Sources/Model/Exposition.swift
> +    let visitors: Int
`visitors` -> `numberOfVisitors`로 수정하였습니다~!

2022-10-20 03:33 UTC, Gundy93 commented
### 테스트하고 싶었던 내용
JSON 파일을 JSON 디코더를 통해 정의한 매칭 타입으로 변환하게 될텐데, 해당 매커니즘이 잘 작동하는지를 테스트하고 싶었습니다. 다시말해 저희가 작성한 타입으로의 변환이 잘 이루어지는지를 테스트하고 싶었습니다. 더불어 무언가 추가적으로 테스트할 만한 것이 있는지 궁금했습니다.

### 파일분류 기준
우선 폴더를 정리한 기준은 저희가 직접 소스코드를 작성하는 것은 Source, 그렇지 않은 asset 등은 Resource로 분류하였습니다. MVC 패턴의 시각에서 소스 파일들을 모델과 뷰, 컨트롤러로 분류하였고, app 자체와 관련된 delegate 파일들만 app으로 분류하였습니다. 결국 MVC에 입각한 분류체계가 목표였습니다.
타입별 파일 분리 기준은 한 타입은 단일 파일로 작성하는 것을 목표로 하였습니다. 그렇게 해야 타입을 수정할 일이 있을 때 쉽게 해당 소스 코드를 찾을 수 있을 것이라 생각했습니다. 단일 파일로 관리하면 유지 보수 등을 용이하게 할 수 있다고 생각합니다.

2022-10-20 10:47 UTC, merged

2022-10-21 15:54 UTC, junbangg commented
파싱이 제대로 되는지 테스트 하고싶으신거라면 `JSON` 을 직접 만드셔서 타입으로 제대로 변환이 되는지 확인하는 단위테스트를 작성해보는 것은 어떨까요???🤔

그리고 파일 분류는 정하기 나름인것 같아요..MVC를 기준으로 폴더를 분리하신것 잘해주신것 같아요~!
나중에 타입이 정말 많아지고 그러면 타입마다 파일을 만다는것에 대해서 다시 고민이 생기는 시점이 생길 수도 있을것 같다고 생각합니다:)
근데 지금은 타입이 별로 없어서 타입마다 파일을 만드신걸로 충분할것 같아요!