만국박람회 [STEP 2] Zhilly, Mangdi
yagom-academy/ios-exposition-universelle pull request #211
Opened 2022-10-20 08:32 UTC by zhilly11

@uuu1101
안녕하세요 태태! STEP-2 완료해서 PR 보냅니다~~
STPE-2의 커밋 일부분들을 STEP-1에서 리뷰받아서 내용이 많지 않습니다!.. 잘부탁드립니다 🙇🏻‍♂️🙇🏻

## 🤔 고민했던점
### KoreanEntriesViewController에서 EntriesViewController로 이동할때 UITableViewDelegate를 사용할지 세그의 prepare를 사용할지 고민되었습니다. 
테이블뷰의 셀을 클릭할때 값을 넘겨줘야하는데 
셀을 클릭하는 상호작용은 delegate가 맡을텐데 UITableViewDelegate를 이용하는것이 맞을것이다. 하는 생각과 
값을 넘겨주는 것이니까 세그를 사용하는게 맞다 하는 두가지 생각이 들었습니다. 둘중 어느방법이 나을까 고민하다가
테이블뷰의 indexPathForSelectedRow 라는 속성이 있다는것을 알곤, 세그의 prepare로 쉽게 구현이 가능했습니다.
만약 delegate로 구현했다면 코드가 훨씬 더 길어졌을것같단 생각이 들었습니다.
이로써 문서읽어보기의 중요성을 다시한번 상기시켜봅니다.
<img width="959" alt="스크린샷 2022-10-20 오후 5 22 53" src="https://user-images.githubusercontent.com/49121469/196896137-de523310-bf5c-45d3-9017-03352ecaa59d.png">

### View의 Title 수정
![](https://i.imgur.com/ZrAlc5A.png)

```swift
// 1번 방법
navigationController?.navigationBar.topItem?.title = "한국의 출품작"

// 2번 방법
self.title = "한국의 출품작"

```

여러가지 방법이 있었지만 가장 간단해 보이는 ViewController의 인스턴스 프로퍼티인 `title`을 수정하는 2번방법을 사용했습니다.

## ✏️ 조언을 얻고 싶은 부분

Cell을 만드는 방법을 두 가지정도 알고 있습니다.
1. 지금처럼 `contentConfiguration`을 사용하여 만드는 방법
2. Custom Cell을 만들어 사용하는 방법

요구사항이 Cell의 default 만 이용해도 될 것 같아서 현재는 1번 방식을 사용했습니다.

하지만 나중에 요구사항이 추가되거나 (ex: cell에 들어갈 이미지가 추가됨) 디자인이 변경된다면 1번 방법보다는 2번 방법으로 만들어 놓는 것이 유리해 보이기도 합니다. 두 방법중 태태가 선호하는 방법은 무엇인지, 두 방법중 지금 상황에서 어떤 것을 사용하는게 맞을지 태태 생각은 어떠신지 궁금합니다.

2022-10-21 15:41 UTC, uuu1101 requested changes
@zhilly11 @MangDi-L STEP2 진행하시느라 고생하셨습니다 :) 
몇가지 코멘트를 남겨두었으니 확인부탁드려요 🙇🏻‍♂️

- 뷰 라이프 사이클을 통해 네비게이션바가 안보이도록 처리를 해볼 수 있을것 같아요.
![Simulator Screen Shot - iPhone 11 - 2022-10-22 at 00 12 26](https://user-images.githubusercontent.com/49808034/197232898-94f01dd9-4902-415a-bcdb-2fa09c7a1ae7.png)
위 이미지와 동일한 부분을 프로젝트 요구사항에서 보면 네비게이션바가 노출되지 않는것을 확인할 수 있습니다 :) 

- TextView가 사용자 인터렉션을 받고 있어서 실제로 사용하는 사용자가 어색할수 있을것 같아요.
![스크린샷 2022-10-22 오전 12 13 09](https://user-images.githubusercontent.com/49808034/197233352-0e07fc01-43b3-4447-9ad7-02a7df83e65a.png)
해당부분은 TextView가 가지고 있는 프로퍼티를 찾아보시면 간단히 해결할 수 있습니다 ! (정확히는 UIKit.UIView 겠네요)

## ✏️ 조언을 얻고 싶은 부분에 대한 답
 - 나중에 요구사항이 추가되거나 (ex: cell에 들어갈 이미지가 추가됨) 디자인이 변경된다면 1번 방법보다는 2번 방법으로 만들어 놓는 것이 유리해 보이기도 합니다. 두 방법중 태태가 선호하는 방법은 무엇인지, 두 방법중 지금 상황에서 어떤 것을 사용하는게 맞을지 태태 생각은 어떠신지 궁금합니다.
 
> `contentConfiguration`를 사용해서 충분히 구현이 가능하다면, 상관없을 것 같아요. 정답이라는것이 없기 때문에 그때의 상황에 맞게 선택하셔서 하시면 될 것 같습니다.
 다만, 저의 경우에는 CustomCell을 만들어서 Cell이 할 수 있는 일들은 Cell이 하도록 하는것도 좋은 방법이라고 생각합니다 ! 실제로 CustomCell을 많이 사용하기도 했었구요 😊
두 방법을 모두 알고 한가지를 채택하여 사용한다면 문제가 되지 않을 것 같아요. 

이번 스텝에서는 TableView에 대해서 많이 다뤄보시고 다음 스텝으로 가시면 좋을것 같습니다 !

2022-10-21 15:41 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/EntriesDetailViewController.swift
> +    @IBOutlet weak var entryDescription: UITextView!
IBOutlet들도 접근제어자 설정을 할 수 있답니다. 되도록이면 `private`으로 감추는 습관을 들이는 게 좋을 것 같아요

2022-10-21 15:41 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/KoreanEntriesViewController.swift
> +        }
에러가 발생하더라도 사용자가 에러를 알수 없을것 같아요. 에러 표현을 해보는 건 어떨까요?

2022-10-21 15:41 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/KoreanEntriesViewController.swift
> +    }
segue를 사용해서 데이터 전달을 하셨네요 👍🏻

2022-10-21 15:41 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/KoreanEntriesViewController.swift
> +extension KoreanEntriesViewController: UITableViewDataSource {
[UITableViewDataSource](https://developer.apple.com/documentation/uikit/uitableviewdatasource)은 어떠한 역할을 하나요?!

2022-10-21 15:41 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/KoreanEntriesViewController.swift
> +extension KoreanEntriesViewController: UITableViewDelegate {
[UITableViewDelegate](https://developer.apple.com/documentation/uikit/uitableviewdelegate)도 한번 알아볼까요?!

2022-10-23 10:34 UTC, MangDi-L commented on Expo1900/Expo1900/Controller/EntriesDetailViewController.swift
> +    @IBOutlet weak var entryDescription: UITextView!
접근제어가 붙이는걸 깜빡했네요.. 항상 붙여주는 습관을 들이겠습니다..!

2022-10-23 10:50 UTC, zhilly11 commented on Expo1900/Expo1900/Controller/KoreanEntriesViewController.swift
> +        }
만약 에러가 난다면 사용자에게 오류를 알 수 있도록 alert을 띄워주도록 작성했습니다 :)

2022-10-23 10:52 UTC, MangDi-L commented on Expo1900/Expo1900/Controller/KoreanEntriesViewController.swift
> +extension KoreanEntriesViewController: UITableViewDataSource {
테이블의 섹션의 개수, 섹션에 해당하는 row의 개수와 헤더와 푸터 같은 테이블 관련 데이터 요청에 응답합니다.

2022-10-23 10:53 UTC, zhilly11 commented on Expo1900/Expo1900/Controller/KoreanEntriesViewController.swift
> +extension KoreanEntriesViewController: UITableViewDelegate {
셀을 선택했을때 액션을 설정할 수 있는 메서드나 table view의 섹션의 헤더나 푸터 등을 설정할 수 있는 메서드, 셀의 삭제나 변경등을 담당하는 메서드가 있는 프로토콜이라고 생각합니다!!~~

2022-10-23 10:58 UTC, zhilly11 commented
> 뷰 라이프 사이클을 통해 네비게이션바가 안보이도록 처리를 해볼 수 있을것 같아요.

네비게이션 바가 보이지 않도록 `isNavigationBarHidden()` 을 통해 설정해줬습니다!
또한, safe area에 대해서 설정 되어있던 오토레이아웃 제약사항들을 superview로 변경해줘서 요구사항에 맞도록 수정했습니다!

> TextView가 사용자 인터렉션을 받고 있어서 실제로 사용하는 사용자가 어색할 수 있을것 같아요.

TextView의 옵션에서 Editable 설정을 체크해제 해주는 방법으로 해결했습니다!

2022-10-24 02:38 UTC, uuu1101 approved these changes
고생하셨습니다 :) 
다음 스텝을 진행해주세요 !

2022-10-24 02:38 UTC, uuu1101 commented on Expo1900/Expo1900/View/Base.lproj/Main.storyboard
> +                                            <textView clipsSubviews="YES" multipleTouchEnabled="YES" contentMode="scaleToFill" scrollEnabled="NO" editable="NO" usesAttributedText="YES" translatesAuto
스토리보드로 TextView 속성을 변경해주셨군요 👍🏻
`MainViewController` 의 `func configureLabels` 에서 
![스크린샷 2022-10-24 오전 10 24 47](https://user-images.githubusercontent.com/49808034/197430007-1ad40a43-7293-4be4-9a2c-00b5734059a4.png)
이런식으로도 작성할 수 있습니다 ! (Lable을 configure 해주는 메서드인데, TextView도 configure해주고 있네요)
두 줄의 코드 중 첫번째줄 코드는 는 Edit에 관한것이고 그 아래는 유저의 인터렉션에 관한 코드입니다.
두 가지에 어떤 차이가 있는지 한번 경험해보시면 좋을 것 같아요.

2022-10-24 02:39 UTC, merged