만국박람회 [STEP 2] Ash, SummerCat
yagom-academy/ios-exposition-universelle pull request #213
Opened 2022-10-20 12:57 UTC by ttokin

@inwoodev 안녕하세요 제임스! 😄
오토 레이아웃..너무 좋아요...^^ 스텝2 완료해서 PR 요청드립니다!
두 번째 화면의 테이블 뷰 내의 셀의 제약조건 설정(이미지 크기 등)은 스텝3에서 해도 된다고 해서 우선 제외하고 진행했습니다.

## 🥹 고민한 점

1. `MainVC`에서 각 함수들이 하는 역할을 최대한 관련성 있는 것끼리 묶어서 역할 분리를 해 보려고 노력했는데, 제임스가 보기에는 적절하게 된 것 같으실까요?
    - 예: `updateLabelText` 함수에서 제목을 제외한 모든 레이블 텍스트를 업데이트

2. 다음의 총 4가지 상황에서 옵셔널 바인딩 처리가 필요했습니다.
    1. 데이터 애셋을 가져오는 상황
    2. json를 디코딩하는 상황
    3. 각 VC가 가지고 있는 객체의 인스턴스(exposition, item 등)에서 프로퍼티를 불러오는 상황
    4. 화면 전환을 위해 instantiateViewController(withIdentifier:) 메서드를 사용해 다음 ViewController의 인스턴스를 생성하는 경우

이 때, 단순히 `return` 하는 대신 어떻게 처리를 할 수 있을까 고민을 하다 우선은 alert를 띄워주는 정도로만 처리를 했습니다. (단, 이미지 표시에 실패한 경우에는 시스템 심볼 이미지를 띄워주는 것으로 대체) 현업에서 또는 제임스라면 보통 이런 경우 어떤식으로 처리를 해 주시는지 궁금합니다.

---

## 🤷‍♀️ 궁금한 점

```swift
extension KoreanItemViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableView.automaticDimension
    }
}
```
1. `rowHeight` 프로퍼티에 값을 지정해주지 않으면 `rowHeight`의 기본값이 `automaticDimension`으로 설정되어 있어 위 메서드를 구현해주지 않아도 자동으로 콘텐트의 intrinsic size에 맞는 높이를 제공하는 것으로 알고 있습니다. 실제로 위의 코드를 제거해도 화면이 정상적으로 표시되는 것을 확인할 수 있었습니다.
그런데 저희가 찾아보니 **automaticDimension 값을 사용해 customCell의 높이를 동적으로 지정해주기 위해서는 '오토레이아웃의 제약이 완벽해야 한다'** 는 내용이 있었던 것 같은데 이 말의 정확한 의미를 잘 모르겠습니다.

---

```swift
extension KoreanItemViewController: UITableViewDataSource {
    
    ...
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell: ItemTableViewCell = tableView.dequeueReusableCell(withIdentifier: self.cellIdentifier, for: indexPath) as? ItemTableViewCell else {
            return UITableViewCell()
        }
        
        cell.itemImage.image = UIImage(named: items[indexPath.row].imageName)
        cell.itemLabel.text = items[indexPath.row].name
        cell.itemDescription.text = items[indexPath.row].shortDesc
        cell.translatesAutoresizingMaskIntoConstraints = true
        cell.itemDescription.sizeToFit()
        return cell
    }
}
```

2. 1번의 메서드를 구현하든, 구현하지 않든 현재 셀의 높이를 별도로 지정해주지 않았기 때문에 `rowHeight`가 `automaticDimension`으로 설정되어 셀의 높이를 자동으로 계산할 수 있다고 생각했는데, 위 코드에서 **`sizeToFit()`을 주석 처리할 경우 셀 크기를 자동으로 계산하지 못하는 것** 으로 보였습니다. 왜 그런지 궁금합니다.
    - 이미지 뷰 1개, 레이블 1개, 텍스트 뷰 1개를 포함하는 **커스텀 셀을 구현**한 경우 아래 사진과 같이 모든 행이 일정하게 큰 높이로 표시되었습니다 (가장 긴 텍스트 뷰의 높이와 무관하게 더 길게).
![sizeToFit 제거 예시](https://i.imgur.com/ndVvmxb.png)
    - 현재는 기본으로 제공하는 subtitle 스타일의 셀을 사용하는 것으로 대체했습니다. 기본으로 제공하는 스타일의 셀을 사용하니 `.automaticDimension`, `sizeToFit()`을 사용하지 않아도 텍스트 레이블의 콘텐트 크기에 따라 셀의 크기가 자동으로 맞춰졌습니다. 왜 그럴까요? (1번 질문에서 여쭤봤던 내용에 포함되어 있는 `rowHeight`의 기본값이 `.automaticDimension`이기 때문일까요?)

3. `translatesAutoresizingMaskIntoConstraints`의 값을 `false`로 지정할 경우, 화면이 제대로 표시되지 않는 문제가 있었습니다. 위 프로퍼티를 `true`로 설정하면 스토리보드상에서 설정한 제약과 오토리사이징 마스크가 만든 제약이 충돌한다는 로그가 생기기 때문에 `false`로 바꿔보려고 했는데요, `false`로 바꾸면 테이블 뷰 셀의 제약이 ambiguous하다면서 화면이 아예 표시되지 않았습니다.
셀 내에 포함된 모든 뷰의 상/하/좌/우 제약 조건을 모두 지정한 상태여서 제약 조건이 충분하다고 생각했는데, 오래 고민해보아도 부족한 부분을 찾지 못해 해결하지 못했습니다. 혹시 해당 문제를 해결하기 위해 더 알아야 하는 부분이 있을지 여쭤보고 싶습니다!

2022-10-20 18:51 UTC, inwoodev requested changes
2번째 PR까지 너무 고생이 많으셨습니다! 
본격적인 리뷰작성 전에 일단 저도 부족한게 많은 개발자이기 때문에 제가 말하는게 정답이 아님을 명시하고자합니다! 혹시나 틀린 부분이 보이거나 이상한 부분이 있다면 얘기 해 주시면 저도 더 고민 해 볼게요!

일단 고민 했던 부분에 대해서 간단하게 얘기 해 보자면 제 생각에는 각 메서드의 네이밍 또한 명확하고 간결해서 일기가 수월 했습니다. 또한 역할 또한 관련성이 있는 것들끼리 묶은 측면에서 현시점에는 적절한거 같아요! 그리고 특히 네트워크 에러 또는 데이터 에러를 alert로 처리를 많이 하는 편입니다. 제 생각에는 이런 접근이 결국은 UX적인 측면을 더욱 고려한 방향이라고 생각합니다. 유저가 앱을 사용하면서 문제가 생기면 빠른 시일 내에 해당 부분에 대해서 피드백을 받을 수 있으니까요! 그렇기 때문에 에러처리에 있어서 alert를 적절히 사용하셨다고 저는 생각합니다.

앱에 대해서 조금 얘기하고자합니다. 테이블뷰의 cell이 스크롤 된 뒤 다시 위로 올리는 과정에서 매끄럽지 않은 부분이 존재하는것 같아요. 이 부분은 수정이 필요해 보입니다!

질문에 답변 또한 남겨보았어요~

> rowHeight 프로퍼티에 값을 지정해주지 않으면 rowHeight의 기본값이 automaticDimension으로 설정되어 있어 위 메서드를 구현해주지 않아도 자동으로 콘텐트의 intrinsic size에 맞는 높이를 제공하는 것으로 알고 있습니다. 실제로 위의 코드를 제거해도 화면이 정상적으로 표시되는 것을 확인할 수 있었습니다.
그런데 저희가 찾아보니 automaticDimension 값을 사용해 customCell의 높이를 동적으로 지정해주기 위해서는 '오토레이아웃의 제약이 완벽해야 한다' 는 내용이 있었던 것 같은데 이 말의 정확한 의미를 잘 모르겠습니다.

커스텀 cell을 구현한 뒤 automaticDimension값을 사용하여 높이를 동적으로 지정해주기 위해서는 해당 셀의 contentView에 들어있는 요소들의 top, bottom의 오토레이아웃이 명확해야만 동적으로 높이를 지정해줄 수 있다고 이해되는데요. 가령 각 셀에 다른 높이의 이미지가 하나씩 주어진다고 하면 해당 이미지 크기에 맞게 셀 높이를 지정하기 위해서는 이미지 사이즈와 해당 이미지와 상단의 contentView와의 간격, 해당 이미지와 contentView 하단의 간격과 같은 정보를 제공해야지 동적으로 해당 이미지에 맞게 셀의 사이즈를 자동으로 조정할 수 있다는 맥락으로 읽으신 글에서 설명하는게 아닌가 싶네요~

> 1번의 메서드를 구현하든, 구현하지 않든 현재 셀의 높이를 별도로 지정해주지 않았기 때문에 rowHeight가 automaticDimension으로 설정되어 셀의 높이를 자동으로 계산할 수 있다고 생각했는데, 위 코드에서 sizeToFit()을 주석 처리할 경우 셀 크기를 자동으로 계산하지 못하는 것 으로 보였습니다. 왜 그런지 궁금합니다.
.
.
.
> 이미지 뷰 1개, 레이블 1개, 텍스트 뷰 1개를 포함하는 커스텀 셀을 구현한 경우 아래 사진과 같이 모든 행이 일정하게 큰 높이로 표시되었습니다 (가장 긴 텍스트 뷰의 높이와 무관하게 더 길게).
> 현재는 기본으로 제공하는 subtitle 스타일의 셀을 사용하는 것으로 대체했습니다. 기본으로 제공하는 스타일의 셀을 사용하니 .automaticDimension, sizeToFit()을 사용하지 않아도 텍스트 레이블의 콘텐트 크기에 따라 셀의 크기가 자동으로 맞춰졌습니다. 왜 그럴까요? (1번 질문에서 여쭤봤던 내용에 포함되어 있는 rowHeight의 기본값이 .automaticDimension이기 때문일까요?)

 "위 코드에서 sizeToFit()을 주석 처리할 경우 셀 크기를 자동으로 계산하지 못하는 것 으로 보였습니다. 왜 그런지 궁금합니다."
이 부분은 기존에 커스텀셀에 어떤식으로 오토레이아웃을 주셨는지를 알지 못해서 저도 어떤게 문제인지 정확하게는 확인하기가 현재로서는 어렵네요ㅠ 음 label의 sizeToFit은 텍스트 길이에 맞게 label의 길이에 맞게 크기가 변경되는걸로 이해하고 있는데요 아마 이런 특징이 다른 제약사항과 맞물려서 말씀하신 문제가 생기지 않을까 조심스럽게 예상해봅니다. 이 부분은 일단 해당 스텝에서는 크게 고려할 부분이 아니니 다음 스텝에서 조금 더 고민 해 보시고 해결이 오랜시간동안 안된다면 같이 한 번 보면 좋겠습니다!

> translatesAutoresizingMaskIntoConstraints의 값을 false로 지정할 경우, 화면이 제대로 표시되지 않는 문제가 있었습니다. 위 프로퍼티를 true로 설정하면 스토리보드상에서 설정한 제약과 오토리사이징 마스크가 만든 제약이 충돌한다는 로그가 생기기 때문에 false로 바꿔보려고 했는데요, false로 바꾸면 테이블 뷰 셀의 제약이 ambiguous하다면서 화면이 아예 표시되지 않았습니다.
셀 내에 포함된 모든 뷰의 상/하/좌/우 제약 조건을 모두 지정한 상태여서 제약 조건이 충분하다고 생각했는데, 오래 고민해보아도 부족한 부분을 찾지 못해 해결하지 못했습니다. 혹시 해당 문제를 해결하기 위해 더 알아야 하는 부분이 있을지 여쭤보고 싶습니다!

음 제 생각에는 autoresizing mask와 intrinsicContentSize 정도를 조금 더 공부 해 보시면 좋을거 같아요!
일단 스토리보드에서 특정 뷰에 제약사항을 주는 순간 해당 뷰의 `translatesAutoresizingMaskIntoConstraint`는 자동으로 false로 설정이 되기 때문에 임의로 해당 설정을 true로 설정하게 된다면 conflict가 일어날 수 밖에 없습니다. 

몇 자 남겨보았습니다. 혹시나 추가적으로 설명이 필요한 부분이 있다면 dm주시면 답변 간간히 남겨볼게요. 그리고 위에 얘기했던 것 처럼 혹시나 조금 더 상세한 설명이 필요하다 싶으시면 시간 맞춰서 디코에서 잠깐 보는것도 괜찮습니다! 아직 머지하기에는 조금 이르다 판단되어서 추후 조금 더 고민 해 보고 머지하는게 좋다고 생각합니다!

2022-10-20 18:51 UTC, inwoodev commented on Expo1900/Expo1900/Controller/ItemListViewController.swift
> +    @IBOutlet weak var tableView: UITableView!
해당 멤버 변수는 internal로 선언되어있네요. 특별한 이유가 있을까요?

2022-10-20 18:51 UTC, inwoodev commented on Expo1900/Expo1900/Controller/ItemListViewController.swift
> +    let cellIdentifier: String = "itemCell"
해당 상수 또한 internal인 이유가 특별히 존재하는지 궁금합니다~

2022-10-20 18:51 UTC, inwoodev commented on Expo1900/Expo1900/Controller/ItemListViewController.swift
> +            showDataErrorAlert()
에러 메세지를 보여주는 것도 UX적인 측면에서 좋은 접근이라 생각합니다 👍

2022-10-20 18:51 UTC, inwoodev commented on Expo1900/Expo1900/Controller/ItemListViewController.swift
> +            print(error)
단순히 여기서 error를 프린트하면 디버깅할 때 이 부분이 문제인지 빠르게 파악할 수 있을까요? 지금은 프로젝트가 크지 않아서 문제가 되지 않을 수도 있지만 만약 수십개의 뷰컨트롤러가 존재한다면요?

2022-10-20 18:51 UTC, inwoodev commented on Expo1900/Expo1900/Controller/ItemListViewController.swift
> +        self.tableView.reloadData()
tableView를 이 시점에서 `reloadData()`하는 이유가 있을까요~?🤔 그리고 추가적으로 tableviewDataSource와 delegate의 lifecycle 또한 아시는지도 궁금합니다~~

2022-10-20 18:51 UTC, inwoodev commented on Expo1900/Expo1900/Extensions/UIViewController+.swift
> +}
네이밍만 관련해서는 특정화면으로 이동할 때 보여주는 alert라는 인상을 받았습니다~ 네이밍을 개선 해 볼 수 있을거 같은데 두 분은 어떻게 생각하시나요?

2022-10-20 18:51 UTC, inwoodev commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    @IBOutlet private weak var descriptionTextView: UITextView!
textView로 만국박람회의 설명을 보여주시는군요! 근데 앱 실행시 유저가 해당 텍스트뷰를 텝하게 되면 해당 텍스트를 수정할 수 있도록 키보드가 화면에 나오게 됩니다. 의도한게 아니라면 수정해 볼 수 있을까요?

2022-10-20 18:51 UTC, inwoodev commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +              let visitorsText = numberFormatter.string(from: Double(exposition.visitors) as NSNumber) else { return }
numberFormatter를 적절하게 사용하셨네요 👍 👍

2022-10-20 18:51 UTC, inwoodev commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        nextViewController.title = "한국의 출품작"
nextViewController의 프로퍼티를 여기서 할당해야 하는 이유가 특별히 있을까요~?

2022-10-20 18:51 UTC, inwoodev commented on Expo1900/Expo1900/Model/Exposition.swift
> +struct Exposition: Decodable {
현재로서는 Decodable이 더 적절해 보이네요 👍 👍 👍

2022-10-20 18:51 UTC, inwoodev commented on Expo1900/Expo1900/Controller/ItemListViewController.swift
> +        nextViewController.title = item.name
nextViewController의 title을 여기서 지정 해 주는 이유가 특별히 있을까요?

2022-10-26 05:06 UTC, ttokin commented on Expo1900/Expo1900/Controller/ItemListViewController.swift
> +    @IBOutlet weak var tableView: UITableView!
접근제어 설정하는 것을 놓친 휴먼 에러인 것 같습니다.. 😅 `private` 처리해주었습니다!

2022-10-26 05:06 UTC, ttokin commented on Expo1900/Expo1900/Controller/ItemListViewController.swift
> +    let cellIdentifier: String = "itemCell"
위의 변수와 더불어 접근제어 설정해주는 것을 단순히 놓친 것 같습니다.😅 `private` 처리해주었습니다!

2022-10-26 05:06 UTC, ttokin commented on Expo1900/Expo1900/Controller/ItemListViewController.swift
> +            print(error)
- 에러가 발생한 지점(파일, 줄 번호, 함수명)을 출력해주는 `printErrorLog` 함수를 `UIViewController`의 익스텐션에 구현해서 어느 지점에서 에러가 발생했는지 명확하게 보여주도록 수정했습니다.

2022-10-26 05:06 UTC, ash-youu commented on Expo1900/Expo1900/Controller/ItemListViewController.swift
> +        nextViewController.title = item.name
- 화면을 전환할 때, 전환될 화면을 미리 준비하는 코드라고 생각하다보니 해당 부분에서 title을 할당을 했었습니다. 하지만, 해당되는 뷰의 VC에서 설정하는 것이 어떤 뷰의 title인지 의도를 명확히 할 수 있다고 생각하여 각 뷰의 `viewDidLoad()` 메서드에서 할당하는 것으로 수정하였습니다. 😄

2022-10-26 05:07 UTC, ash-youu commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    @IBOutlet private weak var descriptionTextView: UITextView!
스토리보드 파일에서 텍스트뷰의 `editable`을 체크 해제하여 유저가 텍스트를 수정할 수 없도록 설정하였습니다.

2022-10-26 05:07 UTC, ttokin commented on Expo1900/Expo1900/Controller/ItemListViewController.swift
> +        self.tableView.reloadData()
- `reloadData()`는 화면에 보여지는 행과 그 주변 몇개 행에 대해서만 셀, 섹션 헤더, 푸터, 인덱스 배열 등 테이블 구성에 사용되는 모든 데이터를 다시 로드해오는 메서드인데 용법을 혼동해서 해당 시점에서 호출하게 된 것 같습니다! `reloadData()`를 호출하지 않는 것으로 수정했습니다.
- `reloadData()`를 호출하면, 이 메서드가 행의 개수, 섹션의 개수, cellForRowAt 등을 결정하는 메서드를 모두 호출해서 화면에 현재 보이는 모든 셀을 reload하게 됩니다 (셀을 다시 그린다고 볼 수 있음). 그렇기 때문에, 데이터 소스와 관련된 변화(이 프로젝트의 경우 테이블 뷰의 데이터와 관계된 배열 - `[Items]`에 요소를 추가/삭제 등)가 있을 때 `reloadData()`를 하는 것 같습니다. [출처](https://www.quora.com/When-should-we-call-tableView-reloadData)
- 추가로 야곰 부스트코스 강의에서 `add 버튼`을 누르면 행이 추가될 때 `reloadData()`를 호출하는 것으로 확인했었는데요. 이렇게 동적으로 데이터가 추가될 때 reload 관련 메서드를 호출하는 것이라고 이해하면 될까요?

2022-10-26 05:08 UTC, ttokin commented on Expo1900/Expo1900/Controller/ItemListViewController.swift
> +        self.tableView.reloadData()
tableViewDataSource와 tableViewDelegate의 메서드 호출 순서(시점)
- `ItemListVC` 화면으로 이동
  1. tableViewDataSource - `tableView(_: numberOfSections: )` 메서드 호출
  2. tableViewDataSource - `tableView(:numberOfRowsInSection:)` 메서드 호출
  3. tableViewDataSource - `dequeueReusableCell(withIdentifier:for:)` 메서드 호출
- 위아래로 스크롤
  1. tableViewDataSource - `dequeueReusableCell(withIdentifier:for:)` 메서드 호출
- 특정 행 선택(탭) 시
  1. tableViewDelegate - `tableView(_: didSelectRowAt: )` 메서드 호출

2022-10-26 05:08 UTC, ttokin commented on Expo1900/Expo1900/Extensions/UIViewController+.swift
> +}
화면 전환 시 에러가 발생했을 때 라는 의미를 담아 `showTransitionErrorAlert()`로 수정해 주었습니다.

2022-10-27 03:25 UTC, inwoodev commented on Expo1900/Expo1900/Extensions/UIViewController+.swift
> +    }
오 에러로그 구현까지!! 이제 디버깅하기 많이 수월하겠네요!! 추가적으로 음 검색해 보시면 print외에 다른 방법으로도 디버그로그를 출력하는 방법이 있다고 알고 있는데요. 한 번 찾아보시는 것도 추천드립니다~~

2022-10-27 03:25 UTC, inwoodev commented on Expo1900/Expo1900/Controller/ItemListViewController.swift
> +        nextViewController.title = item.name
네 말씀하신 방법이 조금 더 객체지향적인 접근이겠네요~~ :)

2022-10-27 03:29 UTC, inwoodev commented on Expo1900/Expo1900/Controller/ItemListViewController.swift
> +        self.tableView.reloadData()
"add 버튼을 누르면 행이 추가될 때 reloadData()를 호출하는 것으로 확인했었는데요. 이렇게 동적으로 데이터가 추가될 때 reload 관련 메서드를 호출하는 것이라고 이해하면 될까요?" - 네 저도 그렇게 이해하고 있습니다~ 호출 순서를 말한다는 것을 lifecycle이라 적어서 혼란을 야기한거 같네요. 죄송합니다 ㅠ. 그럼에도 너무 깔끔하고 직관적이게 설명하셔서 두 분이 해당 부분에 대해서 잘 이해하신거 같아서 고무적입니다 👍👍👍

2022-10-27 03:31 UTC, inwoodev commented on Expo1900/Expo1900/Controller/ItemListViewController.swift
> +            print(error)
인터넷 서칭을 하다가 얼핏 본거 같은데요~ print문이 많아지면 많아질 수록 속도저하를 야기할 수도 있다고 하네요~~ 나중에 이런 부분에 있어서도 성능 최적화를 해 보셔도 좋을거 같습니다~

2022-10-27 03:34 UTC, merged