만국박람회 [Step 2] som, Stone, Aaron
yagom-academy/ios-exposition-universelle pull request #215
Opened 2022-10-21 05:11 UTC by jsa0224

안녕하세요, 토니(@Monsteel)🙇‍🙇‍🙇‍♀️!
[Som](https://github.com/jsa0224), [Stone](https://github.com/lws2269), [Aaron](https://github.com/Hashswim)입니다!
저희 Step 2 구현 완료하여 PR 보냅니다! 

# 📍구현한 부분
- `ExhibitionWork`
  - CodingKey라는 프로토콜을 채택하여 구현했습니다. 간혹 JSON의 데이터 네이밍이 스위프트에서 지양하는 네이밍일 경우, 사용자 지정으로 네이밍을 변경하여 사용할 수 있게 해줍니다. 
(ex. image_name → imageName)
- `ExpositionPoster`
  - Codable 프로토콜을 채택하여, 인코딩과 디코딩이 가능한 타입으로 구현하였습니다.
- `Int Extension`
    - formatNumber 연산 프로퍼티를 사용하여, Int형의 값을 "," 구분자를 포함한 String 값으로 반환하도록 구현하였습니다.
- `ExhibitionMainViewController`
  - exposition_universelle_1900의 Json 데이터를 통해 파리 만국박람회 1900 메인 포스터 뷰를 구현했습니다. 
  - titleLabel의 텍스트 값을 replacingOccurrences 라는 내장함수를 이용해 "(" -> "\n("로 치환하여 줄바꿈 되도록 구현하였습니다.
- `ExhibitionWorkListViewController`
  - 테이블 뷰를 통해 파리 만국박람회의 한국 출품작들을 한 눈에 보여지게끔 구현했습니다. 
- `DetailWorkViewController`
  - 테이블 뷰가 선택되었을 때 해당 테이블에 대한 상세 내용을 보여주게끔 구현했습니다. 

# 📍고민되었던 부분

- `UITableViewCell`
현재 UITableViewCell은 스토리보드 상 Subtitle로 구성이 되어 있습니다. 하지만 예시 화면과 조금 다르게 나오더라고요. 

    |예시 화면|구현한 화면|
    |:---:|:---:|
    |<img src="https://i.imgur.com/M97gnD7.png" width="200px">|<img src="https://i.imgur.com/5w491aM.png" width="200px">|

    그래서 커스텀 셀로 구현할까 고민했지만, Step 3에서 테이블 뷰의 오토레이아웃 문제를 해결하는 걸로 알고 있어, 일단은 보류해두었습니다 ㅎㅎ

- `NSMutableAttributedString`
    해당 Attribute를 통해 하나의 레이블로 글자 크기를 조정해 예시 화면과 똑같이 구현하려고 했지만, 아직 `NSMutableAttributedString`에 대한 이해가 부족한 거 같아 충분히 공부 후, Step 3에서 구현할 예정입니다. 

- `prepare`메서드의 위치
    ```swift
    class ExhibitionWorkListViewController: UIViewController {
        ...
    }

    extension ExhibitionWorkListViewController: UITableViewDataSource {
        ...

        override func prepare(for segue: UIStoryboardSegue, sender: Any?)     {
            guard let detailViewController: DetailWorkViewContorller = segue.destination as? DetailWorkViewContorller else {
                return
            }
            guard let indexPath = self.exhibitionWorkTableView.indexPathForSelectedRow else {
                return
            }
            detailViewController.exhibitionWork = self.exhibitionWork[indexPath.row]
        }
    }
    ```
    `prepare` 메서드는 `tableView`의 cell의 데이터 전환전에 실행하면서 데이터를 전달하는 메서드로 `UITableViewDataSource`채택하며 `ExhibitionWorkListViewController`의 확장에 구현을 할지 아니면 위쪽에 정의를 할지 고민이 되었습니다.

    하지만 `UITableViewDataSource`의 확장과는 관련이 없어보여 원래의 class정의한 곳에 구현하였습니다.

2022-10-24 09:21 UTC, Monsteel requested changes
som, Stone, Aaron 안녕하세요 :) 이번 스텝도 수고많으셨습니다.
따로 남겨주신 질문이나 다른 부분이 없어서 이번에는 코드에 대한 리뷰만 남겨봤어요 :)
확인부탁드립니다! 🙇🏻‍♂️🙇🏻‍♂️

2022-10-24 09:21 UTC, Monsteel commented on Expo1900/Expo1900/Model/Int+Extension.swift
> +            return "Error in Formatter"
이런 경우, 오류를 return 해주기보다, throw개념을 사용해볼 수 있을것 같아요 🙌

2022-10-24 09:21 UTC, Monsteel commented on Expo1900/Expo1900/Controller/ExhibitionWorkListViewController.swift
> +        guard let indexPath = exhibitionWorkTableView.indexPathForSelectedRow else {
guard 문을 하나로 합칠 수 있는 방법도 있습니다 :)

2022-10-24 09:21 UTC, Monsteel commented on Expo1900/Expo1900/Controller/ExhibitionMainViewController.swift
> +            expositionPoster = try jsonDecoder.decode(ExpositionPoster.self, from: dataAsset.data)
try catch 를 통해 안전하게 처리해 주셨네요! 아주 좋습니다! 👍

2022-10-24 09:21 UTC, Monsteel commented on Expo1900/Expo1900/Controller/DetailWorkViewController.swift
> +        title = exhibitionWork?.name ?? ""
요렇게 optional unwrapping이 되면, nil일 경우 아무런 표시 없이 값이 ""(빈 값)으로 뜨게 됩니다. 🧐
optional 상황을 report(print) 받을 수 있도록 처리하면 debug에 용이할 것 같아요 ✨

2022-10-25 12:31 UTC, lws2269 commented on Expo1900/Expo1900/Controller/ExhibitionWorkListViewController.swift
> +        guard let indexPath = exhibitionWorkTableView.indexPathForSelectedRow else {
감사합니다! 한 조건에 처리하도록 리팩토링했습니다!

2022-10-25 12:32 UTC, jsa0224 commented on Expo1900/Expo1900/Model/Int+Extension.swift
> +            return "Error in Formatter"
`IntError` 타입을 생성하고, 해당 `guard` 문에서 `throw`한 에러를 `do-catch`문을 통해 구현하였습니다!

2022-10-26 12:22 UTC, Monsteel approved these changes
꼼꼼하게 확인해주셔서 감사합니다 :) 🙌
이번 스텝도 수고많으셨습니다! 다음 스텝 이어서 진행 부탁드려요!

2022-10-26 12:22 UTC, merged