만국박람회 [STEP 2] Gundy, Dragon
yagom-academy/ios-exposition-universelle pull request #218
Opened 2022-10-21 07:18 UTC by FlameYG

@junbangg 
앨러뒨~ STEP 2도 완료하여 PR 보냅니다!
STEP 1이 별 게 없었던 만큼 신랄하게 코멘트 주시길 기대합니다!

### 조언을 얻고 싶은 부분

- 재사용 셀 자동 리사이징
    - 두 번째 화면, ExhibitionListViewControlle의 화면에서 최초의 테이블뷰 셀들은 사이즈가 프로토타입 셀의 사이즈와 같고, prepareForReuse 등을 설정하지 않았음에도 재사용 셀이 되면서 컨텐츠가 다 보이게 리사이징이 되고 있습니다. 해당 현상은 다음 화면으로 넘어가서 disappear가 되더라도 변함없이 리사이징이 된 상태로 유지되어 있으며, 메인 화면으로 돌아가서 해당 뷰를 메모리에서 해제하기 전까지 유지됩니다. 다시 두 번째 화면으로 들어가면 똑같은 현상이 또 발생합니다. 왜 이런 것인지 전혀 감을 잡을 수 없고, 이를 해결하기 위해 UITableViewAutomaticDimension도 사용해봤는데 변화가 없었습니다. reloadData의 위치를 jsonDecoder.decode 메서드 호출부보다 뒤로 옮겨도 마찬가지입니다...해당 현상을 저희로서는 문제의 원인을 파악할 수 없었습니다. 알라딘께서 저희의 프로젝트를 살펴보시고 원인을 파악하신다면 해당 현상의 원인과 앞으로 같은 문제가 발생하지 않게 하기위한 조언을 해주실 수 있을까요?
- 커스텀 컴포넌트의 파일 위치
    - 테이블뷰 셀을 커스텀하기 위해, `ExhibitionListTableViewCell`파일을 추가한 후 파일&폴더 정리를 하면서 어느 폴더에 넣을지 고민은 해봤으나 명확하게 판단되지 않아 조언 부탁드립니다!
- 한 번 사용되는 매직 리터럴에 대해서 namespace를 설정하는 것이 좋은지?
    - `InformationViewController`파일에 작성된 코드 중 `"exposition_universelle_1900"`,`"메인"`와 같이 매직리터럴 사용하는 방식에서 휴먼에러 방지를 위해 enum을 사용하여 namespace 설정을 해야하나 고민해봤으나, 재사용되는 것이 아니기에 STEP2는 매직리터럴을 사용하였습니다... 혹시, 이럴 경우에도 namespace를 설정해주는 것이 좋은 방법인지 조언 부탁드립니다!
- JSONDecoder가 2번 사용되는데, 이를 타입 메서드나 타입 인스턴스로 만들어서 사용하는 것이 좋은지?
- TableViewDelegate 미사용 익스텐션
    - ExhibitionListViewControlle의 TableView에 관련한 프로토콜 채택을 extension으로 분리하여 사용하고 있습니다. 현재는 delegate 관련한 메서드 등을 사용하지 않고 있는데, 이럴 경우 `self.tableView.delegate = self` 코드가 실질적으로는 아무런 일도 하지 않는 코드가 됩니다. 앞으로 delegate 기능을 사용할 지도 모르겠으나 현재는 사용되지 않을 때, UITableViewDelegate 채택부분을 작성하지 않는 것이 적절할까요?

### 고민했던 부분

- 테이블뷰 셀
    - 두 번째 화면(출품작 리스트 테이블뷰)에서 사용할 프로토타입 셀에서 필요한 것은 좌측의 이미지, 타이틀, 간단한 설명의 두 레이블이라고 생각했습니다. 이는 subtitle 스타일의 셀과 유사하다고 생각해 처음에는 기본 셀의 subtitle을 사용하였습니다. 그런데 액세서리뷰를 설정하는 순간부터 스크롤이 튀는 버그가 있고, 일정한 이미지 사이즈를 맞추는 것이 적절한 것 같아 커스텀 셀을 사용하는 것으로 변경하였습니다.
- 매직리터럴 vs 네임스페이스
    - 매직리터럴이 재사용되지 않는 경우에도 namespace를 설정해줘야하는지 고민해봤습니다.
    - 상세 내용은 **조언을 얻고 싶은 부분**에 내용 기입했습니다! 확인 부탁드립니다~!
- 크기가 다른 문자열
    - 첫 화면의 방문객 수, 개최지, 개최기간 등은 콜론(:)을 기준으로 왼쪽과 오른쪽의 폰트 사이즈가 다릅니다. 해당 사항을 가장 쉽게 구현하는 것은 StackView에 Label을 두 개 넣는 것이라고 생각했는데, attributedLabel을 사용하면 단일 레이블로도 같은 결과를 낼 수 있었습니다. 더 직관적이고 간단한 방법으로 작업하기 위해 attributedLabel을 사용하기로 결정하였습니다.

2022-10-24 13:23 UTC, junbangg requested changes

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +    private let cellIdentifier: String = "cell"
이 identifier 는 셀의 것인데 셀이 갖고있도록 할 수 있는 방법은 어떨까요??🤔

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +    @IBOutlet weak var tableView: UITableView!
요 친구는 private 이 안되는 이유가 있었을까요???

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +        self.tableView.reloadData()
요 친구들은 전부 tableview 관련 메서들 같은데 메서드로 분리해볼 수 있을것 같습니당

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +        self.tableView.reloadData()
오 여기서 reload 하는 이유가 있나요???

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +        guard let text = cell.nameLabel.text else {
흠 셀의 레이블의 내용을 이렇게 빼는거 말고 다른 방법은 호옥시 없으려나요🤔

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +        return self.itemsOfExposition.count
요기 self 쓰신 이유가 있을까요?!(틀렸다는건 아닙니당)

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +    private func configureCells(_ item : Exhibition, cell: ExhibitionListTableViewCell) {
요 메서드가 이 extension 에 들어있는 특별한 이유가 있을까요~?

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/ExhibitionViewController.swift
> +    @IBOutlet weak var exhibitionDescriptionLabel: UILabel!
private~?!

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/ExhibitionViewController.swift
> +        self.exhibitionDescriptionLabel.text = exhibition.description
요 친구들을 각각 메서드로 빼주는것에 대해서는 어떻게 생각하시나요?(꼭 하실 필요는 없고 의견을 묻는것입니당)

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/InformationViewController.swift
> +    @IBOutlet weak var descriptionOfExposition: UILabel!
Private~?🙃

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/InformationViewController.swift
> +        }
viewdidload 에는 나중에 다른 것들이 들어가고 빠지고 할 확률이 아주 농후할텐데 요부분 메서드로 빼뻐리는건 어떠십니까

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/InformationViewController.swift
> +        self.navigationItem.backButtonTitle = "메인"
메서드 따로 제공해주는것에 대한 의견이 궁금합니다~ 위에서 같은 이야기 댓글로 남겨드리긴 해서 한번에 답변 주셔도 됩니당

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/InformationViewController.swift
> +    private func configureLables() {
오타가 있습니당

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/InformationViewController.swift
> +    private func attributedString(of text: String?) -> NSMutableAttributedString? {
👍

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Model/ExhibitionListTableViewCell.swift
> +    @IBOutlet weak var exhibitionImageView: UIImageView!
프라이빗:)

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Model/Exposition.swift
> +    private let titleOfJsonData: String
흠 중간에 json 은 저는 다 대문자로 하는
편이긴 한데 두분은 어떻게 생각하시나요??(정답 절대절대 아니고 저도 궁금해서요 ~~)

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +        }
흠 이부분은 메서드로 따로 분리하는것에 대해서 고민 해보셨을까요???

2022-10-24 13:23 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +    private func configureCells(_ item : Exhibition, cell: ExhibitionListTableViewCell) {
셀 하나씩 configure 하는거니까 s가 빠지는게 낫지않으려나요?!

2022-10-24 13:58 UTC, Gundy93 commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +    private let cellIdentifier: String = "cell"
커스텀 셀을 만든 만큼 프로퍼티로 해결할 수 있을 것 같습니다

2022-10-24 14:02 UTC, Gundy93 commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +    @IBOutlet weak var tableView: UITableView!
놓친 부분인 것 같습니다!

2022-10-24 14:07 UTC, Gundy93 commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +        guard let text = cell.nameLabel.text else {
해당 사항은 드래곤과 더 고민해보겠습니다!

2022-10-24 14:20 UTC, Gundy93 commented on Expo1900/Expo1900/Sources/Controller/InformationViewController.swift
> +        }
기능적으로도 분리하는 것이 맞지않나 싶습니다

2022-10-24 14:35 UTC, Gundy93 commented on Expo1900/Expo1900/Sources/Model/Exposition.swift
> +    private let titleOfJsonData: String
타입도 다 대문자로 되어있어서 첫번째 단어인 경우에는 소문자, 중간이후로는 대문자가 어떨까 싶긴합니다

2022-10-24 16:00 UTC, junbangg commented
```
재사용 셀 자동 리사이징
```
지금 봤을때 오토레이아웃의 문제일 가능성이 높아보여요!
요건 디코로 같이 이야기를 해보시져
```
커스텀 컴포넌트의 파일 위치
```
`ExhibitionListTableViewCell` 이라면 뷰에 해당되지 않을까요?! 어떻게 생각하시나용
```
한 번 사용되는 매직 리터럴에 대해서 namespace를 설정하는 것이 좋은지?
```
흠 네임스페이스의 역할에 대해서 어떻게 생각하시는지 궁금합니다🤔
물론 재사용성의 측면으로만 보면 한번만 사용되니까 필요가 없을 수도 있겠네요:)
그렇지만 네임스페이스 자체가 더이상 필요하지 않을지는...! 모르는거죠ㅎㅎ
그래서 네임스페이스라는게 재사용성의 측면으로 기능을 해주기도 하지만~한곳에서 관리할 수 있다는 이점도 있을것 같아요!
추가를 해야될때 그냥 거기에 추가하면 되니까??
이건 근데 저의 개인적인 생각이고 스타일일 뿐입니다 정답이 있지는 않아요!
```
JSONDecoder가 2번 사용되는데, 이를 타입 메서드나 타입 인스턴스로 만들어서 사용하는 것이 좋은지?
```
재활용하기 위한 방법을 고민하고 계시군요??
말씀하신것 처럼 Decoding 을 책임져주는 타입을 만드는 방법도 좋은것 같아요!!
```
TableViewDelegate 미사용 익스텐션
ExhibitionListViewControlle의 TableView에 관련한 프로토콜 채택을 extension으로 분리하여 사용하고 있습니다. 현재는 delegate 관련한 메서드 등을 사용하지 않고 있는데, 이럴 경우 self.tableView.delegate = self 코드가 실질적으로는 아무런 일도 하지 않는 코드가 됩니다. 앞으로 delegate 기능을 사용할 지도 모르겠으나 현재는 사용되지 않을 때, UITableViewDelegate 채택부분을 작성하지 않는 것이 적절할까요?
```
사용이 안되고 있고 지금 상태에서는 필요가 없다면 그냥 제거 해주셔도 될것 같습니다 개인적으로🤔
필요해지면 다시 붙이면 되니까요~!

2022-10-25 04:12 UTC, FlameYG commented on Expo1900/Expo1900/Sources/Model/Exposition.swift
> +    private let titleOfJsonData: String
아직 주관이 없습니다... 혹시, 현업에서는 JSON으로 네이밍하나요?? (맞춰가겠습니다!)

2022-10-25 06:11 UTC, FlameYG commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +        self.tableView.reloadData()
메서드로 분리했습니다~!

2022-10-25 06:11 UTC, FlameYG commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +        self.tableView.reloadData()
구현 단계에서 문제발생한 것들 테스트용도로 작성한 코드였는데 삭제를 못한 부분입니다... 삭제했습니다! 😀

2022-10-25 06:13 UTC, FlameYG commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +        guard let text = cell.nameLabel.text else {
커스텀셀에서 바로 값을 가져오는 것으로 변경하엿습니다~!

2022-10-25 06:13 UTC, FlameYG commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +        return self.itemsOfExposition.count
아니요... 혹시 몰라서 썼던 부분인데 self 가 없어도 되는 부분은 모두 삭제했습니다! 집어주셔서 감사합니다~!

2022-10-25 06:15 UTC, FlameYG commented on Expo1900/Expo1900/Sources/Controller/InformationViewController.swift
> +    private func configureLables() {
수정하였습니다~!

2022-10-25 06:15 UTC, FlameYG commented on Expo1900/Expo1900/Sources/Controller/InformationViewController.swift
> +        self.navigationItem.backButtonTitle = "메인"
메서드로 분리하는게 적절하다고 판단되어 메서드 생성하여 분리해주었습니다~!

2022-10-25 06:16 UTC, FlameYG commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +        }
넵! JSONDecode에 extension으로 기능 추가하여 여러 ViewController에서 사용가능하도록 변경하였습니다

2022-10-25 06:17 UTC, FlameYG commented on Expo1900/Expo1900/Sources/Controller/ExhibitionViewController.swift
> +        self.exhibitionDescriptionLabel.text = exhibition.description
각각 메서드로 만들면 크기가 작은 메서드가 3개라 메서드 하나에 모두 넣어서 분리했습니다...!

2022-10-25 06:24 UTC, FlameYG commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +    private func configureCells(_ item : Exhibition, cell: ExhibitionListTableViewCell) {
코드 작성할 때, 데이터 처리관련된 메서드라고 생각되어서 extension에 넣었습니다~
그런데 지금 다시 봐보니 `ExhibitionListViewController`안에 있는게 맞다고 판단되어 위치 변경하였습니다!

2022-10-25 13:33 UTC, junbangg commented on Expo1900/Expo1900/Sources/Model/Exposition.swift
> +    private let titleOfJsonData: String
정해진 컨벤션은 없고 이것도 사람마다 다른것 같아요~! 정하기 나름이라고 생각합니다:)

2022-10-25 13:36 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +        self.itemsOfExposition = itemsOfExposition
여기도 `self` 가 있군요!
`self` 를 사용하면 안된다~! 는 절대 아닙니다! 사용하는 근거도 충분히 만들어 볼 수 있다고 생각합니다:)
다만 통일하는건 좋을것 같아요~!

2022-10-25 13:49 UTC, junbangg approved these changes

2022-10-25 13:49 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +        self.itemsOfExposition = itemsOfExposition
여기도 `self` 가 있군요!
`self` 를 사용하면 안된다~! 는 절대 아닙니다! 사용하는 근거도 충분히 만들어 볼 수 있다고 생각합니다:)
다만 통일하는건 좋을것 같아요~!

2022-10-25 13:49 UTC, junbangg commented on Expo1900/Expo1900/Sources/Model/Constant.swift
> +    static let cellIdentifier: String = "cell"
아하 이런식으로 두셨군요..흠 
근데 애초에 `TableViewCell` 한테 자기 `identifier` 를 갖게 한 이유를 생각해보면 이렇게 다시 `Namespace` 에 두는게 의미 있을까 싶네요!

셀의 종류가 정말정말 많아지는 상황을 생각해보면 이렇게 한곳에 두는것 보다 각각의 Cell 이 갖고 있게 하는게 좋지않을까 싶습니다~

2022-10-25 13:50 UTC, merged

2022-10-25 13:53 UTC, Gundy93 commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +        self.itemsOfExposition = itemsOfExposition
self가 없으면 컴파일러가 정확히 이해할 수 없는 부분을 제외하곤 모두 없애는 것으로 통일하였습니다!

2022-10-25 13:55 UTC, Gundy93 commented on Expo1900/Expo1900/Sources/Model/Constant.swift
> +    static let cellIdentifier: String = "cell"
아 여러 셀이 들어갈 경우를 경험해보지 못해서 static으로 진행한 것 같습니다 처음에는 옵셔널 저장 프로퍼티를 부여해야하나 생각했는데 여러 셀이 사용되지 않는 프로젝트인 것 같아 고민이었습니다.

2022-10-25 23:57 UTC, junbangg commented on Expo1900/Expo1900/Sources/Model/Constant.swift
> +    static let cellIdentifier: String = "cell"
앗 그냥 지금 요 문자열을 Cell 의 스태틱 프로퍼티로만 두는건 어떨까요?!

2022-10-25 23:58 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/ExhibitionListViewController.swift
> +        self.itemsOfExposition = itemsOfExposition
아 둘다 itemsOfExposition 이었네요 ㅎㅎ