만국박람회 [STEP 2] Ayaan, Bella
yagom-academy/ios-exposition-universelle pull request #221
Opened 2022-10-21 09:25 UTC by oneStar92

안녕하세요! 올라프 ☃️ @1Consumption
만국박람회 Step 2도 잘 부탁드립니다!!
AutoLayout은 Step 3 구현 사항이라서 아직 구현이 안되어있습니다...
어지러워도 너그럽게 봐주시면 감사하겠습니다!! 🙌🏼

## [고민했던 점]
#### DTO Type의 프로퍼티 접근 제어자
- DTO의 프로퍼티의 접근 제어자를 `private(set)`과 `let` 두가지 중에서 무엇을 사용해야 할지 고민했습니다.
- `private(set)`의 경우 내부에서는 변경이 가능하나 `let`의 경우 이니셜라이징 이후 내/외부에서 변경이 불가능하기 때문에 DTO Type의 프로퍼티 접근 제어자는 `let`으로 선언하는 것이 더 올바르다고 생각해 `let`을 사용하였습니다.

#### Main 화면 구성시, TextView 사용 vs label 사용
- 첫번째 화면인 Main 화면에서, ExpositionUniverselle DTO의 장문의 text인 description을 구현하기 위한 UI 구성요소를 구성함에 있어서 `TextView`와 `Label` 사용에 대해서 고민했습니다.
 `Apple HIG` 의 각 문서와 [Displaying Text Content in iOS](https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/UsingTextClasses/UsingTextClasses.html)를 참고하였습니다. 크게 `label`은 소량의 text를 보여주며 편집할 수 없는 점과, `TextView` 는 다량의 text를 보여주며 편집와 선택이 가능하다는 점이 있었습니다. 
저희는 다량의 text를 보여주는 것을 우선순위로 생각하여 `TextView` 를 선택하였으며 편집기능은 선택을 해제하였습니다. 

#### Segue를 통한 화면 전환시 데이터 전송.
- Segue를 이용하여 스토리보드에서 한국의 출품작을 보여주는 TableView의 Cell을 클릭하면, 클릭된 Cell의 해당하는 출품작의 상세 정보를 보여주는 View로 화면전환이 되게 구현하였습니다. `prepare()`메서드를 오버라이드하여 데이터를 전송할때, `sender`로 전달되는 상세 정보를 나타내는 데이터가 cell에는 없기 때문에 상세 정보를 보여주는 View에 올바른 데이터를 전송하지 못하는 문제가 발생하였습니다.
- TableView Delegate의 메서드인 `tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath)`를 사용해 상세 정보를 보고싶은 Cell을 선택하면 선택된 셀의 row에 해당하는 Item을 `performSegue`메서드의 `sender`로 전달해 주어서 해당 문제를 해결하였습니다.
```swift
func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    self.performSegue(withIdentifier: "ShowItemDetail", sender: expositionItems[indexPath.row])
}

override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    guard let nextViewController: ExpositionItemDetailViewController = segue.destination as? ExpositionItemDetailViewController,
          let item: ExpositionUniverselleItem = sender as? ExpositionUniverselleItem else {
        return
    }
    
    nextViewController.item = item
}
```
#### 메인페이지 이동버튼
|Before|After|
|:---:|:---:|
|<img src="https://i.imgur.com/op4N0rw.gif" width="200" height="400"/>|<img src="https://i.imgur.com/wHQ3Eqn.gif" width="200" height="400"/>|

```swift
showKoreanItemListButton.titleLabel?.text = "한국의 출품작 보러가기"
``` 
- MainVC 내부에서 다음 화면으로 이동하기 위해 해당 코드를 이용해 원하는 text를 구현을 하였으나, 버튼을 클릭하면 버튼을 클릭한 후와 화면 이동 후 다시 Main 화면으로 되돌아왔을 때 지정한 text가 아닌 버튼이 가지고 있는 원래의 text인 "Button" 이 보여지는 문제가 있었습니다.

```swift
showKoreanItemListButton.setTitle("한국의 출품작 보러가기", for: .normal)
```
- Button의 State가 `.nomal`일때의 Title이 "Button"이여서 발생하는 것으로 파악했으며, Button의 `titleLabel`의 `text`를 직접 바꾸는 방식이 아닌 `setTitle(_,for:)`메서드를 사용하여 버튼의 State에 따른 Title을 지정해줘서 해결하였습니다.

## [조언이 필요한 점]

#### VC의 상태 변화에 따른 버튼 Title의 변화
- 저희가 [고민했던 점]에 기재했던 고민들 중에, 마지막 고민인 '메인페이지 이동버튼'을 살펴봐주시면, `showKoreanItemListButton.titleLabel?.text = "한국의 출품작 보러가기"`로 Title을 설정해도 처음 화면을 실행했을 때에는 Title이 "한국의 출품작 보러가기"로 변경되어 있는 것을 볼 수 있었습니다. 
 하지만 DisAppear후에는 nomal State Title인 "button"으로 변경되었습니다. ViewDidLoad시에 Appear의 동작과 DisAppear후에 Appear의 동작이 서로 다른지에 대한 올라프의 생각이 궁금합니다...!

2022-10-23 10:33 UTC, 1Consumption requested changes
안녕하세요 @oneStar92 @hyhy0429 고생하셨습니다.

특별한 코멘트는 없습니다. 

고민한점에 대해 드릴 코멘트는 아래를 참고해주세요.

UIButton의 titleLabel 설명란에 보면 아래와 같은 내용이 있어요. 대충 요약하자면 titleLabel에 직접 접근해서 뭘 하지 말고 setTitle 메소드를 사용하라는 내용입니다.

> Do not use the label object to set the text color or the shadow color. Instead, use the [setTitleColor(_:for:)](doc://com.apple.documentation/documentation/uikit/uibutton/1623993-settitlecolor?language=swift) and [setTitleShadowColor(_:for:)](doc://com.apple.documentation/documentation/uikit/uibutton/1623994-settitleshadowcolor?language=swift) methods of this class to make those changes. To set the actual text of the label, use [setTitle(_:for:)](doc://com.apple.documentation/documentation/uikit/uibutton/1624018-settitle?language=swift) (button.titleLabel.text does not let you set the text).
The titleLabel property returns a value even if the button has not been displayed yet. The value of the property is nil for system buttons.

2022-10-23 10:33 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemDetailViewController.swift
> +}
extension으로 뺀 이유가 있나요?

2022-10-23 10:33 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemDetailViewController.swift
> +    @IBOutlet private weak var itemDescriptionTextView: UITextView!
textView를 사용한 이유가 있나요? scrollView에 label을 넣어도 될텐데요.

2022-10-23 10:33 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemDetailViewController.swift
> +class ExpositionItemDetailViewController: UIViewController {
이 뷰컨트롤러는 다른 뷰컨에 상속되나요? 그렇지 않다면 final 키워드를 붙여주세요.

2022-10-23 10:33 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemsViewController.swift
> +    }
이런 동작은 View에서 할 일이 아니라고 생각합니다. Model을 관리하는 객체를 만들어서 View에서는 사용만 하면 어떨까요?

2022-10-23 10:33 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemsViewController.swift
> +        cell.accessoryType = .disclosureIndicator
Cell 내부에 configure 해주는 메소드가 있으면 좋겠습니다.

2022-10-23 10:33 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemsViewController.swift
> +    }
override 메소드인데 super를 호출해주지 않은 이유가 있을까요?
물론 prepare 부모 메소드는 아무런 동작도 하지 않아서 지금과 별다른 동작 차이는 없습니다.

2022-10-23 10:33 UTC, 1Consumption commented on Expo1900/Expo1900/Model/JSONProcessor.swift
> +    private init() {}
이렇게 생성자를 제한한 이유가 있을까요? 또 enum을 사용하지 않은 이유가 있나요?

2022-10-25 02:06 UTC, oneStar92 commented on Expo1900/Expo1900/Controller/ExpositionItemDetailViewController.swift
> +}
extension을 통해 private Method를 따로 분리해서 관리해주기 위해서 사용했습니다.

2022-10-25 02:07 UTC, hyhy0429 commented on Expo1900/Expo1900/Controller/ExpositionItemDetailViewController.swift
> +    @IBOutlet private weak var itemDescriptionTextView: UITextView!
`Apple HIG` 의 각 문서와 [Displaying Text Content in iOS](https://developer.apple.com/library/archive/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/UsingTextClasses/UsingTextClasses.html)를 참고하였을 때, 저희는 다량의 텍스트를 사용하는데 우선순위를 두어 `TextView`를 사용하였는데, 올라프의 생각도 궁금합니다.

2022-10-25 02:09 UTC, oneStar92 commented on Expo1900/Expo1900/Controller/ExpositionItemDetailViewController.swift
> +class ExpositionItemDetailViewController: UIViewController {
누락되었던 부분이라, 수정하였습니다!

2022-10-25 02:09 UTC, hyhy0429 commented on Expo1900/Expo1900/Controller/ExpositionItemsViewController.swift
> +    }
DataAsset을 불러온 후 Decode된 결과를 반환해주는 객체 추가적으로 구현했습니다.

2022-10-25 02:09 UTC, hyhy0429 commented on Expo1900/Expo1900/Controller/ExpositionItemsViewController.swift
> +    }
Detail한 부분을 놓쳤던 것 같습니다🥲

2022-10-25 02:09 UTC, oneStar92 commented on Expo1900/Expo1900/Controller/ExpositionItemsViewController.swift
> +        cell.accessoryType = .disclosureIndicator
Cell에 extention을 통해 configure메소드를 추가적으로 구현했습니다.

2022-10-25 02:09 UTC, oneStar92 commented on Expo1900/Expo1900/Model/JSONProcessor.swift
> +    private init() {}
생성자를 제한한 이유는, 해당 객체는 Type Method만 호출하여 사용됨으로, 이니셜라이져를 통한 인스턴스화는 불필요하다고 생각되어 private 키워드를 통해 생성자를 제한하였습니다.

2022-10-25 11:12 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemDetailViewController.swift
> +}
Mark주석을 통해 분리할수도 있는데, 굳이 빼줘야하는 이유가 있을까요?

2022-10-25 11:14 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemDetailViewController.swift
> +    @IBOutlet private weak var itemDescriptionTextView: UITextView!
> defines a text view, which displays multiple lines of editable text.

**editable text**라는 말이 있네요. 제 생각에 텍스트필드는 항상 수정 가능한 상황을 고려해 사용해야한다고 생각해요. 

지금과는 다른 경우 같습니다.

2022-10-25 11:17 UTC, 1Consumption commented on Expo1900/Expo1900/Model/JSONProcessor.swift
> +    private init() {}
enum을 사용하면 해당 부분이 해결되지 않나요?

2022-10-25 11:18 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemsViewController.swift
> +        cell.accessoryType = .disclosureIndicator
커스텀셀을 만들어 UI짜는 연습을 더 하면 좋겠습니다. 기본셀은 잘 사용하지 않거든요.

2022-10-25 11:19 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemsViewController.swift
> +    }
제말은 View에서 어떤 데이터를 불러오는지를 알아야할까? 라는 말이었습니다. asset이름까지 view에서 알 필요가 있나요?
View의 역할은 어디까지인가요?

2022-10-25 12:07 UTC, oneStar92 commented on Expo1900/Expo1900/Controller/ExpositionItemDetailViewController.swift
> +    @IBOutlet private weak var itemDescriptionTextView: UITextView!
- Label
![스크린샷 2022-10-25 오후 8 44 14](https://user-images.githubusercontent.com/32012924/197767760-42795c49-966f-444b-8042-ba3c4347f448.png)

저희가 Label과 TextView의 사용 근거에 대한 개념이 부족한것 같습니다.😞 그래서 Apple에서 제공하는 HIG를 다시 살펴봤습니다.🥲 
저희가 다시 이야기 나눈 부분은 밑줄을 친 부분인데요. 다량의 텍스트이면서 선택적으로 편집기능이 필요할 때 TextView를 쓴다고 생각했습니다.
다량의 텍스트도 Label을 사용해도 무방한지가 궁금합니다!🧐

2022-10-25 12:12 UTC, hyhy0429 commented on Expo1900/Expo1900/Controller/ExpositionItemDetailViewController.swift
> +}
올라프의 피드백을 읽어보니, `extension` 은 기능추가라는 확장의 개념에 더 초점을 두어야 하고, 저희가 원하는 상황(코드를 깔끔하게 구분을 짓고 싶은 경우)에는 Mark 주석이 좋을 것 같다는 생각이 드네요! 🙂

2022-10-25 12:16 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemDetailViewController.swift
> +    @IBOutlet private weak var itemDescriptionTextView: UITextView!
네 무방합니다 numberOfLines라는 속성을 참고해주세요.
그리고 첨부해주신 링크에도 optional이지만 edit이라는 키워드가 나오네요. 지금은 용도에 맞지 않아보입니다.

2022-10-25 12:21 UTC, oneStar92 commented on Expo1900/Expo1900/Model/JSONProcessor.swift
> +    private init() {}
기능적으로 둘의 차이점이 없다고 생각하여 `struct`를 사용해서 구현하였습니다...😞
하지만 여러 검색을 통해서 알아본 결과, 둘의 별 차이가 없으나 통상적으로는 `private init()`을 굳이 사용하지 않아도 되는 `enum`을 사용한다는 것을 알게되었습니다!🙂

2022-10-25 14:00 UTC, oneStar92 commented on Expo1900/Expo1900/Controller/ExpositionItemDetailViewController.swift
> +    @IBOutlet private weak var itemDescriptionTextView: UITextView!
[40e635a](https://github.com/yagom-academy/ios-exposition-universelle/pull/221/commits/40e635a51570fb602fed40eea80a4616943ef24f) 넵... 역시 알면알수록 더 어려워지네요... 수정했습니다!

2022-10-25 14:01 UTC, hyhy0429 commented on Expo1900/Expo1900/Controller/ExpositionItemsViewController.swift
> +        cell.accessoryType = .disclosureIndicator
올라프! 저희 STEP3에서 오토레이아웃 작업을 진행하며, CustomCell 구현을 해보아도 괜찮을까요? 🤓

2022-10-25 14:05 UTC, oneStar92 commented on Expo1900/Expo1900/Controller/ExpositionItemsViewController.swift
> +    }
[fb6ffa4](https://github.com/yagom-academy/ios-exposition-universelle/pull/221/commits/fb6ffa4de5dd62d8560ce62391572cfc23229d91) 코멘트 주신 내용 처럼 View에서 asset의 name을 알 필요는 없다고 생각하여 전달받은 DataType을 통해 asset의 Name을 가져올 수 있도록 구현해봤습니다!😂

2022-10-25 14:28 UTC, merged