만국박람회 [STEP 2] 제이푸시, 미니
yagom-academy/ios-exposition-universelle pull request #223
Opened 2022-10-25 05:56 UTC by leegyoungmin

### STEP2 PR
안녕하세여 라자냐!! @wonhee009 
저희가 코드로 UI를 구성하는 법을 공부하다 보니 커밋이 좀 늦었습니다 ㅜ

## 고민 했던 부분
1. view 내부의 버튼 타겟 설정을 위한 Delegate 패턴
- 뷰를 상속 받고 있는 `PosterContentView` 하위 뷰 안에 존재하는 하위 뷰 `flagButton` 타입의 addTarget을 설정하는 과정에서 `ExpositionPosterViewController` 내부에 직접적으로 존재하는 뷰가 아니라 여러가지 방면으로 고민하였습니다.
- 하위 뷰들의 액션을 지정해주는 방법에 대해서 고민한 결과 `Delegate 패턴`을 활용하는 방법을 사용하기로 하였습니다.
- 하지만, 이를 통해서 `ExpositionPosterViewController`가 대리자의 역할을 하는 것이 MVC 패턴으로서 적절하다고 생각하였습니다.
- 그래서 `entityButton`이 직접적으로 버튼의 액션을 정의하고, 이 버튼의 액션이 Delegate를 통해서 위임을 할 수 있도록 구현하였습니다.
- 관련 커밋 : [c42d145](https://github.com/jjpush/ios-exposition-universelle/commit/c42d145c6ed8149c30578ebe9054928f1fd1b63f)

2. custom cell dynamic height
- 테이블 뷰의 커스텀 셀을 구현하는 과정에서 TableView의 다이나믹 Height를 주는 것을 구현하려고 하였습니다. 
- 처음 저희의 생각은 2개의 뷰를 통해서 높이를 직접적으로 계산할 수 있도록 하면, 자동적으로 늘어날 것이라고 생각하였습니다.
- 하지만, 2개의 뷰를 통해서 높이를 계산하는 것은 이미지의 height를 계산하는 과정에서 contentView의 높이가 모호해지는 결과를 낳게 되었고, 이를 해결하기 위해서 `automaticDemention`과 `estimatedHeightForRowAt` 를 이용하려고 하였지만 해결되지 않았습니다.
- 이에 대한 문제는 이미지에 대한 높이를 계산하는 제약과 title과 subTitle의 높이를 계산하는 과정에서 충돌하는 문제였습니다. 추가적으로 title, subtitle이 중앙 정렬이 되지 않고 top으로 붙게 되거나 bottom으로 붙게 되었습니다. 
- 이를 해결하기 위해서 정확하게 Instrict Size를 자동적으로 계산하는 StackView를 활용하여 높이를 자동적으로 계산하고, Top과 Bottom의 제약사항을 통해서 뷰의 셀의 높이를 계산할 수 있도록 하였고, greater와 less 제약사항과 centerYanchor를 통해서 중앙 정렬을 할 수 있도록 하였습니다.
- 관련 커밋 : [27a1b1c](https://github.com/jjpush/ios-exposition-universelle/commit/27a1b1c1e86f8eff22d02fdf3512891eef3ec98b)

## 조언을 받고 싶은 부분
1. Controller의 테이블 뷰 DataSource 및 Delegate 역할
- TableView의 DataSource와 Delegate의 역할을 Controller가 하는 부분이 적절한가에 대해서 고민해보게 되었습니다. SRP의 관점에서는 DataSource와 Delegate의 역할을 하는 것은 Controller의 역할이 한개가 아닌 여러개가 될수도 있겠다고 생각하였습니다.

- 하지만 MVC 관점에서 Controller가 View와 Model의 징검다리의 역할이라고 정의하게 되면, DataSource와 Delegate의 역할을 충분히 할 수 있겠다고 생각하였습니다.

- **물론 관점에 따라서 정답은 없겠지만 라자냐가 보기에는 어떤 방법이 좀 더 설계가 적절한지 궁금합니다.**
- 관련된 커밋 : 

## 추가사항
1. STEP3 내에서 에러 사항에 대한 알림 추가 고려중

2022-10-25 14:56 UTC, wonhee009 requested changes
수고하셨습니다:)
코멘트 남겨두었으니 확인 부탁드려요 🙏 

- "DataSource와 Delegate의 역할을 하는 것은 Controller의 역할이 한개가 아닌 여러개가 될수도 있겠다고 생각하였습니다." 이런 경우가 어떤 경우일까요?

2022-10-25 14:56 UTC, wonhee009 commented on Expo1900/Expo1900/Model/Exposition.swift
> +    }
`Data`를 붙인 이유가 있을까요?
해당 프로퍼티들이 String 타입인데 `-Data`라고 네이밍하니 타입이 Data인가 생각할 수 있을거 같습니다.

2022-10-25 14:56 UTC, wonhee009 commented on Expo1900/Expo1900/Model/Constant.swift
> +    static let durationPrefix = "개최기간 : "
```swift
static let visitorsText = "방문객 : %@명"

String(format: visitorsText, 10)
```
이런건 어떤가요?

2022-10-25 14:56 UTC, wonhee009 commented on Expo1900/Expo1900/View/EntityDetailChildViews/EntityDetailContentView.swift
> +    }
extension 분리 기준이 따로 있는걸까요?

2022-10-25 14:56 UTC, wonhee009 commented on Expo1900/Expo1900/ViewController/KoreaEntitiesViewController.swift
> +    private lazy var tableView: UITableView = {
lazy를 사용한 이유가 있나요?

2022-10-25 14:56 UTC, wonhee009 commented on Expo1900/Expo1900/ViewController/KoreaEntitiesViewController.swift
> +        vc.navigationItem.title = entity.name
image나 description을 `EntityeDetailVC`에서 해주지 않고 `KoreanEntitiesVC`에서 해주고 있네요.
이 부분 `EntityeDetailVC`에 Entity를 아래처럼 주입하는 식으로 하는건 어떤가요?
```swift
let viewController = EntityDetailViewController(entity: entity)
```
그러면 `setImageView()`, `setDescriptionLabel()` 같은 메서드들이 외부에 열려있지 않을 수 있을거 같습니다.

2022-10-26 06:05 UTC, leegyoungmin commented on Expo1900/Expo1900/Model/Exposition.swift
> +    }
Data를 붙인 이유는 실질적으로 사용하는 데이터라고 생각하여서 붙였습니다.
하지만, 라자냐 말씀을 듣고 다시 한번 생각을 해보게 되었고, 원본 데이터에 대한 의미를 부여하는 것이 더욱 모델을 활용하는 입장에서 더욱 정확하고 편리 할 것이라고 생각하였습니다.
또한, 새로운 연산 프로퍼티를 추가할 경우, 변하지 않는 상수로 표현된 데이터를 통해서 새로운 변수 생성에 편리함을 줄 수 있도록 수정하였습니다.

2022-10-26 06:09 UTC, jjpush commented on Expo1900/Expo1900/Model/Constant.swift
> +    static let durationPrefix = "개최기간 : "
좋은것 같습니다! 피드백 받은대로 visitorsText의 포맷을 작성해주고 연산프로퍼티로 값을 넘길 때 visitorsText 포맷을 사용하여 넘기도록 수정했습니다.

2022-10-26 06:15 UTC, leegyoungmin commented on Expo1900/Expo1900/View/EntityDetailChildViews/EntityDetailContentView.swift
> +    }
위의 두개의 extension을 모두 뷰와 관련된 코드로 볼 수도 있지만, 오토 레이아웃을 설정하는 것과 데이터를 설정하고 업데이트 하는 부분은 성격이 다른 코드라고 생각했습니다. 그래서 저희는 오토레이아웃과 관련된 부분의 코드와 뷰의 데이터를 설정하는 부분을 구분 지어서 extension을 수행하였습니다.

2022-10-26 06:37 UTC, leegyoungmin commented on Expo1900/Expo1900/ViewController/KoreaEntitiesViewController.swift
> +    private lazy var tableView: UITableView = {
처음에는 `tableView.delegate = self, tableView.delegate = self` 메서드가 `viewDidLoad` 메서드에서 불리는 것이 코드의 흐름상 tableView 프로퍼티를 생성하는 곳에서 설정하는 것이 자연스럽다고 생각하였습니다.

하지만, tableView를 생성하는 클로저 내부가 init을 하는 단계에서 불리게 되면 Controller 인스턴스가 메모리에 올라가지 않은 상황에서 클로저가 self를 캡처하려고 하여서 클로저 자체를 캡처 하게 됩니다. 그렇기 때문에 `lazy` 키워드를 사용하여서 tableView 프로퍼티의 생성을 늦춤으로 이를 해결하였습니다.

2022-10-26 06:50 UTC, jjpush commented on Expo1900/Expo1900/ViewController/KoreaEntitiesViewController.swift
> +        vc.navigationItem.title = entity.name
저희가 생각하지 못한 부분이었습니다!
피드백 주신대로 ViewController에서 init 메서드를 만들어 준 후 entity 객체를 넣어주어서 init에서 setImageView, setDescriptionLabel 작업을 해주었습니다.

2022-10-26 07:12 UTC, leegyoungmin commented
>"DataSource와 Delegate의 역할을 하는 것은 Controller의 역할이 한개가 아닌 여러개가 될수도 있겠다고 생각하였습니다."
저희의 이 질문의 의미는 Controller가 Delegate와 DataSource를 직접적으로 채택하여서 활용하게 되면, UITableView의 역할도 하기때문에 SRP 원칙에 위배되는 것 인가 라는 의미의 질문이었습니다.

즉, SRP 측면에서 ViewController가 뷰의 역할을 대리하여 가지게 되는 것이 적절한가에 대한 고민이었습니다.

2022-10-27 01:25 UTC, wonhee009 commented on Expo1900/Expo1900/ViewController/KoreaEntitiesViewController.swift
> +    private lazy var tableView: UITableView = {
저는 오히려 `tableView.delegate = self` 같은 경우는 ViewDidLoad가 가져가는게 맞다고 생각하는데요.
self가 사실상 VC를 의미하는데 저 코드가 tableView를 init하는 곳에 있으면 self의 의미가 모호하지 않나 생각합니다.
또한, VC의 메모리가 아직 올라가지 않아서 lazy를 사용해 문제를 해결한거지 lazy를 사용한 적당한 이유는 아니라고 생각합니다.
lazy는 사실상 tableView가 호출될때 메모리에 올라가도록 하는 키워드 인데요. 현재 스펙에서는 그럴 필요가 없다고 생각합니다.
이 부분은 이후 스텝에서 좀 더 고민해봐주세요.

2022-10-27 01:26 UTC, wonhee009 approved these changes
수고하셨습니다. 남겨둔 코멘트 확인해주시고 이후 스텝에서 좀 더 고민해봤으면 좋겠습니다.

> 즉, SRP 측면에서 ViewController가 뷰의 역할을 대리하여 가지게 되는 것이 적절한가에 대한 고민이었습니다.

apple의 MVC에서는 VC가 View와 가깝다라고 얘기하는데요.
(이런 포스트)[https://rolypolytoy.tistory.com/23] 확인해보면 좋을거 같습니다 :)

2022-10-27 01:27 UTC, merged