만국박람회 [STEP 3] Gundy, Dragon
yagom-academy/ios-exposition-universelle pull request #224
Opened 2022-10-26 11:32 UTC by Gundy93

@janbangg
알라딘! 이번 스텝의 오토 레이아웃은 참으로도 극악무도한 것이더군요😰...열심히 공부해서 여러 제약을 잘 파악해야겠습니다.💪

### 조언을 얻고 싶은 부분

- StackView vs View
    - 오토레이아웃을 적용하면서 stackView가 제약 잡는 데에 더 까다로운 부분들이 있어서 view가 더 편한 것은 아닌가? 하는 생각이 들었습니다. 이번 케이스 처럼 필요한 곳이 비슷한 경우 어떤 컴포넌트를 선택하는 것이 적절한 방법인지 궁금합니다.
- 화면 구현
    - 모든 화면은 당연히 코드로도, 스토리보드로도 작성할 줄 알아야 하겠지만, 처음부터 둘 다 잘하는 것은 쉽지 않은 것 같습니다. 하나를 익숙해지고 다른 하나를 익힌다면 어떤 것에 먼저 적응하는 것이 좋을까요?
- Dynamic Type
    - 모든 글자에 Dynamic Type을 적용하는 것이 적절한가요? 타이틀과 본문 등을 무분별하게 동적 변경을 하면 글자가 눈에 잘 들어오지 않는 것 같습니다. 물론 이는 사용자가 감당할 부분이니까 개발자는 모든 글자에 다이나믹 타입을 지원하게끔 하는 것이 맞나 싶은 생각도 듭니다. 알라딘께서는 어떻게 생각하시나요?
- AutoLayout
    - 현재 적용된 AutoLayout 제약들을 보다 간편하게 정리할 수 있는지 문의 드립니다... (질문이 좀 애매합니다만... 혹시, AutoLayout 구현시 자주 구현하는 동작에 대해 어떻게 제약을 거는지 규칙화된 방법이 있는지 궁금합니다.)

### 고민했던 부분

- final 키워드 적용
    - 더이상 상속받지 못하게끔 각종 클래스들을 final 처리하였습니다. 이를 통해 오버라이드를 방지함으로 혹시 저희가 의도한 메서드가 원하는 방식이 아닌 다른 방식의 사용을 방지하고자 하였습니다. 또한 그로 인해 SOLID 원칙 중 리스코프 치환원칙을 위배하는 경우를 아예 사전차단하는 효과도 있다고 생각합니다. 이 밖에도 혹시 '이런 식으로도 생각해볼 수 있다' 하는 부분이 있다면 알려주세요! 😃

2022-10-27 15:20 UTC, junbangg requested changes

2022-10-27 15:20 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/ExhibitionViewController.swift
>      @IBOutlet weak var exhibitionImageView: UIImageView!
여긴 private 없는 이유가 있을까요??

2022-10-27 15:20 UTC, junbangg commented on Expo1900/Expo1900/Sources/View/ExhibitionListTableViewCell.swift
>      @IBOutlet weak var exhibitionImageView: UIImageView!
private?! 혹시 밖에서 접근 할 일이 있나요??

2022-10-27 15:20 UTC, junbangg commented on Expo1900/Expo1900/Sources/View/ExhibitionListTableViewCell.swift
> +    static let identifier: String = "cell"
그냥 "cell" 보다는 조금 더 구체적인게 좋을것 같습니다! 타입의 이름으로 보통 구분하긴 합니다:)

2022-10-27 15:20 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/InformationViewController.swift
> +    @IBOutlet weak var showExhibitionListViewButton: UIButton!
여기도 private?!

2022-10-27 15:31 UTC, Gundy93 commented on Expo1900/Expo1900/Sources/Controller/ExhibitionViewController.swift
>      @IBOutlet weak var exhibitionImageView: UIImageView!
저희가 STEP 2 마무리 과정에서 은닉화 체크할 때 private이 안먹히는 것으로 기억하고 테스트하지 않고 넘어간 부분인데, 지금 테스트해보니까 가능하네요 😂 바로 반영하겠습니다

2022-10-27 15:37 UTC, junbangg commented
```
StackView vs View
오토레이아웃을 적용하면서 stackView가 제약 잡는 데에 더 까다로운 부분들이 있어서 view가 더 편한 것은 아닌가? 하는 생각이 들었습니다. 이번 케이스 처럼 필요한 곳이 비슷한 경우 어떤 컴포넌트를 선택하는 것이 적절한 방법인지 궁금합니다.
```
StackView가 아무래도 꽤 편하게 레이아웃을 잡게 해주는 친구라고 저는 생각하는데🤔 뭐 이것도 개인마다 다르지않을까 싶네요ㅎㅎ
저는 그래서 StackView를 사용할 수 있는 레이아웃이면 그렇게 하고, StackView로는 안되는 뷰들은 오토레이아웃을 딱딱 잡는것 같아요!!
이건 정말 정답이 없고 스타일 차이라고 생각합니다:) 
둘다 가능한 상황이면 더 선호하는 방법을 택하거나! 성능 같은것들도 한번 고려해볼 수 있겠죠~? 근데 지금 같은 뷰에서는 성능 같은건 딱히 고민해볼 필요가 없을것 같아요! (시간되실때 StackView 성능 한번 검색 해보세용)
```
화면 구현
모든 화면은 당연히 코드로도, 스토리보드로도 작성할 줄 알아야 하겠지만, 처음부터 둘 다 잘하는 것은 쉽지 않은 것 같습니다. 하나를 익숙해지고 다른 하나를 익힌다면 어떤 것에 먼저 적응하는 것이 좋을까요?
```
둘다 알아야됩니다! 
근데 뭐가 먼저 익숙해져야되는지는..흠 코드 vs 스토리보드의 장단점이 무엇인지 생각해보셨을까요??
스토리보드의 장점 중에 하나는 눈에 바로 보인다는거죠 제약 같은것들이???
그래서 어떻게 보면 익숙해지기에는 더 좋은 방법일지도 모르겠네요🤔
허나 그렇다고 제대로 이해하지 못한상태로 스토리보드로 제약들 막 무지성 난사하면 도움이 전혀 안됩니다!
그래서 제 생각에는 `지금 가장 익숙한것` 으로 연습하면서 익숙해지는게 가장 좋을것 같네요:)
지금이라면 그게 스토리보드겠죠?! 코드로 해볼 기회 앞으로 충분히 많으실거라고 생각합니다:)

```
Dynamic Type
모든 글자에 Dynamic Type을 적용하는 것이 적절한가요? 타이틀과 본문 등을 무분별하게 동적 변경을 하면 글자가 눈에 잘 들어오지 않는 것 같습니다. 물론 이는 사용자가 감당할 부분이니까 개발자는 모든 글자에 다이나믹 타입을 지원하게끔 하는 것이 맞나 싶은 생각도 듭니다. 알라딘께서는 어떻게 생각하시나요?
```
음 이건 사실 선호?하는것과는 별개의 문제 같습니다! 
저희 개발자들은 가장 중요한게 구현을 할 수 있느냐? 겠죠???
그래서 나중에 회사를 가던 프로젝트를 하던 요구사항에 있으면 구현을 할줄만 알면 된다고 생각해요:)
근데 질문이 이게 아니었던것 같은 느낌이..ㅎㅎ 


```
AutoLayout
현재 적용된 AutoLayout 제약들을 보다 간편하게 정리할 수 있는지 문의 드립니다... (질문이 좀 애매합니다만... 혹시, AutoLayout 구현시 자주 구현하는 동작에 대해 어떻게 제약을 거는지 규칙화된 방법이 있는지 궁금합니다.)
```

저도 처음 공부했을때 그런 생각들을 했던것 같은데...그냥 최대한 많이 해보는 방법이 가장 좋은것 같아요
기본적인 개념들만 충실히 알고 있는 상태로 연습을 하다보면 패턴?들이 보이게 될겁니다! 너무 규칙화된 방법을 외우려고하면 나중에 복잡한 오토레이아웃을 다뤄야될때 오히려 발목을 잡힐 수도 있을것 같아요!

2022-10-27 15:38 UTC, Gundy93 commented on Expo1900/Expo1900/Sources/View/ExhibitionListTableViewCell.swift
>      @IBOutlet weak var exhibitionImageView: UIImageView!
![](https://i.imgur.com/6HjWqbc.png)

`ExhibitionListViewController`의 메서드에서 접근합니다!
`itemsOfExposition`에 `indexPath.row`로 관련한 객체에 접근해야 하기 때문에 셀 타입 내부에서 값을 받아올 수 없다고 생각했습니다.

2022-10-27 15:39 UTC, junbangg commented
그리고 final 에 대해서도 이야기를 해주셨는데 다 맞는 이야기입니다! 
final 이 컴파일러를 어떻게 도와주는지도 한번 시간되실때 찾아보시면 좋을것 같아요! :)

2022-10-27 15:40 UTC, Gundy93 commented on Expo1900/Expo1900/Sources/View/ExhibitionListTableViewCell.swift
> +    static let identifier: String = "cell"
보통 어떻게 네이밍하는지 잘 몰라서 야곰닷넷의 예제를 따라서 "cell"을 선택했었는데, 구체적으로 반영할 수 있는 identifier를 부여하겠습니다! 😃

2022-10-27 15:41 UTC, junbangg commented on Expo1900/Expo1900/Sources/Controller/InformationViewController.swift
>      @IBOutlet weak private var descriptionOfExposition: UILabel!
뭔가 어색하다고 생각했는데 `private weak var` 이 맞지 않을까 싶네요?! 어떻게 생각하십니까🤔

2022-10-27 15:41 UTC, Gundy93 commented on Expo1900/Expo1900/Sources/Controller/InformationViewController.swift
> +    @IBOutlet weak var showExhibitionListViewButton: UIButton!
이것이...! DM으로 자진납세했던 IBOutlet인데, 바로 수정하겠습니다! 🫡

2022-10-27 15:44 UTC, Gundy93 commented on Expo1900/Expo1900/Sources/Controller/InformationViewController.swift
>      @IBOutlet weak private var descriptionOfExposition: UILabel!
저희도 private의 위치에 대해 고민을 했는데요! `@IBOutlet`과 `weak`가 짝꿍이라고 생각해서 그 뒤로 private 위치를 변경한 것 같습니다...하지만 `private weak var`가 컨벤션적으로 더 널리 쓰이거나 적절하다면 당연히 바꿔야한다고 생각합니다!😃

2022-10-27 15:46 UTC, junbangg commented on Expo1900/Expo1900/Sources/View/ExhibitionListTableViewCell.swift
>      @IBOutlet weak var exhibitionImageView: UIImageView!
아하~~~ 그렇군요 그럼 차라리
cell 자체에 저 `Exhibition` 을 넣어줘서 
셀 내부에서 해결하는게 어떨까요??
```
cell.configure(with: item)
```
요런 느낌으로다가
이걸 왜 지금 봤을까요 제가..하하

2022-10-27 15:50 UTC, Gundy93 commented on Expo1900/Expo1900/Sources/View/ExhibitionListTableViewCell.swift
>      @IBOutlet weak var exhibitionImageView: UIImageView!
cell의 일은 cell이 알아서 하라!

2022-10-30 11:20 UTC, junbangg approved these changes

2022-10-30 11:20 UTC, merged