만국박람회 [STEP 3] Zhilly, Mangdi
yagom-academy/ios-exposition-universelle pull request #225
Opened 2022-10-27 02:36 UTC by MangDi-L

@uuu1101 
안녕하세요 태태 :)
STEP-3 완료해서 PR 보냅니다!
AutoLayout에 시간을 제일 많이 할애했습니다 ㅠㅠ

## 🤔 고민했던점

### TableViewCell에 대한 고민
저희가 원래 구현했던 방식으로는 Layout을 잡아주기 힘들 것 같다고 판단해서
Custom Cell을 따로 만들어줘서 구현하는 방식으로 변경했습니다.

xib파일을 같이 만들어줘서 Cell의 xib 파일에서 AutoLayout을 잡아주는 방식으로 진행했습니다.

### 특정화면 세로방향 고정
애플리케이션 전체를 화면 고정할 때에는 프로젝트 설정에서 정해줄 수 있는데, 특정화면을 세로고정하거나, 특정화면에 들어가면 방향을 다시 바꿔준다거나 상세하게 설정해야 할 때에는 어떤 방식으로 해야할지 고민했습니다.

결론은 AppDelegate 파일에서 변수를 하나 두고, `supportedInterfaceOrientationsFor` 를 이용해 화면 고정값을 정해주는 방식으로 진행했습니다.

ViewController 단위에서 화면을 고정해야하거나, 화면을 회전시켜줘야 할 때, viewWillAppear, viewDisAppear 에서 AppDelegate에 접근해 변수를 수정해서 AppDelegate에서 이 ViewController에 대한 화면 전환 값을 알 수 있도록 구현했습니다.

## ✏️ 조언을 얻고 싶은 부분

(서로 구동환경 Xcode 버전과 iOS 버전이 같지 않음)
질리의 시뮬레이터(Version 14.0.1 (986.3))는 가로세로 화면 회전이 정상적으로 작동이 되는데
망디의 시뮬레이터(Version 13.4.1 (977.2))는 정상적인 작동이 되지 않습니다.
가로세로가 바뀌는 그런 기본적인동작이 고작 시뮬레이터의 버전이 조금 낮기때문에? 안되는거라고 보기가 힘든데 혹시 이부분에 대해서 조언해주실수있을까 여쭤봅니다..!

|질리 화면|망디 화면|
|--|--|
|![](https://user-images.githubusercontent.com/99257965/198177304-fe9c1bdf-f3f2-42e4-8075-985ea1ab6b09.gif)|![](https://user-images.githubusercontent.com/49121469/198176460-ed5c3ccc-940b-4e06-b956-ca691848eed5.gif)|

2022-10-28 18:22 UTC, uuu1101 requested changes
STEP3까지 구현하시느라 고생하셨습니다.👍🏻👍🏻

코드 관련해서 몇가지 고민점을 코멘트로 남겨두었습니다! 확인부탁드려요 😊

**✏️ 조언을 얻고 싶은 부분에 대한 답**
- 가로세로가 바뀌는 그런 기본적인동작이 고작 시뮬레이터의 버전이 조금 낮기때문에? 안되는거라고 보기가 힘든데 혹시 이부분에 대해서 조언해주실수있을까 여쭤봅니다..!

> 해당 부분에 대해서 명확한 답을 찾고 있지만 문서로 제공되는 부분을 찾지못했어요.😭

개인적으로 견해를 말씀드리자면, 버전의 차이라고 보여집니다.👀
최신버전으로 업데이트를 해주시는것이 좋을것 같아요.

고작 버전때문이라고? 라고 생각하실수 있지만, 버전에 따라서 현재 작업하시는 프로젝트나 코드들이 작동이 되지 않을 수 있을 만큼 버전관리는 중요합니다.
같이 작업을 하는분들끼리 XCode 버전을 맞추어 작업하는 여러가지 이유중 하나입니다.

물론 현재는 시뮬레이터에 국한된 문제이지만, 제일 좋은 방법은 기기에 앱을 직접 빌드하여 작동해보는것이 가장 좋고, 시뮬레이터를 업데이트 해주시는게 좋을것 같아요! 
시뮬레이터에서는 확인 할 수 없는 기능들도 있습니다. 어떤것들인지 한번 스윽~ 보시는것도 좋다고 생각됩니다!

2022-10-28 18:22 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/KoreanEntriesViewController.swift
>              for: indexPath
Cell을 Custom해서 사용하셨네요 👍🏻👍🏻

2022-10-28 18:22 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/KoreanEntriesViewController.swift
> +
셀이 할수 있는 일은 셀이 하도록 해줘도 좋을 것 같아요.
`koreanEntry`를 셀에게 넘겨주는 방법이 있을 것 같습니다.👍🏻👍🏻

2022-10-28 18:22 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/KoreanEntriesViewController.swift
> +
추가적으로, CustomCell을 만들어주었으니, 10번째 라인의 `cellIdentifier`를 셀이 가지고 있는게 더 적절하지 않을까요?

2022-10-28 18:22 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    }
이렇게 작성하셔도 현재 프로젝트에서는 괜찮을것 같습니다.👏🏻
다만, 뷰 구조가 더 복잡해지게 된다면 두번째 화면이나 세번째 화면에서 viewWillAppear 시점에 해주는게 더 알맞을것 같다는 생각이 드네요.

2022-10-28 18:22 UTC, uuu1101 commented on Expo1900/Expo1900/Delegate/AppDelegate.swift
> +    }
삼항연산자를 이용해보셨네요 👀

2022-10-30 08:35 UTC, zhilly11 commented on Expo1900/Expo1900/Controller/KoreanEntriesViewController.swift
> +
cell 파일에게 cell의 역할을 최대한 맡을 수 있도록 역할을 분리해 줄 수 있도록 했습니다.

`private let cellIdentifier = KoreanEntryTableViewCell().cellIdentifier`
이렇게 `cellIdentifier` 값을 할당해 줬습니다. 이렇게 인스턴스의 프로퍼티를 바로 변수로 할당해 주어도 문제가 없을까요? 옵션키를 눌러서 타입을 확인해 보면  단순하게 `cellIdentifier`의 타입은 String이라고 나오긴 합니다만, 메모리의 관점에서 보면 `KoreanEntryTableViewCell`을 어딘가에 할당해 주고 그 안에 프로퍼티 값을 전달하는 게 아닐까라는 생각이 들었습니다.

2022-10-30 11:45 UTC, uuu1101 reviewed
고생하셨습니다 ! 
코멘트 남긴부분 확인부탁드립니다 !

2022-10-30 11:45 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/KoreanEntriesViewController.swift
> +    private let cellIdentifier = KoreanEntryTableViewCell().cellIdentifier
cellIdentifier를 cell이 가지고 있는데, 여기서 다시 정의해주어야할까요? 👀

2022-10-30 11:45 UTC, uuu1101 commented on Expo1900/Expo1900/View/KoreanEntryTableViewCell.swift
> +    let cellIdentifier: String = "koreanEntryCell"
ViewController에서 바로 접근하지 못하여 위처럼 코멘트부분 처럼 사용하셨는데
```static let cellIdentifier: String = "koreanEntryCell" ``` 으로 수정하시면 
`KoreanEntryTableViewCell.cellIdentifier` 로 접근 가능합니다.
static은 어떤것이길래 이렇게 사용하는게 가능할까요? 👀

2022-11-01 05:24 UTC, merged