만국박람회 [Step 3] Ayaan, Bella
yagom-academy/ios-exposition-universelle pull request #229
Opened 2022-10-27 04:28 UTC by hyhy0429

# 스텝 3 피알

안녕하세요! 올라프 ☃️ @1Consumption
만국박람회 Step3를 구현해보았습니다!🤓
AutoLayout 코드 구현, Dynamic Type 적용, 각 화면 방향 설정 등 새로운 개념을 적용하는 과정에서 미흡한 점이 많이 있습니다. 피드백 잘 부탁드립니다🙌🏼🙌🏼

## [고민했던 점]
#### Label 설정과 Dynamic Type
- MainView의 Label의 font, textAlignment, numberOfLines, lineBreakMode 등의 Label을 설정을 할 때, 코드를 중복해서 작성하게 되었습니다.
- 중복된 코드를 줄이고자 Inheritance 및 Extention을 활용하여 중복된 코드를 줄였습니다.

#### Main VC의 Label의 서로다른 Font 적용
- `range`의 범위를 어떻게 지정해주어야 할지에 대한 고민이 있었고, String Type의 메서드인 `prefix`를 사용해서 지정해 줄 수 있었습니다. 
- 기본적인 Font를 Dynamic Type으로 설정한 후, 원하는 범위의 attributedText를 지정해줬습니다. 하지만 attributedText가 지정된 범위 이외의 Text는 Dynamic Type이 아닌 처음 설정된 Font로 고정되는 오류가 발생했습니다.
- 전체 범위의 attributedText를 지정해 준 후 원하는 범위의 attributedText를 추가적으로 지정해 줘서 이를 해결하였습니다.

#### Main VC의 Title Label 줄바꿈
- Title Label을 줄바꿈하기 위해서 정규식 사용을 고민 하였지만, 너무 무거운 내용이라고 생각되어 다른 방법을 고민했습니다.
- 고민 끝에, Title Label의 text에서 줄바꿈 하고자 하는 부분인 '('의 index를 구한 후, `inset(_, at:)`메서드를 이용해서 원하는 index 부분에 '\n'를 insert 했습니다.

#### 각 화면의 고유 방향 지정
- AppDelegate에서 화면 방향 고정하는 방법도 있는 것을 알았지만, 아직 AppDelegate에 대한 공부가 부족하다고 생각했습니다. 그래서 View Controller의 `supportedInterfaceOrientations` 프로퍼티를 이용해 화면 방향을 고정하도록 구현하였습니다.

## [조언이 필요한 점]

#### 2번째 화면에서 가로 모드로 전환 후 첫번째 화면으로 전환 시 세로모드가 안되는 오류

<img src="https://i.imgur.com/zIVZ6X9.gif" width="300" height="400"/>

- Main View는 Nevigation Controller의 `supportedInterfaceOrientations` 프로퍼티를 사용하여서 Orientation을 `portrait`로 설정하였습니다. 하지만 두번째 화면에서 가로로 화면 전환 후 Main View로 다시 화면을 전환하게 되면 위의 화면과 같은 오류가 발생하였습니다. 어떻게 해결해야 될지 잘 모르겠습니다~!😵‍💫

2022-10-27 13:05 UTC, 1Consumption requested changes
안녕하세요 @hyhy0429 @oneStar92 
마지막 스텝까지 고생하셨습니다.

어느정도 디코로 얘기를 나눴는데, 그중에서 나온 코멘트를 몇개 남겼습니다.

확인 부탁드릴게요.

2022-10-27 13:05 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemDetailViewController.swift
> +
불필요한 변경사항은 커밋하지 말아주세요.

2022-10-27 13:05 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        setUpText(of: durationLabel, text: "개최 기간 : \(expositionUniverselle.duration)")
이부분을(문자열 조합)을 관리해주는 객체를 따로 만들어서 빼면 어떨까요? View는 그 객체에게 요청만하고 반영만 하는거죠.

2022-10-27 13:05 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    }
여기도 마찬가지입니다. 어느정도 잘 나누셨는데, 이부분도 위에 언급한 객체에 같이 들어가면 좋겠어요.

2022-10-27 13:05 UTC, 1Consumption commented on Expo1900/Expo1900/Model/DecimalNumberFormatter.swift
> +class DecimalNumberFormatter: NumberFormatter {
상속 받을일이 없으면 final을 붙여주세요~

2022-10-27 13:05 UTC, 1Consumption commented on Expo1900/Expo1900/View/ExpositionItemCell.swift
> +    }()
var인 이유가 있나요? 그리고 private을 안해준 이유가 있을까요?

2022-10-27 16:09 UTC, hyhy0429 commented on Expo1900/Expo1900/Controller/ExpositionItemDetailViewController.swift
> +
네! 주의하겠습니다! 🥲

2022-10-27 16:10 UTC, oneStar92 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        setUpText(of: durationLabel, text: "개최 기간 : \(expositionUniverselle.duration)")
[400a810](https://github.com/yagom-academy/ios-exposition-universelle/pull/229/commits/400a810130d14a4023415ba77b2fc1286dfc8370) `MainViewManager`를 통해 관리하도록 구현해 봤습니다!!😵‍💫

2022-10-27 16:11 UTC, oneStar92 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    }
[400a810](https://github.com/yagom-academy/ios-exposition-universelle/pull/229/commits/400a810130d14a4023415ba77b2fc1286dfc8370) 위 코멘트와 동일하게 MainViewManager를 통해서 관리하도록 구현하였습니다!!

2022-10-27 16:11 UTC, hyhy0429 commented on Expo1900/Expo1900/View/ExpositionItemCell.swift
> +    }()
생각해보니, 각 레이블의 지정값이 변경될일이 없어 `let`으로 설정해주었습니다. 
또한 해당 타입내에 메서드만 레이블 프로퍼티에 접근이 가능하면 되니, `pravate` 접근제어자를 지정했습니다! 🙌🏼

2022-10-27 16:13 UTC, hyhy0429 commented on Expo1900/Expo1900/Model/DecimalNumberFormatter.swift
> +class DecimalNumberFormatter: NumberFormatter {
아래에 함께 내용 기재하였습니다! 🙂

2022-10-28 10:34 UTC, 1Consumption commented
고생하셨습니다.

2022-10-28 10:34 UTC, merged