만국박람회 [Step3] Jeremy, 준호
yagom-academy/ios-exposition-universelle pull request #230
Opened 2022-10-27 05:05 UTC by yjjem

안녕하세요 ***`올라프`*** ☃️
@1Consumption
STEP3 PR 입니다. 잘 부탁드립니다.

## ✏️ 구현 내용
---
#### Cell Constraint
Cell의 constraint를 적용하면서 imageView의 top, bottom을 지정해주지 않아도 문제가 없을거라고 생각을 했었는데, greaterThen으로 최소값을 10 주어 stackView가 imageView보다 작아질 때containerView에 딱 붙어버리는 문제를 해결하였습니다.
<center><img src="https://i.imgur.com/oMLrCVf.png" width="600px"/></center>

---
#### ViewController AutoLayout
오토레이아웃을 적용해서 이미지 뷰의 크기를 잡아주고, 가로로 회전했을 때도 정상적으로 표시하도록 했습니다.
| ExpositionViewController| ExpositionEntriesViewController | EntryDetailViewController |
| -------- | -------- | -------- |
| <img src="https://i.imgur.com/QNczrXi.jpg" width="170px"/>    | <img src="https://i.imgur.com/LwSUILC.png" width="170px"/>    | <img src="https://i.imgur.com/h1tH8Wx.jpg" width="170px"/>    |
|<center>storyboard</center>|<center>code</center>|<center>storyboard</center>|

| ExpoEntriesViewController(.Landscape) | EntryDetailVeiwController(.Landscape) |
| -------- | -------- |
| <img src="https://i.imgur.com/SeOGx2D.png" width="300px"/>    | <img src="https://i.imgur.com/uBK1K4Y.png" width="300px"/>   |

---
#### Acessability
사용자가 원하는 크기로 텍스트를 읽을 수 있도록 Label과 Button에 Dynamic Type을 적용했습니다. 

| ExpositionViewController | ExpoEntriesViewController | EntryDetailViewController |
| -------- | -------- | -------- |
| <img src="https://i.imgur.com/PA69s8W.png" width="200px"/>    | <img src="https://i.imgur.com/B7Wgb7L.png" width="200px"/>    | <img src="https://i.imgur.com/phW1qey.jpg" width="200px"/>    |

## 🧐 코드를 작성할 때 고민되었던 점

뷰 구성을 스토리보드와 코드 방식을 둘 다 사용해보았습니다.
`ExpositionViewController`,`EntryDetailViewController` -> Storyboard
`ExpoEntryCell` -> Code
* 스토리보드 UI 장단점
    - 장점 : 뷰를 쉽게 추가할 수 있고, 추가한 뷰가 바로 시각화되기 때문에 작업 내용을 확인하기 편함.
    - 단점 : 뷰가 많아지고 화면이 복잡해지면 가독성이 떨어짐.
* 코드 UI 장단점
    - 장점 : 코드로 작성하면 변경사항을 추적하기 쉬움.
    - 단점 : 실제 뷰가 어떻게 그려질 지 바로 확인하기 어렵다. 
* 이번엔 간단히 뷰를 구성할 수 있고 결과를 바로 확인할 수 있는 스토리보드를 우선적으로 사용했습니다.
* CustomCell(ExpoEntryCell)의 contentView의 sub view는 코드를 사용해서 구성해 보았습니다. 스토리보드로 만들다 보니 많은 설정들을 한눈에 보기 어려워서 코드로 작성하는 방법을 써보았습니다.

## 조언을 얻고 싶은 부분
___

`ExpositionManager`,`ExpoEntriesManager` 의 기능을 분리하기위해 아래와 같이 [🔗 테스트 브랜치](https://github.com/junho15/ios-exposition-universelle/commit/4ac8350ab730295a4ea1cd815d8770e7c09927b3)에서 Manager타입을 구현했습니다.

```swift!
typealias Manager = Decoder & ImageMaker

// protocol Decoder extension
extension Decoder {
    
    func configureFromJson<T: Decodable>(assetName: String, type: T?) -> T? {
        guard let dataAsset: NSDataAsset = NSDataAsset(name: assetName) else { return nil }
        let jsonDecoder: JSONDecoder = JSONDecoder ()
        guard let data =  try? jsonDecoder.decode(T?.self, from: dataAsset.data) else { return nil }
        return data
    }
}

// protocol ImageMaker extension
extension ImageMaker {
    
    func makeImage(name: String) -> UIImage? {
        return UIImage(named: name)
    }
    
    func downloadImage(url: Data) -> UIImage? {
        return UIImage(data: url)
    }
}
```

#### 1.1) 이떄 아래의 코멘트에서 남겨주신 내용은 위의 예제와 같이 메소드롤 만들어보라는 방향성을 잡아주신 것 같다는 생각이 드는데 맞게 이해한걸까요? ( 아직 본 브랜치에 적용하지 않았습니다. )
![](https://i.imgur.com/2bnL3QV.png)
#### 1.2) 위의 기능분리 방식에 대한 방향성이 올바른지 궁금합니다.

관련 질문 끝 ---
___

#### 2.1) 커스텀 셀의 contentView의 imageView와 label을 코드로 만들었습니다. 아래와 같이 awakeFromNib() 메서드를 override 하였습니다. 여러 뷰들을 한 곳에서 만들다 보니 코드가 길어지는 데, 여기서도 따로 기능 분리를 하는 게 맞을까요? 
#### 2.2) 한다면 entryImageView, entryNameLabel, entryShortDescriptionLabel, stackView 별로 각각 메서드(인스턴스를 만들고 필요한 속성을 잡아준 뒤 return하는 메서드)를 추가하는 게 좋을까요?
    ```swift
    //  ExpoEntryCell.swift
    override func awakeFromNib() {
        super.awakeFromNib()

        entryImageView = UIImageView()
        entryImageView.translatesAutoresizingMaskIntoConstraints = false
        self.contentView.addSubview(entryImageView)

        entryNameLabel = UILabel()
        entryNameLabel.translatesAutoresizingMaskIntoConstraints = false
        entryNameLabel.font = UIFont.preferredFont(forTextStyle: .title1)
        entryNameLabel.adjustsFontForContentSizeCategory = true
        entryNameLabel.numberOfLines = 0

        entryShortDescriptionLabel = UILabel()
        entryShortDescriptionLabel.translatesAutoresizingMaskIntoConstraints = false
        entryShortDescriptionLabel.font = UIFont.preferredFont(forTextStyle: .callout)
        entryShortDescriptionLabel.adjustsFontForContentSizeCategory = true
        entryShortDescriptionLabel.numberOfLines = 0

        stackView = UIStackView(arrangedSubviews: [entryNameLabel, entryShortDescriptionLabel])
        stackView.translatesAutoresizingMaskIntoConstraints = false
        stackView.alignment = .fill
        stackView.distribution = .fill
        stackView.contentMode = .scaleAspectFit
        stackView.axis = .vertical
        self.contentView.addSubview(stackView)

        NSLayoutConstraint.activate([
            entryImageView.widthAnchor.constraint(equalTo: entryImageView.heightAnchor),
            entryImageView.centerYAnchor.constraint(equalTo: contentView.centerYAnchor),
            entryImageView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 15.0),
            entryImageView.widthAnchor.constraint(equalTo: contentView.widthAnchor, multiplier: 0.2),
            stackView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor),
            contentView.bottomAnchor.constraint(equalTo: stackView.bottomAnchor, constant: 10),
            stackView.leadingAnchor.constraint(equalTo: entryImageView.trailingAnchor, constant: 8.0),
            stackView.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 10)
        ])
    }
    ```

2022-10-27 13:50 UTC, 1Consumption requested changes
안녕하세요 @yjjem @junho15 
마지막 스텝 고생하셨습니다.

몇가지 코멘트를 남겼어요.
그리고 조언을 얻고싶은 점에 적어주신 부분은 아래에 적었습니다.

`typealias Manager = Decoder & ImageMaker` 좋습니다. 뭐 이렇게까지 말한건 아니었는데, 그냥 `이미지를 받아오는 로직을 추상화하면 좋겠다` 정도 였어요.
잘 해주셨습니다.

2022-10-27 13:50 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoEntriesListViewController.swift
> +
이런 불필요한 변경사항은 커밋하지 말아주세요.

2022-10-27 13:50 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoEntryCell.swift
> +    private var entryShortDescriptionLabel: UILabel!
클로저를 통해 생성해주지 않고 var로 선언 후 강제 언래핑을 해준 이유가 있을까요?

2022-10-27 13:50 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoEntryCell.swift
> +    }
너무 기네요! view 별로 메소드를 나눠주세요. constraint 잡는거도 view 별로 나눠야 보기 좋습니다.

2022-10-27 13:50 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionNavigationController.swift
> +class ExpositionNavigationController: UINavigationController {
상속 받을 일이 없는 객체라면 final 키워드를 붙여주세요.

2022-10-27 13:50 UTC, 1Consumption commented on Expo1900/Expo1900/Model/ExpositionManager.swift
> +    }
좋네요 👍

2022-10-28 02:00 UTC, junho15 commented on Expo1900/Expo1900/Controller/ExpoEntryCell.swift
> +    private var entryShortDescriptionLabel: UILabel!
클로저를 통해 생성해주는 방법을 생각하지 못했습니다. 
클로저를 사용하니 awakeFromNib()의 긴 코드가 줄고, view 별로 정리가 되어서 가독성이 좋습니다. 
let으로 선언할 수 있고, 강제 언래핑을 사용하지 않아도 되네요. 감사합니다.
[7993b37](https://github.com/yagom-academy/ios-exposition-universelle/pull/230/commits/7993b377a8a21be5389ae77f9dd45796e8c6b9e2)

2022-10-28 02:03 UTC, yjjem commented on Expo1900/Expo1900/Controller/ExpositionNavigationController.swift
> +class ExpositionNavigationController: UINavigationController {
```swift
final class ExpositionNavigationController: UINavigationController { }
```
앗! 😓 final 지정했습니다. 감사합니다

2022-10-28 02:05 UTC, junho15 commented on Expo1900/Expo1900/Controller/ExpoEntryCell.swift
> +    }
[7993b37](https://github.com/yagom-academy/ios-exposition-universelle/pull/230/commits/7993b377a8a21be5389ae77f9dd45796e8c6b9e2)
각 view들은 클로저를 사용해서 생성해주었습니다.
entryImageView와 stackView의 constraint를 잡아주는 메서드를 두 개 만들어서 분리했습니다.
```swift
    private func activateEntryImageViewConstraint() {
        NSLayoutConstraint.activate([
            entryImageView.widthAnchor.constraint(equalTo: entryImageView.heightAnchor),
            entryImageView.centerYAnchor.constraint(equalTo: contentView.centerYAnchor),
            entryImageView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor, constant: 15),
            entryImageView.widthAnchor.constraint(equalTo: contentView.widthAnchor, multiplier: 0.2),
            entryImageView.topAnchor.constraint(greaterThanOrEqualTo: contentView.topAnchor, constant: 10),
            contentView.bottomAnchor.constraint(greaterThanOrEqualTo: entryImageView.bottomAnchor, constant: 10)
        ])
    }
    
    private func activateStackViewConstraint() {
        NSLayoutConstraint.activate([
            stackView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor),
            contentView.bottomAnchor.constraint(equalTo: stackView.bottomAnchor, constant: 10),
            stackView.leadingAnchor.constraint(equalTo: entryImageView.trailingAnchor, constant: 8),
            stackView.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 10)
        ])
    }
```

2022-10-28 10:32 UTC, merged

2022-10-28 10:32 UTC, 1Consumption commented
고생하셨습니다.