만국박람회 [Step 3] 미니, 제이푸시
yagom-academy/ios-exposition-universelle pull request #233
Opened 2022-10-27 11:57 UTC by jjpush

안녕하세요 라자냐!
@wonhee009 

step3 구현이 끝나서 PR 발송해드립니다.

이번 스텝은 저희가 코드로 작업을 하면서 오토레이아웃을 다 잡으면서 해서 남은 작업인
Dynamic Type과 화면 방향전환 두가지를 구현했습니다.

크게 고민했던 점이나 궁금했던 점은 없었던 것 같습니다.

2022-10-27 12:58 UTC, wonhee009 requested changes
수고하셨습니다!
몇몇 궁금한 부분에 코멘트 남겨두었으니 확인 부탁드려요~:)

2022-10-27 12:58 UTC, wonhee009 commented on Expo1900/Expo1900/View/ExpositionPosterChildViews/FlagButton.swift
> +class FlagButton: UIButton {
final이 사라진 이유가 있나요?.?

2022-10-27 12:58 UTC, wonhee009 commented on Expo1900/Expo1900/View/ExpositionPosterChildViews/FlagButton.swift
> +    }
`required init?(coder: NSCoder)`는 언제 호출되는 메서드인가요?
현재 프로젝트에서는 모든 화면을 코드로 작업한거로 알고 있는데 해당 메서드에서 `setUpLayout()`을 호출할 일이 있나요?

2022-10-28 05:16 UTC, jjpush commented on Expo1900/Expo1900/View/ExpositionPosterChildViews/FlagButton.swift
> +class FlagButton: UIButton {
UIView를 상속하던 커스텀 뷰에서 UIButton을 상속해서 만드는 방법을 생각해보았습니다.
UIButton으로 만들어보니 좀 더 편하고 깔끔한 것 같은 느낌이 들어서 수정을 했는데

그 과정에서 복붙을 하면서 놓쳤습니다 😭
수정하겠습니다!

2022-10-28 05:21 UTC, leegyoungmin commented on Expo1900/Expo1900/View/ExpositionPosterChildViews/FlagButton.swift
> +    }
위의 `required init?(coder: NSCoder)` 초기화 구문은 스토리 보드로 뷰를 불러왔을 때 불리는 초기화입니다.
저희는 코드로 불러오기 때문에 사용되지 않는 초기화 이지만, 필수 구현 초기화 구문 이기 때문에 Designated Initializer를 생성하기 때문에 구현이 불가피합니다.


스토리 보드로 구현하지 않았기 때문에 위의 초기화 구문으로 인스턴스가 생성될 경우는 없지만, 만에하나 저 구문으로 인스턴스가 생성되었을 때, 앱이 죽는 경험은 사용자에게 좋지 않은 경험이라고 생각하여서 레이아웃을 구현하도록 하였습니다.

2022-10-28 07:29 UTC, wonhee009 commented on Expo1900/Expo1900/View/ExpositionPosterChildViews/FlagButton.swift
> +    }
앱이 죽는 경험이 사용자에게 좋지 않은 경험인거는 동의합니다. 다만, 해당 프로젝트의 UI 구성을 코드로 하기로 결정한 부분은 같이 일하는 개발자들끼리의 약속이라고 생각되는데요.
이렇게 코드, 스토리보드 모두 init이 열려 있다면 이후 개발자들에게 둘 다 써도 된다는 생각이 들거 같습니다. 
```swift
required init?(coder: NSCoder) {
   fatalError("init(coder:) has not been implemented")
}
```
이렇게 경고를 남긴다면 이후 개발자들에게도 코드로만 화면을 추가해야한다는 하나의 명세서의 역할을 할 수 있을거 같습니다.

2022-10-28 09:57 UTC, jjpush commented on Expo1900/Expo1900/View/ExpositionPosterChildViews/FlagButton.swift
> +    }
이해했습니다 required init 되는 부분을 모두 수정해서 적용했습니다!!

2022-10-28 09:59 UTC, wonhee009 approved these changes
수고하셨습니다 👍

2022-10-28 09:59 UTC, merged