만국박람회 [STEP 1] 혜모리, Andrew
yagom-academy/ios-exposition-universelle pull request #237
Opened 2023-02-20 07:25 UTC by Andrew-0411

@junbangg 알라딘 안녕하세요! 혜모리, 앤드류 인사드립니다 🙇🏻‍♂️🙇🏻‍♀️
이번 만국박람회 프로젝트 리뷰 잘 부탁드리겠습니다.

요구사항에 제시된 dataset json 포멧의 데이터와 매칭할 모델 타입
`ExpositionInfo`, `Entry` 타입을 구현해 보았습니다.

## 고민했던점 & 조언을 얻고 싶은 점
- Swift는 camel case를 사용하고 JSON은 snake case를 사용하기 때문에 Key값이 달라서 nil값을 반환할 수 있으므로 `CodingKey` 프로토콜을 사용하여 이를 방지 하였습니다.
 
- Codable 프로토콜을 사용하기 보다는 좀 더 명확하게 기능을 표현하기 위해서 현재 Decode만 할 것이라 판단하여 각 타입에 `Decodable` 프로토콜을 채택하였습니다.

- MVC 패턴으로 폴더를 나눠보았습니다. 그 중 `AppDelegate`랑 `SceneDelegate` 파일을 어떤 폴더에 두어야 할 지 고민했습니다. 이전 프로젝트에서는 `Controller` 폴더에 두 파일을 위치해놓아서 이번에도 그렇게 두었는데, 알라딘은 어떤 방식으로 폴더를 정리하시는지 궁금합니다.

2023-02-22 11:29 UTC, junbangg requested changes
수고하셨습니다!!
질문 주신 AppDelegate, SceneDelegate의 위치는 프로젝트 규모에 따라 달라질것 같은데요~ 지금은 Controller 에 둬도 크게 어색함은 없지만 예시를 하나 들면 만약에 Controller 가 하나의 화면을 담당하는 구조로 확장이된다면 또 달라질 수도 있겠죠??

2023-02-22 11:29 UTC, junbangg commented on Expo1900/Expo1900.xcodeproj/project.pbxproj
> +				C79FF4BD2589F404005FB0FD /* Assets.xcassets */,
Assets를 뷰에 넣으신 이유가 있을까요?!

2023-02-22 11:29 UTC, junbangg commented on Expo1900/Expo1900/Model/Entry.swift
> +    let description: String
👍

2023-02-22 11:29 UTC, junbangg commented on Expo1900/Expo1900/Model/ExpositionInfo.swift
> +    let visitors: Int
어라 visitors 가 Int 타입이네요?!
방문객 수 인걸 바로 파악하기 힘든 네이밍일지도 모르겠다는 생각이 드는데 어떻게 생각하시나요~?

2023-02-22 11:29 UTC, junbangg commented on Expo1900/Expo1900/Model/Entry.swift
> +struct Entry: Decodable {
Entry 로 이름을 정하신 이유가 있나요~?(틀렸다는거 아님)

2023-02-23 01:56 UTC, Andrew-0411 commented on Expo1900/Expo1900.xcodeproj/project.pbxproj
> +				C79FF4BD2589F404005FB0FD /* Assets.xcassets */,
화면에 보여지는 파일이기 때문에 View폴더로 분류했습니다. 그런데 데이터일 수도 있다고 생각이드는데 Model로 분류해야할지 궁금합니다

2023-02-23 02:03 UTC, hyemory commented on Expo1900/Expo1900/Model/ExpositionInfo.swift
> +    let visitors: Int
방문객의 수를 가리키는 프로퍼티로 `numberOfVisitors`가 더 알맞은 것 같아 수정하였습니다!

2023-02-23 02:06 UTC, Andrew-0411 commented on Expo1900/Expo1900/Model/Entry.swift
> +struct Entry: Decodable {
번역기로 출품작이 Entry로 나왔고 Entry로 검색을 했을 때도 작품에 관련된것들이 나오기 때문에 Entry로 정했습니다.

2023-02-23 09:08 UTC, junbangg commented on Expo1900/Expo1900.xcodeproj/project.pbxproj
> +				C79FF4BD2589F404005FB0FD /* Assets.xcassets */,
resources 이라는 폴더를 만들어서 넣어주는 방법도 있을걱 같아요~ 너무 그 세개의 폴더로 딱 나누실 필요는 없습니다🤗 어울리지 않으면 새로운 관리 체계를 추구할 수 있으니까요~

2023-02-23 09:09 UTC, merged