만국박람회 [STEP1] 무리, 새홍, 송준
yagom-academy/ios-exposition-universelle pull request #238
Opened 2023-02-20 07:27 UTC by kimseongj

@1Consumption 

# PR

안녕하세요 올라프! 👨‍👧‍👧세홍, 송준, 무리입니다.
이번 프로젝트동안 잘부탁드리겠습니다☺️

## 고민했던 부분

### 1️⃣ 스네이크 카멜
Json 파일의 "image_name", "short_desc"와 같은 스네이크 카멜을 만국박람회 앱에서 어떻게 매칭시켜줘야 할지 고민이 되었습니다. 처음엔 변수명을 똑같이 스네이크카멜로 써도 되지 않을까? 생각했는데 ~~팀원들의 결사반대로~~ 구글링으로 찾은 `CodingKey`프로토콜을 채택하는 방법으로 사용하게되었습니다.

### 2️⃣ Contents.json 파일의 역할이 무엇일까요?
공식문서상에는 Asset의 속성 인코딩을 가지고 있다고 나옵니다. 또한 각 폴더당 하나의 JSON파일을 가진다고 합니다. 그렇다면, 이 파일에 대한 `decoding`데이터타입 정의는 필요가 없는걸까요?
<img width="891" alt="스크린샷 2023-02-20 오후 4 13 38" src="https://user-images.githubusercontent.com/88870642/220037500-9a29ccfa-9bf6-4744-bade-d86b517ff972.png">

## 조언을 얻고싶은 부분

### 1️⃣ test code 작성여부 
JSON 파싱이 잘되는지 확인하기 위해 테스트 코드를 작성하는지 궁금합니다. 또한 어떤식으로 테스트를 하는지 키워드를 주시면 작성해보도록 하겠습니다. 

### 2️⃣ 파일명이나 변수명 
박람회라는 단어의 경우 exposition, exhibition, entry 등등의 단어가 있었습니다. 박람회로 가장 많이 쓰이는 단어인 'expo' 정도로 줄여서 사용해도 되는지 궁금합니다. 이름 짓는 부분에서 의견이 맞지 않는 부분이 있어서 어떤걸 참고하여 네이밍을 하면 좋을지 조언 부탁드립니다.

2023-02-20 16:30 UTC, 1Consumption requested changes
안녕하세요,
@kimseongj @sehoong0429 @parkmuri
반갑습니다🙇‍♂️

저도 이번 프로젝트 잘 부탁드리겠습니다.

변경사항이 많지 않아 코멘트를 달게 별로 없네요.

아래에는 고민한 점, 조언을 얻고싶은 점에 대해 제 생각을 적었으니 참고해주세요.

------------------------------------------

## 고민했던 부분

### 1️⃣ 스네이크 카멜
Json 파일의 "image_name", "short_desc"와 같은 스네이크 카멜을 만국박람회 앱에서 어떻게 매칭시켜줘야 할지 고민이 되었습니다. 처음엔 변수명을 똑같이 스네이크카멜로 써도 되지 않을까? 생각했는데 ~~팀원들의 결사반대로~~ 구글링으로 찾은 `CodingKey`프로토콜을 채택하는 방법으로 사용하게되었습니다.

> 스네이크 카멜은 어떤걸 말하는걸까요? 스네이크 케이스를 말씀하시는 걸까요? 그렇다면 왜 스네이크 케이스를 사용해도 된다고 생각했는지 궁금합니다.
Swift API Design Guidelines를 참고해보세요. Swift에서는 [카멜케이스를 권장](https://www.swift.org/documentation/api-design-guidelines/#follow-case-conventions)하고 있습니다. 

### 2️⃣ Contents.json 파일의 역할이 무엇일까요?
공식문서상에는 Asset의 속성 인코딩을 가지고 있다고 나옵니다. 또한 각 폴더당 하나의 JSON파일을 가진다고 합니다. 그렇다면, 이 파일에 대한 `decoding`데이터타입 정의는 필요가 없는걸까요?
<img width="891" alt="스크린샷 2023-02-20 오후 4 13 38" src="https://user-images.githubusercontent.com/88870642/220037500-9a29ccfa-9bf6-4744-bade-d86b517ff972.png">

> `decoding 데이터타입`이 정확히 뭘 말하는건가요? `Contents.json`을 디코딩해 인스턴스화 한다는 말일까요?  이 부분을 모르겠어서 정확한 답변을 드리지 못하겠습니다.

## 조언을 얻고싶은 부분

### 1️⃣ test code 작성여부 
JSON 파싱이 잘되는지 확인하기 위해 테스트 코드를 작성하는지 궁금합니다. 또한 어떤식으로 테스트를 하는지 키워드를 주시면 작성해보도록 하겠습니다. 

> 테스트 코드는 작성해야 할까요? 그렇다면 왜 작성해야할까요? 이를 모르고 무작정 테스트를 진행하는 것은 좋지 않다고 생각됩니다. 이부분은 구글링을 통해 충분히 정보를 수집할 수 있을거라고 생각됩니다. 충분히 자료를 찾아보시고, 그래도 모르겠으면 그때 다시 얘기를 하는게 좋아보입니다.
또한 아직 지금 단계에서 유닛 테스트를 제대로 진행하기는 무리가 있다고 생각합니다.

### 2️⃣ 파일명이나 변수명 
박람회라는 단어의 경우 exposition, exhibition, entry 등등의 단어가 있었습니다. 박람회로 가장 많이 쓰이는 단어인 'expo' 정도로 줄여서 사용해도 되는지 궁금합니다. 이름 짓는 부분에서 의견이 맞지 않는 부분이 있어서 어떤걸 참고하여 네이밍을 하면 좋을지 조언 부탁드립니다. 

> `내가 짠 코드의 배경을 읽는 사람은 모를거다`라는 전제하에 코드를 작성해야 읽기 쉬운 코드를 작성할 수 있습니다. 약어는 배경을 모르면 알기 어려우니 지양해주세요.
Swift API Design Guidelines를 참고해보세요. Swift에서는 [약어를 지양](https://www.swift.org/documentation/api-design-guidelines/#avoid-abbreviations)하라고 합니다.

2023-02-20 16:30 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ViewController.swift
>      }
현재 오버라이딩을 할 필요가 없으니 아예 지워도 좋은 코드 같습니다.

2023-02-20 16:30 UTC, 1Consumption commented on Expo1900/Expo1900/Models/EntryItems.swift
> +struct EntryItems: Codable {
`Codable`은 어떤 프로토콜인가요? 지금은 decode만 수행할 거 같은데, `Codable`의 기능이 전부 다 필요할까요?

2023-02-20 16:30 UTC, 1Consumption commented on Expo1900/Expo1900/Models/EntryItems.swift
> +    private enum CondingKeys: String, CodingKey {
`CodingKey` 는 어떤 역할을 하나요?

2023-02-20 17:11 UTC, 1Consumption commented on Expo1900/Expo1900/Models/EntryItems.swift
> +struct EntryItems: Codable {
`EntryItems`라는 복수형이 맞을까요?

2023-02-21 00:39 UTC, kimseongj commented on Expo1900/Expo1900/Controller/ViewController.swift
>      }
넵! 확인하고 수정하였습니다.

2023-02-21 00:42 UTC, sehoong0429 commented on Expo1900/Expo1900/Models/EntryItems.swift
> +struct EntryItems: Codable {
`Codable` 은 swift의 프로토콜 중 하나로 `Encodable`과 `Decodable` 프로토콜을 합친 것입니다.
`Encodable`은 Swift 데이터 타입을 JSON, XML 등과 같은 외부 데이터 형식으로 변환 할 수 있도록 하는 프로토콜이고, 
`Decodable`은 반대로 외부 데이터에서 Swift 데이터 타입으로 변환 할 수 있도록 하는 프로토콜입니다. 
올라프가 질문해주신대로 저희 프로젝트에서는 현재 외부 데이터를 Swift 데이터 타입으로 디코딩만 수행 하고 있기 때문에 디코딩만 가능한 `Decodable` 프로토콜만 사용하도록 수정 하였습니다.

2023-02-21 00:43 UTC, parkmuri commented on Expo1900/Expo1900/Models/EntryItems.swift
> +    private enum CondingKeys: String, CodingKey {
- 먼저 인코딩, 디코딩을 하려면 JSON의 key와 사용자의 key가 일치해야합니다.
사용하고자 하는 key가 JSON의 key와 다른경우(위와같이 스네이크 케이스이거나 약어 등으로 네이밍 가이드에서 권장하는 사항에 맞지않을때) `CodingKey`라는 프로토콜을 채택한 `enum CodingKeys`를 이용할 수 있습니다.

- 위에 코멘트 주신 부분에서 "왜 스네이크 케이스를 사용해도 된다고 생각했는지"에 대해서는 아직 `CodingKey`에 대한 개념이 없었고 JSON과는 변수명을 동일하게 주고싶어서 사용해도 되지않을까 하는 생각을 하게됐습니다..🥲!

2023-02-21 00:46 UTC, kimseongj commented on Expo1900/Expo1900/Models/EntryItems.swift
> +struct EntryItems: Codable {
음.. 출품작들이 복수라서 `EntryItems`라고 작성했던 것 같습니다. 하지만 출품작들의 각각의 데이터를 불러오는 것이기 때문에 단수형으로 바꾸는게 맞는거 같습니다!

2023-02-21 00:55 UTC, kimseongj commented
> ### 2️⃣ Contents.json 파일의 역할이 무엇일까요?
> 공식문서상에는 Asset의 속성 인코딩을 가지고 있다고 나옵니다. 또한 각 폴더당 하나의 JSON파일을 가진다고 합니다. 그렇다면, 이 파일에 대한 `decoding`데이터타입 정의는 필요가 없는걸까요? <img alt="스크린샷 2023-02-20 오후 4 13 38" width="891" src="https://user-images.githubusercontent.com/88870642/220037500-9a29ccfa-9bf6-4744-bade-d86b517ff972.png">
> 
> > `decoding 데이터타입`이 정확히 뭘 말하는건가요? `Contents.json`을 디코딩해 인스턴스화 한다는 말일까요?  이 부분이 어떤것을 뜻하는지 모르겠어서 정확한 답변을 드리지 못하겠습니다.

> Asset파일에 아래와 같은 Contents.json 파일이 존재했습니다!
<img width="262" alt="스크린샷 2023-02-21 오전 9 51 52" src="https://user-images.githubusercontent.com/88870642/220221080-1b0aea3d-a55e-4d48-a0a8-aecb0886a9c2.png">
그 안에 내용은 아래와 같습니다.

```swift
{
  "images" : [
    {
      "filename" : "bangjja~universal@1x.png",
      "idiom" : "universal",
      "scale" : "1x"
    },
    {
      "filename" : "bangjja~universal@2x.png",
      "idiom" : "universal",
      "scale" : "2x"
    },
    {
      "filename" : "bangjja~universal@3x.png",
      "idiom" : "universal",
      "scale" : "3x"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
```
이러한 JSON파일에 대한 아래와 같은 데이터 모델을 만들지 않아도 되는걸까요?
```swift
struct EntryItem: Decodable {
    let name: String
    let imageName: String
    let shortDescription: String
    let description: String
    
    private enum CondingKeys: String, CodingKey {
        case name
        case imageName = "image_name"
        case shortDescription = "short_desc"
        case description = "desc"
    }
}
```

2023-02-21 13:04 UTC, 1Consumption commented
네 그렇습니다~ xcode가 자동으로 파싱을 하고 있어요.

2023-02-21 13:49 UTC, merged