만국박람회 [STEP2] kaki, Brody
yagom-academy/ios-exposition-universelle pull request #244
Opened 2023-02-22 06:35 UTC by kak1x

# 만국박람회 [STEP2] Brody, kaki
@havilog
안녕하세요 havi! STEP2 PR 요청 드립니다!🙂🙂🙂
리뷰 잘 부탁드릴게요~🙇🏻

## UML
![](https://i.imgur.com/uHwVGkw.png)

## 고민했던 내용
### 1. 첫번째 화면에서만 네이게이션 바를 숨기는 방법
- 전체 화면에 네비게이션 바를 설정해주며 첫번째 화면에서만 네이게이션 바를 숨기는 방법에 대해 고민하였습니다.
- `isNavigationBarHidden` 프로퍼티를 이용하여 네이게이션 바를 숨겨주었으며, 첫번째 화면으로 돌아올때마다 숨기는 기능이 활성화 될 수 있도록 첫번째 뷰컨트롤러의 `viewWillAppear`에 정의해주었고 두번째 화면으로 진입할때마다 숨기는 기능이 꺼질 수 있도록 두번째 뷰컨트롤러의 `viewDidLoad`에 정의해주었습니다.
### 2. 받아온 String의 중간 부분부터의 폰트 수정 방법
- `firstIndex` 메서드와 String 서브스크립트를 사용하여 수정할 String range를 찾아주었고 이를 `NSMutableAttributedString`의 `addAttribute` 메서드를 사용하여 폰트를 수정해주었습니다.
- String이 아닌 `NSMutableAttributedString`을 Label.text에 할당해주기 위하여 `Label.attributedText` 프로퍼티를 사용하여 이를 할당해주었습니다.
### 3. 이미지를 비율에 맞춰 정사각형 크기로 조정해주는 방법
- 두번째 화면에 진입할 시, 이미지 크기를 조정해주지 않으면 이미지가 제멋대로의 크기로 할당되는 문제가 있었습니다.
- 커스텀 셀이 아니었기에 이를 따로 처리해줄 방법을 고민하다 할당되는 이미지 크기 자체를 조정해주기로 하였습니다.
- 비율에 맞춰 정사각형 모양으로, 여백은 clear하게 처리해줄 수 있는 `squreImage` 메서드를 extension으로 UIImage의 메서드로 추가하여 사용해주었습니다.
### 4. 스크롤뷰에서 크기가 정해지지 않은 IBOutlet들의 y position을 지정해주라고 나오는 경고 해결 방법
- 스토리보드에서 스크롤뷰에 stackView를 content로 넣어줬는데, y position을 지정해주라는 경고가 발생했습니다.
- 크기를 미리 정해주지 않고, 채워질 내용에 따라 크기가 바뀌는 것이라 y position을 지정해줄 수 없는 상황이었기에 stackView의 `Intrinsic Size`를 `Placeholder`로 지정해주어 해결해주었습니다.
### 5. 최대 이미지 크기를 정해주는 방법
- 화면에 보여지는 이미지들이 다른 사이즈를 갖고 있어서 이에 대해 통일된 뷰를 보여줘야하는 부분에 대해 고민했습니다.
- 이미지 뷰의 `content mode`를 `Aspect Fit`을 사용해 이미지 비율을 유지하면서 꽉 차게 만들었고, `width`와 `height` 제약에 `<=200`를 추가함으로써 최대 사이즈가 200을 넘어가지 않도록 만들었습니다. 

### 6. 커스템 셀을 사용하지 않고 Image, Title, SubTitle 셀을 사용하는 방법
- 레이아웃을 보니 커스텀 셀을 만들지 않고 기본 셀로도 가능하다고 생각이 들어 기본 셀을 사용했습니다. 
- iOS14이후로의 기본 셀의 스타일 조정은 `defaultContentConfiguration` 메서드를 이용하도록 바뀌었습니다. 그래서 이 메서드를 통해 `UIListConfiguration`타입의 객체를 만들어준 뒤 이 곳에서 `image`, `text`, `secondaryText`를 설정해주었습니다.

## 조언받고싶은 점

### 네임스페이스 사용

- 현재 프로젝트에서는 asset에서 자료를 불러올 때의 매직리터럴을 네임스페이스로 처리하고 있습니다.
```swift
enum AssetName {
    static let exposition = "exposition_universelle_1900"
    static let poster = "poster"
    static let flag = "flag"
    static let items = "items"
}
```

- 하지만 해당 부분 외에도 매직리터럴이 아래와 같이 존재하고 있습니다.
<img src="https://i.imgur.com/uq0xbjw.png" width="500"/>
<img src="https://i.imgur.com/uwhYere.png" width="500"/>
- 하비는 이런 매직리터럴에 대해서 어떻게 처리하시는지 궁금합니다.

2023-02-22 15:17 UTC, havilog requested changes
private 접근제한자 처리나, 뷰컨 내부의 함수 분리에 신경쓰신 부분이 좋네요 👍 

> 조언받고싶은 점

개인적인 의견인데, tag: 0 과 같은 매직넘버가 아니라면, 너무 신경 안쓰셔도 괜찮을거 같아요.
매직넘버, 매직리터럴이 안좋은 이유는 
다른 사람이 알아보기 힘들 때 유지보수성과, 
string에 오타가 있어 오동작 할 때를 유의하셔서 고민하시고 사용하시면 될거 같아요.

> 테스트코드

모델이 Equatable하면 좋은 이유는,
모델을 테스트하는게 아니라,
어떤 비즈니스 로직이 있을 때
ex) 버튼이 눌려서 -> 네트워크에서 받아온 데이터를 비즈니스로직으로 가공해서 -> 상태를 보여줄 때
비즈니스로직에 대한 테스트 코드를 짜서 상태를 검증할 때 필요한 경우를 말씀드린거에요.
만국박람회에서는 테스트에 대한 부분은 나중에 고민하셔도 괜찮지 않을까 하는 개인적인 의견입니다.

2023-02-22 15:17 UTC, havilog commented on Expo1900/Expo1900/Controllers/ItemDetailViewController.swift
> +    var itemData: ExpositionUniverselleItem?
해당 프로퍼티가 바뀔일도, 없을 일도 없을거 같이 생겨보여요!
또한 property injection을 하는것도 휴먼에러의 위험성이 보입니다.
init 시점에서 non-optional 타입을 받아오는것이 좋을거 같습니다.

2023-02-22 15:17 UTC, havilog commented on Expo1900/Expo1900/Controllers/ItemDetailViewController.swift
> +final class ItemDetailViewController: UIViewController {
final로 최적화 해주신거 좋네요!
내부적으로 어떻게 동작하고 최적화되는지 알고 계실까요?

2023-02-22 15:17 UTC, havilog commented on Expo1900/Expo1900/Controllers/ItemDetailViewController.swift
> +    var itemData: ExpositionUniverselleItem?
프로퍼티 이름은 개인 취향이긴 한데..
`Data`라는 suffix가 의미하는 바가 있을지 애매한거 같아요.
item이라고 해도 충분할거 같다는 느낌이랄가요 .. ㅎㅎ

2023-02-22 15:17 UTC, havilog commented on Expo1900/Expo1900/Controllers/KoreaItemsViewController.swift
> +    private let cellIdentifier: String = "cell"
protocol을 사용해서 모든 Cell타입이 identifier를 가지게 할 수 있는데 찾아보시면 좋을것 같습니다!

2023-02-22 15:17 UTC, havilog commented on Expo1900/Expo1900/Controllers/KoreaItemsViewController.swift
> +}
에러가 발생했을 때 유저가 확인할 수 있는 방법이 없을거 같은데,
에러처리는 어떻게 해야 적절할지 고민해보셨을까요?

2023-02-22 15:17 UTC, havilog commented on Expo1900/Expo1900/Controllers/ParisExpositionUniverselleViewController.swift
> +    }
KoreaItemsViewController에 있는 함수와 같은 역할을 하는 함수네요!
이 로직을 공통화 할 수 있는 방법은 생각해보셨을까요?

2023-02-22 15:17 UTC, havilog commented on Expo1900/Expo1900/Models/ExpositionUniverselle.swift
> +    let visitors: UInt
visitors라는 프로퍼티 명은, 
[Visitor]를 암시할 수도 있어서 헷갈릴 수도 있을거 같아요~

2023-02-22 15:17 UTC, havilog commented on Expo1900/Expo1900/Etc/Extension/UIntExtension.swift
> +        return numberFormatter.string(for: self) ?? "0"
개발자마다 다양한 시각이 존재하겠지만,
저라면 numberFormatter에 있는 `.string(for:)` api자체가 optional을 반환하기 때문에,
default값을 지정해주거나, optional인 채로 label의 text에 넣는건 불가피할 것 같아요.
따라서 위 부분에서 0을 default로 넣어주는게 틀려보이진 않아요.

2023-02-22 15:17 UTC, havilog commented on Expo1900/Expo1900/Controllers/KoreaItemsViewController.swift
> +        self.title = "한국의 출품작"
해당 부분도 궁금하다고 커멘트 남겨주셨는데,

상수가 많다면,
KoreaItemsViewController에서
```
private enum Constant {
/// 안 변할 static let 상수들
}
```
을 잡아주는 경우도 있고,
localization이 필요하다면 로컬라이징 해주는 파일에서 정의해줄 수도 있는데요.

저라면 이정도는 그냥 쓸거 같아요 ㅋㅋ..

2023-02-22 15:17 UTC, havilog commented on Expo1900/Expo1900/Etc/AssetName.swift
> +}
네임스페이스로 상수를 선언해주신거 좋습니다!
다만, 이러면 프로젝트 전역에서 접근이 가능한데,
많은 곳에서 사용하는게 아니라면 전역적인 네임스페이스는 오히려 헷갈릴 수도 있을거 같다는 생각도 드네요 ㅎㅎ
틀렸다는건 아니에여

2023-02-22 15:17 UTC, havilog commented on Expo1900/Expo1900/Controllers/KoreaItemsViewController.swift
> +    }
스토리보드로 뷰를 그리는거와 코드로 그리는거는 개발자의 취향 차이인데요,
서브뷰를 그리기 위해 xib를 활용하는 법을 알면 좋을 것 같구, 
하나의 스토리보드에 여러개의 화면이 들어가면 무거워져서 스토리보드를 여러개로 분리해도 좋을 것 같아요.
또한 강제 캐스팅으로 destination을 찾는것도 위험해보입니다.

2023-02-22 15:17 UTC, havilog commented on Expo1900/Expo1900/Controllers/KoreaItemsViewController.swift
> +        cell.contentConfiguration = content
custom cell을 안 만들고, `defaultContentConfiguration()`를 사용하셨는데, UI상 기본 셀을 사용할 수 있다 하더라도, 웬만하면 커스텀 셀을 만드는게 나을거 같다는 의견입니다 ㅎㅎ

2023-02-22 15:17 UTC, havilog commented on Expo1900/Expo1900/Controllers/ParisExpositionUniverselleViewController.swift
> +        expositionDuration.attributedText = changeFont(expositionData.displayedDuration)
요것도 갠취인데요,
저라면 fileprivate extension String으로 
`expositionVisitors.attributedText = expositionData.displayedVisitors.attributedString`
으로 리니어하게 썼을거 같아요 ㅎㅎ

2023-02-22 15:17 UTC, havilog commented on Expo1900/Expo1900/Etc/Extension/UIImageExtension.swift
> +
이미지의 크기를 조정하고 싶으셔서 UIImage를 CoreGraphic 기반으로 StackOverflow 코드를 가져오신거라 생각되는데 ...
오토레이아웃으로 이미지의 사이즈를 잡아주는게 맞을거 같습니다.

2023-02-22 15:17 UTC, havilog commented on Expo1900/Expo1900/Controllers/ItemDetailViewController.swift
> +        self.title = itemData.name
네비게이션 바의 타이틀이 아니라, self의 title을 바꿔주는 이유가 있을까요?

2023-02-23 08:10 UTC, seunghyunCheon commented on Expo1900/Expo1900/Controllers/ItemDetailViewController.swift
> +final class ItemDetailViewController: UIViewController {
기본적으로 컴파일러는 `class`타입 정보에 대한 것을 정적 메모리에 저장하고 클래스의 메서드를 호출할 때 `vtable`을 조회해 실행하기에 적합한 메서드를 찾게 됩니다. 이를 다이나믹 디스패치라고 부르며 메서드에서 함수의 주소로 바로 이동하는 것이 아니기 때문에 정적 디스패치를 이용하는 `struct`보다 속도가 느리다는 특징이 있습니다.

하지만 클래스에 `final`을 붙이면 더이상 상속하는 클래스가 없어지므로 정적 디스패치로 되고, 컴파일시간에 함수의 호출주소를 알 수 있게되어 성능이 향상됩니다!

2023-02-24 02:37 UTC, kak1x commented on Expo1900/Expo1900/Controllers/ItemDetailViewController.swift
> +        self.title = itemData.name
탭바가 없어서 self.title로 설정해주어도 네이게이션 바의 타이틀만 바뀌기에 사용했는데, 좀 더 명확하게 적어주는 것이 좋을 것 같다 판단하여 self.navigationItem.title = 으로 변경해주었습니다.

2023-02-24 02:38 UTC, kak1x commented on Expo1900/Expo1900/Etc/Extension/UIImageExtension.swift
> +
오토레이아웃으로 이미지 사이즈를 조절하게 바꾸어주고 기존의 UIImageExtension은 삭제해주었습니다.

2023-02-24 02:38 UTC, seunghyunCheon commented on Expo1900/Expo1900/Controllers/KoreaItemsViewController.swift
> +    }
테이블 뷰의 커스텀셀을 `xib`로 분리했고 `UITableViewCell`로 타입캐스팅할 때 생기는 휴먼에러나 강제캐스팅과 같은 위험부분을 제거했습니다. 
```swift
if let itemDetailVC = storyboard?.instantiateViewController(identifier: "ItemDetailViewController", creator: { creator in
    let item = self.expositionItems[indexPath.row]
    let viewController = ItemDetailViewController(item: item, coder: creator)
    return viewController
}) {
    self.navigationController?.pushViewController(itemDetailVC, animated: true)
}
```

2023-02-24 02:38 UTC, seunghyunCheon commented on Expo1900/Expo1900/Controllers/KoreaItemsViewController.swift
> +        self.title = "한국의 출품작"
감사합니다!

2023-02-24 02:40 UTC, kak1x commented on Expo1900/Expo1900/Controllers/ItemDetailViewController.swift
> +    var itemData: ExpositionUniverselleItem?
커스텀 이니셜라이저를 사용하는 것으로 변경해주었습니다.

2023-02-24 02:42 UTC, kak1x commented on Expo1900/Expo1900/Controllers/KoreaItemsViewController.swift
> +}
에러를 유저도 확인할 수 있게 에러가 발생했을 시 데이터 로딩 실패라는 실패 alert창을 띄워주도록 변경하였습니다.

2023-02-24 02:42 UTC, kak1x commented on Expo1900/Expo1900/Controllers/ParisExpositionUniverselleViewController.swift
> +    }
JSONDecoderExtension 을 사용하여 JSON 파일을 디코딩 해주는 메서드를 공통화하였습니다.

2023-02-24 02:43 UTC, seunghyunCheon commented on Expo1900/Expo1900/Controllers/KoreaItemsViewController.swift
> +    private let cellIdentifier: String = "cell"
`reuseIdentifying`프로토콜을 확장해서 기본값으로 `reuseIdentifier`를 갖게 만들어, 이 프로토콜을 채택할 때마다 프로퍼티를 재정의 하는 작업이 없도록 만들었습니다.
```swift
// ExpositionTableViewCell.swift
extension ExpositionTableViewCell: ReuseIdentifying { }

// ReuseIdentifying.swift
protocol ReuseIdentifying {
    static var reuseIdentifier: String { get }
}

extension ReuseIdentifying {
    static var reuseIdentifier: String {
        return String(describing: self)
    }
}
```

2023-02-24 02:44 UTC, kak1x commented on Expo1900/Expo1900/Controllers/ParisExpositionUniverselleViewController.swift
> +        expositionDuration.attributedText = changeFont(expositionData.displayedDuration)
StringExtension 에서 attributedString 계산 속성을 정의해주어 변경하였습니다.

2023-02-25 10:50 UTC, havilog commented on Expo1900/Expo1900/Controllers/KoreaItemsViewController.swift
> +    }
`ItemDetailViewController`도 indentifier를 static하게 잡으면 좋을거 같아요

2023-02-25 12:02 UTC, havilog approved these changes
수고하셨습니다.
다음 단계 진행하셔도 될 거 같아요~!
머지 원하시면 말씀해주세요

2023-02-25 12:02 UTC, havilog commented on Expo1900/Expo1900/Views/ExpositionTableViewCell.swift
> +extension ExpositionTableViewCell: ReuseIdentifying { }
UITableViewCell 타입에 extension을 하면 각각 커스텀 셀마다 extension을 안해줘도 될거 같아요

2023-02-25 12:02 UTC, havilog commented on Expo1900/Expo1900/Views/ExpositionTableViewCell.swift
> +    @IBOutlet weak var itemSubtitleLabel: UILabel!
외부에서 셀의 데이터에 직접 접근하는건 위험해보여요.
`configure(with: item)`과 같은 함수로 변경하는건 어떨까요?

2023-02-25 12:02 UTC, havilog commented on Expo1900/Expo1900/Etc/Extension/StringExtension.swift
> +}
더 잘읽힐 수 있게 이런 방식으로 extension을 쓸 수 있지만, 
해당 파일이나 특정한 곳에서만 쓴다면 fileprivate으로 선언할 수도 있고,
여러군데에서 쓰고 테스트가 필요하다면 객체로 빼는것도 고려해보셔야해요

2023-02-25 12:02 UTC, havilog commented on Expo1900/Expo1900/Etc/Extension/JSONDecoderExtension.swift
> +        }
do-catch문은 필요하지 않아보여요

2023-02-25 12:02 UTC, havilog commented on Expo1900/Expo1900/Etc/Error/DataAssetError.swift
> +}
보통 에러도 Equatable하면 좋고, customStringConvertible하면 좋은 경우도 많은거 같아요

2023-02-25 12:02 UTC, havilog commented on Expo1900/Expo1900/Controllers/KoreaItemsViewController.swift
> +        if let itemDetailVC = storyboard?.instantiateViewController(identifier: "ItemDetailViewController", creator: { creator in
ItemDetailViewController도 cell처럼 static하게 접근할 수 있으면 좋을거 같습니다

2023-02-25 12:02 UTC, havilog commented on Expo1900/Expo1900/Controllers/KoreaItemsViewController.swift
> +        let item = expositionItems[indexPath.row]
subscript로 접근할 때 [safe:]와 같이 안전하게 접근하는 방법도 고려하면 좋을거 같아요

2023-02-27 06:25 UTC, kak1x commented on Expo1900/Expo1900/Etc/Extension/StringExtension.swift
> +}
테스트 측면에선 객체로 빼는 것이 좋고 특정한 곳에서만 쓴다면 fileprivate가 좋다고 생각하지만 리니어하게 사용하기 위해선 String에 확장해주는것이 좋다고 생각하여 수정하지 않았습니다.
하비가 말씀해주신 방법으로 수정하며 리니어하게 사용할 방법이 있을까요?

2023-02-27 06:25 UTC, seunghyunCheon commented on Expo1900/Expo1900/Controllers/KoreaItemsViewController.swift
> +    }
아래 코드처럼 `UITableViewController`에도 확장해서 사용해 identifier를 static하게 사용했습니다.
```swift
protocol Identifying {
    static var identifier: String { get }
}

extension Identifying {
    static var identifier: String {
        return String(describing: self)
    }
}

extension UITableViewCell: Identifying { }

extension UIViewController: Identifying { }
```

2023-02-27 06:26 UTC, kak1x commented on Expo1900/Expo1900/Etc/Extension/JSONDecoderExtension.swift
> +        }
throws 함수 내에서 try를 사용할 경우 do-catch 문을 사용해주지 않아도 에러를 던져주는군요! 좋은 지적 감사합니다🙂

2023-02-27 06:26 UTC, kak1x commented on Expo1900/Expo1900/Etc/Error/DataAssetError.swift
> +}
Equatable, customStringConvertible 프로토콜을 채택하여 수정해보았습니다.

2023-02-27 06:28 UTC, kak1x commented on Expo1900/Expo1900/Controllers/KoreaItemsViewController.swift
> +        if let itemDetailVC = storyboard?.instantiateViewController(identifier: "ItemDetailViewController", creator: { creator in
Identifying 프로토콜을 UIViewController 확장에 채택하여 static하게 접근할 수 있도록 수정하였습니다!

2023-02-27 06:28 UTC, kak1x commented on Expo1900/Expo1900/Controllers/KoreaItemsViewController.swift
> +        let item = expositionItems[indexPath.row]
Array에 확장으로 safe하게 접근하는 방식을 추가해주었습니다.

2023-02-27 06:31 UTC, seunghyunCheon commented on Expo1900/Expo1900/Views/ExpositionTableViewCell.swift
> +    @IBOutlet weak var itemSubtitleLabel: UILabel!
셀 내부에 아래 `configure` 함수를 정의해주었습니다. 
```swift
func configure(item: ExpositionUniverselleItem?) {
        guard let item = item else { return }
        
    itemImageView.image = UIImage(named: item.imageName)
    itemTitleLabel.text = item.name
    itemSubtitleLabel.text = item.shortDescription
}
```

2023-02-27 07:24 UTC, seunghyunCheon commented on Expo1900/Expo1900/Views/ExpositionTableViewCell.swift
> +    }
셀이 재사용될 때 이미지가 있어야할 곳이 아닌 다른 셀에 보여지는 경우를 고려해서 `prepareForReuse`메서드를 사용했습니다. 이렇게 사용해도 괜찮을까요?

2023-02-27 09:28 UTC, havilog commented on Expo1900/Expo1900/Views/ExpositionTableViewCell.swift
> +    }
ExpositionUniverselleItem이 optional이라면 괜찮을거 같은데,
ExpositionUniverselleItem이 없을 경우가 있을까요?
configure의 파라미터를 concrete하게 넣어주고, 각각의 uiproperty의 내용을 비워줘도 될거같아요

2023-02-27 09:29 UTC, havilog commented on Expo1900/Expo1900/Etc/Extension/StringExtension.swift
> +}
이 파일 자체가 사용되는 곳에서 fileprivate extension String으로 사용되는것을 말씀드린거였고,
readability를 선택할지 testability를 선택할지는 개발자의 몫일거 같아요

2023-02-27 09:29 UTC, merged