만국박람회 [Step2] Harry, 레옹아범
yagom-academy/ios-exposition-universelle pull request #245
Opened 2023-02-22 09:08 UTC by HarryHyeon

@AppleCEO 
안녕하세요 도미닉 !
Step2 구현을 완료했습니다.
이번에도 잘 부탁드리겠습니다 😄 

## 고민한점
### 중복되는 View재사용하기
- 첫번째 MainPoster뷰컨트롤러와, Detail뷰컨트롤러는 스크롤뷰를 사용함으로 이 부분이 중복되어 `CustomScrollView`를 만들어 해당 뷰를 재사용하도록 만들었습니다.

### TableViewController
- TableView를 만들 때 대부분의 예제들이 일반적인 ViewController를 상속받아 TableView를 뷰 안에 넣어주는 방식을 채택한걸 많이 봤습니다.
- TableView이외에 다른 뷰를 넣는다면 그런 방식이 조금 더 맞다고 생각하지만 저희 두번째 뷰 컨트롤러의 `ExhibitionEntryTableViewController`같은 경우 테이블 뷰만 존재하기 때문에 뷰 컨트롤러가 아닌 테이블 뷰 컨트롤러를 상속받도록 코드를 작성하였습니다.
- 테이블 뷰 컨트롤러를 상속받음으로 테이블 뷰에대한 오토레이아웃을 잡아주거나, `delegate`, `dataSource`에 뷰 컨트롤러를 위임해주는 등의 잡다한 코드가 사라졌습니다.

### makeKeyAndVisible()의 역할
- 코드로 UI를 작성할 때 `SceneDelegate.swift` 파일에서 사용한 메서드 입니다.
- 해당 윈도우를 `keyWindow`로 만들어 주는 메서드라는 것을 확인 했고 `keyWinodw`는 가장 앞쪽에 배치된 윈도우를 뜻합니다.

## 조언을 얻고 싶은 점

### ScrollView의 contentInset 사용

<img src="https://i.imgur.com/DPeqaIE.gif" width="200">

<br>

``` swift

// CustomScrollView.swift
class CustomScrollView: UIScrollView{
    private func configureStackView() {
        self.addSubview(stackView)

        let scrollContentGuide = self.contentLayoutGuide
        let scrollFrameGuide = self.frameLayoutGuide

        NSLayoutConstraint.activate([
            self.stackView.topAnchor.constraint(equalTo: scrollContentGuide.topAnchor),
            self.stackView.leadingAnchor.constraint(equalTo: scrollContentGuide.leadingAnchor),
            self.stackView.trailingAnchor.constraint(equalTo: scrollContentGuide.trailingAnchor),
            self.stackView.bottomAnchor.constraint(equalTo: scrollContentGuide.bottomAnchor),

            self.stackView.widthAnchor.constraint(equalTo: scrollFrameGuide.widthAnchor)
        ])

        self.contentInset.left = 15
        self.contentInset.right = 15
    }
}
```

- 첫번째 화면에서의 본문(TextView)를 보면 왼쪽과 오른쪽 끝에 여백이 있는 것을 보고 이를 구현하고자 했습니다.
- 지난번 프로젝트에서 ScrollView를 공부하다가 contentInset을 공식문서에서 본 기억이 있어서 한 번 사용하고자 시도 했습니다.
- 결과적으로 고정되어있던 좌우 스크롤이 양옆으로 움직이게 되었고, 여러가지 제약조건을 시도했지만 잘 해결되지 않아서 스크롤뷰의 컨텐트 뷰인 스택뷰의 마진을 주는 것으로 해결했습니다.
- 혹시 contentInset을 주게되면 content뷰의 size가 늘어나서 좌우 스크롤이 되는 것 일까요?
    - content뷰의 넓이 사이즈를 고정시켜 놓았는데, 좌우 스크롤 이동이 어떻게 가능한 것인지 의문입니다...
- 그리고 contentInset으로 해결할 수 있는 방법이 있는 방법이 있을지 여쭤보고 싶습니다 !

<br>

### JSONDecoder 실패시 에러처리방법
```swift
private func decodeJson() {
    let jsonDecoder = JSONDecoder()
    guard let data = NSDataAsset(name: "exposition_universelle_1900") else { return }
        
    do {
        mainPoster = try jsonDecoder.decode(MainPoster.self, from: data.data)
    } catch {
        print(error.localizedDescription)
    }
}
```

- Json파일이 없거나 코드 설계상 decoding이 실패할 시 저희는 catch문으로 단순히 에러를 출력하도록 만들었습니다.
- 하지만 JSON파일이 만약 실패하는 경우가 있다면 도미닉은 이 에러처리구문을 어떻게 작성하시는 편인가요?
- 예를들어 앱에 Alert를 띄어준다거나?, 기본이미지와 데이터를 생성하여 넣어주는 방식?을 사용하여 사용자에게 실패했다는 것을 보여주는게 맞을까요?

2023-02-22 13:31 UTC, AppleCEO requested changes
@HarryHyeon , @fatherLeon 
안녕하세요. 도미닉입니다.
이번 스텝도 굉장히 빠르게 잘 만들어주셨네요!
고생하셨습니다.
코멘트들 확인 부탁드려요~

# 조언
## ScrollView의 contentInset 사용
음.. contentInset 에 대해서 잘못 이해하신 부분이 있는 것 같은데요.
스텝을 일찍 마치셨으니 contentInset 에 대해서 조금 공부해보면 좋겠습니다.
다른 동료들도 이런 내용들에 대해서 잘 알지 못하고 있고 이 것이 있는지도 모르는 분들도 계실텐데 블로그를 작성하거나 내용을 정리해서 발표를 한다던지 해서 공유해보셔도 좋겠습니다.

## JSONDecoder 실패시 에러처리방법
오호... 좋은 관점이네요.
단순히 오류를 프린트하기보다는 스텝을 일찍 마쳤으니 사용자가 알아챌 수 있게 alert 을 표시해보는 것도 보너스로 진행해봐도 좋겠네요. 이런 비슷한 상황이 발생하는 여러 곳에서 alert 은 수시로 추가됩니다. 한번 연습해보셔도 좋을 것 같습니다!

2023-02-22 13:31 UTC, AppleCEO commented on Expo1900/Expo1900.xcodeproj/project.pbxproj
> +				C79FF4B82589F401005FB0FD /* MainPosterViewController.swift */,
뷰컨트롤러의 이름을 그대로 쓰지 않고 명확하게 어떤 화면인지 이름에서 드러나게 수정하신 부분 좋습니다! 💯

2023-02-22 13:31 UTC, AppleCEO commented on Expo1900/Expo1900/App/SceneDelegate.swift
> +//  Created by Harry, 레옹아범.
놓칠 수 있는 부분인데 이렇게 작성자의 이름을 바꿔준 것 좋네요~ 좋은 습관으로 유지하시면 좋겠습니다. 🥇

2023-02-22 13:31 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/MainPosterViewController.swift
> +    private var mainPoster: MainPoster? = nil
이름이 명확한 것 같아요! 🔢

2023-02-22 13:31 UTC, AppleCEO commented on Expo1900/Expo1900/Model/MainPoster.swift
> +    private let duration: String
접근제어자를 설정한 부분 좋네요~ 👍

2023-02-22 13:31 UTC, AppleCEO commented on Expo1900/Expo1900/Model/ExhibitionItem.swift
>  struct ExhibitionItem: Decodable {
Decodable 말고 이 곳에 더 범용적으로 쓰이는 프로토콜이 있는데요. 
그 것에 대해서 공부해보고 어떤 차이가 있을지 고민해보시면 좋겠습니다~

2023-02-22 13:31 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/ExhibitionEntryTableViewController.swift
> +        cell.contentLabel.text = data.shortDescription
이렇게 셀의 각 요소에 일일이 데이터를 직접 넣어주는 것은 이 테이블뷰가 ExhibitionEntryCell 의 프로퍼티를 일일이 알아야합니다.
혹시 cell 에 data를 넘겨주면 cell 안 에서 스스로 뷰를 그리는 방식으로 개선해 볼 수 있을까요?

2023-02-22 13:31 UTC, AppleCEO commented on Expo1900/Expo1900/View/ExhibitionEntryCell.swift
> +class ExhibitionEntryCell: UITableViewCell {
테이블 뷰는 계속 새로 만들어지지 않고 재사용되는데요.
재사용 될 때 기존에 들어있던 내용들이 남아있게 됩니다.
재사용이 될 때 실행되는 함수를 찾아보고 그 함수에서 내용을 비워주는 기능을 추가해 볼 수 있을까요?
혹시 셀이 다시 보여질 때 내용을 바꾸지 않은 것이 있으면 잘못된 데이터가 보여질 수 있기 때문입니다.

2023-02-23 11:26 UTC, fatherLeon commented on Expo1900/Expo1900/View/ExhibitionEntryCell.swift
> +class ExhibitionEntryCell: UITableViewCell {
```swift
class ExhibitionEntryCell: UITableViewCell {
    override func prepareForReuse() {
        super.prepareForReuse()
        
        self.data = nil
    }
}
```

* 위 `prepareForReuse`메소드를 통해 이전 셀을 재사용하기위해 불러오면 이전 데이터를 초기화 하도록 만들었습니다.
* cell의 `data`프로퍼티가 프로퍼티옵저버이며, 옵셔널 값이기 때문에 nil로 할당하여 `data`의 값만 바꾸는게 아닌 `titleLabel`, `contentLabel`, `exhibitionImage`까지 전부 바뀌도록 만들었습니다.

2023-02-23 11:26 UTC, HarryHyeon commented on Expo1900/Expo1900/Controller/ExhibitionEntryTableViewController.swift
> +        cell.contentLabel.text = data.shortDescription
``` swift
// ExhibitionEntryCell.swift

var data: ExhibitionItem? {
        didSet {
            self.exhibitionImage.image = data?.image
            self.titleLabel.text = data?.name
            self.contentLabel.text = data?.shortDescription
        }
    }
```
셀 외부에서 접근할 수 있는 data 라는 프로퍼티 옵저버를 두고,
data가 set 되면 cell 내부의 콘텐츠들을 업데이트 하도록 수정하였습니다 !

2023-02-23 11:45 UTC, HarryHyeon commented on Expo1900/Expo1900/Model/ExhibitionItem.swift
>  struct ExhibitionItem: Decodable {
## Codable

<img src="https://i.imgur.com/2ada7UK.png" width="700">

- Codable은 Decodable과 Encodable을 모두 채택하는 타입의 별칭입니다.

## Encodable
- Encodable을 채택한 객체를 JSON이나 다른 포멧의 데이터로 변환하는 작업을 수행하기 위한 프로토콜 입니다.

## Decodable
- Json 혹은 다른 형식의 데이터를 우리가 원하는 타입으로 만들 수 있게끔 도와주는 타입입니다.

## 결론
- Codable을 채택할 경우 다른 형태의 파일(ex.Json, XML)을 인코딩 하거나 아니면 다른 형태의 파일을 원하는 Data로 디코딩하는 타입이라는 것을 명확히 알려줄 수 있습니다.
- 그러나 저희 코드와 같이 Decodable만 채택할 경우 다른 형태의 파일을 decoding만 한다는 것을 코드를 통해 확실히 다른사람에게 알려줄 수 있습니다.

2023-02-28 09:21 UTC, merged