만국박람회 [STEP2]
yagom-academy/ios-exposition-universelle pull request #247
Opened 2023-02-23 05:35 UTC by sehoong0429

@1consumption
안녕하세요 올라프! 세홍, 무리, 송준 조의 2번째 스텝 PR입니다!
이번 리뷰도 잘부탁드립니다. 감사합니다😁

## 고민했던 부분

### 1️⃣ 상세정보 페이지에 데이터 전달하기
- 한국의 출품작 목록을 나타내는 뷰컨트롤러에서 셀(출품작)을 선택하게되면 출품작의 상세정보를 보여주는 페이지를 나타내주어야했습니다.  
처음엔 `Decoder`를 이용하여 한 번 더 데이터를 파싱해오는 방법을 생각했는데, `Segue`를 이용하여 데이터를 넘기는 방법이 생각 나 이용해보았습니다. 
- `prepare()`메소드를 이용하여 데이터를 넘겨받을 뷰컨트롤러를 설정 한 후 현재 뷰컨트롤러의`cell`이 가지고있는 데이터를 다음뷰컨트롤러의 전역변수에 담아 사용해보았습니다.

### 2️⃣ 구조체 내에서 `read-only computed property`
>구조체 내에서 아래 예시와 같이 저장 프로퍼티를 통해 `init()`되지 않은 `visitors`프로퍼티를 다른 저장 프로퍼티에 담으려고 할 때 이러한 오류 메시지가 나옵니다. 저장 프로퍼티 안에 값이 초기화되지 않은 상태에서 다른 저장 프로퍼티에 담으려고 하여 오류가 발생된거 같습니다.
<img width="532" alt="image" src="https://user-images.githubusercontent.com/88870642/220825662-6e9468f9-940d-4d41-b3b4-9cd47de5b872.png">

 - 변경 전
 ```swift
struct Exposition: Decodable {
    let visitors: Int
    
    var visitorLabelText: String = "방문객 : \(visitors.setDecimal()) 명"
}
```
</br>

>위 문제를 해결하기 위해 연산 프로퍼티를 사용했습니다. 연산 프로퍼티의 경우 구조체가 인스턴스되고 난 이후에 호출이 가능하기 때문에 구조체가 인스턴스되는 과정에서 저장 프로퍼티의 값이 초기화되어 사용이 가능하다고 이해했습니다. 올바르게 이해한걸까요?? 
- 변경 후
```swift
struct Exposition: Decodable {
    let visitors: Int

    var visitorLabelText: String {
        return "방문객 : \(visitors.setDecimal()) 명"
    }
} 

```

## 조언을 얻고싶은 부분

### 1️⃣ 오토레이아웃

오토레이아웃을 코드로 작성하는 방법, mainStoryBoard에서 작성하는 방법이 있는 걸로 알고 있습니다. 저희는 mainStoryBoard에서 오토레이아웃을 설정했는데 프로젝트를 진행하면서 같은 방식으로 컨트롤러에 scrollView를 그리더라도 버그가 생겨서 scroll을 그리지 못하거나 text가 짤리는 경우가 있었습니다.(같은 방식으로 잘못했으니 오류가 발생했겠죠ㅠㅠ) 그래서 차라리 오토레이아웃을 코드로 작성하면 어떨까 생각을 했는데, 오토레이아웃을 코드로 작성하는 걸 보니 너무 양이 많아서 관리가 오히려 쉬운게 아닐거같다는 생각이 들었습니다! 올라프는 어떤방식으로 오토레이아웃을 설정하는게 좋다고 생각하시는지 조언받고 싶습니다. 

### 2️⃣ 다음 viewController로 선택된 셀의 데이터를 넘기고 이동하는 방식 
secondViewController에서 해당 cell의 작품을 상세보기 할 수 있는 화면으로 이동됩니다. 현재 프로젝트에서는 `segue`를 통해 다음 뷰 컨트롤러로 이동하기 전 데이터를 사용하는 함수를 사용해 다음 보여줘야할 뷰 컨트롤러에서 해당 cell 작품에 대한 데이터를 사용할 수 있는 방식으로 진행했습니다. tableView에서는 `tableView(_: didSelctRowAt)`메서드를 사용해서 사용자가 셀을 선택할때 호출되는 콜백함수를 구현하고 해당 셀에 대한 정보를 다음 뷰 컨트롤러로 전달 할 수 있다하는데 어떤 방식으로 구현하는게 효율적인지 조언받고싶습니다.   

### 3️⃣  테이블뷰 셀의 높이
<img src="https://i.imgur.com/Q6dtIkl.png" width="300">
<img src="https://i.imgur.com/svx2tOS.png" width="300">
위 스크린샷과 같이 해금처럼 셀의 높이가 비약적으로 큰 친구가 생겼습니다😥.. 테이블뷰셀에 이미지가 영향이 있는 것 같은데... 셀 안에서의 이미지 오토레이아웃을 좀더 활용하게되면 이와같은 문제를 해결할 수 있을까요? 혹은 어떠한 부분을 보면 좋을지 조언부탁드립니다!

2023-02-23 16:26 UTC, 1Consumption requested changes
안녕하세요 @sehoong0429 @parkmuri @kimseongj 

고민이 많이 느껴지는 코드였습니다.
또한 가독성도 좋아서 읽기 좋았습니다.

다만 몇가지 아쉬운 점이 있었는데, 아래에 코멘트로 남기겠습니다.

----------------------------

`SecondViewController UI 수정`, `ItemDetailViewController UI 수정`, `SecondViewController UI 변경` 이런 이름 보다는 조금 더 구체적이면 좋겠습니다.

----------------------

<img width="255" alt="image" src="https://user-images.githubusercontent.com/37682858/220955496-83e26d18-060c-40d4-a207-4e01410f8fe9.png">

`Assets` 는 view인가요?

------------------------------

아래는 고민하신 점에 대한 제 코멘트입니다.

### 2️⃣ 구조체 내에서 `read-only computed property`
구조체 내에서 아래 예시와 같이 저장 프로퍼티를 통해 `init()`되지 않은 `visitors`프로퍼티를 다른 저장 프로퍼티에 담으려고 할 때 이러한 오류 메시지가 나옵니다. 저장 프로퍼티 안에 값이 초기화되지 않은 상태에서 다른 저장 프로퍼티에 담으려고 하여 오류가 발생된거 같습니다.

```
연산프로퍼티는 초기화된 저장프로퍼티를 계산하는 프로퍼티니까 항상 초기화가 된 이후에 불린다는 보장이 있습니다.
```

### 1️⃣ 오토레이아웃

오토레이아웃을 코드로 작성하는 방법, mainStoryBoard에서 작성하는 방법이 있는 걸로 알고 있습니다. 저희는 mainStoryBoard에서 오토레이아웃을 설정했는데 프로젝트를 진행하면서 같은 방식으로 컨트롤러에 scrollView를 그리더라도 버그가 생겨서 scroll을 그리지 못하거나 text가 짤리는 경우가 있었습니다.(같은 방식으로 잘못했으니 오류가 발생했겠죠ㅠㅠ) 그래서 차라리 오토레이아웃을 코드로 작성하면 어떨까 생각을 했는데, 오토레이아웃을 코드로 작성하는 걸 보니 너무 양이 많아서 관리가 오히려 쉬운게 아닐거같다는 생각이 들었습니다! 올라프는 어떤방식으로 오토레이아웃을 설정하는게 좋다고 생각하시는지 조언받고 싶습니다. 

```
스크롤뷰는 다른 뷰와 다르게 제약을 주는 방법이 조금 다릅니다. 이 부분은 조금 더 공부를 해보시면 좋을듯 합니다.
저는 아래와 같은 이유로 스토리보드보다는 코드를 선호합니다.
1. 스토리보드를 열기만해도 변경 사항이 발생한다.
2. 컨플릭이 발생했을 때 해결하기 어렵다.
3. 코드리뷰할 때 읽을수가 없다.(깃헙에서는 인터페이스빌더가 없으니 XML을 읽어야하는데, 읽기 매우 어렵죠)
```

### 2️⃣ 다음 viewController로 선택된 셀의 데이터를 넘기고 이동하는 방식 
secondViewController에서 해당 cell의 작품을 상세보기 할 수 있는 화면으로 이동됩니다. 현재 프로젝트에서는 `segue`를 통해 다음 뷰 컨트롤러로 이동하기 전 데이터를 사용하는 함수를 사용해 다음 보여줘야할 뷰 컨트롤러에서 해당 cell 작품에 대한 데이터를 사용할 수 있는 방식으로 진행했습니다. tableView에서는 `tableView(_: didSelctRowAt)`메서드를 사용해서 사용자가 셀을 선택할때 호출되는 콜백함수를 구현하고 해당 셀에 대한 정보를 다음 뷰 컨트롤러로 전달 할 수 있다하는데 어떤 방식으로 구현하는게 효율적인지 조언받고싶습니다.   

```
저는 tableView(_:didSelectRowAt:)를 선호합니다. 탭된 셀에 대한 indexPath를 알 수 있어서 더 확장성 있는 작업이 가능하기 때문입니다.
```

### 3️⃣  테이블뷰 셀의 높이
<img src="https://i.imgur.com/Q6dtIkl.png" width="300">
<img src="https://i.imgur.com/svx2tOS.png" width="300">
위 스크린샷과 같이 해금처럼 셀의 높이가 비약적으로 큰 친구가 생겼습니다😥.. 테이블뷰셀에 이미지가 영향이 있는 것 같은데... 셀 안에서의 이미지 오토레이아웃을 좀더 활용하게되면 이와같은 문제를 해결할 수 있을까요? 혹은 어떠한 부분을 보면 좋을지 조언부탁드립니다!

```
오토레이아웃은 스텝3에서 다루도록하죠.
```

------------------------------------------------------------

코멘트 관련해서 구두로 얘기를 하고싶다면 디스코드를 통해 일정을 잡아주시면 좋겠습니다. 언제나 환영합니다!

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/App/AppDelegate.swift
> +
이 변경사항은 뭔가요?

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +    @IBOutlet weak var listTableView: UITableView!
외부에서 알아야하는 변수인가요?

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +                                                 action: nil)
추상화 레벨이 맞으면 좋겠습니다. 어디는 메소드인데, 어디는 바로 코드를 실행하네요.

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +    }
이부분을 view에서 알아야하나요? 저라면 이 동작을 추상화한 객체를 만들어서 view에서 사용할거같아요.

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        self.listTableView.reloadData()
멤버 변수에 접근할 때 어디는 self가 붙고 어디는 self가 붙지 않네요. 기준이 있을까요?

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +            print(error.localizedDescription)
지금 코드에서 만약 json decoding에 실패하면 사용자는 에러 상황을 인지할 수 있나요?

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        guard let cell: ListTableViewCell = sender as? ListTableViewCell else { return }
굳이 guard문을 두개로 나눈 이유가 있을까요?
```suggestion
        guard let nextViewController: ItemDetailViewController = segue.destination as? ItemDetailViewController,
                   let cell: ListTableViewCell = sender as? ListTableViewCell else { 
                   return 
        }
```

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        nextViewController.expoItemImage = cell.expoImageName
이 정보를 묶어서 한번에 설정할수는 없을까요? 추상화가 되면 좋겠습니다.

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +extension ExpoItemListViewController: UITableViewDataSource, UITableViewDelegate {
`UITableViewDelegate`를 채택한 이유가 있을까요?

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        cell.expoShortDescriptionLabel.numberOfLines = 0
numberOfLines는 꼭 외부에서 지정해줘야하나요? 이건 내부에서 해도 될거같습니다.

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        cell.expoImageName = self.expoItems[indexPath.row].imageName
cell에 정보를 configure하는 메소드가 하나 있으면 좋겠습니다. 매개변수로는 `expoItem`만 받고 내부에서 뷰에 뿌려주는거죠.

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        guard let nextViewController: ItemDetailViewController = segue.destination as? ItemDetailViewController else { return }
override 메소드인데 super를 호출하지 않은 이유가 있을까요?

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ItemDetailViewController.swift
> +    var expoItemDescription: String?
위에서 드린 코멘트를 반영한다면 외부에서 몰라도 되는 변수 같습니다.

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    @IBOutlet weak var posterImageView: UIImageView!
`@IBOutlet`으로 선언된 변수들은 왜 기본이 weak일까요?

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    }
여기서 super를 호출하지 않은 이유가 있을까요?

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/testViewController.swift
> +}
이건 어떤 클래스인가요?

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Extension/Int+Extension.swift
> +    }
값을 바꾸는 메소드가 아니라 반환하는 메소드인데, set이 들어가는게 어색하다고 생각합니다.

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Models/Exposition.swift
> +    }
이거는 모델 컨테이너 객체에서 할 일이 아니라, 사용하는데서 추가하는게 더 맞아보입니다.

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +final class ExpoItemListViewController: UIViewController {
final은 왜 붙이셨나요?

2023-02-23 16:26 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        guard let nextViewController: ItemDetailViewController = segue.destination as? ItemDetailViewController else { return }
`nextViewController`보다는 `어떤`이 들어간 구체적인 이름이면 좋겠습니다.

2023-02-24 02:50 UTC, parkmuri commented on Expo1900/Expo1900/App/AppDelegate.swift
> +
- 미처 확인하지 못한 실수네요 👀...! 실수로 엔터를 잘못친것같습니다😥 
수정했습니다!

~~중간에 Pull하지않고 진행하는바람에 오류가있어 커밋이 살짝 꼬이게되었습니다...~~

471e57385fe339a5f2777b95e74c012e91e4999c

2023-02-24 03:05 UTC, parkmuri commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        self.listTableView.reloadData()
- `self` 키워드를 제대로 이해하지 못하고 사용해서 발생한 오류입니다.
> `self`를 이용하여 구조체나 클래스의 `인스턴스`에 속하는 `프로퍼티`에 접근할수 있습니다. 클래스 내부에서는 어느 인스턴스에 속하는 프로퍼티인지 알기 어려워 사용합니다. 또 생략하여 사용 가능하지만 인스턴스 프로퍼티와 변수명이 같을 경우 구분을 위해 사용해준다고 이해했습니다. 

- `self`를 생략 가능할때는 생략을 하는게 맞다고 생각하는 팀원이 있고, 명확하게 표시를 하기 위해 `self`를 사용해야한다는 팀원의 의견이 갈리는데 올라프는 어떻게 생각하시나요?

2023-02-24 03:10 UTC, kimseongj commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +    @IBOutlet weak var listTableView: UITableView!
외부에서 알 필요가 없는 변수같군요! 꼼꼼히 확인하지 못했던거 같습니다😅
수정했습니다!

c238f880bc3093edaf73293fc55dc03c647c63c1

2023-02-24 03:15 UTC, parkmuri commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +                                                 action: nil)
- `setNavigationBar()`라는 메서드를 만들어 메서드를 호출하는 방향으로 추상화레벨을 맞추어보았습니다.

234ec6f6a82268d7ff48f7a74297d7de93b876a6

2023-02-24 03:41 UTC, kimseongj commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +    }
올라프의 코멘트를 보고 고민을 많이 했습니다.
뷰는 UI를 그리는 기능만 하는것이라 생각됩니다! 그래서 decode하는 부분을 따로 클래스로 만들어 정의했습니다! 올라프가 의도를 제대로 이해한 것인지 궁금합니다!

6d8bb350fc39d902a599f66366ec2cb1d11bc486

2023-02-24 05:17 UTC, parkmuri commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        guard let cell: ListTableViewCell = sender as? ListTableViewCell else { return }
- `segue`에 대한 부분을 먼저 선언해놓은 후에 `cell`을 선언하여 따로 쓰게된것같습니다! 코멘트 참고하여 수정하였습니다!

e0754babeaa98c5a392575db2e11412d22d69129

2023-02-24 05:26 UTC, kimseongj commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        nextViewController.expoItemImage = cell.expoImageName
하나의 메서드에 묶어서 수정했습니다!

7904db2e592d5eff3aee28da8b09d199f5750825

2023-02-24 05:29 UTC, parkmuri commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +extension ExpoItemListViewController: UITableViewDataSource, UITableViewDelegate {
- TableView 구성 시 Delegate 기능도 쓸것같아 미리 선언해놓았던 것이 문제였던것같습니다.
현재 `ExpoItemListViewController`에서 `UITableViewDelegate`의 기능을 사용하지 않고 있기 때문에 삭제하였습니다!

2023-02-24 06:49 UTC, sehoong0429 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    }
올라프가 말씀해주신대로 super를 호출하지 않은 경우, 부모 클래스에서 구현한 로직이 실행되지 않으므로, 예기치 않은 동작이 발생할 수 있다는 것을 알게되었습니다. 예를 들어서 다른 뷰 컨트롤러로 전환하거나 앱을 종료할 때 네비게이션 바가 보이지 않는 상태로 남아있을 수 있기때문에 super를 호출하는 코드를 추가해주었습니다.

2023-02-24 06:50 UTC, sehoong0429 commented on Expo1900/Expo1900/Controller/testViewController.swift
> +}
해당 파일은 저희가 실수로 삭제하지 못한 파일 같습니다. 삭제완료했습니다.
꼼꼼하게 알려주셔서 감사합니다.

2023-02-24 06:51 UTC, sehoong0429 commented on Expo1900/Expo1900/Extension/Int+Extension.swift
> +    }
해당 함수는 decimal로 변환시켜준다는 의미로 convertDecimal로 변경하였습니다.

2023-02-24 06:57 UTC, sehoong0429 commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +final class ExpoItemListViewController: UIViewController {
final 키워드를 사용하는 이유는 다른 클래스에서 해당 클래스를 상속하거나 오버라이딩을 하지 않아 final 키워드를 사용해서 코드의 의도를 명확하게 하기 위함과 불필요한 객체 생성을 방지하여 프로그램의 실행 속도를 높여 성능향상의 이유를 찾아보고 사용하게 되었습니다.

2023-02-24 06:58 UTC, sehoong0429 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    @IBOutlet weak var posterImageView: UIImageView!
IBOutlet으로 선언된 변수들은 주로 UI 요소와 관련이 있고 해당 요소들은 View Controller의 자식 요소로 추가된다고 합니다. 이 View Controller는 자식 요소들을 강한 참조로 가지고 있어야 합니다. 그렇지 않으면, 자식 요소가 제거될 때 자동으로 해제되지 않고 계속 메모리에 남아 메모리 누수가 발생할 수 있습니다. 따라서 IBOutlet으로 선언된 변수들은 기본적으로 weak 참조로 선언됩니다. 
weak 참조는 참조 대상이 해제되면 자동으로 nil 값으로 초기화되기에메모리 누수를 방지할 수 있어서 기본이 weak인걸로 알고 있습니다.

2023-02-24 07:03 UTC, sehoong0429 commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        guard let nextViewController: ItemDetailViewController = segue.destination as? ItemDetailViewController else { return }
UIViewController의 메서드인 prepare(for:sender:)를 오버라이드 하는데 
 prepare 메서드는 UIViewController의 뷰 전환이 일어나기 전에 호출되는 메서드고 
 다음 뷰 컨트롤러로 데이터를 전달하는 작업 등을 수행할 때 사용됩니다! 

prepare(for:sender:) 메서드는 기본적으로 아무 작업도 수행하지 않는 빈 구현체이기때문에 
해당 메서드를 오버라이드하여 구현할 때, super를 호출하지 않아도 된다고 알고 호출하지 않았습니다!

2023-02-24 07:09 UTC, sehoong0429 commented on Expo1900/Expo1900/Models/Exposition.swift
> +    }
해당부분은 namespace를 활용하여 구현하는 방법으로 수정하였습니다.

2023-02-24 09:26 UTC, sehoong0429 commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        guard let nextViewController: ItemDetailViewController = segue.destination as? ItemDetailViewController else { return }
`itemDetailViewController`로 수정 완료하였습니다.

2023-02-27 05:17 UTC, sehoong0429 commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        cell.expoShortDescriptionLabel.numberOfLines = 0
해당 부분 의논한 결과 step3에서 오토레이아웃코드 작성해서 진행할때 다시 설정하는 방향으로 수정하기로 하였습니다.

2023-02-27 05:18 UTC, sehoong0429 commented on Expo1900/Expo1900/Controller/ItemDetailViewController.swift
> +    var expoItemDescription: String?
해당 부분은 말씀해주신대로 반영하고 접근 제어자 private으로 수정하였습니다.

2023-02-27 05:18 UTC, parkmuri commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        cell.expoImageName = self.expoItems[indexPath.row].imageName
- 올라프가 주신 코멘트 참고하여 ListTableViewCell 타입에 `configure(expoItem)` 메서드 생성하여 셀 내부에서 뷰의 값을 설정할 수 있게 수정해보았습니다.

29491ae8a9a5a4d8f80bee52cb534b99d38af6b5

2023-02-27 05:18 UTC, kimseongj commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +            print(error.localizedDescription)
사용자는 에러 상황을 인지할 수 없습니다. 이를 해결하기 위해 파싱실패 시 Alert 창을 띄우는 방법을 채택했습니다!

006aaacd268edf0df1573356ea75fe18d7575298

2023-02-27 14:40 UTC, 1Consumption approved these changes
고생하셨습니다. 다음 스텝을 진행하세요

2023-02-27 14:40 UTC, 1Consumption commented on Expo1900/Expo1900/Models/ExpoItemDecoder.swift
> +    }
여기서 직접 알러트를 띄우기보단 throws를 해서 사용하는 곳에서 에러처리를 하는게 좋아보입니다.

2023-02-27 14:41 UTC, merged