만국박람회 [STEP 2] vetto, goat
yagom-academy/ios-exposition-universelle pull request #248
Opened 2023-02-23 06:01 UTC by gzzjk159

안녕하세요! 
@July911
step2 PR 보내겠습니다! 
이번에도 좋은 피드백 부탁드겠습니다.😀

## 고민했던 부분

### 1. tableView cell 오토레이아웃
<img src="https://i.imgur.com/K64E4fp.png" width="40%" height="30%"/>

* 다음스텝에서 고민해볼 문제인거같긴한데 오토레이아웃 적용중 해결하지못한 부분이 있었습니다. textLabel을 cell안에서 오토레이아웃 적용시 적용한 constants만큼 cell과의 거리를 유치한채로 텍스트가 보이고 cell이 늘어나야 정상이라고 생각되는데, Lines를 0으로 조정했음에도 텍스트가 계속늘어나지않고 **cell의 범위안에서 잘리는 현상**이 계속됬습니다.
    * [Q1] 텍스트의 사이즈를 줄여서 cell범위안에 넣는건 잘못된 해결책인거같고, **cell의 크기자체가 안에 컨텐츠에 따라서 유동적으로 변해야**하는데 이부분 해결점을 아직 찾지못헀습니다.

### 2. ExpositionListViewController에서 DetailViewController로 데이터 전달
* tableview에서 cell을 눌렀을 때 `didSelectRowAt` 화면이 이동하는 것을 구현하였지만 화면을 이동할때 데이터를 전달 하는 것은 실패하였습니다. 

수정 전
```swift
func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    listTableView.deselectRow(at: indexPath, animated: true)
    guard let detailVC = self.storyboard?.instantiateViewController(withIdentifier: Identifier.detailViewController) as? DetailViewController else { return }
        
    detailVC.itemImage.image = UIImage(named: expositionLisnt[indexPath.row].imageName)
    detailVC.itemDescription = expositionList[indexPath.row].description
    detailVC.navigationItem.title = expositionList[indexPath.row].name
        
    let backBarButtonItem = UIBarButtonItem(title: Title.itemsOfKorea, style: .plain, target: DetailViewController.self, action: nil)
        
    self.navigationItem.backBarButtonItem = backBarButtonItem
    self.navigationController?.pushViewController(detailVC , animated: true)
    }
```

수정 후
```swift
func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    listTableView.deselectRow(at: indexPath, animated: true)
    guard let detailVC = self.storyboard?.instantiateViewController(withIdentifier: Identifier.detailViewController) as? DetailViewController else { return }
        
    detailVC.imageString = expositionList[indexPath.row].imageName
    detailVC.fullDescription = expositionList[indexPath.row].description
    detailVC.navigationItem.title = expositionList[indexPath.row].name
        
    let backBarButtonItem = UIBarButtonItem(title: Title.itemsOfKorea, style: .plain, target: DetailViewController.self, action: nil)
        
    self.navigationItem.backBarButtonItem = backBarButtonItem
    self.navigationController?.pushViewController(detailVC , animated: true)
    }
```

* 수정 전에는 didSelectRowAt을 통해 DetailViewController의 IBOutlet으로 데이터를 직접 넣어주려고 하였습니다만 데이터가 잘 적용되지않아 고민했습니다. 검색을 하여 찾은 방법으로는 string을 가지는 변수를 DetailViewController클래스 안에 선언 한 후 이 변수에 json data를 전달한 후 viewdidload에서 호출하여 넣어주는 방식이었습니다.
* 문제자체는 해결했지만 이러한 방식은 불필요한 String변수를 만들게되서 비효율적이라고 생각되는데 어떻게 하면 좋을까요?

2023-02-23 09:14 UTC, July911 requested changes

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/TextEnum.swift
> +}
Enum으로 String관리해주시는거 좋네요.

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/MainViewController.swift
> +        guard let expositionText = exposition?.description else { return }
하나라도 없으면 아무것도 안나오나요 ?

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/MainViewController.swift
> +        self.navigationController?.pushViewController(expoListVC , animated: true)
다음화면에 백버튼을 미리 정해주신 느낌이네요.

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/MainViewController.swift
> +    var exposition: MainExposition?
외부에서 사용할 일이 있는 프로퍼티일까요 ?

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/MainViewController.swift
> +
JSON데이터를 받는게 아니라 expo데이터를 받는거 아닌가요 ? 
파일의 형식을 받는다는게 아니라 원하는 정보를 받는다가 자연스러운거 같습니다.

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/ExpositionListViewController.swift
> +        listCell.expositionImage.image = UIImage(named: expositionList[indexPath.row].imageName)
setupLabel 이라고 메인뷰컨에서 선언해주신 메소드 방식이 있었던 것 같습니다. 
인터페이스로 소통하는 방식으로 수정해주세요. 
mainTitle의 모든 권한을 넘겨준 것 같습니다.

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/ExpositionListViewController.swift
> +        detailVC.imageString = expositionList[indexPath.row].imageName
많이 사용할 것이라면, indexPath.row를 상수로 선언해주셔도 좋을 것 같습니다.

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/ExpositionListViewController.swift
> +        self.navigationController?.isNavigationBarHidden = false
굳이 VC 생명주기를 나눠주신 이유가 궁금합니다.

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/DetailViewController.swift
> +    var fullDescription: String = ""
""이 의미하는게 무엇일까요 ?

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/MainViewController.swift
> +
JSONDecoder가 무엇을 하는 객체인가요 ?

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/MainViewController.swift
> +        } catch {
do catch는 언제 사용하나요 ?

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/ListTableViewCell.swift
> +class ListTableViewCell: UITableViewCell {
상속의 여지가 있을까요 ?

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/ListTableViewCell.swift
> +    }
언제 사용하는 메서드인가요 ? 오버라이드가 뭘까요 ?

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/ExpositionListViewController.swift
> +
as! 를 풀기위해선 어떤 방식을 사용해야할까요 ? as?의 차이와 is와의 차이는 무엇일까요 ?

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/MainViewController.swift
> +//
수정이 필요해보이네요.

2023-02-23 09:14 UTC, July911 commented on Expo1900/Expo1900/MainViewController.swift
> +    }
super. 콜은 필요없나요 ?

2023-02-23 09:20 UTC, July911 commented
커밋을 세세하게 나누신 점과 최대한 페어로 하시려고 하신점이 너무 좋았습니다. 
코멘트에 모두 답변해주시면, 수정사항 확인하고 머지하겠습니다 ! 
(레이아웃 부분은 제외입니다.) 
1. tableView cell 오토레이아웃 
->
이미지의 위아래 제약을 주고 셀을 넣어서 그런 것 같습니다. 아래 설명문구가 길어져도 이미지에 제약이 잡혀있어서 안먹는 현상이구요. 
AutomaticDimension에 대해서도 알아보시면 좋을 것 같습니다. 
추가적으로 스택뷰의 사용 역시도 고민해보셨으면 좋겠습니다. 꼭 

2. ExpositionListViewController에서 DetailViewController로 데이터 전달
-> 저라면 옵셔널을 사용할 것 같네요. 지금은 너무 어색한 느낌입니다.

2023-02-23 09:26 UTC, July911 commented on Expo1900/Expo1900/MainExposition.swift
>      let visitors: Int
visitor 배열이 들어가야 할 것 같은 네이밍입니다 !

2023-02-23 09:26 UTC, July911 commented on Expo1900/Expo1900/ListTableViewCell.swift
> +    @IBOutlet weak var shortDescription: UILabel!
MainViewController 에서는 Label로 통일해주셨던 네이밍이 여기선 아니네요.

2023-02-24 01:11 UTC, Goatt8 commented on Expo1900/Expo1900/MainViewController.swift
> +        guard let expositionText = exposition?.description else { return }
아 이부분은 불필요하게 바인딩이 많은거 같아서 exposition자체를 바인딩해주는 식으로 수정했습니다!
```swift
guard let exposition = exposition else { return }
        mainTitleLabel.text = exposition.title
        visitorsLabel.text = "방문객 : \(exposition.visitors)"
        locationLabel.text = "개최지 : \(exposition.location)"
        durationLabel.text = "개최 기간 : \(exposition.location)"
        textLabel.text = exposition.description```

2023-02-24 01:18 UTC, gzzjk159 commented on Expo1900/Expo1900/MainViewController.swift
> +    var exposition: MainExposition?
외부에서 사용하지 않는 변수라 생각하여 private를 붙여 외부에서 접근하지 못하도록 하였습니다. eb43f22e267822f65196640d6b3c7372c4a682ff

2023-02-24 01:23 UTC, Goatt8 commented on Expo1900/Expo1900/MainViewController.swift
> +
json데이터 형식으로 묶여있는 것을 가져온다는 의미에서 그렇게 적었던것같습니다ㅎ
`fetchExpositionData`로 매서드명을 수정했는데
혹시 get은 매서드명 앞에 사용할때 지양하는게 맞을까요?

2023-02-24 01:37 UTC, gzzjk159 commented on Expo1900/Expo1900/ExpositionListViewController.swift
> +        listCell.expositionImage.image = UIImage(named: expositionList[indexPath.row].imageName)
setup메서드를 만들어서 함수를 만들어서 함수로 text, image등을 변경하게 해주었습니다. 662e0858d99dda25e4753190e7ca67e92942321c
mainTitle의 모든 권한을 넘겨주었다는 말이 이해가 잘 가지 않는데 어떤 말일까요?

2023-02-24 01:37 UTC, Goatt8 commented on Expo1900/Expo1900/ExpositionListViewController.swift
> +        self.navigationController?.isNavigationBarHidden = false
아 viewDidLoad쪽에서 네비게이션 바를 숨기는 매서드를 구현시, 화면을 이동하고 다시 돌아왔을때 해당 매서드가 작동하지않는다는 문제가있었습니다. 화면이 전환되더라도 항상 유지되어야하는 매서드여서 viewWIllAppear 쪽에 구현했었습니다!

2023-02-24 01:45 UTC, Goatt8 commented on Expo1900/Expo1900/DetailViewController.swift
> +    var fullDescription: String = ""
이니셜라이징이 필요하다고 생각해서 빈스트링값을 넣어주었는데 옵셔널 처리하는게 더 효율적인 방법인것같습니다
```swift
var imageString: String?
var fullDescription: String?
guard let imageString = imageString, let fullDescription = fullDescription else { return }
```
따라서 위와같이 옵셔널처리와 바인딩으로 변형해봤습니다!

2023-02-24 01:50 UTC, gzzjk159 commented on Expo1900/Expo1900/MainViewController.swift
> +
JSON data를 읽고 decoding하여 변환해주는 객체인 것으로 알고 있습니다.

2023-02-24 01:58 UTC, Goatt8 commented on Expo1900/Expo1900/MainViewController.swift
> +        } catch {
jsondata를 디코딩하는과정에서 json파일과 연결명이 맞지않는것과같은 에러가 발생했을때 에러를 catch해주는 구조인거같습니다

2023-02-24 01:59 UTC, Goatt8 commented on Expo1900/Expo1900/ListTableViewCell.swift
> +class ListTableViewCell: UITableViewCell {
없을거같아서 final 키워드를 넣어주었습니다!

2023-02-24 02:08 UTC, Goatt8 commented on Expo1900/Expo1900/ListTableViewCell.swift
> +    }
데이터들을 load하는과정에서 호출되는 매서드인것같습니다.
awakeFromNib 메시지가 호출되는 것은 nib파일에 정의되있던 속성값, outlet등이 연결완료되었다는 것을 보장한다고 하네욥
저희는 nib파일없이 cell을 스토리보드상에서 만들어서그런지 해당매서드가없어도 잘작동하는데 맞을까요

2023-02-24 02:09 UTC, July911 commented on Expo1900/Expo1900/MainViewController.swift
> +
get/ make 는 지양하는편이 좋다고 생각합니다. 빌드함수에서만 저는 사용하는 편입니다.

2023-02-24 02:11 UTC, July911 commented on Expo1900/Expo1900/ExpositionListViewController.swift
> +        listCell.expositionImage.image = UIImage(named: expositionList[indexPath.row].imageName)
ExpositionListViewController에서 원한다면 shortDescription의 text을 hidden처리 할 수도 있고, 폰트 사이즈나 레이아웃을 바꿀 수 있습니다. ListCell 고유의 역할이 있을텐데 그걸 지켜주지 않는 것 같습니다.

2023-02-24 02:14 UTC, July911 commented on Expo1900/Expo1900/MainViewController.swift
> +        guard let expositionText = exposition?.description else { return }
저라면 JSON으로 파싱하는 타입과 실제로 뷰에서 쓰일 모델을 따로 둘 것 같습니다. 다음 스텝에서 고민해보셔도 좋을 것 같습니다.

2023-02-24 02:17 UTC, gzzjk159 commented on Expo1900/Expo1900/ExpositionListViewController.swift
> +
as!를 풀기 위해서는 as와 is가 무엇인지부터 알아야 할거 같습니다. 
as는 타입캐스팅을 하기 위한 키워드 입니다. 타입 캐스팅이란 업캐스팅과 다운캐스팅을 말하는 것입니다.
업캐스팅이란 서브 클래스 인스턴스를 슈퍼 클래스 인스턴스 타입으로 참조하는 것이고 다운캐스팅은 슈퍼클래스 인스턴스를 서브 클래스 타입으로 참조하는 것입니다. 
업캐스팅은 무조건 성공하여 as라는 키워드를 사용해도 되지만 다운캐스팅은 as?나 as!를 통해 이것이 다운 캐스팅이 되는지 확인해야 합니다.
is는 타입을 확인하는 키워드입니다. 해당 타입이 맞는지 Bool값으로 리턴해주는 키워드인 것으로 알고 있습니다.

따라서 as!를 풀기위해서는 아래 코드 같이 guard let을 이용하여 바인딩 해주면 될 거 같습니다.
```swift
guard let listCell: ListTableViewCell = tableView.dequeueReusableCell(withIdentifier: Identifier.listTableViewCell, for: indexPath) as? ListTableViewCell else { return UITableViewCell() }
```

2023-02-24 02:25 UTC, Goatt8 commented on Expo1900/Expo1900/MainViewController.swift
> +    }
super 콜을 다넣어주었습니다!
해당 키워드가 없어도 동작에는 문제가없었지만 찾아보니, super 상위클래스가 먼저 세팅해야할부분에 대해 이니셜라이즈함으로써 기회를 주고 후에 하위클래스가 프로세스를 진행하는게 정석적이다라고 하네욥. 앞으로 코드를 적을때 viewlifeCycle에 super키워드를 습관적으로라도 넣어주는게 좋은 방법일까요

2023-02-24 02:30 UTC, July911 commented on Expo1900/Expo1900/ExpositionListViewController.swift
> +
LGTM :)

2023-02-24 02:44 UTC, gzzjk159 commented on Expo1900/Expo1900/MainExposition.swift
>      let visitors: Int
visitors라는 복수형이 배열을 나타내는 거 같아 visitor로 변경하고 codingKey를 설정하여 변경 후에도 jsondata를 잘 받을 수 있게 하였습니다. 97da08b1e5d1a38dae090aa116b55ab973b5155d

2023-02-24 02:46 UTC, gzzjk159 commented on Expo1900/Expo1900/ListTableViewCell.swift
> +    @IBOutlet weak var shortDescription: UILabel!
리뷰어의 조언대로 변수명의 Label이나 imageview를 붙여주어 가독성을 높였습니다. 97da08b1e5d1a38dae090aa116b55ab973b5155d

2023-02-24 06:22 UTC, merged

2023-02-24 09:01 UTC, Goatt8 commented on Expo1900/Expo1900/MainViewController.swift
> +
넵 감사합니다ㅎ

2023-02-24 09:03 UTC, Goatt8 commented on Expo1900/Expo1900/ExpositionListViewController.swift
> +        detailVC.imageString = expositionList[indexPath.row].imageName
넵 이부분도 다음스텝에서 한번 적용해보겠습니다!