만국박람회 [STEP 2] kokkilE, rilla 🎪
yagom-academy/ios-exposition-universelle pull request #249
Opened 2023-02-23 11:38 UTC by juun97

# 만국박람회 [STEP 2] kokkilE, rilla 🎪

@uuu1101 
안녕하세요 태태! `코끼릴라` STEP 2 PR 보냅니다! 🐘🦍
저희는 Storyboard 대신에 코드로 UI를 작성해보았습니다! 모든 UI 를 코드로 진행하다 보니 코드의 길이가 어쩔 수 없이 길어지는 것은 감안해서 봐주세요 🥹

<img src = "https://i.imgur.com/LfAf8lA.png" width = "450">

# 고민했던 점 🤔

## 1️⃣ 오토레이아웃 적용
이번 스텝에서 오토레이아웃은 고려하지 않으려고 했지만, 코드로 UI요소를 구현하려니 오토레이아웃을 적용하지 않으면 화면에 표시되지 않았습니다.
오토레이아웃을 적용하지 않고 Frame의 크기를 잡아주는 방법도 있겠지만, 오토레이아웃을 적용하는게 오히려 간단하다고 느껴져서 오토레이아웃을 적용하였습니다.

### UI 요소가 화면에 표시되지 않던 현상
UIStackView 의 오토레이아웃을 주지 않고 내부 subview 들만 오토레이아웃을 적용한 상태에서 `UIStackView.addArrangeSubview`를 할 경우 화면에 표시되지 않았습니다.
반대로 UIStackView의 오토레이아웃만 적용하면 내부의 subview는 자동으로 크기가 잡히는것을 확인했습니다. :+1: 

## 2️⃣ Title 개행 처리
exposition 의 Json 파일을 보게 되면 title 이 하나의 문장으로 되어 있습니다.

```json
"title": "파리 만국박람회 1900(L'Exposition de Paris 1900)"
```

 이 문장을 한글 부분과 영어 부분을 나누어 다른 줄로 출력을 하고 싶었기에 몇가지 방법을 고민 해보았습니다.

### String.components
- 첫 번째로 했던 생각은 해당 문자열을 String 의 Subscript 인 components 를 이용해 `(` 을 기준으로 나누어 한글 부분과 영어 부분을 나눠보려 했습니다.
- 하지만 이 방법으로 진행하게 되면 몇 가지 문제점이 있었습니다. 
1. 한글 title 과 영어 title 을 담을 2개의 UILabel 이 필요했습니다.
2. `(` 을 기준으로 나누었기에 영어 title 의 맨 앞에 `(` 을 다시 붙여주는 과정이 필요했습니다.

> 위 이유로 다른 방법이 있지 않을까 더 고민했습니다.

### `/n` 개행 문자 넣어주기
- 한글 title 과 영어 title 의 경계부분에 `/n` 개행문자를 넣어주게 되면 하나의 UILabel 로 같이 관리할 수 있었기에 해당 방법을 사용하는 쪽으로 결정했습니다.

```swift
if let index = title.range(of: "(")?.lowerBound {
            title.insert(contentsOf: "\n", at: index)
        }
```

1. `range(of: )` 메서드를 이용해 `(` 가 시작되는 첫번 째 위치를 찾기
2. `lowerBound` 프로퍼티를 이용해 인덱스를 가져오기
3.  찾은 인덱스를 기준으로 `insert` 메서드를 이용해 `\n` 개행문자 넣기 

위 방법을 사용해 title 중간에 개행문자를 넣어 한글과 영어부분을 분리하였습니다.

## 3️⃣ 좌우 스크롤 문제
<img src= "https://i.imgur.com/Q7xjVv8.gif" width=250>
<br><br>

``` swift
view.addSubview(scrollView)

NSLayoutConstraint.activate([
    scrollView.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 12),
    scrollView.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -12),
    scrollView.topAnchor.constraint(equalTo: view.topAnchor),
    scrollView.bottomAnchor.constraint(equalTo: view.bottomAnchor)
    ])
...

scrollView.addSubview(stackView)

NSLayoutConstraint.activate([
    stackView.leadingAnchor.constraint(equalTo: scrollView.leadingAnchor),
    stackView.trailingAnchor.constraint(equalTo: scrollView.trailingAnchor),
    stackView.topAnchor.constraint(equalTo: scrollView.topAnchor),
    stackView.bottomAnchor.constraint(equalTo: scrollView.bottomAnchor),
    ])
```
- 위와 같이 오토레이아웃을 적용했을 때 좌우로 스크롤이 되는것을 확인했습니다.
-  scrollView의 leading과 trailing을 view를 기준으로 적용하고, scrollView 내 stackView를 scrollView를 기준으로 오토레이아웃을 적용했으니 stackView의 좌우 길이가 고정될 것이라고 `생각했지만` 예상처럼 작동하지 않았습니다.

> 다음과 같이 widthAnchor를 추가하여 해결할 수 있었습니다.

``` swift
    stackView.widthAnchor.constraint(equalTo: scrollView.widthAnchor)
```
## 4️⃣ StackView 내의 ImageView의 공간 차지
<img src= "https://i.imgur.com/YAObb2O.png" height=450> <img src= "https://i.imgur.com/akhNQ5O.png" height=450>
<br>

- 2개의 태극기 UIImageView와 1개의 UITextLabel을 UIStackView 내에 subview로 넣었을 때의 화면입니다.
- UIImageView의 배경을 칠해 확인해보니, 위와 같이 height가 늘어나 있는것을 확인할 수 있었습니다. width에 따라 자동으로 비율에 맞춰 height가 조정되면 좋을텐데, height는 원본의 크기를 그대로 유지하는 듯 했습니다.

> 다음과 같이 이미지뷰 자체에 크기제한을 적용하여 해결할 수 있었는데요.
``` swift
leftImageView.heightAnchor.constraint(equalToConstant: 28).isActive = true
rightImageView.heightAnchor.constraint(equalToConstant: 28).isActive = true
```
`상수`로 크기제한을 주는 것 보다 비율에 맞춰 자동으로 높이까지 조절되게 할 방법이 없을지 조금 아쉬움이 있습니다. :cry: 

<br>

## 5️⃣ Cell의 UI 구성

- 처음에는 UITableViewCell를 상속받는 `CustomCell` 을 직접 구현했습니다. 직접 구현을 하다보니 저희가 필요로 하는 UI 요소를 하나하나 만들고 추가까지 하는 과정에서 코드의 길이가 매우 길어진 상태였습니다.

- 그러다 다른 캠퍼분의 조언으로 cell의 `ContentConfiguration` 에 기본적으로 `imageView` 와 `textProperties` 그리고 `secondaryText` 가 있다는걸 알게 되었고, 이 구성요소는 저희가 사용하고자 하는 구성요소와 같았기에 cell 의 ContentConfiguration 을 이용해 UI를 구성하였습니다.

```swift
var content = self.defaultContentConfiguration()

        content.text = item.name
        content.textProperties.font = UIFont.systemFont(ofSize: FontSize.subTitle)
        content.secondaryText = item.shortDescription
        content.secondaryTextProperties.font = UIFont.systemFont(ofSize: FontSize.content)
        content.image = image
```
    
 
 직접 UI 를 만들지 않고 `ContentConfiguration` 를 사용하니 코드의 길이도 확 줄고 가독성면에서도 개선되는 점을 체험했습니다 😋

2023-02-24 14:15 UTC, uuu1101 requested changes
STEP2 진행하느라 고생하셨어요! 👏👏
스토리보드를 사용하지 않고 코드로만 작성하시기 힘드셨을텐데 잘 해내셨네요 👍👍👍
몇가지 고민해보면 좋을 것 같은 부분들이 있어서 코멘트 남겨두었습니다.

이외 궁금한 부분이나 의견이 필요하신 부분이 있으면 언제든지 코멘트 또는 DM 보내주세요 :)

2023-02-24 14:15 UTC, uuu1101 commented on Expo1900/Expo1900/ViewController/PosterViewController.swift
> +
해당 부분에 개행을 넣으신 이유가 있을까요? 👀
View와 연관된 Property와 그렇지 않은 Property를 구분하기 위해서 일까요?

2023-02-24 14:15 UTC, uuu1101 commented on Expo1900/Expo1900/ViewController/PosterViewController.swift
> +
해당 부분에 개행이 포함되어 있는데, 어떤 의미를 가진 개행일까요?

2023-02-24 14:15 UTC, uuu1101 commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +
PosterViewController 에는 해당 개행이 존재하지 않는데, 해당 부분에는 개행을 포함하신 이유가 궁금해요 :)

2023-02-24 14:15 UTC, uuu1101 commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +        ])
`setTableView()` 이외에도 
`PosterViewController`의 `setScollView()` , `setStackView()`
`ItemDescriptionViewController`의 `setScollView()` , `setStackView()`메서드 내부에서 Constraint들을 설정해주고 계시는데, 혹시 불편한점은 없으셨나요? 👀

2023-02-24 14:15 UTC, uuu1101 commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +        cell.setCellContents(indexPath)
`numberOfRowsInSection` 메서드에는 `return`전 개행이 없는데 해당 메서드에는 개행을 추가하신 이유가 있으실까요?

2023-02-24 14:15 UTC, uuu1101 commented on Expo1900/Expo1900/ViewController/PosterViewController.swift
> +        guard let formattedVisitor = numberFormatter.string(for: visitors) else { return }
해당부분은 추상화 없이 바로 코드를 실행하셨는데, 이유가 있으실까요?
InfomationLabel을 set하는 역할을 하는 로직인가요? 아니면 set을 위해 부가적으로 진행해야하는 로직인가요?

2023-02-24 14:15 UTC, uuu1101 commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +        cell.setCellContents(indexPath)
indexPath를 주입 받아, 아이템의 해당 인덱스 값에 접근하여 cell에 해당하는 Contents를 set해주고 계시는데, 
indexPath 말고 해당 아이템 자체를 주입 받는 방식에 대해서는 어떻게 생각하시나요?

2023-02-24 14:15 UTC, uuu1101 commented on Expo1900/Expo1900/ViewController/ItemDescriptionViewController.swift
> +class ItemDescriptionViewController: UIViewController {
해당 `ViewController`는 다른 `ViewController`와 다르게 `final` 선언을 하지 않으신 이유가 있으실까요?
`final`은 어떤 때에 선언을 하나요?

2023-02-24 14:15 UTC, uuu1101 commented on Expo1900/Expo1900/Model/extension/extension+UIImage.swift
> +    func squareImage(length: CGFloat = 65) -> UIImage? {
squareImage 메서드를 현재 STEP에서 진행하신 이유가 있으실까요?

2023-02-24 14:15 UTC, uuu1101 commented on Expo1900/Expo1900/Model/extension/extension+UIImage.swift
> +        UIGraphicsBeginImageContext(CGSize(width: length, height: length))
해당 메서드는 어떤 역할을 하나요?

2023-02-24 14:15 UTC, uuu1101 commented on Expo1900/Expo1900/Model/extension/extension+UIImage.swift
> +        UIRectFill(CGRect(x: 0.0, y: 0.0, width: length, height: length))
해당 메서드는 어떤 역할을 하나요?

2023-02-24 14:15 UTC, uuu1101 commented on Expo1900/Expo1900/Model/extension/extension+UIImage.swift
> +        let resizedImage = UIGraphicsGetImageFromCurrentImageContext()
해당 메서드를 통해서 어떻게 이미지가 리사이즈 되나요?

2023-02-24 14:15 UTC, uuu1101 commented on Expo1900/Expo1900/Model/extension/extension+UIImage.swift
> +        UIGraphicsEndImageContext()
해당 메서드는 어떤 역할을 하나요?

2023-02-24 14:15 UTC, uuu1101 commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +    private func initializeView() {
initailze는 어떤 의미 인가요?
해당 메서드에서 init 하는 부분은 어떤 부분 일까요?

2023-02-24 14:15 UTC, uuu1101 commented on Expo1900/Expo1900/Model/Decoder.swift
> +final class Decoder {
Decoder를 객체로 만드셨군요 👍👍👍

2023-02-27 05:06 UTC, juun97 commented on Expo1900/Expo1900/ViewController/PosterViewController.swift
> +
저희 팀에서 정한 컨벤션이었습니다! 
super 메서드 호출 뒤에는 개행을 진행하는 식으로 정했었습니다. 그 과정에서 놓친 부분이 있었던 것 같네요!

2023-02-27 05:06 UTC, juun97 commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +
위 코멘트에서 언급한것처럼 저희가 놓쳤던 부분이었습니다

2023-02-27 05:16 UTC, juun97 commented on Expo1900/Expo1900/ViewController/PosterViewController.swift
> +
네 맞습니다 UI 요소와 그렇지 않은 요소를 구분하기 위해 개행을 진행했습니다!

d5eb3dc7c8c3742ee23db5a5fe90d16a7c5ea1e1

동시에 ItemDescription 뷰컨에서의 프로퍼티 부분의 개행도 같이 처리했습니다

2023-02-27 06:04 UTC, juun97 commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +        ])
57c1e84135823c97af5239b72fee7fd0c95b81d2

계속해서 반복된 코드를 작성하다 보니 눈도 피로하고 불편한점들이 좀 있었습니다!
그래서 범용적으로 쓸 수 있게 UIView 를 extension 하여 UI 의 Subscript 로 오토레이아웃을 잡을 수 있게 변경해보았습니다

2023-02-27 06:13 UTC, kokkilE commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +        cell.setCellContents(indexPath)
`return` 전에 개행하는 컨벤션으로 작성하였으나 `numberOfRowsInSection` 메서드에서 저희가 개행 실수를 한 것 같습니다. 😢

2023-02-27 06:21 UTC, kokkilE commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +        cell.setCellContents(indexPath)
`indexPath`를 주입받도록 설계한 이유는 두 번째 화면(`ExhibitItemViewController`)에서 세 번째 화면(`ItemDescriptionViewController`)의 정보를 최대한 적게 알고 있도록 구현하고자 함이었습니다.

하지만 태태의 의견을 받고 생각해보니, `indexPath`를 전달할 경우 세 번째 뷰에서`indexPath`로 다른 아이템에도 접근이 가능하기 때문에 아이템 자체를 주입받는 방식이 더 좋을 것 같다는 생각이 들었습니다.

의견 반영하여 아이템 자체를 주입받도록 수정하였습니다! 😄 
5786d35a91dcbeae6e41926b010960b450540365

2023-02-27 06:31 UTC, juun97 commented on Expo1900/Expo1900/ViewController/PosterViewController.swift
> +        guard let formattedVisitor = numberFormatter.string(for: visitors) else { return }
set 을 하기위한 포맷팅을 해주는 부가적으로 진행하는 로직입니다

태태의 말을 듣고 잠시 잊고 있었던 "하나의 메서드는 하나의 역할을 한다" 를 다시 상기 시켰습니다!

8d915f7b61d9d41e563c9256431f93ebaebd08bd

Format 부분은 기능 분리를 시켰습니다

2023-02-27 06:34 UTC, kokkilE commented on Expo1900/Expo1900/ViewController/ItemDescriptionViewController.swift
> +class ItemDescriptionViewController: UIViewController {
`final`은 상속될 가능성이 없는 클래스에 선언합니다.
저희가 `final` 적용을 놓친 부분이네요. 😢  적용하였습니다!

2023-02-27 06:53 UTC, juun97 commented on Expo1900/Expo1900/Model/extension/extension+UIImage.swift
> +    func squareImage(length: CGFloat = 65) -> UIImage? {
오토레이아웃 적용은 다음 스텝에서 진행한다고 확인은 했으나 이미지의 크기 때문에 스택뷰의 크기가 제각각인게 너무 신경쓰여서,,, 진행했습니다,,, 🥹

2023-02-27 07:21 UTC, uuu1101 commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +        ])
오 extension 하여 메서드로 작성하셨네요 👍👍👍
각 뷰들의 상관 관계를 파악하는데 어려움은 없을까요? 
(해당 질문은 개인마다의 코딩스타일에 대한 질문이기도 하고, 현재 코드가 어려움이 있다는 이야기는 아닙니다😊)

2023-02-27 07:23 UTC, uuu1101 commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +        cell.setCellContents(indexPath)
아하 그런 의도로 작성하셨군요 :) 
> 혹시나 드리는 말씀인데, 제 의견을 무조건 반영하실 필요는 없습니다 :)

2023-02-27 07:24 UTC, uuu1101 commented on Expo1900/Expo1900/ViewController/ItemDescriptionViewController.swift
> +class ItemDescriptionViewController: UIViewController {
상속될 가능성이 없는 클래스에 `final` 키워드를 선언해주면 어떤 이점이 있을까요?
> 나중에 고민해보셔도 됩니다.

2023-02-27 08:13 UTC, kokkilE commented on Expo1900/Expo1900/Model/extension/extension+UIImage.swift
> +        let resizedImage = UIGraphicsGetImageFromCurrentImageContext()
`UIGraphicsGetImageFromCurrentImageContext()` 함수를 호출하여 현재 할당된 그래픽 컨텍스트의 영역을 캡쳐해서 새로운 UIImage를 생성하고 resizedImage에 저장합니다!

2023-02-27 08:14 UTC, juun97 commented on Expo1900/Expo1900/Model/extension/extension+UIImage.swift
> +        UIRectFill(CGRect(x: 0.0, y: 0.0, width: length, height: length))
`UIGraphicsBeginImageContext()` 는 파라미터로 받은 영역 만큼의 그래픽 컨텍스트 생성하는 함수입니다. `UIGraphicsEndImageContext()` 가 실행되기 전까지 그래픽 컨텍스트의 영역을 `UIGraphicsGetImageFromCurrentImageContext()` 함수를 통해 캡쳐 해올 수 있습니다.

2023-02-27 08:14 UTC, kokkilE commented on Expo1900/Expo1900/Model/extension/extension+UIImage.swift
> +        UIGraphicsEndImageContext()
현재 컨텍스트를 종료하고, 해당 컨텍스트와 관련된 메모리를 해제하는 역할을 합니다. UIGraphicsBeginImageContext() 함수가 실행되고 위 함수를 실행하지 않으면 메모리 누수가 발생할 수 있습니다.

2023-02-27 08:14 UTC, juun97 commented on Expo1900/Expo1900/Model/extension/extension+UIImage.swift
> +        let resizedImage = UIGraphicsGetImageFromCurrentImageContext()
파라미터로 받은 영역중 공백 부분을 Setting 된 컬러로 채워주는 역할을 합니다.

2023-02-27 08:15 UTC, juun97 commented on Expo1900/Expo1900/Model/extension/extension+UIImage.swift
> +        UIGraphicsBeginImageContext(CGSize(width: length, height: length))
`UIGraphicsBeginImageContext()` 는 파라미터로 받은 영역 만큼의 그래픽 컨텍스트 생성하는 함수입니다. `UIGraphicsEndImageContext()` 가 실행되기 전까지 그래픽 컨텍스트의 영역을 `UIGraphicsGetImageFromCurrentImageContext()` 함수를 통해 캡쳐 해올 수 있습니다.

2023-02-27 08:24 UTC, juun97 commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +    private func initializeView() {
초기내용을 설정하다는 의미입니다.
저희가 의도한 바는 해당 뷰가 초기 등록시점에 초기화 해준다는 의미를 전달하려 했으나 이름만 보았을 때는 해당 객체의 Initializer 와 관련이 있어보이는 것 같아 `setInitialView` 라는 이름으로 변경했습니다

2023-02-27 08:28 UTC, kokkilE commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +        ])
`setAutoLayout` 메서드를 호출 시 `equalTo`레이블을 사용하는 파라미터를 통해 기준이 되는 `UIView`를 입력 인자로 넘겨주기 때문에 큰 어려움이 없을 거라고 생각했습니다.

혹시 어떤 방법으로 해보면 각 뷰들의 상관 관계를 파악하는데 도움이 될 지 의견을 나눠주실 수 있으실까요? 👏

2023-03-02 13:22 UTC, uuu1101 commented
디스코드로 이야기 나눈 내용 남깁니다.

1. 뷰의 상관 관계
해당 코멘트는 각 뷰에 대한 제약사항들을 해당 뷰를 set 할때 작성해주고 계시는데 현재는 최상위의 view에 대해서 각각의 뷰만 제약조건을 걸어주면 되는데 만약 각 뷰들이 서로에 대해서 제약조건을 가지는경우 코드상으로 파악하기가 어떨지에 대한 질문이었습니다 ㅎㅎ 
 이 부분은 추후 프로젝트하면서 겪게 될 상황이기도 하여서 현재 우선순위를 높게 가져가지 않아도 될 것 같아요. 

2. 이미지 리사이징 관련해서 해당 부분에 대한 코드를 이해하고 작성하신건지 아니면 리사이징 검색하여 나온 코드를 사용하신건지 궁금했고, 이미지에 대해서는 .scaleToFit 같은 해당 옵션을 사용하지 않고 직접 리사이징 해주신 이유가 궁금했어요. 
ImageView.contentMode 에 대해서 찾아보시면 도움이 될 것 같습니다.

2023-03-03 13:01 UTC, merged