만국박람회 [STEP 2] 혜모리, Andrew
yagom-academy/ios-exposition-universelle pull request #250
Opened 2023-02-24 01:43 UTC by hyemory

알라딘 안녕하세요!
만국박람회 프로젝트 STEP 2 PR 보내드립니다.
스토리보드로 구성하지 않고 코드로만 UI를 구현해 보았습니다.
스토리보드 파일은 필요하지는 않으나, STEP 3 내용이 아직 공개되지 않아 남겨두었습니다.
또한, 오토 레이아웃은 다음 스탭에서 적용한다고하여 아직 전부 손보지 않은 상태입니다.
이 점 감안해 주시고 이번 리뷰도 잘 부탁드리겠습니다 😆

## 고민했던점 & 조언을 얻고 싶은 점
### 1. 커스텀 셀 파일 분리
- CustomTableViewCell을 같은 파일에 만들어 주기 보다는 View 폴더로 따로 분리하였습니다.

### 2. AutoLayout
- 각 파일에 configureUI함수에 Autolayout을 Anchor.constraint를 사용해서 처음 작성해봤는데 알라딘이 보기에는 적당하게 layout이 사용되었는지 아니면 생략된게 있거나 생략했으면 좋은 부분이 있는지 궁금합니다.

### 3. 동일한 ImageView 중복 선언
![](https://i.imgur.com/Rt8ygJy.png)
- 이미지뷰를 생성하지 않고 버튼에 이미지를 넣는 방법도 해보고 이미지 뷰를 하나만 생성해서 스택뷰에 (이미지뷰, 버튼, 이미지뷰) 넣는 방법도 해보았는데 성공하지 못해서 똑같은 이미지뷰를 2개를 만들어서 양쪽에 배치 했습니다. 이미지뷰를 하나만 사용해서 재활용 사용하는 방법이 있을까요?

### 4. 레이블 구성
- 예시 화면을 보면 방문객, 개최지, 개최기간의 경우 레이블의 크기가 미세하게 차이를 보이고 있습니다.
- 우선은 아래와 같이 하나의 레이블에 출력되도록 구현하였는데, `방문객 :` 이라는 레이블과 `3,123,123명` 이라는 레이블을 따로 둬야할지 아니면 하나의 레이블에서 폰트의 크기를 다르게 둘 지 고민이 됩니다. (`NSMutableAttributedString`)
- `방문객 :`은 고정된 값이고 `3,123,123명`은 디코딩을 받아야하는 유동적인 값으로 레이블을 따로 구성하는게 더 좋다고 생각하는데, 알라딘의 의견은 어떠실까요?

``` swift
// ExpoInfoMainViewController 클래스의 34번 행
private lazy var numberOfVisitorsLabel = {
    let label = UILabel()
    label.text = "방문객 : \(String(expoAssets?.numberOfVisitors ?? 0).applyFormatter()) 명"
    return label
}()
```

2023-02-27 01:32 UTC, junbangg requested changes
수고하셨습니다!

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Controller/EntryInfoViewController.swift
> +final class EntryInfoViewController: UIViewController {
Final 에 대해서 공부 하셨나요?! 어떤 이유로 쓰셨는지 궁금하군요!

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Controller/EntryInfoViewController.swift
> +    private lazy var entryImageView = {
Lazy 를 쓰셨는데 이유를 알 수 일을까요~?

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Controller/EntryInfoViewController.swift
> +        label.text = entry.description
텍스트를 여기서 넣어주는것보다는 Entry 가 set 되었을때 configure 메서드를 하나 둬서 ui에 데이터를 넣어주는 방식은 어떨까요??
이해가 만약 안되셨다면 댓글 주세요!

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Controller/EntryInfoViewController.swift
> +        label.text = entry.description
오 밑에 보니까 configure 메서드가 있네요??
왜 이 친구는 거기서 세팅을 안해준건가요??🤔

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Controller/EntryInfoViewController.swift
> +        ])
configureLayout 이라는 메서드로 하나 분리해주는건 어떨까요??ui 요소가 추가될수록 요 메서드가 굉장히 방대해질 여지가 보여서요!

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Controller/EntryTableViewController.swift
> +    private let cellIdentifier: String = "cell"
요거 셀이 자기 자신의 identifier을 갖고있도록 하는 방법은 어떠세요??🤔

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Controller/EntryTableViewController.swift
> +        navigationItem.title = "한국의 출품작"
Self 의 유뮤에 이유가 있을까요???

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Controller/EntryTableViewController.swift
> +    }
Mark 주석으로 정리를 해주셨는데 extension 까지 활용해주신다면 더 깔끔할것 같네요 개인적으로!

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Controller/ExpoInfoMainViewController.swift
> +        label.text = expoAssets?.title
위에 관련해서 비슷한 댓글 남겼습니다!

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Controller/ExpoInfoMainViewController.swift
> +        label.text = "방문객 : \(String(expoAssets?.numberOfVisitors ?? 0).applyFormatter()) 명"
여기도요!

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Controller/ExpoInfoMainViewController.swift
> +        label.text = "개최지 : \(self.expoAssets?.location ?? "")"
밑에 쭉 많군요 !ㅋㅋ

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Controller/ExpoInfoMainViewController.swift
> +        ])
Stackview 에 넣는거 메서드로 빼서 다른 뷰컨 처럼 하는건 어떨까요???

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Controller/ExpoInfoMainViewController.swift
> +        ])
요것도여!

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Controller/ExpoInfoMainViewController.swift
> +    }
잘 몰라서 그러는데 여기다가 히든 하고 안하고 이유가 뭔가요????

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Controller/ExpoInfoMainViewController.swift
> +        scrollView.addSubview(mainStackView)
Configure ui 라는 메서드가 여기 있으니까 스캑뷰 구성도 여기서 하는게 어떨까 싶네요 개인적으로는! 지금 형태로 하신 특별한 이유가 있다면 제가 모르는걸 수도 있으니 꼭 말씀해주세요~

2023-02-27 01:32 UTC, junbangg commented on Expo1900/Expo1900/Model/String+extension.swift
> +    func applyFormatter() -> String {
메서드명이 조금 더 직관적일 수 있을것 같아요! 어떤 format 을 적용시킨다는건지 알 수가 없을것 같아요ㅠ

2023-02-27 01:39 UTC, junbangg commented
질문주신 내용에 대한 답변을 드리자면!

**오토레이아웃**
봤을때 문제 없어보였는데 다시 한번 봐볼게요ㅎㅎㅎ

**레이블**
좋은 고민을 하신것 같네요! 
지금 요구사항에서 큰 문제가 없어보인다면 괜찮겠지만 
나중에 두개의 (방문객, 실제 데이터 부분) ui가 달라질 수 있는 여지도 충분히 있겠죠!

근데 같은 레이블 안에 있는 글씨의 폰트를 다르게 주는 방법도 있답니다~~nsattributedString 잘 활용해서 할 수 있어요!

2023-02-27 04:56 UTC, Andrew-0411 commented on Expo1900/Expo1900/Controller/EntryInfoViewController.swift
> +        label.text = entry.description
configureUI 메서드에는 전역적인 옵션(페이지의 타이틀, 색상, 레이아웃 등)을 구현하고, 
각각 UI 요소마다 적용되어야하는 옵션 (문구, 사이즈, 줄바꿈)등을 각각의 프로퍼티에 정의하는 것을 기준으로 화면을 구현했습니다.

lazy var를 사용하기보다는 알라딘이 말씀하신데로 메서드로 따로 빼주어서 수정했는데 lazy var 사용을 지양해야되는지 궁금합니다

2023-02-27 05:04 UTC, hyemory commented on Expo1900/Expo1900/Controller/EntryInfoViewController.swift
> +    private lazy var entryImageView = {
`entry`의 값을 사용하면 아래와 같은 컴파일 오류가 발생됩니다.

> Cannot use instance member 'entry' within property initializer; property initializers run before 'self' is available
> 인스턴스 멤버인 `entry`를 프로퍼티 이니셜라이저 내에서 사용할 수 없습니다. `self`를 사용하기 전에 프로퍼티 이니셜라이저가 실행됩니다

`entry`가 초기화되기도 전에 UI에 할당해버려 발생한 오류였습니다.
`lazy` 키워드를 사용하면 추후 `entry`가 초기화되는 시점에 UI에 할당할 수 있게 해줍니다.

바로 밑 앤드류의 코멘트와 같이 저희는 아래와 같은 기준으로 코드를 구현했기 때문에 `lazy var`를 선택했습니다.
> configureUI 메서드에는 전역적인 옵션(페이지의 타이틀, 색상, 레이아웃 등)을 구현하고,
각각 UI 요소마다 적용되어야하는 옵션 (문구, 사이즈, 줄바꿈)등을 각각의 프로퍼티에 정의하는 것을 기준으로 화면을 구현했습니다.

알라딘이 제안해 주신대로, configureUI 메서드에서 구현하고 `lazy var`를 제거하는 작업을 했습니다!

2023-02-27 05:45 UTC, hyemory commented on Expo1900/Expo1900/Controller/EntryInfoViewController.swift
> +final class EntryInfoViewController: UIViewController {
`final` 키워드를 사용한 class는 더이상 상속, 재정의를 할 수 없게됩니다.
상속, 재정의를 할 필요가 없을 때 사용해주면 좋다고만 알고 사용하였는데, 런타임에 성능상의 이점을 가지고 있다고 합니다.

- vTable : 클래스 내부에서 어떤 메서드를 실행할 지 결정하는 테이블 (동적 디스패치 지원)

런타임에 vTable이 상속받은 메서드를 호출할 지, 오버라이딩한 메서드를 호출할 지 확인한다고 합니다.
`final` 키워드를 사용하면 이러한 확인 과정을 줄여줄 수 있어 성능상의 이점이 있다고 이해하였습니다.

2023-02-27 06:00 UTC, hyemory commented on Expo1900/Expo1900/Controller/EntryInfoViewController.swift
> +        ])
제안해 주신대로 레이아웃 관련 내용은 `configureLayout()` 메서드로 정리하였습니다! ☺️
d2a0f0a8f8d9fc2fb32d120e1956dc778a61dd7a

2023-02-27 06:11 UTC, Andrew-0411 commented on Expo1900/Expo1900/Controller/EntryTableViewController.swift
> +    private let cellIdentifier: String = "cell"
UITableVIewController에서 TableViewCell로 이동시켜서 자신의 identifier를 갖도록 하였습니다.

2023-02-27 06:17 UTC, Andrew-0411 commented on Expo1900/Expo1900/Controller/EntryTableViewController.swift
> +    }
extension으로 분리해서 Mark 주석으로 구분하였습니다

2023-02-27 06:32 UTC, Andrew-0411 commented on Expo1900/Expo1900/Controller/EntryTableViewController.swift
> +        navigationItem.title = "한국의 출품작"
register에 매개변수 cellClass의 타입은 AnyObject.Type인데 메타타입의 값을 얻으려면 뒤에 .self를 붙여야 하기 때문에 self를 붙였습니다

2023-02-27 06:33 UTC, hyemory commented on Expo1900/Expo1900/Controller/ExpoInfoMainViewController.swift
> +        ])
a128988b4bc7632cc39024fdea9b8bdbabeec778
해당 커밋과 같이 스택뷰를 반환하는 메서드를 만들도록 수정하였습니다!

2023-02-27 06:41 UTC, Andrew-0411 commented on Expo1900/Expo1900/Controller/ExpoInfoMainViewController.swift
> +    }
예제를 보시면 메인페이지의 네비게이션바가 숨겨져 있어서 viewWillAppear에 isHidden = true 을 사용하였고
메인페이지에서 다음 페이지로 이동하면 네비게이션바가 보여져야 하기 때문에 viewWillDisappear에 isHidden = false을 사용하였습니다

2023-02-27 07:01 UTC, Andrew-0411 commented on Expo1900/Expo1900/Model/String+extension.swift
> +    func applyFormatter() -> String {
applyNumberFormatter로 네이밍을 변경하였습니다

2023-02-27 07:07 UTC, hyemory commented on Expo1900/Expo1900/Controller/ExpoInfoMainViewController.swift
> +        scrollView.addSubview(mainStackView)
이번 리뷰를 통해 변경한 뷰 컨트롤러 코드 기준은 아래와 같습니다!
- 뷰에 들어갈 요소 각각의 옵션을 전역 상수로 설정 (사이즈, 줄바꿈 등) 
- `configureUI()` 메서드 : `entry`를 이니셜라이저 해야하는 UI 옵션 세팅 및 뷰 컨트롤러의 옵션 설정 (title 문구, 배경색 등)
- `configureLayout()` 메서드 : 뷰를 추가하고 각 뷰의 위치 설정

2023-02-27 07:15 UTC, Andrew-0411 commented
lazy var를 사용하기보다는 알라딘이 말씀하신데로 메서드로 따로 빼주어서 수정했는데 lazy var 사용을 지양해야되는지 궁금합니다

2023-02-28 13:59 UTC, junbangg commented on Expo1900/Expo1900/Controller/EntryInfoViewController.swift
> +final class EntryInfoViewController: UIViewController {
아주 좋습니다~!

2023-02-28 14:03 UTC, junbangg commented on Expo1900/Expo1900/Controller/EntryTableViewController.swift
> +        navigationItem.title = "한국의 출품작"
오 고것이 아니라 맨 앞에 있는 `self.` 이야기 한거였어요!!

2023-02-28 14:11 UTC, junbangg commented on Expo1900/Expo1900/Controller/EntryInfoViewController.swift
> +        label.text = entry.description
넵 그렇군요!!
그런데 제 개인적인 생각으로는 
`label.text = entry.description` 처럼 UI에 변경될 수 있는 데이터 넣어주는건 `configureUI` 에서 같이 해주는게 더 확장성 있는 코드가 될것 같아요!

지금은 그렇지 않겠지만 `entry` 가 자주 갱신되는 일이 빈번하게 발생하는 경우를 생각해보면 좋을것 같아요!

지금 구조로는 한번만 세팅 되고 끝이겠죠?? 하지만 자주 갱신될 일이 있을때를 대비해서 다음과 같이(예시 일뿐)

```
private var entry: Entry {
  didSet {
     configureUI()
  }
}
```

요런식으로 가져가는 경우를 생각해볼 수 있을것 같습니당

2023-02-28 14:14 UTC, junbangg commented
> lazy var를 사용하기보다는 알라딘이 말씀하신데로 메서드로 따로 빼주어서 수정했는데 lazy var 사용을 지양해야되는지 궁금합니다

음 제가 고 부분에 대해서 말씀 드린 이유는 lazy 가 포인트가 아니었어요! 제가 댓글 단 곳 보면 이해가 되실거라고 생각합니다.
https://github.com/yagom-academy/ios-exposition-universelle/pull/250#discussion_r1120122479

2023-02-28 14:18 UTC, merged