만국박람회 [STEP 2] Rhode, Christy
yagom-academy/ios-exposition-universelle pull request #251
Opened 2023-02-24 03:18 UTC by Rhode-park

@lina0322 
안녕하세요 엘림! 
이번에 만국박람회에서 엘림의 리뷰를 받게 될 7조, `로데스티`입니다.
STEP02는 네비게이션바와 데이터 전달 방식에서 조금 애를 먹은 것 같습니다🥹
오늘도 리뷰 감사드립니다🥰

## 고민했던 부분
### 1️⃣ 네비게이션바 hidden
첫 번째 화면에서는 네비게이션바가 보이지 않습니다. 그래서 첫 번째 화면에서는 네비게이션바를 감추고 나머지 화면들에서는 네비게이션바를 보여줘야합니다. 스토리 보드 상에서 다음의 인스펙터에서 `Hidden`에 체크를 할 수 있습니다:
![](https://i.imgur.com/DCmhs3T.png)
이렇게 할 경우, 다른 네비게이션바까지 모두 사라지는 문제가 발생했습니다.
그래서 맨 첫번째 뷰에서만 네비게이션바를 보이지 않게 코드를 작성했습니다:
```swift
override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    self.navigationController?.isNavigationBarHidden = true
}
```
`viewWillAppear`에 해당 코드를 넣은 이유는, 다음 화면으로 넘어갔다가 다시 돌아올 때 `viewDidLoad`가 아닌 `viewWillAppear`부터 사이클이 시작되기 때문입니다. 뷰의 라이프 사이클은 다음과 같습니다: 
<img height="300px" src="https://i.imgur.com/Vp09mAy.png">
이런 사이클을 가지기 때문에 `viewWillAppear`에 해당 코드를 넣어 현재의 화면으로 다시 돌아오면 네비게이션바가 없어지도록 만들었습니다.

다른 화면에서는 네비게이션바가 있어야하기 때문에, 다음 화면의 `viewDidLoad`에서 다시 `isNavigationBarHidden`를 `false`로 바꾸어주었습니다:
```swift
override func viewDidLoad() {
    super.viewDidLoad()
    tableView.delegate = self
    tableView.dataSource = self
    exhibitItems = decodeJson()
    self.tableView.reloadData()
    self.navigationController?.isNavigationBarHidden = false
    self.navigationItem.title = "한국의 출품작"
}
```

### 2️⃣ tableView 구현 방식
StoryBoard에서 tableView를 구현하는 방법에는 다음과 같은 방법들이 있습니다:
- `UIViewController + UITableView`
- `UITableViewController`

먼저 `UIViewController + UITableView`를 사용할 경우 `ViewController` class에 `UITableViewControllerDelegate`와 `UITableViewControllerDataSource`를 채택하고 구현합니다. `TableView`의 `delegate`와 `datasource`는 `ViewController`의 `self`임을 명시하며 사용합니다. 해당 방법은 원하는대로 custom하기 좋습니다.

`UITableViewController`의 경우 `UITableViewControllerDelegate`와 `UITableViewControllerDataSource`가 자동으로 생성됩니다. 따라서 코드의 양이 적어지지만 원하는 대로 custom하기 불편합니다. 또한 `UITableViewController` 내부에서만 `tableView`를 사용할 수 있어 다른 뷰에서 함께 사용할 수 없습니다.

처음에는 해당 화면에서 `tableView` 하나의 뷰만 존재하니 코드의 길이를 줄이기 위해 `UITableViewController`의 사용을 고민했습니다. 하지만 다음 스텝에서 화면에 다른 뷰가 추가될 수 있고, 원하는 방향으로 custom하여 사용함이 좋겠다 판단하여 저희는 `UIViewController`에 `UITableView`를 상속받아 사용하는 방법을 채택하여 사용했습니다. 

---

## 조언을 얻고싶은 부분
### 1️⃣ 데이터 전송 방법(Singleton, Delegation, Initializer, Segue&Prepare)

`ItemViewController`에서 decoding한 JSON의 데이터를 `ExhibitItemViewController`로 전송해야합니다. `TableView`의 `row`에서 선택한 물건에 대한 정보를 다음 화면에서 띄워줘야하기 때문입니다. 그래서 `TableView`의 각각의 `cell`을 선택했을 때, 거기에 담고 있는 정보를 어떻게 전달해줘야할지 고민을 했습니다.

저희가 알기로는 데이터를 전달하는 방법에는 다음과 같은 방법들이 있습니다:
 - `Singleton`
 - `Delegation`
 - `Initializer`
 - `Prepare`(`Segue` 사용)
 - `Notification Centre`

이 때, `Singleton`은 앱 내의 단 한 개의 인스턴스가 존재하고 이를 전역에서 접근할 수 있기 때문에, 각기 다른 쓰레드에서 객체의 상태를 마구잡이로 변경시킬 여지가 있습니다. 상태가 공유된다는 것이 굉장히 위험한 일이라고 생각하여 사용하지 않았습니다.

`Notification Centre`는 현업에서 잘 사용하지 않는다고 들었습니다. 키보드나 카카오톡 알림 같은 경우에만 사용한다고 들었습니다.

그래서 적합한 것이, `Delegation`, `Initializer`, `Prepare`정도라고 생각했습니다.
그 중에서도 `Delegation`이 가장 적합하다고 생각했으나, 구현에서의 어려움을 겪어 `Prepare`로 노선을 우회했습니다.

그러나, `prepare` 메서드를 사용하고자 하면, `segue`를 같이 사용해야합니다. `segue`를 사용하게 되면, 스토리보드 상에서 화면 전환이 진행됩니다. 코드가 아닌 스토리보드로 많은 것들을 구현하게 되면, 어떤 부분을 건드리게 되었는지 본인도 알기 힘들 뿐더러 협업자도 확인하기 힘들다는 단점이 있다는 것을 느끼고 있습니다. 그래서 `prepare`를 통해 데이터를 전달하는 것 역시 썩 적절하지는 않은 것 같다는 생각이 듭니다.

그래서 `Delegation`이나 `Initializer`를 통해 리팩토링하는 것 역시 생각하고 있습니다.

엘림은 이 부분에 대해서 어떻게 생각하실까요?
어떤 방식을 통해 데이터를 전달하는 것이 저희 프로젝트에 가장 목적적합하다고 생각하시나요?
이 부분에 대해서 엘림의 조언을 구하고 싶습니다.

2023-02-24 06:39 UTC, lina0322 requested changes
두 분 고생하셨습니다~
코멘트 달아 두었으니 확인해보시고, 이해가 안가거나 궁금한 부분이 있으시다면 편하게 DM주세요!

질문중에 데이터 전달에 관한 내용이 있었는데요~
지금 상당히 단순한 구조인데 매우 복잡하게 생각을 하고 있는 것 같아요!
예를 들어 A라는 viewController가 값을 가지고 있고, 그 값을 B라는 viewController에 넘겨줄때
그리고 A에서 B를 생성하고 있을때라면
생성하는 시점에 원하는 값을 같이 넣어주면 되지 않을까요?ㅎㅎ (힌트가 잘 되었는지 모르겠네용ㅎ)

또, 세그가 동작하는 방식은 어떤가요? push는 어떻게 동작하죠? 그 두 가지 방식을 근본적으로 이해하는 과정이 우선되어야할 것 같습니다.
구현도 좋지만 기본적인 부분들을 잘 이해해야 더 좋은 코드가 나올 수 있을 것 같아요~

고생하셨고, 수정 열심히 해봅시다!

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExhibitItemViewController.swift
> +    var prepareDescription: String = ""
타입 명시를 하는 것이 두분의 컨벤션인가요??

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExhibitItemViewController.swift
> +    @IBOutlet weak var descriptionLabel: UILabel!
외부에서 접근할 일이 있나요?

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExhibitItemViewController.swift
> +        imageView.image = UIImage(named: prepareImage)
self는 어떤 기준으로 붙여주고 계신가요?
또 viewDidLoad에서 바로 코드를 작성하는 것 보다는 
연관있는 코드들을 모아 메서드로 만드는 것이 좋을 것 같습니다~

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +final class ExpositionViewController: UIViewController {
final을 붙인 이유는 무엇인가요??

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +    @IBOutlet weak var visitorNumberLabel: UILabel!
number과 count의 차이 확인 하셨나요??

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        self.navigationItem.backButtonTitle = "메인"
String을 별도로 관리해주세요~

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        descriptionLabel.text = expositionUniverselle.description
1. 별도 함수로 분리해주세요
2. 여기 뭔가 정리가 필요해보여요..

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        self.navigationController?.isNavigationBarHidden = true
.isNavigationBarHidden = `true`를 여기서 해주었다면 짝궁인 `false`도 여기서 처리해주는게 좋아요.
먼약에 ExpositionViewController가 아니라 ExhibitItemViewController에 종속되는거면 거기서 해주는게 좋겠죠?

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +    }
viewController가 decoding에 대한 역할을 가질 필요가 있을까요??

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +    @IBAction func itemButtonTapped(_ sender: UIButton) {
Tapped보다는 touchUpInside와 같이 정확하게 연결된 제스쳐로 이름지어주는게 더 좋아보여요

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        guard let itemVC = self.storyboard?.instantiateViewController(withIdentifier: "itemViewController") as? ItemViewController else { return }
약어 사용 지양해주세요!

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        guard let itemVC = self.storyboard?.instantiateViewController(withIdentifier: "itemViewController") as? ItemViewController else { return }
itemViewController라는 String을 직접 사용하기 보단 ItemViewController가 자신의 이름을 들고 있고, ItemViewController 내부의 변수를 참조하는 것이 유지보수에 좋겠죠~

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +final class ItemViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
extension을 활용하여 UITableViewDelegate, UITableViewDataSource 코드를 구분해주면 코드가 보기 편해집니다.

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +    @IBOutlet var tableView: UITableView!
여기엔 왜 weak가 없나요? 반대로 왜 다른 viewController에는 weak가 있었나요?

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +        self.tableView.reloadData()
viewController를 생성하는 시점에 reloadData 해주는 이유가 잘 이해가 안갑니다~ 
reloadData는 어떤 역할을 하는 메서드인가요?

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +    private var exhibitItems: [ExhibitItem] = []
아이템 1개를 보여주는 것 같은 네이밍인데(ItemViewController), 왜 exhibitItems이라는 배열을 가지고있나요??

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +    }
numberOfSections의 기본값은 몇인가요??

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +        cell.imageView?.image = UIImage(named: exhibitItem.imageName)
custom cell을 만드시는 것을 추천드립니다!
기본형을 사용해보는 경험은 좋지만, 실무에서는 기본 셀을 사용할 일이 없어요..
그리고 지금 사용하시는 방식은 Deprecated 된것으로 알고있는데요. 공식문서 확인해보셨나요??

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +            return self.view.bounds.height / 6
화면이 커지면 셀 높이도 높아지는걸까요?? 패드에는 매우 크게 나올거같은데요. 셀 높이를 이렇게 지정한 이유가 있나요?

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +final class ItemViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
전반적으로 ViewController의 이름만 가지고 화면이 어떤 화면인지 정확히 이해가 안가네요
관계를 더 이해할 수 있도록 할 순 없을까요?
작업하시는 두 분 생각에 지금이 최선이신가요??

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +        performSegue(withIdentifier: "itemDetailView", sender: nil)
itemDetailView는 어디인가요?
segue를 사용하지 않고 push로 화면을 띄울수도 있지 않나요??

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +        if segue.identifier == "itemDetailView" {
오타가 발생하면 동작하지 않겠네요..!

2023-02-24 06:39 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +            destination.prepareDescription = exhibitItems[selectedIndex].description
destination안에서 설정할 수 있지 않나요? 
여기서 destination의 프로퍼티들에 직접 접근하는건 destination의 역할을 뺏어오는 것 같네요.
또한 destination과 exhibitItemViewController중에 어느 네이밍이 더 괜찮은거같나요??

2023-02-28 07:38 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ExhibitItemViewController.swift
> +    var prepareDescription: String = ""
저희가 컨벤션을 정하지 않았습니다. 그래서 모두 다 타입 명시를 하는 쪽으로 컨벤션을 정해봤는데, 이렇게 타입 명시를 다 달아주는게 맞을까요 엘림? 맞는지 확인 부탁드립니다🙇🏻‍♀️

그리고 타입 명시를 하다가 이런 상황에 마주했습니다(이 부분은 리팩토링 초기 코드라 현재의 코드와 다를 수 있습니다):
![](https://i.imgur.com/zL9C93l.png)
앞에 `ItemViewController`라고 타입 명시를 해주었기때문에 as? `ItemViewController` 라는 부분을 빼도 될거라고 생각했습니다. 그런데, `Type of expression is ambiguous without more context`라는 오류가 뜹니다. 앞에 타입 명시를 해주면 캐스팅을 해주지 않아도 되는 것이 아니었나요?ㅠㅠ 저희가 잘못 이해하고 있는 것일까요?🥹

2023-02-28 07:39 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ExhibitItemViewController.swift
> +        imageView.image = UIImage(named: prepareImage)
저희가 이 부분에 대해서도 컨벤션을 정하지 않았습니다. 그래서 문법적으로 `self`를 필요로 하는 경우를 제외하고 모두 `self`를 떼어주는 쪽으로 컨벤션을 정했습니다. 이번에 수정한 코드는 컨벤션을 잘 지키고 있다고 볼 수 있을까요? 혹시 잘못된 부분이 있다면 말씀부탁드립니다🙇🏻‍♀️

2023-02-28 07:40 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +final class ExpositionViewController: UIViewController {
상속되지 않을 클래스이기 때문에 성능상 이점을 꾀하기 위해서 `final` 키워드를 붙였습니다.

`final`은 클래스가 오버라이드 되는 것을 막기 위한 키워드입니다. [The Swift Programming Language - Inheritance](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/inheritance)의 Prevent Overrides에서는 `final`키워드를 사용해서 클래스가 오버라이드 되는 것을 막을 수 있다고 말합니다.

`final` 키워드를 사용한 이유는 성능을 향상시키기 위해서입니다. [Apple github - OptimizationTips](https://github.com/apple/swift/blob/main/docs/OptimizationTips.rst#advice-use-final-when-you-know-the-declaration-does-not-need-to-be-overridden)에 따르면, 상속하지 않을 클래스는 `final` 키워드를 사용하는 것이 좋다고 합니다. `V table`을 거치지 않고, 직접적인 호출을 하기 때문입니다. 

`V table`을 거치지 않으면, 컴파일 시점에 어떤 메서드를 실행할지 결정할 수 있으므로 성능상 이점을 가지게 됩니다. `V table`은 가상 메서드 테이블을 말합니다. 메서드 오버라이딩에 따라 실행 시점에 어떤 메서드를 실행할지 결정하는 동적 디스패치를 지원하기 위해 프로그래밍 언어에서 사용하는 메커니즘이라고 합니다. 위에서 언급한 것과 같이 `final` 키워드를 사용하게 되면 `V table`을 거치지 않고 컴파일 시점에서 직접적인 호출을 하게 됩니다. 그렇기때문에 성능상 이점을 가지게 된다고 볼 수 있습니다.

2023-02-28 07:40 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        self.navigationItem.backButtonTitle = "메인"
viewController에 하드코딩한 부분들이 없도록 모든 String을 `NameSpace`라는 열거형을 만들어 관리해주었습니다:
```swift
enum NameSpace {
    static let emptyString = ""
    static let homeViewTitle = "메인"
    static let itemViewTitle = "한국의 출품작"
    static let leftVisitorCountString = "방문객 : "
    static let rightVisitorCountString = " 명"
    static let leftLocationString = "개최지 : "
    static let leftDurationString = "개최 기간 : "
}
```
덧붙여, 하드코딩을 통해 `identifier`를 나타낸 부분도 `static let`키워드를 사용하여 수정했습니다.

2023-02-28 07:41 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +    }
`decodingJson`이라는 구조체를 구현하였습니다. 다음의 두 개의 메서드를 갖고 있습니다: 
 - `decodeExpositionJson() -> ExpositionUniverselle`
 - `decodeItemsJson() -> [ExhibitItem]`

각각의 메서드들은 `ExpositionViewController`와 `ItemListViewController`에서 사용할 JSON의 내용을 디코딩해줍니다.

JSON을 디코딩한 내용은 다음과 같이 불러와서 사용합니다:
```swift
private func configureLabel() {
        let expositionUniverselle = decodingJson().decodeExpositionJson()
        
        ...
    }
```

```swift
final class ItemListViewController: UIViewController {
    static let viewIdentifier = "itemListViewController"
    private var exhibitItems: [ExhibitItem] = decodingJson().decodeItemsJson()
    ...
}
    
```

2023-02-28 07:41 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        guard let itemVC = self.storyboard?.instantiateViewController(withIdentifier: "itemViewController") as? ItemViewController else { return }
하드코딩을 통해 `identifier`를 나타낸 부분 `static let`키워드를 사용하여 수정했습니다. 
다음과 같이 각각의 `UIViewController`와 `UITableViewCell`이 자신의 `identifier`를 들고 있게 했습니다:
```swift
final class ItemListViewController: UIViewController {
    static let viewIdentifier = "itemListViewController"
    ...
}
```
```swift
class CustomTableViewCell: UITableViewCell {
    static let cellIdentifier = "cell"
    ...
}
```
그리고 그 `identifier`를 사용해 참조를 하도록 변경하였습니다:
[`fdd7391`](https://github.com/yagom-academy/ios-exposition-universelle/pull/251/commits/fdd73910d157b7ed5462ce3d93ac9ba24b5f74a1)

### extension을 활용하여 UITableViewDelegate, UITableViewDataSource 코드를 구분해주면 코드가 보기 편해집니다.
코드의 가독성을 위하여 `extension`을 사용하였습니다: 
[`1165f6f`](https://github.com/yagom-academy/ios-exposition-universelle/pull/251/commits/1165f6fd384a5644411eff42f0d53b8b97768d6b)
감사합니다.

2023-02-28 07:42 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +    @IBOutlet var tableView: UITableView!
`ctrl+drag`를 통해 `IBOutlet`을 연결하고자 했으나, 드래그가 잘 되지 않아 타이핑을 했습니다. 그 과정에서 `weak`를 빠뜨린 것 같습니다.

관련해서 공부하고자했으나, 주로 `weak`와 `strong`의 차이를 기술하고 있을 뿐..`weak`를 붙일 때와 붙이지 않았을 때의 차이에 대한 자료는 잘 찾아보지 못한 것 같습니다.

`weak`는 ARC와 관련된 키워드입니다. [
Interface Builder IBOutlet연결에 Strong과 Weak 어떤것을 써야할까?](http://monibu1548.github.io/2018/05/03/iboutlet-strong-weak/)에 따르면, `strong`은 소유대상의 reference count를 1 증가시킴으로서 dealloc되지 않도록하고, `weak`는 reference count는 증가시키지 않고 소유함으로써 상호참조 발생을 막아 메모리 누수를 막는다고 합니다. 

이렇게 `weak`와 `strong`의 차이를 간단하게 이해했을 뿐, `weak` 키워드를 쓰고 쓰지 않았을 때의 차이점은 제대로 공부하지 못했습니다. 팀원끼리 이 부분에 대해서 더 공부하고 토론해보도록 하겠습니다.

2023-02-28 07:43 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +    private var exhibitItems: [ExhibitItem] = []
디코딩 된 전체 출품작에 대한 정보를 저장하고 있는 배열로 여러 item을 가지고있다는 의미에서 exhibitItems라고 네이밍했습니다! 일반적으로 어떤 영단어 뒤에 `s`가 붙으면 배열을 의미한다고 알고 있습니다.

그리고, `ItemViewController`의 네이밍이 적절하지 않다고 판단되어, 두 번째 뷰의 컨트롤러 이름을 `ItemListViewController`로 변경하였습니다.

2023-02-28 07:44 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +    }
공식문서를 통해 기본값은 1이며 해당 메서드를 작성하지 않으면 1개의 section으로 자동 구성됨을 알 수 있었습니다. 따라서 해당 메서드를 제거하여 리팩토링 진행했습니다. 감사합니다.

2023-02-28 07:47 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +            return self.view.bounds.height / 6
STEP2를 진행하기 전 구현해야 하는 부분의 내용에 테이블 뷰 내부의 이미지 크기 등 레이아웃(오토레이아웃) 문제는 STEP3에서 해결한다고 작성되어 있음을 확인했습니다. 오토레이아웃은 최소한으로 작업하며 해당 스텝을 진행하였는데, 셀 내부의 이미지 크기를 조정해주지 않으니 이미지가 너무 커지는 문제가 발생했습니다. 그래서 우선적으로 화면에 보여지는 row의 갯수만 지정해 주었습니다!

2023-02-28 07:48 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +        if segue.identifier == "itemDetailView" {
처음에는 다른 방식을 생각하지 못 하고 하드코딩으로 작업을 했습니다. `identifier`를 사용하는 부분 전부 static let으로 식별자를 설정하여 사용하는 방식으로 수정했습니다.

2023-02-28 07:48 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +final class ItemViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
박람회에 관한 내용을 담고있는 `ExpositionViewController` , 출품작의 리스트를 보여주는 `ItemListViewController`, 아이템의 상세 정보를 보여주는 `ItemDetailViewController`로 수정했습니다!

2023-02-28 07:52 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +            destination.prepareDescription = exhibitItems[selectedIndex].description
해당 코드는 `segue`를 사용하여 데이터를 전달하는 방법에 필요한 부분이었는데, 현재는 `initializer`를 사용한 방식으로 수정되어 코드가 변경되었습니다.

2023-02-28 07:54 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +    @IBOutlet weak var visitorNumberLabel: UILabel!
다음은 count와 number의 동사 의미입니다:
> Count (v) = How many are there.
> Number(v) = Give something a number.
동사를 기준으로 count는 수를 세는 것을, number는 수에 번호를 붙이는 것을 의미하는 것 같습니다. 얼마나 많은 방문자가 방문할 것인지에 대한 정보를 담고 있으므로 count가 더 적절할 것 같아 수정하였습니다. 감사합니다.

2023-02-28 07:55 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +        performSegue(withIdentifier: "itemDetailView", sender: nil)
`itemDetailView`는 `ItemDetailViewController`의 identifier 입니다.

처음 segue를 사용하기 전 `instantiateViewController(withIdentifier:)` 메서드를 사용해 구현을 시도했습니다. 하지만 storyboard에 만들어 놓은 뷰를 불러와 이니셜라이저를 정의하려고 하면 required initializer `init(coder:)`이 호출되어 에러가 발생했습니다. 

그래서 방법을 찾지 못하고 segue를 사용하는 방법으로 코드를 변경했었습니다. storyboard를 사용하여 뷰 컨트롤러 사이를 연결시켜 주고 데이터 전달을 구현했습니다. 하지만 해당 방법으로 구현할 경우 시각적으로 뷰 컨트롤러 간의 관계가 코드상으로 명확하게 확인할 수 없고 코드의 중복이 발생할 수 있다는 단점을 느꼈습니다. 

그러던 중 iOS 13부터 가능해진 `instantiateViewController(identifier:creator:)` 메서드를 학습할 수 있었습니다. 이는 NSCoding 프로토콜을 채택하고 있어 앞서 `instantiateViewController(withIdentifier:)` 메서드를 사용하면서 발생한 에러를 해결할 수 있었습니다.

2023-02-28 07:56 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +        cell.imageView?.image = UIImage(named: exhibitItem.imageName)
학습활동 시간에 해당 방식을 사용하여 보여주셔서 사용했는데, 추가적으로 공식문서를 확인하지 못 했습니다...🥲 
현재는 custom cell을 만들어 사용하는 방식으로 리팩토링 했습니다! 따라서 deprecated된 부분 또한 수정했습니다. `configure()` 메서드를 사용하여 해당 cell에 대한 정보를 전달하고 있습니다.

2023-02-28 07:56 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +        self.tableView.reloadData()
reloadData()는 테이블 뷰의 인스턴스 메서드로 테이블 뷰의 현재 보이는 row, section, index arrays를 업데이트할 때 사용합니다. 
특정 열, 섹션의 부분적인 업데이트가 아닌 테이블 뷰의 보여지는 전체 영역을 업데이트할 때 효율적인 메서드입니다. 
테이블 쥬의 동작 방식을 잘못 이해하여 사용한 것 갑습니다. 저희 코드에서는 데이터의 업데이트가 사용되지 않으므로 제거하였습니다!

2023-02-28 07:57 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +final class ItemViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
코드의 가독성을 위하여 `extension`을 사용하였습니다: 
[`1165f6f`](https://github.com/yagom-academy/ios-exposition-universelle/pull/251/commits/1165f6fd384a5644411eff42f0d53b8b97768d6b)
감사합니다.

2023-02-28 07:57 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        guard let itemVC = self.storyboard?.instantiateViewController(withIdentifier: "itemViewController") as? ItemViewController else { return }
약어 사용 지양해서 네이밍하겠습니다! 알려주셔서 감사합니다.

2023-02-28 07:57 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +    @IBAction func itemButtonTapped(_ sender: UIButton) {
감사합니다. 참고해서 수정 완료했습니다. 
앞으로 정확하게 연결된 제스쳐로 이름을 지어주는 습관을 들이도록 하겠습니다.

2023-02-28 07:58 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        self.navigationController?.isNavigationBarHidden = true
`isNavigationBarHidden`에 대한 내용을 각각의 뷰컨트롤러에서 `hideNavigationBar`라는 메서드로 분리해주었습니다. 
그리고 해당 메서드를 각각의 뷰컨트롤러의 `viewWillAppear` 안에 동일하게 넣어주었습니다.

2023-02-28 07:58 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        descriptionLabel.text = expositionUniverselle.description
`configureLabel`라는 이름의 메서드로 분리했습니다.

2023-02-28 07:58 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/ExhibitItemViewController.swift
> +    @IBOutlet weak var descriptionLabel: UILabel!
없을 것 같습니다. `IBOutlet`에도 `private`을 붙인다는 생각을 잘 해내지 못했습니다. 그래서 `private`을 붙이지 않았습니다. 모든 `IBOutlet`에도 `private`을 붙이는 방향으로 수정하였습니다.

그런데, 질문이 있습니다. `IBAction`의 경우는 어떻게 진행해야할까요? 구글링 해보니 `IBAction`에 private을 붙일 수 있지만, 잘 붙이지 않는다는 의견이 다수였습니다. 그래서 어떻게 해야할지 몰라 현재는 `IBAction`에는 `private`을 붙이지 않은 상태입니다. 엘림께서는 어떻게 생각하시는지 알고 싶습니다🙇🏻‍♀️

2023-03-02 10:17 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExhibitItemViewController.swift
> +    var prepareDescription: String = ""
타입 명시와 캐스팅은 다른 개념이라고 보시면 될거같아요~
<img width="1565" alt="스크린샷 2023-03-02 19 13 48" src="https://user-images.githubusercontent.com/49546979/222399270-d4a74a1f-2aa6-408e-9fc9-641fe4f5f8a2.png">
여러분이 사용한 함수의 리턴값은 UIViewController로 지정되어 있는데, 반드시 ItemViewController가 될 수 있을까요?ㅎㅎ...

타입 명시를 해주면 캐스팅을 해주지 않아도 된다는 생각이 어디서부터 출발되었을까요?!
마치 `var test = 0` 을 했을때 Int 타입으로 되기 때문이었을까요??

2023-03-02 10:18 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExhibitItemViewController.swift
> +    @IBOutlet weak var descriptionLabel: UILabel!
잘 붙이지 않는다는 의견이 다수라는건 어디서 나온거죠??
많은 사람들이 같은 의견을 생각하면 정답일까요??
여러분은 왜 private를 붙이지 않았는지가 더 중요할거같아요.
private은 무엇인가요? 접근제한자는 왜 붙이나요??

2023-03-02 10:19 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExhibitItemViewController.swift
> +        imageView.image = UIImage(named: prepareImage)
` 문법적으로 self를 필요로 하는 경우`는 언제인가요~?

2023-03-02 10:20 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        self.navigationItem.backButtonTitle = "메인"
struct로 만들수도 있었을 것 같은데요~ enum으로 생성하신 이유가 궁금합니다! (틀렸다는거 아님!!!!)

2023-03-02 10:20 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        self.navigationController?.isNavigationBarHidden = true
음.. 각각의 뷰 컨트롤라가 아니라 하나의 뷰컨트롤러 안에서 처리해주세요~

2023-03-02 10:22 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +    @IBOutlet var tableView: UITableView!
음... 뭔가 중요한게 빠진거같은데... 아무 키워드도 붙이지 않으면 strong인가요 weak인가요?
strong은 직접 기술하나요?
차이를 간단히 이해하는건 좋으나, 중요한 부분이 빠지면.. 안될거같아요😅

2023-03-02 10:27 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +        performSegue(withIdentifier: "itemDetailView", sender: nil)
identifier를 해당 viewController 이름과 동일하게 해주세요~

2023-03-02 10:42 UTC, lina0322 requested changes
한 번만 더 다듬어봅시다...! 잘 이해안가는거 DM주세용 화이팅!

2023-03-02 10:42 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/CustomTableViewCell.swift
> +class CustomTableViewCell: UITableViewCell {
final 붙여주세요~

2023-03-02 10:42 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/CustomTableViewCell.swift
> +    static let cellIdentifier = "cell"
프로토콜을 활용하여 CustomTableViewCell인 자신의 이름을 들고있게 할 수 있는 방법은 없을까요??

2023-03-02 10:42 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/CustomTableViewCell.swift
> +    @IBOutlet weak var itemImageView: UIImageView!
접근제어자 붙여주세요~

2023-03-02 10:42 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/CustomTableViewCell.swift
> +    }
혹시 아직 셀 재사용 관련해서는 배우지 않았나요??

2023-03-02 10:42 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        guard let itemsView: ItemListViewController = self.storyboard?.instantiateViewController(withIdentifier: ItemListViewController.viewIdentifier) as? ItemListViewController else { return }
view와 viewController는 다릅니다. 명확히 이해하고 네이밍 해주세요!

2023-03-02 10:42 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemDetailViewController.swift
> +        imageView.image = UIImage(named: imageName)
함수 분리 해주세요~

2023-03-02 10:42 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemDetailViewController.swift
> +    }
required init는 무엇인가요? fatalError로 앱이 꺼져도 괜찮나요?

2023-03-02 10:42 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemListViewController.swift
> +    }
함수 배치 순서를 어떻게 두고있나요??

2023-03-02 10:42 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Controller/ItemListViewController.swift
> +        }
creator를 사용해서 view를 생성하고있네요ㅎㅎ.. 사실 실무에서는 한번도 본적이 없는 코드이긴 합니다만.. 저만 그런걸수도있어서 조심스럽네요ㅎㅎ 제 눈엔 다소 어색한 방식으로 보이긴 합니다!

지금 viewController를 init할때 해주려고 한거같은데, 지난 코멘트에서 이유를 말씀해주셨는데 이해가 잘안가긴했어요..
```swift
let itemDetailView = storyboard?.instantiateViewController(withIdentifier: ItemDetailViewController.viewIdentifier) as? ItemDetailViewController
itemDetailView.item = item
```
이렇게 간단하게 값을 넘겨줄 수 있지 않나용??

2023-03-02 10:42 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Model/DecodingJson.swift
> +        guard let decodedExpositionUniverselle: ExpositionUniverselle = try? decoder.decode(ExpositionUniverselle.self, from: expositionUniverselle.data) else { return emptyData }
왜 굳이 나눠두셨나요??

2023-03-02 10:42 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Model/DecodingJson.swift
> +        let decoder: JSONDecoder = JSONDecoder()
매번 JSONDecoder를 생성할 필요가 있을까요??

2023-03-02 10:42 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Model/DecodingJson.swift
> +struct DecodingJson {
음.. 이름이 좀 이상해요..ㅎㅎㅎ 다른 좋은 이름은 없을까요?? 이러면 이름이 디코딩하는 **제이슨**이 되는거같아서요.

2023-03-02 10:42 UTC, lina0322 commented on Expo1900/Expo1900/Sources/Model/NameSpace.swift
> +}
관련해서 `%@`를 알아보는 것도 좋을거가아요
추가로 String을 String이라고 네이밍하지 않는 것이 좋습니다. text, title 등으로 사용해주세요~

2023-03-03 05:33 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/ExhibitItemViewController.swift
> +    @IBOutlet weak var descriptionLabel: UILabel!
저희가 제대로 선별되지 않은 정보를 읽었던 것 같습니다😢
이전의 경우 `IBAction`에 private을 붙이니 오류가 발생하여 불가능하다고 생각했었습니다. 하지만 이번에 다시 학습하여 붙여보니 정상 작동함을 확인했습니다. 아마 이전 코드의 경우 다른 곳에서 저희가 실수를 했었던 것 같습니다. 
private란 외부에서 private으로 선언한 속성/메서드에 접근하지 못하게 은닉화를 해주는 키워드입니다.
접근 제한자를 사용하는 이유는 대표적으로 은닉화, 영역을 분리하여 효율적인 관리 그리고 컴파일 시간의 감소가 있습니다!

2023-03-03 05:33 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        self.navigationItem.backButtonTitle = "메인"
struct와 enum 모두 NameSpace를 만들 수 있습니다. 그렇지만, struct로 만들 경우 인스턴스 생성이 가능해집니다. 물론, `private init() { }`를 사용하면, 그것을 막을 수 있습니다. 그렇지만, enum을 사용하게되면 그러한 작업 없이도 불필요한 인스턴스 생성을 막을 수 있기 때문에 enum으로 만들었습니다!

2023-03-03 05:34 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +    @IBOutlet var tableView: UITableView!
키워드가 없으면 기본값은 strong입니다. 따라서 직접 기술하지 않아도 됩니다.
다만 `ctrl+drag`를 통해 `IBOutlet`을 연결할 경우 weak로 자동 연결됩니다.
따라서 직접 작성하며 선언할 경우 weak를 빼고 작성한다면 기본값인 strong으로 자동 설정됩니다.
이 경우 불필요한 메모리를 차지할 수 있어 조심해야 한다고 생각합니다!

2023-03-03 05:35 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ExhibitItemViewController.swift
> +    var prepareDescription: String = ""
제(Rhode)가 오개념을 들은 것 같습니다. `opt`키를 누르고 항상 타입을 확인하도록 하겠습니다!!ㅠㅠ 그리고 타입과 타입캐스팅에 대해서도 자세히 다시 공부하도록 하겠습니다!!ㅠㅠ

2023-03-03 05:35 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/CustomTableViewCell.swift
> +class CustomTableViewCell: UITableViewCell {
수정했습니다. 감사합니다!

2023-03-03 05:35 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/CustomTableViewCell.swift
> +    @IBOutlet weak var itemImageView: UIImageView!
수정했습니다. 감사합니다!

2023-03-03 05:35 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ExhibitItemViewController.swift
> +        imageView.image = UIImage(named: prepareImage)
문법적으로 self를 필요로 하는 경우는 아래와 같습니다:

- 인스턴스를 가리키는 경우
- 값타입에서 인스턴스 자체의 값을 치환하는 경우
- 타입 인스턴스를 가리키는 경우

2023-03-03 05:36 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/ItemDetailViewController.swift
> +    }
required init은 필수 생성자로 다른 지정 생성자를 구현하지 않으면 자동으로 필수생성자가 상속됩니다. 
fatalError는 실행을 중단시키는데 custom view 에서 required init이 호출되면 안되기 때문에 사용했습니다. 
중요한 데이터를 넘기고 있는 과정이라 생각하며 해당 데이터가 넘어오지 않을 경우 앱이 꺼지는 것 보다 사용자에게 이를 알리는 알람을 전송하는 방법이 있다고 생각합니다!

2023-03-03 05:36 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        self.navigationController?.isNavigationBarHidden = true
하나의 viewController에서 작성하기 위해 `isNavigationBarHidden = false`를 `viewWillDisappear`에서 처리를 해줬습니다. 감사합니다!

2023-03-03 05:36 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/ExpositionViewController.swift
> +        guard let itemsView: ItemListViewController = self.storyboard?.instantiateViewController(withIdentifier: ItemListViewController.viewIdentifier) as? ItemListViewController else { return }
여기에서는 viewcontroller로 이름 붙여주는게 맞는 것 같습니다. 그래서 네이밍 수정하였습니다. 감사합니다!

2023-03-03 05:37 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Model/DecodingJson.swift
> +        let decoder: JSONDecoder = JSONDecoder()
각각의 메서드마다 JSONDecoder를 생성하여야한다고 생각했었는데, 
메서드의 밖 struct로 빼내도 문제 없이 잘 돌아가는 것을 확인했습니다. 
그래서 각각의 메서드 바깥, `Decoder`의 안으로 빼주었습니다.

2023-03-03 05:37 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/CustomTableViewCell.swift
> +    static let cellIdentifier = "cell"
`IdentifierType`이라는 프로토콜을 만들어주어 자신의 이름을 들고 있도록 하였습니다:
```swift
protocol IdentifierType {
    static var identifier: String { get }
}

extension IdentifierType {
    static var identifier: String {
        return String(describing: self)
    }
}

extension UIViewController: IdentifierType { }

extension CustomTableViewCell: IdentifierType { }
```
`CustomTableViewCell`뿐만 아니라 `ViewController`에서도 자신의 이름을 들고 있도록 수정하였습니다. 감사합니다!

2023-03-03 05:37 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Model/NameSpace.swift
> +}
%@는 문자열을 대체할 때, %d는 Int를 대체할 때 사용합니다. 
format specifier 개념을 사용하여서 enum을 수정해보았습니다:
```swift
enum NameSpace {
    static let emptyString = ""
    static let homeViewTitle = "메인"
    static let itemViewTitle = "한국의 출품작"
    static let visitorCountText = "방문객 : %d 명"
    static let locationText = "개최지 : %@"
    static let durationText = "개최 기간 : %@"
}
```
위와 같이 수정하였습니다. `static let visitorCountText = "방문객 : %d 명"`과 같이 사용해도 정상적으로 잘 작동이 될까 고민이 되었는데, 실제로 다음의 부분에서 문제 없이 사용이 되었습니다:
```swift
private func configureLabel() {
    let expositionUniverselle = Decoder().decodeExpositionJson()
    
    titleLabel.text = expositionUniverselle.title
    visitorCountLabel.text = String(format: NameSpace.visitorCountText, expositionUniverselle.visitorCount)
    locationLabel.text = String(format: NameSpace.locationText, expositionUniverselle.location)
    durationLabel.text = String(format: NameSpace.durationText, expositionUniverselle.duration)
    descriptionLabel.text = expositionUniverselle.description
}
```

2023-03-03 05:38 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/CustomTableViewCell.swift
> +class CustomTableViewCell: UITableViewCell {
수정했습니다. 감사합니다!

2023-03-03 05:38 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/CustomTableViewCell.swift
> +    @IBOutlet weak var itemImageView: UIImageView!
수정했습니다. 감사합니다!

2023-03-03 05:39 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ItemDetailViewController.swift
> +        imageView.image = UIImage(named: imageName)
반영하여 수정했습니다! 감사합니다!

2023-03-03 05:40 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ItemListViewController.swift
> +    }
처음에는 호출되는 순서만으로 배치를 두는게 맞다고 생각해서 그 순서대로 배치하였습니다. 그런데 적절한 순서가 있다는 것을 알아서 수정했습니다. 저희가 정한 함수 배치 순서는 다음과 같습니다:
 - 프로퍼티 -> init -> override methods(view의 lifecycle과 관련한 methods) -> custom methods 순서로 정렬합니다.
 - 각각의 순서 안에서는 먼저 호출되는 순으로 순서를 정렬합니다.

2023-03-03 05:40 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Model/DecodingJson.swift
> +        guard let decodedExpositionUniverselle: ExpositionUniverselle = try? decoder.decode(ExpositionUniverselle.self, from: expositionUniverselle.data) else { return emptyData }
하나의 guard let 문으로 묶었습니다:
```swift
guard let expositionUniverselle: NSDataAsset  = NSDataAsset(name: "exposition_universelle_1900"),
      let decodedExpositionUniverselle: ExpositionUniverselle = try? decoder.decode(ExpositionUniverselle.self, from:
expositionUniverselle.data)
else { return emptyData }

...

guard let items: NSDataAsset = NSDataAsset(name: "items"),
      let decodedItems: [ExhibitItem] = try? decoder.decode([ExhibitItem].self, from: items.data)
else { return emptyArray }
```
감사합니다!

2023-03-03 05:40 UTC, christy-hs-lee commented on Expo1900/Expo1900/Sources/Controller/ItemListViewController.swift
> +        }
해당 방법의 경우 저희가 시도했던 방법 중 하나였습니다... 그러나 custom initializer를 통한 프로퍼티 주입 과정에서 required initializer인 init(coder:)가 호출되는 에러가 발생하여 현재 저희가 사용하는 [instantiateViewController(identifier:, creator:)](https://developer.apple.com/documentation/uikit/uistoryboard/3213989-instantiateviewcontroller) 메서드를 사용했습니다😭

2023-03-03 05:41 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Model/DecodingJson.swift
> +struct DecodingJson {
`Decoder`라는 이름으로 수정하였습니다. 감사합니다. 네이밍에 좀 더 유의하겠습니다!!

2023-03-03 05:42 UTC, Rhode-park commented on Expo1900/Expo1900/Sources/Controller/ItemViewController.swift
> +        performSegue(withIdentifier: "itemDetailView", sender: nil)
반영하여 수정했습니다! 감사합니다!!

2023-03-03 05:56 UTC, lina0322 reviewed
다음 스텝에서 계속 디벨롭 해봅시다~!

2023-03-03 05:56 UTC, merged