만국박람회 [STEP 3] 혜모리, Andrew
yagom-academy/ios-exposition-universelle pull request #254
Opened 2023-03-01 06:39 UTC by Andrew-0411

@junbangg  안녕하세요! 알라딘 STEP3 PR 보내드립니다 

## 고민했던점 & 조언을 얻고 싶은 점

### 1. Table View Cell의 서브 뷰의 길이만큼 동적 height를 주는 방법

- 커스텀 셀에서 이미지, 이름, 간단 소개글을 각각 셀 내에서 오토 레이아웃을 적용하였는데
아래와 같이 간단 소개글을 줄바꿈 처리하면 셀 밖으로 빠져나가는 현상이 생겼습니다.
![](https://i.imgur.com/w8h9Vjr.png)
- 이름, 간단 소개글 Label을 스택 뷰로 묶고, 그 스택뷰와 이미지를 또 다시 스택뷰로 묶어 오토레이아웃을 주니 셀의 height가 동적으로 늘어났습니다.

### 2. 세로모드 고정

- 메인페이지는 가로모드로 변경이 되어서는 안된다는 조건이 있었습니다.
`AppDelegate` 클래스 내부에 지원하는 화면 방향을 설정해주는 `supportedInterfaceOrientationsFor` 메서드를 사용하여 처리하였습니다.
- `changeOrientation` 프로퍼티를 `false`로 주면 `.portrait`(세로 고정)로 설정되고, `true`로 주면 모두 가능하도록 구현하였습니다.

``` swift
// AppDelegate 클래스 내부
var changeOrientation: Bool = true

func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
    if changeOrientation == false {
        return [.portrait]
    } else {
        return [.all]
    }
}
```

뷰 컨트롤러에는 `UIApplication`의 싱글톤을 사용하여 세로모드 고정 여부를 적용하였습니다.
``` swift
open class var shared: UIApplication { get }
```
아래 코드와 같이 뷰가 나타날 때 세로모드로 고정되게 하였고, 뷰가 사라지려고 하면 다시 모든 방향을 지원합니다.

``` swift
// ExpoInfoMainViewController 클래스 내부
private let delegate = UIApplication.shared.delegate as! AppDelegate

// ...
override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    navigationController?.navigationBar.isHidden = true
    delegate.changeOrientation = false

}

override func viewWillDisappear(_ animated: Bool) {
    super.viewWillDisappear(animated)
    navigationController?.navigationBar.isHidden = false
    delegate.changeOrientation = true
}
```

### 3. SceneDelegate에서 전역으로 설정
```swift!
// SceneDelegate.swift
UILabel.appearance().adjustsFontForContentSizeCategory = true
```
- 모든 View가 SceneDelegate를 바라보기 때문에 SceneDelegate에서 설정하면 모든 View가 영향을 받는걸로 알고 있습니다. 
- 그래서 UILabel의 Dynamic Type을 설정하기 위해서 UILabel에 `adjustsFontForContentSizeCategory = true` 옵션값을 주어야 했는데 SceneDelegate에서 옵션을 주어 모든 Label에 설정되게 하였습니다.
- 이 방법이 적절한 방법인지 아니면 SceneDelegate의 사용을 지양하시는지 지양하신다면 왜 지양하시는지 이유가 궁금합니다

### 4. Dynamic Type 설정
- Dynamic Type을 Label에 설정하기 위해 각각의 Lable마다  
label.font = .preferredFont(forTextStyle: .body)로 설정했습니다. 
- 설정값이 똑같기 때문에 모든 Label에 일괄적으로 옵션에 적용해주기 위해 Protocol을 사용하는 방법, extension으로 UILabel을 확장해서 사용하는 방법, SceneDelegate에서 `UILabel.appearance()`을 생각해봤습니다. 
- 알라딘은 일괄적으로 적용해야 할 때 어떤 방법을 권장하시고 권장하시는 이유가 무엇인지 궁금합니다

### 5. UITableViewController 상속
- TableView를 사용해야 되는 View에는 UITableViewController를 상속받는 방법과 UIViewController 상속받고 필요한 기능만 프로토콜을 채택해서 (UITableViewDelegate,UITableViewDataSource) TableView 객체를 생성해서 사용하는 방법 두가지가 있습니다.
- 이번 프로젝트는 전자의 방법으로 UITableViewController를 상속받아서 만들었는데 알라딘은 저 두가지 방법중에서 어떤 방법을 선호하시며 선호하시는 이유가 궁금합니다

2023-03-02 14:39 UTC, junbangg requested changes
> 알라딘은 일괄적으로 적용해야 할 때 어떤 방법을 권장하시고 권장하시는 이유가 무엇인지 궁금합니다
코멘트에 남겼지만 저는 일괄적으로 적용해야되는 경우는..거의 없다고 생각하는 편이에요 ..! 무조건 따로따로 하는게 좋다고 생각하는 편입니다..! 
그렇지만 뭐 뭐든지 케바케이고 정답은 없는거니까~ 일괄적으로 무언가를 적용해야되는 경우에는(꼭 UI 가 아니더라도)나중에 공부하시게 되겠지만 protocol을 활용하여 POP로 한번 도전해보는것도 나쁘지 않을것 같네요!

> UITableViewController 상속
이건 사람마다 다르겠지만 저는 확실히 상속 보다는 프로토콜 두개 따로따로 extension 이용해서 채택하는 방법을 선호해요!
그리고 각각 extension에 각 protocol 메서드를 사용해서 정리도 되는 자연스럽게 느낌이 들어서 좋아합니다:)

2023-03-02 14:39 UTC, junbangg commented on Expo1900/Expo1900/Controller/EntryTableViewController.swift
> +        let entry: Entry = entryList[indexPath.row]
오 Entry 라는 타입을 명시적으로 딱 써주셨는데 이유가 있나요?(틀렸다는거 아닙니다)

2023-03-02 14:39 UTC, junbangg commented on Expo1900/Expo1900/Controller/EntryTableViewController.swift
> +        tableView.rowHeight = UITableView.automaticDimension
이걸 여기 cellForAt에서 설정하신 이유가 있나요?

2023-03-02 14:39 UTC, junbangg commented on Expo1900/Expo1900/Controller/ExpoInfoMainViewController.swift
> +        guard let buttonTitleLabel = nextViewButton.titleLabel else { return }
제가 요걸 잘 이해 못한거 같은데 buttonTitleLabe을 왜 빼서 사용하신거죠..???? 여기만 봤을때 레이아웃을 구성하기 위해 하신것 같은데

2023-03-02 14:39 UTC, junbangg commented on Expo1900/Expo1900/View/CustomTableViewCell.swift
> +        }()
오 이렇게 메서드 안에서 클로져 사용하는거 색다르군요
이렇게 하신 이유가 있나요??

2023-03-02 14:39 UTC, junbangg commented on Expo1900/Expo1900/Controller/SceneDelegate.swift
> +        UILabel.appearance().lineBreakMode = .byWordWrapping
질문 주셨던 내용 같은데 저는 개인적으로 이렇게 하는것보다 차라리 필요한 곳곳마다 명시적으로 정해주는게 나을것 같아요.
이것 또한 확장성을 생각했을때 더 좋을것 같다는 의견입니다.
지금은 저런 공통적인 특징들이 있어서 글로벌하게 설정할 수 있지만 요구사항이 바뀔 확률이 아주 농후하다고 생각합니다. 그래서 필요한 곳곳마다 명시적으로 설정을 해줘야 **변경 사항이 있을때** 변경하는 사람도 헷갈리지않고, 더 유연하게 변경사항에 대응할 수 있을것 같아요. .!

2023-03-02 14:39 UTC, junbangg commented on Expo1900/Expo1900/Model/UILabel+extension.swift
>          attributedText = attributedString
저번에 질문 주셨던거 찾아서 해결하셨군요👍

2023-03-03 04:11 UTC, Andrew-0411 commented
constraint 깨진건 어떤걸 말씀하시는건가요? 시뮬레이터를 돌렸을 때 정상적으로 UI가 잡히는데 실행을 안해보신걸까요?

2023-03-03 04:13 UTC, Andrew-0411 commented on Expo1900/Expo1900/Controller/EntryTableViewController.swift
> +        tableView.rowHeight = UITableView.automaticDimension
cell안에 있는 text의 길이에 따라서 tableViewCell의 높이를 유동적으로 설정하려고 테스트해보다가 삭제하는걸 잊었던거 같습니다.

2023-03-03 04:22 UTC, Andrew-0411 commented on Expo1900/Expo1900/Controller/SceneDelegate.swift
> +        UILabel.appearance().lineBreakMode = .byWordWrapping
필요한곳에만 설정해서 수정하였습니다

2023-03-03 04:23 UTC, hyemory commented on Expo1900/Expo1900/Controller/ExpoInfoMainViewController.swift
> +        guard let buttonTitleLabel = nextViewButton.titleLabel else { return }
다이나믹 타입으로 폰트 크기를 최대로 늘리니 
아래 캡쳐 이미지와 같이 박람회 설명과 화면 이동하는 버튼끼리 겹치는 현상이 있었습니다.

<img width="310" alt="image" src="https://user-images.githubusercontent.com/115605734/222630070-e24c79c8-f9f8-4a90-b6cc-a01eae4ce179.png">

Button의 크기가 Button 안에 들어있는 Label 만큼 height가 늘어나지 않아 발생한 현상으로
Button의 height가 Label 만큼 늘어나게 하기 위해 따로 빼서 오토레이아웃을 적용하였습니다.

``` swift
buttonStackView.heightAnchor.constraint(equalTo: buttonTitleLabel.heightAnchor),
```

2023-03-03 04:41 UTC, Andrew-0411 commented on Expo1900/Expo1900/Controller/EntryTableViewController.swift
> +        let entry: Entry = entryList[indexPath.row]
코드 컨벤션이 통일되지 않았다는걸 느꼈고 그래서 타입이 명시적으로 필요한곳을 제외하고 전부 타입 추론으로 변경하였습니다.

2023-03-03 04:42 UTC, hyemory commented on Expo1900/Expo1900/View/CustomTableViewCell.swift
> +        }()
lazy var를 제거하는 과정에서 구현된 메서드인데 만들어 두었던 스택뷰 상수를 
그대로 복붙하는 과정에서 불필요한 클로저가 되었습니다 😅
비슷하게 불필요해진 상수는 제거하겠습니다!

2023-03-04 04:36 UTC, junbangg commented on Expo1900/Expo1900/Controller/EntryTableViewController.swift
> +        let entry: Entry = entryList[indexPath.row]
이론적으로는 타입 명시 해놓으면 컴파일러가 조금 더 좋아한다고 하더라고요??눈에 띄는 성능 차이는 없겠지만 ~ 그렇다고는 하더라고요??

2023-03-04 04:37 UTC, junbangg commented on Expo1900/Expo1900/Controller/ExpoInfoMainViewController.swift
> +        guard let buttonTitleLabel = nextViewButton.titleLabel else { return }
아하 네넵 이해했습니다~

2023-03-04 04:37 UTC, merged