만국박람회 [STEP3] Harry, 레옹아범
yagom-academy/ios-exposition-universelle pull request #255
Opened 2023-03-01 07:40 UTC by fatherLeon

@AppleCEO 
안녕하세요 도미닉 벌써 마지막 스텝 PR올리게 되었네요...
마지막 스텝도 잘 부탁드립니다!!!

## 고민한 점

### adjustsFontSizeToFitWidth
![](https://i.imgur.com/ZudqgN9.gif)
#### 문제점
- Font 크기를 사용자의 기기폰트 사이즈와 같게끔 하면 글자가 잘리거나, 한줄이 여러줄이 되거나 하는 등의 문제가 있었습니다.
- 원래 Label안의 텍스트가 여러줄이었다면 똑같이 여러줄을 표시해주면 좋을것 같다고 생각하지만, 제목과 같은 한줄 Label은 사용자 기기의 폰트 크기가 아무리 커도 한줄을 유지하는 것이 좋겠다고 생각하였습니다.

#### 해결방법
- [adjustFontSizeToFitWidth](https://developer.apple.com/documentation/uikit/uilabel/1620546-adjustsfontsizetofitwidth) UILabel 프로퍼티를 사용하여 Label의 너비에 맞춰서 폰트사이즈를 조정함으로 너비가 safeArea의 끝까지 길어지는 경우 더 이상 폰트 사이즈가 커지지 않고 기존 한줄로 유지되도록 만들었습니다.

<br>

### attribute Text에 Dynamic Type 적용하기
- 기존 방식의 문제점
    - 레이블 3개를 사용했습니다.
    - 각각의 레이블 마다 텍스트의 글자 수가 달라서 접근성 검사기에서 폰트 크기를 키워주면 3개의 레이블의 폰트 크기가 제각각이었습니다.
    - 파리 만국 박람회의 정보를 알려주는 레이블이라 폰트의 크기가 같아야 보기가 좋을것 같다고 생각했습니다.

- 해결책 1
    - UIView의 프로퍼티 사용해서 콘텐츠의 최대 또는 최소 크기를 제한 할 수 있었습니다.
```swift
var minimumContentSizeCategory: UIContentSizeCategory?
var maximumContentSizeCategory: UIContentSizeCategory?
```

- 해결책 2
    - 3개로 나누어져 있던 레이블을 한 개의 레이블로 통합시키기
    - 줄 바꿈 문자열을 추가해서 총 3줄이 출력될 수 있도록 하고, attributed text를 적용해서 폰트 크기를 다르게 할 수 있도록 할 수 있었습니다.

- 결론
    - 해결책 2번을 선택했습니다.
    - 해결책 1번 같은 경우는 구현하기는 아주 간단하지만 iOS 15버전 이상부터 적용되는 프로퍼티이므로 범용성이 없다고 생각하여 해결책 2번으로 문제를 해결했습니다.

### 특정화면에서 화면전환을 막기
- 특정화면에서 화면전환을 막는 방법에 대해서 2가지 방법을 고민했습니다.
    1. AppDelegate 내에서 변수를 생성하여 화면전환 가능 여부를 체크하도록 하는 방법
    2. NavigationController내에서 `supportedInterfaceOrientations`를 상속받아 사용하는 방법
- 위 두가지 방법 중 첫번째 방법의 경우 UIApplication.shared로 구현된 싱글톤 인스턴스를 뷰 컨트롤러로 가져와 설정을 해줘야했습니다.
- 이는 싱글톤의 단점 중 하나인 코드의 결합도를 높이다라는 문제점으로 인해 `NavigationController`를 상속받는 커스텀 네비게이션 컨트롤러를 만들어주는 두번째 방법으로 구현하였습니다.

```swift
override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
    guard let _ = self.topViewController as? MainPosterViewController else { return .all }
        
    return .portrait
}
```
- NavigationController는 자료구조인 Stack처럼 쌓이는 모양새를 가지고 있는데 위에 쌓인 topViewController는 현재 사용자가 보고있는 ViewController이므로, 해당 뷰 컨트롤러가 만약 `MainPosterViewController`라면 `.portrait`를 해당 프로퍼티에 넣어주어 세로화면만을 사용하도록 만들었습니다. 

## 조언을 얻고 싶은 부분

### 가로모드에서의 layout constraints Error
#### **커스텀 셀에 지정한 레이아웃 제약**

- 기존 코드(ExhibitionEntryTableViewController)
``` swift
NSLayoutConstraint.activate([
    exhibitionImage.widthAnchor.constraint(equalTo: exhibitionImage.heightAnchor),
    exhibitionImage.widthAnchor.constraint(equalTo: self.contentView.widthAnchor, multiplier: 0.2)
])
```
- 출력된 에러코드
``` bash
Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600000feb8e0 UIImageView:0x12e5574d0.width == UIImageView:0x12e5574d0.height   (active)>

```

<br>

- 수정 후 코드
``` swift
let heightAnchor = exhibitionImage.widthAnchor.constraint(equalTo: exhibitionImage.heightAnchor)
    heightAnchor.priority = .defaultHigh
    heightAnchor.isActive = true
        
    NSLayoutConstraint.activate([
        exhibitionImage.widthAnchor.constraint(equalTo: self.contentView.widthAnchor, multiplier: 0.2)
    ])
```

- 에러가 발생했던 제약에 priority를 다른 제약보다 낮게 설정하였더니 에러 문구가 사라졌습니다.
- 너비와 높이가 같으면서, 너비는 현재 cell너비의 2/10만큼의 크기를 가지도록 주었기 때문에 높이 역시 너비와 같은 크기가 될 거라고 생각했습니다.
- 이미지 뷰를 찍어보니 너비와 높이가 꽤나 비슷하긴 하지만 실제로는 0.2~0.4 이런식으로 다른 크기를 보여줬습니다.
- 이러한 이유가 이미지뷰의 contentMode가 .scaleAspectFit으로 설정했기 때문에 위 오토레이아웃과 충돌이 나는 것인지 궁금합니다.

2023-03-02 01:08 UTC, AppleCEO requested changes
안녕하세요. 도미닉입니다.
@fatherLeon , @HarryHyeon  고생하셨습니다~

몇가지 코멘트 드립니다.
댓글들 확인해주세요. 추가로 아래 내용들도 고민해보시면 좋을 것 같습니다.
1. 한 줄에서 여러 번 init 메소드가 호출되면 코드가 복잡해보이는 것 같습니다. 한 줄에서 (( 이런 식으로 여러 번 생성자가 있는 코드들에서 줄을 여러 줄로 나눠볼 수 있을까요?
2. 상세 화면에서 한 단어가 길어질 경우 다음 줄로 넘어가는 식으로 구성이 잘되었네요. 혹시 이 옵션 말고 한 줄에 텍스트가 꽉 찰 수 있도록도 한번 추가로 구성해볼까요? 어떤 게 정답이라는 건 아니지만 꽉 차는 것도 한번 해보면 좋을 것 같습니다~
3. 추가 미션으로 0.2 와 같은 숫자를 하드코딩하지 않고 상수로 사용해 볼 수 있을까요? 하드코딩은 최대한 지양해야 합니다!
# 조언 요청에 대한 답변

## 가로모드에서의 layout constraints Error
오 우선순위를 설정하여 해결을 해보셨군요! 수치가 약간 다르게 나오는 것은 저번처럼 같이 화면공유하고 봐도 좋겠네요. 캡처 화면과 같이 질문 게시판에 올려주셔서 다른 분들도 같이 확인해봐도 좋겠습니다!

2023-03-02 01:08 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/MainPosterViewController.swift
>          configureFooter()
추상화 수준이 같도록 구성되니 더 좋네요!

2023-03-02 01:08 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/MainPosterViewController.swift
> +        paragraphStyle.lineSpacing = 8
오우 lineSpacing 을 사용해보셨군요. 🔢 
이 프로퍼티는 어떤 동작을 하나요?

2023-03-02 01:08 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/DetailViewController.swift
여기 공백이 어떤 의미가 있을까요?
코드에는 공백이나 줄바꿈 하나에도 의미가 있어야 합니다.
의도를 나타낼 수 있는 최소한의 줄바꿈을 추천드려요.
무조건 적은 줄의 코드가 좋다는 뜻은 아닙니다~

2023-03-02 06:49 UTC, HarryHyeon commented on Expo1900/Expo1900/Controller/MainPosterViewController.swift
> +        paragraphStyle.lineSpacing = 8
NSMutablePragarphStyle 객체를 사용해서 스타일(줄간격, 정렬 등등)을 지정하고,
Attribute Text의 attribute를 추가해 한 줄의 하단과 다음 줄의 상단 간의 간격을 설정할때 사용할 수 있습니다.

2023-03-02 06:52 UTC, fatherLeon commented on Expo1900/Expo1900/Controller/DetailViewController.swift
```swift
label.numberOfLines = 0
label.font = .preferredFont(forTextStyle: .body)
label.text = self.exhibitionItem.description
label.adjustsFontForContentSizeCategory = true
label.lineBreakMode = .byCharWrapping
```

* 이 부분은 컨벤션 실수입니다!!
* UI 속성부분은 줄 바꿈 없이 위와 같이 작성하였습니다.

2023-03-02 08:28 UTC, HarryHyeon commented
> 1. 한 줄에서 여러 번 init 메소드가 호출되면 코드가 복잡해보이는 것 같습니다. 한 줄에서 (( 이런 식으로 여러 번 생성자가 있는 코드들에서 줄을 여러 줄로 나눠볼 수 있을까요?
- `Style Share`라는 회사의 Style Guide를 참고하여 99자를 기준으로 긴 줄에대해 개행을 해주었습니다. 
- [Swift Style Guide - Style Share](https://github.com/StyleShare/swift-style-guide#readme)

> 2. 상세 화면에서 한 단어가 길어질 경우 다음 줄로 넘어가는 식으로 구성이 잘되었네요. 혹시 이 옵션 말고 한 줄에 텍스트가 꽉 찰 수 있도록도 한번 추가로 구성해볼까요? 어떤 게 정답이라는 건 아니지만 꽉 차는 것도 한번 해보면 좋을 것 같습니다~
```swift
label.lineBreakMode = .byCharWrapping
```
- 위 lineBreakMode를 `.byCharWrapping`을 사용하여 화면을 꽉 찰 수 있도록 DetailViewController와 MainViewController를 수정하였습니다.
- 말씀하신대로 어느게 좋은지는 잘 모르겠지만, 폰트가 작을때는 단어별로 자르는게 더 좋아보이고 폰트가 클 때는 위와 같이 꽉 찬 화면이 조금 더 보기 편한 것 같습니다.

> 3. 추가 미션으로 0.2 와 같은 숫자를 하드코딩하지 않고 상수로 사용해 볼 수 있을까요? 하드코딩은 최대한 지양해야 합니다!
- 레이아웃 제약을 줄때 사용하는 상수는 `LayoutConstant` 타입에 정의하여 사용했습니다.
- 네비게이션바의 제목에 사용하는 문자열은 `NavigationBarTitle` 타입에 정의하여 사용했습니다.
- 에셋에 접근하여 데이터셋이나 이미지를 가져올 때 사용하는 파일명은 `AssetName` 타입에 정의하여 사용했습니다.

```swift
enum LayoutConstant {
    static let spacing: CGFloat = 8
}

enum NavigationBarTitle {
    static let mainTitle = "메인"
    static let tableViewTitle = "한국인 출품작"
}

enum AssetName {
    static let mainPosterDataset = "exposition_universelle_1900"
    static let tableViewDataset = "items"
    
    static let posterImage = "poster"
    static let flagImage = "flag"
}
```

2023-03-02 08:41 UTC, fatherLeon commented
### 가로모드에서의 layout constraints Error
- 이 부분에대해서 저희끼리는 물론이고, 다른 8기분들과도 이야기 나눠본 결과는 exhibitionImage의 너비에 관한 제약을 두개가 주어져있는데 우선순위가 정해져있지않아서 제약끼리 충돌이 나는것으로 결론을 냈습니다!!!

2023-03-02 14:03 UTC, AppleCEO approved these changes
고생하셨습니다!
많이 더 좋아진 것들이 보이네요~
추가로 오해한 부분이 있으신 것 같은데 저는 초기화하는 함수 같은 곳은 한 줄로 쭉 이어지는 컨벤션을 선호합니다.
이전 코멘트는 여러 변수를 한 줄에서 생성하는 곳을 의미했습니다.
예를 들면 UIImageView(UIImage(name: "construct"))
이런 코드가 있다면 
let image = UIImage(name: "construct")
let imageView = UIImageView(image)

라는 식으로 나누는 것을 의도했습니다!
참고해주시고 머지 원하면 말씀해주세요~

2023-03-02 14:03 UTC, AppleCEO commented on Expo1900/Expo1900/View/ExhibitionEntryCell.swift
> +                                                constant: -10),
아... 제가 조금 더 명확하게 말씀드릴 걸 그랬네요.
저는 이런 부분은 오히려 한 줄로 길게 쓰는 것을 선호합니다!

2023-03-02 14:03 UTC, AppleCEO commented on Expo1900/Expo1900/Controller/ExhibitionEntryTableViewController.swift
> +        self.navigationItem.title = NavigationBarTitle.tableViewTitle
오 제목까지 하드코딩을 제거하셨군요! 너무 보기 좋네요~ 🥇

2023-03-02 14:03 UTC, AppleCEO commented on Expo1900/Expo1900/View/ExhibitionEntryCell.swift
> +
여기 공백은 어떤 의도가 있을까요?

2023-03-02 14:03 UTC, AppleCEO commented on Expo1900/Expo1900/View/ExhibitionEntryCell.swift
> +        let widthMultiplier = 0.2
상수로 빼낸 부분 좋습니다~
추가로 조금 더 의도가 이름에 드러나도 좋겠네요.
지금은 길이곱하기 라고 해석이 되는데 어떤 이유로 이 숫자를 곱하는지 이름에서 드러나면 좋겠습니다.

2023-03-02 14:03 UTC, AppleCEO commented on Expo1900/Expo1900/View/ExhibitionEntryCell.swift
> -        // 우선순위가 높으면 먼저 계산하는가?
주석을 제거한 부분 좋네요~

2023-03-03 01:43 UTC, fatherLeon commented on Expo1900/Expo1900/View/ExhibitionEntryCell.swift
> +
* 저희끼리 상수, 변수 등을 할당한 이후에는 개행을 주고, 상수와 변수 할당이 모여져 있을 경우 개행을 하지 않고 쓰기로 했습니다.
* 코드 확인하다보니 이 부분이 잘 안지켜져 있는 것 같아서 추가적으로 수정했습니다!!!

2023-03-03 01:55 UTC, HarryHyeon commented on Expo1900/Expo1900/View/ExhibitionEntryCell.swift
> +        let widthMultiplier = 0.2
길이의 특정한 비율을 지정하는 것이라는 의미에서 `lengthRatio`라고 변경 해주었습니다.

2023-03-03 04:54 UTC, merged