만국박람회 [STEP3] 세홍, 무리, 송준
yagom-academy/ios-exposition-universelle pull request #256
Opened 2023-03-01 12:53 UTC by kimseongj

@1Consumption
안녕하세요 올라프! ⛄️ 
세홍, 무리, 송준 조의 세번째 스텝 PR입니다!
많은 난항을 겪었지만.. 이번 리뷰도 잘부탁드립니다!😁
</br>
## 고민했던 부분
### 1️⃣ 동일한 Label에서 다양한 font size 표현하기
- 동일한 Label에 다양한 font size를 넣기 위해서는 `NSMutableAttributedString`을 사용해야 한다는 것을 알았습니다.
- `NSMutableAttributedString`은 class타입으로 특성 문자열의 내용을 변경하기 위한 추가 메서드입니다.
- 저희 조의 경우 `NSMutableAttributedString`를 `extension`해서 사용했습니다.
- `attributes`변수를 선언하고 font의 특성을 저장한 후, 매개변수로 받아온 `string`에 적용시켜주었습니다.

```swift
extension NSMutableAttributedString {
    func makeBigText(string: String) -> NSMutableAttributedString {
        let metric = UIFontMetrics(forTextStyle: .body)
        let font = metric.scaledFont(for: UIFont.systemFont(ofSize: 17))
        let attributes: [NSAttributedString.Key: Any] = [.font: font]
        append(NSAttributedString(string: string, attributes: attributes))
        
        return self
    }
    
    func makeNormalText(string: String) -> NSMutableAttributedString {
        let metric = UIFontMetrics(forTextStyle: .body)
        let font = metric.scaledFont(for: UIFont.systemFont(ofSize: 17))
        let attributes: [NSAttributedString.Key: Any] = [.font: font]
        append(NSAttributedString(string: string, attributes: attributes))
        
        return self
    }
}
```

### 2️⃣ NSMutableAttributedString에서 Dynamic Type 적용하기
- Dynamic Type을 적용시켜주기 위해서 해당 label에 `adjustsFontForContentSizeCategory`을 true로 적용시켜주면 됩니다.
- `adjustsFontForContentSizeCategory`는 `UIContentSizeCategoryAdjusting`이라는 protocol 안에 선언되어 있으며, 이 protocol은 폰트의 형태가 변할 때 자동적으로 업데이트 해주는 역할을 한다고 합니다. 
- 그래서 `adjustsFontForContentSizeCategory`를 `true`로 해놓으면 폰트 형태가 변할 때 자동적으로 업데이트를 해줍니다.

```swift
        label.adjustsFontForContentSizeCategory = true
```

- 하지만 `NSMutableAttributedString`에서 동일한 방법을 사용하면 안되는 오류가 생겼습니다. 
- 이를 해결하기 위해 `UIFontMetrics`를 사용했습니다.
- `UIFontMetrics`는 Dynamic Type을 지원하도록 확장되는 사용자 지정 글꼴을 얻기 위한 유틸리티 개체입니다.
- `scaledFont`를 사용하여 현재 채택되어 있는 글꼴을 반환시켜줍니다.

```swift
extension NSMutableAttributedString {
    func makeBigText(string: String) -> NSMutableAttributedString {
        let metric = UIFontMetrics(forTextStyle: .body)
        let font = metric.scaledFont(for: UIFont.systemFont(ofSize: 17))
        let attributes: [NSAttributedString.Key: Any] = [.font: font]
        append(NSAttributedString(string: string, attributes: attributes))
        
        return self
    }
}
```
</br>

## 해결하지 못한 부분 
### 1️⃣ 프로젝트에서 dynamic Type을 적용하였는데 글씨크기를 크게하면 버튼과 바로 위 레이블이 겹치는 문제
아래 사진처럼 글씨크기가 커지면 겹치는 문제가 발생하는데 해결하지 못하였습니다. contentHuggingPriority를 사용해서 조절하는 방식을 사용했는데 적용이 되지 않아 해결 방법에 대한 키워드를 알고 싶습니다. 
<p align="center">
  <img src="https://i.imgur.com/TPx7pPf.png" align="center" width="45%">
  <img src="https://i.imgur.com/rVNlYRm.png" align="center" width="45%">
  </figcaption>
</p>

</br>

## 조언을 얻고싶은 부분
### 1️⃣ 버튼 클릭시 로직 구현 하는 부분 
현재는 저희 코드에서 `MainViewController` -> `ExpoItemListViewController`로 넘어가는 코드는 아래와 같이 `tapButton`함수에 `addTarget`를 사용하여 이동하는 방식을 사용하고 있습니다. `iOS14`부터 `UIButton의 UIAction`에 `addAction`메서드를 사용하여 더 간편하게 사용할 수 있다고 하는데 이전 버전의 iOS를 지원해야한다면 addTarget을 고려하지 않을수가 없을 것 같습니다. 앞으로 어떤 방식을 사용하는 것이 효율적인지 궁금합니다.   
```swift
private func tapButton() {
    pushExpoItemListViewButton.addTarget(self, action: #selector(pushToExpoItemListViewController), for: .touchUpInside)
}
    
@objc func pushToExpoItemListViewController() {
let expoItemListViewController = ExpoItemListViewController()
    self.navigationController?.pushViewController(expoItemListViewController, animated: true)
}
```

2023-03-02 16:00 UTC, 1Consumption requested changes
고생하셨습니다. @kimseongj @parkmuri @sehoong0429 

객체를 역할별로 나누려고 노력한게 눈에 보이네요👍
덕분에 리뷰하기 좋았습니다.

코멘트를 남겼으니 참고해주세요. 

### 1️⃣ 프로젝트에서 dynamic Type을 적용하였는데 글씨크기를 크게하면 버튼과 바로 위 레이블이 겹치는 문제
아래 사진처럼 글씨크기가 커지면 겹치는 문제가 발생하는데 해결하지 못하였습니다. contentHuggingPriority를 사용해서 조절하는 방식을 사용했는데 적용이 되지 않아 해결 방법에 대한 키워드를 알고 싶습니다. 
> 코멘트에 남겼습니다. 코멘트를 참고해주세요.

### 1️⃣ 버튼 클릭시 로직 구현 하는 부분 
> 둘 다 하면 좋습니다.

2023-03-02 16:00 UTC, 1Consumption commented on Expo1900/Expo1900/App/AppDelegate.swift
> +        }
AppDelegate에서 전역적으로 접근하지 말고, UINavigationViewController를 오버라이딩해서 화면 전환을 제어해보세요.

2023-03-02 16:00 UTC, 1Consumption commented on Expo1900/Expo1900/App/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
이 코드에 대해서 설명해주실 수 있나요?

2023-03-02 16:00 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +    private lazy var listTableView: UITableView = {
lazy var를 사용한 이유는 뭔가요?

2023-03-02 16:00 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        tableView.translatesAutoresizingMaskIntoConstraints = false
이 코드는 어떤 역할을 하나요?

2023-03-02 16:00 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +            rootViewController?.present(alertController, animated: true)
굳이 root를 찾아서 알러트를 띄워주는 이유가 있나요?
전역 변수에 바로바로 접근하는게 좋아보이지는 않네요.

2023-03-02 16:00 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        title = "한국의 출품작"
title을 변경하는건 layout이랑 관련이 있나요?

2023-03-02 16:00 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        itemDetailViewController.receiveData(from: decodedExpoItem.expoItems[indexPath.row])
만약 expoItems의 count보다 indexPath의 row가 크거나 같으면 어떻게 되나요?

2023-03-02 16:00 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ItemDetailViewController.swift
> +    }()
var인 이유가 있을까요?

2023-03-02 16:00 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ItemDetailViewController.swift
> +        stackView.distribution = .fill
distribution의 기본값은 fill인데 fill을 할당해준 이유가 있을까요?

2023-03-02 16:00 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ItemDetailViewController.swift
> +        expoItemImage = cell.imageName
`ExpoItem`과 `cell`이라는 매개변수 이름은 무슨 상관이 있나요?

2023-03-02 16:00 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        AppDelegate.portraitOrientation = false
이 작업은 다음 viewController에서 하는게 더 맞아보여요. 왜냐하면 현재 화면 회전은 viewController에 종속되어 있기 때문입니다. 만약 다음 viewController도 portrait라면 다음 viewController에 종속된 작업이지만 여기서 수행해야하네요.

2023-03-02 16:00 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        } catch { }
에러를 분기치지말고 `LocalizedError` 프로토콜을 채택해 `localizedDescription`를 사용해보세요.

2023-03-02 16:00 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        buttonStackView.addArrangedSubview(pushExpoItemListViewButton)
pushExpoItemListViewButton의 baseLineAnchor에 대해서 알아보세요. dynamic type에 대한 답이 될거 같습니다.

2023-03-02 16:00 UTC, 1Consumption commented on Expo1900/Expo1900/NameSpace/NameSpace.swift
> +    static let colon = ": "
뒤에 공백도 빼주세요. 이거도 사용하는데서 결정할 일 같습니다.

2023-03-03 02:19 UTC, sehoong0429 commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +    private lazy var listTableView: UITableView = {
해당 코드에서 lazy var를 사용한 이유는 객체에 접근하기 전에  listTableView 객체 생성을 막기 위해서입니다. 또한 lazy var를 사용하지 않으면 dataSource를 설정하기 전에 tableview가 초기화 되지 않아서 에러가 발생합니다. 필요한 시점에 객체를 초기화하면서 초기화 과정에서 발생할 수 있는 에러를 미리 예방하고 메모리를 절약할 수 있는 장점이 있습니다.

2023-03-03 02:19 UTC, sehoong0429 commented on Expo1900/Expo1900/App/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
저희는 스토리보드를 사용하지 않고 인터페이스를 생성하려고 SceneDelegate에서 window를 직접 생성했습니다.

`windowScene`:  UIWindowScene은 하나의 앱이 다수의 윈도우를 가질 수 있도록 해주고 각 윈도우는 별로의 windowScene 객체를 가지며 이 객체를 통해 윈도우가 어떤 화면에 띄워질지 결정할 수 있습니다. 
`window`: UIWindow 는 iOS 화면에서 보이는 객체를 의미합니다. windowScene을 이용해서 새로운 UIWindow객체를 생성하고 navigationController를 rootViewController로 설정해주고 있습니다. 
`makeKeyAndVisible()`: 해당 메서드는 UIWindow 객체를 화면에 보이도록 하는 메서드 입니다. 생성된 window 객체에 해당 메서드를 호출하여 화면을 보여주고 있습니다.

2023-03-03 02:21 UTC, sehoong0429 commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        tableView.translatesAutoresizingMaskIntoConstraints = false
해당 코드는 UITableView를 생성하고 초기화하는 역할을 합니다. 
- tableView.estimatedRowHeight: Cell의 높이를 자동으로 조절할 때 초기에 예상되는 높이 설정
- tableView.dataSource: TableView의 데이터 소스를 현재 클래스의 인스턴스로 설정
- tableView.delegate: TableView의 델리게이트를 현재 클래스의 인스턴스로 설정
- tableView.translatesAutoresizingMaskIntoConstraints: AutoLayout을 사용할때 코드로 제약 조건을 지정하기 위해 필요하고 TableView가 autoresizingMast를 사용하지 않도록 설정

2023-03-03 02:21 UTC, kimseongj commented on Expo1900/Expo1900/Controller/ItemDetailViewController.swift
> +        stackView.distribution = .fill
기본값이 `.fill`인것을 확인 못했습니다.ㅎ
해당 부분은 중복된 부분인것 같아 삭제 했습니다.

2023-03-03 02:29 UTC, kimseongj commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        title = "한국의 출품작"
관련이 없습니다. title을 변경하는 것은 setNavigationBar와 관련이 있다고 생각되어 이동시켰습니다.

7b7b6ea67bced8e6244525eb7a8d5fd942a2e2fe

2023-03-03 03:01 UTC, parkmuri commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        } catch { }
- 올라프의 코멘트를 참고하여 extension을 이용하여 LocalizedError를 채택한 후, LocalizedDescription을 이용하는 방법으로 수정해보았습니다. 

7e7efadff71118f8a50812d05a30625881b6c4af

2023-03-03 03:01 UTC, parkmuri commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +            rootViewController?.present(alertController, animated: true)
- 에러처리해주는 과정에서 해당 코드는 삭제하였습니다!

7e7efadff71118f8a50812d05a30625881b6c4af

2023-03-03 05:05 UTC, sehoong0429 commented on Expo1900/Expo1900/App/AppDelegate.swift
> +        }
6394278137d615d5c9d3bf327ef2c628d4e82605

UINavigationController를 상속받는 class를 만들어서 구현해보았습니다. 
해당 클래스에서는 UINavigationController에서 이미 정의된 supportedInterfaceOrientations 프로퍼티를 override하여 현재 표시되는 viewControllerdml supportedInterfaceOrientations 프로퍼티 값을 반환해주는데 여기서는 topViewController가 nil인 경우 현재 표시되는 viewController가 없는 경우에는 [.all] 모든 방향을 지원할 수 있도록 기본 값을 설정해주었습니다.

2023-03-03 05:07 UTC, sehoong0429 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        AppDelegate.portraitOrientation = false
감사합니다. 해당 부분은 UINavigationController를 오버라이딩 하는 방식으로 변경되어 삭제 되었습니다.

2023-03-03 05:12 UTC, parkmuri commented on Expo1900/Expo1900/Controller/ItemDetailViewController.swift
> +        expoItemImage = cell.imageName
```swift
extension ExpoItemListViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let navigationController = self.navigationController
        let itemDetailViewController = ItemDetailViewController()
        itemDetailViewController.receiveData(from: decodedExpoItem.expoItems[indexPath.row])
        navigationController?.pushViewController(itemDetailViewController, animated: true)
    }
}
```
- ExpoItemListViewController에서 ItemDetailViewController의 `receiveData()`를 호출하고있습니다. 호출되는 때가 테이블뷰에서 didSelectRowAt, 어떠한 Row가 선택될때이기 때문에 cell에 표시된 ExpoItem의 정보라는 의미로 사용하게되었습니다.

2023-03-03 05:14 UTC, sehoong0429 commented on Expo1900/Expo1900/Controller/ExpoItemListViewController.swift
> +        itemDetailViewController.receiveData(from: decodedExpoItem.expoItems[indexPath.row])
Index out of range 오류가 발생할 것 같습니다.

2023-03-03 05:30 UTC, parkmuri commented on Expo1900/Expo1900/Controller/ItemDetailViewController.swift
> +    }()
- main.storyboard를 사용할 때 `@IBOutlet weak private var`로 선언하여 사용했었습니다. 스토리보드 대신 UI를 코드로 작성하며 IBOutlet 키워드를 삭제하는 과정에서 변수로 남겨두어 이와같은 실수가 있었습니다.
코멘트를 참고하여 `let`으로 선언하였습니다!

46583693919dd1934dd3abd6f05ec19fde1ae13b

2023-03-03 07:20 UTC, sehoong0429 commented on Expo1900/Expo1900/NameSpace/NameSpace.swift
> +    static let colon = ": "
d1afdc809b4693088eb6bdfc052da03ea4d03e47 
namespace에 공백을 하나 선언하여 처리해주었습니다.

2023-03-03 07:23 UTC, sehoong0429 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        buttonStackView.addArrangedSubview(pushExpoItemListViewButton)
해당 부분에 대해서 저희가 정말 많이 찾아보고(자료가 없기도하고요ㅠ) 적용을 시켜봤지만.. 
```swift 
pushExpoItemListViewButton.lastBaselineAnchor.constraint(equalToSystemSpacingBelow: descriptionLabel.bottomAnchor, multiplier: 1.0)
```
과 같은 코드를 추가하면 numberoflines가 적용이 되지 않는 문제가 발생하고.. 무언가 깔끔한 처리가 안되는 것 같습니다.. 
다른 키워드나 도움을 받고싶습니다.. ㅠㅠㅠㅠㅠ!!!!

2023-06-22 09:10 UTC, closed without merging