만국박람회 [STEP 1] Karen
yagom-academy/ios-exposition-universelle pull request #269
Opened 2023-06-27 09:31 UTC by karenyang835

@YebinKim

안녕하세요. 븨븨~
이번에 븨븨의 리뷰를 받게 된 `karen`입니다. 편하게 '카렌'이라고 불러주시면 됩니다.😊

`JSON`을 활용해서 데이터를 받아오는 것도 처음이고, `JSON`을 활용하여 본격적으로 `Model`을 구현하는것도 처음이라 생소하여 다소 오랜 시간이 소요되었지만 븨븨께서 배려해주신 덕분에 무사히 `Step1`을 완료했습니다.

아직 많이 부족하지만 븨븨께서 해주시는 조언 꼼꼼히 읽어보고, 새겨듣도록 하겠습니다.

2주 동안의 만국박람회 프로젝트 리뷰 잘 부탁드립니다.🙇🏻‍♀️

## 🤔 고민한 부분
### 1️⃣ `JSON` 포멧의 데이터와 매칭할 모델 타입 구현
- `JSON`이라는 것도 생소했고, `JSON`을 매칭할 모델 타입을 구현한다는 것 자체가 어디서부터 어디까지 해야될지도 막막했습니다. 미션에서 주어진 것은 `JSON`파일 자체를 `import`하는 단계까지는 아닌 것 같고 `JSON`의 데이터를 `Parsing`할 수 있는 정도로만 구현하면 될 것 같았습니다.

### 2️⃣ 네이밍 컨벤션
> `JSON`은 자바스크립트 객체 표기에서 리터럴과 프로퍼티를 표현하는 방법만 가져와서 사용하는 것으로 자바스크립트 언어로부터 영감을 받아 개발된 데이터형식입니다. 
- 자바크스립트의 경우 변수명 표기법이 카멜 케이스와 스네이크 케이스를 둘 다 사용하기 때문에 카멜 케이스만 활용하는 `swift`에서 "_"를 활용해서 네이밍을 하는 스네이크 케이스에 대처를 해주어야했습니다. `CodingKeys`를 활용하여 해결했습니다.

### 3️⃣ Decoding만 구현
> `Encoding` : 일련의 데이터를 `JSON`형식으로 변환하는 과정
> `Decoding` : `JSON`형식의 데이터를 해당 데이터 형식으로 변환하는 과정
- 맨 처음에는 `Codable`의 프로토콜을 채택을 했었습니다. `Codable` 프로토콜을 채택하면 `Encoding`에 활용하는 `Encodable`와 `Decoding` 할 수 있는 `Decodable` 모두 활용이 가능해지는데 만국박람회 프로젝트에서 `Encoding`를 할 경우는 없어보여서 `Decoding`시 활용하는 `Decodable`만 활용하여 구현했습니다.

### 4️⃣ Nil값의 처리
- `JSON`데이터의 값으로는 `Number`, `String`, `Boolean`, `Object`, `Array`, `NULL과` 같은 타입이 올 수 있다고 명시되어져 있어서, `NULL`은 `Swift`에서의 `nil`값인것으로 알고 있습니다. `nil`값이 들어왔을 때의 처리를 해주어야 된다고 생각되어져서 `Decodable` 프로토콜내에 존재하는 `init` 생성자를 이용하여 안전하게 파싱 작업을 진행했습니다.

--- 

<br>

## 🙇🏻‍♀️ 조언을 얻고 싶은 부분
### 1️⃣ `Codable`를 채택했어야 했을까요?
- 현재 제가 파악하기로는 `Decoding`만 활용되어질 것 같아 `Decodable`를 채택했지만 `Encoding`를 할 경우가` Step3`에서 나올 수도 있으니 `Codable`를 채택했어야 하는게 맞을까요?

### 2️⃣ `struct`와 `class` 중 선택 기준을 어떻게 잡으면 될까요?
- 전 `struct`와 `class`의 선택의 기로에 섰을 때 되도록이면 `struct`를 선택하게 됩니다. 왜냐하면 `Apple`에서도 `struct`를 지향하라고 했기에 무의식적으로 `struct`를 활용하게 되는데요. 제가 생각하기에는 간단한 내용이고 굳이 상속되어질 일도 없을 것 같아서 `struct`로 활용을 하긴 했는데 혹시 선택하는 기준에 조금 더 염두해 두고 할 수 있는 부분이 있을까요?
    - 예를 들어서 메모리 활용 부분을 생각해서 선택하라던가 제가 모르는 성능의 차이라던가 하는 부분처럼 추가로 염두해 두고 선택되어져야 할 사항이 있다면 조언 부탁드립니다.
- 아직 메모리 활용 부분에 대한 이해도와 배움이 부족해서 메모리 활용 부분은 거의 배제하고 선택을 하게 되는데 이 부분에 대해서 혹시 제가 참고해서 볼 수 있는 부분이 있다면 조언 부탁드립니다.(검색어라던가 힌트도 괜찮습니다.)
- 사실 상속 부분도 명확하게 인지하기가 힘든 부분도 있습니다. 과연 이 인스턴스가 상속이 되어질것인지 아닌지도 아직 명확하게 기준을 세우기가 어렵습니다. 어떤 부분을 생각하면 조금 더 쉽게 접근해서 판단할 수 있을까요?

2023-06-27 15:50 UTC, YebinKim requested changes
카렌 안녕하세요~!! 
2주간 만국박람회 프로젝트를 함께하게 된 비비입니다 🥳🎉
서로 자주 소통하며 마무리까지 달려보아요!!

또한, 리뷰 코멘트 확인 전 아래 내용 한 번 확인 부탁드릴게요~

```
코멘트는 중요도에 따라 priority 1~5 로 등급을 매겨 작성하고 있습니다.
p1이 가장 수정을 위한 우선 순위가 높으며,
p5는 수정을 해도 OK, 안 해도 OK 정도로 우선 순위가 낮습니다.

또한, p1, p2 코멘트가 있을 때는 Request Changes 를 요청드리고 있습니다.
참고 부탁드려요 🙇
```

---

### 1. Codable를 채택했어야 했을까요?

현재 요구사항 안에서 필요가 없다면 `Decodable` 로 충분하다는 생각입니다! 😄
추후 Encoding 이 필요하다면 그때 현재 구현한 타입에 `Codable` 을 채택하거나 새로운 Encoding 타입을 만들어볼 수 있을 거 같아요.



### 2. struct 와 class 중 선택 기준을 어떻게 잡으면 될까요?

타입을 만들면서 어떤 방식을 선택할 지는 꼭 한 번씩 고민하게 되는 거 같아요.
두 타입을 고르는 것에 있어서 정답은 없기 때문에 현재 카렌이 알고 계신 범위 안에서 **선택의 근거를 설명할 수 있다면, 그 이상을 고려하진 않아도 괜찮다는 생각입니다** ☺️

만약 메모리 활용 부분에 대해 struct 와 class 의 성능 차이를 알아보고 싶으시다면 Apple Document 중 [Choosing Between Structures and Classes](https://developer.apple.com/documentation/swift/choosing-between-structures-and-classes) 아티클이나 [WWDC16 - Understanding Swift Performance](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiv0aqG4-P_AhX8glYBHY4VAAAQwqsBegQIDRAB&url=https%3A%2F%2Fdeveloper.apple.com%2Fvideos%2Fplay%2Fwwdc2016%2F416%2F&usg=AOvVaw0JeXd8TXvb55UEKzmZROaS&opi=89978449) 영상 등을 추천해드릴 수 있지만 지금 각 자료의 모든 키워드와 동작 원리를 이해하기보다는 이런 내용도 있다고 생각하며 가볍게 훑어보시는 것을 권장드립니다.

상속의 경우에는 타입을 설계함에 있어서 상속 구조가 필요할지 아닐지를 먼저 생각해볼 수 있을 것으로 생각되는데요. 현재 만든 타입이 추후 상속이 될 가능성을 고려하기 보다는 **여러 타입의 공통된 특성들을 모아서 설계 단계에서부터 상속 구조를 만드는 게** 좀 더 잦은 활용 방법이라고 생각됩니다.
또한, 단순히 class 를 활용한 수직 상속 구조 뿐만 아니라 protocol 을 활용한 수평 확장 구조로도 추상화와 다형성을 구현할 수 있을 거 같아요 😄

그래서 상속을 활용하고자 하신다면 우선 요구사항을 분석해서 필요한 기능과 타입을 먼저 설계하고, 이 중 공통된 특성이 무엇이 있는지를 파악하는 것이 시작이라고 생각됩니다!



### 3. Nil값의 처리
고민한 부분도 상세히 공유해주신 덕분에 각 타입을 어떤 생각으로 설계하셨는지 더 잘 파악할 수 있었는데요.
혹시 Nil 값의 처리 부분에서 옵셔널 타입으로 `description` 프로퍼티를 선언하는 방법 등도 고려해보셨을까요?

---

Step1 진행까지 고생 많으셨어요 카렌! 😆👍
이번 스텝에서는 JSON 포맷의 데이터와 매칭할 모델 타입을 설계하는 것이 중심이었기 때문에 코멘트가 많지 않은데요.

코멘트와는 별개로 현재 빌드 오류가 발생하고 있어서 Request Changes 로 요청드렸어요!
`Info.plist` 파일을 옮긴 커밋 748a4c4 에 의해 문제가 발생한 것으로 보이는데, 이 부분만 수정되면 바로 Step2 진행으로 넘어가도 괜찮을 거 같아요~

그 외 궁금한 점 있다면 언제든 깃헙 코멘트 또는 DM 부탁드려요 🙌🥳

2023-06-27 15:50 UTC, YebinKim commented on Expo1900/Expo1900/Model/Items.swift
> +        }
p3;

Optional 값 처리를 위해 `InternationalExposition.swift` 에서는 nil 병합 연산자(`??`) 를 사용했는데 `Items` 타입에서는 if 문을 사용한 것으로 보이네요! 👀
두 타입에서의 방법을 다르게 한 이유가 있을까요?

2023-06-27 20:39 UTC, karenyang835 commented on Expo1900/Expo1900/Model/Items.swift
> +        }
이 부분을 제가 놓친것 같습니다.

처음에 `if let`로 두 구조체에 구현했었다가 굳이 `if let`보다는 `nil`병합연산자로 표기하는게 훨씬 깔끔하게 적용이 되어질 것 같다 생각되어 `InternationalExposition`에는 적용을 하고 `Items`에는 적용을 못하고 누락한 것 같습니다.

또한, `description`부분만 옵셔널 값 처리를 했었는데 수정하면서 다시 한 번 코드를 보면서 생각해보니 `shortDescription`도 `nil`이 충분히 들어올 수 있을 것 같아 추가적으로 `nil`병합연산자로 적용해주었습니다.

아직 코드 작성 부분이 많이 미숙하여서 발생한 사항인 것 같습니다. 앞으로는 조금 더 꼼꼼하게 체크하고 보도록 하겠습니다. 

꼼꼼하게 리뷰해 주셔서 감사합니다.🙇🏻‍♀️

2023-06-27 21:03 UTC, karenyang835 commented
>3. Nil값의 처리
고민한 부분도 상세히 공유해주신 덕분에 각 타입을 어떤 생각으로 설계하셨는지 더 잘 파악할 수 있었는데요.
혹시 Nil 값의 처리 부분에서 옵셔널 타입으로 description 프로퍼티를 선언하는 방법 등도 고려해보셨을까요?

이 부분은 전혀 생각을 못했었습니다. 
어찌보면 해당 방법이 더 단순하게 적용할 수 있고, 옵셔널 바인딩을 사용하지 않고도 해당 프로퍼티에 접근이 가능해 훨씬 용이할 것 같아 해당 프로퍼티를 옵셔널 타입으로 적용해주었습니다.
븨븨의 가르침으로 또 하나 배우게 되었습니다. 감사합니다. 🙇🏻‍♀️


>코멘트와는 별개로 현재 빌드 오류가 발생하고 있어서 Request Changes 로 요청드렸어요!
Info.plist 파일을 옮긴 커밋 https://github.com/yagom-academy/ios-exposition-universelle/commit/748a4c4055657ab9701a992c0d0127230c222559 에 의해 문제가 발생한 것으로 보이는데, 이 부분만 수정되면 바로 Step2 진행으로 넘어가도 괜찮을 거 같아요~

해당 빌드 오류도 수정 완료했습니다.🥹
빌드를 마지막에 한번 더 확인 후에 PR을 보냈어야 했는데, 체크하지 못하고 보내서 죄송합니다.🙇🏻‍♀️
이번에 븨븨의 리뷰 덕분에 한가지 더 꼼꼼히 챙겨야되는 부분을 확인한 것 같습니다. 
감사합니다 븨븨~

2023-06-28 01:59 UTC, YebinKim approved these changes
카렌 안녕하세요~
수정해주신 내용 확인했습니다!

빌드 정상적으로 수행되는 것 확인하였고, 이번 스텝에서의 목표는 모두 달성했다고 생각돼 이대로 머지 진행할게요 😄
다음 스텝 진행도 화이팅입니다 💪🔥

2023-06-28 01:59 UTC, YebinKim commented on Expo1900/Expo1900/Model/Items.swift
> +    }
p4;

Decodable의 [init](https://developer.apple.com/documentation/swift/decodable/init(from:)-8ezpn) 은 기본 구현이 제공되기 때문에 지금과 같이 디코딩 중 특별히 값을 변경하지 않는 경우에는 `init` 을 생략할 수도 있습니다! 😄

2023-06-28 01:59 UTC, merged

2023-06-28 03:09 UTC, karenyang835 commented on Expo1900/Expo1900/Model/Items.swift
> +    }
오옷 감사합니다. 참고하도록 하겠습니다.