Step 3 : 오토레이아웃 적용 (리나)
yagom-academy/ios-exposition-universelle pull request #27
Opened 2020-12-26 15:34 UTC by lina0322

안녕하세요오 좋은 주말입니다😆
~~(주말 밤에 이렇게 PR 안 보내려면, 방학 끝나고 나서는 평소에 더 열심히 해야겠다는 생각을 하며...)~~

---
__1. 오토 레이아웃을 적용했습니다.__
사실 step2에서 스크롤 뷰 하면서 어느 정도 적용을 해서, 많이 바뀌진 않았습니다.

__2. 모든 화면에 Dynamic Type을 적용했습니다.__
요것도, step2에서 의도치 않게 대부분 해서, 빠진 부분만 적용했습니다.

__3. custom cell을 만들었습니다.__
이리저리 아무리 찾아봐도.. 오토 레이아웃을 적용하기에 custom cell이 제일 간편할 것 같아서 시도해보았습니다.

__4. 첫 화면은 세로, 나머지 화면은 회전이 가능합니다.__
회전을 한 경우에도 화면이 정상적으로 보일 수 있도록 노력했습니다.

5. 앞선 스텝에서 다루지 않았던, (글씨 크기나 줄바꿈 같은) 사소한 것들을 조금 수정했습니다.

---

#### [의문 사항]
상세 구현 조건에 `모든 텍스트가 잘리거나 줄임표(...) 처리가 되지 않도록 합니다.`가 있는데 
이렇게 되는 경우가 어떤 건지 잘 모르겠습니다.
그래서 화면이 잘 보이긴 하는데, 대처를 한 것 같진 않아서 어떤 경우인지 살짝 여쭤봅니다!!🥺

오늘도 시간 내주셔서 감사합니다.🙇🏻‍♀️

2020-12-27 05:42 UTC, yagom requested changes
텍스트가 잘리는 경우는 레이블이 텍스트의 길이보다 표현할 수 있는 줄의 제약이 더 작은 경우(예, 글은 긴데 레이블이 한 줄 짜리인 경우 등)에 넘치는 글자를 어떻게 처리하는지 line break를 설정할 수 있습니다.

많은 것을 해냈지만 몇 가지 부족한 점이 있어 이야기해봅니다.

1. 실행 중에는 눈치채기 어렵지만, 스토리보드에선 부족하거나 애매(ambiguous)한 제약이 존재합니다. 가로모드 포함
<img width="1119" alt="스크린샷 2020-12-27 오후 2 34 41" src="https://user-images.githubusercontent.com/3423048/103164642-44dfca80-4851-11eb-9551-bc5310cedee5.png">

<img width="352" alt="스크린샷 2020-12-27 오후 2 31 30" src="https://user-images.githubusercontent.com/3423048/103164637-37c2db80-4851-11eb-9ab4-489a558db835.png">
<img width="369" alt="스크린샷 2020-12-27 오후 2 31 37" src="https://user-images.githubusercontent.com/3423048/103164638-3abdcc00-4851-11eb-9e6f-c2493d9774e1.png">

2. 앱이 실행중인 상태에서 설정앱을 통해 글자크기를 변경하면 앱에서 바로 반영되지 않습니다. 
3. 뒤로가기 버튼의 텍스트가 올바르지 않습니다.
4. 키보드를 사용할 수 있으며, 텍스트를 편집할 수 있습니다. 더불어 키보드가 내려가지 않아 사용상에 어려움이 있습니다.
<img width="392" alt="스크린샷 2020-12-27 오후 2 35 39" src="https://user-images.githubusercontent.com/3423048/103164644-4dd09c00-4851-11eb-898f-9333b9d9ec89.png">

2020-12-27 05:42 UTC, yagom commented on Expo1900/Expo1900/DetailViewController.swift
> +final class DetailViewController: UIViewController {
👍

2020-12-27 05:42 UTC, yagom commented on Expo1900/Expo1900/DetailViewController.swift
> +    private func setUpEntryInformation() {
initiate, setUp, configure, build, set 등의 표현 차이에 대해서는 어떻게 생각하나요?

2020-12-27 05:42 UTC, yagom commented on Expo1900/Expo1900/EntryListViewController.swift
> +            return UITableViewCell()
혹여나 기본 셀을 반환한다 하더라도 기본적인 정보는 담아서 보여주는건 어떻게 생각하나요? :)

2020-12-27 05:42 UTC, yagom commented on Expo1900/Expo1900/NavigationController.swift
> +final class Navigationcontroller: UINavigationController {
내비게이션 컨트롤러에서 제어해준 것은 좋은아이디어네요!
기획이 변경되어 세로 고정인 뷰 컨트롤러가 늘어나면 확장에 용이하려나요? :p

2020-12-27 08:35 UTC, lina0322 commented
@yagom 🐻

꼼꼼한 리뷰 감사합니다!
오늘도 많은 것을 배웠네요🕵🏻‍♀️

나름 열심히 봤다고 생각했는데;
정말 빈틈이 많은 PR이었습니다.. 부끄러워요🙀

말씀해주신 부분들을 수정하기위해 열심히 노력해보았습니다!
혹시 또 부족한 부분이 있다면 말씀해주세욥🙇🏻‍♀️

### [1번]
> initiate, setUp, configure, build, set 등의 표현 차이에 대해서는 어떻게 생각하나요?

이전에도 set과 setUp에 대해서 얘기를 나눈적이 있었던 것 같은데욥 ~~(정확히 기억이 안나네욯ㅎㅎㅎ)~~
__set__ 은 무언가를 `고정`시키는 것으로, 버튼이나 이미지 등의 위치를 지정해 주는 것에 set이 어울린다고 생각했습니다.
비슷한 이름의 __setUp__ 은 `준비하다(세팅하다), 건설하다(bulid), 깔다(install)` 등의 의미로 사용할 수 있는데요. 제가 사용했던 의미는 준비, 혹은 세팅하다의 의미였습니다!
처음에 아무생각 없이 set으로 했다가, 고정의 의미보다는 정보를 보여주기위해 준비한다는 의미가 더 맞다고 생각해서 수정했습니다.

그리고 이외에
__initiate__ 는 `개시되게 하다`는 뜻으로, 변수 초기화(variable initialization)를 이야기할때 가장 많이 사용하는 단어인것 같습니다. 요 단어도 참 좋은 단어인데, 제가 사용했던 함수는 뭔가 변수를 하나씩 초기화 해준다는 느낌보다 아울렛에 이미 들어있는 프로퍼티들에 값을 할당해주는 것 같아서 패스했습니다!
__configure__ 은 `(컴퓨터의) 환경을 설정하다`라는 의미인데.. apple configurator처럼 뭔가 좀 더 큰 사이즈고, 거창한 느낌이여서 패스했습니다.
__bulid__ 는 진짜 뭔가 install처럼 설치하는 느낌이어서... 마찬가지로 패스했습니다.

개인적으로는 setUp이 적당히 가볍게(?) 사용하기 좋은 것 같아서 계속 애용하게 되는 표현입니다ㅎㅎㅎㅎ


### [2번]
> 혹여나 기본 셀을 반환한다 하더라도 기본적인 정보는 담아서 보여주는건 어떻게 생각하나요? :)

셀이 아예 비어있으면 오류로 alert를 띄운다는 건 생각해봤는데, 커스텀 셀이 아니라 기본셀일때 정보를 담아준다는건 생각을 전혀 못했던 부분이라! 적용을 해보고 싶었습니다.
그래서 살짝 시도해봤는데, 이런쪽을 말씀하신건지 확인해주실 수 있을까요?!
image는 사이즈들이 다 달라서 복잡해보일 것 같고, 적당히 title과 subtitle정도만 표시될 수 있게 시도해보았습니다!


### [3번]
> 기획이 변경되어 세로 고정인 뷰 컨트롤러가 늘어나면 확장에 용이하려나요? :p

ㅎㅎㅎㅎ... 같은 네비게이션 컨트롤러에 뷰가 늘어난다면 그나마 괜찮을 것 같은데....
새 네비게이션 컨트롤러가 생기면 쉽진않겠네요..
가볍게 생각했는데 너무 어려워요오우엉ㅇ어어 화면회전...🌪
~~(기획서 변경 안됐으면...)~~
요건.. 좀 더 좋은 방법이 있는지 고민해보겠습니다...ㅎ3ㅎ...



시간내주셔서 감사합니다아👍

2020-12-28 06:40 UTC, yagom approved these changes
부끄러워 마십시오. 아주 훌륭히 해내고 있습니다. 성장하지 못하는게 부끄럽지 쭉쭉 틀리는 것은 아주 자랑스러운 일입니다. 🥇 

cell의 contents configuration을 활용했네요! 좋아요 :) 👍 
그런데 만약 이 앱의 배포 타깃의 OS 버전이 낮아진다면 어떻게 하는 것이 좋을까요?
이번 프로젝트에 요구사항으로는 없지만 배포 버전 연습도 중요해요 :)

화면 회전 제어에 관해서는 오동나무 @odongTree 랑 이야기 했었는데요, 같이 이야기 나눠보세요.

요청하면 머지하겠습니다 :) 즐거운 한 주 되길!

2021-04-07 14:06 UTC, closed without merging