만국박람회 [STEP 2] Erick, 비모
yagom-academy/ios-exposition-universelle pull request #271
Opened 2023-06-28 06:21 UTC by bubblecocoa

@July911 
안녕하세요 July!
Erick & 비모입니다!
만국박람회 STEP2 PR 보냅니다.
잘 부탁드립니다 🙇

---
## July의 질문

### JSON이 무엇인가?
JSON(제이슨, JavaScript Object Notation)은 속성-값 쌍(attribute–value pairs), 배열 자료형(array data types) 또는 기타 모든 시리얼화 가능한 값(serializable value) 또는 키-값 쌍으로 이루어진 데이터 오브젝트를 전달하기 위해 인간이 읽을 수 있는 텍스트를 사용하는 개방형 표준 포맷입니다.

- JSON은 서로 다른 기기에서 데이터를 주고 받기 위해 통상적으로 사용하는 데이터 포멧입니다.
- Swift에서 사용하는 객체를 JSON으로 인토딩하는 과정을 직렬화, 디코딩하는 과정을 역직렬화라고 이해했습니다.

🔗 참고링크
- [🌐 위키백과 - JSON](https://ko.wikipedia.org/wiki/JSON)
- [🌐 위키백과 - 개방형 표준](https://ko.wikipedia.org/wiki/%EA%B0%9C%EB%B0%A9%ED%98%95_%ED%91%9C%EC%A4%80)
- [🌐 위키백과 - 직렬화](https://ko.wikipedia.org/wiki/%EC%A7%81%EB%A0%AC%ED%99%94)
- [🍎 Developer Apple - Archives And Serialization](https://developer.apple.com/documentation/foundation/archives_and_serialization)

### JSON Decoder의 역할은 무엇인가?
JSON 포맷으로 념거진 텍스트를 어떠한 타입으로 변환시키는 역할을 합니다.

🔗 참고링크
- [🍎 Developer Apple - Encoding Decoding And Serialization](https://developer.apple.com/documentation/swift/encoding-decoding-and-serialization)
- [🍎 Developer Apple - Using JSON With Custom Types](https://developer.apple.com/documentation/foundation/archives_and_serialization/using_json_with_custom_types)
- [🍎 Developer Apple - JSONDecoder](https://developer.apple.com/documentation/foundation/jsondecoder)

### meta type 은 무엇인가?
클래스, 구조체, 열거형 및 프로토콜을 포함한 모든 **타입의 타입**을 `meta type`이라고 합니다.

**예시**
```swift
let metatype: String.Type = String.self  // String.Type
```
- `String.Type`은 `String`의 메타타입이며 `String.self`는 `String`이라는 타입 그자체이며 `String.Type`의 인스턴스입니다.

🔗 참고링크
- [🍎 Developer Apple - Metatype Type](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/types/#Metatype-Type)
- [🍎 Developer Apple - decode(_:from:)](https://developer.apple.com/documentation/foundation/jsondecoder/2895189-decode)

### TableView 는 왜 사용하는걸까?
- 여러 건의 구조화 된 데이터나 계칭이 있는 데이터를 순차적으로 보여주기 위해 사용합니다.

🔗 참고링크
- [🍎 Developer Apple - UITableView](https://developer.apple.com/documentation/uikit/uitableview)
- [🍎 Developer Apple - Table Views](https://developer.apple.com/documentation/uikit/views_and_controls/table_views)

### delegate 와 dataSource는 무엇인가?
TableView 기준으로 답변드리겠습니다.

**TableView**
- TableView는 정보를 표시하기 위해 `delegate`와 `dataSource`에게 필요한 정보를 물어봅니다.
    - 테이블뷰는 사용자에게 정보를 보여주는 `View`의 역할을 합니다.

**delegate**
- 테이블뷰의 모양과 동작을 관리하는 `Controller`의 역할을 합니다.
- 선택 항목을 관리합니다.
- 섹션의 헤더와 푸터를 정의합니다.
- 셀의 삭제 및 재정렬을 합니다.
- 기타 테이블뷰의 작업을 수행합니다.

**dataSource**
- 테이블뷰 셀의 개수와 데이터를 처리하는 `Model`의 역할을 합니다.
- 데이터를 관리하고 테이블뷰에 셀을 전달하기 위해 사용됩니다.

🔗 참고링크
- [🍎 Developer Apple - UITableViewDelegate](https://developer.apple.com/documentation/uikit/uitableviewdelegate)
- [🍎 Developer Apple - UITableViewDatasource](https://developer.apple.com/documentation/uikit/uitableviewdatasource)
- [🐻 부스트코스 - DataSource와 Delegate?](https://www.boostcourse.org/mo326/lecture/16887?isDesc=false)

---

## 고민했던점 

### 1️⃣ 디코딩 로직을 Model로 분리
`ViewController`안에서 `JSONDecoder`를 이용한 디코딩 작업이 `Controller`의 역할이 아니라고 생각해 `Model` 내부에 디코딩을 수행하는 타입메서드를 만들어 주었습니다.

**변경 전**

```swift
final class ItemsTableViewController: UITableViewController {
    ...
    private func decodeJSONToItems() {
        guard let json = NSDataAsset(name: "items") else {
            return
        }

        let decoder = JSONDecoder()

        do {
            items = try decoder.decode([Item].self, from: json.data)
        } catch {
            print(error.localizedDescription)
        }
    }
}
```

**변경 후**
```swift
struct Item: Codable {
    ...
    // decode를 담당하는 decodeItems 메서드 추가
    static func decodeItems() throws -> [Item] {
        guard let json = NSDataAsset(name: "items") else {
            fatalError()
        }
                
        return try JSONDecoder().decode([Item].self, from: json.data)
    }
}

final class ItemsTableViewController: UITableViewController {
    ...
    private func decodeJSONToItems() {
        do {
            items = try Item.decodeItems()
        } catch {
            print(error.localizedDescription)
        }
    }
}
```
현재 프로젝트는 데이터를 외부 서버에서 가져오는 과정이 없이 `Assets`에 `dataset`으로 `json`파일을 가지고 있었기 때문에 `server`와 같은 파일을 만드는 것이 아닌 모델 자체에 `static func`을 사용하여 디코딩 해주었습니다.

### 2️⃣ init을 이용한 데이터 주입
초기에는 첫화면에서 다음 화면으로 넘어갈 때 `ViewController` 내의 프로퍼티로 직접 접근하여 데이터를 넣어줬습니다.
하지만 이럴 경우 `ViewController`의 프로퍼티로의 접근이 쉬워지고 데이터 은닉화가 불가능하기 때문에 `init`을 이용하여 데이터를 주입시켜 주는 방식으로 변경하였습니다.

**변경 전**
```swift
final class ItemsTableViewController: UITableViewController {
    ...
    var navigationTitle: String?
    ...
}

final class ExpositionUniverselleViewController: UIViewController {
    ...
    @IBAction private func tapShowItemsButton(_ sender: UIButton) {
        guard let nextViewController = storyboard?.instantiateViewController(withIdentifier: ItemsTableViewController.id) as? ItemsTableViewController else {
            return
        }
        ...
    }
    ...
}
```

**변경 후**
```swift
final class ItemsTableViewController: UITableViewController {
    ...
    private let navigationTitle: String
    
    init?(navigationTitle: String, coder: NSCoder) {
        self.navigationTitle = navigationTitle
        super.init(coder: coder)
    }
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    ...
}

final class ExpositionUniverselleViewController: UIViewController {
    ...
    @IBAction private func tapShowItemsButton(_ sender: UIButton) {
        guard let nextViewController = storyboard?.instantiateViewController(
            identifier: ItemsTableViewController.id,
            creator: {
                let title = sender.currentTitle?.replacingOccurrences(of: " 보러가기", with: "") ?? ""
                return ItemsTableViewController(navigationTitle: title, coder: $0)
            }
        ) else {
            return
        }
        ...
    }
    ...
}
```

🔗참고링크
- [𝓥 블로그 - UIViewController 서브클래스의 custom initializer 만들기](https://velog.io/@dev_jane/UIViewController-서브클래스의-custom-initializer-만들기required-initializer-initcoder-must-be-provided-by-subclass-of-UIViewController)
- [🍎 Developer Apple - instantiateViewController(identifier:creator:)](https://developer.apple.com/documentation/uikit/uistoryboard/3213989-instantiateviewcontroller)

---

## 조언을 얻고싶은점

### 1️⃣ fatalError
테이블뷰에 셀을 반환해주기 위해 `dequeueReusableCell(withIdentifier:for:)`로 셀을 가져오는 과정에서 옵셔널이 아닌 셀을 가져오기 위해 guard문을 사용하여 else일 경우 함수를 `fatalError`를 호출해줬습니다. 하지만 `fatalError`가 호출되면 앱이 강제로 종료가 된다는 점이 신경쓰였습니다.
`tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell`는 `override`로 작성하는 것이기 때문에 `throws`나 `UITableViewCell?`과 같이 함수의 반환값을 바꾸는 작업을 못하기 때문에 이럴 때는 어떻게 에러처리를 해야할지 조언을 얻고싶습니다.

2023-06-28 06:49 UTC, July911 requested changes

2023-06-28 06:49 UTC, July911 commented on Expo1900/Expo1900/Controller/ExpositionUniverselleViewController.swift
> +        navigationController?.setNavigationBarHidden(true, animated: true)
super 콜이 빠져있는거같네요

2023-06-28 06:49 UTC, July911 commented on Expo1900/Expo1900/Controller/ExpositionUniverselleViewController.swift
> +        navigationController?.setNavigationBarHidden(false, animated: true)
여기도요 ! 왜 써줘야할까요 ?

2023-06-28 06:49 UTC, July911 commented on Expo1900/Expo1900/Controller/ItemDetailViewController.swift
> +    @IBOutlet weak var itemDescriptionLabel: UILabel!
이건 왜 밑에 있나요 ?  UI 요소면 동일하게 init 위에 있는게 좋아보이네요.

2023-06-28 06:49 UTC, July911 commented on Expo1900/Expo1900/Controller/ItemsTableViewCell.swift
> +final class ItemsTableViewCell: UITableViewCell {
여러개의 아이템이 담기는 cell인가요 ?

2023-06-28 06:49 UTC, July911 commented on Expo1900/Expo1900/Controller/ItemsTableViewController.swift
> +        cell.shortDesctionLabel.text = item.shortDescription
인터페이스로 소통해주세요.

2023-06-28 06:49 UTC, July911 commented on Expo1900/Expo1900/Model/ExpositionUniverselle.swift
> +        guard let json = NSDataAsset(name: "exposition_universelle_1900") else {
Codable을 채택한 모델이 디코딩하는 기능까지 가지고 있는거보다는 제네릭으로 decoder를 만들어보는게 나을거같네요.

2023-06-28 06:49 UTC, July911 commented on Expo1900/Expo1900/Controller/ItemsTableViewController.swift
> +                return ItemDetailViewController(item: self.items[indexPath.row], coder: coder)
다른곳에선 coder: $0 로 하셨던데, 여기선 다르게하신 이유는 무엇인가요 ?

2023-06-28 06:49 UTC, July911 commented on Expo1900/Expo1900/Controller/ItemsTableViewController.swift
> +            identifier: ItemDetailViewController.id,
개인적으로는 여기서는 if let 이 조금 더 자연스럽지 않나 라는 생각이 드네요. 
if let 을 통과못하면 어차피 navigationController?.pushViewController(nextViewController, animated: true) 를 못타게 될 같구요. 
이건 개인적인 생각입니다 !

2023-06-28 06:49 UTC, July911 commented on Expo1900/Expo1900/Controller/ItemsTableViewController.swift
> +            fatalError()
UITableViewCell() 를 리턴하는게 더 나아보이네요

2023-06-28 06:49 UTC, July911 commented on Expo1900/Expo1900/Controller/ItemsTableViewCell.swift
> +    @IBOutlet weak var shortDesctionLabel: UILabel!
prepareForResue()는 무엇을 하는 메서드일까요 ?

2023-06-28 06:49 UTC, July911 commented on Expo1900/Expo1900/Controller/ItemsTableViewCell.swift
> +//  Created by Erick, 비모 on 2023/06/27.
cell 은 controller 인가요 ? 폴더 뎁스가 이상한거같아요.

2023-06-28 06:49 UTC, July911 commented on Expo1900/Expo1900/Controller/ItemsTableViewCell.swift
> +    @IBOutlet weak var itemImageView: UIImageView!
contentMode가 무엇인가요 설명해주세요 !

2023-06-28 06:56 UTC, July911 commented
저번과는 다르게 커밋을 상세하게 작성해주셨네요 정말 훌륭합니다 ! 
그리고 따로 정리하라고 말씀드린 부분 역시도 잘 정리되어있는 것 같습니다. 
하지만 빠르게 하다보니 조금 미비된 부분이 보여서 정리/수정하시고 디엠주시면 다시 한번 말씀드리겠습니다. 
코멘트에 궁금하다고 물어보신부분은 답변으로 따로 남겼습니다. 
학습하시거나, 코멘트를 보고 궁금한점이 있다면 언제든 디엠주시면 답변 드리겠습니다. 

정말 고생하셨습니다 !

2023-06-29 01:07 UTC, bubblecocoa commented on Expo1900/Expo1900/Controller/ExpositionUniverselleViewController.swift
> +        navigationController?.setNavigationBarHidden(false, animated: true)
[viewWillAppear(_:)](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621510-viewwillappear)와 [viewWillDisappear(_:)](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621485-viewwilldisappear) 문서에 따르면 `Discussion` 항목에 다음과 같은 설명이 있습니다.
> If you override this method, you must call super at some point in your implementation.

2023-06-29 01:20 UTC, h-suo commented on Expo1900/Expo1900/Controller/ExpositionUniverselleViewController.swift
> +        navigationController?.setNavigationBarHidden(false, animated: true)
`super`를 호출함으로써 부모 클래스의 해당 메서드가 실행되어 기본 동작이 수행되도록 합니다. 하지만 모든 메서드가 `super`를 호출해야 하는 것은 아니며, 특정 상황에 따라 `super`를 호출하지 않는 것이 적절한 경우도 있을 수 있습니다.
저희가 문서를 찾아본바로 `override`를 했을 때 `super`를 호출해야하는 메서드는 다음과 같습니다.

- viewDidLoad()
- viewWillAppear(_:)
- viewDidAppear(_:)
- viewWillDisappear(_:)
- viewDidDisappear(_:)

2023-06-29 01:37 UTC, bubblecocoa commented on Expo1900/Expo1900/Controller/ItemsTableViewController.swift
> +                return ItemDetailViewController(item: self.items[indexPath.row], coder: coder)
컨벤션 맞춰 변경하던 중 누락 되었습니다. 😅

2023-06-29 02:10 UTC, h-suo commented on Expo1900/Expo1900/Controller/ItemsTableViewCell.swift
> +    @IBOutlet weak var shortDesctionLabel: UILabel!
[prepareForReuse()](https://developer.apple.com/documentation/uikit/uitableviewcell/1623223-prepareforreuse)는 셀이 dequeue되기 전에 호출되는 메서드로 셀을 재사용하기 전에 준비하는 메서드입니다.

2023-06-29 02:11 UTC, bubblecocoa commented on Expo1900/Expo1900/Controller/ItemsTableViewCell.swift
> +//  Created by Erick, 비모 on 2023/06/27.
`UITableViewCell` 클래스는 `UIView`, `NSCoding`, `UIGestureRecognizerDelegate`를 상속받고 있습니다.
`Controller`역할 클래스를 상속받지 않고, `View` 역할을 수행하는 클래스만 상속받은 상태이기 때문에 `View`로 보입니다.

해당 파일은 `View` 그룹으로 이동하였습니다 👍

2023-06-29 02:22 UTC, bubblecocoa commented on Expo1900/Expo1900/Controller/ItemsTableViewCell.swift
> +    @IBOutlet weak var itemImageView: UIImageView!
content mode(콘텐츠 모드)는 UIImageView 내부의 이미지가 표시되는 방식을 결정하는 속성입니다.

2023-06-29 02:22 UTC, bubblecocoa commented on Expo1900/Expo1900/Controller/ItemsTableViewCell.swift
> +    @IBOutlet weak var itemImageView: UIImageView!
contentMode는 UIImageView 내부의 이미지가 표시되는 방식을 결정하는 속성입니다

2023-06-29 02:29 UTC, h-suo commented on Expo1900/Expo1900/Controller/ItemsTableViewCell.swift
> +    @IBOutlet weak var itemImageView: UIImageView!
저희가 사용한 `Mode`는 `Aspect Fit`입니다.
- Aspect Fit : 콘텐츠의 비율을 유지하며 콘텐츠의 내용이 모두 보이도록 View에 맞게 표시됩니다. (View의 남는 부분은 투명하게 표시됩니다.)
- Aspect Fill : 콘텐츠의 비율을 유지하며 View를 모두 채우도록 표시됩니다. (표시되지 않는 콘텐츠는 잘리게 됩니다.)
- Scale To Fill : 콘텐츠의 비율을 유지하지 않고 View에 맞게 표시됩니다.

2023-06-29 02:30 UTC, bubblecocoa commented on Expo1900/Expo1900/Controller/ItemsTableViewCell.swift
> +    @IBOutlet weak var itemImageView: UIImageView!
위는 주로 사용하는 `contentMode`이며 이외에도 아래와 같은 `contentMode`들이 있습니다.
- bottom
- bottomLeft
- bottomRight
- center
- left
- redraw
- right
- top
- topLeft
- topRight

2023-06-29 08:11 UTC, h-suo commented on Expo1900/Expo1900/Model/ExpositionUniverselle.swift
> +        guard let json = NSDataAsset(name: "exposition_universelle_1900") else {
`JSONDecoder`를 `extension`하여 데이터와 매칭할 타입 그리고 Asset 이름을 넣어주면 데이터를 반환하는 `decode` 메서드를 추가하였습니다.

https://github.com/yagom-academy/ios-exposition-universelle/pull/271/commits/87e6b6a98c61b48863d7e7f4a7b3442eef5144ec

2023-06-29 08:14 UTC, bubblecocoa commented on Expo1900/Expo1900/Controller/ItemsTableViewController.swift
> +            identifier: ItemDetailViewController.id,
의견주신 방식으로 변경하였습니다 🙏
https://github.com/yagom-academy/ios-exposition-universelle/pull/271/commits/aaac626d547a520ddfa92314ae5bceace9d07324

2023-06-29 08:15 UTC, bubblecocoa commented on Expo1900/Expo1900/Controller/ItemsTableViewController.swift
> +            fatalError()
수정하였습니다!
https://github.com/yagom-academy/ios-exposition-universelle/pull/271/commits/b992ce11926bf87867dfcbf0c4c120e8aaed2c71

2023-06-29 09:33 UTC, merged