만국박람회 [STEP2] Jusbug, Minsup
yagom-academy/ios-exposition-universelle pull request #272
Opened 2023-06-29 07:14 UTC by JusBug

@1Consumption 
안녕하세요 올라프!!!
저희 Step2까지 구현해서 PR 보내드립니다!
어제 조언해주신 것처럼 커밋 단위를 보다 쪼개서 짝프로그래밍을 진행했습니다!
꼼꼼한 리뷰 잘 부탁드립니다!!!🙏

## 🧐 고민한점
### **<네비게이션 바로 인해 이미지가 밀리는 문제>**

🤯 **문제상황** 
첫 번째 메인 포스터 뷰에서 네비게이션 바가 존재하여 예시와 달리 컨텐츠가 아래로 밀려나는 문제가 있었습니다

🔥 **해결방법**
viewWillAppear(), viewWillDisappear() 메서드를 이용하여 네비게이션 바를 특정 뷰에서만 네비게이션 바가 보이게 하고 나머지에서는 숨기도록 하였습니다.
```swift!
override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    self.navigationController?.setNavigationBarHidden(true, animated: animated)
}

override func viewWillDisappear(_ animated: Bool) {
    super.viewWillDisappear(animated)
    self.navigationController?.setNavigationBarHidden(false, animated: animated)
}
```
- - -
### **<폰트가 다른 글자를 한 레이블에 넣기>**

🤯 **문제상황**
첫 번째 메인 포스터 뷰에서는 각 데이터의 이름을 나타내는 맨 앞의 문자열과 그 뒤에 값들의 폰트 크기가 서로 다르게 표현되어야 하는데 같게 출력되는 문제가 있었습니다.

🔥 **해결방법**
특정 문자열의 속성을 변경할 수 있는 NSMutableAttributedString으로 문자열의 타입을 변환해주고 addAttribute를 이용하여 문자열 내에서 폰트를 변경해주고 싶은 문자열의 길이를 지정해주었습니다.

```swift
let expoTitle = NSMutableAttributedString(string: "방문객 : " + format(by: exposition.visitors))
let expoLocation = NSMutableAttributedString(string: "개최지 : " + exposition.location)
let expoDuration = NSMutableAttributedString(string: "개최 기간 : " + exposition.duration)
let font1 = UIFont.systemFont(ofSize: 20)

expoTitle.addAttribute(.font, value: font1, range: NSRange(location: 0, length: 4))
expoLocation.addAttribute(.font, value: font1, range: NSRange(location: 0, length: 4))
expoDuration.addAttribute(.font, value: font1, range: NSRange(location: 0, length: 5))
```
- - -
### **<중복되는 디코딩 메소드 통합>**

🤯 **문제상황**
DecodingHandler 내부에 Exposition과 Entry타입을 디코딩해서 반환하는 메소드가 두 개 있었습니다.
```swift
static func getExposition() -> Exposition {       
    //생략
}

static func getEntryList() -> [Entry] {
    //생략
}
```
두 메소드의 코드 내용이 대부분 똑같고 반환하는 타입과 json파일 이름만 달랐습니다.
그래서 두 함수를 하나로 통합하고 싶은 생각이 들었습니다.

🔥 **해결방법**
Generic을 사용하여 문제를 해결했습니다. 
```swift
 static func decode<T: Codable>(fileName file: FileName) -> T? {
```
Decodable을 준수하는 제네릭 타입을 이용해 Exposition과 Entry를 하나의 메소드로 디코드했습니다. 
파일이름은 다르기 때문에 매개변수로 전달받아 사용했습니다. 또한 변환과정에서 에러가 발생하면 리턴할 내용이 없기 때문에 nil을 반환할 수 있도록 T? 타입을 반환했습니다.
- - -
### **<back button title 바꾸기>**

🤯 **문제상황**
요구사항에 back button의 내용이 `back`이 아닌 `메인`, `한국의 출품작` 등 을 사용하는 것을 발견했습니다. 저희는 back button의 내용을 바꾸려고 시도했습니다.

🔥 **해결방법**
back button의 내용을 바꾸는 방법은 두 가지가 있습니다.
1. 직접 navigationItem을 통해 바꿀 수 있습니다.
2. 네비게이션 타이틀을 지정하면 그 내용에 맞게 back button이 생성됩니다.

저희는 두 번째 방법을 이용해 각 뷰컨트롤에 navigation title을 지정해서 back button의 내용을 수정했습니다.

```swift!
// 첫 번째 ExpositionViewController
self.navigationItem.title = "메인"

// 두 번째 KoreanEntryViewController
self.navigationItem.title = "한국의 출품작"

```
- - -

## 😀 조언을 얻고싶은 점
### **<한 번만 사용하는 문자열 리터럴>**
ExpositionIntroVC에서 문자열 리터럴을 네임스페이스를 이용하지 않고 그대로 사용하였습니다. 

```swift
self.navigationItem.title = "메인"
self.navigationItem.title = "한국의 출품작"
let expoTitle = NSMutableAttributedString(string: "방문객 : " + format(by: exposition.visitors))
let expoLocation = NSMutableAttributedString(string: "개최지 : " + exposition.location)
let expoDuration = NSMutableAttributedString(string: "개최 기간 : " + exposition.duration)
```
1. 첫 번째 이유는 해당 문자열이 여러 곳에서 사용되는 것이 아닌 한번만 사용되기 때문입니다.
2. 두 번째 이유는 오히려 가독성이 좋아지기 때문입니다. 문자열을 보고 이 코드가 어떤 코드인지 힌트를 줄 수 있다고 생각하였습니다.

이런 이유로 문자열 리터럴을 그대로 사용하였는데 현재 둘이서 하는 프로젝트와는 달리 현업에서는 여러 명이 함께 코드를 공유하기 때문에 유지보수성 면에서는 어떤 방식이 더 좋은 방향인지 궁금합니다.

2023-06-29 16:21 UTC, 1Consumption requested changes
고생하셨습니다. @JusBug @agilestarskim 

https://github.com/yagom-academy/ios-exposition-universelle/pull/272/commits/e8144d600f2e49b62af8b1b85d6e52f581adec88, https://github.com/yagom-academy/ios-exposition-universelle/pull/272/commits/36809eb746275abfdabf22d9d0a7e0de1c0e9d87, https://github.com/yagom-academy/ios-exposition-universelle/pull/272/commits/9c796c7f78ccb6102d78388fad78cd4da46f569f, https://github.com/yagom-academy/ios-exposition-universelle/pull/272/commits/1b39068a1c9f6aa04abc2627cc33fdbf04fc7d1e
이 커밋들은 한번에 두가지 이상의 역할을 하고 있는듯 합니다. 

-----------------------------------

### 고민한 점에 대한 코멘트

> 이런 이유로 문자열 리터럴을 그대로 사용하였는데 현재 둘이서 하는 프로젝트와는 달리 현업에서는 여러 명이 함께 코드를 공유하기 때문에 유지보수성 면에서는 어떤 방식이 더 좋은 방향인지 궁금합니다.

코드에 문자열을 그대로 넣으면 다국어 지원이나, 관리 측면에서 매우 어려워집니다. 또한 이미 코드로 의미를 내포하고 있으니 굳이 문자열을 그대로 사용할 필요는 없어보입니다.
저는 Localizable.strings 이라는 파일로 관리를 합니다. 또한 이를 보다 사용하기 좋게 SwiftGen이라는 라이브러리도 같이 사용하는 편입니다.

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    var entry: Entry?
생성자를 통해 주입받으면 외부에서 몰라도 되는 프로퍼티 같습니다. 또한 옵셔널도 제거할 수 있을 것 같아요.

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +        self.configureComponents()
title에 값을 넣어주는 코드는 노출이 되어있고, image를 넣어주거나 descriptionLabel에 값을 넣어주는 코드는 추상화가 되어 있네요.
코드간에 추상화 수준이 맞으면 좋겠습니다.

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +        }
guard let 대신에 if let을 사용한 이유가 있을까요?

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +        if let entry = self.entry {
swift 5.7부터 아래와 같이 축약할 수 있습니다.
```suggestion
        if let entry {
```

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/EntryListCell.swift
> +    }
불필요한 코드 같습니다.

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionIntroViewController.swift
> +        expoDuration.addAttribute(.font, value: font1, range: NSRange(location: 0, length: 5))
4, 4, 5 같은 매직넘버 보다 String의 count로 접근하는게 좀 더 안전한 방법 같습니다.

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionIntroViewController.swift
> +        let font1 = UIFont.systemFont(ofSize: 20)
font1은 너무 성의 없는 네이밍 같네요. 다른 의미있는 이름을 찾아보세요.

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionIntroViewController.swift
> +        self.expositionTitleLabel.text = exposition.title.replacingOccurrences(of: "(", with: "\n(")
만약 괄호가 여러개 나오면 어떻게 되나요?

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionIntroViewController.swift
> +    }
viewController에서 이런 자세한 코드를 알 필요가 있나싶어요. 로직을 담당하는 객체를 만들고 이 코드를 그 객체로 옮겨보시죠.

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionIntroViewController.swift
> +        guard let koreanEntryListViewController = self.storyboard?.instantiateViewController(withIdentifier: KoreanEntryListViewController.identifier) as? KoreanEntryListViewController else { return
NSCoder를 제공하는 메소드가 있습니다. 이를 통해 stoaryBoard에서 viewController 정보를 coder로 얻어오고, 원하는 값을 넣어줄 수 있습니다.
https://developer.apple.com/documentation/uikit/uistoryboard/3213989-instantiateviewcontroller

``` swift
final class ViewController: UIViewController {
 
    private let entry: Entry

    init?(entry: Entry, coder: NSCoder) {
        self.entry = entry
        
        super.init(coder: coder)
    }

    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }    
}
```

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/KoreanEntryListViewController.swift
> +    private var entryList: [Entry] = DecodingHandler.decode(fileName: .entry) ?? []
var인 이유가 있나요?

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Model/Entry.swift
>      let description: String
`description`이라는 이름은 이미 swift에서 선점하고 있는 이름입니다. 
https://developer.apple.com/documentation/swift/customstringconvertible/description-3eos3
다른 이름을 고민해보는게 어떨까요?

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +}
왜 enum으로 만드셨나요? 또한 내부에 static으로 선언된 메소드가 있는데, static으로 선언한 이유가 궁금합니다.

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +        }
[`CustomStringConvertible`](https://developer.apple.com/documentation/swift/customstringconvertible)에 대해서 알아보세요.

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +    static func decode<T: Decodable>(fileName file: FileName) -> T? {
아래와 같이 제네릭에 Decodable 자체를 넣으면 어떻게 될까요? 굳이 `T: Decodable`로 선언한 이유가 있을까요?
```suggestion
    static func decode<Decodable>(fileName file: FileName) -> Decodable? {
```

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +        }
print문을 사용하면 개발자가 아닌 사용자가 알아챌 수 있나요? 어떻게해야 유저가 이런 상황을 인지할 수 있을까요?

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +enum DecodingHandler {
~Handler 라는 이름은 보통 closure에 붙는 이름인데, 여기에 붙은 이유가 궁금합니다.

2023-06-29 16:21 UTC, 1Consumption commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +        var name: String {
`FileName` enum의 `name`이라는 프로퍼티가 의미상 중복이라고 생각합니다.

2023-07-03 02:13 UTC, agilestarskim commented on Expo1900/Expo1900/Controller/ExpositionIntroViewController.swift
> +        guard let koreanEntryListViewController = self.storyboard?.instantiateViewController(withIdentifier: KoreanEntryListViewController.identifier) as? KoreanEntryListViewController else { return
외부에서 주입해준 덕분에 옵셔널을 지울 수 있었습니다. 또한 외부에서 직접 프로퍼티에 접근하지 않아 은닉화를 할 수 있게 되었습니다.!!

2023-07-03 02:14 UTC, agilestarskim commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +        if let entry = self.entry {
좋은 정보 감사합니다.!!

2023-07-03 02:18 UTC, agilestarskim commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    var entry: Entry?
밑에 코멘트를 참고하여 생성자를 만들었고 외부에서 entry를 주입받을 수 있었습니다. 감사합니다.😀

2023-07-03 02:26 UTC, agilestarskim commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +        self.configureComponents()
EntryDetailVC 뿐만 아니라 ExpositionIntroVC도 수정을 통해 추상화 수준을 맞췄습니다.😀

2023-07-03 02:28 UTC, agilestarskim commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +        }
entry가 nil일 경우 다른 로직이 필요없기 때문에 if let을 사용했습니다.

2023-07-03 02:30 UTC, agilestarskim commented on Expo1900/Expo1900/Controller/EntryListCell.swift
> +    }
삭제했습니다~😀

2023-07-03 02:51 UTC, agilestarskim commented on Expo1900/Expo1900/Controller/ExpositionIntroViewController.swift
> +        expoDuration.addAttribute(.font, value: font1, range: NSRange(location: 0, length: 5))
수정했습니다~

2023-07-03 02:51 UTC, agilestarskim commented on Expo1900/Expo1900/Controller/ExpositionIntroViewController.swift
> +        let font1 = UIFont.systemFont(ofSize: 20)
잠깐 테스트 하려고 이름 지은 변수인데 미처 바꾸지 못했습니다. clauseFont로 수정했습니다

2023-07-03 03:03 UTC, JusBug commented on Expo1900/Expo1900/Controller/ExpositionIntroViewController.swift
> +        self.expositionTitleLabel.text = exposition.title.replacingOccurrences(of: "(", with: "\n(")
Exposition title에만 JSON 데이터의 특정 문자열을 대체하여 반환해주는 것이기 때문에 접근 방식에는 문제가 없다고 생각합니다. 그리고 만약 여러 개의 소괄호를 포함하는 예외적인 경우에는 지정된 range 값을 주어 접근할 것 같습니다.

2023-07-03 03:04 UTC, agilestarskim commented on Expo1900/Expo1900/Controller/ExpositionIntroViewController.swift
> +        self.expositionTitleLabel.text = exposition.title.replacingOccurrences(of: "(", with: "\n(")
> 만약 괄호가 여러개 나오면 어떻게 되나요?

괄호가 나올 때마다 개행이 됩니다! 

> 왜 이런 방식을 사용했는가?

json 데이터가 바뀌지 않는다는 가정하에 만든 코드였습니다. 
json 데이터에 직접 개행문자를 넣는것은 chitting의 느낌이 들어서 코드에서 문자를 가공하는 방법을 사용했습니다.

2023-07-03 03:17 UTC, agilestarskim commented on Expo1900/Expo1900/Controller/ExpositionIntroViewController.swift
> +    }
Int 를 Extension하여 로직을 분리했습니다.

2023-07-03 03:20 UTC, agilestarskim commented on Expo1900/Expo1900/Controller/KoreanEntryListViewController.swift
> +    private var entryList: [Entry] = DecodingHandler.decode(fileName: .entry) ?? []
처음에 빈 배열로 초기화했고 viewDidload에서 디코딩 후 값을 바꾸어주려고 var로 선언했었습니다. 하지만 굳이 그럴 필요가 없다고 판단했고 초기화할 때 decode하는 방식으로 변경하는 과정에서 미처 let으로 변경하지 못했습니다. 

let으로 다시 수정했습니다~

2023-07-03 03:25 UTC, agilestarskim commented on Expo1900/Expo1900/Model/Entry.swift
>      let description: String
shortDescription에 대비되는 느낌으로 longDescription으로 변경하였습니다.

2023-07-03 03:33 UTC, agilestarskim commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +}
> 왜 enum으로 만드셨나요?

해당 객체는 정보 저장이 필요없는 객체라 여러 인스턴스를 만들 필요없이 싱글턴으로 만드는 것이 메모리 측면에서 유리하다고 판단했습니다. 싱글턴을 만들기 위해 class로 구현한 뒤 싱글턴 작업 ( private init 등)을 해주는 것 보다 enum으로 만들면 자동으로 싱글턴이 구현되기 때문에 enum으로 만들었습니다.

> static으로 선언한 이유가 궁금합니다.

enum을 통해 싱글턴을 구현했다면 해당 메소드를 사용하기 위해선 static 키워드를 사용해야합니다.
만약 static을 붙이지 않으면 인스턴스 생성 후(enum에서는 case를 명시) 메소드에 접근해야 하기 때문에 불필요한 case를 만들어야 합니다.

2023-07-03 03:33 UTC, JusBug commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +        }
customStringConvertible 프로토콜을 채택하면 모든 타입의 인스턴스를 지정한 형식의 문자열로 변환하여 출력할 수 있습니다. 따라서 해당 프로토콜을 이용하면 가독성을 높일 수 있는 장점이 있습니다.

2023-07-03 03:37 UTC, agilestarskim commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +        }
저희 코드에서는 print할 내용이 없어서 적용하지 못했습니다. 😢

2023-07-03 03:41 UTC, agilestarskim commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +    static func decode<T: Decodable>(fileName file: FileName) -> T? {
문법 오류가 발생합니다. 
`<T: Decodable>`의 뜻은 Decodable을 준수한 타입을 사용하겠다는 뜻이고 T는 함수 내부와 리턴에서 사용해야하기 때문에 T와 같이 사용할 타입 이름을 명시해 주어야합니다.

2023-07-03 04:15 UTC, agilestarskim commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +        }
alert를 띄워 nil일 경우 유저에게 "데이터를 불러올 수 없습니다." 라는 문구를 보여주었습니다.

2023-07-03 10:25 UTC, agilestarskim commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +enum DecodingHandler {
Helper 라는 단어를 사용하고 싶었는데 실수를 했습니다.
Helper는 보통 한가지 특정 역할을 전역에서 수행하는 객체에 붙이는 접미사로 들었습니다.

DecodingHelper로 수정하였습니다~

2023-07-03 10:35 UTC, agilestarskim commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +        var name: String {
FileName enum을 File이라는 이름으로 변경하였습니다.

2023-07-03 11:11 UTC, 1Consumption commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +        }
name이라는 프로퍼티를 직접 사용하기보다 enum 자체를 문자열 보간법을 활용해 넣을 수 있지 않나요?

2023-07-03 11:12 UTC, 1Consumption commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +    static func decode<T: Decodable>(fileName file: FileName) -> T? {
> T는 함수 내부와 리턴에서 사용해야하기 때문에 T와 같이 사용할 타입 이름을 명시해 주어야합니다.

이 부분을 조금 더 자세하게 설명해주시겠어요? 명시를 하지 않는다면 컴파일러는 어떻게 받아들일까요? 그리고 그게 왜 문제가 될까요?

2023-07-03 12:05 UTC, agilestarskim commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +        }
그 방법은 미처 생각하지 못했네요.
문자열 보간법을 이용하여 name 프로퍼티를 삭제하였습니다.

https://github.com/yagom-academy/ios-exposition-universelle/pull/272/commits/6457bc7f9f18e62cf434f5ebda509e6598330a79

2023-07-03 12:23 UTC, agilestarskim commented on Expo1900/Expo1900/Utils/DecodingHandler.swift
> +    static func decode<T: Decodable>(fileName file: FileName) -> T? {
* Generic은 `어떤 타입`에 대해서도 대응할 수 있는 메소드나 타입을 만들기 위해 존재합니다.
* 여기서 `어떤 타입`이라는 것은 특정 타입이 아닌, 매우 광범위하고 추상적인 타입을 의미하기 때문에 특별한 별칭이 필요합니다.
* 만약 별칭을 지어주지 않는다면 `어떤 타입`을 언급할 방법이 없기 때문입니다.
* 사람도 이름이 없으면 부를 수 없는 것 처럼 `어떤 타입`도 이름을 붙여야 원하는 시기와 장소에서 사용할 수 있게 됩니다.

위에 예시처럼

```swift
static func decode<Decodable>(fileName file: FileName) -> Decodable? {
```
이런 코드를 작성한다고 가정했을 때 
별칭을 정해주지 않았기 때문에 함수 내부에서 `어떤 타입`을 사용할 수 없게 됩니다.

```swift
guard let result = try? decoder.decode( ??? .self, from: content) else {
    print("\(file).json 파일을 \( ??? .self)으로 변환하는데 실패하였습니다.") 
    return nil
}
```

2023-07-03 22:03 UTC, merged