만국박람회 [STEP 2] Dasan, EtialMoon
yagom-academy/ios-exposition-universelle pull request #273
Opened 2023-06-30 00:09 UTC by DasanKim

안녕하세요 그린! (@GREENOVER)
그린과 함께 하여 공부가 즐거운 다산과 문입니다😁

STEP2 PR을 보내드립니다. 
오토레이아웃은 이번 스텝 요구사항에 없었지만, 원활한 프로젝트 진행을 위하여 기본적인 오토레이아웃만 잡아놓았습니다:)
STPE2 잘 부탁드립니다!☺️ 감사합니다!

----

# STEP 2

## 🔍 고민되었던 점

### 1. Navigation Controller를 이용한 UI 구현
'출품작 목록'에과 '출품작 상세화면'으로 오고갈때에, 각 뷰컨트롤러 인스턴스들을 **계층적으로 관리**하는 것이 좋겠다고 판단하여 `Navigation Controller`를 이용하여 화면전환을 구현하였습니다. 

#### 가. navigationBar.isHidden
- 1900 만국박람회 포스터와 각종 설명을 표시하는 `첫번째 화면`은 `navigation bar`가 없어야했지만, 나머지 `출품작 목록`과 `출품작 상세화면`은 `navigation bar`가 있어, `BackButton`을 통해 앞/뒤 화면으로 이동할 수 있어야했습니다.
- 따라서 첫번째 화면에서 `navigationBar`의 `isHidden` 프로퍼티에 `true`값을 주어 navigation bar가 보이지 않도록 하였고, 두번째 화면(출품작 목록)에서는 `false`값을 주어 navigation bar가 보이도록 하였습니다.
- 두번째 화면(출품작 목록)->첫번째 화면으로 돌아올 때 다시 `navigation bar`가 보이지 않게 하기 위하여, `viewWillAppear` 메서드에서 `isHidden` 값을 설정하였습니다.

#### 나. scroll edge
- 처음 만들어진 `navigation bar`는 view와 **같은 색**이었습니다. 스크롤을 하여 컨텐츠가 navigation bar `위`로 올라갔을 때에만 navigation bar의 색깔이 변하는 것을 확인하였습니다.
- 요구사항에 있는 예시에는 **스크롤을 하지 않았을 때에도** navigation bar와 view가 색으로 `구분`이 되어있었기 때문에, [scroll edge appearances](https://developer.apple.com/documentation/uikit/uinavigationbar/3198027-scrolledgeappearance)를 이용하여 navigation bar와 view를 구분하였습니다.

  > When a navigation controller contains a navigation bar and a scroll view, part of the scroll view’s content appears underneath the navigation bar. If the edge of the scrolled content reaches that bar, UIKit applies the appearance settings in this property.

#### 다. BackBarButtonItem
- 첫번째 화면에 `navigation bar`가 없다보니 두번째 화면(출품작 목록)의 `back button title`이 `Back`으로 설정되는 것을 보았습니다.
  - 보통 `navigation bar`에 있는 `back button의 title`은 이전 화면의 `title`값을 갖는데, `title`이 없는 경우 [backButtonDisplayMode](https://developer.apple.com/documentation/uikit/uinavigationitem/3656350-backbuttondisplaymode)에 따라 `back button`의 `title`를 정해준다고 합니다.
- 저희는 "메인"이라는 title로 설정하고 싶었는데, 이를 위하여 아래와 같이 `커스텀한 bar button item`를 만들어 할당해주었습니다.
    ```swift
    @IBAction func touchUpGoToEntryListButton(_ sender: UIButton) {
        (...)
        navigationItem.backBarButtonItem = createMainBackBarButtonItem()
        (...)
    }

    private func createMainBackBarButtonItem() -> UIBarButtonItem {
        let backBarButtonTitle = "메인"
        let backBarButtonItem = UIBarButtonItem(title: backBarButtonTitle, style: .plain, target: self, action: nil)

        return backBarButtonItem
    }
    ```

### 2. Decoder 모델 타입 추가
#### 가. [보일러 플레이트 코드](https://en.wikipedia.org/wiki/Boilerplate_code)를 줄이기 위한 타입 추가
- 기존 코드에서는 `MainViewController`와 `EntryListViewController`에서 **직접** json 파일을 decode하였습니다. 두 개의 ViewController는 decode하는 함수 부분이 `dataAsset 이름`과 `data 타입`만 다르고 하는 역할 및 코드가 같았습니다.
- 변화없이 여러 군데에서 반복되는 코드인 `보일러 플레이트 코드`라고 판단하여 이를 줄이기 위해 `Model`에 `Decoder` 타입을 추가하였습니다.
- Before
    ```swift 
    // MainViewController
    private func decodeIntroduction() {
        let decoder = JSONDecoder()
        
        guard let dataAsset: NSDataAsset = NSDataAsset(name: "exposition_universelle_1900") else {
            return
        }
        
        do {
            introduction = try decoder.decode(Introduction.self, from: dataAsset.data)
        } catch {
            print(error)
        }
    }
    ```
- After
    ```swift
    // Decoder
    struct Decoder<T: Decodable> {
        static func decodeJSON(_ dataAssetName: String) throws -> T {
            let decoder = JSONDecoder()

            guard let dataAsset: NSDataAsset = NSDataAsset(name: dataAssetName) else {
                throw DecoderError.notFoundAsset
            }

            return try decoder.decode(T.self, from: dataAsset.data)
        }
    }
    ```
    
#### 나. decodeJSON이라는 네이밍
- 위와 같이 `Decoder` 타입을 나눠주면서, `Decoder` 내 메서드명을 `decodeJSON`으로 지어주었습니다. 왜냐하면 메서드명에서 JSON을 decode한다는 것을 **명확하게** 알려주고 싶었기 때문입니다.
- 하지만 `decodeJSON`이라는 네이밍으로 결정하기까지 마음에 걸리는 것들이 있었습니다.
    1. `JSON`은 대문자이고,
    2. `JSON`은 약어이다.
- [api-design-guidelines](https://www.swift.org/documentation/api-design-guidelines/)에 의하면 약어를 피해야하는데
    > Avoid abbreviations. Abbreviations, especially non-standard ones, are effectively terms-of-art, because understanding depends on correctly translating them into their non-abbreviated forms.
    > The intended meaning for any abbreviation you use should be easily found by a web search.
- JSON은 약어이지만 JSON으로 `오랫동안 불리었고`, 개발자라면 오히려 쉽고 올바르게 이해할 것 같아 네이밍에 JSON이라는 약어를 사용해도 되겠다는 결론에 이르렀습니다.

### 3. 의존성 주입
처음에는 `EntryListViewController`에서 `EntryTableViewCell`, `EntryDetailViewController`에 직접 접근하여 프로퍼티에 값을 넣었습니다. 멘토링을 받으며 이렇게 직접 접근하는 것이 객체 간의 결합도를 높인다는 것을 알게 되었습니다. 결합도가 높을 경우 `EntryTableViewCell`, `EntryDetailViewController`에서 에러가 발생할 경우 `EntryListViewController`까지 영향을 받을 가능성이 있기 때문에 의존성 주입을 통해 결합도를 낮추게 되었습니다.
https://github.com/DasanKim/ios-exposition-universelle/commit/f4c7556a03bc70bfdd5d3876f8811dbb0aadf185
https://github.com/DasanKim/ios-exposition-universelle/commit/f9bd64930324bd5783989d70c6fab3942a8f22a0

<br>

## 🙏 조언을 얻고 싶은 부분

### 1. init(coder:)
의존성 주입을 진행하며 뷰컨트롤러에서 이니셜라이저를 만들게 되며 `init(coder:)`를 사용하게 되었습니다. 공식 문서에는 `지정된 언아카이버의 데이터에서 초기화된 객체를 반환합니다.`, `디코더의 데이터를 사용하여 초기화된 self를 리턴한다.` 정도로만 나와 있어 이해가 힘들어 블로그를 찾아보았습니다. 아래 마지막 링크의 블로그에서 설명하기로는
`storyboard나 xib는 우리가 만들어둔 UI의 형태를 xml 형태로 저장하고 있다. 이 저장된 형태를 우리의 화면으로 가져오기 위해서는 이 xml형태로 저장된 파일의 구성을 가져와야 하는데 이 구성을 가져올 때 사용되는 것이바로 init(coder: NSCoder)이다.`
이렇게 설명하고 있습니다.
더 깊게 이해하는 건 힘들 것 같지만 `init(coder:)`가 `storyboard`나 `xib`의 내용이 저장된 `xml`을 디코딩 해서 화면에 보여주는 역할을 한다고만 이해해도 괜찮을까요?

<br>

## 📚 참고 링크

- [🍎Apple Docs: scrollEdgeAppearance](https://developer.apple.com/documentation/uikit/uinavigationbar/3198027-scrolledgeappearance)
- [🍎Apple Docs: backBarButtonItem](https://developer.apple.com/documentation/uikit/uinavigationitem/1624958-backbarbuttonitem)
- [🍎Apple Docs: init(coder:)](https://developer.apple.com/documentation/foundation/nscoding/1416145-init)
- [🌐Blog: init(coder:)](https://babbab2.tistory.com/171)

2023-06-30 01:28 UTC, GREENOVER requested changes
두분 모두 고생 많으셨습니다!!
기능과 동작 모두 이상 없어서 크게 리팩토링 하실건 없을것 같아요ㅎㅎ
욕심내서 로직 분리라던지 조금 더 보완되면 좋을 포인트들에 주로 코멘트를 남겨보았고,
순수하게 여러분들의 의견이 궁금한 포인트에도 질문을 남겨봤습니다 🙋🏻
***
### 칭찬 드리고 싶은 부분
- 파일 및 코드의 명확한 분리가 너무 좋아요 💯
- 에러까지 고려한 코드 완전 💯💯💯
- 메서드 및 변수 네이밍이 항상 쉽지 않을텐데 명확한 의도로 네이밍이 되어 있는것 같아 리뷰가 수월했습니다 💯
- 여전히 세세한 커밋 이력 관리 💯
***
### 궁금하신 부분에 대한 저의 의견
- init(coder:)
  - 네 많은 부분에서 고민하시고 잘 찾아보신것 같은데요!?
  점차 알아갈것이고 그정도로도 충분히 많이 인지하고 계신다고 생각해요.
  좀 더 딥하게 공부하고자 하신다면 Nib, xib 정의를 넘어서 둘은 어떤 연관이 있는지 xib로 작업하지만 앱 배포시에는 nib로 변환하는데 어떻게 변환되고 왜 변환되는지 시스템적으로 들어가면서 하나씩 파보면 더 많은 도움이 되실것 같아요 🙋🏻
***
### 코멘트 외 보완되면 좋을 부분
- 아래 gif를 보시면 리스트 셀이 탭되고 다시 돌아와도 선택된 회색이 존재하는데 의도라면 상관없지만 일반적인 사용자 경험에서는 어색해 보일 수 있다고 생각이 들어서요..!
요 부분을 탭될때만 색상이 변하도록 deselectRow 메서드를 활용해봐도 좋을것 같아 남겨봅니다 ㅎㅎ
https://developer.apple.com/documentation/uikit/uitableview/1614989-deselectrow
![셀렉유지](https://github.com/yagom-academy/ios-exposition-universelle/assets/72292617/b598fd89-2fb5-424c-91b1-b66817658510)
- 오토레이아웃 너무 잘 잡아주셨네요!!
하나만 욕심 내자면 메인 뷰에서 양옆에 패딩이 없어 딱 붙는 느낌이 큰데 조금만 패딩을 주면 편하게 보일것 같아요 🙋🏻
***
다시 한번 고생 많으셨어요!
너무 잘해주셔서 ㅎㅎ 
리뷰 코멘트가 수는 많지만 반 정도는 정말 궁금해서 여쭤보는것이라 자유롭게 코멘트 달아주셔도 좋습니다 😄
한번 더 체크할 겸 리퀘스트 체인지로 드릴께요!
언제든 다시 편하게 재요청해주세요~!
불금 푹 쉬고 주말도 푹 쉬시고 화이팅입니다 🙌🙌🙌

2023-06-30 01:28 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        super.viewDidLoad()
해당 코드는 왜 필요한걸까요~?
만약 없다면 어떻게 되나요? 🙋🏻

2023-06-30 01:28 UTC, GREENOVER commented on Expo1900/Expo1900/Error/DecoderError.swift
> +    case notFoundAsset
이외 다른 에러가 디코딩 시 발생할 여지는 없을까요?
가령 디코딩 실패라던지..?

2023-06-30 01:28 UTC, GREENOVER commented on Expo1900/Expo1900/Model/Decoder.swift
> +        return try decoder.decode(T.self, from: dataAsset.data)
여기서 디코딩이 실패될때 DecoderError에서 디코딩 실패에 대한 케이스를 정의하고 do catch로 try시켜 던져주는건 어떨까요?🙋🏻

2023-06-30 01:28 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +            print(error)
현재 요구사항엔 없지만 추후 의미있는 에러처리가 되면 더 좋을것 같아요~!
사용자에게 에러를 인지시켜줄 수 있는 토스트나 팝업 메시지 같은것들로 알려줄 수도 있을것 같아요 🙋🏻

2023-06-30 01:28 UTC, GREENOVER commented on Expo1900/Expo1900/View/EntryTableViewCell.swift
> +    }
해당 코드는 어떤 동작을 의도하셨을까요?
실제 현재 코드에서 유의미한 어떤 기능을 하나요..?! 🤔

2023-06-30 01:28 UTC, GREENOVER commented on Expo1900/Expo1900/View/EntryTableViewCell.swift
> +    private func createEntryTextStackView(arrangedSubviews: [UILabel]) -> UIStackView {
위에서 셀을 구성할때 메서드 명은 configure로 사용되는데
여기서도 스택뷰를 구성하는 메서드로 이해가 되는데 만든다는 관점에서 create도 맞지만 메서드명의 기조를 통일해보면 어떨까하는 의견도 있습니다..!

2023-06-30 01:28 UTC, GREENOVER commented on Expo1900/Expo1900/View/EntryTableViewCell.swift
> +        setUpEntryTextStackViewConstraints(for: entryTextStackView)
메서드들을 관심사에 맞게 잘 분리하고 사용하는 코드가 아주 좋네요 👍👍👍

2023-06-30 01:28 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    }()
NumberFormatter와 같은 친구들은 현재는 여기서만 해당되어 사용되지만 만약 앱이 확장되고 기능이 많아질때
해당 formatter 형식이 다른곳에서도 필요할 수 있을것 같아보이는데,
이러한 범용적인 친구들은 별도 파일을 구성해서 관리해줘도 공통적으로 사용할 수 있고 분리가 잘 될것 같은데 두분은 어떻게 생각하시나요 🙋🏻

2023-06-30 01:28 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        let dataAssetName = "exposition_universelle_1900"
dateAsset이 현재 요기와 items들이 존재하는데 요러한 에셋 네임을 별도 네임 스페이스 타입을 만들어 관리하면 어떨까요!?
그렇게 된다면 한번에 관리하기도 편하고 의도치 않은 오탈자를 조금 더 방지하면서 체킹하기 좋을것 같아보입니다 🙋🏻

2023-06-30 01:28 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        let storyboardId = "EntryListViewController"
요런 친구들도 EntryListVC에서도 storyboardName, id들을 각기 다른 값이지만 갖고 있어
하나의 공통적인 네임 스페이스에서 관리하면 추후 앱이 커질때도 더 수월하게 변경 및 확인 할 수 있을것 같아요😃

2023-06-30 01:28 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    }
해당 상황에서 파탈에러가 필요한 이유가 무엇일까요~?
한번 생각해보면 좋을 포인트여서 코멘트 남겨봅니다!ㅎㅎ

2023-06-30 01:28 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    }
네비게이션 title을 configure해주는것은 viewDidLoad가 아닌 viewWillAppear에서 해주는 이유가 궁금합니다 🙋🏻

2023-06-30 01:28 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +        descriptionLabel.text = descriptionText
이것도 별도 메서드로 분리해보면 조금 더 메서드 관심사를 분리할 수 있을것 같습니다~!

2023-06-30 01:28 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        navigationItem.title = "한국의 출품작"
viewWillAppear에서 해주는 이유가 궁금합니다🙋🏻
전혀 잘못되었다는 코멘트는 아닌 어느 부분은 viewDidLoad에서 해주고 어느 부분은 viewWillAppear에서 구성해주기에 두 차이를 두분은 어떤 의도로 나눠주시는지 궁금합니다 🙋🏻

2023-06-30 01:28 UTC, GREENOVER commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        navigationItem.title = "한국의 출품작"
이 두 코드들도 configureNavigation 블라블라 와 같은 메서드로 분리시켜서 사용하면 어떨까요~?

2023-06-30 05:36 UTC, DasanKim commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        super.viewDidLoad()
- 저희 코드에서  `부모 클래스`의 `viewDidLoad()`를 호출하는 `super.viewDidLoad()`를 생략하여도 문제가 없는 것 같았습니다.
- 현재 [viewDidLoad()의 문서](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621495-viewdidload)에는 [다른 문서](https://developer.apple.com/documentation/appkit/nsviewcontroller/1434476-viewdidload)에서와 같이 `super`를 호출하라는 말은 없었지만, `super.viewDidLoad()`를 안했을 때 **중요한 초기화 작업이 누락될 수도** 있기 때문에 `super.viewDidLoad()`를 호출해주는 것이 좋다고 생각하였습니다😊

2023-06-30 05:47 UTC, DasanKim commented on Expo1900/Expo1900/Error/DecoderError.swift
> +    case notFoundAsset
- 디코딩 시 발생하는 실패에 대하여 `JSONDecoder`에서 자체적으로 던져주는 `Error`가 있을 것이라고 생각하여, `DecoderError`에서 따로 정의를 해주지 않았습니다.
- 그린의 피드백을 보다보니, 저희가 직접 처리해봐야겠다고 생각하여 디코딩 실패에 관한 case `decodeFailed`를 추가해주었습니다:)

2023-06-30 05:50 UTC, DasanKim commented on Expo1900/Expo1900/Model/Decoder.swift
> +        return try decoder.decode(T.self, from: dataAsset.data)
디코딩 실패에 대한  case `decodeFailed`를 정의하고 do-catch문으로 try시켜 던져주었습니다😆

2023-06-30 06:18 UTC, DasanKim commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +            print(error)
그린의 말씀대로 `의미있는 에러처리`가 되면 더 좋을 것 같아 `Alert`으로 에러를 인지할 수 있도록 처리하였습니다:)

2023-06-30 06:49 UTC, hojun-jo commented on Expo1900/Expo1900/View/EntryTableViewCell.swift
> +    }
해당 코드는 셀 파일을 처음 만들었을 때 자동 완성 되어있어 셀의 기본 동작에 필요한 줄 알았습니다.
그린의 말씀을 듣고 공식 문서를 확인해보니 셀이 선택 되었을 때 `제목을 흰색으로 하여 선택한 셀의 배경을 그립니다.`라고 되어 있었습니다.
실제 동작은 해당 코드가 없어도 차이가 없는 것같아 현재 저희 코드에 의미가 없는 기능으로 판단하여 삭제하였습니다.

2023-06-30 06:52 UTC, hojun-jo commented on Expo1900/Expo1900/View/EntryTableViewCell.swift
> +    private func createEntryTextStackView(arrangedSubviews: [UILabel]) -> UIStackView {
메서드명을 통일하는 것이 일관된 느낌이 들어 configure로 수정하였습니다!

2023-06-30 07:13 UTC, hojun-jo commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    }()
저희도 확장성을 고려하면 별도 파일을 구성해서 공통적으로 사용할 수 있게 분리하는게 좋을 것같습니다!
`DataFormatter` 타입을 만들어서 `NumberFormatter`의 `decimal` 형식 외에 다른 형식이 생길 가능성도 대비했습니다!

2023-06-30 10:26 UTC, DasanKim commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        let dataAssetName = "exposition_universelle_1900"
너무 좋은 생각이어서 바로 적용하였습니다!
`Namespace` 폴더를 생성하고, 그 폴더 내 `DataAssetNamespace`라는 타입을 추가하여 `Namespace`로 관리하도록 하였습니다😆

2023-06-30 10:27 UTC, DasanKim commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        let storyboardId = "EntryListViewController"
이 부분도 역시 `Namespace` 폴더 내 `StoryboardNamespace`라는 타입을 추가하여 `Namespace`로 관리하도록 하였습니다!

2023-06-30 11:19 UTC, hojun-jo commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    }
지정 생성자를 만들었기 때문에 `required init?(coder:)`을 구현해야 합니다.
`required init?(coder:)`는 스토리보드로 만들 때(`instantiateViewController(withIdentifier:)`) 불리는 것으로 알고 있습니다.
`instantiateViewController(identifier:creator:)`로 뷰컨트롤러를 만들면 `required init?(coder: NSCoder)`로 가면 안 되기 때문에 자동 완성에서 파탈에러를 쓰는 것같습니다.

2023-06-30 11:26 UTC, hojun-jo commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    }
`MainViewController`에서 네비게이션바를 숨겨야하기 때문에 `viewWillAppear`에서 `navigationController?.navigationBar.isHidden = true`를 했습니다.  일관성을 위해 다른 뷰컨트롤러에서도 네비게이션 관련된 코드를 `viewWillAppear`에서 사용했습니다.

2023-06-30 11:33 UTC, DasanKim commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +        descriptionLabel.text = descriptionText
`configureEntryDetailView`라는 메서드 이름으로 위 코드를 분리하였습니다☺️

2023-06-30 11:54 UTC, DasanKim commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        navigationItem.title = "한국의 출품작"
- Before
  - **화면 전환시마다** 호출이 필요한 네비게이션 관련된 코드를 `viewWillAppear`에서 작성하였습니다. (`navigationItem.title` 같은 경우는 `viewDidLoad`에서 하여도 무방하였지만, 일관성을 위하여 네비게이션 관련 코드들은 `viewWillAppear`에서 작성하였습니다.)
  - 초기 세팅 혹은 요소를 구성처럼 메모리에 올라왔을 때 **한번의 호출만 필요한** 코드들은 `viewDidLoad`에 작성하였습니다.

- After
  - `EntryListViewController`의 View의 `생명주기`를 확인해본 결과 두번째화면->첫번째화면->두번째화면 으로 이동할 때에 `EntryListViewController`의 `viewDidLoad`가 다시 호출되는 것을 알게되었습니다!
  - 따라서 `EntryListViewController`에서의 `viewWillAppear` 메서드 내에서 실행되었던 코드들을 `viewDidLoad` 메서드로 옮기고, `viewWillAppear` 메서드는 삭제해주었습니다:)

2023-06-30 12:00 UTC, DasanKim commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        navigationItem.title = "한국의 출품작"
`configureNavigation`이라는 메서드 이름으로 분리시켜주었습니다:)
또한 `EntryListViewController`뿐 아니라 `MainViewController`, `EntryDetailViewController` 에서도 같은 메서드 이름으로 **네비게이션 구성과 관련된 코드**를 메서드로 분리해주었습니다!😊

2023-06-30 13:17 UTC, DasanKim commented
안녕하세요 그린!
바쁘신데도 불구하고, 신속하고 꼼꼼한 리뷰에 항상 진심으로 감사드립니다🥹

----

### 코멘트 외 보완한 부분

1. 
> 아래 gif를 보시면 리스트 셀이 탭되고 다시 돌아와도 선택된 회색이 존재하는데 의도라면 상관없지만 일반적인 사용자 경험에서는 어색해 보일 수 있다고 생각이 들어서요..!
요 부분을 탭될때만 색상이 변하도록 deselectRow 메서드를 활용해봐도 좋을것 같아 남겨봅니다

- 의도한 바는 아니었지만 어색하다고 생각했었는데, 그린이 말씀해주신 deselectRow 메서드를 사용하여 해당 문제를 해결하였습니다!
아래와 같이 didSelectRowAt 메서드 내부에서 deselectRow 메서드의 animated에 false값을 줌으로서 선택된 row에 애니메이션이 작동하지 않도록 하였습니다:)

```swift
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        (중략)
        tableView.deselectRow(at: indexPath, animated: false)
    }
```

2. 
> 하나만 욕심 내자면 메인 뷰에서 양옆에 패딩이 없어 딱 붙는 느낌이 큰데 조금만 패딩을 주면 편하게 보일것 같아요 🙋🏻
- 아래 그림과 같이 각 스크롤 뷰 내 `StackView`의 `leading`과 `trailing`에 조금씩 값을 주어 패딩을 주었습니다.
- 이렇게 패딩을 주었더니, 첫번째 화면의 `title`이 잘리는 현상이 생겼습니다.
    - 이에, `title Label`의 `Autoshrink`에 `Fixed Font Size`가 아닌, `Minimum Font Sacle`로 설정해주어 **해당 Label의 크기에 따라** 폰트의 크기가 줄어들도록 하였습니다☺️

|첫번째 화면|출품작 상세화면|
|:--:|:--:|
|<img src="https://github.com/yagom-academy/ios-exposition-universelle/assets/106504779/090c3b32-83c6-486c-89aa-109c82e60631" width="300">|<img src="https://github.com/yagom-academy/ios-exposition-universelle/assets/106504779/bb9ac186-667d-49ca-ba16-6911d9903cf7" width="300">|

------

### 조언을 얻고 싶은 점

1. 에러 처리
- 에러 처리를 하다보니 같은 코드가 `MainViewController`, `EntryListViewController`에서반복되었습니다. 혹시 이러한 에러 처리를 간소화 하거나 반복을 줄일 수 있는 방법이 있을까요?

2. namespace 폴더 위치
- namespace를 모델에 두어야 할지 따로 밖으로 빼야 할지 고민하다가 다용도로 사용될 것같은 `utility`라는 폴더를 만들어 그 안에 넣었습니다. 혹시 그린이라면 어디에 namespace를 어디에 두실 것같으신가요?

2023-06-30 21:41 UTC, GREENOVER commented
@DasanKim @hojun-jo 
고생많으셨습니다!!
훨씬 더 보완되었네요 👍👍👍
***
1. 에러처리
- 에러 핸들링의 경우 각기 다른 VC에서 같은 코드를 가지더라도 반복될 수 있는데 요 부분은 별도의 에러 핸들링을 처리하는 공통 메서드를 만들어 확장하여 사용할 수 있을것 같아요!
음 쉽게 풀어서 코드로 대략적으로 나타내보자면?
```
import UIKit

extension UIVC {
  func showAlert(error: Error) { 
    // 얼럿 구현
    let alert = UIAlertController ~~
    alert.addAction ~~
    
    switch error {
      // 에러에 따른 메시지 처리
    ...
    }
    
    present alert~~
  }
}
```
여러분들의 코드를 참고해서 스도코드처럼 생략하여 썼습니다!
이렇게 공통적으로 VC를 익스텐션해 얼럿 노출에 대한 로직을 확장시켜주고 사용하는 쪽에서는 단순히 저 메서드를 호출 할 수 있을것 같아요.

2. namespace 폴더 위치
- 저도 utility 괜찮은것 같아요! 정답은 없지만 저는 보통 공통적으로 사용될 파일들은 common을 쓰기도 하고 utility를 쓰기도 하는것 같네요!
그런데 저는 모델에는 딱히 위치 시킨적은 없던것 같습니다!
스토리보드 네임이나 다른 네임들이 들어오기 때문에 모델이랑 조금 거리가 있다고 생각했습니다 🙋🏻
***
아직 리뷰 재요청이 안오고 Draft 상태인데 코멘트가 달려서 먼저 답변을 해봤습니다 ㅎㅎ
혹시 재요청 원하시면 말씀주세요~!
좋은 주말 되세요🙌

2023-07-03 12:47 UTC, GREENOVER approved these changes

2023-07-03 12:47 UTC, merged