만국박람회 [STEP 2] hoon, Idinaloq
yagom-academy/ios-exposition-universelle pull request #278
Opened 2023-06-30 13:09 UTC by Hoon94

안녕하세요 올라프(@1Consumption)😊 hoon, idinaloq입니다. 
만국박람회 STEP 2 PR 드립니다. 처음으로 코드 베이스로 UI를 구현하며 많은 어려움이 있었고 여전히 부족한 점이 많은 것 같습니다.
천천히 보시고 코멘트 남겨주시면 열심히 공부해서 다시 답변 남기도록 하겠습니다. 감사하겠습니다.🙇
좋은 주말 보내세요.🥳

# PR: STEP 2

## 고민되었던 점

### 오토레이아웃 사용
- 스토리보드를 사용하지 않고 코드 베이스로 뷰를 생성하여 `addSubview`를 통해 뷰를 추가하면 시뮬레이터에 나오지 않았습니다. 생성한 뷰를 화면에 어느 위치에 띄워주어야 하는지 판단하지 못하여 생긴 문제였습니다. 이를 해결해 주기 위해 오토레이아웃을 사용하여 화면의 어느 위치에 뷰를 띄울지에 대한 제약조건을 설정하였습니다.

    ```swift
    private func configureExpositionUniverselleScrollViewConstraint() {
        NSLayoutConstraint.activate([
            expositionUniverselleScrollView.topAnchor.constraint(equalTo: view.topAnchor),
            expositionUniverselleScrollView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            expositionUniverselleScrollView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            expositionUniverselleScrollView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
        ])
    }
    
    private func configureContentStackViewConstraint() {
        NSLayoutConstraint.activate([
            contentStackView.topAnchor.constraint(equalTo: expositionUniverselleScrollView.topAnchor),
            contentStackView.bottomAnchor.constraint(equalTo: expositionUniverselleScrollView.bottomAnchor),
            contentStackView.widthAnchor.constraint(equalTo: expositionUniverselleScrollView.widthAnchor)
        ])
    }
    ```

### 뷰 업데이트 시점
- 뷰 컨트롤러에서 연산 프로퍼티를 사용하여 뷰를 생성할 때 `UILabel`의 경우 입력되어야 하는 내용들을 함께 입력하여 생성하였습니다.

    ```swift
    private var expositionUniverselle: ExpositionUniverselle?

    private lazy var titleLabel: UILabel = {
        let label: UILabel = UILabel()
        label.text = = expositionUniverselle?.title
        label.textAlignment = .center
        
        return label
    }()
    ```
    
    위와 같이 사용하면 `expositionUniverselle`이 초기화 전에 값에 접근하여 `title` 값을 받아오려고 하기 때문에 `lazy var`를 사용해야 했습니다. 이러한 문제를 해결하기 위해 뷰를 생성하고 이후에 `updateLabel()` 메서드에서 `label.text`에 값을 할당하는 작업들을 모아서 진행하도록 하였습니다.
    
    ```swift
    private var expositionUniverselle: ExpositionUniverselle?

    private let titleLabel: UILabel = {
        let label: UILabel = UILabel()
        label.textAlignment = .center
        
        return label
    }()

    ...

    private func updateLabel() {
        navigationItem.title = "메인"
        titleLabel.text = expositionUniverselle?.titleForLabel
        visitorsLabel.text = expositionUniverselle?.visitorsForLabel
        locationLabel.text = expositionUniverselle?.locationForLabel
        durationLabel.text = expositionUniverselle?.durationForLabel
        totalDescriptionLabel.text = expositionUniverselle?.totalDescription
    }
    ```

### `addArrangedSubview()` 메서드 중복 제거
- `ExpositionUniverselleViewController`의 첫 화면에서는 다양한 뷰들을 사용하여 전체 화면을 구성하였습니다. 많은 뷰들을 `contentStackView`에 추가하여 관리하기 위해 아래와 같이 여러 번의 동일한 `addArrangedSubview()` 메서드를 작성해야 했습니다.

    ```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        decodeExpositionUniverselle()
        horizontalStackView.addArrangedSubview(leftFlagImage)
        horizontalStackView.addArrangedSubview(expositionItemListButton)
        horizontalStackView.addArrangedSubview(rightFlagImage)
        verticalStackView.addArrangedSubview(titleLabel)
        verticalStackView.addArrangedSubview(posterImage)
        verticalStackView.addArrangedSubview(visitorsLabel)
        verticalStackView.addArrangedSubview(durationLabel)
        verticalStackView.addArrangedSubview(locationLabel)
        verticalStackView.addArrangedSubview(totalDescriptionLabel)
        verticalStackView.addArrangedSubview(horizontalStackView)
        expositionUniverselleScrollView.addSubview(verticalStackView)
        view.addSubview(expositionUniverselleScrollView)
    }
    ```
    
    `addArrangedSubview()` 메서드에 매개변수로 주어지는 뷰만 변경하면 중복된 코드를 줄일 수 있어 가독성을 높일 수 있었습니다.
    
    ```swift
    private func configureView() {
        addArrangedSubviews(to: buttonStackView, elements: [leftItemImage,
                                                            expositionItemListButton,
                                                            rightItemImage
                                                           ])
        addArrangedSubviews(to: contentStackView, elements: [titleLabel,
                                                             posterImage,
                                                             visitorsLabel,
                                                             locationLabel,
                                                             durationLabel,
                                                             totalDescriptionLabel,
                                                             buttonStackView])
        expositionUniverselleScrollView.addSubview(contentStackView)
        view.addSubview(expositionUniverselleScrollView)
    }
    
    private func addArrangedSubviews(to superview: UIStackView, elements subviews: [AnyObject]) {
        subviews.forEach {
            guard let subview = $0 as? UIView else { return }
            superview.addArrangedSubview(subview)
        }
    }
    ```
    
    위와 같이 `addArrangedSubviews()` 메서드에 여러 뷰들을 `Array`로 묶어 매개변수로 넘기면 순차적으로 `superview`에 `subview`들이 추가되도록 하였습니다.

### 매직리터널 최소화
- `exposition_universelle_1900`, `items`같은 `JSON` 파일에서 직접적으로 파일을 읽어올 때 아래와 같이 파일 이름을 직접 지정하여 읽어오도록 하였습니다.

    ```swift
    private func decodeExpositionUniverselle() {
        do {
            expositionUniverselle = try JSONDecoder().decode(ExpositionUniverselle.self, from: "exposition_universelle_1900")
        } catch {
            print(error)
        }
    }
    ```
    
    추후 파일의 이름이나 파일 자체가 바뀌는 경우 파일 이름을 계속 변경해야 되는데, 만약 뷰 컨트롤러가 커지거나 파일이 많아지는 경우 일일이 파일명을 입력하는 코드를 찾아 변경하기 어려울 것 같다고 생각했습니다. 이를 해결하기 위해 `JSONFile.swift` 파일을 만들고 파일 이름을 관리할 수 있도록 했습니다.
    
    ```swift
    enum JSONFile {
        case exposition
        case items

        var name: String {
            switch self {
            case .exposition:
                return "exposition_universelle_1900"
            case .items:
                return "items"
            }
        }
    }
    ```
    
    이렇게 하나의 파일에서 JSON 파일을 관리하기 때문에 파일의 수정이 필요한 경우 파일 명을 입력하는 코드를 찾아갈 필요 없이 `JSONFile.swift` 파일에서 모두 해결할 수 있었습니다. 위의 `JSONFile` 타입을 적용하여 아래와 같이 코드를 수정하였습니다.
    
    ```swift
    private func decodeExpositionUniverselle() {
        do {
            expositionUniverselle = try JSONDecoder().decode(ExpositionUniverselle.self, from: JSONFile.exposition.name)
        } catch {
            print(error)
        }
    }
    ```

### 세 번째 뷰로 데이터 넘기기
- 두 번째 뷰 컨트롤인 `ExpositionItemViewController`에서 `JSON` 데이터를 사용할 때 `decodeItems()` 메서드를 통해 디코딩 된 데이터를 `itemList`에 할당합니다. 세 번째 뷰 컨트롤인 `ExpositionItemListViewController`에서도 위와 같이 디코딩을 하면 같은 결과가 나오지만, 동일한 파일을 두 번 디코딩 하는 것보다 두 번째 뷰 컨트롤에서 다음 뷰 컨트롤러에 데이터를 넘겨주는 편이 동일한 작업을 여러 번 반복하지 않아 좋다고 생각했기 때문에 아래와 같이 구현했습니다.

    ```swift
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
        let expositionItemViewController: ExpositionItemViewController = ExpositionItemViewController(item: itemList[indexPath.row])
        navigationController?.pushViewController(expositionItemViewController, animated: true)
    }
    ```

### `JSONDecoder Extension`
- 같은 `decode()` 메서드를 현재 두 번 사용하고 있는데, `do - try - catch` 과정에서 `NSDataAsset`을 옵셔널 바인딩을 해서 사용하고 있었습니다. `decode()` 메서드를 사용하는 횟수가 늘어난다면, `NSDataAsset`에 대한 옵셔널 바인딩 코드가 중복되는 것 같다고 생각하여 `Extension`으로 `decode`의 기능을 다음과 같이 확장하여 사용했습니다.

    ```swift
    extension JSONDecoder {
        func decode<T: Decodable>(_ type: T.Type, from assetName: String) throws -> T {
            guard let json = NSDataAsset(name: assetName) else {
                throw NSDataAssetError.invalidDataAsset
            }

            return try JSONDecoder().decode(type, from: json.data)
        }
    }
    ```

### `CustomCell` 사용
- 두 번째 뷰에서 각각의 셀이 `subtitle`을 필요로 했습니다.

    ```swift
    cell.detailTextLa [...]

2023-07-03 11:42 UTC, 1Consumption requested changes
고생하셨습니다.

> 스토리보드로 UI를 구현할 때 아이콘을 스토리보드에 생성하는 순간 UI가 생성되고, 그것을 ViewController와 각각의 UI들을 연결해 주는 작업을 진행했었습니다. 코드 베이스로 변경된 지금의 코드를 보면, ViewController에서 UI를 생성하고 연결까지 하는 두 개의 동작을 하기 때문에 UI를 생성하는 부분은 View에 들어가야 된다고 생각합니다. 이러한 과정들이 어떻게 나눠지고, 실행되어야 하는지에 대해 잘 알지 못하여 ViewController에 모두 구현한 상태로 이 부분을 아직 해결하지 못하였습니다.

고민하신 점에 적어주신 `아이콘을 스토리보드에 생성하는 순간 UI가 생성되고,` 라는 부분이 어떤 것을 뜻하는지 잘 모르겠습니다. 이 부분을 조금 더 자세하게 설명해 주시겠어요?

`UIViewController`에 많은 subView들이 있는게 보기 싫다면 `UIViewController`의 view를 customView로 만들어주는 방법도 있을 것 같습니다. `LoadView`라는 라이프사이클을 찾아보세요.

2023-07-03 11:42 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemListViewController.swift
> +        configureItemListTableViewConstraint()
여기 있는 코드들의 추상화 수준이 안맞네요. 역할별로 메소드로 분리해보시겠어요?

2023-07-03 11:42 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemListViewController.swift
> +    }
print를 하면 앱을 사용하는 사용자들은 에러 발생 상황을 인지하지 못합니다. 어떤 방법이 있을까요?

2023-07-03 11:42 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemListViewController.swift
> +        tableView.translatesAutoresizingMaskIntoConstraints = false
이 코드의 역할은 뭔가요? 왜 해주셨나요?

2023-07-03 11:42 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemListViewController.swift
> +    }()
클로저 생성을 통해 인스턴스를 만들어준 이유는 뭔가요? 이렇게하면 어떤 장점이 있던가요?

2023-07-03 11:42 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemListViewController.swift
> +        cell.imageView?.image = UIImage(named: itemList[indexPath.row].imageName)
하나하나 접근하지말고 메소드 하나로 접근을 제어해보는건 어떨까요?

2023-07-03 11:42 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemViewController.swift
> +final class ExpositionItemViewController: UIViewController {
final을 붙여준 이유가 궁금합니다. 이 키워드는 어떤 역할을 하나요?

2023-07-03 11:42 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemViewController.swift
> +    }()
이정도는 굳이 클로저 생성을 안해도 될 것 같은데요..ㅋㅋ

2023-07-03 11:42 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemViewController.swift
> +    private var expositionItem: Item
var인 이유가 없어보입니다.

2023-07-03 11:42 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemViewController.swift
> +    }
이 이니셜라이저는 언제 불리나요? fatalError를 해준 의도가 궁금합니다.

2023-07-03 11:42 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionUniverselleViewController.swift
> +    }
어차피 StackView에 들어가는데 왜 매개변수 타입이 AnyObject인가요?

2023-07-03 11:42 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionUniverselleViewController.swift
> +        }
compactMap에 대해서 알아보세요.

2023-07-03 11:42 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
이 코드의 역할이 궁금합니다. 한줄한줄 설명해주시겠어요?

2023-07-03 11:42 UTC, 1Consumption commented on Expo1900/Expo1900/Model/JSONFile.swift
> +}
`CustomStringConvertible`이라는 프로토콜을 한번 알아보시고, 적용할 수 있으면 적용해보시면 좋겠습니다.

2023-07-03 12:42 UTC, Hoon94 commented on Expo1900/Expo1900/Controller/ExpositionItemListViewController.swift
> +        cell.imageView?.image = UIImage(named: itemList[indexPath.row].imageName)
`configureCell(with:item:)` 메서드를 사용하여 셀에 접근하도록 수정하였습니다.

2023-07-03 12:50 UTC, idinaloq commented on Expo1900/Expo1900/Controller/ExpositionItemViewController.swift
> +    private var expositionItem: Item
`private var expositionItem: Item`는 init에서 초기화가 되기 때문에 `let`으로 변경하였습니다.

2023-07-03 12:51 UTC, idinaloq commented on Expo1900/Expo1900/Controller/ExpositionItemViewController.swift
> +    }()
클로저 제거하였습니다!!

2023-07-03 13:00 UTC, Hoon94 commented on Expo1900/Expo1900/Controller/ExpositionUniverselleViewController.swift
> +    }
`UIView`타입을 사용하여 `addArrangedSubviews(to superview: UIStackView, elements subviews: [UIView])`로 수정하였습니다.

2023-07-03 13:02 UTC, Hoon94 commented on Expo1900/Expo1900/Controller/ExpositionUniverselleViewController.swift
> +        }
위와 같이 subviews의 타입을 `UIView`로 수정을 하여 guard let을 통한 옵셔널 바인딩을 사용하지 않게 되었습니다.
```swift
private func addArrangedSubviews(to superview: UIStackView, elements subviews: [UIView]) {
    subviews.forEach {
        superview.addArrangedSubview($0)
    }
}
```

2023-07-03 13:16 UTC, idinaloq commented on Expo1900/Expo1900/Model/JSONFile.swift
> +}
`CustomStringConvertible`프로토콜을 채택하도록 수정했습니다.

``` swift
enum JSONFile: CustomStringConvertible {
    case exposition
    case items
    
    var description: String {
        switch self {
        case .exposition:
            return "exposition_universelle_1900"
        case .items:
            return "items"
        }
    }
}

```

2023-07-04 02:33 UTC, Hoon94 commented on Expo1900/Expo1900/Controller/ExpositionItemListViewController.swift
> +        tableView.translatesAutoresizingMaskIntoConstraints = false
`translatesAutoresizingMaskIntoConstraints`의 [공식 문서](https://developer.apple.com/documentation/uikit/uiview/1622572-translatesautoresizingmaskintoco)를 보면 뷰의 `Autoresizing mask`를 `Auto Layout constraints`로 바꿀지를 결정하는 `Boolean` 값이라고 설명합니다. `translatesAutoresizingMaskIntoConstraints`의 값이 `true` 일 때 시스템은 뷰의 `Autoresizing mask`에 의해 지정된 제약 조건을 생성합니다. 이러한 경우에 새로운 제약 조건을 추가하면 이전 제약 조건과 충돌이 발생할 수 있습니다. 이를 해결하기 위해 `translatesAutoresizingMaskIntoConstraints`의 값을 `false`로 설정합니다.

2023-07-04 02:37 UTC, Hoon94 commented on Expo1900/Expo1900/Controller/ExpositionItemListViewController.swift
> +    }()
클로저를 사용하여 인스턴스를 생성함으로써 관련된 코드를 블록화하여 가독성을 높일 수 있었습니다. 뷰를 생성하고 이에 필요한 프로퍼티들을 함께 설정함으로써 하나의 코드 블록 안에서 필요한 모든 동작을 수행해 가독성을 높였습니다.

2023-07-04 02:39 UTC, Hoon94 commented on Expo1900/Expo1900/Controller/ExpositionItemViewController.swift
> +final class ExpositionItemViewController: UIViewController {
[final](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/inheritance/#Preventing-Overrides) 키워드는 더 이상 상속이 필요 없음을 명시적으로 표현하며, 오버라이드 할 시 컴파일 에러를 발생시킬 수 있습니다.

2023-07-04 03:11 UTC, Hoon94 commented on Expo1900/Expo1900/Controller/ExpositionItemListViewController.swift
> +        configureItemListTableViewConstraint()
`viewDidLoad()` 메서드의 추상화 수준을 같게 수정하였습니다.

2023-07-04 03:15 UTC, idinaloq commented on Expo1900/Expo1900/Controller/ExpositionItemListViewController.swift
> +    }
[UIAlertController](https://developer.apple.com/documentation/uikit/uialertcontroller)를 사용해서 사용자에게 [Alerts](https://developer.apple.com/design/human-interface-guidelines/alerts)을 표시해서 에러 발생 상황을 알리는 방법이 있다고 생각합니다.

2023-07-04 06:20 UTC, idinaloq commented on Expo1900/Expo1900/Controller/ExpositionItemViewController.swift
> +    }
상속받은 `init()` 메서드 대신 `ExpositionItemViewController`에서 지정 생성자를 직접 구현했습니다. 
현재 코드베이스를 통해 초기화를 진행하고 있고, 스토리보드나 xib 파일을 사용하는 경우는 없기 때문에 `required init?` 메서드가 직접 호출될 일은 없다고 생각합니다. 만약 호출된다면 비정상적인 작동이기 때문에 `fatalError`를 통해 앱이 실행 종료되도록 했습니다.

2023-07-04 07:39 UTC, idinaloq commented on Expo1900/Expo1900/Controller/SceneDelegate.swift
> +        window?.makeKeyAndVisible()
이 코드는 네이게이션 컨트롤러를 루트뷰 컨트롤러로 지정해주는 역할입니다.
```swift
//UIWindowScene은 scene을 관리하고, UIScene은 앱에서 사용자 인터페이스를 표시하는 역할
//UIScene을 상속받은 UIWindowScene으로 Scene을 관리하기위해 다운캐스팅을 사용
guard let windowScene = (scene as? UIWindowScene) else { return }
    
// SceneDelegate의 프로퍼티에 할당
// windowScene이 관리할 window 생성
window = UIWindow(windowScene: windowScene)
    
// 맨 처음 보여줄 ViewController 할당
let mainViewController = ExpositionUniverselleViewController()
    
// mainViewController를 사용하여 UINavigationController 초기화
// 네비게이션의 첫 화면을 mainViewController로 지정
let navigationController = UINavigationController(rootViewController : mainViewController)
    
// 화면의 첫 시작지점을 할당
window?.rootViewController = navigationController
    
// window를 화면에 표시하고 key window로 사용
window?.makeKeyAndVisible()
}
```

2023-07-04 08:00 UTC, idinaloq commented
고민하신 점에 적어주신 아이콘을 스토리보드에 생성하는 순간 UI가 생성되고, 라는 부분이 어떤 것을 뜻하는지 잘 모르겠습니다. 이 부분을 조금 더 자세하게 설명해 주시겠어요?

- 스토리보드로 UI를 구현할 때 아이콘을 스토리보드에 추가하면 XML에도 추가가 되어 UI에 대한 정보가 기록된다고 생각했습니다.

2023-07-04 13:03 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemListViewController.swift
> +    }
그럼 그렇게 바꿔주세요.

2023-07-04 13:04 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemViewController.swift
> +final class ExpositionItemViewController: UIViewController {
이 키워드를 사용해서 여러분들은 어떤 이점을 얻을 수 있었나요?

2023-07-04 15:16 UTC, idinaloq commented on Expo1900/Expo1900/Controller/ExpositionItemListViewController.swift
> +    }
https://github.com/yagom-academy/ios-exposition-universelle/pull/278/commits/46e0d96560980d5c652b589c15faee9d866d56df

에러 발생 시 사용자들이 얼럿을 통해 확인할 수 있도록 수정하였습니다.

2023-07-04 15:20 UTC, idinaloq commented on Expo1900/Expo1900/Controller/ExpositionItemViewController.swift
> +final class ExpositionItemViewController: UIViewController {
현재 코드에서는 `final` 키워드를 사용하여 얻은 이점은 없다고 생각합니다. 하지만 프로젝트 규모가 커진다고 가정한다면 상속받는 것에 대한 문제를 미연에 방지할 수 있다고 생각합니다.

2023-07-05 00:54 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpositionItemViewController.swift
> +final class ExpositionItemViewController: UIViewController {
상속받는 것에 대한 문제는 상황이고, 왜 그 상황이 문제인지를 알아보면 좋겠습니다.

2023-07-05 00:54 UTC, merged