만국박람회 [STEP 2] yyss99, kyungmin
yagom-academy/ios-exposition-universelle pull request #279
Opened 2023-07-03 12:07 UTC by yy-ss99

@1Consumption

안녕하세요 올라프☃️

kyungmin, yyss99 Step2 PR 보냅니다

조금 늦었지만 사소한 부분이라도 조언해주시면 달게 듣겠습니다🫡

## 🔍 고민되었던 점

### NumberFormatter

- class? struct? extension?
    
    방문객 수에 `,`를 추가하는 방법으로 `numberFormatter`를 `struct`나 `class` 타입으로 만들어서 인스턴스를 만드는 방법을 고려했습니다. 하지만 인스턴스를 만들어 쓰는 것 보다는 `extension` 해서 사용하는 것이 더 뷰 컨트롤러 코드 상으로 간단하다는 이점이 있어 `extension` 하는 방법을 선택하게 되었습니다.
    

## 🙏 조언을 얻고 싶은 부분

### Decoder 파일의 위치 🤔

`JSON`파일명을 입력받아 디코딩해주는 `Decoder`객체의 파일의 위치는 `Model`에 있어야 한다고 생각했습니다. 하지만 `NSDataAsset` 클래스를 사용하기 위해 `UIKit`모듈을 `import` 해줘야 해서 `Model`안의 파일이 `UIKit`을 `import`해줘도 되는지 의문점이 들었습니다.

### AutoLayout 코드❓ 스토리보드⁉️

이번 프로젝트에서는 스토리보드 만을 이용하여 `AutoLayout`을 잡아보려고 노력했습니다. 코드로 제약을 잡는 것과 스토리보드 사이에서 더 많이 사용 되는 방법이 궁금하고, 두 방법의 차이와 장단점이 궁금합니다. 

```swift
private func setUpUI() {
    entryImageView.translatesAutoresizingMaskIntoConstraints = false
    contentView.addSubview(entryImageView)

    titleLabel.translatesAutoresizingMaskIntoConstraints = false
    titleLabel.font = UIFont.preferredFont(forTextStyle: .title1)
    titleLabel.adjustsFontForContentSizeCategory = true
    titleLabel.textColor = .black

    shortDescLabel.translatesAutoresizingMaskIntoConstraints = false
    shortDescLabel.font = UIFont.preferredFont(forTextStyle: .body)
    shortDescLabel.adjustsFontForContentSizeCategory = true
    shortDescLabel.textColor = .black
    shortDescLabel.numberOfLines = 0

    let containerStackView = UIStackView(arrangedSubviews: [titleLabel, shortDescLabel])
    containerStackView.translatesAutoresizingMaskIntoConstraints = false
    containerStackView.alignment = .fill
    containerStackView.distribution = .fill
    containerStackView.spacing = 8
    containerStackView.axis = .vertical
    contentView.addSubview(containerStackView)

    NSLayoutConstraint.activate([
        entryImageView.topAnchor.constraint(equalTo: contentView.topAnchor, constant: 8),
        entryImageView.leadingAnchor.constraint(equalTo: contentView.leadingAnchor),
        entryImageView.widthAnchor.constraint(equalTo: contentView.widthAnchor, multiplier: 0.2),
        entryImageView.widthAnchor.constraint(equalTo: entryImageView.heightAnchor),
        entryImageView.bottomAnchor.constraint(lessThanOrEqualTo: contentView.bottomAnchor, constant: -8),
        containerStackView.leadingAnchor.constraint(equalTo: entryImageView.trailingAnchor, constant: 8),
        containerStackView.topAnchor.constraint(equalTo: contentView.topAnchor),
        containerStackView.trailingAnchor.constraint(equalTo: contentView.trailingAnchor),
        containerStackView.bottomAnchor.constraint(equalTo: contentView.bottomAnchor)
    ])
}
```

그리고 위의 코드로 제약을 잡았을때는 제약 오류가 나지 않던 `AutoLayout`이 스토리보드 상으로 `adjustsFontForContentSizeCategory`이 옵션을 제외하고 나머지 제약을 똑같이 잡아줬더니 제약 오류가 났습니다. 

## 📚 참고 링크

[🍎Apple Docs: JSONDecoder](https://developer.apple.com/documentation/foundation/jsondecoder)

[🍎Apple Docs: Using JSON with Custom Types](https://developer.apple.com/documentation/foundation/archives_and_serialization/using_json_with_custom_types)

[🍎Apple Docs: Encoding and Decoding Custom Types](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types)

[🍎Apple Docs: UINavigationController](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types)

[🍎Apple Docs: UITableViewDelegate](https://developer.apple.com/documentation/uikit/uitableviewdelegate)

[🍎Apple Docs: UITableViewDataSource](https://developer.apple.com/documentation/uikit/uitableviewdatasource)

2023-07-04 13:02 UTC, 1Consumption requested changes
고생하셨습니다. @yy-ss99 @YaRkyungmin 

커밋이 하나의 역할만 하도록 노력한게 눈에 보입니다.
또한 일관성 있는 코드스타일을 가져가려고 한 것이 느껴지네요.

다만 아쉬운 점은 아직은 코드스타일이 전부 일관성 있지는 않다 입니다.
예를 들자면 클래스 선언 후 어떤 클래스는 한칸 개행을 하는데, 어디는 하지 않은 경우가 있겠습니다.

아래는 조언을 얻고 싶은 점에 적어주신 제 생각입니다.

> Decoder 파일의 위치 🤔
JSON파일명을 입력받아 디코딩해주는 Decoder객체의 파일의 위치는 Model에 있어야 한다고 생각했습니다. 하지만 NSDataAsset 클래스를 사용하기 위해 UIKit모듈을 import 해줘야 해서 Model안의 파일이 UIKit을 import해줘도 되는지 의문점이 들었습니다.

정말 엄밀히 따지면 말씀해주신게 맞습니다. Model은 View를 몰라야하죠. 그런데 이건 어디까지를 View로 볼것이냐부터 정해야 할 것 같습니다. 예를 들어 저는 `UIImage`도 모델로 보는 편입니다. URL을 Data로 만들고 UIImage로 만드는데 필요한 비즈니스 로직이 있다고 생각하기 때문입니다. 하여 이부분은 여러분들께서 정하시고, 나름의 기준을 세우면 좋을 것 같습니다.

> AutoLayout 코드❓ 스토리보드⁉️
이번 프로젝트에서는 스토리보드 만을 이용하여 AutoLayout을 잡아보려고 노력했습니다. 코드로 제약을 잡는 것과 스토리보드 사이에서 더 많이 사용 되는 방법이 궁금하고, 두 방법의 차이와 장단점이 궁금합니다.
그리고 위의 코드로 제약을 잡았을때는 제약 오류가 나지 않던 AutoLayout이 스토리보드 상으로 adjustsFontForContentSizeCategory이 옵션을 제외하고 나머지 제약을 똑같이 잡아줬더니 제약 오류가 났습니다.

보통 현업에서 많이 사용되는 방법은 코드입니다. 그러나 이건 회사 바이 회사이고, 스토리보드를 주로 사용하는 회사도 있습니다. 또한 스토리보드는 레거시니까 안좋은 방법이라고 할 수도 없습니다. 

장단점 같은 경우는 여러분들이 학습해야할 부분 같아서 따로 언급하지는 않겠습니다. 제가 굳이 알려드리지 않아도 이미 블로그나 아티클이 많이 있고, 또한 정보를 구하기도 쉽습니다. 중요한 것은 직접 만져보면서 장점이 진짜 장점이 맞는지, 단점은 진짜 단점인지를 피부로 느끼는 것입니다.

제약 오류 같은 경우는 에러 로그를 같이 보여주셔야 추측이 가능합니다.

------------------------------------------------------------------------

나머지는 코멘트를 참고해주세요.

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +final class EntryDetailViewController: UIViewController {
final키워드를 붙인 이유는 무엇인가요? 이 키워드는 어떤 역할을 하나요?

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    var expoEntry: ExpoEntry?
생성자를 통해 주입해주면 외부에서 몰라도 되는 정보 같아요. 또한 옵셔널이 아니어도 될 것 같습니다. 

https://developer.apple.com/documentation/uikit/uistoryboard/3213989-instantiateviewcontroller 이 메소드를 공부해보세요.

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    }
외부에서 몰라도 되는 정보 같습니다.

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/EntryTableViewCell.swift
> +    }
super 메소드를 호출하지 않았는데, 이러면 어떤 일이 발생할까요?

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/EntryViewController.swift
> +    }
외부에서 몰라도 되는 코드 같아요.

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/EntryViewController.swift
> +        }
에러처리를 한 것은 좋은데, 이러면 앱을 사용하는 사용자들이 에러가 발생했음을 알 수 있을까요? 어떻게해야 사용자에게 에러가 발생했음을 전달할 수 있을까요?

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/EntryViewController.swift
> +        updateEntryTableView()
`updateExpoEntries()` 이후에 `updateEntryTableView(`) 이유는 무엇인가요?

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoViewController.swift
> +    }
외부에서 몰라도 되는 코드네요.

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Controller/ExpoViewController.swift
> +        } catch DecodeError.searchNoFile {
이부분은 로직이 들어간 것 같습니다. View의 역할이 아니라고 생각됩니다. 이런 역할을 담당하는 객체를 만들어보는건 어떨까요?

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Model/DecodeError.swift
> +enum DecodeError: LocalizedError {
LocalizedError 👍

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Model/Decoder.swift
> +}
왜 struct로 선언하셨나요? 네임스페이스를 제공하기 위함이라면 enum도 있는데요.

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Model/Decoder.swift
> +    static func decodeJson<Data: Decodable>(from dataAssetName: String) throws -> Data {
왜 `Data: Decodable`으로 표현하셨나요? `Decodable` 프로토콜 자체를 제네릭으로 넣으면 안되는걸까요? 만약 아래와 같이 바꾸면 어떤 일이 벌어지나요?
```suggestion
    static func decodeJson(from dataAssetName: String) throws -> Decodable {
```

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Model/Decoder.swift
> +    static func decodeJson<Data: Decodable>(from dataAssetName: String) throws -> Data {
`Data`라는 이름은 이미 swift의 타입 이름입니다. 중복이고, 개발자에게 혼동을 줄 수 있어 가독성을 해칩니다. 다른 이름을 고민해보세요.

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Model/Decoder.swift
> +    static func decodeJson<Data: Decodable>(from dataAssetName: String) throws -> Data {
왜 static으로 선언하셨나요?

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Model/Extension/NumberFormatter +.swift
> +}
여기도 `Decoder`에 해당하는 코멘트와 같습니다.

2023-07-04 13:02 UTC, 1Consumption commented on Expo1900/Expo1900/Model/NameSpace/AssetsNameSpace.swift
> +
불필요한 공백이네요.

2023-07-05 01:29 UTC, yy-ss99 commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +final class EntryDetailViewController: UIViewController {
`final` 키워드는 상속과 오버라이딩을 방지하는 역할을 합니다.

2023-07-05 05:40 UTC, yy-ss99 commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    }
`private` 키워드 붙여주었습니다!

2023-07-05 05:41 UTC, yy-ss99 commented on Expo1900/Expo1900/Controller/EntryViewController.swift
> +    }
`private` 키워드 추가했습니다!

2023-07-05 05:42 UTC, yy-ss99 commented on Expo1900/Expo1900/Controller/ExpoViewController.swift
> +    }
`private` 키워드 추가했습니다!

2023-07-05 06:04 UTC, YaRkyungmin commented on Expo1900/Expo1900/Controller/EntryViewController.swift
> +        updateEntryTableView()
`tableView`객체 메서드가 호출 되기 전에 `JSON`정보를 받아와야 한다고 생각했는데 `Delegate`, `DataSource`객체를 지정해주는 것만으로는 `tableView`객체 메서드가 호출되지 않는다는 사실을 알게 됐습니다. 감사합니다.🙏🏻

2023-07-05 06:05 UTC, yy-ss99 commented on Expo1900/Expo1900/Model/NameSpace/AssetsNameSpace.swift
> +
수정했습니다!👍

2023-07-05 06:08 UTC, YaRkyungmin commented on Expo1900/Expo1900/Model/Decoder.swift
> +}
`네임스페이스를 제공하기 위함`이라는 말의 뜻을 모르겠습니다😭
`JSON`데이터를 `DTO`객체로 디코딩 해주기 위해 `Decoder`타입을 정의해줬습니다.
말씀해주신대로 `enum`으로 수정했습니다.

2023-07-05 06:16 UTC, YaRkyungmin commented on Expo1900/Expo1900/Model/Decoder.swift
> +    static func decodeJson<Data: Decodable>(from dataAssetName: String) throws -> Data {
`Decodable`프로토콜 자체를 제네릭으로 넣으면 `Decodable`네임 자체가 제네릭 타입으로 돼서 `Decodable`프로토콜을 채택한 타입이라고 명시해줄 수 없는 것 같습니다😭
저희가 제네릭에 대해 잘못 이해하고 있는 걸까요?

2023-07-05 06:17 UTC, YaRkyungmin commented on Expo1900/Expo1900/Model/Decoder.swift
> +    static func decodeJson<Data: Decodable>(from dataAssetName: String) throws -> Data {
`DataType`으로 변경해줬습니다🙏🏻

2023-07-05 06:21 UTC, YaRkyungmin commented on Expo1900/Expo1900/Model/Decoder.swift
> +    static func decodeJson<Data: Decodable>(from dataAssetName: String) throws -> Data {
`struct`타입으로 선언해줬을때는 디코딩이 필요한 곳마다 `struct`인스턴스를 생성하지 않기 위해 `static`메서드를 정의해줬습니다😭
`enum`타입으로 변경해주면서 어쩔 수 업이 `static`메서드를 이용해줘야 되는 것 같습니다.

2023-07-05 06:24 UTC, yy-ss99 commented on Expo1900/Expo1900/Model/Extension/NumberFormatter +.swift
> +}
NumberFormatter 타입 자체에 extension하여서 numberFormatter상수를 정의하고 메서드도 쓸 수 있도록 `static`키워드를 사용했습니다. 이렇게 하면 따로 인스턴스 생성 없이 사용할 수 있는 이점이 있다고 생각했습니다.

2023-07-05 06:50 UTC, yy-ss99 commented on Expo1900/Expo1900/Controller/EntryTableViewCell.swift
> +    }
`super.prepareForReuse()`를 호출하지 않으면 부모 클래스의 기본 동작이 실행되지 않을 수 있어 재사용 이전의 셀 상태가 그대로 유지될 수 있습니다. 셀이 재사용 될 때 셀에 이전에 설정된 이미지나 텍스트 등이 남아있을 수 있다고 생각해서 추가 해주었습니다.

2023-07-05 08:05 UTC, yy-ss99 commented on Expo1900/Expo1900/Controller/EntryViewController.swift
> +        }
Alert을 추가해서 화면에 오류 발생시 사용자에게 알리도록 수정했습니다!

2023-07-05 08:37 UTC, 1Consumption commented on Expo1900/Expo1900/Model/Decoder.swift
> +    static func decodeJson<Data: Decodable>(from dataAssetName: String) throws -> Data {
앗 수정했어요 코멘트 다시 확인 부탁드릴게요~

2023-07-05 08:38 UTC, 1Consumption commented on Expo1900/Expo1900/Model/Decoder.swift
> +    static func decodeJson<Data: Decodable>(from dataAssetName: String) throws -> Data {
~Type도 좋은 이름은 아닙니다. Swift는 모든 것을 타입으로 보기 때문입니다. 하여 중복이라고 생각합니다.

2023-07-05 08:57 UTC, yy-ss99 commented on Expo1900/Expo1900/Controller/ExpoViewController.swift
> +        } catch DecodeError.searchNoFile {
넵 연산 프로퍼티를 활용해서 로직을 분리했습니다!

2023-07-05 08:57 UTC, yy-ss99 commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    var expoEntry: ExpoEntry?
넵 생성자를 통해 주입하는 것으로 바꾸었습니다!

2023-07-05 09:08 UTC, YaRkyungmin commented on Expo1900/Expo1900/Model/Decoder.swift
> +    static func decodeJson<Data: Decodable>(from dataAssetName: String) throws -> Data {
```swift
let decodeData = try jsonDecoder.decode(T.self, from: dataAsset.data)
```
말씀해주신대로 바꾸면 위의 코드에서 DTO객체 타입을 찾을 수 가 없습니다😭

2023-07-05 09:09 UTC, YaRkyungmin commented on Expo1900/Expo1900/Model/Decoder.swift
> +    static func decodeJson<Data: Decodable>(from dataAssetName: String) throws -> Data {
`T`로 변경했습니다. `DecodeObject`가 더 나은 대안 일까요?

2023-07-06 02:05 UTC, YaRkyungmin commented on Expo1900/Expo1900/Model/Decoder.swift
> +    static func decodeJson<Data: Decodable>(from dataAssetName: String) throws -> Data {
프로토콜을 반환 타입으로 사용하면 확장성이 좋은 코드를 작성 할 수 있고,  의존성 주입을 통해 코드의 결합도를 낮출 수 있다는 것에 대해 알게됐습니다. 하지만 `decode`메서드의 `parameter`가 메타 타입 이기때문에 `Decodable.self`를 하면 프로토콜이 나오기 때문에 저희 코드에서는 적용할 수 없었습니다😭
```swift
enum Decoder {
    static func decodeJson(from dataAssetName: String) throws -> Decodable {
        let jsonDecoder: JSONDecoder = JSONDecoder()

        guard let dataAsset = NSDataAsset(name: dataAssetName) else {
            throw DecodeError.searchNoFile
        }

        do {
            let decodeData = try jsonDecoder.decode(Decodable.self, from: dataAsset.data)

            return decodeData
        } catch {
            throw DecodeError.jsonDecodeError
        }
    }
}
```

2023-07-06 09:21 UTC, merged