만국박람회 [STEP 3] Erick, 비모
yagom-academy/ios-exposition-universelle pull request #287
Opened 2023-07-06 08:41 UTC by bubblecocoa

@July911 
안녕하세요 July!
Erick & 비모입니다!
만국박람회 마지막 STEP3 PR 보냅니다.
항상 좋은 리뷰 감사드립니다!!
마지막까지 잘 부탁드립니다 🙇

---

## 고민했던점 

### 1️⃣ Safe Area
step2에서는 Safe Area를 기준으로 오토레이아웃을 설정하지 않고 `superView`를 기준으로 UI를 설정하여 아래 사진과 같이 텍스트가 잘리는 경우가 발생하기도 했습니다.
이를 해결하기 위해 ScrollView를 Safe Area를 기준으로 하여 오토레이아웃을 설정하여 넘어가지 말아야 하는 부분으로는 콘텐츠가 넘어가지 않도록 설정하였습니다.
|superView 기준|Safe Area 기준|
|:----:|:----:|
|<img src="https://github.com/h-suo/TIL/assets/109963294/0e925614-642e-4eac-b8dc-928830a6ea5e" width="300">|<img src="https://github.com/h-suo/TIL/assets/109963294/4476242e-0b1a-47f0-8628-d36827e8a568" width="300">|

</br>

### 2️⃣ 특정 뷰만 회전하도록 설정하는 방법
처음에는 `AppDelegate`에서 해당 `ViewController`가 특정 화면인지 확인한 후 회전이 가능하도록 했습니다.
```swift
@main
class AppDelegate: UIResponder, UIApplicationDelegate {
    ...
    func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
        if let navigationController = window?.rootViewController as? UINavigationController,
           let _ = navigationController.visibleViewController as? ExpositionUniverselleViewController {
            return .portrait
        }
        
        return .all
    }
    ...
}
```

하지만 `AppDelegate`가 모든 화면에 대한 회전 방향 정보를 가지고 분기처리 하는것보다, 각각의 화면이 직접 자신이 어떤 회전을 허용하고 있는지 아는것이 더 나은 방법이라고 생각했습니다.

따라서 위의 코드는 제거하고, `Embeded In` 되어있던 `Navigation Controller`에 `ExpositionUniverselleNavigationController`를 지정해 주었습니다.
```swift
class ExpositionUniverselleNavigationController: UINavigationController {
    ...
    override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        if let supportedInterfaceOrientations = self.topViewController?.supportedInterfaceOrientations {
            return supportedInterfaceOrientations
        }
        
        return self.supportedInterfaceOrientations
    }
}
```

```swift
final class ExpositionUniverselleViewController: UIViewController {
    ...
    override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        return .portrait
    }
    ...
}
```
코드 자체는 크게 다르지 않지만 `topViewController`를 이용하는 것으로 `AppDelegate`의 역할을 줄이고, 해당 `view`를 띄워주는 `Navigation Controller`가 하위 `View Controller`의 옵션을 보고 회전을 판단하도록 하였습니다.

### 3️⃣ 스토리보드에서 버튼에 Dynamic Type 적용
모든 `Label`에 대해 `Dynamic Type`적용을 했으나, 디버그 도중 `Button`의 `text`만 `Dynamic Type`이 적용되지 않는 현상을 발견했습니다. 코드로 `Button.titleLabel`의 옵션을 설정하여 `Dynamic Type`을 적용할 수 있었습니다. 그리고 스토리보드에서는 `Button Style`을 `Default`에서 `Plain`으로 바꾸면 `Dynamic Type`이 적용되었습니다.

**코드**
```swift
button.titleLabel?.adjustsFontForContentSizeCategory = true
button.titleLabel?.numberOfLines = 0
```

**스토리보드**
<img src="https://github.com/h-suo/TIL/assets/109963294/2aca371d-a6c8-4d85-8eee-63841d7d81c0" width="300">

두 방식 모두 코드를 통해 `Dynamic Type`을 지정할 수 있는 방법이 있지만, 저희는 스토리보드를 베이스로 이번 프로젝트를 작업했기 때문에 버튼 스타일을 `Plain`으로 바꾸는 것으로 마무리 하였습니다.

<br>

#### 참고링크🔗
- [🍎 Developer Apple - application(_:supportedInterfaceOrientationsFor:)](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623107-application)
- [🍎 Developer Apple - supportedInterfaceOrientations](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621435-supportedinterfaceorientations)

2023-07-07 08:18 UTC, July911 requested changes

2023-07-07 08:18 UTC, July911 commented on Expo1900/Expo1900/Controller/ExpositionUniverselleNavigationController.swift
> +class ExpositionUniverselleNavigationController: UINavigationController {
상속받나요 ?

2023-07-07 08:18 UTC, July911 commented on Expo1900/Expo1900/Controller/ExpositionUniverselleNavigationController.swift
> +
필요없는 인덴트같습니다.

2023-07-07 08:18 UTC, July911 commented on Expo1900/Expo1900/Controller/ExpositionUniverselleViewController.swift
> +            print(error.localizedDescription)
프린트 말고 다른 방법은 없나요 ?

2023-07-07 08:18 UTC, July911 commented on Expo1900/Expo1900/Controller/ExpositionUniverselleViewController.swift
> +    private func configure() {
모호한 이름 같습니다.

2023-07-07 08:18 UTC, July911 commented on Expo1900/Expo1900/Controller/ItemDetailViewController.swift
> +    private func configure() {
이름 수정 부탁드립니다.

2023-07-07 08:18 UTC, July911 commented on Expo1900/Expo1900/Controller/ItemsTableViewController.swift
>      static let id = "itemsTableViewControllerID"
이건 왜 필요한가요 ?

2023-07-07 08:18 UTC, July911 commented on Expo1900/Expo1900/Base.lproj/Main.storyboard
> +                                                    <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="Label" textAl
adjustsFontForContentSizeCategory 옵션에 대해 설명해주세요.

2023-07-07 08:18 UTC, July911 commented on Expo1900/Expo1900/Base.lproj/Main.storyboard
> +                                                    <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="Label" textAl
numberOfLines 을  0 으로 하면 어떤 동작을 하나요 ?

2023-07-07 08:18 UTC, July911 commented on Expo1900/Expo1900/Base.lproj/Main.storyboard
> +                                            <stackView opaque="NO" contentMode="scaleToFill" distribution="equalCentering" alignment="center" spacing="8" translatesAutoresizingMaskIntoConstraints="NO
equalCentering 

distribution 의 종류는 무엇이 있으며, 이게 적절한지 한번 생각해보세요.

2023-07-07 08:18 UTC, July911 commented on Expo1900/Expo1900/Base.lproj/Main.storyboard
> +                                                        <buttonConfiguration key="configuration" style="plain" title="한국의 출품작 보러가기">
button style이 plain 하고 default 의 차이는 무엇이며, 
type에서 system하고 custom의 차이는 무엇인가요 ?

2023-07-07 08:18 UTC, July911 commented on Expo1900/Expo1900/Base.lproj/Main.storyboard
> +                                                <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" ambiguous="YES" text="L
tailTruncation 은 무엇인가요 ? 
한 단어씩 끊기게 하려면 어떤 옵션을 적용해야할까요 ?

2023-07-07 13:39 UTC, h-suo commented on Expo1900/Expo1900/Base.lproj/Main.storyboard
> +                                                    <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="Label" textAl
**adjustsFontForContentSizeCategory**
- 장치의 콘텐츠 크기 범주가 변경될 때 객체가 글꼴을 자동으로 업데이트하는지 여부를 나타내는 속성입니다.
- 사용자가 설정에서 텍스트 크기를 조절하면 자동으로 글꼴 크기를 업데이트 해주기 위해 `true`로 설정하였습니다.

2023-07-07 13:40 UTC, bubblecocoa commented on Expo1900/Expo1900/Base.lproj/Main.storyboard
> +                                                    <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="Label" textAl
즉, `adjustsFontForContentSizeCategory`는 `Dynamic Type`을 `Bool`값을 이용해 적용하는 옵션입니다.

2023-07-07 13:41 UTC, bubblecocoa commented on Expo1900/Expo1900/Base.lproj/Main.storyboard
> +                                                    <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="Label" textAl
해당 옵션을 0으로 지정하면 줄 제한 없이 모든 텍스트 콘텐츠가 출력됩니다.

2023-07-07 13:44 UTC, h-suo commented on Expo1900/Expo1900/Base.lproj/Main.storyboard
> +                                                    <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" text="Label" textAl
`Dynamic Type`을 사용하였기 때문에 텍스트 크기가 증가하면 레이블의 컨텐츠가 길어지게 되는데 이때 `numberOfLines` 설정 이상으로 컨텐츠가 늘어나면 생략이 되기 때문에 이를 방지하기 위해서는 `numberOfLines `의 제한을 없애줬습니다.

2023-07-07 14:04 UTC, h-suo commented on Expo1900/Expo1900/Base.lproj/Main.storyboard
> +                                            <stackView opaque="NO" contentMode="scaleToFill" distribution="equalCentering" alignment="center" spacing="8" translatesAutoresizingMaskIntoConstraints="NO
`flag` 이미지의 비율만 설정했을 때는 `equalCentering`도 적절하다고 생각했지만 지금 처럼 버튼과 이미지가 대칭일 경우에만 성립되는 제약이라고 생각되어 `flag` 이미지에 `stackView`의 16%의 너비를 주고 `distribution`을 `fill`로 수정하였습니다.

2023-07-07 14:20 UTC, h-suo commented on Expo1900/Expo1900/Base.lproj/Main.storyboard
> +                                                <label opaque="NO" userInteractionEnabled="NO" contentMode="left" horizontalHuggingPriority="251" verticalHuggingPriority="251" ambiguous="YES" text="L
`tailTruncation`은 `Line Break`의 옵션으로 콘텐츠가 설정한 줄 밖으로 나갔을 때 마지막 문단의 끝을 생략하는 옵션입니다.
한 단어씩 끊기게 하려면 `Line Break`를 `Word Wrap`으로 설정하면 한 단어씩 줄바꿈이 됩니다.

2023-07-09 00:14 UTC, h-suo commented on Expo1900/Expo1900/Controller/ItemsTableViewController.swift
>      static let id = "itemsTableViewControllerID"
UI를 코드 베이스가 아닌 스토리보드 베이스로 구현하였기 때문에 뷰 컨트롤러에 접근하기 위해서는 `instantiateViewController` 메서드를 사용해야 했습니다. 이때 `instantiateViewController`의 파라미터로 뷰 컨트롤러의 `identifier`가 필요했기 때문에 해당 뷰 컨트롤러에서 타입 프로퍼티로 `id`를 가지고 있는 것이 재사용성을 높여줄 수 있다고 생각하여 사용하였습니다.

2023-07-09 00:26 UTC, h-suo commented on Expo1900/Expo1900/Base.lproj/Main.storyboard
> +                                            <stackView opaque="NO" contentMode="scaleToFill" distribution="equalCentering" alignment="center" spacing="8" translatesAutoresizingMaskIntoConstraints="NO
[UIStackView.Distribution](https://developer.apple.com/documentation/uikit/uistackview/distribution)의 종류에는 `fill`, `fillEqually`, `fillProportionally`, `equalSpacing`, `equalCentering`이 있습니다.

2023-07-09 00:29 UTC, bubblecocoa commented on Expo1900/Expo1900/Base.lproj/Main.storyboard
> +                                            <stackView opaque="NO" contentMode="scaleToFill" distribution="equalCentering" alignment="center" spacing="8" translatesAutoresizingMaskIntoConstraints="NO
UI의도를 해석하면 이미지 일정한 크기를 가지고, 항상 양쪽 끝에 위치합니다.
버튼은 `width`가 늘어남에 따라 함께 늘어납니다.
위 두 상황을 고려했을때, `distribution`은 `fill`로 지정하고, 버튼의 `hugging priority`를 이미지보다 낮게 조정해야 합니다.

2023-07-09 01:11 UTC, bubblecocoa commented on Expo1900/Expo1900/Base.lproj/Main.storyboard
> +                                                        <buttonConfiguration key="configuration" style="plain" title="한국의 출품작 보러가기">
[plain()](https://developer.apple.com/documentation/uikit/uibutton/configuration/3750793-plain)은 iOS 15.0에 추가된 `UIButton.Configuration` 요소입니다.
`UIButton.Configuration`의 스타일에 포함되어 있는 모든 항목은 `Dynamic Type`이 기본이지만, `default`는 그렇지 않습니다.

2023-07-09 01:14 UTC, h-suo commented on Expo1900/Expo1900/Base.lproj/Main.storyboard
> +                                                        <buttonConfiguration key="configuration" style="plain" title="한국의 출품작 보러가기">
[UIButton.ButtonType](https://developer.apple.com/documentation/uikit/uibutton/buttontype)은 `button`의 스타일을 나타내며 버튼을 사용자가 커스텀하게 사용하고 싶다면 `custom`을 apple에서 제공하는 스타일을 사용하고 싶다면 `system`을 사용할 수 있습니다.

2023-07-11 02:19 UTC, h-suo commented on Expo1900/Expo1900/Controller/ExpositionUniverselleViewController.swift
> +            print(error.localizedDescription)
`Alert`을 이용하여 에러가 발생했을 때 사용자가 "데이터 로드에 실패했습니다."라는 알림을 볼 수 있도록 로직을 추가하였습니다.

2023-07-24 06:03 UTC, closed without merging