만국박람회 [STEP 3] karen
yagom-academy/ios-exposition-universelle pull request #288
Opened 2023-07-06 12:28 UTC by karenyang835

@YebinKim

안녕하세요. 븨븨~

만국박람회 프로젝트도 이제 마무리가 되어지게 되었습니다.
븨븨와 더 많은 시간을 함께하고 싶은데 벌써 이렇게 마무리하게 되다니 많이 아쉽습니다.🥹

븨븨께서 많이 배려해주시고 기다려주시고, 또 꼼꼼하고 상세 하게 알려주시고 도움 주셔서 많이 성장할 수 있었던 것 같습니다.😊

다음번에도 기회가 된다면 븨븨께 리뷰를 받을 수 있다면 좋겠습니다.

`Step02`에서 `Step03`의 많은 부분을 진행했었기에 `Step03`에서는 적용 되어지는 사항이 많이 없었지만 엉뚱한 부분에서 헤메다가 시간이 조금 많이 소요되었던 것 같습니다.

마지막 `Step03` 보내드립니다. 이번 PR도 잘 부탁드립니다.🙇🏻‍♀️

## 🤔 고민한 부분
### 1️⃣ `AppDelegate`를 통한 세로 모드로 제한
- 처음에 보여지는 `MainViewController`만 세로모드로 제한을 주고 출품작 리스트와 출품작 상세 설명은 가로, 세로 모두 적용되게 하기 위해서 어떻게 해야될지를 먼저 파악해보았습니다. 처음에는 단순하게  `MainViewController`에서 `shouldAutorotate`값을 설정해주면 되지 않을까 생각했었습니다.
`ViewController`에 모드를 적용한다고 세로 모드로 고정되지 않았습니다. 생각해보니 화면전환 모드를 `ViewController`에서 관리하는게 아닌것 같다는 생각이 들었고, 찾아보니 `AppDelegate`에서 앱의 전역적인 동작을 관리한다는 것을 알게 되어서 `supportedInterfaceOrientationsFor`라는 메소드를 활용해 해결했습니다.

**<처음 적용했던 코드>**
```swift
override var supportedInterfaceOrientations: UIInterfaceOrientationMask {
        return .landscapeLeft
}

 override var shouldAutorotate: Bool {
        return true
}

```

**<세로모드 적용 코드>**
```swift
class AppDelegate: UIResponder, UIApplicationDelegate {
    var shouldSupportAllOrientation = true

    func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
        if shouldSupportAllOrientation {
            return .all
        } else {
            return .portrait
        }
    }
}
    
```

### 2️⃣ 시뮬레이터
- 위에서 언급한대로 엉뚱한 곳에서 시간을 빼았겼다는 부분이 이 부분이었습니다. 미션에 나와있는 건 첫 화면에서 세로모드로 고정이기에 전 시뮬레이터 상도 첫 화면은 세로모드로 고정되어져야 된다고 생각을 해 시뮬레이터도 고정해주는 방법을 찾았습니다. 아무리 찾아도 해당 방법을 찾을 수가 없었고 한다 하더라도 세로로 고정하는 방법뿐이었는데 그렇게 되어버리면 두 번째, 세 번째 화면도 세로로만 볼 수 있게 되어버립니다.
아무리 찾아도 어떻게 해야될 지를 몰라서 헤메다가 솜에게 여쭤봤더니 시뮬레이터는 말 그대로 사용자들이 핸드폰의 방향을 이리저리 돌리는 부분인거라 시뮬레이터 부분까지는 세로로 고정하지 않아도 된다는 것을 깨닳았습니다.

### 3️⃣ `contentMode`
- `Step2`에서 븨븨가 알려주셨던 `contetMode`를 활용해 태극기 이미지의 크기를 설정해주는 방법을 찾아보았습니다. 이 부분에서도 `contentMode`가 오토레이아웃 부분일거라고 착각해서 한참을 헤메다가 `contentMode`는 이미지뷰 내에서 이미지를 어떻게 표시할지 결정하는 속성값이라는 것을 알게 되어 적용 시켜주었습니다.

--- 

<br>

## 🙇🏻‍♀️ 조언을 얻고 싶은 부분
### 1️⃣ 시뮬레이터 화면 전환
- 고민한 부분에서 엉뚱한 곳에서 비록 시간을 허비하긴 했지만 정말 시뮬레이터를 첫 화면에서는 세로 모드만 보여지게 하고 두 번째, 세 번째 화면에서는 가로, 세로 모드로 전환할 수 있게 하는 방법은 정말 없는 걸까요?? 제가 찾지 못한 방법이 왠지 있을 것 같은데 혹시 븨븨께서는 알고 계시는 지 궁금합니다.

### 2️⃣ 앱의 환경과 CS지식
- 이번에 코드베이스로 진행을 하면서 많은 부분을 배웠지만 또 그만큼 모르는 부분이 많다는 생각이 들었습니다. 특히나 앱이 어떻게 돌아가는지 구조를 조금 더 알아보고 싶다는 생각이 많이 들었습니다. 예를 들면 시뮬레이터가 어떠한 원리로 돌아가고 앱을 어떻게 실행을 시키게 되는 것인지, 또 어떤 명령어를 받으면 앱을 실행시키고 끄게 되는것인지 등 궁금한게 참 많아진 것 같습니다.
- 메모리나 `CPU`같은 `CS`적인 요소도 많이 알아봐야 될 것 같은데 제가 노베이스고 전공자가 아니다 보니 CS지식이 많이 부족한데 또 눈높이도 그만큼 낮아서 구글링으로 검색해서 나오는 자료들은 대부분 어려운 용어다보니 이해하는게 쉽지 않은 것 같습니다.🥹
- 혹시 이 부분을 제 수준에서 공부할 수 있는 자료나 책이나 사이트같은 곳이 있을까요?

### 3️⃣ 엉뚱한 방향으로 가는 문제점
- 이 부분은 개인적인 부분이긴 한데요.🥹
제가 미션 이해를 하는데 있어서 조금 엉뚱한 방향성으로 자주 흘러가는 것 같습니다. 생각해보니 이런 부분도 학습시간을 많이 잡아먹게 하는 요인인 것 같습니다. 어떻게 하면 미션내용의 핵심을 잘 짚고 이렇게 엉뚱한 방향으로 흘러가지 않을 수 있을까요? 기초 지식이 없어서 자꾸 엉뚱한 곳으로 생각이 튀는것일까요??🥹

2023-07-06 14:21 UTC, YebinKim requested changes
카렌 안녕하세요~

고민한 부분과 조언을 얻고 싶은 부분들을 읽고 답변을 드리기 전에, 이번 스텝의 요구사항이 적용되지 않은 부분이 보여서 빠른 작업이 필요할 거 같아 Request Changes 요청 먼저 드립니다.

```
- 모든 화면에 Dynamic Type을 적용합니다.
- 모든 텍스트가 잘리거나 줄임표(…) 처리가 되지 않도록 합니다.
```

위 두 가지 요구사항 및 p1 코멘트 확인 부탁드려요 🙌

2023-07-06 14:21 UTC, YebinKim commented on Expo1900/Expo1900/Controller/ExhibitDetailViewController.swift
> +
[661f221](https://github.com/yagom-academy/ios-exposition-universelle/pull/288/commits/661f221bc1d077144b486df409f9ba1f0224406f) 커밋에 코드 컨벤션 수정 내역이 모두 포함되어 있어서 나중에 다시 해당 커밋 로그를 찾아볼 때 커밋에서 중요하게 봐야 할 내용(세로모드 적용 코드)을 한 번에 찾기 불편해보여요 👀
코드 컨벤션 수정 커밋은 기능 작업 커밋과 분리해서 작성해보면 어떨까요?

2023-07-06 14:21 UTC, YebinKim commented on Expo1900/Expo1900/Controller/MainViewController.swift
> -        super.viewWillAppear(animated)
p1;

super 메서드의 호출을 제거한 이유가 무엇일까요?

2023-07-06 14:45 UTC, karenyang835 commented on Expo1900/Expo1900/Controller/ExhibitDetailViewController.swift
> +
네~ 앞으로 신경써서 커밋 해 보도록 하겠습니다.
조언해 주셔서 감사합니다 븨븨~!🙏🏻

2023-07-06 19:36 UTC, karenyang835 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> -        super.viewWillAppear(animated)
제가 이해하기로는 `viewWillAppear`에서는 `AppDelegate`의 `shouldSupportAllOrientation` 속성을 `false`로 설정하여 메인 화면에서는 세로 모드로 적용이 되어져야 하고, `navigationController`의 네비게이션 바를 숨기고, 메인 화면을 제외한 출품작 리스트 화면과 출품작 상세설명에서는 네비게이션 바를 다시 표시해야되고, `viewWillDisappear`에서는 `shouldSupportAllOrientation` 속성을 `true`로 설정하여 가로,세로 방향 전환을 허용하기 위해 부모클래스의 메서드 호출을 제거해 원하는 상황에 맞게 제어하기 위해서 삭제하였습니다.

2023-07-07 06:08 UTC, YebinKim requested changes
카렌 안녕하세요!
빠르게 Dynamic Types를 적용하느라 고생 많으셨습니다 👏👏

코멘트로 남겨주신 질문들 먼저 답변드려볼게요 🥳

---

### 1. 시뮬레이터 화면 전환

구현 방법이 더 있을 수는 있지만 여러 구현 방법들 중 정답은 없고 지금의 구현에서 어떤 문제점이 있는지를 인지할 수 없다면 개선하는 것 또한 방향을 잡을 수 없기 때문에 의미있게 진행하기는 어려울 것으로 생각됩니다 🤔
현재의 구현에서 어떤 점을 개선하고 싶으신가요?


### 2. 앱의 환경과 CS지식

시뮬레이터의 동작 원리에 대한 궁금증이 생기셨군요!
관련 WWDC 영상이 도움될 수 있을 거 같아요 ☺️ [Getting the Most Out of Simulator - WWDC19 - Videos - Apple Developer](https://developer.apple.com/wwdc19/418)

CS 지식은 워낙 범위가 방대해서 키워드를 하나씩 찾고 이해하기보다는 각 분야를 커리큘럼에 따라 전체적인 맥락을 이해해보는 것을 시작으로 공부를 시작해보는 것을 추천드리고 싶은데요.
궁금하신 부분이 메모리와 CPU의 물리적 내용(설계 방식, 성능 측정 등)이라면 `Computer Architecture` 의 학습이 도움되실 수 있고,
메모리와 CPU의 논리적 내용(컴퓨터 안에서의 역할, 동작 방식 등)이라면 `Operating System` 의 학습이 도움되실 수 있습니다!

학습 방법으로는 순서대로 학습할 수 있는 목차만 있다면 어떤 책이나 강의든 괜찮다고 생각되는데, 찾아보실 때 이론서보다는 입문자 학습용 책/강의 임을 확인하고 선정하시면 좋을 거 같습니다 😄
KOCW에서 오픈 강의를 찾아보실 수도 있구요 [KOCW - 전공](http://www.kocw.net/home/search/majorCourses.do#subject/0306)


### 3. 엉뚱한 방향으로 가는 문제점

엉뚱한 방향이 어떤 방향인지 잘 이해되지 않았지만..😅 미션 이해를 하는 데 어려움이 있다면 미션을 수행하기 위해 무엇을 해야 하는지 되질문을 해본다면 핵심을 짚는 데 도움될 수 있을 거 같아요!

---

현재 프로젝트 요구사항은 모두 충족되었지만, p1 코멘트가 있어서 Request Changes 로 다시 요청드렸습니다~
코멘트 내용 중 궁금한 점이 있으면 편히 질문 주세요 🙇🙌

2023-07-07 06:08 UTC, YebinKim commented on Expo1900/Expo1900/Controller/MainViewController.swift
> -        super.viewWillAppear(animated)
p1;

부모클래스의 호출이 있으면 카렌이 원하는 상황으로 제어하는 게 불가능해지는 걸까요?
[viewWillAppear(_:)](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621510-viewwillappear)의 문서 중 super 메서드의 호출을 어느 시점에든 필수로 해야 하는 것을 권장한다는 설명도 있어서 super 메서드의 호출을 제거해야 할지 다시 한 번 고민해보는 게 필요해보여요 🤔

<img width="836" alt="스크린샷 2023-07-07 오후 2 08 15" src="https://github.com/yagom-academy/ios-exposition-universelle/assets/38066039/e58dbe73-e08e-43ec-98dc-d879590709b7">

2023-07-07 06:08 UTC, YebinKim commented on Expo1900/Expo1900/View/ExpositionInformationStackView.swift
> +    }
p3;

메서드에서 수행하고자 하는 동작이 모두 같네요 👀
매개변수를 활용해 코드 중복을 줄여볼 수 있을까요?

2023-07-07 06:43 UTC, karenyang835 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> -        super.viewWillAppear(animated)
어느 시점에서는 필수로 해야된다는 부분을 제가 놓친것 같습니다. 그리고 제거를 하였을 경우에도 크게 문제 되는 사항은 보이지 않아 삭제를 했던 부분이었는데 다시 추가해두었습니다.
그리고 이 부분에 대해서는 조금 더 공부해보고 고민해도록 하겠습니다.

조언해주셔서 감사합니다. 😊
만약 븨븨께서 이렇게 조언해주시지 않았다면 잘못 인식한 상황을 인지하지 못하고 추후에 문제가 발생되어졌을 때 어려움을 겪었을 것 같습니다.🤦🏻‍♀️

2023-07-07 06:44 UTC, karenyang835 commented on Expo1900/Expo1900/View/ExpositionInformationStackView.swift
> +    }
나름대로 코드 정리를 한다고 했는데 이 부분을 찾지를 못했었네요.🥹

븨븨께서 조언해주시고 찾아주셔서 1개의 메서드로 통합해서 수정하였습니다.☺️

2023-07-07 06:53 UTC, karenyang835 commented
> 3. 엉뚱한 방향으로 가는 문제점
엉뚱한 방향이 어떤 방향인지 잘 이해되지 않았지만..😅 미션 이해를 하는 데 어려움이 있다면 미션을 수행하기 위해 무엇을 해야 하는지 되질문을 해본다면 핵심을 짚는 데 도움될 수 있을 거 같아요!

- 제가 설명이 부족했던 것 같습니다.😅 여기서 조언을 구하고자 했던 엉뚱한 방향이라는 것은 미션에서 요구하는 방향의 핵심을 잘못찾고 엄한 부분에 꽂혀서 길을 헤메는 상황을 말씀드렸습니다.

- 예를 들어서 세로 모드로 변경하는 부분에서 앱에서 보여지는 부분만 세로모드로 고정하면 되는데 시뮬레이터까지 고정해야된다고 생각해서 세로모드 적용하는 부분보다 시뮬레이터 고정시켜야 되는 부분에서 시간을 더 허비했던 것 같습니다. 시뮬레이터는 한 방향만 고정이 되는 것 같아서 어떻게 해야되는지 계속 검색하고 알아보다가 안되어서 결국에는 주변에 여쭤보고 시뮬레이터 환경이라는 것은 사용자가 핸드폰을 돌리는 부분과 관련이 된 것인데 앱상에서 세로모드로 적용시킨다고 해서 사용자가 핸드폰을 안돌리는 것은 아닌데 시뮬레이션이 그런것을 나타낸다고 연결을 전혀 하지 못해서 발생하는 부분인 것 같습니다.

2023-07-07 07:28 UTC, YebinKim approved these changes
카렌 안녕하세요~
수정해주신 내용 확인했습니다!
`엉뚱한 방향으로 가는 문제점` 에 대한 고민이 어떤 내용인지도 이해됐어요 ㅎㅎ

저는 이런 고민을 하는 게 문제점이고 고쳐야 할 부분은 아니라고 생각합니다.
카렌이 고민을 한 덕분에 시뮬레이터라는 프로그램에 대해 이번 기회를 통해 새로운 관점으로 이해할 수 있게 되었고 다시는 잊지 않게 될 거 같아요 😆

제한된 시간 안에 프로젝트를 진행해야 하다보니 고민이 너무 길어지거나 관련 자료를 찾기 어렵다면 질문을 해보는 게 그나마 시간을 절약한다면 절약할 수 있는 방법일 거 같아요 😄 반복해서 질문의 장점을 언급드리고 있어서 주변에 질문하기 쉬운 환경이 갖춰져있을 때 적극적으로 활용해보셨으면 좋겠다는 생각이 드네요 🔥💪

이번 스텝은 여기서 마무리하고 머지 진행하겠습니다.
2주간 정말 고생 많으셨어요!! 만국박람회 프로젝트 완주 축하드립니다 🏃💯

2023-07-07 07:28 UTC, merged