만국박람회 [STEP2] Uemu, Morgan
yagom-academy/ios-exposition-universelle pull request #301
Opened 2023-11-06 08:47 UTC by devjoon

@havilog 
안녕하세요 havi 😃😃
Step2 PR 보내드립니다.
이번에도 잘 부탁드리겠습니다! 🙇‍♂️🙇‍♀️🙇

### 고민되었던 점 & 조언을 얻고싶은 점
- Error상황에서 Alert를 발생시키는 방식이 올바른지 궁금합니다
처음에는 generateAlert()(현 ErrorAlert.swift파일의)를 각 뷰 컨트롤러에 넣어줬는데 generateAlert()를 한곳에서만 만들어서 재사용이 가능하다 생각하게 되어
따로 파일(ErrorAlert.swift)을 만들어 준뒤 present를 실행해주기 위해서 실행되는곳의 뷰 컨트롤러를 매개변수로 넘겨주는 방식으로 구현하였습니다.해당 방식이 올바를까요?

- JSONData decoder를 재사용하여 처리하기 위한 방법이 궁금합니다.
decodeJSONData()(현 ExpoInfoViewController.swift , EntryItemViewController.swift 파일의)메서드가 중복으로 사용되고 있는 상황에서 파일을 따로 생성해서 중복을 방지하고자 시도 해봤지만 JSON데이터를 담는 전역변수 expoInfo를 다른 파일에서 사용할 수가 없어서 decodeJSONData 메서드의 중복을 어떻게 묶을 수 있을지 조언을 얻고 싶습니다.

- 휴먼 에러를 방지하기 위한 reuseidentifier를 사용하지 않고 Namespace를 지정해서 사용해 보았는데 올바른지 궁금합니다.

그외에 더 지적해주실 부분이 있다면 편하게 남겨주시면
감사한 마음으로 열심히 배워보겠습니다
잘 부탁드립니다.

### 실행화면
정상 실행화면
![firstTest](https://github.com/yagom-academy/ios-exposition-universelle/assets/101351216/858b185c-7e62-4f0c-9a8c-abe0da1b2aae)

DescriptionDetailViewController에 imageName 이 전달실패했을 경우 화면
![secondTest](https://github.com/yagom-academy/ios-exposition-universelle/assets/101351216/e170d040-b9a7-462e-aab7-dca78628acb9)

2023-11-06 11:07 UTC, havilog requested changes
수고하셨어요 모에뭉

2023-11-06 11:07 UTC, havilog commented on Expo1900/Expo1900/Sources/Error/ErrorAlert.swift
> +}
재사용성을 고려해서 설계하면 좋을 것 같아요.
에러의 타이틀이나 메세지, 버튼의 갯수과 버튼 타이틀 등을 정의할 수 있는 struct가 존재하고,
그 struct(Configuration)을 파라미터로 받아서 띄울 수 있는 인터페이스를 뚫어보는 방식도
고려해볼 만 할 것 같아요

2023-11-06 11:07 UTC, havilog commented on Expo1900/Expo1900/Sources/Model/IdentifierNameSpace.swift
> +}
> 휴먼 에러를 방지하기 위한 reuseidentifier를 사용하지 않고 Namespace를 지정해서 사용해 보았는데 올바른지 궁금합니다.

코드에 정답은 없어서 '올바른 코드'란 워딩은 조금 애매하긴 한데요,
이렇게 작성했을 때 프로토콜을 사용하는 것에 비해 장점이 어떤게 있다고 생각해서 요렇게 구현하셨는지 궁금해요

2023-11-06 11:07 UTC, havilog commented on Expo1900/Expo1900/Sources/View/DescriptionDetailViewController/DescriptionDetailViewController.swift
> +}
DescriptionDetailViewController을 initialize하는 시점에 안넣어주고 dynamic하게 inject해주는 이유가 무엇일까요?

2023-11-06 11:07 UTC, havilog commented on Expo1900/Expo1900/Sources/View/EntryItemViewController/EntryItemViewController.swift
> +        let thirdViewController = UIStoryboard(name: "DescriptionDetail", bundle: .main)
UIStoryboard이름도 마찬가지로 String literal이 아니도록 관리해주세요

2023-11-06 11:07 UTC, havilog commented on Expo1900/Expo1900/Sources/View/EntryItemViewController/EntryItemViewController.swift
> +    private var entryItems: [Exposition.EntryItem]?
entryItems는 반드시 optional이어야 한가요?
초기값으로 빈 배열을 가지고 있는 경우도 고려해보셨는지 궁금해요

2023-11-06 11:07 UTC, havilog commented on Expo1900/Expo1900/Sources/View/EntryItemViewController/EntryItemViewController.swift
> +        guard let entryItem = entryItems?[indexPath.row] else {
저번에 말슴드렸던 safe subscript도 적용해주세요

2023-11-06 11:07 UTC, havilog commented on Expo1900/Expo1900/Sources/View/ExpoInfoViewController/ExpoInfoViewController.swift
> +    }
같은 로직을 처리하는 방법을 함수로 처리할 수도 있지만,
객체로 만들어서 처리할 수도 있는데요,
universelle decoder라는 아이를 만들어서 처리하는 방법은 고민해보셨을까요?

2023-11-06 11:07 UTC, havilog commented on Expo1900/Expo1900/Sources/Error/ErrorReason.swift
> +}
일반적으로 ErrorReason을 String으로 정의하기 보다는
Error를 정의해주고, 해당 에러에 대해 computed property로 에러 이유를 명시해주는게 나을거 같아요

2023-11-08 06:44 UTC, devjoon commented on Expo1900/Expo1900/Sources/Error/ErrorAlert.swift
> +}
Struct 형태의 AlertConfiguration을 만들어주었고 Configuration을 파라미터로 받도록 하였으며
ShowAlert의 presentAlert 메서드를 static으로 생성하여 매개변수로 AlertConfiguration의 인스턴스를 넣어
Alert를 생성,발생시키는 형태로 변경하였습니다.

2023-11-08 06:56 UTC, ue-mu commented on Expo1900/Expo1900/Sources/Error/ErrorReason.swift
> +}
가독성 향상 및 에러 유형을 명확하게 정의하고 통일성 있게 작성해 보았습니다

2023-11-08 08:51 UTC, ue-mu commented on Expo1900/Expo1900/Sources/Model/IdentifierNameSpace.swift
> +}
프로토콜의 공부가 부족해서 enum 타입으로 namespace를 작성했는데 프로토콜의 공부를 마치고 프로토콜과 프로토콜 extension을
이용하여 reuseidentifier를 사용하여 휴먼에러를 방지 하였습니다.

2023-11-08 10:19 UTC, devjoon commented on Expo1900/Expo1900/Sources/View/EntryItemViewController/EntryItemViewController.swift
> +        let thirdViewController = UIStoryboard(name: "DescriptionDetail", bundle: .main)
StoryBoardName 파일을 만들어서 관리하였습니다.

2023-11-08 10:33 UTC, devjoon commented on Expo1900/Expo1900/Sources/View/EntryItemViewController/EntryItemViewController.swift
> +        guard let entryItem = entryItems?[indexPath.row] else {
Collection 을 확장하여 safe subscript를 구현하고 해당 부분에서 safe를 사용하여 잘못된 인덱스의 접근을 차단하였습니다.

2023-11-08 10:41 UTC, ue-mu commented on Expo1900/Expo1900/Sources/View/EntryItemViewController/EntryItemViewController.swift
> +    private var entryItems: [Exposition.EntryItem]?
팀원과 옵셔널과 빈 배열을 두고 무엇을 사용할지 고민해본 결과 값이 없을 수 도 있는 상황을 다루기 위해서 옵셔널을 채택하였습니다.
초기값이 없는 옵셔널을 채택한 방법과 초기값이 존재하는 빈 배열에 대해서 하비는 어떻게 생각하시는지 궁금합니다.

2023-11-08 11:33 UTC, devjoon commented on Expo1900/Expo1900/Sources/View/ExpoInfoViewController/ExpoInfoViewController.swift
> +    }
UniverselleDecoder 를 작성하여 Asset의 이름을 전달하여 디코딩 한 후 리턴값으로 전달하여 재사용성을 높혔습니다.

2023-11-08 11:35 UTC, ue-mu commented on Expo1900/Expo1900/Sources/View/DescriptionDetailViewController/DescriptionDetailViewController.swift
> +}
initializer의 이해가 아직 부족해서 초기화하는 시점에 넣어주지 않고 dynamic하게 주입하는 방식을 사용하였습니다.
이 부분에 대해서 도움을 받을 수 있을까요?

2023-11-08 12:51 UTC, havilog commented on Expo1900/Expo1900/Sources/Error/ErrorAlert.swift
> +}
수정 커밋 메세지도 같이 태그해주시면 확인이 더 쉬울거 같아요~!

2023-11-08 13:12 UTC, havilog commented
모바일로.. 어케 남기지..

2023-11-08 13:58 UTC, havilog approved these changes

2023-11-08 13:58 UTC, havilog commented on Expo1900/Expo1900/Sources/Error/AlertMessage.swift
> +    case Confirm
요 아이들은 왜 대문자인가요 ㅋㅋ

2023-11-08 13:58 UTC, havilog commented on Expo1900/Expo1900/Sources/Model/ShowAlert.swift
> +struct ShowAlert {
ShowAlert객체는 반드시 필요할까요?
ViewController의 extension으로 하는것과는 어떤 차이점이 있는지 궁금해요
(바꾸라는게 아니라 어떤 생각으로 만드셨는지가 궁금합니다)

2023-11-08 13:58 UTC, havilog commented on Expo1900/Expo1900/Sources/Model/AlertConfiguration.swift
> +    var actionTitle: String
변경될 일이 있어서 variable로 선언하신걸까요?

2023-11-08 13:58 UTC, havilog commented on Expo1900/Expo1900/Sources/Model/StoryBoardName.swift
> +}
스토리보드도 reuseidentifier를 만들 수 있지 않을까요?
화면이 많아지면 100개의 스토리보드 이름을 enum으로 관리하기는 힘들거 같아요.

2023-11-08 13:58 UTC, havilog commented on Expo1900/Expo1900/Sources/Model/UniverselleDecoder.swift
> +struct UniverselleDecoder<T: Decodable> {
객체 자체가 제네릭이 되기보다는, 함수가 제네릭이 되는게 확장성이 더 좋지 않을까하는 생각이 들어요.

2023-11-08 13:58 UTC, havilog commented on Expo1900/Expo1900/Sources/Model/UniverselleDecoder.swift
> +    static func decodeAssetData(assetName: String) throws -> T {
decoder도 파라미터로 받으면 좀 더 확장성있지 않을까요?

2023-11-08 13:58 UTC, havilog commented on Expo1900/Expo1900/Sources/View/DescriptionDetailViewController/DescriptionDetailViewController.swift
> +}
정확히 어느 부분이 이해가 안되셔서 어떤 도움을 바라는지가 명확하지 않은거 같은데요,
뷰 컨트롤러의 라이프 사이클을 먼저 공부하시면 좋을 거 같아요.
스토리보드에서는 뷰컨트롤러를 어느 시점에 Initialize하는지를 확인한 뒤에,
해당 시점에 parameter로 원하는 값을 주입해주는게 좋아보여요
이렇게 inject data라는 값을 넣으면 변경되면 안되는 값이, 외부에서 잘못 주입되어 변경될 수도 있을거 같아요

2023-11-08 13:58 UTC, havilog commented on Expo1900/Expo1900/Sources/View/EntryItemViewController/EntryItemViewController.swift
> +    private var entryItems: [Exposition.EntryItem]?
요거는 정답이 있지는 않을거 같구요,
optional이라는 시그니쳐는 있을수도 있고, 없을 수도 있다 라는 뜻이 있고,
빈 배열을 넣을 경우, 초기값은 비어있지만, 유저의 동작에 따라 배열에 값이 추가되거나, 지워질 수도 있다.
라는 의미를 지니고 있을거 같아요.

따라서 모에무가 어떤 의도로 해당 변수를 선언했고 그 목적에 맞게 사용하셨는지만 명확해지면 좋을 것 같습니다.

2023-11-09 05:30 UTC, devjoon commented on Expo1900/Expo1900/Sources/Error/ErrorAlert.swift
> +}
https://github.com/yagom-academy/ios-exposition-universelle/pull/301/commits/0e8c0583702bbed712830fa30a23e85c57875439 해당 커밋 메시지 태그입니다!

2023-11-09 06:14 UTC, devjoon commented on Expo1900/Expo1900/Sources/View/DescriptionDetailViewController/DescriptionDetailViewController.swift
> +}
해당 부분을 뷰 컨트롤러가 만들어지는 시점에서 초기화 할 수 있도록 init을 이용하여 구현을 하였습니다.

2023-11-09 06:18 UTC, devjoon commented on Expo1900/Expo1900/Sources/Error/AlertMessage.swift
> +    case Confirm
😱헉! 해당부분 소문자로 변경 하였습니다.

2023-11-09 06:24 UTC, devjoon commented on Expo1900/Expo1900/Sources/Model/AlertConfiguration.swift
> +    var actionTitle: String
🙀 확인결과 인스턴스를 생성하고 사용하는 부분이여서 변경이 될 필요가 없는것으로 확인 하였습니다
해당부분 let으로 변경하였습니다.

2023-11-09 07:28 UTC, ue-mu commented on Expo1900/Expo1900/Sources/Model/UniverselleDecoder.swift
> +    static func decodeAssetData(assetName: String) throws -> T {
decoder를 파라미터로 받아서 나중에 새로운 디코더를 받을 때 기존의 코드를 변경하거나 추가하지 않고도 새로운 디코더를 채택할 수 있게 수정하였습니다.

2023-11-09 07:28 UTC, ue-mu commented on Expo1900/Expo1900/Sources/Model/UniverselleDecoder.swift
> +struct UniverselleDecoder<T: Decodable> {
제네릭을 객체가 아닌 메서드에 사용하여 객체의 다형성을 높일 수 있게 수정하였습니다.

2023-11-09 08:31 UTC, devjoon commented on Expo1900/Expo1900/Sources/Model/StoryBoardName.swift
> +}
스토리보드도 reuseidentifier 를 만드려고 시도해봤는데 도저히 방법을 찾을수 없어서 만들지 못하게 되었습니다.

저희가 `let thirdStoryboard: UIStoryboard? = UIStoryboard(name: StoryBoardName.DescriptionDetail.description, bundle: .main)` 이 방식으로 thirdStoryboard를 만들어준 이유가 DescriptionDetail 스토리보드에 접근할방법이 없어서 만들어 준 것인데 해당 스토리보드를 reuseIdentifier로 접근하려면 해당 스토리 보드에서 프로토콜을 채택해줘야하는데 그 방법을 모르겠습니다. 

일단 해결한 방법으로는 새로운 reuseIdentifier를 만들어주고 해당하는 뷰컨트롤러를 받아와서 component로 ViewController 라는 스트링 부분만 제외하여 리턴해주는 형태로 구현하였습니다. 다른 방법이 있을까요?

2023-11-09 08:33 UTC, devjoon commented on Expo1900/Expo1900/Sources/Model/ShowAlert.swift
> +struct ShowAlert {
사실 둘의 차이점은 크지 않다고 생각합니다. 이렇게 만든 이유는 코드를 조금이라도 더 분리하기 위해서 작성하였습니다.

2023-11-09 08:50 UTC, merged