만국박람회 [STEP 2] 햄찌, 가마 (작성중)
yagom-academy/ios-exposition-universelle pull request #309
Opened 2024-03-12 15:44 UTC by forseaest

안녕하세요!
STEP 2 PR 드립니다. 잘 부탁드립니다~!

# 고민했던 점
## 

# 조언을 얻고 싶은 점
1. item이 nil일 경우에 대한 처리가 현재 충분한지 궁금합니다. 옵셔널 바인딩 외에 더 나은 방법이 있을까요?
2. 이미지 로딩 시, 파일이 클 경우 UI가 느려질 수도 있을 거 같아요. 이것을 개선할 수 있는 방법이 있는지도 궁금합니다.

2024-03-14 12:54 UTC, uuu1101 requested changes
안녕하세요 햄찌 가마 ! 
STEP2 잘 진행해주셨네요 ! 👍🏻

앱 개발자로서 저희는 요구사항(디자이너 또는 기획자)에 대해서 그들이 원하는 것들을 그대로 구현하는 역할을 하고 있는데요!

메서드 역할 분리도 잘해주셨고 요구사항에 잘 맞추어서 작성해주신것 같아요 ! 

다만 요구사항에는 방문객숫자가 3자리마다 `,`가 들어있는 형태에요. 이 부분도 추가적으로 구현해주실수 있을까요?! 만약 해당 부분구현에 어려움이 있다면 언제든 알려주세요.

<img width="221" alt="스크린샷 2024-03-14 오후 9 19 46" src="https://github.com/yagom-academy/ios-exposition-universelle/assets/49808034/9749133f-068a-4bd5-becc-eff9c174239b">

## 아쉬운 점에 대한 부분
- 양쪽에 이미지를 배치하는 방법을 찾지 못하셨다고 하셨네요.  구현하는 방법은 여러가지가 있을 것 같아요. 
1. StackView를 활용하거나 (StackView안에 이미지뷰 + UIButton(Text만) + 이미지뷰) 
2. 이미지뷰 + UILabel + 이미지뷰를 UIView에 넣고 해당 UIView를 UIButton(이미지,text모두 없는)으로 감싸주는 방법 (UIView는 optional하게 선택사항입니다) 

말씀하신것처럼 StackView로 묶고 작업해주시되, TextButton에 IBAction 을 연결하면 될 것같아요 ! 

1번으로 구현해보았습니다(용량제한이 있어서 영상이 짧아요)

https://github.com/yagom-academy/ios-exposition-universelle/assets/49808034/e113ffc4-9320-4a13-a72b-62d337d53d62



## 궁금한점
1. 음 nil 처리는 안전하게 옵셔널 바인딩 하는게 좋다고 생각합니다 ! 
2. 이미지 로딩 시 서버에서 이미지를 받아올 경우 캐싱을 해서 보여주는 방법이 있을것 같구요. 로컬에 이미지를 저장해두는(앱 내부에 두는 방식)은 이미 앱에서 가지고 있기 때문에 앱용량이 커질 것 같아요.
3. 네이밍에 관한 부분은 코멘트 남겨두었습니다.
4. if let관련해서 코멘트를 남겨두었는데요, 음 guard let과 if let의 차이점을 알아보시면 좋을 것 같습니다. 
한 가지 예시를 들자면, guard let 같은경우에는 else문을 통해서 return 하게 되는데, 이 guard문과 상관없이 실행되어야하는 로직이 있다면 어떻게 될까요..!? if let 구문은 어떻게 될까요?!

2024-03-14 12:54 UTC, uuu1101 commented on Expo1900/Expo1900/Model/Items.swift
> +        case imageUrl = "image_name"
👍🏻👍

2024-03-14 12:54 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/DetailViewController.swift
> +    */
불필요한 주석은 삭제하셔도 좋을 것 같아요 !

2024-03-14 12:54 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/TableViewCell.swift
> +    }
해당 메서드는 어떤 역할을 하는 메서드 일까요?!

2024-03-14 12:54 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/TableViewController.swift
> +    }
해당 메서드들도 어떤때에 필요한 메서드 인지 알아보면 좋을 것 같아요 😀

2024-03-14 12:54 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/ViewController.swift
> +    @IBOutlet weak var titleLabel: UILabel!
IBOutlet과 weak 에 대해서도 알아보면 좋을것 같습니다 !

2024-03-14 12:54 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/ViewController.swift
> +    @IBOutlet weak var imageView: UIImageView!
왜 @IBOutlet 로 선언한 프로퍼티는 강제언래핑을 사용할까요?!

2024-03-14 12:54 UTC, uuu1101 commented on Expo1900/Expo1900/Model/Item.swift
> +struct Item: Codable {
👍
Codable에 대해서 설명해주실수 있을까요?

2024-03-14 12:54 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/TableViewController.swift
> +        itemsTableView.estimatedRowHeight = 100
estimatedRowHeight는 어떤 역할을 하나요?!

2024-03-14 12:54 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/TableViewController.swift
> +    var list: [Item] = []
그냥 `list`라고 하면 다른곳에서 사용할때 `어떤것들의 list`인지 알려면 해당 타입을 보아야 할것 같아요.
`Items` 또는 `ItemList` 이라는 이름 어떠신가요?

2024-03-14 12:54 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/TableViewController.swift
> +    }
```suggestion
  override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
    guard segue.identifier == "listToDetail",
          let cell = sender as? UITableViewCell,
          let indexPath = itemsTableView.indexPath(for: cell),
          let vc = segue.destination as? DetailViewController else {
              return
          }
    
    let item = list[indexPath.row]
    vc.item = item
    vc.navigationItem.title = item.name
}
```

이렇게 작성하면 더 깔끔 할것 같아요 !
if 의 depth가 너무 깊어지면 (if문의 중첩) 가독성이 좋아지지 않아요.

2024-03-14 12:54 UTC, uuu1101 commented on Expo1900/Expo1900/Controller/TableViewController.swift
> +        cell.accessoryType = .disclosureIndicator
`override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell` 메서드는 어떤 역할을 할까요? 

cell의 프로퍼티에 직접 접근하셨네요. 이렇게 접근하면 어떤 장단점이 있을까요?!

나아가, 해당 부분을 Cell에게 Item을 넘겨주어 TableViewCell이 직접 하도록 해보는건 어떨까요?

2024-03-15 11:48 UTC, forseaest commented on Expo1900/Expo1900/Model/Item.swift
> +struct Item: Codable {
Codable 프로토콜은 Decodable+Encodable 프로토콜의 조합인 프로토콜로, 사용자 정의 데이터 타입을 다른 형식으로 쉽게 인코딩하고 디코딩할 수 있습니다. Codable을 준수하는 타입의 데이터를 JSON 문자열로 변환하게 하는 JSONEncoder, JSON 문자열을 타입의 인스턴스로 변환하게 하는 JSONDecoder 클래스가 포함된 Foundation 프레임워크와 함께 자주 활용됩니다.

2024-03-15 13:28 UTC, forseaest commented on Expo1900/Expo1900/Controller/TableViewController.swift
> +        itemsTableView.estimatedRowHeight = 100
estimatedRowHeight는 개발자가 지정하는 row의 예상 높이값으로, 테이블뷰의 테이블뷰의 각 row마다 다른 높이들을 적용시키고 싶을 때 사용하는 프로퍼티로, rowHeight와 함께 사용됩니다! rowHeight에 UITableViewAutomaticDimension 값을 할당하여, 셀 안의 콘텐츠에 맞게 셀의 높이를 자동으로 계산해서 반환해줍니다. estimatedRowHeight에는 셀 높이의 예상값을 지정해주는데, 이는 테이블뷰의 row가 동적인 높이를 가질 때 테이블뷰가 reload될 때마다 row별 다른 모든 높이들을 계산하는 데에 불필요한 성능과 비용을 지출하지 않게 도와줍니다.

2024-03-15 13:48 UTC, kkomgi commented on Expo1900/Expo1900/Controller/TableViewController.swift
> +        cell.accessoryType = .disclosureIndicator
### cell의 프로퍼티에 직접 접근하셨네요. 이렇게 접근하면 어떤 장단점이 있을까요?!
- 장점: 직접 접근 방식은 코드를 간결하게 만들어 빠르게 이해하고 수정이 가능하게 합니다.
- 단점: 셀의 내부 구현을 외부에서 직접 접근하면 캡슐화에 위반되어 셀의 내부 구현 변경 시 외부 코드도 영향을 받을 수 있습니다. 셀 내부 구조를 변경할 때 관련된 모든 코드를 찾아 수정해야 하므로 불편함이 있을 수 있습니다.

### 해당 부분을 Cell에게 Item을 넘겨주어 TableViewCell이 직접 하도록 해보는건 어떨까요?
아래와 같이 변경하였습니다 :)

```swift
class TableViewCell: UITableViewCell {
    ...
    func configure(with item: Item) {
        nameLabel.text = "\(item.name)"
        shortDescriptionLabel.text = "\(item.summary)"
        itemImageView.image = UIImage(named: "\(item.imageUrl)")
        accessoryType = .disclosureIndicator
    }
}
```

2024-03-15 13:48 UTC, forseaest commented on Expo1900/Expo1900/Controller/TableViewCell.swift
> +    }
awakeFromNib()은 스토리보드에서 작업한 테이블뷰의 셀이 로드될 때, 해당 셀의 인스턴스에 대해 호출되는 메소드로 셀의 추가적인 초기 설정을 위해 사용되므로, 셀의 UI를 변경하는 내용의 코드를 이 메소드 안에 작성합니다. 현재 셀을 코드가 아닌 인터페이스 빌더를 통해 구현하였으므로 셀의 생성자가 아닌 이 메소드를 통해서 셀의 초기 설정을 하게 됩니다!

2024-03-15 13:57 UTC, kkomgi commented on Expo1900/Expo1900/Controller/TableViewController.swift
> +    }
맞네요! if의 중첩을 줄이면 코드의 가독성이 더 높아지네요! 수정하였습니다 :)

2024-03-15 14:00 UTC, kkomgi commented on Expo1900/Expo1900/Controller/TableViewController.swift
> +    var list: [Item] = []
추천해주신 ItemList 로 이름을 변경하였습니다.

2024-03-15 14:02 UTC, forseaest commented on Expo1900/Expo1900/Controller/TableViewController.swift
> +    }
- numberOfSections()는 테이블뷰에 표시될 세션의 수를 리턴시키는 메소드로, 세션의 수를 정의할 때 필요합니다.
- tableView(numberOfRowsInSection:)는 세션 별 row 수를 리턴시키는 메소드로, 세션 안의 row 개수를 지정하고 싶을 때 사용합니다.

2024-03-15 14:06 UTC, kkomgi commented on Expo1900/Expo1900/Controller/ViewController.swift
> +    @IBOutlet weak var imageView: UIImageView!
@IBOutlet으로 선언된 프로퍼티는 Interface Builder를 통해 UI 컴포넌트와 연결되는데, 이 과정에서 강제 언래핑(!)을 사용하는 주된 이유는 연결된 UI 요소의 접근이 안정적이라고 가정하기 때문입니다. 또한 UI 컴포넌트는 존재한다는 가정 하에 코드가 작성됩니다. 이 요소들을 매번 옵셔널로 다루게 되면, 코드 내에서 반복적으로 옵셔널 체크를 수행해야 하며, 이는 코드의 가독성을 떨어뜨리고 작성하기 번거롭게 만들기 때문에 강제언래핑을 사용합니다.

2024-03-15 17:28 UTC, forseaest commented on Expo1900/Expo1900/Controller/ViewController.swift
> +    @IBOutlet weak var titleLabel: UILabel!
IBOutlet은 스토리보드에서 작업한 UI 객체를 코드에 연결하기 위해 사용하는 키워드로, IBOutlet가 붙은 변수는 Interface Builder(IB)와 연결된 것을 의미하며 기본적으로 weak로 약한 참조로 선언합니다.
메모리가 부족한 상황에 뷰 컨트롤러는 `didReceiveMemoryWarning()`를 호출하여 내부의 뷰들을 nil 처리하여 메모리에서 해제시킵니다. 이때, 뷰가 강한 참조를 하는 뷰 객체들은 뷰에게 참조된만큼 Retain Count도 줄어들지만, 여전히 뷰 컨트롤러가 뷰 객체들을 강한 참조를 하고 있기에, 뷰 객체들의 RC는 0으로 돌아가지 못하고 메모리에서 해제되지 못합니다. 즉, 메모리 부족을 관리하기 위해 뷰들을 메모리에서 해제시켰지만 뷰 객체들은 여전히 메모리에 남아있기 때문에 메모리 누수의 발생 가능성이 존재합니다. 따라서 IBOutlet은 메모리 누수를 방지하기 위해 weak로 선언하게 됩니다!

2024-03-15 17:36 UTC, forseaest commented on Expo1900/Expo1900/Controller/DetailViewController.swift
> +    */
삭제했습니다!

2024-03-16 04:24 UTC, uuu1101 commented
해당 PR을 드래프트로 돌려두신 이유가 있으실까요..?! @forseaest @kkomgi

2024-03-16 10:04 UTC, forseaest commented
> 해당 PR을 드래프트로 돌려두신 이유가 있으실까요..?! @forseaest @kkomgi

드래프트로 해놓으면 답변을 드릴 때마다 가는 알람을 방지할 수 있다고 들어서 하게 되었습니다! 아직 남은 작업 사항들이 있어서 드래프트 그대로 유지 중인데 혹시 답변을 달 때마다 알람이 계속 갔을까요...?🥺

2024-03-17 12:03 UTC, forseaest commented
> 안녕하세요! @uuu1101 STEP 2 PR 드립니다. 잘 부탁드립니다! 🫡 감사합니다~!
> 
> ## 고민했던 점
> * step1에서는 json 파일이 있다는 것을 인지하지 못하고 스크린샷만 확인하고 타입을 정의했습니다. step2에서는 json 파일에 맞게 박람회와 출품작 각각을 Exposition, Item으로 타입을 생성하고 CodingKeys를 사용하여 프로퍼티도 적절하게 구현해주었습니다.
> * 화면을 전환하는 방식에 트리거 세그웨이를 적용했습니다. 첫번째 박람회 화면에서 두번째 출품작 목록 화면을 가기 위해서는 버튼을, 두번째 화면에서 세번째 출품작 세부정보 화면을 가기 위해서는 셀을 눌러야 하므로 트리거 세그웨이 방식이 적절하다고 생각했습니다. 또한 이 과정에서 데이터를 전달하기 위해 prepare 함수를 사용하게 되었습니다. 현재 셀로 indexPath를 찾고 item 배열에서 indexPath.row와 대응되는 item 인스턴스를 찾아서 다음 화면으로 넘겨주는 코드로 데이터를 전달할 수 있게 하였습니다.
> * UIScrollView를 구현하는 것에서 어려움이 많았습니다. 스크롤이 완전히 아래까지 내려가지 않고 화면이 멈추는 현상이 계속해서 발생하였고, 이를 해결하기 위해서는 스크롤뷰 안에 구현한 뷰들의 오토레이아웃을 정확히 지정해줘야 한다는 것을 알게 되었습니다. 따라서 오토레이아웃은 step3의 주제지만 현재 일부 적용하여 진행하게 되었습니다. 스크롤뷰 안 최상단 요소와 최하단 요소의 레이아웃 기준을 Frame Layout Guide으로 잡고 문제를 해결했습니다.
> 
> ## 아쉬운 점
> * 🇰🇷 한국의 출품작 바로가기 🇰🇷 버튼을 구현하려고 했지만 이미지를 양쪽에 배치하는 방법을 찾지 못해 구현하지 못했습니다. 텍스트말고도 이미지를 클릭할 때에도 다음 화면으로 전환할 수 있는 방법에 대해 다음과 같이 시도해보았습니다.
>   
>   * 처음에는 UIButton 하나를 만들어 버튼 내부의 UIImageView에 태극기 이미지를 넣어서 구현하려고 했습니다! 그러나 이미지의 크기를 인터페이스 빌더로는 변경할 수 없는 것을 알게 되었고, 버튼에 이미지 1개만 가능하기에 제하게 되었습니다.
>   * 가운데 한국의 출품작 바로가기를 UILabel로, 양 옆의 태극기 이미지는 UIImageView로 구현하고 StackView로 묶었습니다. 그러나 이렇게 하면 아울렛 변수는 생성할 수 있으나 아울렛 함수는 작성하지 못합니다. 따라서 이 또한 제하게 되었습니다.
>   * 이외에 생각나는 방법이 없어 양쪽의 태극기 이미지를 제외하고 텍스트로만 이루어진 버튼으로 구현하게 되었습니다. 아니면 버튼의 텍스트 안에 태극기 이모지를 넣는 방법도 생각하게 되는데, 이는 스크린샷 상으로 이미지가 텍스트보다 더 크기 때문에 맞지 않는 방법인 것 같아서 고민입니다..
> 
> ## 궁금한 점
> 1. item이 nil일 경우에 대한 처리가 현재 충분한지 궁금합니다. 옵셔널 바인딩 외에 더 나은 방법이 있을까요?
> 2. 이미지 로딩 시, 파일이 클 경우 UI가 느려질 수도 있을 거 같아요. 이것을 개선할 수 있는 방법이 있는지도 궁금합니다.
> 3. 변수들의 네이밍이 적절하게 이루어졌는지 궁금합니다!
> 4. 뷰 컨트롤러나 셀을 코드 상에서 사용하려고 할 때 타입 캐스팅을 하게 되는데, 이 과정에서 if let을 사용할지, guard let을 사용할지 고민이 많습니다. 어느 쪽을 자주 사용하시는지 궁금합니다! 또한 타입 캐스팅과 옵셔널 바인딩이 실패하는 경우에도 에러를 따로 구현하여 에러 처리를 해줘야 하는지 궁금합니다.

### NumberFormatter

- 박람회의 방문객 숫자에 콤마를 적용하기 위해 NumberFormatter를 사용했습니다.
1. 직전에 NumberFormatter()를 호출하여 직접 사용하는 방법

```swift
let numberFormatter = NumberFormatter()
numberFormatter.numberStyle = .decimal

guard let expositionVisitorsCount = numberFormatter.string(for: expositionData.visitors) else {
    return
}

visitorsLabel.text = "방문객: \(expositionVisitorsCount) 명"
```

화면 중에서 NumberFormatter를 적용하여 세 자리마다 콤마를 넣는 방식은 현재 뷰에서만 활용하고 있습니다. 이렇게 일회적인 케이스에 대해서는 직전에 호출시켜 사용하는 방법도 적절하다고 생각되었습니다.

2024-03-17 12:44 UTC, forseaest commented
> 안녕하세요 햄찌 가마 ! STEP2 잘 진행해주셨네요 ! 👍🏻
> 
> 앱 개발자로서 저희는 요구사항(디자이너 또는 기획자)에 대해서 그들이 원하는 것들을 그대로 구현하는 역할을 하고 있는데요!
> 
> 메서드 역할 분리도 잘해주셨고 요구사항에 잘 맞추어서 작성해주신것 같아요 !
> 
> 다만 요구사항에는 방문객숫자가 3자리마다 `,`가 들어있는 형태에요. 이 부분도 추가적으로 구현해주실수 있을까요?! 만약 해당 부분구현에 어려움이 있다면 언제든 알려주세요.
> 
> <img alt="스크린샷 2024-03-14 오후 9 19 46" width="221" src="https://private-user-images.githubusercontent.com/49808034/312834133-9749133f-068a-4bd5-becc-eff9c174239b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2NzczNDAsIm5iZiI6MTcxMDY3NzA0MCwicGF0aCI6Ii80OTgwODAzNC8zMTI4MzQxMzMtOTc0OTEzM2YtMDY4YS00YmQ1LWJlY2MtZWZmOWMxNzQyMzliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDEyMDQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1ZmZkYTdkNjQyNDZmNWYxMjhkMDNkNmU3YWFiY2VlNWI1NGRiYTY0M2MxZDY3NTYyYjE4YzUwZDUxZWNhNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PQSgtY75iY1kav7aTfPuqeZ27UFNHU8i4GzLcmzTT04">
> ## 아쉬운 점에 대한 부분
> * 양쪽에 이미지를 배치하는 방법을 찾지 못하셨다고 하셨네요.  구현하는 방법은 여러가지가 있을 것 같아요.
> 
> 1. StackView를 활용하거나 (StackView안에 이미지뷰 + UIButton(Text만) + 이미지뷰)
> 2. 이미지뷰 + UILabel + 이미지뷰를 UIView에 넣고 해당 UIView를 UIButton(이미지,text모두 없는)으로 감싸주는 방법 (UIView는 optional하게 선택사항입니다)
> 
> 말씀하신것처럼 StackView로 묶고 작업해주시되, TextButton에 IBAction 을 연결하면 될 것같아요 !
> 
> 1번으로 구현해보았습니다(용량제한이 있어서 영상이 짧아요)
> 
>  Simulator.Screen.Recording.-.iPhone.15.Pro.-.2024-03-14.at.21.53.59.mp4 
> ## 궁금한점
> 1. 음 nil 처리는 안전하게 옵셔널 바인딩 하는게 좋다고 생각합니다 !
> 2. 이미지 로딩 시 서버에서 이미지를 받아올 경우 캐싱을 해서 보여주는 방법이 있을것 같구요. 로컬에 이미지를 저장해두는(앱 내부에 두는 방식)은 이미 앱에서 가지고 있기 때문에 앱용량이 커질 것 같아요.
> 3. 네이밍에 관한 부분은 코멘트 남겨두었습니다.
> 4. if let관련해서 코멘트를 남겨두었는데요, 음 guard let과 if let의 차이점을 알아보시면 좋을 것 같습니다.
>    한 가지 예시를 들자면, guard let 같은경우에는 else문을 통해서 return 하게 되는데, 이 guard문과 상관없이 실행되어야하는 로직이 있다면 어떻게 될까요..!? if let 구문은 어떻게 될까요?!

### 숫자 세 자리마다 콤마 적용
방문객 숫자에 콤마를 적용하기 위해 NumberFormatter를 사용했습니다. NumberFormatter의 `numberStyle` 프로퍼티를 `decimal`로 설정하고, `.string(for:)` 함수를 이용했습니다. `.string(for:)`의 매개변수로 방문객 숫자가 담긴 변수를 대입하면 콤마가 적용된 문자열이 나오게 됩니다! 이때, 문자열이 옵셔널 문자열이기 때문에 guard let으로 옵셔널 바인딩을 추가적으로 실행했습니다. 현재 화면의 하나의 뷰에서만 숫자에 콤마를 적용하는 것이 필요하기 때문에, 이런 일회적인 케이스에 대해서는 따로 분리시키거나 하지 않고 사용 직전에 NumberFormatter를 호출시키는 방법이 적절하다고 생각되어 이렇게 구현하게 되었습니다.

```swift
let numberFormatter = NumberFormatter()
numberFormatter.numberStyle = .decimal

guard let expositionVisitorsCount = numberFormatter.string(for: expositionData.visitors) else {
    return
}

visitorsLabel.text = "방문객: \(expositionVisitorsCount) 명"
```

### 버튼의 양 옆에 이미지 배치
박람회 화면에서 출품작 목록으로 가는 버튼의 양 옆에 태극기 이미지를 놓아야 하는데, 말씀하신 스택뷰로 UIImageView + UIButton + UIImageView을 묶어서 구현했습니다!

### if let과 guard let의 차이점
- guard let은 옵셔널 값의 추출이 실패한다면 함수를 종료하거나 오류를 던질 수 있습니다. 옵셔널 바인딩된 변수는 else 코드 블록 뒤에서도 계속 사용할 수 있습니다.
  - guard문과 상관 없이 실행되어야 하는 로직은 guard문 앞에 배치하여 guard문의 조건에 무관하게 실행되도록 해야 합니다. 블록 안에 위치하면 옵셔널 바인딩이 실패할 때에만 실행되고, 블록 아래에 위치하면 옵셔널 바인딩이 성공할 때에만 실행되기에 guard를 만나기 전에 위치해야 한다고 생각합니다.
- if let은 옵셔널 값을 성공적으로 추출하면 코드 블록을 실행하는데, 여기서 옵셔널 바인딩된 변수는 이 코드 블록 안에서만 사용이 가능합니다.
  - if let은 guard문처럼 if문 앞에 배치하거나, if let 블록 혹은 else 블록(else가 있는 경우)이 완전히 닫힌 후에 로직을 배치해야 조건과 무관하게 실행될 수 있다고 생각합니다! if let 블록 안에 배치하면 옵셔널 바인딩이 성공한 경우에만 로직이 실행되고, 선택적으로 else문도 있는 경우, else 블록 안에 배치하면 옵셔널 바인딩이 실패한 경우에만 로직이 실행되기 때문입니다.

2024-03-20 14:15 UTC, merged