[Step1] Tak
yagom-academy/ios-exposition-universelle pull request #31
Opened 2021-04-05 12:56 UTC by Tak95

@corykim0829 
안녕하세요 Cory!! :)

첫번째 Step1 PR 날립니다~!

Codable 프로토콜 채택해서 JSON 데이터와 매칭할 모델 타입 구현해봤습니다.
Asset에 주어진 JSON파일과 이미지 추가했습니다.

공식문서보고 구현해봤는데 코드가 많이 빈약한 것같은데 뭘 더해봐야 할지 모르겠어요ㅠㅠ
더 해봐야 하거나 참고해볼만한 게 있을까요?

2021-04-05 16:04 UTC, corykim0829 requested changes
수고하셨어요 탁! 👍

빨리 하신 만큼 저도 빠르게 리뷰 해드렸습니다 ㅎㅎ
제가 리뷰에 남겼던 부분 공부하면서 같이 이야기 해보면 좋을 것 같아요!!!

궁금한게 있는데, JSON 파일은 이번에 직접 만드는건가요? 아니면 파일은 정해져 있나요? 👀

아 그리고 스토리보드나 UI 적 요소를 구현하면 꼭 캡쳐해서 PR에 같이 올려주세요!

수고 정말 많았어요!

2021-04-05 16:04 UTC, corykim0829 commented on Expo1900/Expo1900/Model/KoreaItem.swift
> +        case desc
변수명을 치환하지 않을 케이스는 한번에 모아서 처리할 수 있어요!
``` suggestion
        case imageName = "image_name"
        case shortDesc = "short_desc"
        case name, desc
```

2021-04-05 16:04 UTC, corykim0829 commented on Expo1900/Expo1900/Model/KoreaItem.swift
> +struct KoreaItems: Codable {
1. KoreaItems 보다는 KoreanItems가 더 문법적으로 알맞은 것 같아요!
2. KoreaItems라고 하면 item 배열을 프로퍼티로 가질 것 같은데 그러지 않네요!

2021-04-05 16:04 UTC, corykim0829 commented on Expo1900/Expo1900/Model/ExpositionUniverselle_1900.swift
> +struct ExpoItem: Codable {
struct와 class의 차이점이 무엇인가요? 여기에서는 왜 struct를 사용했나요? 👀

2021-04-06 07:31 UTC, Tak95 commented on Expo1900/Expo1900/Model/ExpositionUniverselle_1900.swift
> +    init(from decoder: Decoder) throws {
이번 프로젝트처럼 인코드 할 일이 없을 경우엔 Decodable프로토콜을 채택해도 될 것 같네요!

2021-04-06 07:40 UTC, Tak95 commented on Expo1900/Expo1900/Model/KoreaItem.swift
> +struct KoreaItems: Codable {
프로젝트 기능상세서에 이미지파일과 json파일이 첨부되있는데 KoreanItem과 ExpoItem이 분리되어있어서 둘을 분리해주기 위한 네이밍이었는데 혹시 이해하는데 방해가 되었을까요?? 적절하지 않은 네이밍일까요??

2021-04-06 07:51 UTC, Tak95 commented on Expo1900/Expo1900/Model/ExpositionUniverselle_1900.swift
> +struct ExpoItem: Codable {
struct와 class의 차이는 값 타입(복사)인지, 참조 타입인지 / 상속 유무 정도로 알고있습니다.
사실 별 생각 없이 공식문서와 다른 블로그들에서 Struct를 사용해서 사용해봤는데 고민해볼 필요가 있는것 같아서 제 나름대로 생각을 정리해봤어요. :)
애플 가이드라인에 밑 조건 중 하나 이상에 해당한다면 struct사용을 권장한다고 나와있습니다
- 연관된 간단한 값의 집합을 캡슐화 하는것만이 목적일  때
- 캡슐화한 값을 참조하는 것보다 복사하는 것이 합당할 때
- 구조체에 저장된 프로퍼티가 값 타입이며 참조하는 것보다 복사하는 것이 합당할  때
- 다른 타입으로부터 상속받거나 자신이 상속할 필요가 없을 때

저는 이번 프로젝트에서 상속은 쓰일 일이 없을 것 같아서 struct가 더 적절한 것 같아요.
기능을 확장할 일이 생긴다면 extension으로 충분히 확장 가능할 것 같습니다. 
또 구조체는 참조하지 않고 복사하기 때문에 참조로 인한 시간적 비용적 낭비를 막을 수 있다고 알고있어서 클래스와 구조체를 선택함에 있어 더 유리하게 작용한 것 같아요!

2021-04-06 07:58 UTC, Tak95 commented
첫번째 피드백 반영 수정했습니다!
json파일은 기능상세서에 첨부되어서 제시된 json파일이 있어요!

2021-04-06 11:49 UTC, corykim0829 commented on Expo1900/Expo1900/Model/ExpositionUniverselle_1900.swift
> +    init(from decoder: Decoder) throws {
맞아요 디코딩만 할 때가 많아서 Decodable을 먼저 채택하는 것도 좋습니다 ㅎ

2021-04-06 11:50 UTC, corykim0829 commented on Expo1900/Expo1900/Model/KoreaItem.swift
> +struct KoreaItems: Codable {
`KoreanItem`, `ExpoItem`으로 가면 좋습니다 👍

2021-04-06 11:50 UTC, corykim0829 commented on Expo1900/Expo1900/Model/ExpositionUniverselle_1900.swift
> +struct ExpoItem: Codable {
좋습니다 😃

2021-04-06 11:57 UTC, corykim0829 requested changes
수고하셨습니다! 리뷰 남긴 부분 확인 부탁드립니다 👍

2021-04-06 11:57 UTC, corykim0829 commented on Expo1900/Expo1900/Model/KoreanItems.swift
> +    }
ExpoItem과 KoreanItems에 여기 init이 꼭 필요한가요?

2021-04-06 11:57 UTC, corykim0829 commented on Expo1900/Expo1900/Model/ExpositionUniverselle_1900.swift
> +    }
여기 JsonKey enum은 무엇을 위한 코드인가요? 👀

2021-04-06 15:21 UTC, Tak95 commented on Expo1900/Expo1900/Model/KoreanItems.swift
> +    }
json이 잘못들어왔을 경우에 오류가 나면 앱이 터지는 경우가 있다고 찾아봤어요! 이럴 경우를 대비해서 에러처리를 하기 위해 구현해줬어요!
이번엔 제공되어있는 json파일이 있어서 쓸 필요는 없을 것 같은데 공식문서 보면서 배웠던 부분 써먹어보고 싶어서 적었어요!

2021-04-06 15:36 UTC, Tak95 commented on Expo1900/Expo1900/Model/ExpositionUniverselle_1900.swift
> +    }
CodingKey프로토콜을 채택해주기 위해 enum타입으로 묶어줬어요!
어차피 struct ExpoItem 안에서 상수로 타입을 선언해주기 때문에 간단하게 case로 묶어주기만 하면 될 것 같아서 열거형으로 구현했구요
밑에 이니셜라이즈 해줄 때 container를 사용하려면 CodingKey프로토콜이 필요하다고 하더라구요 :)

2021-04-08 15:12 UTC, corykim0829 commented on Expo1900/Expo1900/Model/ExpositionUniverselle_1900.swift
> +    }
CodingKey 프로토콜은 json 데이터의 key값이 Decode할 변수명과 달라서 이를 매치시켜주기 위해서 사용하는거 아닌가요? 👀

2021-04-08 15:20 UTC, Tak95 commented on Expo1900/Expo1900/Model/ExpositionUniverselle_1900.swift
> +    }
넵! 근데 CodingKey프로토콜을 제거하면 밑에 init에서 container(keyedBy:) 메서드를 사용할 수 없다고 나와서 명시해 줬어요! 이 부분은 조금 더 찾아보겠습니다! :)

2021-04-08 15:28 UTC, merged

2021-04-08 15:28 UTC, corykim0829 commented
🎉🎉🎉🎉
개인미션 첫 머지 축하드려요! 탁 스텝2도 화이팅입니다 💪