[Step1] JM
yagom-academy/ios-exposition-universelle pull request #34
Opened 2021-04-06 08:11 UTC by alwaysblu

@delmaSong 

안녕하세요 1번째 STEP입니다!

# 📌 코드를 작성할 때 고민되었던 점 :
<br>
Codable 을 사용할지 아니면 Request와 Reponse에 맞게 Decodable과 Encodable을 사용할지 고민하였습니다.

# 📌 해결이 되지 않은 점:
<br>

# 📌 조언을 얻고 싶은 부분 :
<br>

제가 지은 변수명들 중에서 보다 더 괜찮을 거라고 생각하시는 변수명이 있으신지 궁금합니다!

2021-04-06 15:29 UTC, delmaSong requested changes
안녕하세요! 😀
전반적인 타입의 네이밍과 제공되는 json 파일을 다시 한번 확인해주세요.
`swift json decoding` 등의 키워드로 구글링하시면 도움이 될만한 정보를 얻으실 수 있을거에요.

----

> 리뷰어 님의 폴더 정리 기준과 JSON 타입의 이름을 짓는 기준이 궁금합니다!

- 폴더는 비슷한 역할을 하는 것끼리 모아둡니다. 그런데 프로젝트 규모가 커지면 개별 화면으로 폴더를 정리하고, 내부에 다시 역할에 맞게 폴더를 구분해요.
- json 타입의 이름이면 모델을 말씀하시는 건가요? 표현하고자 하는 모델을 가장 간단하게 나타낼 수 있는 이름으로 짓습니다. 예를들어 이번 프로젝트라면 `ExpoInfo`, `ExpoItem` 으로 각각 지을 수도 있겠네요 ㅎㅎ

> JSON 타입을 만드는 과정에서 유닛테스트가 필요하다고 생각하시는지 궁금합니다!

타입을 만든다는 것이 json 타입(형식)의 파일을 만든다는 말이 아니라 json을 담을 모델을 만드는 과정을 말씀하시는 거지요? 그거라면 모델 자체가 잘 만들어지는지는 테스트하지 않습니다. 서버에서 제공되는 어떤 json 형식이 달라졌을 때 캐치하기도 용이하고 만든 모델의 타입들이 json을 디코딩/인코딩하기에 적절하게 만들어졌다는 걸 확인하는데 도움이 되고자 만든 모델로 json이 제대로 디코딩/인코딩 되는지를 판단하는 테스트케이스는 작성합니다.

2021-04-06 15:29 UTC, delmaSong commented on Expo1900/Expo1900/Entity/MainRequest.swift
> +    var content: String
`MainRequest`라는 표현은 담고있는 프로퍼티들을 표현하기에 충분하지 않은 표현인 것 같아요.
이게 요구사항의 `첫 화면에는 1900 만국박람회 포스터와 각종 설명을 표시합니다` 를 충족하기 위한 타입인거죠?
제공되는 `expo_assets.zip`의 `exposition_universell_1900.json` 파일 확인은 해보셨나요?

2021-04-06 15:29 UTC, delmaSong commented on Expo1900/Expo1900/Entity/EntryOfKoreaRequest.swift
> +    var title: String
`Entry`라는 단어가 참 모호한데, 무슨 의미를 표현하고자 사용하신건가요?

2021-04-06 15:29 UTC, delmaSong commented on Expo1900/Expo1900/Entity/EntryOfKoreaRequest.swift
> +struct EntryOfKoreaRequest: Decodable {
`-Request` 라는 접미사는 보통 네트워크 요청을 보내는 객체에 붙입니다
표현하시고자 하는 건 모델에 더 가까워보이는데, 맞을까요?

2021-04-06 15:29 UTC, delmaSong commented on Expo1900/Expo1900/Entity/detailOfEntryRequest.swift
> +    var title: String
struct를 사용하셨는데 class를 사용하지 않고 struct를 사용하신 기준이 무엇인지 궁금합니다

2021-04-07 05:57 UTC, alwaysblu commented on Expo1900/Expo1900/Entity/MainRequest.swift
> +    var content: String
이미지만 있는 줄 알았는데 json 파일도 있었네요

확인인 후 수정했습니다!

2021-04-07 05:58 UTC, alwaysblu commented on Expo1900/Expo1900/Entity/EntryOfKoreaRequest.swift
> +    var title: String
Entry가 출품작이라는 뜻이 있어서 사용했는데 의미가 모호하게 느껴지는 것 같아서 item으로 변경했습니다!

2021-04-07 06:01 UTC, alwaysblu commented on Expo1900/Expo1900/Entity/EntryOfKoreaRequest.swift
> +struct EntryOfKoreaRequest: Decodable {
네 step1을 다시 보니 모델로 하면 안될 것 같다는 생각이 드네요

step1은 네트워크와는 관계가 없어서 Request 접미사는 삭제했습니다!

2021-04-07 06:04 UTC, alwaysblu commented on Expo1900/Expo1900/Entity/EntryOfKoreaRequest.swift
> +struct EntryOfKoreaRequest: Decodable {
네 JSON 포멧의 데이터와 매칭할 모델 타입을 표현하고자 했습니다

step1은 네트워크와는 관계가 없어서 Request 접미사는 삭제했습니다!

2021-04-07 06:05 UTC, alwaysblu commented on Expo1900/Expo1900/Entity/detailOfEntryRequest.swift
> +    var title: String
https://developer.apple.com/documentation/foundation/jsondecoder

위의 애플 공식 문서에서 struct를 사용하고 있어서 class 대신 struct를 사용하였고

https://developer.apple.com/documentation/swift/choosing_between_structures_and_classes

위의 링크에 class와 struct의 선택 기준에서 Objective - C 를 제어하지 않고 data의 identity를 제어하지 않으므로 default 로 struct를 사용하였습니다!

2021-04-07 06:19 UTC, alwaysblu commented
# 리뷰 감사합니다!

제가 JSON 파일을 확인을 못하고 제멋대로 만들어 버렸었네요;;



# 📌 코드를 작성할 때 고민되었던 점 :

Contents.json 파일이 왜 필요할까? 라는 궁금증이 생겼습니다.

# 📌 해결이 되지 않은 점:

Contents.json 파일이 왜 필요할까? 라는 궁금증을 완벽히 해결하지 못하였습니다.

# 📌 조언을 얻고 싶은 부분 :

Contents.json 파일의 용도와 필요 여부에 대해서 고민해 보았지만 아직 완벽히 해결되지않았습니다.

여러개의 json 데이터를 관리할 목적으로 만들었다는 생각이 드는데

혹시 왜 Contents.json 파일을 저 형식으로 작성했다고 생각하시는지 궁금합니다.

Codable과 Decodable과 Encodable의 사용 기준이 궁금합니다!

2021-04-07 12:46 UTC, delmaSong requested changes
> Content.json 이 왜 필요할까?

아래 코멘트를 확인해주세요. 그리고 `swift content.json` 으로 구글링 해보셨나요?

> Codable VS Decodable과 Encodable의 사용 기준이 궁금합니다!

Codable과 Decodable, Encodable은 각각 무엇인가요? 

> 제가 struct를 사용한 이유가 좀 더 struct에 특성에 관련된 이유여야 할지 궁금합니다!

공식문서등을 따라하는 것은 좋은 연습 방법입니다. 그러나 좀 더 나아가서는 각각의 특징이 무엇이고 장단점은 무엇인지, 내가 어떤 용도로 사용하고자 하는 지 등을 생각해서 본인만의 기준을 세워가시면 좋을 것 같습니다. 

> 이번 경우에는 굳이 JSON의 변수명과 똑같이 안해줘도 되는건지 궁금합니다!

`swift json decoding` 이라는 키워드로 찾아보셨나요? 왜 이번에는 json의 키와 똑같이 안해줘도 된다고 생각하셨는지 궁금합니다

2021-04-07 12:46 UTC, delmaSong commented on Expo1900/Expo1900/Entity/Content.swift
> +}
무슨 용도의 구조체인가요?

2021-04-07 12:46 UTC, delmaSong commented on Expo1900/Expo1900/Entity/ExhibitOfKorea.swift
> +    var name: String
Item 이라는 타입만 놓고 보자면 무엇의 아이템이란건지 전혀 모르겠습니다

2021-04-07 12:46 UTC, delmaSong commented on Expo1900/Expo1900/Entity/Content.swift
> +}
Content.json 파일은 Assets.xcaseets의 메타데이터입니다.
보통 이미지 등은 json에 담아 주고받지 않고 http 헤더나 바디에 담아 서버와 주고받습니다.
http 요청/응답시에 데이터를 어떤식으로 주고받는지 살펴보시고 [Contents.json File](https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_ref-Asset_Catalog_Format/Contents.html) 도 참고해보세요

2021-04-07 12:46 UTC, delmaSong commented on Expo1900/Expo1900/Entity/MainOfExposition.swift
> +}
> Open API 를 사용할 때 Codable을 이용해서 데이터를 받을 때는 JSON 의 변수명과 완전 똑같이 해줘야 된다고 알고 있는데
이번 경우에는 굳이 JSON의 변수명과 똑같이 안해줘도 되는건지 궁금합니다!

왜 이번에는 json의 키와 똑같이 안해줘도 된다고 생각하셨는지 궁금합니다

2021-04-07 15:05 UTC, alwaysblu commented
## Item 이라는 타입만 놓고 보자면 무엇의 아이템이란건지 전혀 모르겠습니다

명확하지 않은 것 같아서 ExhibitItem 로 변경했습니다.
 
## 왜 이번에는 json의 키와 똑같이 안해줘도 된다고 생각하셨는지 궁금합니다

enum을 이용해서 구현한 모델 내용을 보고 착각한 것 같습니다.

2021-04-08 14:26 UTC, delmaSong commented on Expo1900/Expo1900/Entity/ExhibitOfKorea.swift
> +    var desc: String
[swift conventions](https://swift.org/documentation/api-design-guidelines/#conventions)
위 문서를 보면 프로퍼티는 모두 lowerCarmelCase로 작성한다고 합니다.
CodingKeys에 대해 알아볼까요?

2021-04-08 14:29 UTC, delmaSong commented on Expo1900/Expo1900/Entity/Content.swift
> +}
커밋으로는 이 파일을 지웠다고 나와있는데
아직 남아있네요? 🤔

2021-04-08 14:54 UTC, alwaysblu commented on Expo1900/Expo1900/Entity/Content.swift
> +}
다시 확인하고 지웠습니다!

2021-04-08 14:54 UTC, alwaysblu commented on Expo1900/Expo1900/Entity/ExhibitOfKorea.swift
> +    var desc: String
import Foundation

struct ExhibitOfKorea: Decodable {
    var exhibitItems: [ExhibitItem]
}

struct ExhibitItem: Decodable {
    var name: String
    var imageName: String
    var shortDescriptions: String
    var descriptions: String
    
    enum CodingKeys: String, CodingKey {
        case name
        case imageName = "image_name"
        case shortDescriptions = "short_desc"
        case descriptions = "desc"
    }
}

이와 같이 변경했습니다!

2021-04-08 14:57 UTC, alwaysblu commented
@delmaSong 

리뷰 감사합니다!

lowerCamelCase로 변경하고 Codingkey를 이용했습니다.

Contetn.swift 파일 지워진 것을 확인했습니다.

2021-04-08 14:58 UTC, delmaSong commented
수고하셨습니다! 1단계는 여기까지하고 2단계에서 뵈어요!
추가로, 공부하셨겠지만 복습의 차원에서 CodingKey가 무엇인지, 어떨때 사용하는지 설명해주실 수 있을까요? 😀

2021-04-08 14:58 UTC, delmaSong approved these changes

2021-04-08 14:59 UTC, merged

2021-04-09 07:14 UTC, alwaysblu commented
> 수고하셨습니다! 1단계는 여기까지하고 2단계에서 뵈어요!
> 추가로, 공부하셨겠지만 복습의 차원에서 CodingKey가 무엇인지, 어떨때 사용하는지 설명해주실 수 있을까요? 😀

CodingKey는 encoding과 decoding을 위한 Key로서 사용되어지는 프로토콜 타입입니다.      

CodingKey는 JSON의 키값이 카멜케이스 형식이 아닐때 카멜케이스 형식으로 변경하기 위해서 주로 사용한다고 조사했습니다!