[Step1] Sunny
yagom-academy/ios-exposition-universelle pull request #41
Opened 2021-04-07 04:08 UTC by unme88

@corykim0829

Cory 안녕하세요 😉
맛점 하셨나요? 😋
캠프에서 처음으로 진행하는 단독 프로젝트라 두근두근합니다...ㅎㅎ

Step1에서는 타입 구현만 해봤어요!
우선 제공받은 json 첨부파일에 맞게 모델을 저는 2가지로 나눠줬는데요.
ItemsOfExpo와 ItemsOfKorea을 구조체로 구현해봤습니다.

class를 사용하지 않은 이유는 딱히 상속을 할 경우가 이번에 있을지 잘 모르겠어서 필요성을 못 느꼈어요. 

enum의 경우 값이 나중에 추가되거나 그러면 변경하기 어렵다고 들었는데요.
이번에는 그런 경우는 특별히 없을 것 같지만,
그런 상황이 있을수도 있다는 가정(?) 하에 enum을 사용하지 않았습니다.

**고민한 부분 - 네이밍 **
json 첨부 파일을 보니 name이랑 imageName이랑 같은 이름인데 한국 이름, 영문 이름 이 차이라 이에 맞게 네이밍을 해봤습니다.

_ItemsOfExpo.swift_
expoTitle, location, description는 변경 사항이 없어서 한번에 let으로 선언했습니다.
visitors와 duration는 의미가 정확하게 전달되지 않는 것 같아서 바꿔줬어요.
visitors는 누가 방문한다는 느낌인데 예시에는 방문객 수가 숫자로 나와있어서 numberOfVisitors로 네이밍했습니다.
duration은 몇년, 몇 주 이런 기간의 의미인데 예시에는 언제부터 언제까지라고 나와있어서 openingPeriod (오프닝 기간)으로 바꿨습니다.

_ItemsOfKorea.swift_
후보 1. titleInKorean, titleInEnglish
후보 2. KoreanTitle, EnglishTitle
왠지 후보 2가 더 눈에 잘 들어오는 것 같아서 이걸로 CodingKey를 이용한 enum안에서 이름을 바꿔줬어요.

**궁금한 점**
다른 캠퍼분들 코드를 보니 json 값이 없거나 제대로 들어가지 않은 경우를 대비해서
init(from decoder: Decoder) throws  이런 식으로 디코드 + 에러 핸들링을 해줬는데요.
저는 첨부파일에 보니 내용이 모두 맞게 들어가있어서..
이번 프로젝트에서는 굳이? 필요 없다고 생각해서 decode만 해줄 계획인데요.
혹시 에러 핸들링도 시도를 해보는게 좋을까요?

(디코드 방식이 종류가 여러가지가 있는데
어떤 걸 써보는게 좋은지..? 고민입니다 ^^;)

이해가 되지 않는 부분 & 피드백 언제나 환영입니다 🙆‍♀️
감사합니다 :)

2021-04-07 12:56 UTC, corykim0829 requested changes
수고했어요 써니! 👏👏👏👏

전체적으로 봤을 때 뭔가 빠져있는 느낌이 많이 드는데, 혹시 커밋이나 푸쉬할 때 일부 파일이 누락이 된건가요?
현재 프로젝트에서 컴파일 에러가 나서 말씀드려요 🥲

디코딩 관련 프로토콜은 [Encoding and Decoding Custom Types](https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types)을 참고하여 다시 한번 적용해보시면 좋을 것 같아요!

여유가 되신다면 class와 struct에서 상속 외에도 어떤 차이가 있는지 알아보시면 좋을 것 같아요!! 화이팅입니다 💪

2021-04-07 12:56 UTC, corykim0829 commented on Expo1900/Expo1900/Model/ItemsOfKorea.swift
> +struct ItemsOfKorea : decoder {
여기도 `ItemsOfExpo` 피드백 참고해서 반영해보세요!

2021-04-07 12:56 UTC, corykim0829 commented on Expo1900/Expo1900/Contents2.swift
> +//}
의미없는 주석은 지워서 올려주세요~

2021-04-07 12:56 UTC, corykim0829 commented on Expo1900/Expo1900/Model/ItemsOfExpo.swift
> +struct ItemsOfExpo : decoder {
여기 decoder는 직접 구현한 protocol인가요? 👀 제가 직접 코드를 똑같이 작성해도 정상적으로 동작하지 않아서 여쭤봐요!

2021-04-07 12:56 UTC, corykim0829 commented on Expo1900/Expo1900/Model/ItemsOfKorea.swift
> +    var data = jsonString.data(using: .utf8)
여기에 `jsonString`은 어디에 구현되어 있나요? 👀

2021-04-07 12:56 UTC, corykim0829 commented on Expo1900/Expo1900/Model/ItemsOfKorea.swift
> +    }
해당 코드를 여기에 구현한 이유가 있나요? 👀

2021-04-08 08:27 UTC, unme88 commented on Expo1900/Expo1900/Model/ItemsOfExpo.swift
> +struct ItemsOfExpo : decoder {
> 여기 decoder는 직접 구현한 protocol인가요? 👀 제가 직접 코드를 똑같이 작성해도 정상적으로 동작하지 않아서 여쭤봐요!

Decodable을 넣는다는게 실수했네요 ㅠㅠ 고쳤습니다!
(이번 프로젝트에서는 인코딩을 하지 않아서 Codable을 반드시 사용하지 않아도 될 것 같아요!)

2021-04-08 08:29 UTC, unme88 commented on Expo1900/Expo1900/Model/ItemsOfExpo.swift
> +struct ItemsOfExpo : decoder {
> `ItemsOfExpo`라고 하면 `Items`라고 하여 배열을 가지고 있을법한 네이밍 같아요
> 어떤 아이템 하나를 나타내는 구조체이니 간결하게 `ExpoItem`이라고 해도 좋을 것 같습니다.😀

넵! 수정했습니다 ^.^

2021-04-08 08:33 UTC, unme88 commented on Expo1900/Expo1900/Model/ItemsOfKorea.swift
> +struct ItemsOfKorea : decoder {
> 여기도 `ItemsOfExpo` 피드백 참고해서 반영해보세요!

넵 KoreanItem으로 바꿨어요! ^.^

2021-04-08 08:33 UTC, unme88 commented on Expo1900/Expo1900/Model/ItemsOfKorea.swift
> +struct ItemsOfKorea : decoder {
넵 KoreanItem으로 바꿨어요! ^.^

2021-04-08 08:34 UTC, unme88 commented on Expo1900/Expo1900/Contents2.swift
> +//}
음 저 파일은 만들었다가 지웠는데 ㅠㅠ 왜 올라간거지.. 다시 확인해볼게요! 😢

2021-04-08 08:37 UTC, unme88 commented on Expo1900/Expo1900/Model/ItemsOfKorea.swift
> +    var data = jsonString.data(using: .utf8)
음.. json 구현 방법을 아직 고민중이라 하다가 냅뒀네요 😥 지웠습니다!!! 완성하면 다시 포함해서 올릴게요 😅

2021-04-08 08:39 UTC, unme88 commented on Expo1900/Expo1900/Model/ItemsOfKorea.swift
> +    }
json을 연습하고 있었는데... step1까지는 타입만 구현하는 걸로 다시 확인해서 일단 지웠어요!
Step2 올릴 때 다시 완성해서 올릴게요!!
혼란스럽게 해서 죄송해요!! 🤦‍♀️

2021-04-08 09:20 UTC, unme88 commented
@corykim0829
안녕하세요 cory ^.^
말씀해주신 부분 수정해서 다시 업데이트했어요!
(지난번엔 이미 삭제한 파일이 같이 올라갔는데 😢
이번엔 제대로 반영됐을런지 모르겠네요 ㅠㅜ)

말씀하신 class와 struct의 가장 중요한 차이는 참조 타입과 값 타입인 것으로 알고 있어요! (enum도 struct와 마찬가지로 값 타입이고요) class는 참조 타입이라서 변수를 만들때 새로운 카피본이 생겨나는 것이 아니라 이미 존재하는 인스턴스에 대한 레퍼런스가 이용되고요.
참조 횟수 또한 클래스의 인스턴스에만 해당돼요.
 
반면, struct는 값 타입이라서 또 하나의 복사본 (또 하나의 인스턴스)를 만들어내요.

타입캐스팅과 디이니셜라이저 또한 클래스의 인스턴스에만 적용할 수 있습니다.

감사합니다 :)

2021-04-08 15:18 UTC, corykim0829 commented on Expo1900/Expo1900/Contents.swift
> +//
아직도 여기 파일들이 남아있네요! 정리 부탁드립니당 ㅎ

2021-04-08 22:33 UTC, unme88 commented on Expo1900/Expo1900/Contents.swift
> +//
앗 폴더로 들어가서 파일을 아예 삭제했습니다 🤦‍♀️

2021-04-08 22:51 UTC, unme88 commented on Expo1900/Expo1900/Model/KoreanItem.swift
> +    enum CodingKeys : String, CodingKey {
수정해줬어요 >.<
꼼꼼하게 봐주셔서 감사합니다!!!

2021-04-09 02:36 UTC, corykim0829 approved these changes
변수명 하나 수정할 부분은 다음 스텝 하시면서 수정해주세요! 수고하셨어요 ㅎㅎ

2021-04-09 02:36 UTC, corykim0829 commented on Expo1900/Expo1900/Model/KoreanItem.swift
> +    let EnglishTitle : String
이제보니 여기는 대문자로 시작하네요!

2021-04-09 02:38 UTC, merged

2021-04-09 02:41 UTC, unme88 commented on Expo1900/Expo1900/Model/KoreanItem.swift
> +    let EnglishTitle : String
이럴수가 ㅠㅠ 수정할게요!!