[Step1] - Sookim
yagom-academy/ios-exposition-universelle pull request #43
Opened 2021-04-07 14:18 UTC by Sookim18

## [STEP 1] 만국박람회 🇰🇷

@corykim0829 

안녕하세요~ cory 

step1 코드를 작성해봤어요 

ViewController에서 json파싱이 되는지 추가로 테스트코드를 작성했어요 👀

### 고민되었던 점, 해결되지 않은 점, 궁금한 점 ❗️❓

- `Contents.json`파일은 계층 구조에서 폴더로 표시되는 요소에 대한 속성을 인코딩합니다. 하지만, `Contents.json` 파일을 안만들고 이미지파일만 넣어도 작동이 하는데 사용하는 이유가 궁금해요🤔 

- `Exhibits`와 `ExhibitDescription`을 구조체로 사용한 이유가 json의 key값을 불러오고 사용만 하기 때문에 상속을 사용하지 않고 값을 불러온 후 사용하기 때문에 구조체로 사용했는데 맞게 사용한 건가요??

- `Exhibits`와 `ExhibitDescription`에서 프로퍼티를 let으로 선언한 이유가 값을 가져온 후 변경하지 않을 거라 생각해서 let을 사용했는데 적절하게 사용한 건지 궁금해요

- `Exhibits` 구조체에서 image_name프로퍼티에서 이미지를 가지고 올때 뷰에서 보여줄 때 UIImage(named: image_name) 이런식으로 named에 이미지명을 넣어줄 텐데 미리 Exhibits구조체에서 처리하는 방식이 맞는지 ?? 나중에 이미지를 가지고올 때 처리하는게 맞는지 궁금해요 🤔

- `Exhibits`와 `ExhibitDescription`을 구조체에서 init을 사용한 이유가 json파일에서 key값이 삭제된 경우나 다른 key값이 들어올 때 기본값을 생성함으로써 에러에 대비해야 해서 구조체를 생성할 때 

  1. init을 통해 직접 디폴트 값으로 사용하는 방법, 

  2. 구조체 매개변수에 디폴트값을 직접 넣는 방법,

  3. 옵셔널타입으로 처리하는 방법 중 무엇이 가장 합리적인지 궁금해요 😁

2021-04-08 07:57 UTC, corykim0829 requested changes
수고하셨어요 수킴 👏👏👏👏👏

리뷰 해드린 부분 수정해주세욥!
마지막 코드는 테스트 코드라기 보다는 실행코드라고 보면 좋을 것 같네요!

> 고민되었던 점, 해결되지 않은 점, 궁금한 점 ❗️❓

> Contents.json파일은 계층 구조에서 폴더로 표시되는 요소에 대한 속성을 인코딩합니다. 하지만, Contents.json 파일을 안만들고 이미지파일만 넣어도 작동이 하는데 사용하는 이유가 궁금해요🤔

➡️ 흠 제가 알기로는 Contens.json은 Xcode에서 자동적으로 생성하고 처리하지 않나요? 파일을 안만든다는 말이 어떤 의미인지 잘 모르겠네요 👀

> Exhibits와 ExhibitDescription을 구조체로 사용한 이유가 json의 key값을 불러오고 사용만 하기 때문에 상속을 사용하지 않고 값을 불러온 후 사용하기 때문에 구조체로 사용했는데 맞게 사용한 건가요??

➡️ 상속으로만 판단하기에는 무리가 있고, struct와 class의 본질적인 차이를 조금 더 알아보면 좋을 것 같네요! 

> Exhibits와 ExhibitDescription에서 프로퍼티를 let으로 선언한 이유가 값을 가져온 후 변경하지 않을 거라 생각해서 let을 사용했는데 적절하게 사용한 건지 궁금해요

➡️ 네 현재 구조체에서 let으로 사용하신거는 적절한 것 같습니다. 왜 적절할까요??

> Exhibits 구조체에서 image_name프로퍼티에서 이미지를 가지고 올때 뷰에서 보여줄 때 UIImage(named: image_name) 이런식으로 named에 이미지명을 넣어줄 텐데 미리 Exhibits구조체에서 처리하는 방식이 맞는지 ?? 나중에 이미지를 가지고올 때 처리하는게 맞는지 궁금해요 🤔

➡️ 질문을 이해하기가 어렵네요 ㅜ 미리 Exhibits구조체에서 처리한다는게 어떤 의미죠?

> Exhibits와 ExhibitDescription을 구조체에서 init을 사용한 이유가 json파일에서 key값이 삭제된 경우나 다른 key값이 들어올 때 기본값을 생성함으로써 에러에 대비해야 해서 구조체를 생성할 때
init을 통해 직접 디폴트 값으로 사용하는 방법,
구조체 매개변수에 디폴트값을 직접 넣는 방법,
옵셔널타입으로 처리하는 방법 중 무엇이 가장 합리적인지 궁금해요 😁

➡️ 이 부분은 리뷰로 답변을 해드렸습니다! 😃

2021-04-08 07:57 UTC, corykim0829 commented on Expo1900/Expo1900/Model/ExhibitModel.swift
> +struct Exhibits: Decodable {
`Exhibits`라고 하면 Exhibit 타입의 배열 컬렉션을 가지고 있을 것 같은 네이밍 입니다. 이 하나의 객체가 뭘 의미하는 모델인지 표현할 수 있는 이름이면 좋을 것 같아요!

2021-04-08 07:57 UTC, corykim0829 commented on Expo1900/Expo1900/Model/ExhibitModel.swift
> +    }
이렇게 디코드 처리를 하면, 값이 공백인 객체가 생길 수도 있습니다. 이 부분은 질문에도 해주셨는데, 데이터가 어떻게 넘어올지 보장 여부와도 관련이 있기는 합니다. 정확하게 이 타입대로만 넘어오면 문제가 없기 때문에 nil값으로 넘어올 수 도 있는 친구들은 옵셔널 타입 자체로 받는게 더 처리하는데 있어서 수월합니다. 
개인적인 의견으로는 여기 init은 꼭 필요하지 않은 것 같습니다.

2021-04-08 07:57 UTC, corykim0829 commented on Expo1900/Expo1900/ViewController.swift
> +    var exhibitDescription: ExhibitDescription = ExhibitDescription(title: "", visitors: 0, location: "", duration: "", description: "")
이런 경우는 타입이 명확하기 때문에 타입을 명시하지 않아도 될 것 같아요! 👀

2021-04-08 07:57 UTC, corykim0829 commented on Expo1900/Expo1900/ViewController.swift
> +    var exhibitDescription: ExhibitDescription = ExhibitDescription(title: "", visitors: 0, location: "", duration: "", description: "")
항상 private 으로 먼저 고려해주는게 객체지향적인 프로그래밍입니다 😃

2021-04-08 07:57 UTC, corykim0829 commented on Expo1900/Expo1900/Model/ExhibitDescription.swift
> +struct ExhibitDescription: Decodable {
ExhibitDescription안에 또 description이 있어서 조금 아쉬운 네이밍이네요 😅

2021-04-08 11:55 UTC, Sookim18 commented on Expo1900/Expo1900/Model/ExhibitModel.swift
> +struct Exhibits: Decodable {
Exhibits 출품작들인데 한국의 출품작 각각 하나의 인스턴스로 생성되므로 KoreaExhibitItem으로 변경했어요 ❗️

2021-04-08 11:57 UTC, Sookim18 commented on Expo1900/Expo1900/Model/ExhibitModel.swift
> +    }
지금 사용하는 items.json 파일은 이미 asset폴더에 파일을 넣어주어서 json의 키-값이 변경되는 경우가 없어서 init을 사용하지 않아도 된다고 이해하면 될까요?? url이나 외부에서 json파일을 받는 경우에 init을 사용하는 편이 좋다는

2021-04-08 12:01 UTC, Sookim18 commented on Expo1900/Expo1900/ViewController.swift
> +    var exhibitDescription: ExhibitDescription = ExhibitDescription(title: "", visitors: 0, location: "", duration: "", description: "")
exhibitDescription 에서 ExhibitDescription이 명시되어있어서 타입은 생략해도 될거 같아요 ㅎㅎ

2021-04-08 12:01 UTC, Sookim18 commented on Expo1900/Expo1900/ViewController.swift
> +    var exhibitDescription: ExhibitDescription = ExhibitDescription(title: "", visitors: 0, location: "", duration: "", description: "")
주의하겠습니다 💡

2021-04-08 12:01 UTC, Sookim18 commented on Expo1900/Expo1900/Model/ExhibitDescription.swift
> +struct ExhibitDescription: Decodable {
단어가 겹치면 헷갈릴 수 있는 것 같아요 주의하겠습니다.

2021-04-08 12:27 UTC, Sookim18 commented
➡️ 흠 제가 알기로는 Contens.json은 Xcode에서 자동적으로 생성하고 처리하지 않나요? 파일을 안만든다는 말이 어떤 의미인지 잘 모르겠네요 👀

- 💡 만약 color asset을 추가한다면 Contents.json도 직접 작성해야하는 줄로 잘못 이해하고 있었어요. 이미지 파일만 asset에 넣어도  Contents.json이 자동으로 생성하고 처리하는지 몰랐었어요 😅

➡️ 상속으로만 판단하기에는 무리가 있고, struct와 class의 본질적인 차이를 조금 더 알아보면 좋을 것 같네요!

- Struct : 값 타입 (변경하려면 키워드를 여러가지 명시해야함)
- Class : 참조 타입 
  - 구조체를 사용하면 좋은 경우
    1. 연관된 간단한 값의 집합을 캡슐화하는 것만이 목적일 때
    2. 캡슐화한 값을 참조하는 것보다 복사하는 것이 합당할 때
    3. 구조체에 저장된 프로퍼티가 값 타입이며 참조하는 것보다 복사하는 것이 합당할 때
    4. 다른 타입으로부터 상속받거나 자신을 상속할 필요가 없을 때

➡️ 네 현재 구조체에서 let으로 사용하신거는 적절한 것 같습니다. 왜 적절할까요??

- 구조체에서 프로퍼티명과 값은 json파일의 키 -값과 같은데 json파일의 키 - 값이 정확히 보장되어있기 때문에 값이 변경되지 않을 것 같아서 let이 적절한 것 같아요. 



➡️ 질문을 이해하기가 어렵네요 ㅜ 미리 Exhibits구조체에서 처리한다는게 어떤 의미죠?

- 연산프로퍼티를 활용해서 모델에서 직접 이미지처리를 해야하는지 생각해봤어요

2021-04-11 11:14 UTC, corykim0829 approved these changes
수고하셨어요 수킴!! 👍👍

첫 머지 축하드려요!! 👏👏👏👏👏
제 질문에 대한 답변들도 너무 잘해주셨습니다 😎

피드백 해드린 부분은 step2 진행하면서 수정해보세요!! 화이팅! 😃

2021-04-11 11:14 UTC, corykim0829 commented on Expo1900/Expo1900/Model/Expo1900Information.swift
> +struct Expo1900Information: Decodable {
이 구조체 자체가 Expo1900의 정보를 담고 있으니 Information이라는 단어를 빼면 더 깔끔한 네이밍이 될 것 같아요! 😃

2021-04-11 11:14 UTC, merged