[Step1] Yoshikim
yagom-academy/ios-exposition-universelle pull request #48
Opened 2021-04-08 13:26 UTC by taeyoung-Kim-KR

@corykim0829 

안녕하세요! cory! 
첫번째 PR이 많이 늦었습니다. 처음으로 프로젝트 PR을 해보는데 지금까지는 동기들 옆에서 따라다니다가
혼자 프로젝트 진행하려니 너무 떨리고 모든게 다 어렵네요😨

구현정보
STEP1은 STEP2 내용을 참고하여 JSON 포멧 데이터와 매칭할 모델 타입을 구현해 보았습니다.
- ExpoInformation 모델 타입 구현
- KoreaItemInformation 모델 타입 구현

2021-04-08 15:16 UTC, corykim0829 requested changes
요시킴 수고하셨어요!! 👏👏👏

깔끔하게 잘 구현하셨네요 ㅎ

네이밍만 집고 넘어가면 좋을 것 같아요!

2021-04-08 15:16 UTC, corykim0829 commented on Expo1900/Expo1900/KoreaItemInformation.swift
> +    }
CodingKey 구현 깔끔하게 잘 하셨네요! 👍

2021-04-08 15:16 UTC, corykim0829 commented on Expo1900/Expo1900/KoreaItemInformation.swift
> +
공백 줄 정리 부탁드려요~

2021-04-08 15:16 UTC, corykim0829 commented on Expo1900/Expo1900/ExpoInformation.swift
> +struct ExpoInformation: Codable {
이 구조체가 Expo를 의미하고 있기 때문에 뒤에 Information을 붙이기 보다는 그냥 `Exopo`라고 하면 더 깔끔한 네이밍이 될 것 같아요!

2021-04-08 15:16 UTC, corykim0829 commented on Expo1900/Expo1900/ExpoInformation.swift
> +    let description: String
타입이 같고 초기값을 넣어주지 않을거면, 한 줄에 여러개를 동시에 선언할 수 있어요! 참고하세요~

2021-04-09 07:24 UTC, taeyoung-Kim-KR commented on Expo1900/Expo1900/KoreaItemInformation.swift
> +    }
잘 할줄몰라서 깔끔해진것 같아요. 😅 감사합니다!

2021-04-09 07:25 UTC, taeyoung-Kim-KR commented on Expo1900/Expo1900/KoreaItemInformation.swift
> +
공백 지웠습니다! 😃

2021-04-09 07:28 UTC, taeyoung-Kim-KR commented on Expo1900/Expo1900/ExpoInformation.swift
> +struct ExpoInformation: Codable {
네이밍을 선택할때 내포한것을 자세히 쓰는것과 간소화하는게 아직 어려운거 같아요. 천천히 진행하면서 좋은 방향으로 만들어 보겠습니다.
일단 Expo 로 수정하였습니다.😃

2021-04-09 07:29 UTC, taeyoung-Kim-KR commented on Expo1900/Expo1900/ExpoInformation.swift
> +    let description: String
넵. 일단 한눈에 보기 편하려고 나눠 놨는데 한 줄에 여러개 동시에 선언 참고하도록 하겠습니다!☺️

2021-04-11 14:08 UTC, corykim0829 approved these changes
요시 수고하셨습니다!! 👍

첫 머지 축하드려요!! 👏👏👏 🎉🎉🎉🎉

피드백은 step2 진행하면서 처리해주시면 될 것 같아요! 화이팅!

2021-04-11 14:08 UTC, corykim0829 commented on Expo1900/Expo1900/KoreaItemInformation.swift
> +struct KoreaItemInformation: Codable {
여기도 Expo 구조체 리뷰 때 말씀드렸 듯이 Information을 빼면 더 깔끔한 네이밍이 될 것 같아요!

2021-04-11 14:08 UTC, merged