Step2 - wody
yagom-academy/ios-exposition-universelle pull request #53
Opened 2021-04-09 09:00 UTC by Wody95

@O-O-wl 

안녕하세요 붱이 😆😆😆

붱이에게 물어보니깐 step2를 술술술 할 수 있었습니다!! 정말 감사해요☺️

이번 스텝을 진행하면서 고민되었던 점은 다음과 같습니다
- JSON 데이터를 파싱하는 기능을 따로 함수로 만들어 관리하고 싶은데 어떻게 하면 좋을지 감이 안잡힙니다. 
- 뷰 컨트롤러 간 데이터를 전달하는 방식을 뷰컨트롤러 밖에 변수를 만들어 전달하게 했는데 괜찮은 방법일까요?

2021-04-09 15:09 UTC, O-O-wl requested changes
고민을 많이 하신 것 같아요 저도 아직도 고민을 많이하고 있는 객체간의 커뮤니케이션에서 고민을 하고 계시군요
지금 특히 ViewController간의 커뮤니케이션에서 고민을 하시고 계신 것 같아요
그 과정에서 전역적인 itemData라는 프로퍼티를 이용하셨군요
음 천천히 생각해보시면 좋을 것 같아요
ViewController가 아닌 다른 오브젝트였더라도(ex. JuiceMaker?) 
이런 방식으로 커뮤니케이션 했을까요? 
혹시 질문이 있다면 언제든지! 불러주세여~

2021-04-09 15:09 UTC, O-O-wl commented on Expo1900/Expo1900/Controller/View/ViewController.swift
> +    func jsonPaser() {
메소드 네이밍을 조금 더 고려해볼까요 
음 ... 사견이지만 메소드 내부에서 어떤 행위를 하는 지로 네이밍을 하는 것보다 호출하는 쪽에서 어떤 결과를 얻는 지에 대한 네이밍을 하는 게 더 명확할 것 같아요

2021-04-09 15:09 UTC, O-O-wl commented on Expo1900/Expo1900/Controller/View/ViewController.swift
> +            print(error.localizedDescription)
고민해보시면 좋을 것 같아서 질문!

여기서 실패처리가 하나는 옵셔널이고 하나는 에러인데 어떤 차이가 있을까요?

2021-04-10 02:26 UTC, Wody95 commented on Expo1900/Expo1900/Models/Items.swift
> +struct Item: Decodable {
* 위 desc, descrtiption 네이밍 코멘트와 같이 쓰는 글입니다 *

desc와 desctiption 네이밍은 json 데이터의 키값과 동일한 이름인데요 :)
item또한 json 파일의 이름이어서 json 파일의 데이터를 decode 해서 동일한 이름으로 네이밍했습니다.

이렇게 json 데이터의 이름과 동일하게 네이밍하는 방법은 현장에서 권장하지 않는 편인가요?

2021-04-10 02:32 UTC, Wody95 commented on Expo1900/Expo1900/Controller/View/ItemsViewController.swift
> +        cell.shortDescLabel.text = items[indexPath.row].shortDesc
제가 "ViewController에서 직접 프로퍼티에 접근해 setup하는 것" 이 문장이 이해되지 않아서 부분적으로 답해보겠습니다 😅

item을 넘겨서 Cell을 setup 하는 것
-> table view에서 cell을 반복적으로 생산하되, 서로 다른 데이터를 표시해주기 위해서 cell의 프로퍼티에 item의 값들을 넘겨주는 것

2021-04-10 02:40 UTC, Wody95 commented on Expo1900/Expo1900/Controller/View/ItemsViewController.swift
> +    func jsonPaser() {
1. 계획
json 데이터를 파싱하는 메서드를 만들려고 했던 이유는 viewDidLoad() 안에서 파싱하는 코드가 지저분해보여 분리하려고 했습니다

2. 과정
메인화면에 사용되는 json 데이터와 출품작 목록 및 상세보기에 사용되는 json 데이터를 파싱하는 두 과정은 상당히 유사해 보였습니다. 그래서 하나의 메소드로 만들어 재사용성을 고려해보았는데요. 문제점 중 하나가 expositionUniverselles의 경우 json 데이터를 파싱 할 때 배열을 사용하지 않았고, items의 경우 배열을 사용해야만 했습니다. 

3. 결론
각 뷰컨트롤러에서 사용되는 json 파일이 고정적이었고 상시로 다른 json 파일을 파싱해야 할 기능이 필요하지 않았기 때문에 매개변수가 없는 메소드로 만들었습니다.

2021-04-10 02:40 UTC, Wody95 commented on Expo1900/Expo1900/Controller/View/ItemsViewController.swift
> +    func jsonPaser() {
메서드는 private 처리를 진행하겠습니다!

2021-04-10 02:48 UTC, Wody95 commented on Expo1900/Expo1900/Controller/View/ViewController.swift
> +            print(error.localizedDescription)
위의 NSDataAsset의 경우 에셋 안에 있는 데이터 중 이름이 동일한 파일을 가져와 사용하기 때문에 
" 이름이 일치하지 않은 = 파일이 없는 = nil의 경우 " 를 위해 옵셔널 처리를 해주었습니다.

에러처리의 경우 jsonDecoder의 정의를 보니까 init 과정에서 throw를 낼 수 있어서 do catch 문을 사용했습니다.

2021-04-10 11:14 UTC, O-O-wl commented on Expo1900/Expo1900/Controller/View/ItemsViewController.swift
> +        cell.shortDescLabel.text = items[indexPath.row].shortDesc
cell에게 item을 전달하고 전달받은 아이템으로 UI요소들에 설정해줄 수 도있다고 생각했어요
cell.textField 가 아닌 cell.configure(with: item)? 과 같은?

2021-04-10 11:20 UTC, O-O-wl commented on Expo1900/Expo1900/Models/Items.swift
> +struct Item: Decodable {
꼭 그런건 아닙니다하지만 JSON에 맞추어야한다고 생각하신 이유가 있을까요? 
다른 JSON 데이터를 제공하는 쪽과 클라이언트간의 권장하는 스타일가이드가 다르다면 꼭 맞추어야할까요?
short_desc라는 네이밍 대신 shortDesc를 채택하신건 스위프트의 가이드라인을 따라가려고 한것 같아서요

2021-04-10 11:21 UTC, O-O-wl commented on Expo1900/Expo1900/Controller/View/ViewController.swift
> +            print(error.localizedDescription)
아하 해당 문법을 사용하신 이유가 아니라 음
왜 어떤 메소드들은 실패처리에 대해 에러를 던지게 되어있고 어떤 메소드는 옵셔널로 실패를 처리하는 걸까? 라는 의문을 가져보셨으면 좋을 것 같아서 던져본 질문이었어요

2021-04-10 11:30 UTC, O-O-wl commented on Expo1900/Expo1900/Controller/View/ItemsViewController.swift
> +    func jsonPaser() {
결론
각 뷰컨트롤러에서 사용되는 json 파일이 고정적이었고 상시로 다른 json 파일을 파싱해야 할 기능이 필요하지 않았기 때문에 매개변수가 없는 메소드로 만들었습니다.

매개변수가 없는 메소드는 테스트에 어려움이 있을 거 같아요
음 이야기가 조금 길것 같긴한데 
현재 ViewController가 가지고 있는 책임은 어떤 것들이 있다고 생각하시는지 정리해볼까요?
또 우디가 생각할 때 중요한 로직이라서 테스트가 있어야할 것 같다고 생각하는 부분도 정리해보면 좋을 것 같아요

당장 어렵게 느껴진다면 넘어가도 좋아요 🙇‍♂️

2021-04-10 14:00 UTC, Wody95 commented on Expo1900/Expo1900/Controller/View/ViewController.swift
> +            print(error.localizedDescription)
```suggestion
        guard let expositionUniversellesData: NSDataAsset = NSDataAsset(name: "exposition_universelle_1900") else {
            return
        }
        do {
            self.expositionUniverselles = try jsonDecoder.decode(ExpositionUniverselle.self, from: expositionUniversellesData.data)
        } catch {
            print(error.localizedDescription)
```

아하! 문법적인 것 이전에 다시 생각해보니까 옵셔널을 통해 데이터를 가져왔을 때 옵셔널이 성공적으로 해제 됐다면 빈 데이터가 아니므로 decode 과정에서 남은건 성공 여부만 남았다고 생각해요 ( nil 값 검증은 guard let을 통해 해결 )

2021-04-10 17:42 UTC, O-O-wl commented on Expo1900/Expo1900/Controller/View/ViewController.swift
> +            print(error.localizedDescription)
음 제가 의도를 잘 전달하지 못한 것 같아요
음 `decode(_, from:)` 메소드는 왜 실패로 Error를 던지고
`NSDataAsset(name: )` 은 생성실패에서 에러를 안던지고 옵셔널타입일까 어떤차이일까? 라는 질문이었어요

2021-04-13 08:21 UTC, Wody95 commented
안녕하세요 붱이! 😊😊😊

지난번 DM으로 말씀드렸던 STEP2 목표 사항 3가지를 다음과 같이 풀어봤습니다.

1. View Controller간 데이터 전달 방법 개선 
>> segue를 이용한 데이터 전달
2. Table View Cell의 데이터 뷰 관리 방법을 cell configure 방식으로 바꿔보기
>> 각 configure 메서드를 통해 아웃렛 관리
3. JSON 데이터 파싱을 타입 생성 시 초기화를 통해 포함시켜보기 
>> CustomJsonFileDecoder 클래스를 만들어 Json Data 파싱하기

그런데 진행 중 1번 segue를 이용한 데이터 전달에서 문제가 생겼는데요,

![expo_gif](https://user-images.githubusercontent.com/44163277/114520406-5e7c1500-9c7c-11eb-96b0-9133e43ebb60.gif)

위 사진에서 알 수 있듯이 ItemDetailViewController에서 네비게이션 층이 하나 더 깊어지는 현상이 발생해버립니다 😂
어떻게 해결하면 좋을까요?

그리고 delegate 패턴을 이용한 뷰 컨트롤러간 데이터 전달 방식은 tableView에서 어떻게 적용해야 할지 감이 오지 않아요...

2021-04-14 12:44 UTC, O-O-wl approved these changes
우디 ! 긴 STEP2를 진행하시느라 고생하셨습니다 
궁금한 부분과 제 의견들 코멘트로 남겼습니다 
머지하고 STEP3에서 같이 또 이야기해보아요🙇‍♂️

2021-04-14 12:44 UTC, O-O-wl commented on Expo1900/Expo1900/Controller/View/ItemDetailViewController.swift
> +    private var detailData: KoreaItems?
접근 제한자를 잘 설정하셨네요!

2021-04-14 12:44 UTC, O-O-wl commented on Expo1900/Expo1900/Controller/View/ItemsViewController.swift
> +        }
이 부분도 메소드로 분리가능하지 않을까요?

2021-04-14 12:44 UTC, O-O-wl commented on Expo1900/Expo1900/Controller/View/ViewController.swift
> +        }
이 부분도 메소드 분리할 수 있으면 고민해볼까요

2021-04-14 12:44 UTC, O-O-wl commented on Expo1900/Expo1900/Models/CustomJsonDecoder.swift
> +    static let jsonDecoder = JSONDecoder()
싱글턴으로 구현하신 이유가 있을까요?

2021-04-14 12:44 UTC, O-O-wl commented on Expo1900/Expo1900/Models/CustomJsonDecoder.swift
> +    static let jsonDecoder = JSONDecoder()
static 메소드만 두는거와 싱글턴은 어떤 차이가 있을까요?

2021-04-14 12:44 UTC, O-O-wl commented on Expo1900/Expo1900/Models/CustomJsonDecoder.swift
> +class CustomJsonDecoder {
더 명시적인 네이밍을 고민해볼까요? 아니면 현재같은 상황이면 extension을 고려해볼수도있었을 것 같아요

2021-04-14 12:44 UTC, O-O-wl commented on Expo1900/Expo1900/Models/ExpoError.swift
> +    case failJsonParser = "파싱에 실패했습니다"
`rawValue`는 어떤 뜻일까요?

2021-04-14 12:45 UTC, merged