[Step2] JM
yagom-academy/ios-exposition-universelle pull request #59
Opened 2021-04-11 12:04 UTC by alwaysblu

@delmaSong  

안녕하세요 [STEP 2] PR 입니다!

# 📌 코드를 작성할 때 고민되었던 점 :

cell을 indexPath.row에 알맞게 지정할 때 modern cell configuration으로 작성하면 더 효율적일까 고민했습니다.

테이블 뷰 셀의 높이가 자동으로 조절되지 않아 여러 시도를 해봤습니다.

## 시도해본 것

* 스토리 보드 TableView Row Height Automatic 체크하기
<img width="264" alt="스크린샷 2021-04-11 오후 8 20 39" src="https://user-images.githubusercontent.com/75533266/114302317-809e5780-9b03-11eb-9181-425c1b2b1f14.png">

* TableViewCell Row Height Automatic 체크하기
<img width="261" alt="스크린샷 2021-04-11 오후 8 22 35" src="https://user-images.githubusercontent.com/75533266/114302396-d246e200-9b03-11eb-9afe-918b95354ded.png">

* TableView의 estimateRowHeight와 rowHeight를 UITableView.automaticDimension으로 설정하기
<img width="1151" alt="스크린샷 2021-04-11 오후 8 24 49" src="https://user-images.githubusercontent.com/75533266/114302483-38336980-9b04-11eb-985c-f19df171110a.png">

* TableView와 TableViewCell AutoLayout 확인하기
<img width="692" alt="스크린샷 2021-04-11 오후 8 27 53" src="https://user-images.githubusercontent.com/75533266/114302527-6f097f80-9b04-11eb-9f5d-655b06fc8cf5.png">

<img width="686" alt="스크린샷 2021-04-11 오후 8 28 32" src="https://user-images.githubusercontent.com/75533266/114302671-fb1ba700-9b04-11eb-8467-767a00d6535e.png">

<br>

### 결과

짤림

<br>

<img width="346" alt="스크린샷 2021-04-11 오후 8 32 57" src="https://user-images.githubusercontent.com/75533266/114302707-256d6480-9b05-11eb-9032-4fb9a839dda6.png">

# 📌 조언을 얻고 싶은 부분 :

테이블 뷰 셀의 높이를 테이블 뷰 셀 콘텐츠 크기에 맞게 동적으로 움직이게 하는 부분에 대해서 조언을 얻고 싶습니다.

2021-04-12 14:54 UTC, delmaSong requested changes
수고하셨습니다👏🏼

### 조언을 얻고 싶다고 하신 부분
> Segue를 이용한 화면 이동 방법과 navigationViewController를 이용한 화면 이동방법의 선택 기준에 대해서 잘모르겠어서 이 부분에 대한 조언을 얻고 싶습니다.

화면 이동 방법 중 Segue를 이용하는 것과 navigationViewController를 이용한 방법에는 각각 어떤 특성과 차이점이 있는지 설명해주실 수 있을까요?

> 하드코딩을 대체하고자 class를 이용하여 상수 테이블을 구현했는데 이 부분이 적절한지에 대해서 조언을 얻고 싶습니다.

아래 코멘트에도 남겨놓았는데, 상수 선언을 위해 여러 타입들(class, struct, enum..)중 왜 struct를 선택하셨는지 그 기준이 궁금합니다(질문은 class를 이용하셨다고 했는데 코드에는 전부 struct를 이용하셨네요)

> 하드코딩을 자제해야한다는 것은 알겠는데 얼마나 자제해야할지 잘모르겠습니다.
상수 테이블을 만들어서 모든 문자열을 대체시키는 것이 가장 좋은 방법인지에 대해서도 조언을 얻고 싶습니다.

모든 값들을 상수로 정의하는 것은 매우 비효율적인 것 같아요. 저는 한번만 호출하고 말 값이라면 따로 타입을 만드는 번거로움도 덜하고, 읽었을 때도 바로 이해되기 때문에 그냥 리터럴하게 사용합니다.
몇 군데에서 여러번 사용하는 값이라면 그 때 상수로 정의하는데, 사용하는 상수들의 집합이 연관성이 있고 여러 객체들에 걸쳐서 사용이 필요할 때 별개의 타입으로 만들고 그렇지 않으면 사용하는 타입에 해당 상수를 정의합니다.

> 테이블뷰 셀 동적 높이

그 전에 테이블뷰 셀에 title과 description 부분을 스택뷰로 구현하셨던데, 왜 스택뷰를 이용하셨는지 궁금합니다. 추가적으로 스택뷰를 사용하기 위한 몇가지 대표적인 특징에 대해 설명해주시면 좋겠습니다.

2021-04-12 14:54 UTC, delmaSong commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +    var tableViewIndex: Int = -1
private(set) 접근제어자에 대해 알아보세요

2021-04-12 14:54 UTC, delmaSong commented on Expo1900/Expo1900/ViewController/MainViewController.swift
> +
viewDidLoad 메서드 안에서 많은 작업을 하기는 하는데
너무 길어지지 않도록 비슷한 작업을 하는 것끼리 별개의 메소드로 분리하면 좋겠습니다

2021-04-12 14:54 UTC, delmaSong commented on Expo1900/Expo1900/ViewController/MainViewController.swift
> +    private func changeNumberFormat(number: Int) -> String {
넘버 포맷을 어떻게 바꾼다는 건지 이름만 보고는 모르겠습니다

2021-04-12 14:54 UTC, delmaSong commented on Expo1900/Expo1900/ViewController/MainViewController.swift
> +        }
Result 타입을 사용하셨군요 👍🏼

2021-04-12 14:54 UTC, delmaSong commented on Expo1900/Expo1900/ViewController/MainViewController.swift
> +        }
다만 `initExpoData`라는 이름은 제너릭과 함께 쓰기에 어울리는 이름은 아닌 것 같군요
또한 데이터를 가져오고 디코딩하는 걸 `init`으로 아우르기에는 무리가 있을 것 같아요

2021-04-12 14:54 UTC, delmaSong commented on Expo1900/Expo1900/ViewController/ExhibitOfKoreaViewController.swift
> +    }
이부분도 몇개의 메소드로 분리할 수 있겠군요

2021-04-12 14:54 UTC, delmaSong commented on Expo1900/Expo1900/ViewController/ExhibitOfKoreaViewController.swift
> +        func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
들여쓰기가 이상해요

2021-04-12 14:54 UTC, delmaSong commented on Expo1900/Expo1900/ViewController/ExhibitOfKoreaViewController.swift
> +
상위 객체가 다 지정해주지 말고 데이터만 전달받고 하위 객체가 알아서 일하도록 만드는 건 어떨까요

2021-04-12 14:54 UTC, delmaSong commented on Expo1900/Expo1900/ViewController/ExhibitOfKoreaViewController.swift
> +
이 뷰컨에서 꼭 `tableViewIndex`를 들고있어야 할까요? 🤔

2021-04-12 14:54 UTC, delmaSong commented on Expo1900/Expo1900/ViewController/MainViewController.swift
> +    @IBAction private func EnterExhibitOfKoreaButton(_ sender: Any) {
대문자

2021-04-12 14:54 UTC, delmaSong commented on Expo1900/Expo1900/Constant/MainScene.swift
> +    static let colon = " : "
너무 과해요
다른 곳에서 (, \n, : 등이 필요하면 매번 구조체를 만들고 상수로 선언해야 하나요?

2021-04-12 14:54 UTC, delmaSong commented on Expo1900/Expo1900/Constant/ExhibitOfKoreaScene.swift
> +    static let tableViewCellNibName = "TableViewCell"
상수 선언을 위해 class, struct, enum.. 타입 중 왜 struct를 선택하셨는지 그 기준이 궁금합니다

2021-04-13 09:07 UTC, alwaysblu commented
# 임시로 작성된 상태입니다.

1. 화면 이동 방법 중 Segue를 이용하는 것과 navigationViewController를 이용한 방법에는 각각 어떤 특성과 차이점이 있는지 설명해주실 수 있을까요?  -> 
2.  아래 코멘트에도 남겨놓았는데, 상수 선언을 위해 여러 타입들(class, struct, enum..)중 왜 struct를 선택하셨는지 그 기준이 궁금합니다(질문은 class를 이용하셨다고 했는데 코드에는 전부 struct를 이용하셨네요) -> enum은 rawvalue를 사용해야해서 class나 struct로 구현하는게 더 낫다고 생각했고 상속할일 없고 값이므로 struct를 선택했습니다. 
3.  그 전에 테이블뷰 셀에 title과 description 부분을 스택뷰로 구현하셨던데, 왜 스택뷰를 이용하셨는지 궁금합니다. 추가적으로 스택뷰를 사용하기 위한 몇가지 대표적인 특징에 대해 설명해주시면 좋겠습니다. ->  계속 잘려서 이것저것 시도해보다가 스택뷰를 사용하게 되었습니다.  스택뷰는 행과 열을 나란히 정렬할 때 많이 사용하고 장점으로는 조작과 조립 그리고 유지보수가 쉽다는 점이 있습니다. 
4.  final 키워드에 대해 알아보세요 🙂 -> final 키워드는 클래스 자체가 상속되는 것을 막거나 클래스가 상속될때 클래스의 특성을 재정의할 수 없게 하기위한 목적으로 사용합니다. final class TableViewCell: UITableViewCell 로 변경했습니다. 
5.  사용하지 않는 메서드는 제거해주세요  -> 제거했습니다. 
6.  String(describing:)에 대해 알아보세요 ->  String(describing:)는 인터폴레이션 불가능한 타입들을 문자열로 변환하는데 사용됩니다.  static let reuseIdentifier = String(describing: TableViewCell.self)로 변경했습니다. 
7.  대문자 -> 변경했습니다. 
8.  private(set) 접근제어자에 대해 알아보세요 -> 읽기 전용으로 구현할때 주로 사용합니다. 즉, setter와 getter의 접근권한을 다르게 할 목적으로 사용합니다. tableViewIndex는 private(set) 으로 선언하면 오류가 발생합니다.  
9.   작업하지 않는 빈 메서드는 제거해주세요 -> 제거했습니다. 
10.  switch 시작에 너무 긴 함수..를 사용하니까 가독성이 떨어지네요🤨 -> let resultOfFetch = fetchExpoData()를 이용해서  긴함수를 대체했습니다. 
11.  viewDidLoad 메서드 안에서 많은 작업을 하기는 하는데 너무 길어지지 않도록 비슷한 작업을 하는 것끼리 별개의 메소드로 분리하면 좋겠습니다 -> initMainSceneData을 이용하여 메소드를 분리했습니다. 
12.  넘버 포맷을 어떻게 바꾼다는 건지 이름만 보고는 모르겠습니다 -> changeNumberDecimalFormat으로 변경했습니다. 
13.  다만 initExpoData라는 이름은 제너릭과 함께 쓰기에 어울리는 이름은 아닌 것 같군요 또한 데이터를 가져오고 디코딩하는 걸 init으로 아우르기에는 무리가 있을 것 같아요 -> fetch cycle 이라는 것을 보고 fetchExpoData라고 naming 했습니다. 
14.  이부분도 몇개의 메소드로 분리할 수 있겠군요 -> initNavigationBar 메소드와  initThingsUsedInTableView 메소드로 분리했습니다. 
15.  들여쓰기가 이상해요 -> 수정했습니다. 
16.  상위 객체가 다 지정해주지 말고 데이터만 전달받고 하위 객체가 알아서 일하도록 만드는 건 어떨까요 ## ->  
17.  이 뷰컨에서 꼭 tableViewIndex를 들고있어야 할까요? 🤔 -> 제 로직에서는 prepare에 선택된 인덱스를 전달해줘야하기 때문에 있어야된다고 생각합니다.  어떤 부분 때문에 관련 질문을 주셨는지 궁금합니다. 
18.  대문자  -> 수정했습니다. 
19.  너무 과해요 다른 곳에서 (, \n, : 등이 필요하면 매번 구조체를 만들고 상수로 선언해야 하나요? -> 저도 좀 과하다고 생각해서 고민하고 있었습니다. 수정했습니다. 
20.  상수 선언을 위해 class, struct, enum.. 타입 중 왜 struct를 선택하셨는지 그 기준이 궁금합니다 ->  enum은 rawvalue를 사용해야해서 class나 struct로 구현하는게 더 낫다고 생각했고 상속할일 없고 값이므로 struct를 선택했습니다. 

2021-04-13 15:13 UTC, alwaysblu commented
리뷰 감사합니다!


1. 화면 이동 방법 중 Segue를 이용하는 것과 navigationViewController를 이용한 방법에는 각각 어떤 특성과 차이점이 있는지 설명해주실 수 있을까요?       

-> Segue는 스토리보드를 이용한다는 특성이 있고 NavigationController는 프로그래밍 방식을 이용한다는 특성이 있습니다. segue를 이용하여 데이터를 전달하는 방법(prepare함수 사용방법)과 NavigationController를 이용하여 데이터를 전달하는 방법(화면 전환할 객체를 생성한 후에 데이터를 초기화하고 해당객체를 push하는 방법 )에서 차이점이 있습니다. NavigationController를 사용할때 Push로 화면을 이동을 시킬지 Segue로 화면이동을 시킬지는 성능상 차이가 없으므로 결국 데이터 이동방식과 StoryBoard를 사용하냐 안하냐의 기준으로 선택하면 될 것 같다는 생각을 했습니다.     

<br>

2.  아래 코멘트에도 남겨놓았는데, 상수 선언을 위해 여러 타입들(class, struct, enum..)중 왜 struct를 선택하셨는지 그 기준이 궁금합니다(질문은 class를 이용하셨다고 했는데 코드에는 전부 struct를 이용하셨네요)    

-> enum은 rawvalue를 사용해야해서 class나 struct로 구현하는게 더 낫다고 생각했고 상속할일 없고 값이므로 struct를 선택했습니다. 

<br>

3.  그 전에 테이블뷰 셀에 title과 description 부분을 스택뷰로 구현하셨던데, 왜 스택뷰를 이용하셨는지 궁금합니다. 추가적으로 스택뷰를 사용하기 위한 몇가지 대표적인 특징에 대해 설명해주시면 좋겠습니다.    

->  계속 잘려서 이것저것 시도해보다가 스택뷰를 사용하게 되었습니다.     
스택뷰는 행과 열을 나란히 정렬할 때 많이 사용하고 장점으로는 조작과 조립 그리고 유지보수가 쉽다는 점이 있습니다. 

<br>

4.  final 키워드에 대해 알아보세요 🙂    
-> final 키워드는 클래스 자체가 상속되는 것을 막거나 클래스가 상속될때 클래스의 특성을 재정의할 수 없게 하기위한 목적으로 사용합니다. final class TableViewCell: UITableViewCell 로 변경했습니다. 

<br>

5.  사용하지 않는 메서드는 제거해주세요  -> 제거했습니다. 

<br>

6.  String(describing:)에 대해 알아보세요    

->  String(describing:)는 인터폴레이션 불가능한 타입들을 문자열로 변환하는데 사용됩니다.  static let reuseIdentifier = String(describing: TableViewCell.self)로 변경했습니다. 

<br>

7.  대문자 -> 변경했습니다. 

<br>

8.  private(set) 접근제어자에 대해 알아보세요 

-> 읽기 전용으로 구현할때 주로 사용합니다. 즉, setter와 getter의 접근권한을 다르게 할 목적으로 사용합니다. tableViewIndex는 private(set) 으로 선언하면 오류가 발생합니다.  

<br>

9.   작업하지 않는 빈 메서드는 제거해주세요 -> 제거했습니다. 

<br>

10.  switch 시작에 너무 긴 함수..를 사용하니까 가독성이 떨어지네요🤨 
-> let resultOfFetch = fetchExpoData()를 이용해서  긴함수를 대체했습니다. 

<br>

11.  viewDidLoad 메서드 안에서 많은 작업을 하기는 하는데 너무 길어지지 않도록 비슷한 작업을 하는 것끼리 별개의 메소드로 분리하면 좋겠습니다
 -> initMainSceneData을 이용하여 메소드를 분리했습니다. 

<br>

12.  넘버 포맷을 어떻게 바꾼다는 건지 이름만 보고는 모르겠습니다.  

 -> changeNumberDecimalFormat으로 변경했습니다. 

<br>

13.  다만 initExpoData라는 이름은 제너릭과 함께 쓰기에 어울리는 이름은 아닌 것 같군요 또한 데이터를 가져오고 디코딩하는 걸 init으로 아우르기에는 무리가 있을 것 같아요    
-> fetch cycle 이라는 것을 보고 fetchExpoData라고 naming 했습니다. 

<br>

14.  이부분도 몇개의 메소드로 분리할 수 있겠군요    
-> initNavigationBar 메소드와  initThingsUsedInTableView 메소드로 분리했습니다. 

<br>

15.  들여쓰기가 이상해요 -> 수정했습니다. 

<br>

16.  상위 객체가 다 지정해주지 말고 데이터만 전달받고 하위 객체가 알아서 일하도록 만드는 건 어떨까요    

 ->  modern cell configuration을 이용해서 하위 객체가 일하도록 하게 하는 방법이 괜찮은 방법일까요? 

<br>

17.  이 뷰컨에서 꼭 tableViewIndex를 들고있어야 할까요? 🤔     
-> 제 로직에서는 prepare에 선택된 인덱스를 전달해줘야하기 때문에 있어야된다고 생각합니다.  어떤 부분 때문에 관련 질문을 주셨는지 궁금합니다. 

<br>

18.  대문자  -> 수정했습니다. 

<br>

19.  너무 과해요 다른 곳에서 (, \n, : 등이 필요하면 매번 구조체를 만들고 상수로 선언해야 하나요?     
-> 저도 좀 과하다고 생각해서 고민하고 있었습니다. 수정했습니다. 

<br>

20.  상수 선언을 위해 class, struct, enum.. 타입 중 왜 struct를 선택하셨는지 그 기준이 궁금합니다     
->  enum은 rawvalue를 사용해야해서 class나 struct로 구현하는게 더 낫다고 생각했고 상속할일 없고 값이므로 struct를 선택했습니다.

2021-04-14 15:20 UTC, delmaSong commented
흑 개별 코멘트에 대한 답글은 해당 쓰레드 답글로 달아주시는게 코드를 비롯해 흐름 파악에 좀 더 용이할 것 같아요 😂 일단 오늘은 이 방식으로 킵고잉

2021-04-14 16:00 UTC, delmaSong reviewed
수고하셨습니다 👏🏼 코드를 보면서 몇가지 코멘트 남겼으니 확인해주셔요

> 상수 선언을 위한 타입

나름의 기준을 가지고 타입을 정한 부분이 좋네요! 앞선 선배들의 고민도 참고해보면 좋을 것 같아 [링크](https://github.com/yagom-academy/ios-signup-flow/pull/25#issuecomment-743993703) 덧붙여요 

> 야곰의 코멘트 중에 "날것의 상수가 코드에서 뛰어놀게 놔두지 않으면 좋겠어요" 란 코멘트가 있는데 어떻게 생각하시는지 궁금합니다.

대답은 제가 이전에 남겼던 코멘트 그대로입니다. JM이 리터럴한 값들을 상수로 선언하는 것은 좋은 시도였다고 생각해요. 모든 값들을 그렇게 만들기보다는 가독성이나 재사용 등을 고려하시면 더 좋을 것 같습니다. 또한 아예 별개의 타입으로 생성할 수도 있겠지만 해당 상수를 사용하는 객체 안에 nested 타입등으로 응집도있게 작성하는 편이 더 좋지 않을까 생각합니다.

*모든 값들을 상수로 정의하는 것은 매우 비효율적인 것 같아요. 저는 한번만 호출하고 말 값이라면 따로 타입을 만드는 번거로움도 덜하고, 읽었을 때도 바로 이해되기 때문에 그냥 리터럴하게 사용합니다.
몇 군데에서 여러번 사용하는 값이라면 그 때 상수로 정의하는데, 사용하는 상수들의 집합이 연관성이 있고 여러 객체들에 걸쳐서 사용이 필요할 때 별개의 타입으로 만들고 그렇지 않으면 사용하는 타입에 해당 상수를 정의합니다.*

> 화면 이동 방식

화면 이동 방식을 선택하는 저의 기준을 말씀드리자면, 설명해주신대로 Segue는 스토리보드를 이용한 경우에만 사용이 가능하기때문에 코드로 뷰를 작성할 일이 많은 저는 Segue는 사용을 안하게 되더라구요. UINavigationViewController를 이용한 화면 이동 방식은 공식 문서에 나와있듯이 네비게이션 컨트롤러를 통해 나타내고자 하는 데이터가 보통 계층적인 데이터니까 해당 뎁스를 표현하기 위해 push/pop 동작을 이용합니다. 그 외에 일시적으로 나타난다거나 계층적이지 않거나 일련의 흐름이 없는 화면이라면 present 방식을 이용해요(사실 보통 기획자의 의도대로 따라갑니다..ㅎ)

> 셀 동적 높이

스택뷰에 대해 질문을 드렸던 건, 구현해주신 셀의 뷰 컴포넌트들의 간격이 부자연스럽다고 느꼈기 때문이었어요.! UIStackView의 axit, distribution, spacing, alignment들은 스택뷰를 다룬다면 의도대로 보여주기 위해서는 거의 필수적으로 설정해줘야하는 요소들이므로 한번 알아보시면 좋을 것 같습니다.

2021-04-14 16:00 UTC, delmaSong commented on Expo1900/Expo1900/ViewController/MainViewController.swift
> +
넘버 포맷팅에 실패하면 화면에는 `방문객 : Failed to change format명`으로 뜨겠군요
리턴타입이 옵셔널이면 어떨까요?

2021-04-14 16:00 UTC, delmaSong commented on Expo1900/Expo1900/ViewController/MainViewController.swift
> +    }
내부에서는 어디서도 ExpoData의 흔적을 볼 수 없어서 좀 더 제너럴한 이름이 어울릴 것 같습니다. setUpData같은? ㅎㅎ

2021-04-14 16:00 UTC, delmaSong commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +            // Put the code you want to measure the time of here.
제거하셨다고 했는데 남아있네요 ..ㅎ

2021-04-14 16:00 UTC, delmaSong commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +        case .success(let data):
앗 이미 ExhibitOfKoreaViewController에서 전체 아이템에 대한 정보를 가지고있지 않은가요? 
여기서 모든 ExhibitItem 배열을 전부 불러올 필요 없이 셀에 해당하는 아이템 하나만 전달받는 식이 좋을 것 같아요

2021-04-14 16:00 UTC, delmaSong commented on Expo1900/Expo1900/Constant/MainScene.swift
> +    static let colon = " : "
아무데서도 사용하지 않는 변수들이 남아있네요

2021-04-14 16:25 UTC, alwaysblu commented on Expo1900/Expo1900/ViewController/MainViewController.swift
> +
~~~
private func changeNumberDecimalFormat(number: Int) -> String? {
        let numberFormatter = NumberFormatter()
        numberFormatter.numberStyle = .decimal
        
        guard let demicalStyleNumber = numberFormatter.string(from: NSNumber(value:number)) else {
            return nil
        }
        
        return demicalStyleNumber
    }
~~~

옵셔널 타입으로 변경했습니다!

2021-04-14 16:26 UTC, alwaysblu commented on Expo1900/Expo1900/ViewController/MainViewController.swift
> +    }
~~~
func setUpData<T: Decodable>(fileName: String, model: T.Type) -> Result<T, DataError> {
        switch loadData(name: fileName) {
        case .success(let data):
            return decodeData(data: data, model: model)
        case .failure:
            return .failure(DataError.loadJSON)
        }
    }
~~~

변수명 추천 감사합니다! 변경했습니다!

2021-04-14 16:29 UTC, alwaysblu commented on Expo1900/Expo1900/ViewController/ExhibitItemViewController.swift
> +        case .success(let data):
~~~
 func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        guard let exhibitItemViewController = self.storyboard?.instantiateViewController(withIdentifier: ExhibitItemViewController.storyboardID) as? ExhibitItemViewController else { return }
        exhibitItemViewController.exhibitItemData = exhibitItem[indexPath.row]
        navigationController?.pushViewController(exhibitItemViewController, animated: true)
    }
~~~

~~~
var exhibitItemData: ExhibitItem?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        guard let exhibitItemData = exhibitItemData else { return }
        self.navigationItem.title = exhibitItemData.name
        exhibitItemImage.image = UIImage(named: exhibitItemData.imageName)
        exhibitItemDescriptions.text = exhibitItemData.descriptions
    }
~~~

아이템 하나만을 전달하는 방식 너무 좋네요 👍 
수정했습니다!

2021-04-14 16:30 UTC, alwaysblu commented
@delmaSong 

리뷰 정말 감사드립니다!

해주신 피드백들 반영해서 업데이트 했습니다!

2021-04-15 00:20 UTC, delmaSong approved these changes
좋습니다! 다음 스텝에서 만나요 🙌🏻

2021-04-15 00:20 UTC, merged