[Step 3] Fezz
yagom-academy/ios-exposition-universelle pull request #62
Opened 2021-04-12 10:25 UTC by Fezravien

# [STEP 3]  Exposition-Universelle 🇰🇷

@seizze 
## 안녕하세요 `하이디` !!! 

#### 드디어 마지막 스텝까지 왔습니다 🥳 

#### `하이디` 덕분에 많이 고쳐보고 이것저것 시도해볼 수 있었어요 감사해요 👍

---

### 새롭게 추가, 수정된 기능 ⚙️ / 조언을 얻고 싶은 부분 👂

1. Dynamic Type 적용, 
   - But... 어느 한계를 넘어가는 `Font size`를 주게되면 라벨이 짤리는 문제가 발생 🤔
   - Font size가 커짐에 따라 이미지를 줄이고 싶어서 `content compression`의 우선순위를 낮게 지정해봤는데.. 아무일도 일어나지 않네요 ,,

<img width="300" alt="스크린샷 2021-04-12 오후 5 18 51" src="https://user-images.githubusercontent.com/44525561/114363449-5e641280-9bb3-11eb-929f-c867fdca5a15.png"><img width="500" alt="스크린샷 2021-04-12 오후 5 19 16" src="https://user-images.githubusercontent.com/44525561/114363470-6459f380-9bb3-11eb-962b-56fb5285472f.png">

<img width="300" alt="스크린샷 2021-04-12 오후 5 19 32" src="https://user-images.githubusercontent.com/44525561/114363473-64f28a00-9bb3-11eb-9178-19dc8398bbd1.png"> <img width="500" alt="스크린샷 2021-04-12 오후 5 19 37" src="https://user-images.githubusercontent.com/44525561/114363485-6623b700-9bb3-11eb-8dd0-075e89fca908.png"> 

<img width="300" alt="스크린샷 2021-04-12 오후 5 19 53" src="https://user-images.githubusercontent.com/44525561/114364837-c6ffbf00-9bb4-11eb-8bb3-98fe8e846329.png"> <img width="500" alt="스크린샷 2021-04-12 오후 5 31 57" src="https://user-images.githubusercontent.com/44525561/114365044-00d0c580-9bb5-11eb-821c-fdb6d4c77592.png">

2. 세로 모드 (footnote ), 가로 모드 (body)
   - 메인 페이지 세로 고정 
   - 이외 가로 세로 변경 가능 
   - 가로 모드로 변경시 폰드 사이즈가 작아 회전시 타입을 변경해주도록 했어요 **(viewWillTransition)**

<img width="300" alt="스크린샷 2021-04-12 오후 5 27 31" src="https://user-images.githubusercontent.com/44525561/114364455-61abce00-9bb4-11eb-988d-aa045ea9dfb6.png"> <img width="450" alt="스크린샷 2021-04-12 오후 5 25 01" src="https://user-images.githubusercontent.com/44525561/114364167-1691bb00-9bb4-11eb-80a5-c623c77392f3.png"> 

<br/>

3. AppDelegate에서 파싱된 데이터 관리

   - 메인에서 출품작 페이지 그리고 디테일 페이지까지 `push`하고, 다시 메인페이지로 `pop` 하는 과정을 반복하면서 뷰 컨트롤러가 생성될 때마다 파싱해서 변수에 저장하는 일을 반복한다고 생각했어요. 그래서 앱의 시작과 끝에 있는 AppDelegate에 변수를 지정해서 프로그램이 꺼지기 전까지 파싱은 한 번만 진행되도록 수정해봤어요. (물론 JSON 데이터가 바뀐다면 다시 파싱을 해야됩니다 ! 하지만 지금은 정적인 데이터를 기준으로 구현했어요)

   <br/>

4. Step 1 에서 했어야 했지만 Unit Test를 했봤어요 !

   <br/>

5. 약간의 과제(?)를 주신 부분 

   - `static` 메소드를 활용해서 수정했는데 하이디가 말씀해주신게 이게 맞을까요 ?

   <br/>

6. 오류처리를 Result 타입으로 수정했어요 

   <br/>

7. > 음... 어떤 구조로 나눴는지 구체적인 의도를 설명해 주시면 좋을 것 같아요. 😅
   > 먼저 대분류로 Extension, Storyboard, Error, ViewController를 나눈 이유가 궁금해요. MVC 별로 나누신 건가요?

   제가 구체적으로 말씀드리지 못했어요 😢😢

   저는 **MVC** 로 파일 구조를 생성해봤어요 !! 

`Model` : Expo, StateEntry

`ViewController` : ExpoViewController, KoreaEntryViewController, KoreaDetailEntryViewControler

<br/>

8. UML Diagram
   - 아직 의존관계, 연관 관계를 나누는 것이 명확하지 못하지만, 우선 제가 생각하는 방식대로 작성해봤어요! 

<img src="https://user-images.githubusercontent.com/44525561/114377943-2c0de180-9bc2-11eb-8625-d807fecd5e3f.jpg" alt="UML Diagram" style="zoom: 200%;" />

2021-04-13 15:13 UTC, seizze requested changes
Fezz~! 수고 많으셨습니다. 🚀 
코멘트 확인 부탁드리고, 아래는 코멘트 주신 사항에 대한 의견입니다.

> 1. Dynamic Type 적용

![image](https://user-images.githubusercontent.com/49332230/114575851-8dfb4380-9cb5-11eb-87e5-38a9063d5510.png)

레이블이 짤리는 문제는 뭔가 버그 같은데, 위 이미지처럼 개최기간 레이블의 Lines를 0으로 줘서 다음 줄로 넘어갈 수 있도록 해 주면 짤리지 않네요~

<img width="300" alt="image" src="https://user-images.githubusercontent.com/49332230/114575681-62785900-9cb5-11eb-9991-9914a780e95e.png">

<img width="300" alt="image" src="https://user-images.githubusercontent.com/49332230/114575805-7fad2780-9cb5-11eb-89e2-64c0e2ed2654.png">

content compression이 여기서 Vertical 값을 낮게 지정했다는 말이죠?
Content compression resistance priority는 그럴 때 쓰는게 아니고, 한정된 공간이 있는 상태에서 누가 줄어들지를 결정하는 순위입니다.
지금은 스크롤뷰에 있으니 한정된 공간이 아니고, 아래로 늘어날 수 있어서 이미지가 줄어들지 않아요.
이미지가 줄어들게 하고 싶다면 여러 방법이 있겠지만 스택뷰 등을 사용해서 이미지+레이블이 가질 수 있는 한정된 공간을 지정해주면 이미지가 레이블이 커짐에 따라서 작아질 겁니다.

> 3, 4, 5

코멘트 참조해 주세요!
특히 AppDelegate 관련하여 드린 링크는 꼭 읽어보세요.

> 7. 디렉토리 구조

KoreaEntryViewController, KoreaDetailEntryViewController는 스토리보드와 함께 있는데 ExpoViewController는 스토리보드와 함께 있지 않은점이 일관되지 않아 보입니다. 이 점이 개선되면 좋을 것 같아요 :)

2021-04-13 15:13 UTC, seizze commented on Expo1900/Expo1900/VIewController/Entry/Korea/KoreaDetailEntryViewController.swift
>      }
아래 링크에서 The App Delegate Source File 부분을 반드시 읽어보세요.
https://developer.apple.com/library/archive/referencelibrary/GettingStarted/DevelopiOSAppsSwift/BuildABasicUI.html

2021-04-13 15:13 UTC, seizze commented on Expo1900/Expo1900/VIewController/Entry/Korea/KoreaDetailEntryViewController.swift
> +    private var appDelegate = UIApplication.shared.delegate as? AppDelegate
이런 식으로 상위 방향으로 참조를 가지는 것은 순환 참조 관계가 발생하지 않을지 반드시 생각해 봐야 합니다.
여기서도 발생할 것으로 추측이 되네요

2021-04-14 06:55 UTC, Fezravien commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +    }
`하이디` 말씀대로 NSDataAsset에 오류를 넣어도 성공으로 작동하는 문제가 있었네요 😲
```swift
func test_KoreaEntryTitle() {
        guard let assetData = NSDataAsset(name: "items") else {
            XCTAssert(false)
            return
        }
        do {
            let data = try decoder?.decode([StateEntry].self, from: assetData.data)
            XCTAssertEqual(data?.first?.name, "직지심체요절")
        } catch {
            print(error.localizedDescription)
            XCTAssert(false)
        }
    }
```

오류가 났을때 호출되는 분기(NSDataAsset, error handler)에 `XCTAssert(false)`을 추가했어요 !

2021-04-14 07:09 UTC, Fezravien commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +    }
🙆‍♂️

2021-04-16 05:11 UTC, Fezravien commented on Expo1900/Expo1900/VIewController/Entry/Korea/KoreaDetailEntryViewController.swift
>      }
가로, 세로 모드를 판단해서 글씨 크기를 바꿔주기 위해서 사용해봤는데.. 사실 없어도 상관없다고 생각해요 !
제가 이렇게 해놓은 이유는 가로모드로 변경시 폰트 크기가 작아서 가로, 세로 모드마다 변경시켜주고 싶었어요 🤔 
그렇게 하기 위해서는 `viewWillTransition` 으로 모드가 바뀔때마다 호출되는 메소드를 사용해야 될 것 같아서 사용했는데 다른 방법이 있을까요?

2021-04-16 09:09 UTC, Fezravien commented on Expo1900/Expo1900/VIewController/Entry/Korea/KoreaDetailEntryViewController.swift
>      }
> 저는 화면 전환 기능도 해당 화면이 담당해 처리하는 방식이 맞다고 생각하는데 어떤가요?

`하이디` 말씀이 맞다고 생각해요! 근데 저부분이 가로, 세로 모드가 변경됨에 따라 호출 되는 부분이라 어떻게 화면이 담당하도록 해야될지 모르겠어요. 이 부분은 따로 싱글톤을 생성해서 다루도록 해야되나요 ?

2021-04-16 09:19 UTC, Fezravien commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +            XCTAssertEqual(data?.title, "파리 만국박람회 1900(L'Exposition de Paris 1900)")
Equatable 을 사용해서 
```swift
func test_만국박람회_메인페이지_디코더_확인() {
        let assetData = NSDataAsset(name: "exposition_universelle_1900")
        XCTAssertNotNil(assetData)
        let data = try! decoder?.decode(Expo.self, from: assetData!.data)
        XCTAssertEqual(data!, Expo(title: "파리 만국박람회 1900(L'Exposition de Paris 1900)", visitors: 48130300, location: "프랑스 파리", duration: "1900. 04. 14 - 1900. 11. 12", description: "1900년 파리 만국박람회(지금의 세계 박람회[World’s
Fair/Exposition/Expo])는 지난 세기를 기념하고 다음 세기를 향한 발전을 가속하자는 의미에서 1900년 4월 14일부터 11월 12일까지 프랑스 파리에서 열린 세계 박람회였다. 이 박람회에서 널리 선보였던 건축 양식이 바로 '아르누보'였다. 총 관람객수가 5000만 명에 달한 1900년 세계 박람회에서는 수많은 기계와 발명품, 그리고 건축물들이 전시됐는데 그 중에는 그랑드 루 드 파리 대관람차, 마트료시카 인형, 디젤 엔진, 유성영화, 에스컬레이터, 텔레그라폰 (최초의 자석식 녹음기) 등 지금도 널리 알려져 있는 것들도 등장했다.\n\n프랑스는 1855년에도 만국 박람회를 개최한 전력이 있었는데 전쟁 후 국가의 자부심과 신념을 다시 세우고자 하는 욕구로부터 비롯된 것이었다. 1900년 박람회가 성공을 거둔 것도 전후 국가 부흥이라는 똑같은 주제에 따른 것이었다. 1900년 파리 세계 박람회가 개최되기 8년 전인 1892년, 프랑스 정부는 새 세기의 도래를 환영하고 축하하는 박람회를 열 것이라고 발표했다.\n\n프랑스는 전세계 56개국에 초청장을 보냈고, 그 중 40개국이 수락하여 참가했다.참가국들이 이룬 것과 생활양식을 전시했다. 이 세계 박람회는 여러 가지 체험을 종합하여 익히도록 한 것이었다. 이를 통해 외국인들에게 각 국가들 간의 유사성은 물론 그 사이의 독특한 다양성을 깨닫도록 하는 기회를 제공했다. 또 새로운 문화를 경험하고 각국이 전시해 놓은 자국의 가치들을 전반적으로 더욱 이해할 수 있도록 했다. 이러한 상호 이해의 환경이 전쟁 시대 이후 필요하다고 여겨졌던 문화적 관용을 늘리는데 한몫하도록 했다. 박람회 개최 소식이 발표되자 독일에서 처음으로 열린 국제 박람회에 쏠렸던 관심은 풀리고 박람회 개최에 대한 호응이 어마어마하게 쏟아졌다. 박람회에 대한 지지도 대단해서 각국에서는 즉시 자국 전시관 계획을 세우기 시작했다. \n\n파리 만국박람회가 개최된 1900년 4월 14일부터 11월 12일까지 프랑스 파리에는 대한제국의 문화와 문물이 전시된 한국관이 세워졌습니다. 한국관은 경복궁의 근정전을 재현한 주전시관과 옛 국왕들의 위패를 모셔놓은 사당을 별채로 구성되었는데, 이는 우리 건축의 아름다움을 세계에 알린 첫 건축물이 되었습니다. 특히 만국박 람회의 대한제국관을 묘사한 프랑스 잡지 ‘르 프티 주르날(Le Petit Journal)’은 태극기를 표시해 당당하게 대한 제국의 상징으로 많은 관심을 받을 수 있었습니다.\n\n한국관의 전시품은 정확하게 어떤 것이 전시되었는지 알 수는 없지만 대한제국과 프랑스 정부간에 오고 간 문 서를 통해 짐작할 수 있습니다. 대한제국 정부는 우리의 다양한 전통문화를 나타내는 비단, 놋그릇, 도자기, 칠 보 등의 공예품을 제공한 것으로 보이며, 이 밖에도 악기, 옷, 가구, 예술품 등도 있었다고 합니다. 만국박람회는 참가한 나라들의 산업을 소개하는 역할을 했고, 전시는 물론 시상도 했는데 대한제국은 식물성 농업식품 분야 에서 그랑프리(대상)을 수상하였다고 합니다.\n\n1900년 11월 12일 파리 만국박람회가 폐막된 후 한국관에 출품되었던 전시품들은 다시 본국으로 돌아오지 못하고 대부분 현지에 기증되었는데, 이는 일종의 관례이기도 했지만 본국으로 회수하는데 드는 과도한 운송비용 때문이기도 했습니다.\n\n현재 이 전시품들은 프랑스에 있는 국립공예박물관, 국립예술직업전문학교, 국립음악원 음악박물관, 국립 기메 아시아박물관 등에 소장되어있습니다. 특히 전시품으로 기증된 악기들 중 해금은 현존하는 해금 가운데 가장 오래된 것으로 추정되고 있다고도 합니다. 우리의 소중한 역사적 유물을 멀리 두고 올 수 밖에 없던 상황이 안타깝게 느껴집니다.\n\n작고 힘없는 나라 대한제국이 세계 강국들이 모인 만국박람회에 참가한다는 자체가 불가능하다는 의견이 지배 적이었지만 1900년 프랑스 파리에 근정전을 본뜬 한국관이 우뚝 세워졌습니다. 그 존재만으로 독립된 나라임을 세계에 알리고자 했던 목표는 이루어진 것 같습니다. 그러나 안타깝게도 그로부터 5년 후인 1905년 을사늑약이 체결되었고, 대한제국은 독립국가로서 세계에서 점점 잊혀져 갔습니다."))
        
    }
```

이렇게 `description ` 긴 부분을 다 넣는거라면 `koreaEntry`의 배열을 전부다 써서 비교할 수 없을탠데 어떻게 비교를 해야될지 모르겠어요.

2021-04-16 09:20 UTC, Fezravien commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +    func test_ExpoLocation() {
🙆‍♂️

2021-04-16 09:21 UTC, Fezravien commented on Expo1900/Expo1900/VIewController/Cell/KoreaEntryTableViewCell.swift
>      @IBOutlet private weak var entryImage: UIImageView!
수정했어요! 🙆‍♂️

2021-04-16 09:21 UTC, Fezravien commented on Expo1900/Expo1900/VIewController/Entry/Korea/KoreaEntryViewController.swift
> +        static let cellIdentifier = "KoreaEntryCell"
수정했어요 🙆‍♂️

2021-04-16 09:36 UTC, Fezravien commented on Expo1900/Expo1900/VIewController/Entry/Korea/KoreaDetailEntryViewController.swift
>      }
자료 잘 읽었어요! 
이 부분을 해결하기 위해서 의존성 역전의 원칙, 단일 책임 원칙을 생각해봤어요 
1. `ModelManager` 를 통해 데이터를 관리하는 싱글톤을 만들었어요 (단일 책임 원칙)
2. `OrientationMask` 을 통해 뷰 컨트롤러에서 app delegate에 직접 접근하지 못하게 했어요 (의존성 역전 원칙)
이 부분에서 의존성 역전 원칙이 이해가 안가는 부분이 있어요! 다음 PR에서 궁금한 부분을 정리해볼게요 !

2021-04-16 10:15 UTC, Fezravien commented on Expo1900/Expo1900/VIewController/Entry/Korea/KoreaDetailEntryViewController.swift
> +    private var appDelegate = UIApplication.shared.delegate as? AppDelegate
직접적으로 호출하는 부분을 수정했어요 

> 상위 방향으로 참조를 가지는 것은 순환 참조 관계가 발생

이 부분은 AppDelegate가 앱의 생명주기를 다루니까 이미 참조되서 한번 더 참조를 하니까 발생되는 상황일까요 ?

2021-04-16 10:18 UTC, seizze commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +            XCTAssertEqual(data?.title, "파리 만국박람회 1900(L'Exposition de Paris 1900)")
앗...그러네요. 제가 여기까지 생각하지 못했어요 ㅠㅠ

2021-04-16 11:11 UTC, Fezravien commented
# [STEP 3] Exposition-Universelle - 2 🇰🇷

---
@seizze 
### 안녕하세요 `하이디` !!!
피드백 주신 부분 한참 생각하다보니... PR이 조금 늦어졌네요 ㅎㅎ
최대한 반영해 보려고 했어요! 하지만 명확하게 이해안된 부분도 있어요 🤔
덕분에 많은 생각을 해볼 수 있었어요 감사합니다 `하이디` !!

1. AppDelgate 

- `AppDelgate ` 는 앱의 전체 라이프 사이클에 해당하는 기능을 담당한다.

  제가 이 부분에 데이터를 저장하고, 가로 세로 모드의 상태 변수를 해놨었는데 `하이디`가 올려주신 문서를 확인하고 수정할 수 있는 방법을 생각해봤어요.

  - `ModelManager` 를 통해 데이터를 관리하는 싱글톤을 만들었어요 (단일 책임 원칙)

  ```swift
  final class ModelManager {
      static let shared = ModelManager()
      
      var koreaEntrys: [StateEntry] = []
      var detailEntry: StateEntry?
      var expoData: Expo?
      
      private init() { }
  }
  ```

  

  - `OrientationMask` 을 통해 뷰 컨트롤러에서 app delegate에 직접 접근하지 못하게 했어요 (의존성 역전 원칙)

  ```swift
  protocol OrientaionMakeable {
      static var shared: OrientaionMake { get set }
      func judgedOrientaionMake(_ isPortrait: Bool)
      func isOrientaionMake() -> Bool
  }
  
  final class OrientaionMake: OrientaionMakeable {
      static var shared = OrientaionMake()
      private var shouldSupportAllOrientation = true
      
      private init() { }
      
      func judgedOrientaionMake(_ isPortrait: Bool) {
          if isPortrait == true {
              shouldSupportAllOrientation = true
          } else {
              shouldSupportAllOrientation = false
          }
      }
      
      func isOrientaionMake() -> Bool {
          return shouldSupportAllOrientation
      }
  }
  
  // AppDelegate
  class AppDelegate: UIResponder, UIApplicationDelegate {
      private var orientation: OrientaionMakeable = OrientaionMake.shared
      
      func application(_ application: UIApplication, supportedInterfaceOrientationsFor window: UIWindow?) -> UIInterfaceOrientationMask {
          if orientation.isOrientaionMake() {
              return UIInterfaceOrientationMask.all
          } else {
              return UIInterfaceOrientationMask.portrait
          }
      }
  }
  ```

  제 생각은 `ViewControll`에서 `AppDelegate`에 직접 접근하는 것을 `OrientaionMake` 싱글톤 객체를 통하는 방식으로 수정하여 의존성을 `OrientaionMakeable` 프로토콜에 두는 것이 의존성 역전의 원칙이 아닐까 생각했어요.

  

  제가 생각한 의존성 역전의 원칙은

  ```
  상위에 있는 객체가 하위에 있는 객체에 의존하면 코드에 변경이 있을때 변화가 많아서
  "자신보다 변하기 쉬운 것에 의존하면 안된다" 이기 때문에 
  자신보다 변하기 쉬운 것에 의존하던 것을 의존성을 역전시켜(?) 변하기 쉬운 상태에 영향을 받지 않게 하는 것
  이렇게 이해하고 있어요 !
  ```

  이 부분에서 프로토콜을 통해 의존성을 싱글톤 객체와 분리했고,  `AppDeleate`의 `orientation`에 의존성 주입을 했어요. 

  여기서 의문이 들었던 점은 ViewControll가 직접 접근하는 것을 피하기 위해 새로운 싱글톤 패턴을 만들어서 의존성을 수정했는데 왜 프로토콜에 의존성을 줘야 하는지 잘 이해가 가지 않아요 😢

  

  이렇게 수정한 방법이 옳은 방향인가요 ? 하이디의 생각이 궁금해요 !

  <br/>

2. Unit Test 

> title 만 비교하면 될까요? ㅎㅎ Expo, StateEntry 등에 Equatable을 구현해서 인스턴스 자체를 비교해 보세요.

​	비교하기 위해서 `Equatable` 을 구현했어요 

​	문제점은 

```swift
func test_만국박람회_메인페이지_디코더_확인() {
        let assetData = NSDataAsset(name: "exposition_universelle_1900")
        XCTAssertNotNil(assetData)
        let data = try! decoder?.decode(Expo.self, from: assetData!.data)
        XCTAssertEqual(data!, Expo(title: "파리 만국박람회 1900(L'Exposition de Paris 1900)", visitors: 48130300, location: "프랑스 파리", duration: "1900. 04. 14 - 1900. 11. 12", description: "1900년 파리 만국박람회(지금의 세계 박람회[World’s Fair/Exposition/Expo])는 지난 세기를 기념하고 다음 세기를 향한 발전을 가속하자는 의미에서 1900년 4월 14일부터 11월 12일까지 프랑스 파리에서 열린 세계 박람회였다. 이 박람회에서 널리 선보였던 건축 양식이 바로 '아르누보'였다. 총 관람객수가 5000만 명에 달한 1900년 세계 박람회에서는 수많은 기계와 발명품, 그리고 건축물들이 전시됐는데 그 중에는 그랑드 루 드 파리 대관람차, 마트료시카 인형, 디젤 엔진, 유성영화, 에스컬레이터, 텔레그라폰 (최초의 자석식 녹음기) 등 지금도 널리 알려져 있는 것들도 등장했다.\n\n프랑스는 1855년에도 만국 박람회를 개최한 전력이 있었는데 전쟁 후 국가의 자부심과 신념을 다시 세우고자 하는 욕구로부터 비롯된 것이었다. 1900년 박람회가 성공을 거둔 것도 전후 국가 부흥이라는 똑같은 주제에 따른 것이었다. 1900년 파리 세계 박람회가 개최되기 8년 전인 1892년, 프랑스 정부는 새 세기의 도래를 환영하고 축하하는 박람회를 열 것이라고 발표했다.\n\n프랑스는 전세계 56개국에 초청장을 보냈고, 그 중 40개국이 수락하여 참가했다.참가국들이 이룬 것과 생활양식을 전시했다. 이 세계 박람회는 여러 가지 체험을 종합하여 익히도록 한 것이었다. 이를 통해 외국인들에게 각 국가들 간의 유사성은 물론 그 사이의 독특한 다양성을 깨닫도록 하는 기회를 제공했다. 또 새로운 문화를 경험하고 각국이 전시해 놓은 자국의 가치들을 전반적으로 더욱 이해할 수 있도록 했다. 이러한 상호 이해의 환경이 전쟁 시대 이후 필요하다고 여겨졌던 문화적 관용을 늘리는데 한몫하도록 했다. 박람회 개최 소식이 발표되자 독일에서 처음으로 열린 국제 박람회에 쏠렸던 관심은 풀리고 박람회 개최에 대한 호응이 어마어마하게 쏟아졌다. 박람회에 대한 지지도 대단해서 각국에서는 즉시 자국 전시관 계획을 세우기 시작했다. \n\n파리 만국박람회가 개최된 1900년 4월 14일부터 11월 12일까지 프랑스 파리에는 대한제국의 문화와 문물이 전시된 한국관이 세워졌습니다. 한국관은 경복궁의 근정전을 재현한 주전시관과 옛 국왕들의 위패를 모셔놓은 사당을 별채로 구성되었는데, 이는 우리 건축의 아름다움을 세계에 알린 첫 건축물이 되었습니다. 특히 만국박 람회의 대한제국관을 묘사한 프랑스 잡지 ‘르 프티 주르날(Le Petit Journal)’은 태극기를 표시해 당당하게 대한 제국의 상징으로 많은 관심을 받을 수 있었습니다.\n\n한국관의 전시품은 정확하게 어떤 것이 전시되었는지 알 수는 없지만 대한제국과 프랑스 정부간에 오고 간 문 서를 통해 짐작할 수 있습니다. 대한제국 정부는 우리의 다양한 전통문화를 나타내는 비단, 놋그릇, 도자기, 칠 보 등의 공예품을 제공한 것으로 보이며, 이 밖에도 악기, 옷, 가구, 예술품 등도 있었다고 합니다. 만국박람회는 참가한 나라들의 산업을 소개하는 역할을 했고, 전시는 물론 시상도 했는데 대한제국은 식물성 농업식품 분야 에서 그랑프리(대상)을 수상하였다고 합니다.\n\n1900년 11월 12일 파리 만국박람회가 폐막된 후 한국관에 출품되었던 전시품들은 다시 본국으로 돌아오지 못하고 대부분 현지에 기증되었는데, 이는 일종의 관례이기도 했지만 본국으로 회수하는데 드는 과도한 운송비용 때문이기도 했습니다.\n\n현재 이 전시품들은 프랑스에 있는 국립공예박물관, 국립예술직업전문학교, 국립음악원 음악박물관, 국립 기메 아시아박물관 등에 소장되어있습니다. 특히 전시품으로 기증된 악기들 중 해금은 현존하는 해금 가운데 가장 오래된 것으로 추정되고 있다고도 합니다. 우리의 소중한 역사적 유물을 멀리 두고 올 수 밖에 없던 상황이 안타깝게 느껴집니다.\n\n작고 힘없는 나라 대한제국이 세계 강국들이 모인 만국박람회에 참가한다는 자체가 불가능하다는 의견이 지배 적이었지만 1900년 프랑스 파리에 근정전을 본뜬 한국관이 우뚝 세워졌습니다. 그 존재만으로 독립된 나라임을 세계에 알리고자 했던 목표는 이루어진 것 같습니다. 그러나 안타깝게도 그로부터 5년 후인 1905년 을사늑약이 체결되었고, 대한제국은 독립국가로서 세계에서 점점 잊혀져 갔습니다."))
    }
```

메인 페이지의 JSON 파싱은 길지만 한 개만 존재해서 이렇게 비교할 수 있었는데, `KoreaEntry` 부분의 `[StateEntry]` 부분은 배열을 전부 다 객체를 생성해서 비교하는 것에는 무리가 있지 않을까 해서 어떻게 테스트를 진행해야 될지 궁금해요 🤔



<br/>`VIewController`에 `private`로 존재하는 메소드들은 어떻게 테스트를 진행하는 것인지, 아니면 코드가 `Testable` 하지 않아서 테스트를 못하는 것인지 궁금해요 

### 그리고 테스트 코드, `Testable` 한 로직을 어떤식으로 작성해야 될지도 궁금해요 🤔 (방법?)

```swift
// ExpoViewController
private func creatVisitorsComma(_ visitors: UInt) -> String {
        let numberFormatter = NumberFormatter()
        numberFormatter.numberStyle = .decimal
        guard let decimalStyleValue = numberFormatter.string(from: NSNumber(value: Int(visitors))) else {
            return String(visitors)
        }
        return decimalStyleValue
 }

private func initExpoData() throws -> Result<Expo, ExpoError> {
        guard let dataAsset = NSDataAsset(name: Constant.expoJson) else {
            return .failure(ExpoError.expoData)
        }
        return .success(try JSONDecoder().decode(Expo.self, from: dataAsset.data))
    }
```



3. 화면 동작 

> 저는 화면 전환 기능도 해당 화면이 담당해 처리하는 방식이 맞다고 생각하는데 어떤가요?
> 이 화면이 동작하기 위한 기능이 이렇게 여러 곳에 분산되어 있으면, 나중에 이 화면에 이슈가 생겨서 다른 사람이 이 코드를 보고 이해하려 할 때 수월할까요?

```swift
private let orientaionMask = OrientaionMake.shared 

override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        if orientaionMask.isOrientaionMake() {
            orientaionMask.judgedOrientaionMake(true)
            descriptionLable.font = UIFont.preferredFont(forTextStyle: .footnote)
        } else {
            orientaionMask.judgedOrientaionMake(false)
            descriptionLable.font = UIFont.preferredFont(forTextStyle: .body)
        }
    }
```

<img width="300" alt="스크린샷 2021-04-12 오후 5 27 31" src="https://user-images.githubusercontent.com/44525561/114364455-61abce00-9bb4-11eb-988d-aa045ea9dfb6.png"> <img width="500" alt="스크린샷 2021-04-12 오후 5 25 01" src="https://user-images.githubusercontent.com/44525561/114364167-1691bb00-9bb4-11eb-80a5-c623c77392f3.png">

3 번째 디테일 화면에서 가로, 세로 모드 변경할 때마다 알 수 있도록 `viewWillTransition`를 사용해서 모드가 변경될 때 마다 폰트도 변경되도록 사용했는데 `하이디`가 말씀해주신 **"화면 전환 기능도 해당 화면이 담당해 처리하는 방식"** 이 부분이 잘 이해되지 않았어요 😢  



5. 순환 참조 

> 상위 방향으로 참조를 가지는 것은 순환 참조 관계가 발생하지 않을지 반드시 생각해 봐야 합니다.
> 여기서도 발생할 것으로 추측이 되네요

```swift
private var appDelegate = UIApplication.shared.delegate as? AppDelegate
```

`AppDelegate`가 뷰의 라이프 사이클을 담당하는데 제가 다시 싱글톤으로 뷰 컨트롤러에서 상위 방향의 참조를 가져오게되서 순환 참조 관계가 발생하는 걸까요?

--- 
`하이디`는 스토리보드로 작성할때 속성을 스토리보드내에서 주시나요 아니면 따로 코드로 속성을 주시나요 ?

저는 어떤게 넣었는지 해깔릴때가 있어서 특정 속성은 코드로 명시해줬어요 
```swift 
private func setLabelAttribute() {
        expoTitleLabel.numberOfLines = 2
        expoTitleLabel.textAlignment = .center
        expoTitleLabel.adjustsFontSizeToFitWidth = true
        
        visitorsLabel.numberOfLines = 0
        visitorsLabel.textAlignment = .center
        visitorsLabel. [...]

2021-04-17 09:20 UTC, seizze commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +    }
오잉 `try!`를 쓰다니.. 디코딩이 실패하면 테스트가 실패하는게 아니라 그냥 크래시가 나겠는데요?

"테스트가 실패한 것"과 "테스트에서 크래시가 나는 것"의 차이는 뭘까요? 테스트가 실패한 건 프로덕트 코드가 잘못되었다는 뜻이고, 테스트에서 크래시가 나는건 테스트 코드를 잘못 작성한 것입니다. 이 둘의 차이가 뭔지를 고민해 보고 디코딩 실패 시 테스트가 실패하도록 수정해 보세요.

2021-04-17 09:20 UTC, seizze commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +    }
위 코멘트를 참고하셔서 여기도 수정해 보세요!

2021-04-17 09:20 UTC, seizze commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +        let data = try! decoder?.decode([StateEntry].self, from: assetData!.data)
근데 여기서 리턴값을 사용하지 않았다는 warning이 뜨지 않나요? 경고 표시가 나는 것을 그대로 두면 안됩니다. 이 상태로 프로젝트가 커지고, 워닝이 계속 쌓이면 중요한 워닝도 묻혀서 놓치게 됩니다. 간단하게는 다음과 같이 워닝을 지울 수 있습니다.
```swift
_ = try! decoder?.decode([StateEntry].self, from: assetData!.data)
```

2021-04-17 09:20 UTC, seizze commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +        let data = try! decoder?.decode([StateEntry].self, from: assetData!.data)
아 코멘트를 보니 StateEntry에 Equatable을 채택해서 이용하려다가 어떻게 할지 몰라서 그냥 둔 것 같네요 ㅎㅎ

여기선 어쩔 수 없이 Expo, StateEntry 모두 일부만 비교해야 할 것 같아요 😢

2021-04-17 09:48 UTC, Fezravien commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +        let data = try! decoder?.decode([StateEntry].self, from: assetData!.data)
맞아요 Equatable을 채택해서 이용해보려고 했는데 이 부분은 배열이라 전부 쓸 수도 없고 어떻게 해야될까 싶어서 진행이 멈췄어요 ㅎㅎ
배열의 첫 번째만 확인해볼게요 !! 

이번 PR에 작성했지만, 디코더 부분 테스트 말고 다른 부분을 테스트 할 수 있는 방법이 있을까요? 🤔

2021-04-18 08:36 UTC, seizze reviewed
아 어제 리뷰를 하던 도중에 제출을 안하고 껐는데 제출이 되어버렸네요 😅
추가로 마무리해서 올립니다 ㅎㅎ 제가 빼먹은게 있다거나 이해 안가는 내용이 있다면 언제든지 DM이나 추가 코멘트 주세요~!
그리고 다음 주는 방학이니, 수정하고 싶다면 추가로 커밋해서 올려주시고 머지하고 싶다면 알려주세요~~

아래는 코멘트에 남겨주신 내용에 대한 제 의견입니다.

------------

### 1. ModelManager, OrientationMask

ModelManager는 관련 부분에 코멘트 남겼으니 확인해 주세요~

의존성 역전 원칙에 대해서는, 이런 개념들에 대해 알아보고 적용하려 시도한 점은 좋습니다. 하지만, 이번 경우에서는 조금 적용하기가 적절하지 않은 경우 같아요. 그리고 AppDeleate의 orientation에 의존성 주입을 하셨다는 부분도 원래는 외부에서 주입해줘야 하는 부분인데, App Delegate는 자동으로 생성되는 인스턴스라 그러기가 힘들 것 같고요..
개발하면서 자주 쓰이는 패턴이니, 다음 프로젝트들에서 이 원칙을 적용하기 적절한 예제가 나올거에요. 그때 다시 적용해 보고 명확히 이해하는 게 좋을 것 같습니다.ㅎㅎ

화면 회전 기능을 분리한 내용에 대해서도, 이전 코멘트에다가 답변 남겼으니 참고해 주세요!

### 2. Unit Test

관련 코멘트 남겼습니다~!
현재 View Controller에 있는 private 메서드들은 지금은 테스트가 힘들 것 같고, 나중에 뷰모델이란 걸 만들면 이렇게 뷰에 값을 표시하기 위한 로직들도 테스트할 수 있게 됩니다. (참고만 하세요!)
그리고 private 메서드의 테스트에 관한 내용은 여기 글이 정말 좋으니 한번 읽어보세요~ https://www.slipp.net/questions/253

### 3. 화면 회전 & 5. 순환 참조

이 부분에 대해서도 이전 코멘트에 답변 남겼으니 확인해 주세요~ ☺️

### 속성 설정

저는 코드엔 최대한 비즈니스 로직만 있는걸 선호해서 속성 설정은 스토리보드에서 합니다. ㅎㅎ 이건 취향 차이라고 생각해요~

2021-04-18 08:37 UTC, seizze commented on Expo1900/Expo1900/VIewController/Entry/Korea/KoreaDetailEntryViewController.swift
> +    private var appDelegate = UIApplication.shared.delegate as? AppDelegate
이런 식의 참조를 가지는 경우를 제가 처음 봐서 어색하다는 생각이 드는게 아닌가 하는 느낌이 들어서 의견을 남기기 조심스럽지만, 그래도 남겨보겠습니다..ㅎㅎ

예를 들어, 일반적으로 View Controller는 View 쪽으로 strong 참조를 유지하고 있고, View는 delegate 패턴 등으로 View Controller 쪽으로 이벤트를 보낼 때 weak 참조를 갖고 있습니다. 순환 참조가 일어나지 않도록 하기 위해서요~ 이런 경우의 연장선상에서 저는 View Controller에서 App Delegate 쪽으로의 강한 참조를 유지하는 게 이상하다고 느꼈었고, 그래서 위 코멘트를 남겼었습니다.

따라서 App Delegate에 접근해야 한다면, 프로퍼티로 참조를 유지하지 말고 메서드 내에서 로컬 변수로 그때그때 UIApplication.shared.... 의 참조를 얻어서 사용하는 방식이 더 나을 것 같아요.

2021-04-18 08:38 UTC, seizze commented on Expo1900/Expo1900/VIewController/Entry/Korea/KoreaDetailEntryViewController.swift
> +    private var appDelegate = UIApplication.shared.delegate as? AppDelegate
인스턴스 간의 강한 참조를 하면 어떤 문제가 있는지는 [Strong Reference Cycles Between Class Instances](https://docs.swift.org/swift-book/LanguageGuide/AutomaticReferenceCounting.html#ID51) 를 참조해 주세요!

2021-04-18 08:38 UTC, seizze commented on Expo1900/Expo1900/VIewController/Entry/Korea/KoreaDetailEntryViewController.swift
>      }
제가 화면 회전 쪽에 대해 어렴풋이만 알고 있었는데, 오늘 조금 알아보니 해당 화면이 온전히 담당하게 하는 방법이 생각보다 까다롭네요.. 이 코멘트는 무시해 주세요 ㅠㅠ

2021-04-25 07:45 UTC, seizze approved these changes
안녕하세요 Fezz ㅎㅎ 마지막까지 수고많았어요 !! ☺️
처음에 비해서 구조도 굉장히 좋아지고 테스트도 많이 개선되었네요

### 1. 화면 회전

오 화면 회전 기능을을 해당 화면이 담당해 처리하도록 만드셨네요!! 👍👍 좋은 방향이라고 생각합니다.

문제가 생겼던 부분은 아래와 같이 하니까 되는데용?? 그러고보니 프레임워크 함수들을 override한 후에 super를 하나도 호출해주고 있지 않네요 ㅠㅠ 프레임워크 메서드들을 오버라이드할 땐 기본적으로 super를 호출해줘야 합니다. 그렇지 않으면 이상 동작을 할 수 있습니다.

```swift
override func viewWillAppear(_ animated: Bool) {
    super.viewWillAppear(animated)
    
    let value = UIDeviceOrientation.portrait.rawValue
    UIDevice.current.setValue(value, forKey: "orientation")
    
    self.navigationController?.navigationBar.isHidden = true
}
```

### 2. 데이터 처리

👍👍

### 3. 

디코딩 기능을 분리한 점 좋네요~ 👍
오류처리가 복잡해진 것 같이 느껴지는 이유는 Result와 throw를 동시에 사용하기 때문인 것으로 보입니다. Result에서 failure case를 통해서 이미 에러를 받아볼 수 있는데 throw까지 사용할 필요가 없지 않을까요? ㅎㅎ

```swift
let result: Result<Expo, ExpoError> = try jsonDecode(assetName: Constant.expoJson)
```

그리고 여기서 타입을 명시해야 하는 이유는 `jsonDecode(assetName: Constant.expoJson)`를 호출하는 것 만으로 리턴값의 T에 대한 타입 추론이 불가능하기 때문입니다. 이 부분에선 지정해 줘야 하는게 맞아요~!

### 4. 테스트

코멘트 하나 남겼습니다~ ㅎㅎ

2021-04-25 07:46 UTC, merged