Step2 Steven
yagom-academy/ios-exposition-universelle pull request #63
Opened 2021-04-12 11:43 UTC by stevenkim18

@yagom 

안녕하세요 야곰! 두번째 PR을 보냅니다^^

## 구현한 부분   
### step2에서 요구한 부분들 모두 구현했습니다.
- 전시회 정보 화면에서 `방문자`, `개최지`, `개최기간`의 텍스트 크기를 다르게 주었습니다.
- 세부사항을 갔다가 다시 테이블 뷰로 오면 이전에 선택한 셀이 회색 배경으로 칠해졌었는데 요구사항에 화면처럼 다시 흰 배경으로 처리해주었습니다.
### 간단하게 오토레이아웃을 적용했습니다
- 다른 것들은 사용안하고 뷰들 간에 제약만 주었습니다

## 조언을 얻고 싶은 부분
- 기능은 잘 구현 되지만 아직 코드가 깔끔하지는 않습니다. 리펙토링을 하기 전에 야곰의 날카롭고 꼼꼼한 피드백을 적용해서 고치고 싶어서 미리 pr을 보냈습니다. 
- 이외에도 이상하게 사용한 부분들이 있다면 알려주세요!

2021-04-12 14:19 UTC, yagom requested changes
더 늘어지기 전에 PR 보낸 것은 좋은 선택이라고 생각해요 👍 

❓ 질문과 ❗코멘트는 남겨두었습니다 :)

2021-04-12 14:19 UTC, yagom commented on Expo1900/Expo1900/Cell/ItemTableViewCell.swift
> +class ItemTableViewCell: UITableViewCell {
무슨 Item일까요?

2021-04-12 14:19 UTC, yagom commented on Expo1900/Expo1900/Cell/ItemTableViewCell.swift
> +    @IBOutlet weak var itemShortDescription: UILabel!
어차피 Item Cell 이므로 item을 굳이 중복해서 써줄 필요는 없지 않을까요?

2021-04-12 14:19 UTC, yagom commented on Expo1900/Expo1900/Cell/ItemTableViewCell.swift
> +    @IBOutlet weak var itemShortDescription: UILabel!
또, Image라는 이름은 이미지인지, 이미지 뷰인지 모르겠어요.
TItle도 Description도 String인지 레이블인지 모르겠어요.

2021-04-12 14:19 UTC, yagom commented on Expo1900/Expo1900/Cell/ItemTableViewCell.swift
> +    }
필요없는 코드 지워주기

2021-04-12 14:19 UTC, yagom commented on Expo1900/Expo1900/Model/ExhibitionInfomation.swift
> +    }
만약 기획서나 문자열이 변경되어 괄호가 사라진다면, 이 코드는 유효할까요? 더 좋은 방법이 있을까요?

2021-04-12 14:19 UTC, yagom commented on Expo1900/Expo1900/Model/ExhibitionInfomation.swift
> +        return numberFormatter.string(for: visitors) ?? "0"
nil 병합 연산자는 이 위치에서 안전한 선택일까요? 단순히 코드 작성의 복잡성을 피하고 싶은 회피성 사용은 아닐까요?

2021-04-12 14:19 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/ExhibitionViewController.swift
> +class ExhibitionViewController: UIViewController {
클래스 이름을 변경한 이유가 있나요?

2021-04-12 14:19 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/ExhibitionViewController.swift
> +    private func initValues() {
내부 코드가 뭉터기로 있는것 같아요.
좀 더 기능을 분리할 수 있을것 같아요.

2021-04-12 14:19 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/ExhibitionViewController.swift
> +    }
스텝 3에서 수정할거죠? 😃

2021-04-12 14:19 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/ExhibitionViewController.swift
> +    private func changeFont(from label: UILabel, applyText: String) {
뭔가... 이 메서드를 레이블에서만 사용하게 하기는 아까울 것 같은데...ㅎㅎ 그냥 연습삼아 텍스트 뷰도 이 메서드를 통해 텍스트를 적용할 수 있도록 변경해보려면 어떻게 하면 좋을까요?

2021-04-12 14:19 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/ItemDetailViewController.swift
> +        itemImage.image = UIImage(named: exhibitedItem?.imageName ?? "")
nil 병합 연산자를 너무 남발하는 것 같아요

2021-04-12 14:19 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/ExhibitionViewController.swift
> +    @IBOutlet weak var exhibitionDescriptionLabel: UILabel!
여기도 이름의 중복이 보이죠? 👀

2021-04-12 14:19 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/ExhibitionViewController.swift
> +        changeFont(from: exhibitionHoldingPeriodLabel, applyText: "개최기간")
기능을 수행하는 코드에서 최대한 날것의 상수를 없애줍시다. 
날것의 상수는 언젠가는 문제를 일으킬 시한폭탄과 같아요.
여기서 날것의 상수를 빼내려면 어떻게 하는게 좋을까요?

2021-04-12 14:19 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/ExhibitionViewController.swift
> +        changeFont(from: exhibitionHoldingPeriodLabel, applyText: "개최기간")
위의 viewDidLoad 메서드 안에도 날것이 팔딱이네요! 🐟

2021-04-15 07:30 UTC, stevenkim18 commented on Expo1900/Expo1900/Cell/ItemTableViewCell.swift
> +class ItemTableViewCell: UITableViewCell {
셀이름을 더 명확하게 해주었어요 ㅎㅎ `ExhibiedItemTableViewCell` 로 변경했습니다!

2021-04-15 07:39 UTC, stevenkim18 commented on Expo1900/Expo1900/Cell/ItemTableViewCell.swift
> +    @IBOutlet weak var itemShortDescription: UILabel!
앗 이름 짓는 것도 여쭤보려고 했는데 이미지뷰나 라벨 이런 것들을 다 써주면 좋군요 ㅎㅎ 
`imageView`  `titleLabel`  `shortDescriptionLabel` 로 변경했습니다!

2021-04-15 08:01 UTC, stevenkim18 commented on Expo1900/Expo1900/Model/ExhibitionInfomation.swift
> +    }
만약 바뀐다면 유효하지 않아요 ㅜㅜ 

1. 음.. title에서 한글 부분과 영어 부분을 두개로 자른 다음에 2개의 라벨을 만들어서 넣어주는 방법
2. 아니면 파싱을 할때 맨 처음 영어나 특수기호가 오면 그 인덱스 바로 앞에 개행을 추가해주는 방법

이렇게 2가지 있을 것 같아요!

2021-04-15 08:11 UTC, stevenkim18 commented on Expo1900/Expo1900/Model/ExhibitionInfomation.swift
> +        return numberFormatter.string(for: visitors) ?? "0"
네 😅 복잡성을 피하려고 썼었어요.. ㅎㅎ

```swift
var formattedVistorsNumber: String {
        let numberFormatter = NumberFormatter()
        numberFormatter.numberStyle = .decimal
        guard let formattedNumber = numberFormatter.string(for: visitors) else { return String(visitors) }
        return formattedNumber
    }
```

포맷을 실패 했을 때는 그냥 숫자 사이에 콤마 없이 그냥 문자열로 케스팅 된 숫자를 리턴하게 수정했습니다!

2021-04-15 08:12 UTC, stevenkim18 commented on Expo1900/Expo1900/ViewControllers/ExhibitionViewController.swift
> +class ExhibitionViewController: UIViewController {
전시회 정보를 보여주는 뷰컨이라고 생각해서 변경했습니다!!
이전 프로젝트에서 처음 만들어진 뷰컨도 이름이 있는것이 좋을 것 같다는 피드백이 있어서 이번에 반영해봤어요 :)

2021-04-15 08:23 UTC, stevenkim18 commented on Expo1900/Expo1900/ViewControllers/ExhibitionViewController.swift
> +    private func initValues() {
뷰를 초기화하는 함수`initViews` 와 뷰들의 벨류를 바꾸는(폰트를 바꾸는) 함수 `changeViewsValue`로 나눠주었습니다!

2021-04-16 03:23 UTC, stevenkim18 commented on Expo1900/Expo1900/ViewControllers/ExhibitionViewController.swift
> +        changeFont(from: exhibitionHoldingPeriodLabel, applyText: "개최기간")
enum 안에 static 변수로 뺐습니다!

2021-04-16 03:23 UTC, stevenkim18 commented on Expo1900/Expo1900/ViewControllers/ItemDetailViewController.swift
> +        itemImage.image = UIImage(named: exhibitedItem?.imageName ?? "")
옵셔널 바인딩으로 전시회 아이템 인스턴스를 안전하게 뻈습니다!

2021-04-16 03:26 UTC, stevenkim18 commented
@yagom 
야곰! 몸은 좀 괜찮으신가요? ㅜㅜ 너무 무리하지 마세요 ㅜㅜ

야곰이 주신 피드백을 적극 반영해서 수정했습니다!!

`changefont` 함수는 조금 더 고민해보고 스탭3에서 적용해보고 싶어서 아직 수정하지 않았습니다.

한가지 질문하고 싶은것은 cell이나 json 파일도 문자열 상수로 되어 있는데 이것들도 따로 뺴는 것이 좋을까요?

2021-04-17 03:44 UTC, yagom commented on Expo1900/Expo1900/Cell/ExhibiedItemTableViewCell.swift
> +    @IBOutlet weak var photoImageView: UIImageView!
`UITableViewCell`의 프로퍼티로 `imageView`라는 이름이 있어서 문제가 발생했겠죠? ㅎㅎ 다른 이름을 찾았군요. photo 보다는 더 나은 이름이 있었을지도요 ;p
이름 참 어렵죠?

2021-04-17 03:44 UTC, yagom commented on Expo1900/Expo1900/Constant/KoreanLetter.swift
> +}
열거형으로 빼낸 것은 정말 멋진시도입니다!

다만 아직 이름이 조금 아쉬운데요, 나중엔 좀 더 멋진 이름이 탄생할 수 있을거예요 :)
다른 캠퍼는 어떻게 해결했는지 찾아보는것도 좋을것 같아요~

2021-04-17 03:44 UTC, yagom commented on Expo1900/Expo1900/Constant/SpecialSymbol.swift
> +    static let black = " "
blank

2021-04-17 03:44 UTC, yagom commented on Expo1900/Expo1900/Constant/SpecialSymbol.swift
> +    static let colonWithBlack = " : "
blank

2021-04-17 03:44 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/ExhibitionViewController.swift
> +    @IBOutlet weak var descriptionLabel: UILabel!
훨씬 깔끔하네요!

2021-04-17 03:44 UTC, yagom commented on Expo1900/Expo1900/Model/ExhibitionInfomation.swift
> +    }
상황에 따라 다를것 같아요 ㅎㅎ
저라면 데이터를 주는 쪽에게 부탁할 것 같기도 합니다~
정답은 없네요 ㅎㅎㅎ

2021-04-17 03:45 UTC, yagom approved these changes
스티븐, 고생 많았습니다!

스텝2 머지합니다 🚀

2021-04-17 03:45 UTC, merged

2021-04-17 15:22 UTC, yagom commented
cell이나 json 파일도 문자열 상수로 되어 있다는게 어떤 뜻인지 잘 이해하지 못했어요~