[Step2] - Sookim
yagom-academy/ios-exposition-universelle pull request #64
Opened 2021-04-12 11:45 UTC by Sookim18

## [STEP 2] 만국박람회 🇰🇷

@corykim0829

안녕하세요~ cory

step2에서 기능요구서에 레이아웃 문제는 다음 스텝에서 해결한다고 적혀있어서 참고해서 진행했어요 😅

### 고민되었던 점, 해결되지 않은 점, 궁금한 점 ❗️❓

* 여러가지 데이터 전달 방식 중 segue를 활용하여 KoreaExhibitViewController에서 ExhibitDetailViewController로 선택한 셀의 정보를 전달했는데 다른 방식을 사용하는게 맞는지 궁금해요 

* 작성한 코드가 많이 부족한 것 같아요. 부족한 부분 피드백 주시면 참고해서 수정해볼게요 !  👂

2021-04-12 15:32 UTC, corykim0829 commented
@Sookim18 수고하셨어요! 제가 리뷰하기 전에 구현한 화면 캡쳐해서 PR에 같이 올려주실 수 있나요? 😀

2021-04-13 08:31 UTC, corykim0829 requested changes
수고하셨어요 수킴 😃

UI도 깔끔하게 잘 구현하셨네요 👍👍👍👍
테이블뷰 깔끔하게 잘 구현하셔서 놀랐어요!! 😎

먼저 코드에 대한 부분 피드백 진행하고 UI에 대해서 같이 이야기해보면 좋을 것 같아요!
전체적인 흐름, 로직은 컨트롤러가 처리하고 있어서 좋아요! 
여기서 컨트롤러가 뷰에게 데이터를 넘겨줘서 뷰는 이 데이터를 받아서 화면을 업데이트 방향으로 좀 더 수정하면 좋을 것 같아요!!

화이팅입니다 👍👍👍

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/ExhibitDetailViewController.swift
> +    @IBOutlet weak var detailDescription: UILabel!
UIKit 클래스 변수명들은 어떤 클래스인지 더 명확하게 이름을 정해줄 필요가 있어보여요! 
나중에 사용할 때 `imageName`만 보면 `String` 처럼 보이기도 할 것 같아요! 😅
예시로 타이틀 이미지를 담을 `UIImageView` 변수는 `titleImageView`, 설명 라벨을 담을 `UILabel`은 `descriptionLabel`과 같이 네이밍 하면 더 명확할 것 같아요!

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/KoreaExhibitViewController.swift
> +    }
viewDidLoad에서 많은 일을 하고 있네요! 함수로 분리해서 명확하게 어떤 일들을 viewDidLoad에서 처리하는지 해주면 좋을 것 같아요!!

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/KoreaExhibitViewController.swift
> +    private func itemDecode() {
itemDecode 보다는 decodeItem이 문법적으로 자연스러울 것 같아요 😄

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/KoreaExhibitViewController.swift
> +        else { return }
guard에서 바로 return 처리하는 경우에는 보통 다음과 같이 표기를 많이 합니다! 참고하세요 😀
```suggestion
        guard let koreaExhibitItemsData = NSDataAsset(name: "items")  else { return }
```

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/KoreaExhibitViewController.swift
> +                if let select_index = sender as? Int {
엇 여기서 스네이크케이스 변수를 쓴 이유가 있나요?

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/KoreaExhibitViewController.swift
> +        performSegue(withIdentifier: "ShowDetail", sender: indexPath.row)
sender로 index를 잘 전달했네요! 👏👏👏 깔끔해요

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/KoreaExhibitViewController.swift
> +extension KoreaExhibitViewController: UITableViewDelegate {
extension으로 Delegate, DataSource 분리 좋네요 깔끔해요 😃

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/KoreaExhibitViewController.swift
> +        for i in 0..<koreaExhibitItems.count {
여기서 한번 더 for문으로 처리해줄 필요는 없어보이네요! indexPath만으로도 처리하는 걸로 개선해봐요! 😀

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/KoreaExhibitViewController.swift
> +            if koreaExhibitTableView == self.koreaExhibitTableView && indexPath.row == i {
`koreaExhibitTableView == self.koreaExhibitTableView` 이 부분은 항상 `true`인 명제가 아닐까요? 👀

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/KoreaExhibitViewController.swift
> +            if segue.identifier == "ShowDetail" {
prepare 함수 인덴트 정리 해주세요!

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/KoreaExhibitViewController.swift
> +                cell.koreaExhibitShortDescription.text = koreaExhibitItems[i].short_desc
이렇게 cell에 있는 UIKit의 요소를 직접 가져오지 않고 cell에 data만 넘겨주는 방식으로 뷰단을 업데이트하는 구조로 변경해보면 좋을 것 같아요! 😀

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/Expo1900ViewController.swift
> +    private func expo1900DecodeData() {
여기도 decode~ 이런식으로 해야 문법적으로 자연스러울 것 같아요!

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/Expo1900ViewController.swift
> +        informationDescription.text = expo1900.description
decode함수 안에서 UIKit 요소들을 변경하고 있네요! 분리하면 좋을 것 같아요 😀

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/Expo1900ViewController.swift
> +    }
viewDidLoad에서 많은 일을 하고 있네요! 함수로 분리해서 명확하게 어떤 일들을 viewDidLoad에서 처리하는지 해주면 좋을 것 같아요!! (아래에도 동일한 리뷰를 남겼습니다!)

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/Expo1900ViewController.swift
> +    private var expo1900 = Expo1900(title: "", visitors: 0, location: "", duration: "", description: "")
이렇게 의미없는 초기값을 넣기 보다는 optional타입으로 처리하는게 좋을 것 같아요!

2021-04-13 08:31 UTC, corykim0829 commented on Expo1900/Expo1900/View/ExhibitDetailViewController.swift
> +    private func inputDetailData() {
함수명이 왜 `inputDetailData()`인지 설명을 들을 수 있을까요? 잘 이해가 되지 않네요 👀

2021-04-13 13:21 UTC, Sookim18 commented on Expo1900/Expo1900/View/ExhibitDetailViewController.swift
> +
swift공식문서에 클래스 및 함수의 시작과 끝은 개행을 추가하지 않아서 규칙을 따라하면 좋을 것 같아요👍

2021-04-13 13:39 UTC, Sookim18 commented on Expo1900/Expo1900/View/ExhibitDetailViewController.swift
> +    @IBOutlet weak var detailDescription: UILabel!
UIKit 변수명들을 뒤에 클래스를 적어주면 cory피드백처럼 명확해서 좋은 것 같아요

2021-04-13 13:48 UTC, Sookim18 commented on Expo1900/Expo1900/View/KoreaExhibitViewController.swift
> +    private func itemDecode() {
동사를 앞에 쓰도록 주의해야겠어요 😅

2021-04-13 13:51 UTC, Sookim18 commented on Expo1900/Expo1900/View/KoreaExhibitViewController.swift
> +        else { return }
guard문 표기법 주의해야겠네요😅   덕분에 깃허브 suggestion 기능에 대해서 배웠어요 ㅎㅎ

2021-07-03 02:27 UTC, closed without merging