[Step2] Neph
yagom-academy/ios-exposition-universelle pull request #66
Opened 2021-04-13 07:27 UTC by Neph3779

안녕하세요 야곰! Step2 PR을 보냅니다!

이번 프로젝트는 스토리보드 없이 코드로만 UI를 구성하는 것을 중점으로 진행해봤습니다.

### 고민했던 부분

- lazy var의 사용을 최소화하려 해봤지만 JSON data를 불러온 뒤 그 내용을 반영해야 했기 때문에 클로저를 통한 let상태로의 초기화가 어려웠습니다. 이 부분을 어떻게 처리해야 좋을까요?
- 제 코드 구조상 JSON 파일의 디코딩을 main view와 navigation view를 왔다갔다 할때마다 init()을 통해 진행해주고 있는데 한번 디코딩 해놓으면 백그라운드에 저장되어 있도록 해줄 수 없을까요?
\+ JSON 파일의 디코딩을 initialize 시점에 진행해주는 것이 바람직한 방법인지 잘 모르겠습니다 ㅠㅠ..
- custom label과 custom imageView를 만든 뒤 init을 사용해서 한 파일 내의 중복 코드를 줄이려고 노력해봤는데 적절한 방식일까요?

새롭게 배운것들이 워낙 많고 이것을 중간중간 반영하다보니 커밋을 잘게 짤라서 보내지 못했습니다.. 다음부턴 의식적으로 더 노력해보도록 하겠습니다 🥲

2021-04-13 11:59 UTC, yagom requested changes
네프, 많은 고민이 묻어나오는 코드네요!

고민했던 부분을 고민의 단계단계를 이야기 해주면 더 좋을것 같아요. 어떤어떤 방법의 후보가 있었고, 어떤 이유때문에 이 방법을 택하게 되었다 등의 이야기를 써주면 더 답변하기 좋을것 같아요. 단편적인 코드만으로는 그 고민의 과정을 충분히 이해하기 어렵기 때문이에요.

또, 어떤 타입에서는 private을 적극적으로 사용하고, 어떤 타입에서는 덜 사용한 부분이 있어요. 개선의 여지가 있을 것 같습니다.

나머지 의견은 코멘트에 남겨두었으니 확인해보면 좋을것 같아요 ;)

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/Model/DefaultValues.swift
> +}
이름만 보면 어떤 기본값을 의미하는지 잘 모르겠습니다 😮

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/Model/ExpositionUniverselle1900.swift
> +    }
이니셜라이저를 구현한 이유는 무엇이고, 기본 값을 할당한 이유는 무엇인가요?

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/Model/KoreanItem.swift
> +    }
이곳에도 이니셜라이저를 구현한 이유가 궁금합니다

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/ExpositionImageView.swift
> +    }
이미지뷰를 이니셜라이저를 통해 기본적인 동작을 구현해줬군요! 좋은 시도예요! 👍 
그런데 이 접근은 스토리보드를 사용할 때는 유효하지 못할 방식입니다.
꼭 코드만으로 사용해야 하는 클래스가 아니도록 유연하게 구현할 수는 없을까요?

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/ExpositionImageView.swift
> +        fatalError("init(coder:) has not been implemented")
예제에는 fatalError를 많이 사용하는데요, 좋지 못하다고 생각합니다. 좀 더 나은 방법이 있을거라고 생각해요

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/ExpositionLabel.swift
> +final class ExpositionLabel: UILabel {
final을 사용했군요! 그 이유는 무엇일까요?
또, 이 클래스 또한 커스텀 이미지뷰처럼 고민해볼거리가 있을것 같아요

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemCell.swift
> +    static let identifier = "KoreanItemCell"
```suggestion
    static let reuseIdentifier = "KoreanItemCell"
```

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemCell.swift
> +    }()
클로저를 사용한 프로퍼티 초기화 좋아요 👍

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemCell.swift
> +        label.font = UIFont.preferredFont(forTextStyle: .title2)
다이나믹 타입의 적용 좋아요 :)

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemCell.swift
> +    }
무의미한 코드는 없애줘도 좋아요 :)

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemCell.swift
> +    private func setConstraint() {
이름이 조금 아쉬운데, 단수형을 통해서 하나의 제약을 셋팅한다는 느낌이 드는데,
내용은 여러 제약을 추가해주고 있습니다.

또, 여러 화면 요소를 한번에 제약을 추가하기 보다는 여러 메서드로 나누는 것도 좋겠어요.
만약 화면 요소 하나가 변경된다면 이 메서드는 과연 얼만큼의 수술이 필요할지 생각해 본다면, 어떻게 분리해야 할지 고민해볼 수 있을거예요.

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +    }()
이 뷰 컨트롤러가 관리하는 스크롤뷰가 한 개 더 추가된다면 이 프로퍼티 이름은 과연 버텨낼 수 있을까요? 😢

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +    lazy var contents = [itemImageView, itemDescriptionLabel]
만약 여기에서 lazy var의 사용이 아쉽다면, 뷰 컨트롤러의 뷰 라이프 사이클을 활용해보는건 어떨까요?

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +    }
viewDidLoad에서 할 일도 메서드에 그냥 몰아넣기 보다는 따로 유의미한 메서드로 분리해주는 것이 나중에 코드를 해석해낼 때 좋습니다.

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +    private func setContentsVertically(intervalOf interval: CGFloat) {
인터벌이 어떤 의미인지 한참 생각했어요... 😮
아마 inset을 의미한 것 같은데, 맞을까요?
용어의 잘못된 사용은 굉장히 큰 혼동을 유발하고, 엄청난 나비효과...🐞를 경험할 수 있습니다😱

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +            item.widthAnchor.constraint(equalTo: view.safeAreaLayoutGuide.widthAnchor, constant: -20).isActive = true
날것의 상수를 끄집어낼 방법이 있을까요?

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +            }
이 코드를 3년 뒤에 다시 보면 한 번에 이해할 수 있을까요? 저는 너무 어렵네요 ㅠㅠ

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +                                                  action: #selector(touchUpBackButton))
커스텀 백버튼을 만들지 않고 시스템 백버튼을 활용하도록 합시다.
이 방법을 대체할 방법을 찾으면 좋겠습니다.

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +    var koreanItemsData = [KoreanItem]()
```suggestion
    var koreanItems = [KoreanItem]()
```

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +            return
이 데이터는 꼭 불러와야 하는 데이터로 이해했는데, catch에서 그냥 return 해버리면 오류처리를 하는 큰 의미가 없을 것 같아요.  이 곳에 좀 더 유의미한 코드가 올 수 있지 않을까요?

참고 : print는 굉장히 무의미한 코드입니다

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +        tableView.rowHeight = 100
rowHeight을 100으로 설정한 이유는 무엇인가요?

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +    func setConstraint() {
이 메서드 이름도 수정이 필요할 것 같아요.

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/MainViewController.swift
> +        let rootVc = KoreanItemsRootViewController()
저는 VC 축약형을 지양하는 편이에요
이 부분의 선택은 자유지만, 대체적으로 Vc라고 표현하진 않아요

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/MainViewController.swift
> +//        navigationController?.navigationBar.topItem?.title = "한국의 출품작"
무의미한 코드는 커밋하지 않습니다 🚫

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/MainViewController.swift
> +        navigationViewController.modalPresentationStyle = .fullScreen
모달을 사용한 이유가 있나요? 
프로젝트 기능상세서에 따르면 모달을 사용한 화면은 없던것 같아요.
모달은 언제 사용하고, 내비게이션 방식은 언제 사용하나요?
우리 활동학습때 제가 매우 강조했던 내용중 하나예요~

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +        dismiss(animated: true, completion: nil)
이 프로젝트에서는 dismiss라는 코드가 나올 일이 없을 것 같습니다.
왜 이 코드가 나왔는지 궁금합니다 🤔

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +        navigationController?.pushViewController(KoreanItemViewController(data: koreanItemsData[indexPath.row]), animated: true)
이동은 내비게이션을 사용하는데, 모달 스타일을 지정해주는 이유가 무엇일까요?

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/MainViewController.swift
> +        super.init(nibName: nil, bundle: nil)
이 이니셜라이저는 `init(coder: NSCoder)` 인데, `super.init(nibName: bundle:)` 이니셜라이저를 호출하는 이유가 무엇일까요?
예상치 못한 결과를 얻을 수도 있을 것 같은데요. 충분히 고민하고 어떤 리스크를 갖게될지 예상을 해봤는지 궁금합니다.

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/MainViewController.swift
> +    private lazy var contents = [titleLabel, posterImageView, visitorsLabel, locationLabel, durationLabel, descriptionLabel, moveToKoreanItemsStackView]
화면의 기획이 바뀌면 이 프로퍼티는 안전할까요?

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/MainViewController.swift
> +    private lazy var durationLabel = ExpositionLabel(text: "개최기간 : " + expositionData.duration, textStyle: .subheadline)
날것의 상수가 코드에서 뛰어놀게 놔두지 않으면 좋겠어요

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +    func getKoreanItemsData() {
get, fetch, retrive 등 다양한 표현이 있는데, get이라는 prefix를 사용한 이유가 무엇일까요?
그리고 이 메서드는 get이라는 이름을 달고 있어서 결과를 반환해줄 것 같은데, 반환값이 전혀 없군요!?

2021-04-13 11:59 UTC, yagom commented on Expo1900/Expo1900/View & Controller/MainViewController.swift
> +        present(navigationViewController, animated: true, completion: nil)
이 흐름에서 present를 사용한 이유가 무엇일까요?

2021-04-14 09:49 UTC, Neph3779 commented
@yagom 
### 고민해봤던 내용들

1. JSON 파일의 디코딩에 실패했을 경우 이를 어떻게 처리할지에 대한 고민이 있었습니다

   제가 생각해본 처리 방법은 다음과 같습니다.

   1. error alert를 띄움과 동시에 해당 화면(JSON 파일을 디코딩한 데이터가 필요한 화면)으로의 전환 차단
   2. JSON 데이터를 이용해 구성해야하는 UIView를 빈 공간을 놔둠
   3. JSON 데이터를 이용해 구성해야하는 UIView에 default value를 채워서 보여줌

   저는 위 방법들 중 3번을 택했고 어떻게 default value를 할당할 수 있을지 고민해본 결과 initialize 시점에 할당을 해주면 되겠다고 생각했습니다.

   ```swift
   private let expositionData: ExpositionUnivereselle1900
   
   //...
   
   required init(coder: NSCoder) {
           if let dataAsset = NSDataAsset(name: "exposition_universelle_1900") {
               do {
                   expositionData =  try JSONDecoder().decode(ExpositionUnivereselle1900.self, from: dataAsset.data)
               } catch {
                   expositionData = ExpositionUnivereselle1900()
               }
           } else {
               expositionData = ExpositionUnivereselle1900()
           }
           super.init(nibName: nil, bundle: nil)
   }
   ```

   위의 코드와 같이 error를 catch한 경우와 dataAsset이 nil인 경우에 `expositionData`에 default 값이 할당되어있는 instance를 assign해주는 방식을 고안했습니다. 

    

2. constraint를 얼마나 나누어서 주어야할지에 대한 고민이 있었습니다.

   제가 생각했던 방식은 다음과 같습니다.

   1. 각각의 view마다 constraint를 주는 메서드를 제작
   2. 같은 맥락의 view마다(label 종류, imageView 종류 등으로 나누어서)  constraint를 주는 메서드를 제작
   3. 하나의 화면을 구성하는 view들의 constraint를 주는 메서드 제작

   가장 처음에는 1번과 2번을 동시에 사용해보았습니다. (아래의 코드와 같이 사용했었습니다.)

   ```swift
   private func setLabelsConstraints() { 
   	setTitleLabelConstraint()
   	setShortDescriptionLabelConstraint()
   }
   
   private func setTitleLabelConstraint() { ... }
   private func setShortDescriptionLabelConstraint() { ... }
   ```

   위와 같이 코드를 구성했더니 제가 생각하기에 의미없는 메서드들로 인해 코드가 너무 길어진다는 느낌을 받았습니다. 제 생각에는 `setConstraints()` 메서드를 읽으면 어떤식으로 constraint를 주었는지 쉽게 파악할 수 있을거라 생각했습니다. 

   하지만 야곰의 피드백을 들으니 constraint를 주는 작업이 얼마든지 변경될 수 있으며 view가 많아질수록 한 메서드에 넣어서 관리하는 것이 좋지 않다는 생각이 들어 1번과 2번을 동시에 사용하는 기존의 방식으로 수정했습니다. 메서드로의 분리가 너무 과하다 싶은 부분이 있다면 알려주시면 감사하겠습니다.

   

3. init을 필요한 부분에만 활용했습니다.

   required init?(coder: NSCoder)이 필요한 이유에 대해 알아보았는데 UIViewController가 채택한 NSCoding 프토코롤이 required init?(coder: NSCoder)의 구현을 요구하고 있기 때문이었습니다. 왜 이 이니셜라이저를 요구할까에 대해 생각해보는 과정에서 NSCoder에 대해 알아보았고 스토리보드, xib 파일등이 xml로 변환되면 그것을 디코딩해주는 작업을 NSCoder가 한다는 사실을 알게되었습니다. 

   > 그런데 이 접근은 스토리보드를 사용할 때는 유효하지 못할 방식입니다.
   > 꼭 코드만으로 사용해야 하는 클래스가 아니도록 유연하게 구현할 수는 없을까요?

   이 피드백을 통해 required init?(coder: NSCoder)에 필요한 것들을 구현해주면 스토리보드를 사용하더라도 커스텀 label, imageView가 정상적으로 처리된다고 유추해봤는데 제가 생각한 것이 맞을까요? ExpositionLabel, ExpositionImageView가 스토리보드를 통해서도 정상적으로 처리되도록 구현해봤는데 제대로 한 것인지 피드백 주시면 감사하겠습니다.

   

   init을 사용하기 적절하지 않은 곳은 바로 `KoreanItemViewController`였습니다. 기존에는 init을 통해 `KoreanItem` 타입의 전달인자를 넘겨받아 그것을 토대로 초기화를 진행했는데 이렇게하면 스토리보드를 사용할 때 전혀 쓸 수가 없게 되어버리는 불상사가 있었습니다. 이에 어쩔 수 없이 화면전환이 이루어지기 전(view가 push 되기 전)에 data들을 넣어주는 작업을 아래와 같이 진행했습니다.

   ```swift
   final class KoreanItemsRootViewController: UIViewController {
   
     //...
     
   func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
           let koreanItemViewcontroller = KoreanItemViewController()
           koreanItemViewcontroller.koreanItem = koreanItems[indexPath.row]
           navigationController?.pushViewController(koreanItemViewcontroller, animated: true)
   }
     
   //...
   ```

   외부(KoreanItemRootViewController)에서 KoreanItemViewController의 프로퍼티인 koreanItem에 접근해야하므로 private 처리를 해줄 수 없었으며 var로 선언해야했습니다. 이 부분을 어떻게 개선할 수 있을지 피드백 주시면 감사하겠습니다.









### 기타 개선한 내용들

- private으로 처리해줄 수 있지만 private 처리되어있지 않던 메서드와 변수들을 private 처리해주었습니다.
- 복잡하게 구성했던 view간의 constraint 조정작업을 stackView를 활용하여 개선했습니다. 기존에 stackView를 사용하지 않았던 이유는 scrollView위에 stackView를 올리니 scroll이 되지 않았는데 이 이유를 찾지 못했었습니다. 답은 stackView의 bottomAnchor를 scrollView와 동일하게 맞춰주는 것이었습니다. (기존에는 heightAnchor을 먼저 맞춰준 뒤 stackView에 subview들을 넣었었습니다.)
- navigation controller를 present했다 dismiss하는 방식에서 시작 화면부터 navigation view가 되도록 했습니다. 기능상세서의 시작화면에 navigation bar가 없다가 한국의 출품작 페이지로 이동하면 navigation bar가 생기길래 당연히 navigation view를 present 했다 dismiss하는거라 생각했었는데 착각이었습니다. 



### 해결하지 못한 내용들

- ```swift
  private lazy var contents = [titleLabel, posterImageView, visitorsLabel, locationLabel, durationLabel, descriptionLabel, moveToKoreanItemsStackView]
  ```
  
  > 화면의 기획이 바뀌면 이 프로퍼티는 안전할까요?
  
  contents 배열을 저런식으로 관리하는것이 비효율적이라는 생각이 들지만 어떻게 개선해야할지 감이 잘 안오네요..

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemCell.swift
> +    }
이정도 코드 분리는 전혀 문제될게 없어요!
다만, 이름에 of 처럼 중간 접속사는 사용하지 않는 방향으로 지어주면 좋습니다.

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +    var koreanItem = KoreanItem()
아마 이렇게 해주려고 KoreanItem의 모든 프로퍼티의 기본값을 사용한 것 같은데,
옵셔널을 활용하지 않을 이유가 있을까요?

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +        navigationController?.isNavigationBarHidden = false
viewDidLoad는 이 코드가 실행되어야 할 타이밍과는 동떨어진 메서드 같아요
그리고 `isNavigationBarHidden` 프로퍼티를 직접 수정해준 이유가 있나요?
`setNavigationBarHidden(_:animated:)` 메서드를 사용하지 않는 이유가 따로 있나요?
기능상세서의 영상과 차이를 느껴보세요.

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +    let koreanItemRootViewTitle = "한국의 출품작"
이 프로퍼티 외부에서 참조할 필요가 있는 프로퍼티인가요?

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +    private let mainTableView: UITableView = {
mainTableView는 모호한 이름이라고 생각합니다.

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +        setConstraint()
여기 코드도 유의미하게 메서드로 분리해줄 수 있을것 같아요

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +    lazy var itemDescriptionLabel = ExpositionLabel(text: koreanItem.description, textStyle: .body)
Text View가 아니고 Label을 선택한 이유가 궁금합니다

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/MainViewController.swift
> +final class MainViewController: UIViewController {
만약에 이 앱의 기획이 변경이되어서 이 화면이 메인 첫 화면이 아니게되면 이 코드는 안전할까요?

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/MainViewController.swift
> +    private let mainViewTitle = "메인"
이 프로퍼티는 어디에서 쓰이나요?

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/MainViewController.swift
> +    private lazy var contents = [titleLabel, posterImageView, visitorsLabel, locationLabel, durationLabel, descriptionLabel, moveToKoreanItemsStackView]
꼭 필요한 프로퍼티인가요?
혹시 이 요소들이 스택뷰 내부로 들어간다면 stack view의 arranged subview로 접근할 수 있지 않을까요?

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +    private func setConstraint() {
이 메서드 이름도 하나의 제약만 셋팅한다는 의미로 받아들일것 같아요.

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemCell.swift
> +    private func setConstraintsOfContents() {
제가 지난 코멘트에서 워딩을 `추가`한다고 했던것은 의도적이었습니다.
제약은 `set`해주는게 아니고 `add`하죠? 🙂
set과 add는 엄연히 아주 많이 다른 뉘앙스 차이를 보입니다.
나비효과 잊지마세요 :)

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +    private let stackViewOfMainScrollView: UIStackView = {
다른 프로퍼티와 다르게 여기 위아래에는 줄바꿈이 되어있는 이유는 무엇일까요?

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900.xcodeproj/project.pbxproj
> +			path = "View & Controller";
파일명, 경로 등에 엠퍼센드 같은 특수문자, 띄어쓰기는 제외하는것이 좋습니다.
될수 있으면 특수문자는 언더바 정도만 사용하는게 좋아요.

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +        setConstraint()
지난번 코멘트에서도 유사한 코멘트가 있었는데요, 리뷰어는 아마 그 부분만을 보고 남기진 않았을수도 있어요. 프로젝트 전반에서 살펴보는 것도 필요합니다.

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +    private func setConstraint() {
여기도 위의 viewDidLoad와 같이 또 지난번 코멘트와 같은 내용이네요.

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +                items = [KoreanItem]()
이 부분은 아래 통합 코멘트에 의견 남겨두었습니다.
무의미한 기본값은 지양해야 한다고 생각합니다.
사용자에게 유의미해질 수 있어야해요.

2021-04-14 12:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +    func getKoreanItemsData() {
@Neph3997 여기에 대한 의견을 듣지 못했습니다

2021-04-14 12:43 UTC, yagom requested changes
Neph, 금방 돌아왔군요!
이번 PR에선 커밋 단위를 그래도 나눠보려고 노력한 점이 좋아요 :)

1. 여러 고민이 있었군요! 그런데 세 방법 모두 프로그래머 입장에서만 생각한 해결방법 같아요. 만약 내가 사용자라면 의미없는 기본값이 보인다고 했을 때 어떨까요? 우리는 프로그램을 만드는 사람이라 어느정도 이해할 수 있겠지만, 사용자 입장에선 어떨까 고민해보는 것도 좋을것 같아요. 저라면 사용자에게 현재의 오류상태를 명확히 알리고 오류 리포트를 요청하고, 이전 화면으로 되돌려볼 것 같은데, 네프에게는 더 좋은 생각이 있는지 궁금합니다~
2. 좋은 변경 방향이라고 생각해요
3.  'required init?(coder: NSCoder)에 필요한 것들을 구현해주면 스토리보드를 사용하더라도 커스텀 label, imageView가 정상적으로 처리된다고 유추해봤는데'가 무슨뜻인지 잘 이해하지 못했습니다.
`didSelectRowAt` 메서드를 사용한 것 좋습니다. 스토리보드에 대응하기 위해 `prepare`에도 같은 로직이 필요로 할텐데, 그럼 중복되는 코드가 생길테니 메서드로 따로 빼보는 것도 고려해볼만하겠어요.
또, 프로퍼티에 직접 접근하지 않고 메서드를 통해 간접적으로 값을 세팅할 수 있도록 하는것이 좋습니다.

----------

아래 스크린샷 중 첫 번째 스크린샷은 스크롤뷰의 스크롤 인디케이터로 인해서 텍스트가 가려지는 현상이 있습니다. 우리는 코드를 다루는 사람이기도 하지만, 사용자와 바로 만나는 뷰를 다루는 사람이라는 것도 명심해야합니다.

두 번째 스크린샷은 뒤로가기 버튼의 타이틀이 기능상세서와 다르네요. 로직이 변경되면서 필요한 코드를 분실했는데, 커밋을 하기 전에는 디테일을 챙겨주는 것도 필요합니다.

<img width="486" alt="scroll_indicator" src="https://user-images.githubusercontent.com/3423048/114709661-d6733980-9d67-11eb-90f7-bbc2ca72cf34.png">
<img width="486" alt="back_button_title" src="https://user-images.githubusercontent.com/3423048/114709672-dc691a80-9d67-11eb-8e58-0cc4b1ad31e8.png">

잘 해내고 있는데, 기능구현에만 집중하지 말고 사소한 디테일과 이유에도 조금 집착해보면 좋겠어요. 어제 올라프가 했던 이야기를 곱씹어보는 시간을 가져보는것도 좋을것 같아요.
마음이 급해지면 생각보다 많은 것을 놓치게됩니다. 구현에 급급하지 말고 조금 더 깊고 디테일한 부분을 챙겨주면 훨씬 완성도가 높아질거예요 👍

2021-04-14 13:34 UTC, Neph3779 commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +    var koreanItem = KoreanItem()
매번 디코딩한 데이터를 사용할 때마다 guard let을 통한 옵셔널 해제 작업이 필요하기에 지양하려 했었습니다.

2021-04-14 13:42 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +    var koreanItem = KoreanItem()
생산성이 떨어지는 코드 스타일을 가지는 것은 좋은 방향이지만, 스위프트에서 guard 를 안쓰고 싶어한다면 아마도 코드가 엉망이 될 가능성이 커요.
경비원을 무서워하지 마세요 💂  해치지 않아요 😉

2021-04-14 14:00 UTC, yagom commented on Expo1900/Expo1900/View & Controller/ExpositionImageView.swift
> +    }
@Neph3779 옆동네에서 하이디도 유사한 피드백을 줬었네요 :)
https://github.com/yagom-academy/ios-exposition-universelle/pull/42#discussion_r609785970

2021-04-15 04:37 UTC, Neph3779 commented on Expo1900/Expo1900/Model/ExpositionUniverselle1900.swift
> +    var description: String = DefaultJSONValues.text
JSON 디코딩에 실패해도 
```swift
required init(coder: NSCoder) {
        if let dataAsset = NSDataAsset(name: "exposition_universelle_1900") {
            do {
                expositionData =  try JSONDecoder().decode(ExpositionUnivereselle1900.self, from: dataAsset.data)
            } catch {
                expositionData = ExpositionUnivereselle1900()
            }
        } else {
            expositionData = ExpositionUnivereselle1900()
        }
        super.init(nibName: nil, bundle: nil)
}
```

if let에서 걸러져서 else로 간 경우, catch 한 경우에 기본 인스턴스를 생성하여 넣어주는 것을 고안했는데
제가 의도한대로 동작하지 않는걸까요? (JSON 디코딩에 실패했을 때 사용자에게 의미없는 디폴트 값을 보여주는 것 자체는 좋지 않은 방법 생각되므로 방안으로 수정해보도록 하겠습니다)

2021-04-15 04:40 UTC, Neph3779 commented on Expo1900/Expo1900/View & Controller/ExpositionImageView.swift
> +        let image = UIImage(named: imageName) ?? UIImage(systemName: "zzz")
imageName을 통해 `image`에 UIImage 인스턴스를 할당하게 되면 `imageName`이 잘못되었을 경우에 nil이 할당되는 것을 확인했습니다. 따라서 system 이미지 중 하나가 대체하여 들어가도록 해주었는데 "zzz" 자체가 적절한 이미지는 아닌 것 같습니다. 사용자에게 오류가 발생했다는 사실을 알릴 수 있을만한 이미지를 제작하여 넣는 방안으로 바꿔보겠습니다.

2021-04-15 05:26 UTC, Neph3779 commented on Expo1900/Expo1900/View & Controller/ExpositionImageView.swift
> +    }
```swift
init(imageName: String) {
        let image = UIImage(named: imageName) ?? UIImage(systemName: "zzz")
        super.init(image: image)
        setUpExpositionImageView()
}
    
required init?(coder: NSCoder) {
  super.init(coder: coder)
  setUpExpositionImageView()
}
```
이런식으로 두가지의 이니셜라이저를 모두 구현해주면 스토리보드를 통해 UI를 만들어도, 코드만을 통해 UI를 구성해도 사용할 수 있다는 것이군요!

2021-04-15 05:33 UTC, Neph3779 commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +    private let stackViewOfMainScrollView: UIStackView = {
가독성을 고려하여 한 프로퍼티를 표현하는데 사용되는 줄 수가 2줄 이상으로 넘어가면 위 아래 한 칸씩 띄워 주었습니다. 
화면이 작아서 한 줄에 표현하지 못하는 경우 (이름이 긴 파라미터가 여러개 들어가는 경우) 에는 파라미터별로 newline을 해주려고 했습니다.

2021-04-15 05:36 UTC, Neph3779 commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +    func getKoreanItemsData() {
메서드의 역할을 통해 보았을 때 fetch가 가장 적절해보이네요!
다만 JSON 데이터를 가져오는 작업을 init에서 진행해주기 때문에
이 메서드는 삭제된 상황입니다
변수의 prefix 선택시에 상황에 맞는 이름으로 지을 수 있도록 조금 더 고려해볼게요!

2021-04-15 05:38 UTC, Neph3779 commented on Expo1900/Expo1900/View & Controller/MainViewController.swift
> +    private lazy var contents = [titleLabel, posterImageView, visitorsLabel, locationLabel, durationLabel, descriptionLabel, moveToKoreanItemsStackView]
stackView에 addArrangedSubview()를 통해 넣어주는 작업을 contents 배열을 통해 간단히 만드려고 시도했습니다.
```swift
contents.forEach({ stackViewOfMainScrollView.addArrangedSubview($0) })
```
만약 stackView에 넣어주는 작업을 여러줄에 걸쳐서 사용하는 것보다
content 배열을 하나 만든 뒤 forEach 구문을 통해 넣어주는 것이 더 보기에 깔끔하다 생각했습니다
야곰의 의견은 어떠신가요?

2021-04-15 06:28 UTC, Neph3779 commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +        navigationController?.isNavigationBarHidden = false
KoreanItemRootViewController의 viewWillAppear쪽으로 가야할 코드가 들어가있네요.. 꼼꼼하게 보지 못했네요.. ㅠ 
수정했습니다.

2021-04-15 07:37 UTC, Neph3779 commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +        tableView.rowHeight = 100
row Height을 설정해주지 않으면 이미지가 잘리거나 하는 등의 문제들이 있었습니다. 동적으로 글의 길이나 이미지의 크기에 따라 cell의 높이를 조절하는 것은 Step3에 가서 진행하려 했습니다.

2021-04-15 07:41 UTC, Neph3779 commented on Expo1900/Expo1900/View & Controller/MainViewController.swift
> +    private let mainViewTitle = "메인"
메인 뷰의 Title을 지정할 때 쓰였는데 코드를 수정하다 title을 정해주는 코드가 지워졌네요 🥲
수정했습니다

2021-04-15 07:42 UTC, Neph3779 commented on Expo1900/Expo1900/View & Controller/KoreanItemsRootViewController.swift
> +    private func setConstraint() {
수정사항이 많다보니 깜빡하고 챙기지 못한 내용들이 많네요
이 일 이후로 트렐로를 깔아서 할일들을 관리하게 되었습니다
놓치는 부분이 없도록 해볼게요

2021-04-15 12:44 UTC, Neph3779 commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +    lazy var itemDescriptionLabel = ExpositionLabel(text: koreanItem.description, textStyle: .body)
이 피드백을 보고 Text view에 대해 공부해봤습니다
기본적으로 editable한 경우에 사용하도록 만들어진 것을 수정하여 editable 하지 않게 만드는 부분이 어색하다 생각합니다
자동으로 scroll을 지원하는 것도 제 코드와는 맞지 않다 생각합니다.

2021-04-16 02:31 UTC, yagom commented on Expo1900/Expo1900/View & Controller/KoreanItemViewController.swift
> +    lazy var itemDescriptionLabel = ExpositionLabel(text: koreanItem.description, textStyle: .body)
그렇군요 ㅎㅎ 다른 캠퍼와는 정 반대의 의견을 줬군요.
레이블과 텍스트뷰가 단순히 편집이 가능하고 하지않고의 차이만 있을까요? 스크롤이 가능하고 아니고의 차이만 있을까요?
또 다른 점은 무엇이 있을까요? 🤔

2021-04-16 03:28 UTC, Neph3779 commented
@yagom 

안녕하세요 야곰! 야곰이 주신 피드백을 바탕으로 많은 수정이 이루어졌습니다.



### 반영한 수정사항

- back button의 이름이 설정되어 있지 않던 문제를 해결했습니다.

- 상수를 따로 모아 관리하도록 했습니다.

  상수가 따로 하드코딩 되어있으면 다른 사람이 이해하기도 어렵고 한꺼번에 여러 변경이 있을 때 관리하기 어렵다 판단하여 개선하였습니다.

- main~~ 관련 네이밍을 개선했습니다

  main... 으로 시작하는 네이밍이 적합하지 않다는걸 느꼈습니다. 기능을 토대로 네이밍을 해주는 방향으로 수정했습니다.

- 유의미한 메서드로 묶을 수 있는 부분들을 최대한 묶어주었습니다.

  메서드로 묶었을 때의 장점은 줄글처럼 코드를 읽을 수 있다는 점인 것 같습니다. 코드의 흐름을 코드 자체로 이해하는 것보다 훨씬 빠르게 파악할 수 있으며 기능을 묶어줌으로써 간결성도 올라가는 것을 느꼈습니다.

- 화면이 잘리는 부분을 safeArea를 통해 개선했습니다.

  화면이 잘리는 부분에 대해 개선했습니다. safeArea를 활용하거나 일정 여백을 두어 서로의 영역을 침범하지 않도록 했습니다.

- constraint를 주는 메서드들의 네이밍을 개선했습니다. (set으로 시작하던 것들 add로 시작하도록 개선)

- 이미지 뷰는 메서드를 통해 간접적으로 넣어주도록 했습니다.



### 변경된 로직

>  JSON 데이터를 가져오거나 Image 데이터를 가져올 때 에러가 발생하면 어떤 액션을 취해야할까? 

이 질문에 대해 오래 고민해본 결과 사용자로 하여금 에러 리포트를 전송할 것인지 말 것인지를 결정하도록 하는 alert을 띄워주면 좋을 것이라고 생각했습니다.

위의 기능을 구현하기 위해 ExpositionError에 CustomDebugStringConvertible을 채용하여 error 발생시 나오는 alert의 text에 넣어주었으며 `Result` type과 클로저 (completionHandler)를 활용해 유동적인 처리가 가능하도록 제작했습니다.



하나의 view에서도 여러개의 error가 발생할 수 있으므로 error message들이 순차적으로 alert을 통해 띄워지길 기대했었습니다. 하지만 alert을 단순히 viewWillAppear 시점에 모두 띄워지도록 했더니 이미 띄워져있는 alert이 내려가기 전에 새로운 alert을 띄우려고 시도하는 상황이 발생했고 이를 해결하기 위해 `errorList`를 만들어서 관리했습니다.

이 과정에서 nested function이 사용되었는데 바람직한지 잘 모르겠습니다. 이 부분에 대해 피드백 주시면 감사하겠습니다.

2021-04-17 12:58 UTC, yagom approved these changes
정말 엄청난 고민이 묻어나온 코드였습니다.

네프의 질문에 대해서는 코드에 코멘트 남겨두었고, 몇몇 질문도 남겨두었습니다 :)

STEP 2 머지합니다~!

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/Model/ConstantValue.swift
> +}
Nested Type을 잘 활용하면 이름짓기도 업그레이드 됩니다 ㅎㅎㅎ 👍

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/Model/ConstantValue.swift
> +//  DefaultValues.swift
상수를 따로 파일단위로 관리하는 것도 좋지만, 특정 화면에서만 사용하는 상수라면 해당 화면의 범위에서 상수를 선언해주는 것이 의미를 명확히 할 수 있고 다른 프로그래머가 파악하기에도 더 좋을것 같아요 :)

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/Model/ConstantValue.swift
> +}
이 파일의 맨 위의 코멘트와 맥락을 같이하는데요,  지금은 Cell이 하나지만 여러 셀이 생기면 이 이름도 변경되어야 할 것 같아요.
셀 안에서만 사용하는 상수라면 셀 클래스 내부 혹은 같은 파일에 구현해주는게 더 파악에 좋을듯 합니다.

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/Model/DataFetcher.swift
> +        }
`try ?`를 사용하게 되면 명확한 오류의 이유를 파악하기 어려워서 저는 특별한 경우가 아니라면 지양하고 있습니다.

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/Model/DataFetcher.swift
> +    static func fetchJsonData<DecodeType: Decodable>(dataAssetName: String, completionHandler: (Result<DecodeType, ExpositionError>) -> Void) {
컴플리션 핸들러의 사용 좋아요 :) 좋은 시도입니다!

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/Model/ExpositionError.swift
> +}
오류를 따로 정의했군요 👍 
열거형 케이스의 연관값 활용도 아주 좋아요 :)

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/Model/JsonDecodingError.swift
> +            return "😢 \(fileName).json파일의 디코딩 과정에서 오류가 발생했어요"
오류의 이유가 명확하지 않은것 같아요. 코드의 내용과 문자열의 내용이 달라서 의문이 생겼어요.
오류의 종류도 여러가지 일 수 있는데, 오류 케이스의 이름은 명확히 json 포멧의 문제라고 명시되어 있으면서 안내 내용은 그와 다른데 그 이유가 궁금하네요.

혹은 케이스 이름을 `failedDecodeJson` 등의 이름을 의도했던 걸까요?

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/Model/KoreanItem.swift
> +
의미없는 커밋이 없도록 주의하는 것도 좋아요 :)

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/Alert.swift
> +}
아래 익스텐션과 정확히 같은 동작을 하는 것 같은데요!? 아닌가요? 😱
개선의 여지가 충분합니다!
어떻게 하면 좋을까요? Protocol Oriented Programming에 대해 알아봐도 좋습니다!

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/Alert.swift
> +        }
사용자가 모든 오류리스트를 알 필요는 없을것 같아요. 
처음 마주한 오류 정도만 알려주고 리포트를 보낼때 모든 오류 내용을 자동으로 보내주는게 더 낫지 않을까요? :)

또, 사용자가 빈 화면을 보게 놔두는 것보다, Alert를 다 보고나면 completion handler를 통해서 이전 화면으로 되돌려 보내주는 동작을 하는게 UX로 더 좋을것 같단 생각이 듭니다. 이건 순전히 제 개인적인 의견이에요 🤠

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/CustomViews/ExpositionImageView.swift
> +        sizeToFit()
sizeToFit을 해준 이유는 무엇일까요? 이 코드는 유효한가요? 어떤 이유로 사용했는지 궁금합니다~

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/CustomViews/ExpositionLabel.swift
> +        lineBreakStrategy = .hangulWordPriority
ㅎㅎ 한글 줄바꿈! 좋네요!

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/ExpoIntroductionViewController.swift
> +            return ExpositionLabel(text: ExpoAffix.Prefix.visitors + String(visitors) + ExpoAffix.Suffix.visitors,
저는 변탠가봐요. 왠지 + 를 보면... reduce를 사용하고 싶어져요... 👉👈

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/ExpoIntroductionViewController.swift
> +    }
Neph 말대로 흐름을 파악하기 훨씬 좋아졌네요 :)

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/ExpoIntroductionViewController.swift
> +        showFailAlerts()
will appear 보다는 did appear에서 보여주는건 어때요?

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/KoreanItemCell.swift
> +    }
internal 메서드랑 private 메서드의 위치가 변경되면 좀 나으려나요?

메서드를 배치한 의도나 규칙이 있을까요?

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/KoreanItemTableViewController.swift
> +        return count
이런 경우엔 `koreanItems?.count ?? 0` 으로 축약해서 사용할 수 있습니다.

2021-04-17 12:58 UTC, yagom commented on Expo1900/Expo1900/ViewControllers/KoreanItemTableViewController.swift
> +    }
아마 최근 iOS 버전에는 기본값이 automaticDimension 일겁니다.
그래도 명시적으로 적어주는게 더 좋을수 있다는 생각은 듭니다 :)

2021-04-17 12:58 UTC, merged