[Step2] James
yagom-academy/ios-exposition-universelle pull request #67
Opened 2021-04-13 09:44 UTC by inwoodev

@O-O-wl 

붱이, 안녕하세요. 드디어 PR 보내봅니다. 항상 세심하게 피드백 주셔서 감사합니다~!!

# 구현한 내용
---
- 유닛테스트를 활용하여 JSON파일이 디코딩이 잘 되는지 확인하였습니다.
- Segue를 활용하여 화면전환을 구현하였고 데이터 전달을 하였습니다.
- 각 Cell 그리고 화면에 오토레이아웃을 적용시켰습니다.

# 궁금한 내용
---
- UITableViewDelegate를 활용하여 데이터를 넘겨주지 않고 Segue의 prepare() 메서드를 활용해서 데이터를 전달하였는데 어떤 방식이 더 효율적인 방법이라고 생각하시는지 궁금합니다. 메모리 효율적인 측면도 고려해야 할지 궁금합니다.
- 오토레이아웃을 어떻게 더 개선해야 하는지 궁금합니다.
- prepare메서드를 통해 이미지와 세부정보데이터를 전달하였고 이렇게 하기 위해서 cell에서 나타내지는 않지만 description이라는 정보를 저장해 놓은 뒤 해당 description을 전달 해 주는 방식으로 세부사항 페이지를 구현하였는데요. cell에 나타내지 않는 정보임에도 불구하고 cell에 저장 하는게 올바른 방식인지 궁금합니다.
- cell에서 존재하는 UIImageView를 바로 다음 화면에 전달하려 했는데 이렇게 하니까 이미지가 화면에 뜨지 않았어요. 그래서 imageName을 활용하여 image 파일의 정보만 전달한 전달받은 뷰컨트롤러에서 뒤 해당 정보에 따라 이미지를 불러왔는데 이렇게 구현하는 것이 맞는지 궁금합니다.

2021-04-14 13:14 UTC, O-O-wl requested changes
고생하셨습니다 제임스 
테스트 까지 작성하셨군요!
힘든 STEP2 고생 많으셨습니다 🙇‍♂️

> UITableViewDelegate를 활용하여 데이터를 넘겨주지 않고 Segue의 prepare() 메서드를 활용해서 데이터를 전달하였는데 어떤 방식이 더 효율적인 방법이라고 생각하시는지 궁금합니다. 메모리 효율적인 측면도 고려해야 할지 궁금합니다.
> 오토레이아웃을 어떻게 더 개선해야 하는지 궁금합니다.
> prepare메서드를 통해 이미지와 세부정보데이터를 전달하였고 이렇게 하기 위해서 cell에서 나타내지는 않지만 description이라는 정보를 저장해 놓은 뒤 해당 description을 전달 해 주는 방식으로 세부사항 페이지를 구현하였는데요. cell에 나타내지 않는 정보임에도 불구하고 cell에 저장 하는게 올바른 방식인지 궁금합니다.
> cell에서 존재하는 UIImageView를 바로 다음 화면에 전달하려 했는데 이렇게 하니까 이미지가 화면에 뜨지 않았어요. 그래서 imageName을 활용하여 image 파일의 정보만 전달한 전달받은 뷰컨트롤러에서 뒤 해당 정보에 따라 이미지를 불러왔는데 이렇게 구현하는 것이 맞는지 궁금합니다.

먼저 제임스의 생각을 좀 듣고싶습니다 
- 메모리적 측면을 고려하신다고 하셨는데 혹시 어떤 이슈가 있을 걸로 생각되는 걸까요?
- 두개의 객체간의 소통방법에 정답은 없을 것 같아요. 혹시 두개는 어떤 차이가 있다고 느끼셧나요?

정답이 있는 게 아니라서 질문으로 남겨보았어요
제임스가 그런 생각을 하시면서 어떤 이유가 있었을 것 같아서요
- 예를 들어 
세그웨이는 간편하게 전달할 수 있지만 음 .. if문으로 분기가 쳐져서 코드가 복잡해지겠군 과 같은 그런 생각을 한 근거가 함께 이야기 되어야 하지않을까요? 
메모리는 이러한 이유로 걱정되는 데 혹시 어떻게 생각하는지? 와 같은 이유들이 있으면 더 함께 이야기하기 좋을 것 같아요 🙇‍♂️

2021-04-14 13:14 UTC, O-O-wl commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +    }
혹시 setUp과 tearDown은 어느 시점에 불리고, 어떤 동작을 구현해야할까요?

2021-04-14 13:14 UTC, O-O-wl commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +        }
여기서 에러가 나면 메소드는 실패하나요?

2021-04-14 13:14 UTC, O-O-wl commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +    func test_itemData() {
테스트는 이 프로그램의 스펙을 보여줄 수 있을 것 같아요
테스트 네이밍을 조금 더 신경써봐도 좋을 것 같습니다

2021-04-14 13:14 UTC, O-O-wl commented on Expo1900/Expo1900/ViewControllers/MainViewController.swift
> +            expoDescription.lineBreakStrategy = .hangulWordPriority
이 메소드를 보면
화면에 보여질 
- 데이터 파싱
- 파싱한 데이터로 UI업데이트
- UI요소 속성 설정
과 같은 많은 로직이 하나의 메소드에 몰려있는 것 처럼 보여요 
분리할 수 있는 부분은 분리하면 좋을 것 같아요

2021-04-14 13:14 UTC, O-O-wl commented on Expo1900/Expo1900/ViewControllers/MainViewController.swift
> +            expoDuration.translatesAutoresizingMaskIntoConstraints = false
이 속성은 어떤 걸 표현하는 걸까요?

2021-04-15 11:36 UTC, inwoodev commented on Expo1900/Expo1900/ViewControllers/ItemTableViewController.swift
> +        }
예외 사항을 다루기 위해서 try를 쓰는 경우 do ~ catch 문을 사용해야지 에러처리가 가능합니다. do 문에서 try한 메서드에서 에러가 발생되면 앱이 종료되지 않고 catch문에서 처리가 가능 해 지는 특징이 있습니다.

try?를 사용하면 에러발생시 nil값을 반환하고 에러가 발생하지 않으면 옵셔널값을 반환합니다. do catch문이 없어도 사용할 수 있기에 코드가 간결해진다는 장점이 있다고 생각했어요. 대신에 반환되는 값이 옵셔널이기에 추후에 다시 옵셔널바인딩을 사용해야 한다는 번거로움이 단점이라고 생각됩니다.

둘 중에서 do catch문을 쓴 이유는 데이터를 파싱한 뒤 viewDidLoad에 데이터를 가져오지 못할 경우 catch문 에서 오류메세지를 작성하여 유저에게 데이터를 불러오지 못하는 점을 알려줄 때 활용하면 좋다고 생각해서 사용했습니다. 혹시 다른 더 나은 방향으로 구현하는게 좋을지 궁금합니다.

2021-04-15 12:51 UTC, inwoodev commented on Expo1900/Expo1900/ViewControllers/MainViewController.swift
> +            return ""
현재 코드에서 formatter의 string 메서드를 사용하여 결과값을 문자열로 반환하려 하였습니다. 그런데 해당 메서드가 옵셔널 문자열을 반환하기 때문에 추후에 그냥 바로 사용할 수 있도록 guard let문을 활용하여 추출해 줬는데요..이 상황에서 문자열로 반환이 되지 않을시 빈 문자열을 반환하는 것이 적절하지 않아보여서 고쳐봤습니다!

2021-04-15 13:57 UTC, inwoodev commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +    }
setUpWith Error()는 테스트가 시작되지 전에  테스트에 필요한 객체를 생성하는 메서드로 이해했어요. tearDownWithError()는 테스트가 끝난 뒤 테스트에 사용된 데이터를 초기화 시켜주는 메서드로 이해했습니다. 그런데 코드를 살펴보니 테스트에 필요한 객체를 생성하지 않아서 setUpWithError() 메서드에 객체를 생성하는 방향으로 수정하였습니다. 그리고 tearDownWithError()메서드에서는 사용된 객체를 초기화 시켜주어야 하기 때문에 nil이 되도록 설정하였는데요. 혹시 제가 접근하는 방식이 틀린지 궁금합니다.

2021-04-15 13:59 UTC, inwoodev commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +        }
네! 해당 메서드에서 올바르지 않은 값이 들어오면 메서드는 실패할 것이라 생각하고 있어요!

2021-04-16 03:37 UTC, O-O-wl approved these changes

2021-04-16 03:37 UTC, O-O-wl commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +    }
해당 메소드의 문서를 읽어보시고 하셨을테니 이해는 충분히 되셨을 거에요
그리고 저부분에 tearDown에서 setUp을 호출하길래 저부분이 이상하다고 생각했었어요

2021-04-16 03:37 UTC, O-O-wl commented on Expo1900/Expo1900/ViewControllers/ItemTableViewController.swift
> +        }
실패처리를 Error 또는 Optional 에 대해서 고민해보시고 제임스가 본인의 기준을 세워보면 좋을 것 같아요
하지만 저 부분에서 의문이었던건 
do - catch 를 하셨으니 error를 잡아서 핸들링하실 줄 알았는데 아무 로직이 없어서 의문이 들었어요

2021-04-16 03:37 UTC, O-O-wl commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +    }
해당 메소드의 문서를 읽어보시고 하셨을테니 이해는 충분히 되셨을 거에요
그리고 저부분에 tearDown에서 setUp을 호출하길래 저부분이 이상하다고 생각했었어요

2021-04-16 03:38 UTC, O-O-wl commented
제임스 고생하셨어요
 머지하시고 다음 스탭 진행해보시면서 코멘트해주신 부분 고민해주세요 🙇‍♂️

2021-04-16 03:38 UTC, merged

2021-04-16 03:39 UTC, O-O-wl commented on Expo1900/Expo1900Tests/Expo1900Tests.swift
> +        }
음 저 상태에서 Error를 캐치 해도 실패하지 않을 것 같은데 혹시 확인해보실 수있나요?