[STEP 1] Bobby
yagom-academy/ios-exposition-universelle pull request #68
Opened 2021-04-13 19:14 UTC by Babywalnut

## STEP1 PR
@seizze 

안녕하세요 하이디!! 저번주에 일이생겨서 이제서야 첫 PR을 보내게되어 죄송합니다😭
코드를 작성한 과정에 대해서 설명드리고 간단하게 궁금한 점 및 조언받고 싶은점에 대해 남겨놓겠습니다!

### 📘궁금한 점

처음 코드를 작성할 때 **Assets.xcassets**를 활용하는 법을 몰라 저의 로컬디렉터리의 파일경로를 받아와 사용하는 과정의 코드를 작성하였습니다.
 위의 방식의 메서드와 **Assets.xcassets**를 활용하는 메서드가 모두 **Decoder.swift**에 정의되어있습니다.

여기서 메서드들의 정의를 읽어보면서 그리고 코드의 구조에 대해 의문이 생겼습니다.

1. `private func extractData(_ path: String) throws -> Data`의 String(contentsOfFIle: path)를 통해 해당 파일의 데이터를 추출하는 부분과
`func decodeAssetData<T: Decodable>(_ object: T.Type, _ assetData: NSDataAssetName)`메서드에서 
**NSDataAsset**을 이용하여 **Assets.scassets**디렉터리의 해당파일 데이터를 가져오는 부분이 같은역할이라 생각하는 것과
`private func encodingData(_ data: String) throws -> Data` 메서드가 하는 역할을 42번째줄의 `itemData.data`가 하는 역할로 생각한게 맞는 생각인지 궁금합니다.

2. 디코딩하는 모델을 타입으로 정의하였습니다. 이렇게할 경우 최종적으로 디코딩된 데이터를 사용하려면 메서드에서 해당데이터를 반환값으로 받는 처리를해줘야하는데 이렇게 반환값이 있는 메서드로 코드를 고쳐야할지 아니면 타입안의 메서드가 아닌 전역적으로 디코딩하는 코드를 작성해줘야할지 궁금합니다. 
 
### 📕 조언받고 싶은점

이외에도 피드백주실부분에 대해서 많은 피드백 부탁드립니다 감사합니다!🙈

2021-04-14 13:47 UTC, seizze requested changes
안녕하세요 바비 ☺️ 수고많았어요
이번 PR은 간단해서 피드백 드릴 부분이 많지 않네요~

아래에 질문 주신 부분들에 대한 의견 남겼습니다.

### 1

> private func extractData(_ path: String) throws -> Data의 String(contentsOfFIle: path)를 통해 해당 파일의 데이터를 추출하는 부분과 func decodeAssetData<T: Decodable>(_ object: T.Type, _ assetData: NSDataAssetName)메서드에서 NSDataAsset을 이용하여 Assets.scassets디렉터리의 해당파일 데이터를 가져오는 부분이 같은역할이라 생각하는 것

**파일에서 불러오는 기능**측면에서 같은지 물어보신 거라면, 비슷한 역할인 거 같인 한데 String 타입으로 불러와지는지 Data 타입으로 불러와지는지가 기능적으로 다른 것 같아요.

> private func encodingData(_ data: String) throws -> Data 메서드가 하는 역할을 42번째줄의 itemData.data가 하는 역할로 생각한게 맞는 생각인지 궁금합니다.

이것도 비슷한 역할인 것 같아 보이지만, 수행되는 기능은 좀 다른 것 같아요.
내부 구현은 알 수 없겠지만 `itemData.data`는 이미 Data 타입으로 존재하는 상황에서 그 값에 접근한 거고, encodingData의 기능은 문자열 타입으로 존재하는 상황에서 그 메모리의 데이터를 어떤 방식으로(어떤 인코딩으로) 읽을지 결정하여 접근했다는 점에서 약간 다르지 않을까 하는 생각이 들어요 ㅎㅎ

그런데 같은 역할로 묶으려는 이유도 궁금하네요~~ 저번 프로젝트처럼 추상화하려는 목적인가요? 그렇다면 괜찮은 접근 방향인 것 같아요. 이와 관련해서도 코멘트 남겼으니 확인 부탁 드려요.

### 2

반환값으로 리턴해 줘야 테스트도 가능해지지 않을까요? ㅎㅎ
전역 함수 말씀하시는거라면 그렇게는 보통 잘 작성하지 않습니다~!

2021-04-14 13:47 UTC, seizze commented on Expo1900/Expo1900/ExpoItems.swift
> +    }
CodingKeys 굿굿~~ 💯

2021-04-14 13:47 UTC, seizze commented on Expo1900/Expo1900/ViewController.swift
> +        decoder.decodeAssetData([ExpositionItems].self, "items")
코멘트에서 말씀 주신 것처럼 로컬디렉토리의 경로를 받아와 사용하는 방법보다는, .json 파일을 프로젝트에 직접 추가하고 `Bundle.main....` 이런식으로 접근해서 사용하도록 바꾸는건 어떤가요? 테스트에 필요한 json mock 데이터를 이런 식으로 많이 관리합니다.
현재는 파일을 프로젝트에서 확인할 수 없고 디렉토리에 가봐야 한다는 점이 그다지 좋지 않은 것 같아요.
(물론 Asset으로 관리해도 됩니다.)

2021-04-14 13:47 UTC, seizze commented on Expo1900/Expo1900/Decoder.swift
> +
타입의 이름은 디코더지만 실제론 파일에서 불러오는 역할까지 포함되어 있네요!

제네릭을 활용해 범용적이고 재사용될 수 있도록 신경쓰신 부분은 좋습니다. 👍 
Data 타입을 받아서 디코딩해 반환하는 기능을 하나의 메서드로 만드는 건 어떤가요? 어디서 파일을 불러오는지는 이 타입이 상관하지 않도록 만들면 더 general하게 만들 수 있을 것 같아요.
이렇게 한다면 decodeData와 decodeAssetData는 하나로 합쳐질 것 같아요~~

2021-04-14 13:55 UTC, seizze commented on Expo1900/Expo1900/ViewController.swift
> +        decoder.decodeAssetData([ExpositionItems].self, "items")
앗.. Asset에서 가져오는 메서드를 사용하고 있었네요. 로컬 디렉토리에서 가져오는줄 착각하고 있었어요..
위 코멘트는 반영해도 되고 안해도 됩니다~

2021-04-15 11:35 UTC, Babywalnut commented
## Step1 PR2
@seizze 

안녕하세요 하이디!! ☺️

빠른 리뷰 감사드립니다👍
코멘트를 바탕으로 코드 리팩토링을 진행해봤습니다!!

* Decoder 타입에서 path에 대한 의존성을 없애주었습니다.

* Decoder이전단계 전처리과정에 대한 메서드들은 DataPretreatment타입에 정의해주었습니다.

* Decoder타입 내에서는 디코딩과정에 대한 메서드를 하나로 통일했습니다.

리뷰 부탁드립니다! 감사합니다🙏👍

2021-04-15 13:33 UTC, seizze approved these changes
수고 많으셨습니다~~ 다음 스텝에서 봐요 😉
아래 추가 코멘트도 참고해 주세요~!

제가 드린 피드백은 무조건 그렇게 고치라는 것이 아니고 바비의 의도를 물어보기 위한 것들도 있으니 스레드에 다른 의견이나 질문, 생각같은게 있으면 써주면 좋을 것 같아요~

2021-04-15 13:33 UTC, seizze commented on Expo1900/Expo1900/DataPretreatment.swift
> +class DataPretreatment {
"데이터 전처리"라는 뜻인가요? ㅎㅎ
약간 어색하게 느껴지는데 보통 컴퓨터 쪽에서는 preprocessing을 더 많이 쓰는것 같아요.

2021-04-15 13:33 UTC, seizze commented on Expo1900/Expo1900/Decoder.swift
> +    func decodeData<T: Decodable>(_ object: T.Type, of data: Data) -> T?{
메서드를 작성할 땐 매개변수의 순서도 중요합니다. "데이터를 타입 T로 디코딩한다" 이 말을 잘 표현하기 위해서 아래 시그니쳐가 더 읽기 편할 것 같은데 어떤가요?
```swift
func decode<T: Decodable>(data: Data, to type: T.Type) -> T?
```

2021-04-15 13:33 UTC, seizze commented on Expo1900/Expo1900/ViewController.swift
> +        decoder.decodeData([ExpositionItems].self, of: dataManager.data)
인스턴스의 참조를 유지할 필요갸 없다면 아래와 같이 쓰면 더 간결해질 수 있습니다.
```swift
Decoder().decodeData(...)
```

2021-04-15 13:33 UTC, merged

2021-04-15 16:52 UTC, Babywalnut commented on Expo1900/Expo1900/DataPretreatment.swift
> +class DataPretreatment {
넵ㅎㅎ 수정하겠습니다!!

2021-04-15 16:53 UTC, Babywalnut commented on Expo1900/Expo1900/ViewController.swift
> +        decoder.decodeData([ExpositionItems].self, of: dataManager.data)
이해했습니다! 참고하여 반영해보겠습니다!