만국박람회 [Step2] EHD, Hosinging
yagom-academy/ios-exposition-universelle pull request #94
Opened 2021-07-13 04:55 UTC by Hosinging

안녕하세요. 라자냐~! Step2에 필요한 내용을 충분히 공부해보고 PR보냅니다.
잘 부탁드립니다.

진행하면서 궁금하거나 고민했던 점은 아래와 같습니다.

1. 알 수 없는 문제
팀원들간에 같은 파일로 빌드를 했는데 첫번째 화면의 UI에서 Second Title이 누구는 전체가 잘 보이고 누구는 잘려서 보이는데 해결을 못했습니다.시뮬레이터에 사용된 디바이스 종류는 같고 ios버전이 14.4, 14.5 로 각각 달랐는데 혹시 이것이 iOS 버전 문제인 건지 아니면 저희가 제약에서 무언가를 빼먹고 안해준 건지 알고 싶습니다.

2. 스크롤뷰 컨텐츠 길이에 따른 높이 제약 관련
스크롤 뷰에서 컨텐츠 높이에 따라 자동으로 스크롤뷰 안에 추가한 뷰가 늘어날 수 있게 하는 것은 뷰의 Height Priority값 조정과 각 객체들의 적절한 제약 추가가 되어있고, 상황에 따라 뷰 안의 객체들의 Content Hugging Priority, Content Compression Resistance Priority 를 조정해주면 되는 것인지 궁금합니다. 저희는 맨처음에 뷰의 고정된 높이 값을 길게 주고, 각 객체들간 제약을 고정으로 준다음 늘어나야되는 부분이 있을 경우 Relation을 Greater than or Equal로 지정을 해줬었는데요. 중간 중간 디바이스별로, 또는 어떤 알 수 없는 문제로 생각했던 제약대로 뷰가 나오지 않아 애를 먹었습니다. 컨텐츠 길이에 따라 자동으로 조정을 해주는 방법을 검색해보니 contentView의 역할을 하는 뷰의 heigt의 Priority를 조정해주면 되는 것으로 나왔었고 그렇게 했더니 길게 표시될 내용은 나오지만, 일부 잘리는 객체가 발생해서 Content Hugging Priority, Content Compression Resistance Priority로 조정을 해주고 해결을 했습니다. 해볼 수 있는 대로 해봤는데, 적절한 조치였는지 궁금합니다. 
 
3. 스크롤뷰 vs 테이블뷰
스크롤 뷰는 테이블 뷰와 컬렉션 뷰로 사용이 어려울 경우 마지막에 사용을 고려해보라고 본적이 있어서, 사실 스크롤 뷰를 사용하지 않으려고 했었지만, 경험을 해볼 필요가 있다고 판단해서 메인 화면은 스크롤 뷰로, 마지막 아이템 디테일화면은 테이블 뷰로 구현을 해봤습니다.
현업에서는 이 두 뷰에 대해서 어떻게 생각하고, 상황에 따라 구현은 달라지겠지만 어느 상황에서는 꼭 이것이다.와 같은게 있는지 궁금합니다.
(테이블뷰와 컬렉션뷰가 스크롤 뷰에서 가능한 모든 역할을 다하고 남는다고 생각이 들어서요...)

4. 마지막 디테일 화면에서 스크롤뷰로도 구현할 수 있겠지만, 기본적으로 스크롤이 가능한 테이블뷰로 구현을 해봤습니다. 테이블뷰의 데이터 소스에 표시되는 섹션안의 로우가 1개이기 떄문에 매직넘버를 없애는 차원에서 프로퍼티나 상수, 변수에 담았다가 넣어줄까, 계산프로퍼티같은것을 만들어서 접근했을 때 1을 리턴하게 해줄까...그냥 리턴을 해줄까 하다가 1을 리턴해주는 것으로 정리해봤는데 이 부분의 해결이 마음에 걸립니다 ㅎㅎ 적절한 해결로는 어떤 방법이 있을지 궁금합니다.

2021-07-13 11:49 UTC, wonhee009 requested changes
<img width="554" alt="image" src="https://user-images.githubusercontent.com/30456206/125439982-d97cdadf-f876-4252-b4eb-71942a926fd8.png">
출품작 리스트 들어갔다 뒤로 돌아오면 네비게이션바가 생겨버려요ㅠ_ㅠ
이 부분 확인 부탁드립니다!

> 1. 알 수 없는 문제

**잘려서 보이는데 해결을 못했습니다.** 어떻게 잘려서 보이는지 알 수 있을까요?

> 2. 스크롤뷰 컨텐츠 길이에 따른 높이 제약 관련

이 부분도 어떤 view에서의 문제였는지 알 수 있을까요?

> 3. 스크롤뷰 vs 테이블뷰

**(테이블뷰와 컬렉션뷰가 스크롤 뷰에서 가능한 모든 역할을 다하고 남는다고 생각이 들어서요...)** 이 부분은 table/collectionView가 스크롤이 되면서 다른 부가적인 기능들이 있어서 그렇게 생각하신거 같아요!
음.... 제 생각은 table/collectionView가 어떤식으로 동작하는지를 보면 어느정도 답이 나올거 같아요.
table/collecionView는 왜 cell을 등록하고 등록된 cell을 재사용하는지 생각해보면 도움이 되실거 같아요!

> 4. 데이터 소스에서 리턴하는 row의 값 관련

지금의 방법도 괜찮은거 같은데요.
뭔가 마음에 걸린다면 rowCount(예시)라는 프로퍼티를 VC에 선언해서 사용하는 방법도 하나의 방법이 도리 수 있을거 같아요.

> 5. Error Handling

우선 Result의 예시는 봐보셨나요?
[Result 공식 문서](https://developer.apple.com/documentation/swift/result/writing_failable_asynchronous_apis)를 보면 이런 예시 article이 있습니다!
[Swift 공식 문서](https://docs.swift.org/swift-book/LanguageGuide/ErrorHandling.html)에서 Error Handling은 이렇게 소개하고 있고요!

2021-07-14 05:20 UTC, Brian2931 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        try? obtainExpositionData()
아 그부분은 생각하지 못했네요! 반영해보겠습니다.

2021-07-14 05:46 UTC, Brian2931 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    }
Data parsing 하는 obtainExpositionData()와 UI요소를 세팅해주는 setMainViewUIComponents() 를 분리해주었습니다!

2021-07-14 05:49 UTC, Brian2931 commented on Expo1900/Expo1900/Controller/ListTableViewController.swift
> +}
반영해보았습니다.

2021-07-14 05:54 UTC, Brian2931 commented on Expo1900/Expo1900/Controller/ItemTableViewController.swift
> +class ItemTableViewController: UITableViewController {
스크롤 뷰는 테이블 뷰와 컬렉션 뷰로 사용이 어려울 경우 마지막에 사용을 고려해보라고 본적이 있어서, 사실 스크롤 뷰를 사용하지 않으려고 했었지만, 경험을 해볼 필요가 있다고 판단해서 메인 화면은 스크롤 뷰로, 마지막 아이템 디테일화면은 테이블 뷰로 구현을 해봤습니다.

2021-07-14 05:55 UTC, Brian2931 commented on Expo1900/Expo1900/Controller/ItemTableViewController.swift
> +import UIKit
반영했습니다.

2021-07-14 07:10 UTC, Hosinging commented on Expo1900/Expo1900/Controller/ItemTableViewController.swift
> +    var itemDescription: String?
Entry(구 Item, 현 Entry) 타입 자체를 넘겨주고, 받는 것도 생각을 해봤습니다. 
기능 상세에 있는 부분만 보고 맞춰서 하기에는 표시해줘야하는 항목이 많지 않고, 확장성에 대한 부분을 배제하고했던 것 같습니다. 그래서 프로퍼티로 각각 전달하고, 전달받는 것이 효율적이라고 생각하고 작성했었던 것 같습니다. 

1. 라쟈냐의 리뷰대로 Entry타입을 넘겨주고, 받아서 해당 값을 표시해주는 형태로 변경해봤는데요.
UIImage(named:)로 에셋을 가져오는 부분을 제외하고는 옵셔널 체이닝으로 각각의 값을 표시해 줄 수 있었고, UIImage(named:)로 에셋을 가져오는 부분의 경우에는 옵셔널 바인딩을 통해 그 값을 벗겨서 사용했습니다.
이렇게 하는 것이 적절했는지 궁금합니다.

2. 확장성을 고려했을 때 옵셔널 Entry를 바인딩해주는 것을 함수화 해서 함수의 리턴값을 이용한 방식으로도 해볼 수 있을 것 같았지만, 옵셔널 바인딩이 필요한 부분이 UIImage부분 하나여서 일단 그 방식은 배제를 하고 해봤습니다. 
좀 더 많은 UI요소에 값을 표시해줘야하는 경우 Entry타입을 받아서 하는 것은 변함이 없겠지만, 그 값을 표시해주는 방식을 이렇게 옵셔널 바인딩을 해줘서 옵셔널 타입을 논옵셔널 타입으로 만들어주고 그 프로퍼티를 활용하는 것이 적절할까요?

2021-07-14 07:13 UTC, Hosinging commented on Expo1900/Expo1900/Controller/ListTableViewController.swift
> +    private var items: [Item] = []
직관적인 네이밍으로 반영했습니다.

2021-07-14 08:14 UTC, Hosinging commented on Expo1900/Expo1900/Controller/ListTableViewController.swift
> +            print(String(describing: error))
catch문 안에서 실패했을 경우 에러를 전달할 수 있게 해주었습니다.

2021-07-14 08:18 UTC, Hosinging commented on Expo1900/Expo1900/Controller/ListTableViewController.swift
> +        return cell
네 맞습니다. 일반적으로 이렇게 tableView(_:cellForRowAt:)메소드 내에서 셀을 디자인 하는 것으로 알고 있고, 활동학습 시간이나 UIKit튜토리얼에서도 그렇게 봤어서 이렇게 해봤습니다. 저희가 테이블뷰가 익숙하지 않아서 라쟈냐가 말씀하신 내용이 정확히 어떤 것을 의미하는지 잘 모르겠습니다. 혹시 키워드나 예시가 될 수 있는 내용을 보여주실 수 있으실까요?

2021-07-14 11:08 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        try? obtainExpositionData()
변경 사항 확인했는데 `print`로 에러를 출력해주고 있는데 사용자가 에러를 알 수 있을까요?

2021-07-14 11:33 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/ListTableViewController.swift
> +        return cell
- cell
```swift
func bindCell(item: Entry) {
   ...UI setting
}
```

- VC
``` swift
func tableView(_: cellForRowAt:) {
   ...
   cell.bindCell(item: entry)
   ...
}
```

이런 느낌으로 말씀 드렸어요!

2021-07-14 12:36 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/ItemTableViewController.swift
> +    var itemDescription: String?
이 부분은 기획에 따라 다를거 같아요.
뭔가 nil을 허용하는 타입이 있을 수도 있죠. nil을 허용하고 nil일 경우에는 placeholder를 줘야할때도 있을거 같고요.

2021-07-14 12:50 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/ItemTableViewController.swift
> +class ItemTableViewController: UITableViewController {
혹시 스크롤뷰는 마지막에 고려해보라는 얘기는 어디서 들은 얘기인가요? (링크 있으면 궁금해서요!) 제가 질문 드렸던 이유는 cell register를 하나의 cell만 하고 있는데 tableView를 사용하는게 맞을까라는 생각이 들어서요!
호시잉과 에드의 의견은 어떤가요?

2021-07-14 13:12 UTC, wonhee009 requested changes
한국의 출품작 리스트 갔다오면 메인의 네비게이션 바가 다시 보이는데 이 부분 확인 부탁드려요🙏

2021-07-14 13:12 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    private func obtainExpositionData() throws -> Exposition {
요로 viewController에서`obtainExpositionData()`가 동일한 역할을 하고 있는거 같아요.
이 부분을 viewCtontroller에서 공통으로 사용할 수 있도록 개선할 수 있을까요?

2021-07-15 11:22 UTC, Hosinging commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        try? obtainExpositionData()
Alert를 추가해주는 것이 방법일 수 있다고 생각하는데, 기능상세서 상에 사용자에게 오류를 보여주는 화면이 없었기 때문에 개발하는 저희가 에러를 볼 수 있게 print로 처리했습니다.

2021-07-15 11:26 UTC, Hosinging commented on Expo1900/Expo1900/Controller/ItemTableViewController.swift
> +class ItemTableViewController: UITableViewController {
저희도 그렇게 생각을 했었습니다. 테이블뷰를 배운지 얼마안됐고 배운것을 활용해보고자 한번 사용해봤습니다.

2021-07-15 11:31 UTC, Hosinging commented on Expo1900/Expo1900/Controller/ItemTableViewController.swift
> +    var itemDescription: String?
'nil일 경우 placeholder를 줘야할 때도 있을 것 같고요.'라고 말씀해주신 부분에서 placeholder라는 단어가 여러 곳에서 동일한 이름으로 사용되기 때문에 조금 혼란스럽습니다. 
제네릭에서 T나 U와 같은 것들을 placeholder라고 표현하기도하고, 텍스트필드에서 값을 입려하기 전에 보여지는 내용도 placeholder라고 하고..
말씀하시는 placeholder는 어떤 것을 의미하는지 예시를 들어주실 수 있으실까요?

2021-07-15 11:44 UTC, Hosinging commented on Expo1900/Expo1900/Controller/ListTableViewController.swift
> +        return cell
ListTableViewCell과 ItemTableViewCell에서 공통으로 사용하는 메소드를 만들어보려다가 보여지는 내용이 달라서 각 각의 셀 파일에 configure()메소드를 만들어서 해당 메소드를 ListTableViewController와 ItemTableViewController의 data Source의 tableView(_:cellForRowAt:)메소드에서 호출할 수 있게 해주었습니다.

2021-07-15 11:58 UTC, Hosinging commented
> 한국의 출품작 리스트 갔다오면 메인의 네비게이션 바가 다시 보이는데 이 부분 확인 부탁드려요🙏

이 부분은 코멘트 다는 부분이 없어서 여기에 코멘트 남깁니다. viewWillAppear(animated:)메소드에서 네비게이션바 히든을 해주도록 조치했습니다.

2021-07-15 12:07 UTC, Hosinging commented on Expo1900/Expo1900/Controller/ItemTableViewController.swift
> +        }
전 화면에서 데이터 파싱이 문제 없이 되었다면 전달해주는 것에서 nil이 들어올 일은 없지 않을까 생각합니다. 
데이터 파싱에서 문제가 생겨서 데이터 전달이 되지 않았다면, 빈 화면이 보여질 것이라고 생각은 되지만, 이럴 때 라이프 사이클 메소드에서 데이터가 비어있으면 alert를 띄워주는 식으로 조치를 할 수 있을 거라고 생각합니다. 
이 역시 기능 상세서에 명시되어있지 않았던 내용이라서 따로 조치를 취하지 않았었습니다.

2021-07-15 12:12 UTC, Hosinging commented on Expo1900/Expo1900/Controller/ListTableViewController.swift
> +                break
저희 역시 alert가 기능상세에 있었다면 그런 식으로 사용자에게 알려줄 수 있었을 것 같습니다. 
기능상세에 사용자에게 알리는 부분이 없었기 때문에 저희가 에러를 확인하고자 print를 사용해봤습니다.

2021-07-15 12:16 UTC, Hosinging commented on Expo1900/Expo1900/Controller/ListTableViewController.swift
> +            return
데이터 파싱에 성공했을 때 그 값을 success에 담아서 전달하고, 메소드 호출 시점에 해당 값을 활용하는 것으로 작성을 해봤는데 Result타입을 사용하지 않았다라고 하신 말씀이 어떤 말씀이신지 조금 풀어서 설명해주실 수 있을까요?

2021-07-15 12:23 UTC, Hosinging commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        guard let dataAsset: NSDataAsset = NSDataAsset(name: "exposition") else { fatalError() }
fatalError()에 대해서 확인해봤습니다. 문제가 될 수 있는 부분이 있음을 인지하고, ImportAssetDataError타입을 만들고 해당 에러를 던질 수 있게 수정했습니다.

2021-07-15 12:25 UTC, Hosinging commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    private func obtainExpositionData() throws -> Exposition {
질문을 잘 이해못했습니다. ㅠㅠ 조금만 풀어서 다시 한번 말씀해주실 수 있을까요?

2021-07-15 13:10 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +        try? obtainExpositionData()
이 부분은 다음 스텝에서 고려해봐도 좋을거 같아요!😀

2021-07-15 13:19 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/ItemTableViewController.swift
> +class ItemTableViewController: UITableViewController {
호싱잉이나 에드처럼 학습한 것을 활용하고 싶어서 테이블뷰를 사용할 수 있다고 생각해요.
다만, 오토레이아웃에 익숙하지 않을 때에는 스크롤뷰를 나중에 생각해보라는 것은 공감이 조금 힘든거 같아요.😅

호싱잉과 에드가 왜 테이블뷰를 사용했는지는 이해했습니다.

2021-07-15 13:21 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/ItemTableViewController.swift
> +        }
> 전 화면에서 데이터 파싱이 문제 없이 되었다면 전달해주는 것에서 nil이 들어올 일은 없지 않을까라고 생각을 해봤습니다.

저는 최대한 모든 케이스에 대응하자는 주의라서 말씀 드렸습니다!
alert을 띄워줄 수도 있을거 같고, placeholder 같이 기본 이미지, 텍스트를 활용할 수도 있을거 같아요.

이 부분은 다음 스텝에서 고민해도 될 것 같습니다!

2021-07-15 13:22 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/ListTableViewController.swift
> +                break
현업처럼 하게 된다면 에러가 발생했다는 것을 사용자에게 알리는게 맞다고 생각하여 의견을 드렸습니다!
이 부분은 다음 스텝에서 고민해봐도 될 것 같습니다.

2021-07-15 13:30 UTC, wonhee009 requested changes

2021-07-15 13:30 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/ListTableViewController.swift
> +            return
앗 이 부분은 제가 리뷰를 잘못 남겼네요 죄송합니다.🥲
제가 의도했던 부분은 json asset을 가져오지 못할 경우 return을 해주고 있는데 결국 이 부분도 디코딩에 실패한 케이스라고 생각했고, 에러를 던져줘야하지 않나 생각했습니다.

2021-07-15 13:30 UTC, wonhee009 commented on Expo1900/Expo1900/Controller/MainViewController.swift
> +    private func obtainExpositionData() throws -> Exposition {
`ListTableViewController`와 `MainViewController`에 `obtainExpositionData()` 메서드가 동일한 이름, 동일한 역할(데이터 파싱)을 하고 있는거 같아요!
하나의 `obtainExpositionData()`를 정의하고 `ListTableViewController`와 `MainViewController`에서 해당 메서드를 호출하도록 개선할 수 있을까요?

2021-08-25 08:24 UTC, closed without merging