만국박람회 [STEP 2] Marco, Soll, Yescoach
yagom-academy/ios-exposition-universelle pull request #97
Opened 2021-07-13 15:44 UTC by Keeplo

@jungseungyeo 

@soll4u @Yescoach @keeplo

안녕하세요 린생 🤠

먼저 항상 찾아와서 질문도 받아주시고 감사합니다
그와중에도 궁금한게 더 생기기도 했고 Step1에서 UML 피드백 해주신점, Model Decodable init() 구현관련 피드백 
수정해보았구요. Step2를 구현하고 PR 날려봅니다
잘 부탁드립니다

## 고민되었던 점 🤯
* **viewDidLoad에 구현된 기능 분리?!**
~~~swift
// 분리 전
override func viewDidLoad() {
        super.viewDidLoad()
        
        numberFormatter.numberStyle = .decimal
        
        let jsonDecoder = JSONDecoder()
        guard let dataAsset = NSDataAsset(name: expositionDataIdentifier) else {
            return
        }
        do {
            self.exposition = try jsonDecoder.decode(Exposition.self, from: dataAsset.data)
        } catch {
            print(error.localizedDescription)
        }
 }
// 분리 후
override func viewDidLoad() {
        super.viewDidLoad()
        
        numberFormatter.numberStyle = .decimal
        분리된함수()
}
func 분리된함수() {
        let jsonDecoder = JSONDecoder()
        guard let dataAsset = NSDataAsset(name: expositionDataIdentifier) else {
            return
        }
        do {
            self.exposition = try jsonDecoder.decode(Exposition.self, from: dataAsset.data)
        } catch {
            print(error.localizedDescription)
        }
}
~~~
위 코드처럼 viewDidLoad에서 구현된 JSON 데이터 바인딩 부분을 다른 함수로 분리 시키는 점이 꼭 필요한가 고민했습니다.
분리한 것과 안한 것에 큰 차이는 없는지 궁금합니다.
* **String 데이터 변수 선언**
~~~swift
class ViewController: UIViewController {
// ...
private let cellIdentifier = "EntryCell"
private let entryDataIdentifier = "items"
// ...
}
~~~
json 파일명이나 identifier의 이름 등 코드에서 "문자열" 작성하는 부분 관리를 위해 전역 상수를 작성해보았는데 
현재처럼 사용하는게 좋은지 아니면 문자열 관리하는 방법이 있는지 궁금합니다~
* **Label에 문자열 데이터 넣을때**
JSON 파일에서 바인딩된 모델에 저장된 옵셔널 프로퍼티를 Label.text 에 바로 넣어주는 형태의 구현이 (오류는 없는데)
데이터 처리 없이 넣어도 되는지 궁금합니다.

## 궁금한점 
* **// MARK: -- 의 사용방법**
주석처리를 이용한 문서화 하는 방법이라거나 특별한 컨벤션이 있는지 궁금합니다.

## 피드백 받고 싶은 부분 😹
* **프로토콜 채택 및 준수 하는 구현부를 extension으로 분리**
~~~swift
class ViewController: UIViewController {
// ...
}
extension ViewController: UITableViewDataSource {
// ... 
}
~~~
위 코드처럼 말꼬가 주장해서 분리했는데 이렇게 분리해서 작성하는 부분을 나누는게 옳은 방법인지, 괜찮다면 특별한 효과가 무엇인지
명확하게 이해하지 못했습니다. 이런 부분에 관해 궁금합니다
* **화면전환 시 값 전달**
Entry 인스턴스를 가지고 있는 테이블 뷰에서 셀이 선택 되었을 때 내용을 보여주는 화면으로 전환될때 
값을 전달 해주는 데, 전달해주는 데이터를 인스턴스 단위로 (Entry 인스턴스) 전달하는게 좋은지 
~~~swift
class EntryDetailViewController: UIViewController {
    var entryTitle: String?
    var entryImageName: String?
    var entryDescription: String?
}
~~~
위 코드처럼 필요한 데이터만 프로퍼티를 생성하고 전달하는게 좋은지 궁금합니다!
저희는 사용되지 않는 shortDescription 프로퍼티가 있어서 위코드처럼 구현해 보았습니다.
* **접근제어자 관련**
접근 제어자에 관련한 기본적인 이해는 했는데, 실제로 구현할 때 Model이외에 ViewController에서도 적용하는게 맞을지 궁금합니다.
제어자를 설정하는 팁으로 일단 private를 모두 주고 필요하면 하나씩 접근 수준을 낮춰 주는 형태로 구현하라는 정보도 있어서 그런 형태로구현해보았는데 이런점에서 구현하는 방법이 궁금합니다.

2021-07-14 14:52 UTC, jungseungyeo reviewed
위 코드처럼 viewDidLoad에서 구현된 JSON 데이터 바인딩 부분을 다른 함수로 분리 시키는 점이 꼭 필요한가 고민했습니다.
분리한 것과 안한 것에 큰 차이는 없는지 궁금합니다.

> 분리하는게 좋아요! 기능 단위로 함수를 만들어야 테스트가 가능하다는걸 잊지 마세요!

json 파일명이나 identifier의 이름 등 코드에서 "문자열" 작성하는 부분 관리를 위해 전역 상수를 작성해보았는데 현재처럼 사용하는게 좋은지 아니면 문자열 관리하는 방법이 있는지 궁금합니다~

> cell의 identifier는 cell 내부에 두는 것이 좋은거 같아요!
```swift
class TableViewCell: UITableViewCell {
    static let registerID: String = "\(TableViewCell.self)"
}
```
JSON 파일에서 바인딩된 모델에 저장된 옵셔널 프로퍼티를 Label.text 에 바로 넣어주는 형태의 구현이 (오류는 없는데) 데이터 처리 없이 넣어도 되는지 궁금합니다.

> 옵셔널 바인딩을 하지 않고 넣으면 optional(value)로 표시 되지 않나요?

// MARK: -- 의 사용방법
주석처리를 이용한 문서화 하는 방법이라거나 특별한 컨벤션이 있는지 궁금합니다.

>  크게 없는데 protocol을 채택하는 경우 써주는 편입니다! :) 

위 코드처럼 말꼬가 주장해서 분리했는데 이렇게 분리해서 작성하는 부분을 나누는게 옳은 방법인지, 괜찮다면 특별한 효과가 무엇인지 명확하게 이해하지 못했습니다. 이런 부분에 관해 궁금합니다

> 이건 코드 스타일인거 같아요! 특별히 규칙이 있는건 아니지만 기능 단위로 분리를 하고 싶을 때 많이 사용이 됩니다. 

Entry 인스턴스를 가지고 있는 테이블 뷰에서 셀이 선택 되었을 때 내용을 보여주는 화면으로 전환될때
값을 전달 해주는 데, 전달해주는 데이터를 인스턴스 단위로 (Entry 인스턴스) 전달하는게 좋은지

> Entry를 전달하는게 좋아요! entry를 넘겨주지 않으면 model이 없어지는거 같아요! 

위 코드처럼 필요한 데이터만 프로퍼티를 생성하고 전달하는게 좋은지 궁금합니다!
저희는 사용되지 않는 shortDescription 프로퍼티가 있어서 위코드처럼 구현해 보았습니다.

> 필요한 값만 전달하는것 보다는 model class를 전달하는게 좋은거 같아요! 데이터 은닉화와 의존성 관점에서 생각해보면 좋을거 같아요!

접근 제어자에 관련한 기본적인 이해는 했는데, 실제로 구현할 때 Model이외에 ViewController에서도 적용하는게 맞을지 궁금합니다.
제어자를 설정하는 팁으로 일단 private를 모두 주고 필요하면 하나씩 접근 수준을 낮춰 주는 형태로 구현하라는 정보도 있어서 그런 형태로구현해보았는데 이런점에서 구현하는 방법이 궁금합니다.

> 모든 객체에 접근제어자를 붙여주세요! 이것을 접근할때 풀어주고 사용하는게 좋습니다! 

Marco, Soll, Yescoach 정말 고생하셨어요! 몇가지 몇가지 수정 사항만 적용하면 좋을거 같아요!
특히 delegate를 꼭 채택하여 작성해주면 좋을거같아요!

2021-07-14 14:52 UTC, jungseungyeo commented on Expo1900/Expo1900/Model/Entry.swift
> +        self.name = try? container.decode(String.self, forKey: .name)
👍

2021-07-14 14:52 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        let jsonDecoder = JSONDecoder()
따로 함수로 분리하여 만들면 좋을거 같아요! 결과 값을 클로저 또는 Result를 사용하면 좋을거같아요!

```swift
func fetch(_ complite: (Result<[Entry], Error>) -> Void) { }
```

2021-07-14 14:52 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        guard let nextViewController = segue.destination as? EntryDetailViewController else {
tableVIew의 delegate를 채택하여 사용하면 좋을거같아요! 채택하고 안하고의 차이점이 무엇일까요?

2021-07-14 14:52 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        nextViewController.entryTitle = entries[index].name
캡슐화를 지켜주세요! 값을 주입하고 내부에서 binde하면 좋을거같아요!

2021-07-14 14:52 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        cell.entryImageView.image = UIImage(named: entry.imageName ?? "")
여기도 캡슐화를 지켜주세요! 내부에서 configure함수를 만들어서 하면 좋을거같아요!

2021-07-14 14:52 UTC, jungseungyeo commented on Expo1900/Expo1900/Model/Exposition.swift
> +    init(from decoder: Decoder) throws {
👍

2021-07-14 14:52 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        let entry = self.entries[indexPath.row]
indexPath.row의 값이 배열이 없는 경우 크래시가 발생하지 않을까요? 배열의 값이 indexPath.row 값 보다 작은걸 보장이 되는 걸까요?

2021-07-14 14:52 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/ExpositionViewController.swift
> +        didSet {
너무 좋아요! mvc 패턴에서 옵저버를 붙어주는 부분을 잘 적용하셨네요! 👍

2021-07-14 14:52 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/ExpositionViewController.swift
> +        guard let stringNumber = numberFormatter.string(from: NSNumber(value: (exposition?.visitors)!)) else {
강제 업레핑은 하지 말아주세요!

2021-07-16 01:58 UTC, jungseungyeo requested changes

2021-07-16 01:58 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> -    private let entryDataIdentifier = "items"
삭제해주셨네요! 너무 좋아요!

2021-07-16 01:58 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +extension EntryListViewController: UITableViewDelegate {
너무 좋아요! delegate를 채택하여 보다 코드 읽기가 수월해졌네요!

2021-07-16 01:58 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        detailVC.entry = entries[indexPath.row]
이렇게 넣어주면 캡슐화가 안되어 있는거 같아요! 
변수를 직접 접근해서 넣어주는 것 보다는 주입을 받는 함수를 이용하면 좋을거같아요!

```swift
func updateModel(_ entry: entrees[index{Path.row])
```

만들면 더욱 좋을거같아요!

2021-07-16 01:58 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    var entry: Entry?
private를 해주면 좋을거같아요!

2021-07-16 02:48 UTC, soll4u commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        let entry = self.entries[indexPath.row]
빈 배열일 경우 `dequeueReusableCell(identifier:for:)` 메서드가 셀 인스턴스 생성을 못하고 `UITableViewCell()`을 반환하면서 에러가 나지 않았습니다.
위에 말씀드린 정도로 밖에 이해를 못했습니다. `indexPath`의 원리는 잘 모르겠어요. 
다음에 설명해주실 수 있을까요? :)

2021-07-16 02:49 UTC, soll4u commented on Expo1900/Expo1900/Controller/EntryListViewController.swift
> +        detailVC.entry = entries[indexPath.row]
말씀하신 내용과 아래 은닉화 피드백 참고해서 push했습니다
확인 부탁드립니다 !!

2021-07-17 10:24 UTC, jungseungyeo approved these changes
말꼬, 솔, 예스코치! 너무 고생하셨어요!

step2에서 데이터 은닉화도 잘 지켜주고 정보 전달도 잘해주셨어요! 
특히 model에서 didSet으로 옵저버를 붙여준 것도 너무 좋아요!

코드에서 얼마나 mvc 패턴을 지켜줄려고 했는지 느껴지네요!

2021-07-17 10:24 UTC, jungseungyeo commented on Expo1900/Expo1900/Controller/EntryDetailViewController.swift
> +    static func updateModel(by entry: Entry) -> EntryDetailViewController? {
함수명이 instance였으면 더좋았는데 사용성 측면에서 너무 좋아요!

2021-07-17 10:25 UTC, merged